package co0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.a3;
import pz0.g3;
import pz0.h50;
import pz0.ha0;
import pz0.hm;
import pz0.i3;
import pz0.jx;
import pz0.k3;
import pz0.mv;
import pz0.n30;
import pz0.ny;
import pz0.o7;
import pz0.pd;
import pz0.py;
import pz0.su;
import pz0.td;
import pz0.vd;
import pz0.w0;
import pz0.wk;
import pz0.xd;
import pz0.y90;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class a {
    public static final List a;

    static {
        td.Companion.getClass();
        x xVar = td.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        x xVar2 = xd.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar2 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.a.a;
        List r3 = x61.l.r(new s[]{mVar2, no.a.c(list, "selections", "Actor", r2, list)});
        aa.m mVar3 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar4 = new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ny.Companion.getClass();
        aa.m mVar5 = new aa.m("owner", l0.b(ny.e), (String) null, rVar, rVar, r3);
        py.Companion.getClass();
        a0 a0Var = py.s;
        k71.k.g(a0Var, "type");
        List r4 = x61.l.r(new aa.m[]{mVar3, mVar4, mVar5, new aa.m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar6 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        x xVar3 = vd.a;
        aa.m mVar7 = new aa.m("runNumber", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        y90.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{mVar6, mVar7, new aa.m("workflow", l0.b(y90.e), (String) null, rVar, rVar, r5), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar8, new aa.m("logoUrl", l0.b(h50.a), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar9 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        mv.Companion.getClass();
        q0 q0Var = mv.e;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("branch", q0Var, (String) null, rVar, rVar, r);
        pd.Companion.getClass();
        x xVar4 = pd.a;
        aa.m mVar11 = new aa.m("rerunnable", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        jx.Companion.getClass();
        aa.m mVar12 = new aa.m("repository", l0.b(jx.t0), (String) null, rVar, rVar, r4);
        ha0.Companion.getClass();
        q0 q0Var2 = ha0.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar13 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r6);
        w0.Companion.getClass();
        q0 q0Var3 = w0.a;
        k71.k.g(q0Var3, "type");
        List r8 = x61.l.r(new aa.m[]{mVar9, mVar10, mVar11, mVar12, mVar13, new aa.m("app", q0Var3, (String) null, rVar, rVar, r7), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar), new aa.m("hasPreviousPage", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        s mVar14 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0.n("CheckStep");
        List list2 = wn0.a.a;
        List r10 = x61.l.r(new s[]{mVar14, no.a.c(list2, "selections", "CheckStep", n, list2)});
        aa.m mVar15 = new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        hm.Companion.getClass();
        aa.m mVar16 = new aa.m("pageInfo", l0.b(hm.a), (String) null, rVar, rVar, r9);
        g3.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar15, mVar16, new aa.m("nodes", l0.a(g3.a), (String) null, rVar, rVar, r10)});
        s mVar17 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("CheckRun");
        List list3 = wn0.f.a;
        s c = no.a.c(list3, "selections", "CheckRun", n2, list3);
        k3.Companion.getClass();
        s mVar18 = new aa.m("checkSuite", l0.b(k3.f), (String) null, rVar, rVar, r8);
        i3.Companion.getClass();
        q0 q0Var4 = i3.a;
        k71.k.g(q0Var4, "type");
        a3.Companion.getClass();
        List r13 = x61.l.r(new s[]{mVar17, c, mVar18, new aa.m("steps", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(a3.c, new u0(new t("afterSteps"))), new aa.k(a3.d, new u0(new t("first")))}), r12)});
        aa.m mVar19 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar20 = new aa.m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar21 = new aa.m("description", xVar2, (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        aa.m mVar22 = new aa.m("createdAt", l0.b(o7.a), (String) null, rVar, rVar, rVar);
        n30.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{mVar19, mVar20, mVar21, mVar22, new aa.m("state", l0.b(n30.s), (String) null, rVar, rVar, rVar)});
        s mVar23 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s nVar = new aa.n("CheckRun", d0.n("CheckRun"), r13);
        List n3 = d0.n("StatusContext");
        List list4 = wn0.e.a;
        List r15 = x61.l.r(new s[]{mVar23, nVar, no.a.c(list4, "selections", "StatusContext", n3, list4), new aa.n("RequiredStatusCheck", d0.n("RequiredStatusCheck"), r14), new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        wk.Companion.getClass();
        j0 j0Var = wk.a;
        k71.k.g(j0Var, "type");
        su.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(su.i, new u0(new t("id"))), r15), new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
