package co0;

import a81.t;
import aa.a0;
import aa.j0;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.a3;
import pz0.c3;
import pz0.e3;
import pz0.g1;
import pz0.ha0;
import pz0.k3;
import pz0.pd;
import pz0.su;
import pz0.td;
import pz0.vd;
import pz0.wk;
import pz0.xd;
import pz0.y2;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class f {
    public static final List a;

    static {
        vd.Companion.getClass();
        x xVar = vd.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        List n = d0Shadow.n(new aa.m("totalCount", b, (String) null, rVar, rVar, rVar));
        xd.Companion.getClass();
        x xVar2 = xd.a;
        s mVar = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        x xVar3 = td.a;
        s mVar2 = new aa.m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        List n2 = d0Shadow.n("WorkflowRun");
        List list = wn0.c.a;
        List r = x61.l.r(new s[]{mVar, mVar2, no.a.c(list, "selections", "WorkflowRun", n2, list)});
        s mVar3 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("CheckRun");
        List list2 = wn0.f.a;
        List r2 = x61.l.r(new s[]{mVar3, no.a.c(list2, "selections", "CheckRun", n3, list2), new aa.m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.m mVar4 = new aa.m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar);
        a3.Companion.getClass();
        List r3 = x61.l.r(new aa.m[]{mVar4, new aa.m("nodes", l0.a(a3.f), (String) null, rVar, rVar, r2)});
        List n4 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n5 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n6 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n7 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        aa.m mVar5 = new aa.m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        e3.Companion.getClass();
        aa.m mVar6 = new aa.m("status", l0.b(e3.s), (String) null, rVar, rVar, rVar);
        y2.Companion.getClass();
        a0 a0Var = y2.s;
        k71.k.g(a0Var, "type");
        aa.m mVar7 = new aa.m("conclusion", a0Var, (String) null, rVar, rVar, rVar);
        aa.m mVar8 = new aa.m("duration", l0.b(xVar), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        aa.m mVar9 = new aa.m("rerunnable", l0.b(pd.a), (String) null, rVar, rVar, rVar);
        g1.Companion.getClass();
        q0 q0Var = g1.a;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("artifacts", q0Var, (String) null, rVar, rVar, n);
        ha0.Companion.getClass();
        q0 q0Var2 = ha0.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar11 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r);
        c3.Companion.getClass();
        q0 q0Var3 = c3.a;
        k71.k.g(q0Var3, "type");
        k3.Companion.getClass();
        t tVar = k3.b;
        aa.k kVar = new aa.k(tVar, new u0(no.a.u("conclusions", x61.l.r(new String[]{"CANCELLED", "FAILURE", "TIMED_OUT", "ACTION_REQUIRED", "STALE", "STARTUP_FAILURE"}))));
        t tVar2 = k3.c;
        List r4 = x61.l.r(new s[]{new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.n("CheckSuite", d0Shadow.n("CheckSuite"), x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, mVar8, mVar9, mVar10, mVar11, new aa.m("checkRuns", q0Var3, "failedCheckRuns", rVar, x61.l.r(new aa.k[]{kVar, new aa.k(tVar2, new u0(5))}), r3), new aa.m("checkRuns", q0Var3, "runningCheckRuns", rVar, x61.l.r(new aa.k[]{new aa.k(tVar, new u0(no.a.u("statuses", x61.l.r(new String[]{"IN_PROGRESS", "PENDING", "QUEUED", "REQUESTED", "WAITING"})))), new aa.k(tVar2, new u0(1))}), n4), new aa.m("checkRuns", q0Var3, "skippedCheckRuns", rVar, x61.l.r(new aa.k[]{new aa.k(tVar, new u0(no.a.u("conclusions", d0Shadow.n("SKIPPED")))), new aa.k(tVar2, new u0(1))}), n5), new aa.m("checkRuns", q0Var3, "neutralCheckRuns", rVar, x61.l.r(new aa.k[]{new aa.k(tVar, new u0(no.a.u("conclusions", d0Shadow.n("NEUTRAL")))), new aa.k(tVar2, new u0(1))}), n6), new aa.m("checkRuns", q0Var3, "successfulCheckRuns", rVar, x61.l.r(new aa.k[]{new aa.k(tVar, new u0(no.a.u("conclusions", d0Shadow.n("SUCCESS")))), new aa.k(tVar2, new u0(1))}), n7)}))});
        wk.Companion.getClass();
        j0 j0Var = wk.a;
        k71.k.g(j0Var, "type");
        su.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(su.i, new u0(new aa.t("id"))), r4), new aa.m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
