plugins {
    id 'com.android.application'
}

android {
    namespace 'com.webapk.hosttemplate'
    compileSdk 36

    defaultConfig {
        applicationId 'com.webapk.hosttemplate'
        minSdk 22
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
