package qw0;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import k71.k;
import pz0.a3;
import pz0.f30;
import pz0.h30;
import pz0.h50;
import pz0.ha0;
import pz0.hs;
import pz0.j30;
import pz0.k3;
import pz0.l30;
import pz0.n30;
import pz0.nz;
import pz0.o7;
import pz0.pd;
import pz0.ps;
import pz0.pz;
import pz0.s4;
import pz0.su;
import pz0.td;
import pz0.ts;
import pz0.vd;
import pz0.w0;
import pz0.wk;
import pz0.xd;
import pz0.y2;
import pz0.y90;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class e {
    public static final List a;

    static {
        td.Companion.getClass();
        x xVar = td.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        x xVar2 = xd.a;
        m mVar2 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        n30.Companion.getClass();
        a0 a0Var = n30.s;
        List r = l.r(new m[]{mVar, mVar2, new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar), new m("description", xVar2, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        vd.Companion.getClass();
        x xVar3 = vd.a;
        m mVar3 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        nz.Companion.getClass();
        List r2 = l.r(new m[]{mVar3, new m("nodes", l0.a(nz.a), (String) null, rVar, rVar, r)});
        m mVar4 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar5 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        x xVar4 = h50.a;
        k.g(xVar4, "type");
        m mVar7 = new m("avatarUrl", xVar4, (String) null, rVar, rVar, rVar);
        m mVar8 = new m("description", xVar2, (String) null, rVar, rVar, rVar);
        m mVar9 = new m("targetUrl", xVar4, (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        x xVar5 = pd.a;
        r b2 = l0.b(xVar5);
        l30.Companion.getClass();
        List r3 = l.r(new m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new m("isRequired", b2, (String) null, rVar, no.a.s(l30.b, new u0(new t("prNumber"))), rVar)});
        List r4 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        y90.Companion.getClass();
        List r5 = l.r(new m[]{new m("workflow", l0.b(y90.e), (String) null, rVar, rVar, r4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("logoUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ha0.Companion.getClass();
        q0 q0Var = ha0.b;
        k.g(q0Var, "type");
        m mVar10 = new m("workflowRun", q0Var, (String) null, rVar, rVar, r5);
        w0.Companion.getClass();
        q0 q0Var2 = w0.a;
        k.g(q0Var2, "type");
        List r7 = l.r(new m[]{mVar10, new m("app", q0Var2, (String) null, rVar, rVar, r6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar11 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        y2.Companion.getClass();
        a0 a0Var2 = y2.s;
        k.g(a0Var2, "type");
        m mVar12 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("duration", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar15 = new m("summary", xVar2, (String) null, rVar, rVar, rVar);
        m mVar16 = new m("permalink", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        k3.Companion.getClass();
        m mVar17 = new m("checkSuite", l0.b(k3.f), (String) null, rVar, rVar, r7);
        r b3 = l0.b(xVar5);
        a3.Companion.getClass();
        List r8 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("StatusContext", d0.n("StatusContext"), r3), new n("CheckRun", d0.n("CheckRun"), l.r(new m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new m("isRequired", b3, (String) null, rVar, no.a.s(a3.b, new u0(new t("prNumber"))), rVar)}))});
        m mVar18 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        h30.Companion.getClass();
        List r9 = l.r(new m[]{mVar18, new m("nodes", l0.a(h30.a), (String) null, rVar, rVar, r8)});
        m mVar19 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        j30.Companion.getClass();
        r b4 = l0.b(j30.a);
        f30.Companion.getClass();
        List r10 = l.r(new m[]{mVar19, mVar20, new m("contexts", b4, (String) null, rVar, no.a.s(f30.b, new u0(100)), r9), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar21 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        m mVar22 = new m("committedDate", l0.b(o7.a), (String) null, rVar, rVar, rVar);
        q0 q0Var3 = f30.c;
        k.g(q0Var3, "type");
        List r12 = l.r(new m[]{mVar21, mVar22, new m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r10), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar23 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s4.Companion.getClass();
        List r13 = l.r(new m[]{mVar23, new m("commit", l0.b(s4.j), (String) null, rVar, rVar, r12), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar24 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ps.Companion.getClass();
        List r14 = l.r(new m[]{mVar24, mVar25, new m("nodes", l0.a(ps.a), (String) null, rVar, rVar, r13)});
        m mVar26 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        pz.Companion.getClass();
        r b5 = l0.b(pz.a);
        hs.Companion.getClass();
        m mVar27 = new m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(hs.x, new u0(25)), r2);
        m mVar28 = new m("actionRequiredWorkflowRunCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ts.Companion.getClass();
        List r15 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("PullRequest", d0.n("PullRequest"), l.r(new m[]{mVar26, mVar27, mVar28, new m("commits", l0.b(ts.a), (String) null, rVar, no.a.s(hs.l, new u0(1)), r14)})), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        wk.Companion.getClass();
        j0 j0Var = wk.a;
        k.g(j0Var, "type");
        su.Companion.getClass();
        a = l.r(new m[]{new m("node", j0Var, (String) null, rVar, no.a.s(su.i, new u0(new t("id"))), r15), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
