package pz0;

import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class jx {
    public static final aa.q0 t0;
    public static final ix Companion = new ix();
    public static final a81.t a = new a81.t(1, "after", false);
    public static final a81.t b = new a81.t(1, "first", false);
    public static final a81.t c = new a81.t(1, "query", false);
    public static final a81.t d = new a81.t(1, "after", false);
    public static final a81.t e = new a81.t(1, "first", false);
    public static final a81.t f = new a81.t(1, "query", false);
    public static final a81.t g = new a81.t(1, "after", false);
    public static final a81.t h = new a81.t(1, "first", false);
    public static final a81.t i = new a81.t(1, "number", false);
    public static final a81.t j = new a81.t(1, "after", false);
    public static final a81.t k = new a81.t(1, "filterByAssignable", false);
    public static final a81.t l = new a81.t(1, "first", false);
    public static final a81.t m = new a81.t(1, "first", false);
    public static final a81.t n = new a81.t(1, "affiliations", false);
    public static final a81.t o = new a81.t(1, "after", false);
    public static final a81.t p = new a81.t(1, "first", false);
    public static final a81.t q = new a81.t(1, "number", false);
    public static final a81.t r = new a81.t(1, "after", false);
    public static final a81.t s = new a81.t(1, "first", false);
    public static final a81.t t = new a81.t(1, "first", false);
    public static final a81.t u = new a81.t(1, "states", false);
    public static final a81.t v = new a81.t(1, "after", false);
    public static final a81.t w = new a81.t(1, "first", false);
    public static final a81.t x = new a81.t(1, "orderBy", false);
    public static final a81.t y = new a81.t(1, "query", false);
    public static final a81.t z = new a81.t(1, "first", false);
    public static final a81.t A = new a81.t(1, "onlyOwnedByViewer", false);
    public static final a81.t B = new a81.t(1, "first", false);
    public static final a81.t C = new a81.t(1, "query", false);
    public static final a81.t D = new a81.t(1, "branch", false);
    public static final a81.t E = new a81.t(1, "after", false);
    public static final a81.t F = new a81.t(1, "first", false);
    public static final a81.t G = new a81.t(1, "orderBy", false);
    public static final a81.t H = new a81.t(1, "query", false);
    public static final a81.t I = new a81.t(1, "states", false);
    public static final a81.t J = new a81.t(1, "expression", false);
    public static final a81.t K = new a81.t(1, "first", false);
    public static final a81.t L = new a81.t(1, "first", false);
    public static final a81.t M = new a81.t(1, "feature", false);
    public static final a81.t N = new a81.t(1, "feature", false);
    public static final a81.t O = new a81.t(1, "after", false);
    public static final a81.t P = new a81.t(1, "first", false);
    public static final a81.t Q = new a81.t(1, "orderBy", false);
    public static final a81.t R = new a81.t(1, "query", false);
    public static final a81.t S = new a81.t(1, "number", false);
    public static final a81.t T = new a81.t(1, "first", false);
    public static final a81.t U = new a81.t(1, "states", false);
    public static final a81.t V = new a81.t(1, "refName", false);
    public static final a81.t W = new a81.t(1, "qualifiedName", false);
    public static final a81.t X = new a81.t(1, "after", false);
    public static final a81.t Y = new a81.t(1, "first", false);
    public static final a81.t Z = new a81.t(1, "last", false);
    public static final a81.t a0 = new a81.t(1, "query", false);
    public static final a81.t b0 = new a81.t(1, "refPrefix", false);
    public static final a81.t c0 = new a81.t(1, "tagName", false);
    public static final a81.t d0 = new a81.t(1, "after", false);
    public static final a81.t e0 = new a81.t(1, "first", false);
    public static final a81.t f0 = new a81.t(1, "orderBy", false);
    public static final a81.t g0 = new a81.t(1, "first", false);
    public static final a81.t h0 = new a81.t(1, "after", false);
    public static final a81.t i0 = new a81.t(1, "first", false);
    public static final a81.t j0 = new a81.t(1, "orderBy", false);
    public static final a81.t k0 = new a81.t(1, "period", false);
    public static final a81.t l0 = new a81.t(1, "limit", false);
    public static final a81.t m0 = new a81.t(1, "skipBots", false);
    public static final a81.t n0 = new a81.t(1, "skipViewer", false);
    public static final a81.t o0 = new a81.t(1, "after", false);
    public static final a81.t p0 = new a81.t(1, "first", false);
    public static final a81.t q0 = new a81.t(1, "after", false);
    public static final a81.t r0 = new a81.t(1, "first", false);
    public static final a81.t s0 = new a81.t(1, "orderBy", false);

    static {
        List n2 = sy.d0Shadow.n("id");
        qh.Companion.getClass();
        aa.j0 j0Var = qh.a;
        wk.Companion.getClass();
        aa.j0 j0Var2 = wk.a;
        fm.Companion.getClass();
        aa.j0 j0Var3 = fm.a;
        tn.Companion.getClass();
        aa.j0 j0Var4 = tn.a;
        vn.Companion.getClass();
        aa.j0 j0Var5 = vn.a;
        hr.Companion.getClass();
        aa.j0 j0Var6 = hr.a;
        ey.Companion.getClass();
        aa.j0 j0Var7 = ey.a;
        x20.Companion.getClass();
        aa.j0 j0Var8 = x20.a;
        z30.Companion.getClass();
        aa.j0 j0Var9 = z30.a;
        v50.Companion.getClass();
        t0 = new aa.q0("Repository", n2, x61.l.r(new aa.j0[]{j0Var, j0Var2, j0Var3, j0Var4, j0Var5, j0Var6, j0Var7, j0Var8, j0Var9, v50.a}));
    }
}
