package pz0;

import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class mj {
    public static final lj Companion;
    public static final mj s;
    public static final /* synthetic */ mj[] t;
    public static final /* synthetic */ d71.b u;
    public String r;

    static {
        mj mjVar = new mj("ACCOUNT_SWITCHER_ADD", 0, "ACCOUNT_SWITCHER_ADD");
        mj mjVar2 = new mj("ACCOUNT_SWITCHER_ITEM", 1, "ACCOUNT_SWITCHER_ITEM");
        mj mjVar3 = new mj("ACCOUNT_SWITCHER_REMOVE", 2, "ACCOUNT_SWITCHER_REMOVE");
        mj mjVar4 = new mj("CODE_SEARCH_LIST_ITEM", 3, "CODE_SEARCH_LIST_ITEM");
        mj mjVar5 = new mj("COMPARE_BRANCHES", 4, "COMPARE_BRANCHES");
        mj mjVar6 = new mj("COMPARE_BRANCHES_ACTIVE_PULL_REQUEST", 5, "COMPARE_BRANCHES_ACTIVE_PULL_REQUEST");
        mj mjVar7 = new mj("COMPARE_BRANCHES_COMMITS", 6, "COMPARE_BRANCHES_COMMITS");
        mj mjVar8 = new mj("COMPARE_BRANCHES_CREATE_PULL_REQUEST", 7, "COMPARE_BRANCHES_CREATE_PULL_REQUEST");
        mj mjVar9 = new mj("COMPARE_BRANCHES_FILES_CHANGED", 8, "COMPARE_BRANCHES_FILES_CHANGED");
        mj mjVar10 = new mj("COPILOT_AGREEMENT", 9, "COPILOT_AGREEMENT");
        mj mjVar11 = new mj("COPILOT_ALL_CONVERSATIONS", 10, "COPILOT_ALL_CONVERSATIONS");
        mj mjVar12 = new mj("COPILOT_BUY", 11, "COPILOT_BUY");
        mj mjVar13 = new mj("COPILOT_CHAT_BUTTON", 12, "COPILOT_CHAT_BUTTON");
        mj mjVar14 = new mj("COPILOT_CHAT_CONVERSATION", 13, "COPILOT_CHAT_CONVERSATION");
        mj mjVar15 = new mj("COPILOT_CHAT_MESSAGE_COPY", 14, "COPILOT_CHAT_MESSAGE_COPY");
        mj mjVar16 = new mj("COPILOT_CHAT_SUGGESTION", 15, "COPILOT_CHAT_SUGGESTION");
        mj mjVar17 = new mj("COPILOT_DELETE_CONVERSATION", 16, "COPILOT_DELETE_CONVERSATION");
        mj mjVar18 = new mj("COPILOT_DISMISS_PAYWALL", 17, "COPILOT_DISMISS_PAYWALL");
        mj mjVar19 = new mj("COPILOT_LEARN_MORE", 18, "COPILOT_LEARN_MORE");
        mj mjVar20 = new mj("COPILOT_MANAGE_SUBSCRIPTION", 19, "COPILOT_MANAGE_SUBSCRIPTION");
        mj mjVar21 = new mj("COPILOT_NEW_CONVERSATION", 20, "COPILOT_NEW_CONVERSATION");
        mj mjVar22 = new mj("COPILOT_POLICY_DISABLED_LINK", 21, "COPILOT_POLICY_DISABLED_LINK");
        mj mjVar23 = new mj("COPILOT_PRIVACY_POLICY", 22, "COPILOT_PRIVACY_POLICY");
        mj mjVar24 = new mj("COPILOT_RECENT_CONVERSATION", 23, "COPILOT_RECENT_CONVERSATION");
        mj mjVar25 = new mj("COPILOT_RESTORE_PURCHASE", 24, "COPILOT_RESTORE_PURCHASE");
        mj mjVar26 = new mj("COPILOT_SCOPE_LINK", 25, "COPILOT_SCOPE_LINK");
        mj mjVar27 = new mj("COPILOT_SETTINGS_ENABLE", 26, "COPILOT_SETTINGS_ENABLE");
        mj mjVar28 = new mj("COPILOT_SETTINGS_HIDE_BOA", 27, "COPILOT_SETTINGS_HIDE_BOA");
        mj mjVar29 = new mj("COPILOT_UPSELL_DISMISS", 28, "COPILOT_UPSELL_DISMISS");
        mj mjVar30 = new mj("COPILOT_UPSELL_LEARN_MORE", 29, "COPILOT_UPSELL_LEARN_MORE");
        mj mjVar31 = new mj("DEEP_LINK_ERROR_ACCOUNT_SWITCHER", 30, "DEEP_LINK_ERROR_ACCOUNT_SWITCHER");
        mj mjVar32 = new mj("EXPLORE_BOTTOM_NAVIGATION", 31, "EXPLORE_BOTTOM_NAVIGATION");
        mj mjVar33 = new mj("EXPLORE_FEATURED_REPOSITORY", 32, "EXPLORE_FEATURED_REPOSITORY");
        mj mjVar34 = new mj("EXPLORE_FOR_YOU_REPOSITORY", 33, "EXPLORE_FOR_YOU_REPOSITORY");
        mj mjVar35 = new mj("EXPLORE_STAR_FEATURED_REPOSITORY", 34, "EXPLORE_STAR_FEATURED_REPOSITORY");
        mj mjVar36 = new mj("EXPLORE_STAR_FOR_YOU_REPOSITORY", 35, "EXPLORE_STAR_FOR_YOU_REPOSITORY");
        mj mjVar37 = new mj("EXPLORE_STAR_TRENDING_REPOSITORY", 36, "EXPLORE_STAR_TRENDING_REPOSITORY");
        mj mjVar38 = new mj("EXPLORE_TRENDING_LIST_FILTER", 37, "EXPLORE_TRENDING_LIST_FILTER");
        mj mjVar39 = new mj("EXPLORE_TRENDING_REPOSITORY", 38, "EXPLORE_TRENDING_REPOSITORY");
        mj mjVar40 = new mj("FINISH_REVIEW_BOA", 39, "FINISH_REVIEW_BOA");
        mj mjVar41 = new mj("FOCUS_CTA_DISMISSED", 40, "FOCUS_CTA_DISMISSED");
        mj mjVar42 = new mj("FOCUS_CTA_ENABLED", 41, "FOCUS_CTA_ENABLED");
        mj mjVar43 = new mj("FOCUS_CTA_VIEWED", 42, "FOCUS_CTA_VIEWED");
        mj mjVar44 = new mj("FOLLOW", 43, "FOLLOW");
        mj mjVar45 = new mj("GLOBAL_SEARCH_SHORTCUT", 44, "GLOBAL_SEARCH_SHORTCUT");
        mj mjVar46 = new mj("HOME_BOTTOM_NAVIGATION", 45, "HOME_BOTTOM_NAVIGATION");
        mj mjVar47 = new mj("HOME_CREATE_ISSUE", 46, "HOME_CREATE_ISSUE");
        mj mjVar48 = new mj("HOME_DISCUSSIONS", 47, "HOME_DISCUSSIONS");
        mj mjVar49 = new mj("HOME_FAVORITE_REPOSITORY_ITEM", 48, "HOME_FAVORITE_REPOSITORY_ITEM");
        mj mjVar50 = new mj("HOME_IN_APP_UPDATE", 49, "HOME_IN_APP_UPDATE");
        mj mjVar51 = new mj("HOME_ISSUES", 50, "HOME_ISSUES");
        mj mjVar52 = new mj("HOME_ISSUES_LIST_NEW_ISSUE", 51, "HOME_ISSUES_LIST_NEW_ISSUE");
        mj mjVar53 = new mj("HOME_ORGANIZATIONS", 52, "HOME_ORGANIZATIONS");
        mj mjVar54 = new mj("HOME_PROJECTS", 53, "HOME_PROJECTS");
        mj mjVar55 = new mj("HOME_PULL_REQUESTS", 54, "HOME_PULL_REQUESTS");
        mj mjVar56 = new mj("HOME_RECENT_ACTIVITY_ITEM", 55, "HOME_RECENT_ACTIVITY_ITEM");
        mj mjVar57 = new mj("HOME_RELEASE_NOTES", 56, "HOME_RELEASE_NOTES");
        mj mjVar58 = new mj("HOME_REPOSITORIES", 57, "HOME_REPOSITORIES");
        mj mjVar59 = new mj("HOME_REPOSITORY_LIST_FILTER", 58, "HOME_REPOSITORY_LIST_FILTER");
        mj mjVar60 = new mj("HOME_SHORTCUTS", 59, "HOME_SHORTCUTS");
        mj mjVar61 = new mj("HOME_STARRED", 60, "HOME_STARRED");
        mj mjVar62 = new mj("ISSUES_LIST_ITEM", 61, "ISSUES_LIST_ITEM");
        mj mjVar63 = new mj("ISSUES_SEARCH", 62, "ISSUES_SEARCH");
        mj mjVar64 = new mj("ISSUE_COMPOSER", 63, "ISSUE_COMPOSER");
        mj mjVar65 = new mj("ISSUE_COMPOSER_PROPERTY_BAR", 64, "ISSUE_COMPOSER_PROPERTY_BAR");
        mj mjVar66 = new mj("NOTIFICATIONS_ONBOARDING_BANNER", 65, "NOTIFICATIONS_ONBOARDING_BANNER");
        mj mjVar67 = new mj("NOTIFICATION_BOTTOM_NAVIGATION", 66, "NOTIFICATION_BOTTOM_NAVIGATION");
        mj mjVar68 = new mj("NOTIFICATION_FILTER", 67, "NOTIFICATION_FILTER");
        mj mjVar69 = new mj("NOTIFICATION_LIST", 68, "NOTIFICATION_LIST");
        mj mjVar70 = new mj("NOTIFICATION_LIST_FILTER", 69, "NOTIFICATION_LIST_FILTER");
        mj mjVar71 = new mj("NOTIFICATION_LIST_ITEM", 70, "NOTIFICATION_LIST_ITEM");
        mj mjVar72 = new mj("NOTIFICATION_LIST_ITEM_FOCUSED", 71, "NOTIFICATION_LIST_ITEM_FOCUSED");
        mj mjVar73 = new mj("NOTIFICATION_LIST_ITEM_UNDO", 72, "NOTIFICATION_LIST_ITEM_UNDO");
        mj mjVar74 = new mj("NOTIFICATION_ONBOARDING_CONTINUE_BANNER", 73, "NOTIFICATION_ONBOARDING_CONTINUE_BANNER");
        mj mjVar75 = new mj("NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER", 74, "NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER");
        mj mjVar76 = new mj("NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER", 75, "NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER");
        mj mjVar77 = new mj("NOTIFICATION_ONBOARDING_NUX_BANNER", 76, "NOTIFICATION_ONBOARDING_NUX_BANNER");
        mj mjVar78 = new mj("NOTIFICATION_ONBOARDING_PROGRESS", 77, "NOTIFICATION_ONBOARDING_PROGRESS");
        mj mjVar79 = new mj("NOTIFICATION_ONBOARDING_PROGRESS_REVIEW", 78, "NOTIFICATION_ONBOARDING_PROGRESS_REVIEW");
        mj mjVar80 = new mj("NOTIFICATION_ONBOARDING_RECAPTURE", 79, "NOTIFICATION_ONBOARDING_RECAPTURE");
        mj mjVar81 = new mj("NOTIFICATION_ONBOARDING_REVIEW_BANNER", 80, "NOTIFICATION_ONBOARDING_REVIEW_BANNER");
        mj mjVar82 = new mj("NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS", 81, "NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS");
        mj mjVar83 = new mj("NOTIFICATION_PUSH", 82, "NOTIFICATION_PUSH");
        mj mjVar84 = new mj("ONBOARDING_BANNER", 83, "ONBOARDING_BANNER");
        mj mjVar85 = new mj("PIN_SHORTCUT", 84, "PIN_SHORTCUT");
        mj mjVar86 = new mj("PROFILE_BOTTOM_NAVIGATION", 85, "PROFILE_BOTTOM_NAVIGATION");
        mj mjVar87 = new mj("PROFILE_HEADER_NAME", 86, "PROFILE_HEADER_NAME");
        mj mjVar88 = new mj("PROFILE_REPOSITORY_LIST_FILTER", 87, "PROFILE_REPOSITORY_LIST_FILTER");
        mj mjVar89 = new mj("PROJECTS_LIST_ITEM", 88, "PROJECTS_LIST_ITEM");
        mj mjVar90 = new mj("PROJECTS_QUICK_ACTION_CLOSE", 89, "PROJECTS_QUICK_ACTION_CLOSE");
        mj mjVar91 = new mj("PROJECTS_QUICK_ACTION_DELETE", 90, "PROJECTS_QUICK_ACTION_DELETE");
        mj mjVar92 = new mj("PROJECTS_QUICK_ACTION_EDIT_FIELD", 91, "PROJECTS_QUICK_ACTION_EDIT_FIELD");
        mj mjVar93 = new mj("PROJECTS_QUICK_ACTION_EDIT_TITLE", 92, "PROJECTS_QUICK_ACTION_EDIT_TITLE");
        mj mjVar94 = new mj("PROJECTS_QUICK_ACTION_OPEN_DETAILS", 93, "PROJECTS_QUICK_ACTION_OPEN_DETAILS");
        mj mjVar95 = new mj("PROJECTS_QUICK_ACTION_OTHER_PROJECTS", 94, "PROJECTS_QUICK_ACTION_OTHER_PROJECTS");
        mj mjVar96 = new mj("PROJECTS_QUICK_ACTION_REOPEN", 95, "PROJECTS_QUICK_ACTION_REOPEN");
        mj mjVar97 = new mj("PROJECTS_TABLE_VIEW_LIST_ITEM", 96, "PROJECTS_TABLE_VIEW_LIST_ITEM");
        mj mjVar98 = new mj("PROJECT_VIEW", 97, "PROJECT_VIEW");
        mj mjVar99 = new mj("PROJECT_VIEW_TIMEOUT_CTA", 98, "PROJECT_VIEW_TIMEOUT_CTA");
        mj mjVar100 = new mj("PULL_REQUESTS_LIST_ITEM", 99, "PULL_REQUESTS_LIST_ITEM");
        mj mjVar101 = new mj("PULL_REQUESTS_SEARCH", 100, "PULL_REQUESTS_SEARCH");
        mj mjVar102 = new mj("PULL_REQUEST_COMPOSER_SUBMIT", 101, "PULL_REQUEST_COMPOSER_SUBMIT");
        mj mjVar103 = new mj("PULL_REQUEST_FILES_CHANGED", 102, "PULL_REQUEST_FILES_CHANGED");
        mj mjVar104 = new mj("PULL_REQUEST_LEGACY_CREATION_SUBMIT", 103, "PULL_REQUEST_LEGACY_CREATION_SUBMIT");
        mj mjVar105 = new mj("PULL_REQUEST_REVIEW_BANNER", 104, "PULL_REQUEST_REVIEW_BANNER");
        mj mjVar106 = new mj("PULL_REQUEST_REVIEW_CTA", 105, "PULL_REQUEST_REVIEW_CTA");
        mj mjVar107 = new mj("PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW", 106, "PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW");
        mj mjVar108 = new mj("PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY", 107, "PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY");
        mj mjVar109 = new mj("RELEASES_LIST_LATEST_RELEASE", 108, "RELEASES_LIST_LATEST_RELEASE");
        mj mjVar110 = new mj("RELEASE_DOWNLOAD_ASSET", 109, "RELEASE_DOWNLOAD_ASSET");
        mj mjVar111 = new mj("RELEASE_LINKED_DISCUSSION", 110, "RELEASE_LINKED_DISCUSSION");
        mj mjVar112 = new mj("REPOSITORY_DISCUSSIONS_LIST_FILTER", 111, "REPOSITORY_DISCUSSIONS_LIST_FILTER");
        mj mjVar113 = new mj("REPOSITORY_EDIT_README", 112, "REPOSITORY_EDIT_README");
        mj mjVar114 = new mj("REPOSITORY_ISSUES_LIST_FILTER", 113, "REPOSITORY_ISSUES_LIST_FILTER");
        mj mjVar115 = new mj("REPOSITORY_LATEST_RELEASE", 114, "REPOSITORY_LATEST_RELEASE");
        mj mjVar116 = new mj("REPOSITORY_PULL_REQUESTS_LIST_FILTER", 115, "REPOSITORY_PULL_REQUESTS_LIST_FILTER");
        mj mjVar117 = new mj("SETTINGS_ACCOUNTS", 116, "SETTINGS_ACCOUNTS");
        mj mjVar118 = new mj("SETTINGS_DISABLE_ANALYTICS", 117, "SETTINGS_DISABLE_ANALYTICS");
        mj mjVar119 = new mj("SETTINGS_ENABLE_APP_LOCK", 118, "SETTINGS_ENABLE_APP_LOCK");
        mj mjVar120 = new mj("SHORTCUTS_LIST_ITEM", 119, "SHORTCUTS_LIST_ITEM");
        mj mjVar121 = new mj("SHORTCUT_SUGGESTIONS_LIST_ITEM", 120, "SHORTCUT_SUGGESTIONS_LIST_ITEM");
        mj mjVar122 = new mj("SHOW_MORE_ROLLUP", 121, "SHOW_MORE_ROLLUP");
        mj mjVar123 = new mj("STAR_REPOSITORY", 122, "STAR_REPOSITORY");
        mj mjVar124 = new mj("SUBMIT_REVIEW", 123, "SUBMIT_REVIEW");
        mj mjVar125 = new mj("SUB_ISSUE_ADD_EXISTING_ISSUE", 124, "SUB_ISSUE_ADD_EXISTING_ISSUE");
        mj mjVar126 = new mj("SUB_ISSUE_ADD_NEW_ISSUE", 125, "SUB_ISSUE_ADD_NEW_ISSUE");
        mj mjVar127 = new mj("SUB_ISSUE_EDIT_PARENT_ISSUE", 126, "SUB_ISSUE_EDIT_PARENT_ISSUE");
        mj mjVar128 = new mj("SUB_ISSUE_EDIT_SUB_ISSUE", 127, "SUB_ISSUE_EDIT_SUB_ISSUE");
        mj mjVar129 = new mj("SUB_ISSUE_ISSUE", 128, "SUB_ISSUE_ISSUE");
        mj mjVar130 = new mj("SUB_ISSUE_NESTED_ISSUES_TOGGLE", 129, "SUB_ISSUE_NESTED_ISSUES_TOGGLE");
        mj mjVar131 = new mj("SUB_ISSUE_PARENT_ISSUE", 130, "SUB_ISSUE_PARENT_ISSUE");
        mj mjVar132 = new mj("SUB_ISSUE_SECTION", 131, "SUB_ISSUE_SECTION");
        mj mjVar133 = new mj("TRIAGE_ASSIGNEE_EDIT", 132, "TRIAGE_ASSIGNEE_EDIT");
        mj mjVar134 = new mj("TRIAGE_CLOSE", 133, "TRIAGE_CLOSE");
        mj mjVar135 = new mj("TRIAGE_COMMENT", 134, "TRIAGE_COMMENT");
        mj mjVar136 = new mj("TRIAGE_COMMENT_DOWN", 135, "TRIAGE_COMMENT_DOWN");
        mj mjVar137 = new mj("TRIAGE_COMMENT_EDIT", 136, "TRIAGE_COMMENT_EDIT");
        mj mjVar138 = new mj("TRIAGE_COMMENT_UP", 137, "TRIAGE_COMMENT_UP");
        mj mjVar139 = new mj("TRIAGE_EXPAND", 138, "TRIAGE_EXPAND");
        mj mjVar140 = new mj("TRIAGE_ISSUE_TYPE_EDIT", 139, "TRIAGE_ISSUE_TYPE_EDIT");
        mj mjVar141 = new mj("TRIAGE_LABEL_EDIT", 140, "TRIAGE_LABEL_EDIT");
        mj mjVar142 = new mj("TRIAGE_LINKED_ITEM_EDIT", 141, "TRIAGE_LINKED_ITEM_EDIT");
        mj mjVar143 = new mj("TRIAGE_LOCK", 142, "TRIAGE_LOCK");
        mj mjVar144 = new mj("TRIAGE_MILESTONE_EDIT", 143, "TRIAGE_MILESTONE_EDIT");
        mj mjVar145 = new mj("TRIAGE_PROJECT_EDIT", 144, "TRIAGE_PROJECT_EDIT");
        mj mjVar146 = new mj("TRIAGE_PROJECT_NEXT_EDIT", 145, "TRIAGE_PROJECT_NEXT_EDIT");
        mj mjVar147 = new mj("TRIAGE_PROJECT_NEXT_PICKER_OWNER", 146, "TRIAGE_PROJECT_NEXT_PICKER_OWNER");
        mj mjVar148 = new mj("TRIAGE_PROJECT_NEXT_PICKER_RECENT", 147, "TRIAGE_PROJECT_NEXT_PICKER_RECENT");
        mj mjVar149 = new mj("TRIAGE_REVIEW_REQUEST_EDIT", 148, "TRIAGE_REVIEW_REQUEST_EDIT");
        mj mjVar150 = new mj("TRIAGE_UNSUBSCRIBE", 149, "TRIAGE_UNSUBSCRIBE");
        mj mjVar151 = new mj("VIEWER_DISCUSSIONS_LIST_FILTER", 150, "VIEWER_DISCUSSIONS_LIST_FILTER");
        mj mjVar152 = new mj("VIEWER_ISSUES_LIST_FILTER", 151, "VIEWER_ISSUES_LIST_FILTER");
        mj mjVar153 = new mj("VIEWER_PULL_REQUESTS_LIST_FILTER", 152, "VIEWER_PULL_REQUESTS_LIST_FILTER");
        mj mjVar154 = new mj("VIEWER_PULL_TO_REFRESH", 153, "VIEWER_PULL_TO_REFRESH");
        mj mjVar155 = new mj("VIEWING_AS_TOAST", 154, "VIEWING_AS_TOAST");
        mj mjVar156 = new mj("UNKNOWN__", ModuleDescriptor.MODULE_VERSION, "UNKNOWN__");
        s = mjVar156;
        mj[] mjVarArr = {mjVar, mjVar2, mjVar3, mjVar4, mjVar5, mjVar6, mjVar7, mjVar8, mjVar9, mjVar10, mjVar11, mjVar12, mjVar13, mjVar14, mjVar15, mjVar16, mjVar17, mjVar18, mjVar19, mjVar20, mjVar21, mjVar22, mjVar23, mjVar24, mjVar25, mjVar26, mjVar27, mjVar28, mjVar29, mjVar30, mjVar31, mjVar32, mjVar33, mjVar34, mjVar35, mjVar36, mjVar37, mjVar38, mjVar39, mjVar40, mjVar41, mjVar42, mjVar43, mjVar44, mjVar45, mjVar46, mjVar47, mjVar48, mjVar49, mjVar50, mjVar51, mjVar52, mjVar53, mjVar54, mjVar55, mjVar56, mjVar57, mjVar58, mjVar59, mjVar60, mjVar61, mjVar62, mjVar63, mjVar64, mjVar65, mjVar66, mjVar67, mjVar68, mjVar69, mjVar70, mjVar71, mjVar72, mjVar73, mjVar74, mjVar75, mjVar76, mjVar77, mjVar78, mjVar79, mjVar80, mjVar81, mjVar82, mjVar83, mjVar84, mjVar85, mjVar86, mjVar87, mjVar88, mjVar89, mjVar90, mjVar91, mjVar92, mjVar93, mjVar94, mjVar95, mjVar96, mjVar97, mjVar98, mjVar99, mjVar100, mjVar101, mjVar102, mjVar103, mjVar104, mjVar105, mjVar106, mjVar107, mjVar108, mjVar109, mjVar110, mjVar111, mjVar112, mjVar113, mjVar114, mjVar115, mjVar116, mjVar117, mjVar118, mjVar119, mjVar120, mjVar121, mjVar122, mjVar123, mjVar124, mjVar125, mjVar126, mjVar127, mjVar128, mjVar129, mjVar130, mjVar131, mjVar132, mjVar133, mjVar134, mjVar135, mjVar136, mjVar137, mjVar138, mjVar139, mjVar140, mjVar141, mjVar142, mjVar143, mjVar144, mjVar145, mjVar146, mjVar147, mjVar148, mjVar149, mjVar150, mjVar151, mjVar152, mjVar153, mjVar154, mjVar155, mjVar156};
        t = mjVarArr;
        u = v8.l0.t(mjVarArr);
        Companion = new lj();
        sy.d0Shadow.o(new String[]{"ACCOUNT_SWITCHER_ADD", "ACCOUNT_SWITCHER_ITEM", "ACCOUNT_SWITCHER_REMOVE", "CODE_SEARCH_LIST_ITEM", "COMPARE_BRANCHES", "COMPARE_BRANCHES_ACTIVE_PULL_REQUEST", "COMPARE_BRANCHES_COMMITS", "COMPARE_BRANCHES_CREATE_PULL_REQUEST", "COMPARE_BRANCHES_FILES_CHANGED", "COPILOT_AGREEMENT", "COPILOT_ALL_CONVERSATIONS", "COPILOT_BUY", "COPILOT_CHAT_BUTTON", "COPILOT_CHAT_CONVERSATION", "COPILOT_CHAT_MESSAGE_COPY", "COPILOT_CHAT_SUGGESTION", "COPILOT_DELETE_CONVERSATION", "COPILOT_DISMISS_PAYWALL", "COPILOT_LEARN_MORE", "COPILOT_MANAGE_SUBSCRIPTION", "COPILOT_NEW_CONVERSATION", "COPILOT_POLICY_DISABLED_LINK", "COPILOT_PRIVACY_POLICY", "COPILOT_RECENT_CONVERSATION", "COPILOT_RESTORE_PURCHASE", "COPILOT_SCOPE_LINK", "COPILOT_SETTINGS_ENABLE", "COPILOT_SETTINGS_HIDE_BOA", "COPILOT_UPSELL_DISMISS", "COPILOT_UPSELL_LEARN_MORE", "DEEP_LINK_ERROR_ACCOUNT_SWITCHER", "EXPLORE_BOTTOM_NAVIGATION", "EXPLORE_FEATURED_REPOSITORY", "EXPLORE_FOR_YOU_REPOSITORY", "EXPLORE_STAR_FEATURED_REPOSITORY", "EXPLORE_STAR_FOR_YOU_REPOSITORY", "EXPLORE_STAR_TRENDING_REPOSITORY", "EXPLORE_TRENDING_LIST_FILTER", "EXPLORE_TRENDING_REPOSITORY", "FINISH_REVIEW_BOA", "FOCUS_CTA_DISMISSED", "FOCUS_CTA_ENABLED", "FOCUS_CTA_VIEWED", "FOLLOW", "GLOBAL_SEARCH_SHORTCUT", "HOME_BOTTOM_NAVIGATION", "HOME_CREATE_ISSUE", "HOME_DISCUSSIONS", "HOME_FAVORITE_REPOSITORY_ITEM", "HOME_IN_APP_UPDATE", "HOME_ISSUES", "HOME_ISSUES_LIST_NEW_ISSUE", "HOME_ORGANIZATIONS", "HOME_PROJECTS", "HOME_PULL_REQUESTS", "HOME_RECENT_ACTIVITY_ITEM", "HOME_RELEASE_NOTES", "HOME_REPOSITORIES", "HOME_REPOSITORY_LIST_FILTER", "HOME_SHORTCUTS", "HOME_STARRED", "ISSUES_LIST_ITEM", "ISSUES_SEARCH", "ISSUE_COMPOSER", "ISSUE_COMPOSER_PROPERTY_BAR", "NOTIFICATIONS_ONBOARDING_BANNER", "NOTIFICATION_BOTTOM_NAVIGATION", "NOTIFICATION_FILTER", "NOTIFICATION_LIST", "NOTIFICATION_LIST_FILTER", "NOTIFICATION_LIST_ITEM", "NOTIFICATION_LIST_ITEM_FOCUSED", "NOTIFICATION_LIST_ITEM_UNDO", "NOTIFICATION_ONBOARDING_CONTINUE_BANNER", "NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER", "NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER", "NOTIFICATION_ONBOARDING_NUX_BANNER", "NOTIFICATION_ONBOARDING_PROGRESS", "NOTIFICATION_ONBOARDING_PROGRESS_REVIEW", "NOTIFICATION_ONBOARDING_RECAPTURE", "NOTIFICATION_ONBOARDING_REVIEW_BANNER", "NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS", "NOTIFICATION_PUSH", "ONBOARDING_BANNER", "PIN_SHORTCUT", "PROFILE_BOTTOM_NAVIGATION", "PROFILE_HEADER_NAME", "PROFILE_REPOSITORY_LIST_FILTER", "PROJECTS_LIST_ITEM", "PROJECTS_QUICK_ACTION_CLOSE", "PROJECTS_QUICK_ACTION_DELETE", "PROJECTS_QUICK_ACTION_EDIT_FIELD", "PROJECTS_QUICK_ACTION_EDIT_TITLE", "PROJECTS_QUICK_ACTION_OPEN_DETAILS", "PROJECTS_QUICK_ACTION_OTHER_PROJECTS", "PROJECTS_QUICK_ACTION_REOPEN", "PROJECTS_TABLE_VIEW_LIST_ITEM", "PROJECT_VIEW", "PROJECT_VIEW_TIMEOUT_CTA", "PULL_REQUESTS_LIST_ITEM", "PULL_REQUESTS_SEARCH", "PULL_REQUEST_COMPOSER_SUBMIT", "PULL_REQUEST_FILES_CHANGED", "PULL_REQUEST_LEGACY_CREATION_SUBMIT", "PULL_REQUEST_REVIEW_BANNER", "PULL_REQUEST_REVIEW_CTA", "PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW", "PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY", "RELEASES_LIST_LATEST_RELEASE", "RELEASE_DOWNLOAD_ASSET", "RELEASE_LINKED_DISCUSSION", "REPOSITORY_DISCUSSIONS_LIST_FILTER", "REPOSITORY_EDIT_README", "REPOSITORY_ISSUES_LIST_FILTER", "REPOSITORY_LATEST_RELEASE", "REPOSITORY_PULL_REQUESTS_LIST_FILTER", "SETTINGS_ACCOUNTS", "SETTINGS_DISABLE_ANALYTICS", "SETTINGS_ENABLE_APP_LOCK", "SHORTCUTS_LIST_ITEM", "SHORTCUT_SUGGESTIONS_LIST_ITEM", "SHOW_MORE_ROLLUP", "STAR_REPOSITORY", "SUBMIT_REVIEW", "SUB_ISSUE_ADD_EXISTING_ISSUE", "SUB_ISSUE_ADD_NEW_ISSUE", "SUB_ISSUE_EDIT_PARENT_ISSUE", "SUB_ISSUE_EDIT_SUB_ISSUE", "SUB_ISSUE_ISSUE", "SUB_ISSUE_NESTED_ISSUES_TOGGLE", "SUB_ISSUE_PARENT_ISSUE", "SUB_ISSUE_SECTION", "TRIAGE_ASSIGNEE_EDIT", "TRIAGE_CLOSE", "TRIAGE_COMMENT", "TRIAGE_COMMENT_DOWN", "TRIAGE_COMMENT_EDIT", "TRIAGE_COMMENT_UP", "TRIAGE_EXPAND", "TRIAGE_ISSUE_TYPE_EDIT", "TRIAGE_LABEL_EDIT", "TRIAGE_LINKED_ITEM_EDIT", "TRIAGE_LOCK", "TRIAGE_MILESTONE_EDIT", "TRIAGE_PROJECT_EDIT", "TRIAGE_PROJECT_NEXT_EDIT", "TRIAGE_PROJECT_NEXT_PICKER_OWNER", "TRIAGE_PROJECT_NEXT_PICKER_RECENT", "TRIAGE_REVIEW_REQUEST_EDIT", "TRIAGE_UNSUBSCRIBE", "VIEWER_DISCUSSIONS_LIST_FILTER", "VIEWER_ISSUES_LIST_FILTER", "VIEWER_PULL_REQUESTS_LIST_FILTER", "VIEWER_PULL_TO_REFRESH", "VIEWING_AS_TOAST"});
    }

    public mj(String str, int i, String str2) {
        this.r = str2;
    }

    public static mj valueOf(String str) {
        return (mj) Enum.valueOf(mj.class, str);
    }

    public static mj[] values() {
        return (mj[]) t.clone();
    }
}
