package pz0;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class nk {
    public static final nk A;
    public static final nk A0;
    public static final nk B;
    public static final nk B0;
    public static final nk C;
    public static final nk C0;
    public static final mk Companion;
    public static final nk D;
    public static final nk D0;
    public static final nk E;
    public static final nk E0;
    public static final nk F;
    public static final nk F0;
    public static final nk G;
    public static final nk G0;
    public static final nk H;
    public static final nk H0;
    public static final nk I;
    public static final nk I0;
    public static final nk J;
    public static final nk J0;
    public static final nk K;
    public static final nk K0;
    public static final nk L;
    public static final nk L0;
    public static final nk M;
    public static final nk M0;
    public static final nk N;
    public static final nk N0;
    public static final nk O;
    public static final nk O0;
    public static final nk P;
    public static final nk P0;
    public static final nk Q;
    public static final nk Q0;
    public static final nk R;
    public static final nk R0;
    public static final nk S;
    public static final nk S0;
    public static final nk T;
    public static final nk T0;
    public static final nk U;
    public static final nk U0;
    public static final nk V;
    public static final nk V0;
    public static final nk W;
    public static final nk W0;
    public static final nk X;
    public static final nk X0;
    public static final nk Y;
    public static final nk Y0;
    public static final nk Z;
    public static final nk Z0;
    public static final nk a0;
    public static final /* synthetic */ nk[] a1;
    public static final nk b0;
    public static final /* synthetic */ d71.b b1;
    public static final nk c0;
    public static final nk d0;
    public static final nk e0;
    public static final nk f0;
    public static final nk g0;
    public static final nk h0;
    public static final nk i0;
    public static final nk j0;
    public static final nk k0;
    public static final nk l0;
    public static final nk m0;
    public static final nk n0;
    public static final nk o0;
    public static final nk p0;
    public static final nk q0;
    public static final nk r0;
    public static final nk s;
    public static final nk s0;
    public static final nk t;
    public static final nk t0;
    public static final nk u;
    public static final nk u0;
    public static final nk v;
    public static final nk v0;
    public static final nk w;
    public static final nk w0;
    public static final nk x;
    public static final nk x0;
    public static final nk y;
    public static final nk y0;
    public static final nk z;
    public static final nk z0;
    public final String r;

    static {
        nk nkVar = new nk("BRANCHES", 0, "BRANCHES");
        s = nkVar;
        nk nkVar2 = new nk("CHECK_SUITE", 1, "CHECK_SUITE");
        t = nkVar2;
        nk nkVar3 = new nk("CODE", 2, "CODE");
        u = nkVar3;
        nk nkVar4 = new nk("COMMIT", 3, "COMMIT");
        v = nkVar4;
        nk nkVar5 = new nk("COMMITS", 4, "COMMITS");
        w = nkVar5;
        nk nkVar6 = new nk("COPILOT_PAYWALL", 5, "COPILOT_PAYWALL");
        x = nkVar6;
        nk nkVar7 = new nk("COPILOT_SETTINGS", 6, "COPILOT_SETTINGS");
        y = nkVar7;
        nk nkVar8 = new nk("COPILOT_UPSELL", 7, "COPILOT_UPSELL");
        z = nkVar8;
        nk nkVar9 = new nk("DEEP_LINK", 8, "DEEP_LINK");
        A = nkVar9;
        nk nkVar10 = new nk("DEPLOYMENT_REVIEW", 9, "DEPLOYMENT_REVIEW");
        B = nkVar10;
        nk nkVar11 = new nk("DIFF", 10, "DIFF");
        C = nkVar11;
        nk nkVar12 = new nk("DISCUSSION", 11, "DISCUSSION");
        D = nkVar12;
        nk nkVar13 = new nk("DISCUSSIONS", 12, "DISCUSSIONS");
        E = nkVar13;
        nk nkVar14 = new nk("DRAFT_ISSUE", 13, "DRAFT_ISSUE");
        F = nkVar14;
        nk nkVar15 = new nk("FEED", 14, "FEED");
        G = nkVar15;
        nk nkVar16 = new nk("FILE", 15, "FILE");
        H = nkVar16;
        nk nkVar17 = new nk("FILTER_ASSIGNEE", 16, "FILTER_ASSIGNEE");
        I = nkVar17;
        nk nkVar18 = new nk("FILTER_AUTHOR", 17, "FILTER_AUTHOR");
        J = nkVar18;
        nk nkVar19 = new nk("FILTER_DISCUSSION_CATEGORY", 18, "FILTER_DISCUSSION_CATEGORY");
        K = nkVar19;
        nk nkVar20 = new nk("FILTER_DISCUSSION_IS_UNANSWERED", 19, "FILTER_DISCUSSION_IS_UNANSWERED");
        L = nkVar20;
        nk nkVar21 = new nk("FILTER_DISCUSSION_TOP", 20, "FILTER_DISCUSSION_TOP");
        M = nkVar21;
        nk nkVar22 = new nk("FILTER_DISCUSSION_VIEWER", 21, "FILTER_DISCUSSION_VIEWER");
        N = nkVar22;
        nk nkVar23 = new nk("FILTER_ISSUE_STATUS", 22, "FILTER_ISSUE_STATUS");
        O = nkVar23;
        nk nkVar24 = new nk("FILTER_ISSUE_TYPE", 23, "FILTER_ISSUE_TYPE");
        P = nkVar24;
        nk nkVar25 = new nk("FILTER_ISSUE_VIEWER", 24, "FILTER_ISSUE_VIEWER");
        Q = nkVar25;
        nk nkVar26 = new nk("FILTER_LABEL", 25, "FILTER_LABEL");
        R = nkVar26;
        nk nkVar27 = new nk("FILTER_LANGUAGE", 26, "FILTER_LANGUAGE");
        S = nkVar27;
        nk nkVar28 = new nk("FILTER_MILESTONE", 27, "FILTER_MILESTONE");
        T = nkVar28;
        nk nkVar29 = new nk("FILTER_NOTIFICATION_FILTER", 28, "FILTER_NOTIFICATION_FILTER");
        U = nkVar29;
        nk nkVar30 = new nk("FILTER_NOTIFICATION_FOCUSED", 29, "FILTER_NOTIFICATION_FOCUSED");
        V = nkVar30;
        nk nkVar31 = new nk("FILTER_NOTIFICATION_IS_UNREAD", 30, "FILTER_NOTIFICATION_IS_UNREAD");
        W = nkVar31;
        nk nkVar32 = new nk("FILTER_NOTIFICATION_STATUS", 31, "FILTER_NOTIFICATION_STATUS");
        X = nkVar32;
        nk nkVar33 = new nk("FILTER_ORGANIZATION", 32, "FILTER_ORGANIZATION");
        Y = nkVar33;
        nk nkVar34 = new nk("FILTER_PROJECT", 33, "FILTER_PROJECT");
        Z = nkVar34;
        nk nkVar35 = new nk("FILTER_PULL_REQUEST_REVIEW_STATUS", 34, "FILTER_PULL_REQUEST_REVIEW_STATUS");
        a0 = nkVar35;
        nk nkVar36 = new nk("FILTER_PULL_REQUEST_STATUS", 35, "FILTER_PULL_REQUEST_STATUS");
        b0 = nkVar36;
        nk nkVar37 = new nk("FILTER_PULL_REQUEST_VIEWER", 36, "FILTER_PULL_REQUEST_VIEWER");
        c0 = nkVar37;
        nk nkVar38 = new nk("FILTER_REPOSITORY", 37, "FILTER_REPOSITORY");
        d0 = nkVar38;
        nk nkVar39 = new nk("FILTER_REPOSITORY_TYPE", 38, "FILTER_REPOSITORY_TYPE");
        e0 = nkVar39;
        nk nkVar40 = new nk("FILTER_REPOSITORY_VISIBILITY", 39, "FILTER_REPOSITORY_VISIBILITY");
        f0 = nkVar40;
        nk nkVar41 = new nk("FILTER_SORT", 40, "FILTER_SORT");
        g0 = nkVar41;
        nk nkVar42 = new nk("FILTER_TRENDING_DATE_RANGE", 41, "FILTER_TRENDING_DATE_RANGE");
        h0 = nkVar42;
        nk nkVar43 = new nk("FILTER_TRENDING_LANGUAGE", 42, "FILTER_TRENDING_LANGUAGE");
        i0 = nkVar43;
        nk nkVar44 = new nk("FILTER_TRENDING_SPOKEN_LANGUAGE", 43, "FILTER_TRENDING_SPOKEN_LANGUAGE");
        j0 = nkVar44;
        nk nkVar45 = new nk("GIST", 44, "GIST");
        k0 = nkVar45;
        nk nkVar46 = new nk("GLOBAL_SEARCH", 45, "GLOBAL_SEARCH");
        l0 = nkVar46;
        nk nkVar47 = new nk("HOME", 46, "HOME");
        m0 = nkVar47;
        nk nkVar48 = new nk("ISSUE", 47, "ISSUE");
        n0 = nkVar48;
        nk nkVar49 = new nk("ISSUES", 48, "ISSUES");
        o0 = nkVar49;
        nk nkVar50 = new nk("JUMP_TO", 49, "JUMP_TO");
        p0 = nkVar50;
        nk nkVar51 = new nk("NAVIGATION_BAR", 50, "NAVIGATION_BAR");
        q0 = nkVar51;
        nk nkVar52 = new nk("NOTIFICATIONS", 51, "NOTIFICATIONS");
        r0 = nkVar52;
        nk nkVar53 = new nk("ORGANIZATION", 52, "ORGANIZATION");
        s0 = nkVar53;
        nk nkVar54 = new nk("ORGANIZATIONS", 53, "ORGANIZATIONS");
        t0 = nkVar54;
        nk nkVar55 = new nk("PROJECT", 54, "PROJECT");
        u0 = nkVar55;
        nk nkVar56 = new nk("PROJECTS", 55, "PROJECTS");
        v0 = nkVar56;
        nk nkVar57 = new nk("PULL_REQUEST", 56, "PULL_REQUEST");
        w0 = nkVar57;
        nk nkVar58 = new nk("PULL_REQUESTS", 57, "PULL_REQUESTS");
        x0 = nkVar58;
        nk nkVar59 = new nk("PUSH_NOTIFICATIONS", 58, "PUSH_NOTIFICATIONS");
        y0 = nkVar59;
        nk nkVar60 = new nk("PUSH_NOTIFICATION_ACTION", 59, "PUSH_NOTIFICATION_ACTION");
        z0 = nkVar60;
        nk nkVar61 = new nk("PUSH_NOTIFICATION_ASSIGN", 60, "PUSH_NOTIFICATION_ASSIGN");
        A0 = nkVar61;
        nk nkVar62 = new nk("PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", 61, "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL");
        B0 = nkVar62;
        nk nkVar63 = new nk("PUSH_NOTIFICATION_MENTION", 62, "PUSH_NOTIFICATION_MENTION");
        C0 = nkVar63;
        nk nkVar64 = new nk("PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", 63, "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST");
        D0 = nkVar64;
        nk nkVar65 = new nk("PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", 64, "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW");
        E0 = nkVar65;
        nk nkVar66 = new nk("PUSH_NOTIFICATION_RELEASE", 65, "PUSH_NOTIFICATION_RELEASE");
        F0 = nkVar66;
        nk nkVar67 = new nk("PUSH_NOTIFICATION_REVIEW_REQUEST", 66, "PUSH_NOTIFICATION_REVIEW_REQUEST");
        G0 = nkVar67;
        nk nkVar68 = new nk("RELEASE", 67, "RELEASE");
        H0 = nkVar68;
        nk nkVar69 = new nk("RELEASES", 68, "RELEASES");
        I0 = nkVar69;
        nk nkVar70 = new nk("REPOSITORIES", 69, "REPOSITORIES");
        J0 = nkVar70;
        nk nkVar71 = new nk("REPOSITORY", 70, "REPOSITORY");
        K0 = nkVar71;
        nk nkVar72 = new nk("REPOSITORY_ADVISORY", 71, "REPOSITORY_ADVISORY");
        L0 = nkVar72;
        nk nkVar73 = new nk("REPOSITORY_DEPENDABOT_THREAD_ALERT", 72, "REPOSITORY_DEPENDABOT_THREAD_ALERT");
        M0 = nkVar73;
        nk nkVar74 = new nk("REPOSITORY_VULNERABILITY_ALERT", 73, "REPOSITORY_VULNERABILITY_ALERT");
        N0 = nkVar74;
        nk nkVar75 = new nk("SECURITY_ADVISORY", 74, "SECURITY_ADVISORY");
        O0 = nkVar75;
        nk nkVar76 = new nk("SETTINGS", 75, "SETTINGS");
        P0 = nkVar76;
        nk nkVar77 = new nk("SHORTCUT", 76, "SHORTCUT");
        Q0 = nkVar77;
        nk nkVar78 = new nk("SUBMIT_REVIEW_SHEET", 77, "SUBMIT_REVIEW_SHEET");
        R0 = nkVar78;
        nk nkVar79 = new nk("SUB_ISSUE", 78, "SUB_ISSUE");
        S0 = nkVar79;
        nk nkVar80 = new nk("SWIPE_ACTIONS", 79, "SWIPE_ACTIONS");
        T0 = nkVar80;
        nk nkVar81 = new nk("TEAM_DISCUSSION", 80, "TEAM_DISCUSSION");
        U0 = nkVar81;
        nk nkVar82 = new nk("TOAST", 81, "TOAST");
        V0 = nkVar82;
        nk nkVar83 = new nk("USER", 82, "USER");
        W0 = nkVar83;
        nk nkVar84 = new nk("USERS", 83, "USERS");
        X0 = nkVar84;
        nk nkVar85 = new nk("WORKFLOW_RUN", 84, "WORKFLOW_RUN");
        Y0 = nkVar85;
        nk nkVar86 = new nk("UNKNOWN__", 85, "UNKNOWN__");
        Z0 = nkVar86;
        nk[] nkVarArr = {nkVar, nkVar2, nkVar3, nkVar4, nkVar5, nkVar6, nkVar7, nkVar8, nkVar9, nkVar10, nkVar11, nkVar12, nkVar13, nkVar14, nkVar15, nkVar16, nkVar17, nkVar18, nkVar19, nkVar20, nkVar21, nkVar22, nkVar23, nkVar24, nkVar25, nkVar26, nkVar27, nkVar28, nkVar29, nkVar30, nkVar31, nkVar32, nkVar33, nkVar34, nkVar35, nkVar36, nkVar37, nkVar38, nkVar39, nkVar40, nkVar41, nkVar42, nkVar43, nkVar44, nkVar45, nkVar46, nkVar47, nkVar48, nkVar49, nkVar50, nkVar51, nkVar52, nkVar53, nkVar54, nkVar55, nkVar56, nkVar57, nkVar58, nkVar59, nkVar60, nkVar61, nkVar62, nkVar63, nkVar64, nkVar65, nkVar66, nkVar67, nkVar68, nkVar69, nkVar70, nkVar71, nkVar72, nkVar73, nkVar74, nkVar75, nkVar76, nkVar77, nkVar78, nkVar79, nkVar80, nkVar81, nkVar82, nkVar83, nkVar84, nkVar85, nkVar86};
        a1 = nkVarArr;
        b1 = v8.l0.t(nkVarArr);
        Companion = new mk();
        sy.d0.o(new String[]{"BRANCHES", "CHECK_SUITE", "CODE", "COMMIT", "COMMITS", "COPILOT_PAYWALL", "COPILOT_SETTINGS", "COPILOT_UPSELL", "DEEP_LINK", "DEPLOYMENT_REVIEW", "DIFF", "DISCUSSION", "DISCUSSIONS", "DRAFT_ISSUE", "FEED", "FILE", "FILTER_ASSIGNEE", "FILTER_AUTHOR", "FILTER_DISCUSSION_CATEGORY", "FILTER_DISCUSSION_IS_UNANSWERED", "FILTER_DISCUSSION_TOP", "FILTER_DISCUSSION_VIEWER", "FILTER_ISSUE_STATUS", "FILTER_ISSUE_TYPE", "FILTER_ISSUE_VIEWER", "FILTER_LABEL", "FILTER_LANGUAGE", "FILTER_MILESTONE", "FILTER_NOTIFICATION_FILTER", "FILTER_NOTIFICATION_FOCUSED", "FILTER_NOTIFICATION_IS_UNREAD", "FILTER_NOTIFICATION_STATUS", "FILTER_ORGANIZATION", "FILTER_PROJECT", "FILTER_PULL_REQUEST_REVIEW_STATUS", "FILTER_PULL_REQUEST_STATUS", "FILTER_PULL_REQUEST_VIEWER", "FILTER_REPOSITORY", "FILTER_REPOSITORY_TYPE", "FILTER_REPOSITORY_VISIBILITY", "FILTER_SORT", "FILTER_TRENDING_DATE_RANGE", "FILTER_TRENDING_LANGUAGE", "FILTER_TRENDING_SPOKEN_LANGUAGE", "GIST", "GLOBAL_SEARCH", "HOME", "ISSUE", "ISSUES", "JUMP_TO", "NAVIGATION_BAR", "NOTIFICATIONS", "ORGANIZATION", "ORGANIZATIONS", "PROJECT", "PROJECTS", "PULL_REQUEST", "PULL_REQUESTS", "PUSH_NOTIFICATIONS", "PUSH_NOTIFICATION_ACTION", "PUSH_NOTIFICATION_ASSIGN", "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", "PUSH_NOTIFICATION_MENTION", "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", "PUSH_NOTIFICATION_RELEASE", "PUSH_NOTIFICATION_REVIEW_REQUEST", "RELEASE", "RELEASES", "REPOSITORIES", "REPOSITORY", "REPOSITORY_ADVISORY", "REPOSITORY_DEPENDABOT_THREAD_ALERT", "REPOSITORY_VULNERABILITY_ALERT", "SECURITY_ADVISORY", "SETTINGS", "SHORTCUT", "SUBMIT_REVIEW_SHEET", "SUB_ISSUE", "SWIPE_ACTIONS", "TEAM_DISCUSSION", "TOAST", "USER", "USERS", "WORKFLOW_RUN"});
    }

    public nk(String str, int i, String str2) {
        this.r = str2;
    }

    public static nk valueOf(String str) {
        return (nk) Enum.valueOf(nk.class, str);
    }

    public static nk[] values() {
        return (nk[]) a1.clone();
    }
}
