package kz0;

import java.util.List;
import pz0.cu;
import pz0.dt;
import pz0.ft;
import pz0.h50;
import pz0.hs;
import pz0.ht;
import pz0.kt;
import pz0.ld;
import pz0.mt;
import pz0.pd;
import pz0.q9;
import pz0.sk;
import pz0.td;
import pz0.vd;
import pz0.w80;
import pz0.xd;
import pz0.yt;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class j {
    public static final List a;

    static {
        td.Companion.getClass();
        aa.x xVar = td.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        aa.x xVar2 = xd.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("login", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        vd.Companion.getClass();
        aa.x xVar3 = vd.a;
        List n = sy.d0Shadow.n(new aa.m("totalCount", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar2 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        ht.Companion.getClass();
        aa.q0 q0Var = ht.a;
        aa.r b2 = v8.l0.b(q0Var);
        dt.Companion.getClass();
        List r3 = x61.l.r(new aa.m[]{mVar2, new aa.m("comments", b2, (String) null, rVar, no.a.s(dt.a, new aa.u0(1)), n), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.q0 q0Var2 = dt.d;
        List n2 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(q0Var2), (String) null, rVar, rVar, r3));
        aa.s mVar3 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar4 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0Shadow.n("PullRequest");
        List list = yt0.d.a;
        aa.s c = no.a.c(list, "selections", "PullRequest", n3, list);
        ld.Companion.getClass();
        aa.s mVar5 = new aa.m("headRefOid", v8.l0.b(ld.a), (String) null, rVar, rVar, rVar);
        mt.Companion.getClass();
        aa.q0 q0Var3 = mt.a;
        k71.k.g(q0Var3, "type");
        hs.Companion.getClass();
        List r4 = x61.l.r(new aa.s[]{mVar3, mVar4, c, mVar5, new aa.m("reviews", q0Var3, "pendingReviews", rVar, x61.l.r(new aa.k[]{new aa.k(hs.A, new aa.u0(1)), new aa.k(hs.B, new aa.u0(sy.d0Shadow.n("PENDING")))}), n2)});
        aa.s mVar6 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n4 = sy.d0Shadow.n("DiffLine");
        List list2 = xq0.a.a;
        List r5 = x61.l.r(new aa.s[]{mVar6, no.a.c(list2, "selections", "DiffLine", n4, list2)});
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ft.Companion.getClass();
        aa.q0 q0Var4 = ft.a;
        List n5 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(q0Var4), (String) null, rVar, rVar, r6));
        aa.s mVar7 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar8 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        aa.x xVar4 = pd.a;
        aa.s mVar9 = new aa.m("isResolved", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        w80.Companion.getClass();
        aa.q0 q0Var5 = w80.W;
        k71.k.g(q0Var5, "type");
        aa.s mVar10 = new aa.m("resolvedBy", q0Var5, (String) null, rVar, rVar, r2);
        aa.s mVar11 = new aa.m("viewerCanResolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar12 = new aa.m("viewerCanUnresolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("pullRequest", v8.l0.b(hs.N), (String) null, rVar, rVar, r4);
        q9.Companion.getClass();
        aa.p a2 = v8.l0.a(q9.a);
        yt.Companion.getClass();
        aa.s mVar14 = new aa.m("diffLines", a2, (String) null, rVar, no.a.s(yt.c, new aa.u0(1)), r5);
        List n6 = sy.d0Shadow.n("PullRequestReviewThread");
        List list3 = fu0.a.a;
        List r7 = x61.l.r(new aa.s[]{mVar7, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, no.a.c(list3, "selections", "PullRequestReviewThread", n6, list3), new aa.m("comments", v8.l0.b(q0Var), (String) null, rVar, no.a.s(yt.b, new aa.u0(2)), n5)});
        aa.s mVar15 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar16 = new aa.m("pullRequestReview", q0Var2, (String) null, rVar, rVar, r);
        cu.Companion.getClass();
        aa.s mVar17 = new aa.m("subjectType", v8.l0.b(cu.s), (String) null, rVar, rVar, rVar);
        aa.s mVar18 = new aa.m("position", xVar3, (String) null, rVar, rVar, rVar);
        aa.q0 q0Var6 = yt.d;
        k71.k.g(q0Var6, "type");
        aa.s mVar19 = new aa.m("thread", q0Var6, (String) null, rVar, rVar, r7);
        aa.s mVar20 = new aa.m("path", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        kt.Companion.getClass();
        aa.s mVar21 = new aa.m("state", v8.l0.b(kt.s), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        aa.s mVar22 = new aa.m("url", v8.l0.b(h50.a), (String) null, rVar, rVar, rVar);
        List r8 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list4 = hu0.a.a;
        aa.s c2 = no.a.c(list4, "selections", "Reactable", r8, list4);
        List r9 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list5 = zp0.a.a;
        aa.s c3 = no.a.c(list5, "selections", "Comment", r9, list5);
        List r10 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list6 = cw0.b.a;
        aa.s c4 = no.a.c(list6, "selections", "Updatable", r10, list6);
        List r12 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"});
        List list7 = bt0.a.a;
        List n7 = sy.d0Shadow.n(new aa.m("comment", q0Var4, (String) null, rVar, rVar, x61.l.r(new aa.s[]{mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, c2, c3, c4, no.a.c(list7, "selections", "Minimizable", r12, list7), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)})));
        pz0.d0.Companion.getClass();
        aa.q0 q0Var7 = pz0.d0.a;
        k71.k.g(q0Var7, "type");
        sk.Companion.getClass();
        a = sy.d0Shadow.n(new aa.m("addPullRequestReviewThreadReply", q0Var7, (String) null, rVar, no.a.s(sk.i, new aa.u0(x61.x.u(new w61.k("body", new aa.t("body")), new w61.k("pullRequestReviewThreadId", new aa.t("threadId"))))), n7));
    }
}
