package kz0;

import java.util.List;
import pz0.aw;
import pz0.ba;
import pz0.c90;
import pz0.cw;
import pz0.ew;
import pz0.fd;
import pz0.h50;
import pz0.hm;
import pz0.ja;
import pz0.jd;
import pz0.jx;
import pz0.la;
import pz0.ld;
import pz0.mv;
import pz0.nd;
import pz0.ny;
import pz0.o7;
import pz0.pd;
import pz0.su;
import pz0.td;
import pz0.vd;
import pz0.w80;
import pz0.xd;
import pz0.zd;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class k3 {
    public static final List a;

    static {
        xd.Companion.getClass();
        aa.x xVar = xd.a;
        aa.r b = v8.l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        aa.x xVar2 = td.a;
        aa.s mVar2 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.b.a;
        List r2 = x61.l.r(new aa.s[]{mVar, mVar2, no.a.c(list, "selections", "Actor", r, list)});
        pd.Companion.getClass();
        aa.x xVar3 = pd.a;
        List n = sy.d0.n(new aa.m("isValid", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar3 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ld.Companion.getClass();
        aa.x xVar4 = ld.a;
        aa.m mVar4 = new aa.m("oid", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("abbreviatedOid", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        nd.Companion.getClass();
        aa.j0 j0Var = nd.a;
        k71.k.g(j0Var, "type");
        aa.m mVar6 = new aa.m("signature", j0Var, (String) null, rVar, rVar, n);
        aa.m mVar7 = new aa.m("message", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        zd.Companion.getClass();
        aa.x xVar5 = zd.a;
        aa.m mVar8 = new aa.m("messageBodyHTML", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        aa.x xVar6 = o7.a;
        List r3 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("Commit", sy.d0.n("Commit"), x61.l.r(new aa.m[]{mVar3, mVar4, mVar5, mVar6, mVar7, mVar8, new aa.m("authoredDate", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar)}))});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r4 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = dp0.a.a;
        List r5 = x61.l.r(new aa.s[]{mVar9, no.a.c(list2, "selections", "Actor", r4, list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        w80.Companion.getClass();
        aa.q0 q0Var = w80.W;
        k71.k.g(q0Var, "type");
        List n2 = sy.d0.n(new aa.m("user", q0Var, (String) null, rVar, rVar, r5));
        aa.m mVar10 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        jd.Companion.getClass();
        aa.j0 j0Var2 = jd.a;
        aa.m mVar11 = new aa.m("target", v8.l0.b(j0Var2), (String) null, rVar, rVar, r3);
        aa.m mVar12 = new aa.m("message", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        aa.x xVar7 = h50.a;
        aa.m mVar14 = new aa.m("commitUrl", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar);
        fd.Companion.getClass();
        aa.q0 q0Var2 = fd.a;
        k71.k.g(q0Var2, "type");
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("target", j0Var2, (String) null, rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("Tag", sy.d0.n("Tag"), x61.l.r(new aa.m[]{mVar10, mVar11, mVar12, mVar13, mVar14, new aa.m("tagger", q0Var2, (String) null, rVar, rVar, n2)}))})), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("oid", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("abbreviatedOid", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r8 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar, (String) null, rVar, rVar, rVar)});
        aa.m mVar15 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        aa.x xVar8 = vd.a;
        List r10 = x61.l.r(new aa.m[]{mVar15, mVar16, new aa.m("size", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar), new aa.m("url", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar), new aa.m("contentType", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        hm.Companion.getClass();
        aa.m mVar17 = new aa.m("pageInfo", v8.l0.b(hm.a), (String) null, rVar, rVar, r9);
        cw.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar17, new aa.m("nodes", v8.l0.a(cw.a), (String) null, rVar, rVar, r10)});
        List r13 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2)});
        aa.s mVar18 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar19 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        pz0.l.Companion.getClass();
        aa.j0 j0Var3 = pz0.l.a;
        k71.k.g(j0Var3, "type");
        aa.s mVar20 = new aa.m("author", j0Var3, (String) null, rVar, rVar, r13);
        aa.s mVar21 = new aa.m("createdAt", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("lastEditedAt", xVar6, (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("body", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"});
        List list3 = bt0.a.a;
        List r15 = x61.l.r(new aa.s[]{mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, no.a.c(list3, "selections", "Minimizable", r14, list3)});
        aa.m mVar24 = new aa.m("totalCount", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar);
        ja.Companion.getClass();
        List r16 = x61.l.r(new aa.m[]{mVar24, new aa.m("nodes", v8.l0.a(ja.c), (String) null, rVar, rVar, r15)});
        aa.m mVar25 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar26 = new aa.m("number", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar);
        la.Companion.getClass();
        aa.r b2 = v8.l0.b(la.a);
        ba.Companion.getClass();
        List r17 = x61.l.r(new aa.m[]{mVar25, mVar26, new aa.m("comments", b2, (String) null, rVar, no.a.s(ba.h, new aa.u0(3)), r16), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r18 = x61.l.r(new aa.m[]{new aa.m("totalCount", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar), new aa.m("nodes", v8.l0.a(q0Var), (String) null, rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        aa.s mVar27 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar29 = new aa.m("url", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar30 = new aa.m("name", xVar, (String) null, rVar, rVar, rVar);
        aa.s mVar31 = new aa.m("tagName", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        pz0.s4.Companion.getClass();
        aa.q0 q0Var3 = pz0.s4.j;
        k71.k.g(q0Var3, "type");
        aa.s mVar32 = new aa.m("tagCommit", q0Var3, (String) null, rVar, rVar, r7);
        aa.s mVar33 = new aa.m("author", q0Var, (String) null, rVar, rVar, r8);
        List r19 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list4 = hu0.a.a;
        aa.s c = no.a.c(list4, "selections", "Reactable", r19, list4);
        k71.k.g(xVar5, "type");
        aa.s mVar34 = new aa.m("descriptionHTML", xVar5, (String) null, rVar, rVar, rVar);
        aa.s mVar35 = new aa.m("isPrerelease", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar36 = new aa.m("isDraft", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar37 = new aa.m("isLatest", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar38 = new aa.m("createdAt", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar6, "type");
        aa.s mVar39 = new aa.m("publishedAt", xVar6, (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        aa.r b3 = v8.l0.b(ew.a);
        aw.Companion.getClass();
        aa.s mVar40 = new aa.m("releaseAssets", b3, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(aw.c, new aa.u0(new aa.t("after"))), new aa.k(aw.d, new aa.u0(new aa.t("number")))}), r12);
        aa.q0 q0Var4 = ba.l;
        k71.k.g(q0Var4, "type");
        aa.s mVar41 = new aa.m("discussion", q0Var4, (String) null, rVar, rVar, r17);
        c90.Companion.getClass();
        aa.q0 q0Var5 = c90.a;
        k71.k.g(q0Var5, "type");
        List r20 = x61.l.r(new aa.s[]{mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, c, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, new aa.m("mentions", q0Var5, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(aw.a, new aa.u0((Object) null)), new aa.k(aw.b, new aa.u0(5))}), r18)});
        aa.m mVar42 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ny.Companion.getClass();
        aa.m mVar43 = new aa.m("owner", v8.l0.b(ny.e), (String) null, rVar, rVar, r2);
        mv.Companion.getClass();
        aa.q0 q0Var6 = mv.e;
        k71.k.g(q0Var6, "type");
        jx.Companion.getClass();
        aa.m mVar44 = new aa.m("ref", q0Var6, (String) null, rVar, no.a.s(jx.W, new aa.u0(new aa.t("tagName"))), r6);
        aa.q0 q0Var7 = aw.e;
        k71.k.g(q0Var7, "type");
        List r22 = x61.l.r(new aa.m[]{mVar42, mVar43, mVar44, new aa.m("release", q0Var7, (String) null, rVar, no.a.s(jx.c0, new aa.u0(new aa.t("tagName"))), r20), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.q0 q0Var8 = jx.t0;
        k71.k.g(q0Var8, "type");
        su.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("repository", q0Var8, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(su.l, new aa.u0(new aa.t("repositoryName"))), new aa.k(su.m, new aa.u0(new aa.t("repositoryOwner")))}), r22), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
