package kz0;

import java.util.List;
import pz0.a9;
import pz0.h50;
import pz0.ha0;
import pz0.hs;
import pz0.jx;
import pz0.ny;
import pz0.su;
import pz0.td;
import pz0.vd;
import pz0.w80;
import pz0.wk;
import pz0.xd;
import pz0.xs;
import pz0.y8;
import pz0.y90;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class r0 {
    public static final List a;

    static {
        xd.Companion.getClass();
        aa.x xVar = xd.a;
        aa.r b = v8.l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.a.a;
        List r2 = x61.l.r(new aa.s[]{mVar, no.a.c(list, "selections", "Actor", r, list)});
        ny.Companion.getClass();
        aa.m mVar2 = new aa.m("owner", v8.l0.b(ny.e), (String) null, rVar, rVar, r2);
        aa.m mVar3 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        aa.x xVar2 = td.a;
        List r3 = x61.l.r(new aa.m[]{mVar2, mVar3, new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r4 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = sy.d0.n("DeploymentRequest");
        List list2 = vq0.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar4, no.a.c(list2, "selections", "DeploymentRequest", n, list2)});
        y8.Companion.getClass();
        List n2 = sy.d0.n(new aa.m("nodes", v8.l0.a(y8.c), (String) null, rVar, rVar, r6));
        aa.m mVar5 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        aa.x xVar3 = h50.a;
        aa.m mVar6 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        aa.m mVar7 = new aa.m("runNumber", v8.l0.b(vd.a), (String) null, rVar, rVar, rVar);
        y90.Companion.getClass();
        aa.m mVar8 = new aa.m("workflow", v8.l0.b(y90.e), (String) null, rVar, rVar, r5);
        a9.Companion.getClass();
        aa.r b2 = v8.l0.b(a9.a);
        ha0.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, mVar8, new aa.m("pendingDeploymentRequests", b2, (String) null, rVar, no.a.s(ha0.a, new aa.u0(new aa.t("numberOfDeploymentRequests"))), n2), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0.n("CheckRun");
        List list3 = vp0.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar9, no.a.c(list3, "selections", "CheckRun", n3, list3), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        pz0.a3.Companion.getClass();
        List n4 = sy.d0.n(new aa.m("nodes", v8.l0.a(pz0.a3.f), (String) null, rVar, rVar, r8));
        aa.s mVar10 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n5 = sy.d0.n("PullRequest");
        List list4 = yt0.b.a;
        List r9 = x61.l.r(new aa.s[]{mVar10, no.a.c(list4, "selections", "PullRequest", n5, list4), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        hs.Companion.getClass();
        List n6 = sy.d0.n(new aa.m("nodes", v8.l0.a(hs.N), (String) null, rVar, rVar, r9));
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar12 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        pz0.e3.Companion.getClass();
        aa.m mVar13 = new aa.m("status", v8.l0.b(pz0.e3.s), (String) null, rVar, rVar, rVar);
        jx.Companion.getClass();
        aa.m mVar14 = new aa.m("repository", v8.l0.b(jx.t0), (String) null, rVar, rVar, r3);
        w80.Companion.getClass();
        aa.q0 q0Var = w80.W;
        k71.k.g(q0Var, "type");
        aa.m mVar15 = new aa.m("creator", q0Var, (String) null, rVar, rVar, r4);
        aa.q0 q0Var2 = ha0.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar16 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r7);
        pz0.c3.Companion.getClass();
        aa.q0 q0Var3 = pz0.c3.a;
        k71.k.g(q0Var3, "type");
        pz0.k3.Companion.getClass();
        aa.m mVar17 = new aa.m("checkRuns", q0Var3, (String) null, rVar, no.a.s(pz0.k3.c, new aa.u0(new aa.t("numberOfCheckRuns"))), n4);
        xs.Companion.getClass();
        aa.q0 q0Var4 = xs.a;
        k71.k.g(q0Var4, "type");
        List r10 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("CheckSuite", sy.d0.n("CheckSuite"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("matchingPullRequests", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(pz0.k3.d, new aa.u0(new aa.t("cursor"))), new aa.k(pz0.k3.e, new aa.u0(new aa.t("numberOfPullRequests")))}), n6)})), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        wk.Companion.getClass();
        aa.j0 j0Var = wk.a;
        k71.k.g(j0Var, "type");
        su.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(su.i, new aa.u0(new aa.t("nodeId"))), r10), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
