package kz0;

import java.util.List;
import pz0.f30;
import pz0.h30;
import pz0.h50;
import pz0.ha0;
import pz0.hm;
import pz0.hs;
import pz0.j30;
import pz0.l30;
import pz0.n30;
import pz0.nz;
import pz0.o7;
import pz0.pd;
import pz0.ps;
import pz0.pz;
import pz0.su;
import pz0.td;
import pz0.ts;
import pz0.vd;
import pz0.wk;
import pz0.xd;
import pz0.y90;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class v {
    public static final List a;

    static {
        td.Companion.getClass();
        aa.x xVar = td.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        aa.x xVar2 = xd.a;
        aa.m mVar2 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        n30.Companion.getClass();
        aa.a0 a0Var = n30.s;
        List r = x61.l.r(new aa.m[]{mVar, mVar2, new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar), new aa.m("description", xVar2, (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        vd.Companion.getClass();
        aa.x xVar3 = vd.a;
        aa.m mVar3 = new aa.m("totalCount", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        nz.Companion.getClass();
        List r2 = x61.l.r(new aa.m[]{mVar3, new aa.m("nodes", v8.l0.a(nz.a), (String) null, rVar, rVar, r)});
        pd.Companion.getClass();
        aa.x xVar4 = pd.a;
        List r3 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        aa.m mVar4 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar6 = new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        aa.x xVar5 = h50.a;
        k71.k.g(xVar5, "type");
        aa.m mVar7 = new aa.m("avatarUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.m mVar8 = new aa.m("description", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("targetUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.r b2 = v8.l0.b(xVar4);
        l30.Companion.getClass();
        List r4 = x61.l.r(new aa.m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(l30.a, new aa.u0(new aa.t("id"))), rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        y90.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{new aa.m("workflow", v8.l0.b(y90.e), (String) null, rVar, rVar, r5), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("logoUrl", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ha0.Companion.getClass();
        aa.q0 q0Var = ha0.b;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("workflowRun", q0Var, (String) null, rVar, rVar, r6);
        pz0.w0.Companion.getClass();
        aa.q0 q0Var2 = pz0.w0.a;
        k71.k.g(q0Var2, "type");
        List r8 = x61.l.r(new aa.m[]{mVar10, new aa.m("app", q0Var2, (String) null, rVar, rVar, r7), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        pz0.y2.Companion.getClass();
        aa.a0 a0Var2 = pz0.y2.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar12 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar14 = new aa.m("summary", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar15 = new aa.m("permalink", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("duration", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        pz0.k3.Companion.getClass();
        aa.m mVar17 = new aa.m("checkSuite", v8.l0.b(pz0.k3.f), (String) null, rVar, rVar, r8);
        aa.r b3 = v8.l0.b(xVar4);
        pz0.a3.Companion.getClass();
        List r9 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", sy.d0Shadow.n("StatusContext"), r4), new aa.n("CheckRun", sy.d0Shadow.n("CheckRun"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(pz0.a3.a, new aa.u0(new aa.t("id"))), rVar)}))});
        hm.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", v8.l0.b(hm.a), (String) null, rVar, rVar, r3);
        h30.Companion.getClass();
        List r10 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", v8.l0.a(h30.a), (String) null, rVar, rVar, r9)});
        aa.m mVar19 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        j30.Companion.getClass();
        aa.r b4 = v8.l0.b(j30.a);
        f30.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar19, new aa.m("contexts", b4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(f30.a, new aa.u0(new aa.t("after"))), new aa.k(f30.b, new aa.u0(25))}), r10), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        o7.Companion.getClass();
        aa.x xVar6 = o7.a;
        k71.k.g(xVar6, "type");
        aa.m mVar20 = new aa.m("pushedDate", xVar6, (String) null, rVar, rVar, rVar);
        aa.q0 q0Var3 = f30.c;
        k71.k.g(q0Var3, "type");
        List r13 = x61.l.r(new aa.m[]{mVar20, new aa.m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r12), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        pz0.s4.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{new aa.m("commit", v8.l0.b(pz0.s4.j), (String) null, rVar, rVar, r13), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ps.Companion.getClass();
        List n = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(ps.a), (String) null, rVar, rVar, r14));
        pz.Companion.getClass();
        aa.r b5 = v8.l0.b(pz.a);
        hs.Companion.getClass();
        aa.m mVar21 = new aa.m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(hs.x, new aa.u0(25)), r2);
        ts.Companion.getClass();
        List r15 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequest", sy.d0Shadow.n("PullRequest"), x61.l.r(new aa.m[]{mVar21, new aa.m("commits", v8.l0.b(ts.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(hs.j, new aa.u0((Object) null)), new aa.k(hs.l, new aa.u0(1))}), n)})), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        wk.Companion.getClass();
        aa.j0 j0Var = wk.a;
        k71.k.g(j0Var, "type");
        su.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(su.i, new aa.u0(new aa.t("id"))), r15), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
