package dd0;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import gn0.eq;
import gn0.hr;
import gn0.jj;
import gn0.jr;
import gn0.lb;
import gn0.mo;
import gn0.mx;
import gn0.n0;
import gn0.n2;
import gn0.pb;
import gn0.r6;
import gn0.rb;
import gn0.rn;
import gn0.t2;
import gn0.tb;
import gn0.u10;
import gn0.v2;
import gn0.x2;
import gn0.y10;
import gn0.yh;
import gn0.yv;
import java.util.List;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class a {
    public static final List a;

    static {
        pb.Companion.getClass();
        x xVar = pb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar2 = tb.a;
        List r = x61.l.r(new m[]{mVar, new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar2 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.a.a;
        List r3 = x61.l.r(new s[]{mVar2, no.a.c(list, "selections", "Actor", r2, list)});
        m mVar3 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar4 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hr.Companion.getClass();
        m mVar5 = new m("owner", l0.b(hr.a), (String) null, rVar, rVar, r3);
        jr.Companion.getClass();
        a0 a0Var = jr.s;
        k71.k.g(a0Var, "type");
        List r4 = x61.l.r(new m[]{mVar3, mVar4, mVar5, new m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new m[]{new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar6 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        x xVar3 = rb.a;
        m mVar7 = new m("runNumber", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        u10.Companion.getClass();
        List r6 = x61.l.r(new m[]{mVar6, mVar7, new m("workflow", l0.b(u10.c), (String) null, rVar, rVar, r5), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar8 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        List r7 = x61.l.r(new m[]{mVar8, new m("logoUrl", l0.b(mx.a), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar9 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        mo.Companion.getClass();
        q0 q0Var = mo.b;
        k71.k.g(q0Var, "type");
        m mVar10 = new m("branch", q0Var, (String) null, rVar, rVar, r);
        lb.Companion.getClass();
        x xVar4 = lb.a;
        m mVar11 = new m("rerunnable", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        m mVar12 = new m("repository", l0.b(eq.m0), (String) null, rVar, rVar, r4);
        y10.Companion.getClass();
        q0 q0Var2 = y10.b;
        k71.k.g(q0Var2, "type");
        m mVar13 = new m("workflowRun", q0Var2, (String) null, rVar, rVar, r6);
        n0.Companion.getClass();
        q0 q0Var3 = n0.a;
        k71.k.g(q0Var3, "type");
        List r8 = x61.l.r(new m[]{mVar9, mVar10, mVar11, mVar12, mVar13, new m("app", q0Var3, (String) null, rVar, rVar, r7), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new m[]{new m("hasNextPage", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("endCursor", xVar2, (String) null, rVar, rVar, rVar), new m("hasPreviousPage", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        s mVar14 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0.n("CheckStep");
        List list2 = xc0.a.a;
        List r10 = x61.l.r(new s[]{mVar14, no.a.c(list2, "selections", "CheckStep", n, list2)});
        m mVar15 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        jj.Companion.getClass();
        m mVar16 = new m("pageInfo", l0.b(jj.a), (String) null, rVar, rVar, r9);
        t2.Companion.getClass();
        List r12 = x61.l.r(new m[]{mVar15, mVar16, new m("nodes", l0.a(t2.a), (String) null, rVar, rVar, r10)});
        s mVar17 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("CheckRun");
        List list3 = xc0.f.a;
        s c = no.a.c(list3, "selections", "CheckRun", n2, list3);
        x2.Companion.getClass();
        s mVar18 = new m("checkSuite", l0.b(x2.f), (String) null, rVar, rVar, r8);
        v2.Companion.getClass();
        q0 q0Var4 = v2.a;
        k71.k.g(q0Var4, "type");
        n2.Companion.getClass();
        List r13 = x61.l.r(new s[]{mVar17, c, mVar18, new m("steps", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(n2.c, new u0(new t("afterSteps"))), new aa.k(n2.d, new u0(new t("first")))}), r12)});
        m mVar19 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar21 = new m("description", xVar2, (String) null, rVar, rVar, rVar);
        r6.Companion.getClass();
        m mVar22 = new m("createdAt", l0.b(r6.a), (String) null, rVar, rVar, rVar);
        yv.Companion.getClass();
        List r14 = x61.l.r(new m[]{mVar19, mVar20, mVar21, mVar22, new m("state", l0.b(yv.s), (String) null, rVar, rVar, rVar)});
        s mVar23 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s nVar = new n("CheckRun", d0.n("CheckRun"), r13);
        List n3 = d0.n("StatusContext");
        List list4 = xc0.e.a;
        List r15 = x61.l.r(new s[]{mVar23, nVar, no.a.c(list4, "selections", "StatusContext", n3, list4), new n("RequiredStatusCheck", d0.n("RequiredStatusCheck"), r14), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yh.Companion.getClass();
        j0 j0Var = yh.a;
        k71.k.g(j0Var, "type");
        rn.Companion.getClass();
        a = d0.n(new m("node", j0Var, (String) null, rVar, no.a.s(rn.i, new u0(new t("id"))), r15));
    }
}
