package x80;

import aa.a0;
import aa.j0;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import hc0.ap;
import hc0.bb;
import hc0.bo;
import hc0.db;
import hc0.dc;
import hc0.dd;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.fq;
import hc0.h6;
import hc0.hb;
import hc0.hq;
import hc0.jn;
import hc0.jq;
import hc0.ln;
import hc0.lq;
import hc0.qz;
import hc0.vn;
import hc0.xa;
import hc0.xk;
import hc0.yv;
import java.util.List;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class e {
    public static final List a;

    static {
        fb.Companion.getClass();
        x xVar = fb.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("Ref");
        List list = d.a;
        s c = no.a.c(list, "selections", "Ref", n, list);
        bb.Companion.getClass();
        x xVar2 = bb.a;
        List r = x61.l.r(new s[]{mVar, c, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Ref", d0Shadow.n("Ref"), list), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        db.Companion.getClass();
        x xVar3 = db.a;
        List n2 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        s mVar2 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar3 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar4 = new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r3 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = f30.b.a;
        List r4 = x61.l.r(new s[]{mVar2, mVar3, mVar4, no.a.c(list2, "selections", "Actor", r3, list2)});
        List n3 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List n4 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        hb.Companion.getClass();
        x xVar4 = hb.a;
        k71.k.g(xVar4, "type");
        List r5 = x61.l.r(new aa.m[]{new aa.m("contentHTML", xVar4, (String) null, rVar, rVar, rVar), new aa.m("path", xVar, (String) null, rVar, rVar, rVar)});
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yv.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{new aa.m("topic", l0.b(yv.a), (String) null, rVar, rVar, r6), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        jq.Companion.getClass();
        List n5 = d0Shadow.n(new aa.m("nodes", l0.a(jq.a), (String) null, rVar, rVar, r7));
        List n6 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n7 = d0Shadow.n("License");
        List list3 = h60.a.a;
        List r8 = x61.l.r(new s[]{mVar5, no.a.c(list3, "selections", "License", n7, list3), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar6 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        j0 j0Var = dq.a;
        List r11 = x61.l.r(new aa.m[]{mVar6, mVar7, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List n8 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("name", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar10 = new aa.m("tagName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        x xVar5 = h6.a;
        k71.k.g(xVar5, "type");
        List r12 = x61.l.r(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("publishedAt", xVar5, (String) null, rVar, rVar, rVar), new aa.m("createdAt", l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar12 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar13 = new aa.m("databaseId", xVar3, (String) null, rVar, rVar, rVar);
        List n9 = d0Shadow.n("Repository");
        List list4 = a.a;
        s c2 = no.a.c(list4, "selections", "Repository", n9, list4);
        s mVar14 = new aa.m("contributorsCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        jn.Companion.getClass();
        q0 q0Var = jn.b;
        k71.k.g(q0Var, "type");
        s mVar15 = new aa.m("defaultBranchRef", q0Var, (String) null, d0Shadow.n(new aa.l("defaultBranch", false)), rVar, r);
        List t = no.a.t("defaultBranch", true);
        ap.Companion.getClass();
        s mVar16 = new aa.m("ref", q0Var, "branchInfo", t, no.a.s(ap.O, new u0(new t("qualifiedName"))), r2);
        s mVar17 = new aa.m("forkCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar6 = xa.a;
        s mVar18 = new aa.m("hasIssuesEnabled", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar19 = new aa.m("showActions", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        x xVar7 = ew.a;
        k71.k.g(xVar7, "type");
        s mVar20 = new aa.m("homepageUrl", xVar7, (String) null, rVar, rVar, rVar);
        s mVar21 = new aa.m("isPrivate", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar22 = new aa.m("isArchived", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar23 = new aa.m("isTemplate", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar24 = new aa.m("isFork", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar25 = new aa.m("isEmpty", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar26 = new aa.m("isInOrganization", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        dc.Companion.getClass();
        s mVar27 = new aa.m("issues", l0.b(dc.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ap.q, new u0(0)), new aa.k(ap.r, new u0(d0Shadow.n("OPEN")))}), n2);
        s mVar28 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar29 = new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r4);
        xk.Companion.getClass();
        s mVar30 = new aa.m("pullRequests", l0.b(xk.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ap.L, new u0(0)), new aa.k(ap.M, new u0(d0Shadow.n("OPEN")))}), n3);
        ln.Companion.getClass();
        q0 q0Var2 = ln.a;
        k71.k.g(q0Var2, "type");
        s mVar31 = new aa.m("refs", q0Var2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ap.Q, new u0(0)), new aa.k(ap.T, new u0("refs/heads/"))}), n4);
        hq.Companion.getClass();
        q0 q0Var3 = hq.a;
        k71.k.g(q0Var3, "type");
        s mVar32 = new aa.m("readme", q0Var3, (String) null, rVar, no.a.s(ap.N, new u0(new t("branch"))), r5);
        lq.Companion.getClass();
        s mVar33 = new aa.m("repositoryTopics", l0.b(lq.a), (String) null, rVar, no.a.s(ap.Y, new u0(6)), n5);
        s mVar34 = new aa.m("url", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        s mVar35 = new aa.m("shortDescriptionHTML", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        s mVar36 = new aa.m("descriptionHTML", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        s mVar37 = new aa.m("description", xVar, (String) null, rVar, rVar, rVar);
        s mVar38 = new aa.m("viewerCanAdminister", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar39 = new aa.m("viewerCanPush", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar40 = new aa.m("viewerCanSubscribe", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        fq.Companion.getClass();
        a0 a0Var = fq.s;
        k71.k.g(a0Var, "type");
        s mVar41 = new aa.m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar);
        qz.Companion.getClass();
        s mVar42 = new aa.m("watchers", l0.b(qz.a), (String) null, rVar, no.a.s(ap.g0, new u0(0)), n6);
        dd.Companion.getClass();
        q0 q0Var4 = dd.a;
        k71.k.g(q0Var4, "type");
        s mVar43 = new aa.m("licenseInfo", q0Var4, (String) null, rVar, rVar, r8);
        s mVar44 = new aa.m("isDiscussionsEnabled", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar45 = new aa.m("discussionsCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        q0 q0Var5 = ap.k0;
        k71.k.g(q0Var5, "type");
        s mVar46 = new aa.m("parent", q0Var5, (String) null, rVar, rVar, r11);
        bo.Companion.getClass();
        s mVar47 = new aa.m("releases", l0.b(bo.a), (String) null, rVar, no.a.s(ap.W, new u0(0)), n8);
        List r13 = x61.l.r(new String[]{"Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team", "TeamDiscussion"});
        List list5 = n90.a.a;
        s c3 = no.a.c(list5, "selections", "Subscribable", r13, list5);
        vn.Companion.getClass();
        q0 q0Var6 = vn.e;
        k71.k.g(q0Var6, "type");
        s mVar48 = new aa.m("latestRelease", q0Var6, (String) null, rVar, rVar, r12);
        List n11 = d0Shadow.n("Repository");
        List list6 = fa0.f.a;
        s c4 = no.a.c(list6, "selections", "Repository", n11, list6);
        s mVar49 = new aa.m("isViewersFavorite", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar50 = new aa.m("viewerHasBlockedContributors", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar51 = new aa.m("viewerBlockedByOwner", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        List n12 = d0Shadow.n("Repository");
        List list7 = m.a;
        s c5 = no.a.c(list7, "selections", "Repository", n12, list7);
        List n13 = d0Shadow.n("Repository");
        List list8 = k.a;
        a = x61.l.r(new s[]{mVar11, mVar12, mVar13, c2, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, c3, mVar48, c4, mVar49, mVar50, mVar51, c5, no.a.c(list8, "selections", "Repository", n13, list8)});
    }
}
