package com.google.android.gms.internal.measurement;

/* loaded from: /home/user/work/p/classes4.dex */
public final class b7 implements a7 {
    public static final m4 A;
    public static final m4 B;
    public static final m4 C;
    public static final m4 D;
    public static final m4 E;
    public static final m4 F;
    public static final m4 G;
    public static final m4 H;
    public static final m4 I;
    public static final m4 J;
    public static final m4 K;
    public static final m4 L;
    public static final m4 M;
    public static final m4 N;
    public static final m4 O;
    public static final m4 P;
    public static final m4 Q;
    public static final m4 R;
    public static final m4 S;
    public static final m4 T;
    public static final m4 U;
    public static final m4 V;
    public static final m4 W;
    public static final m4 X;
    public static final m4 Y;
    public static final m4 Z;
    public static final m4 a;
    public static final m4 a0;
    public static final m4 b;
    public static final m4 b0;
    public static final m4 c;
    public static final m4 c0;
    public static final m4 d;
    public static final m4 d0;
    public static final m4 e;
    public static final m4 e0;
    public static final m4 f;
    public static final m4 f0;
    public static final m4 g;
    public static final m4 g0;
    public static final m4 h;
    public static final m4 h0;
    public static final m4 i;
    public static final m4 i0;
    public static final m4 j;
    public static final m4 j0;
    public static final m4 k;
    public static final m4 k0;
    public static final m4 l;
    public static final m4 l0;
    public static final m4 m;
    public static final m4 m0;
    public static final m4 n;
    public static final m4 n0;
    public static final m4 o;
    public static final m4 o0;
    public static final m4 p;
    public static final m4 p0;
    public static final m4 q;
    public static final m4 q0;
    public static final m4 r;
    public static final m4 r0;
    public static final m4 s;
    public static final m4 s0;
    public static final m4 t;
    public static final m4 t0;
    public static final m4 u;
    public static final m4 u0;
    public static final m4 v;
    public static final m4 v0;
    public static final m4 w;
    public static final m4 w0;
    public static final m4 x;
    public static final m4 y;
    public static final m4 z;

    static {
        n4 n4Var = new n4(l4.a(), true, true);
        a = n4Var.s("measurement.ad_id_cache_time", 10000L);
        b = n4Var.s("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L);
        c = n4Var.t("measurement.config.bundle_for_all_apps_on_backgrounded", true);
        d = n4Var.s("measurement.max_bundles_per_iteration", 100L);
        e = n4Var.u("measurement.gbraid_campaign.campaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid");
        f = n4Var.s("measurement.config.cache_time", 86400000L);
        n4Var.u("measurement.log_tag", "FA");
        g = n4Var.u("measurement.config.url_authority", "app-measurement.com");
        h = n4Var.u("measurement.config.url_scheme", "https");
        i = n4Var.s("measurement.upload.debug_upload_interval", 1000L);
        n4Var.t("measurement.config.default_flag_values", true);
        j = n4Var.s("measurement.session.engagement_interval", 3600000L);
        k = n4Var.u("measurement.rb.attribution.event_params", "value|currency");
        l = n4Var.u("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp");
        m = n4Var.s("measurement.upload.google_signal_max_queue_time", 605000L);
        n = n4Var.u("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d");
        n4Var.s("measurement.id.upload.max_conversions_per_day", 0L);
        o = n4Var.s("measurement.lifetimevalue.max_currency_tracked", 4L);
        p = n4Var.s("measurement.dma_consent.max_daily_dcu_realtime_events", 1L);
        q = n4Var.s("measurement.upload.max_event_parameter_value_length", 500L);
        r = n4Var.s("measurement.store.max_stored_events_per_app", 100000L);
        s = n4Var.s("measurement.experiment.max_ids", 50L);
        t = n4Var.s("measurement.audience.filter_result_max_count", 200L);
        u = n4Var.s("measurement.upload.max_item_scoped_custom_parameters", 27L);
        v = n4Var.s("measurement.rb.max_trigger_registrations_per_day", 1000L);
        w = n4Var.s("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0L);
        x = n4Var.s("measurement.rb.attribution.client.min_ad_services_version", 7L);
        y = n4Var.s("measurement.alarm_manager.minimum_interval", 60000L);
        z = n4Var.s("measurement.upload.minimum_delay", 500L);
        A = n4Var.s("measurement.monitoring.sample_period_millis", 86400000L);
        B = n4Var.s("measurement.rb.attribution.notify_app_delay_millis", 3000L);
        C = n4Var.t("measurement.config.notify_trigger_uris_on_backgrounded", true);
        D = n4Var.u("measurement.rb.attribution.app_allowlist", "");
        E = n4Var.s("measurement.upload.realtime_upload_interval", 10000L);
        F = n4Var.s("measurement.upload.refresh_blacklisted_config_interval", 604800000L);
        n4Var.s("measurement.config.cache_time.service", 3600000L);
        G = n4Var.s("measurement.service_client.idle_disconnect_millis", 5000L);
        n4Var.u("measurement.log_tag.service", "FA-SVC");
        H = n4Var.s("measurement.service_client.reconnect_millis", 1000L);
        n4Var.u("measurement.sgtm.app_allowlist", "*");
        I = n4Var.s("measurement.sgtm.batch.long_queuing_threshold", 240000L);
        J = n4Var.s("measurement.sgtm.batch.retry_interval", 1800000L);
        K = n4Var.s("measurement.sgtm.batch.retry_max_count", 10L);
        L = n4Var.s("measurement.sgtm.batch.retry_max_wait", 21600000L);
        M = n4Var.u("measurement.sgtm.service_upload_apps_list", "");
        N = n4Var.u("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504");
        O = n4Var.s("measurement.sgtm.upload.batches_retrieval_limit", 5L);
        P = n4Var.s("measurement.sgtm.upload.max_queued_batches", 5000L);
        Q = n4Var.s("measurement.sgtm.upload.min_delay_after_background", 600000L);
        R = n4Var.s("measurement.sgtm.upload.min_delay_after_broadcast", 1000L);
        S = n4Var.s("measurement.sgtm.upload.min_delay_after_startup", 5000L);
        T = n4Var.s("measurement.sgtm.upload.retry_interval", 600000L);
        U = n4Var.s("measurement.sgtm.upload.retry_max_wait", 21600000L);
        V = n4Var.s("measurement.upload.stale_data_deletion_interval", 86400000L);
        W = n4Var.s("measurement.rb.attribution.max_retry_delay_seconds", 16L);
        X = n4Var.s("measurement.rb.attribution.client.min_time_after_boot_seconds", 90L);
        Y = n4Var.u("measurement.rb.attribution.uri_authority", "google-analytics.com");
        Z = n4Var.s("measurement.rb.attribution.max_queue_time", 864000000L);
        a0 = n4Var.u("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion");
        b0 = n4Var.u("measurement.rb.attribution.query_parameters_to_remove", "");
        c0 = n4Var.u("measurement.rb.attribution.uri_scheme", "https");
        d0 = n4Var.s("measurement.sdk.attribution.cache.ttl", 604800000L);
        e0 = n4Var.s("measurement.redaction.app_instance_id.ttl", 7200000L);
        f0 = n4Var.s("measurement.upload.backoff_period", 43200000L);
        g0 = n4Var.s("measurement.upload.initial_upload_delay_time", 15000L);
        h0 = n4Var.s("measurement.upload.interval", 3600000L);
        i0 = n4Var.s("measurement.upload.max_bundle_size", 65536L);
        j0 = n4Var.s("measurement.upload.max_bundles", 100L);
        k0 = n4Var.s("measurement.upload.max_conversions_per_day", 500L);
        l0 = n4Var.s("measurement.upload.max_error_events_per_day", 1000L);
        m0 = n4Var.s("measurement.upload.max_events_per_bundle", 1000L);
        n0 = n4Var.s("measurement.upload.max_events_per_day", 100000L);
        o0 = n4Var.s("measurement.upload.max_public_events_per_day", 50000L);
        p0 = n4Var.s("measurement.upload.max_queue_time", 518400000L);
        q0 = n4Var.s("measurement.upload.max_realtime_events_per_day", 10L);
        r0 = n4Var.s("measurement.upload.max_batch_size", 65536L);
        s0 = n4Var.s("measurement.upload.retry_count", 6L);
        t0 = n4Var.s("measurement.upload.retry_time", 1800000L);
        u0 = n4Var.u("measurement.upload.url", "https://app-measurement.com/a");
        v0 = n4Var.s("measurement.upload.window_interval", 3600000L);
        w0 = n4Var.u("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot");
    }
}
