package com.github.service.models.response.type;

import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;
import d71.a;
import r01.j;
import v8.l0;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class MobileAppElement {
    private static final /* synthetic */ a $ENTRIES;
    private static final /* synthetic */ MobileAppElement[] $VALUES;
    public static final j Companion;
    private String rawValue;
    public static final MobileAppElement REPOSITORY_DISCUSSIONS_LIST_FILTER = new MobileAppElement("REPOSITORY_DISCUSSIONS_LIST_FILTER", 0, "REPOSITORY_DISCUSSIONS_LIST_FILTER");
    public static final MobileAppElement VIEWER_DISCUSSIONS_LIST_FILTER = new MobileAppElement("VIEWER_DISCUSSIONS_LIST_FILTER", 1, "VIEWER_DISCUSSIONS_LIST_FILTER");
    public static final MobileAppElement EXPLORE_BOTTOM_NAVIGATION = new MobileAppElement("EXPLORE_BOTTOM_NAVIGATION", 2, "EXPLORE_BOTTOM_NAVIGATION");
    public static final MobileAppElement EXPLORE_TRENDING_REPOSITORY = new MobileAppElement("EXPLORE_TRENDING_REPOSITORY", 3, "EXPLORE_TRENDING_REPOSITORY");
    public static final MobileAppElement EXPLORE_FOR_YOU_REPOSITORY = new MobileAppElement("EXPLORE_FOR_YOU_REPOSITORY", 4, "EXPLORE_FOR_YOU_REPOSITORY");
    public static final MobileAppElement EXPLORE_FEATURED_REPOSITORY = new MobileAppElement("EXPLORE_FEATURED_REPOSITORY", 5, "EXPLORE_FEATURED_REPOSITORY");
    public static final MobileAppElement EXPLORE_STAR_TRENDING_REPOSITORY = new MobileAppElement("EXPLORE_STAR_TRENDING_REPOSITORY", 6, "EXPLORE_STAR_TRENDING_REPOSITORY");
    public static final MobileAppElement EXPLORE_STAR_FOR_YOU_REPOSITORY = new MobileAppElement("EXPLORE_STAR_FOR_YOU_REPOSITORY", 7, "EXPLORE_STAR_FOR_YOU_REPOSITORY");
    public static final MobileAppElement EXPLORE_STAR_FEATURED_REPOSITORY = new MobileAppElement("EXPLORE_STAR_FEATURED_REPOSITORY", 8, "EXPLORE_STAR_FEATURED_REPOSITORY");
    public static final MobileAppElement EXPLORE_TRENDING_LIST_FILTER = new MobileAppElement("EXPLORE_TRENDING_LIST_FILTER", 9, "EXPLORE_TRENDING_LIST_FILTER");
    public static final MobileAppElement FOLLOW = new MobileAppElement("FOLLOW", 10, "FOLLOW");
    public static final MobileAppElement HOME_BOTTOM_NAVIGATION = new MobileAppElement("HOME_BOTTOM_NAVIGATION", 11, "HOME_BOTTOM_NAVIGATION");
    public static final MobileAppElement HOME_ISSUES = new MobileAppElement("HOME_ISSUES", 12, "HOME_ISSUES");
    public static final MobileAppElement HOME_FAVORITE_REPOSITORY_ITEM = new MobileAppElement("HOME_FAVORITE_REPOSITORY_ITEM", 13, "HOME_FAVORITE_REPOSITORY_ITEM");
    public static final MobileAppElement HOME_PULL_REQUESTS = new MobileAppElement("HOME_PULL_REQUESTS", 14, "HOME_PULL_REQUESTS");
    public static final MobileAppElement HOME_RECENT_ACTIVITY_ITEM = new MobileAppElement("HOME_RECENT_ACTIVITY_ITEM", 15, "HOME_RECENT_ACTIVITY_ITEM");
    public static final MobileAppElement HOME_REPOSITORIES = new MobileAppElement("HOME_REPOSITORIES", 16, "HOME_REPOSITORIES");
    public static final MobileAppElement HOME_STARRED = new MobileAppElement("HOME_STARRED", 17, "HOME_STARRED");
    public static final MobileAppElement HOME_SHORTCUTS = new MobileAppElement("HOME_SHORTCUTS", 18, "HOME_SHORTCUTS");
    public static final MobileAppElement HOME_ORGANIZATIONS = new MobileAppElement("HOME_ORGANIZATIONS", 19, "HOME_ORGANIZATIONS");
    public static final MobileAppElement HOME_CREATE_ISSUE = new MobileAppElement("HOME_CREATE_ISSUE", 20, "HOME_CREATE_ISSUE");
    public static final MobileAppElement HOME_RELEASE_NOTES = new MobileAppElement("HOME_RELEASE_NOTES", 21, "HOME_RELEASE_NOTES");
    public static final MobileAppElement HOME_DISCUSSIONS = new MobileAppElement("HOME_DISCUSSIONS", 22, "HOME_DISCUSSIONS");
    public static final MobileAppElement HOME_PROJECTS = new MobileAppElement("HOME_PROJECTS", 23, "HOME_PROJECTS");
    public static final MobileAppElement HOME_IN_APP_UPDATE = new MobileAppElement("HOME_IN_APP_UPDATE", 24, "HOME_IN_APP_UPDATE");
    public static final MobileAppElement NOTIFICATION_LIST = new MobileAppElement("NOTIFICATION_LIST", 25, "NOTIFICATION_LIST");
    public static final MobileAppElement NOTIFICATION_LIST_ITEM = new MobileAppElement("NOTIFICATION_LIST_ITEM", 26, "NOTIFICATION_LIST_ITEM");
    public static final MobileAppElement NOTIFICATION_LIST_ITEM_UNDO = new MobileAppElement("NOTIFICATION_LIST_ITEM_UNDO", 27, "NOTIFICATION_LIST_ITEM_UNDO");
    public static final MobileAppElement NOTIFICATION_LIST_ITEM_FOCUSED = new MobileAppElement("NOTIFICATION_LIST_ITEM_FOCUSED", 28, "NOTIFICATION_LIST_ITEM_FOCUSED");
    public static final MobileAppElement NOTIFICATION_LIST_FILTER = new MobileAppElement("NOTIFICATION_LIST_FILTER", 29, "NOTIFICATION_LIST_FILTER");
    public static final MobileAppElement NOTIFICATION_FILTER = new MobileAppElement("NOTIFICATION_FILTER", 30, "NOTIFICATION_FILTER");
    public static final MobileAppElement NOTIFICATION_BOTTOM_NAVIGATION = new MobileAppElement("NOTIFICATION_BOTTOM_NAVIGATION", 31, "NOTIFICATION_BOTTOM_NAVIGATION");
    public static final MobileAppElement NOTIFICATION_PUSH = new MobileAppElement("NOTIFICATION_PUSH", 32, "NOTIFICATION_PUSH");
    public static final MobileAppElement ISSUES_LIST_ITEM = new MobileAppElement("ISSUES_LIST_ITEM", 33, "ISSUES_LIST_ITEM");
    public static final MobileAppElement VIEWER_ISSUES_LIST_FILTER = new MobileAppElement("VIEWER_ISSUES_LIST_FILTER", 34, "VIEWER_ISSUES_LIST_FILTER");
    public static final MobileAppElement REPOSITORY_ISSUES_LIST_FILTER = new MobileAppElement("REPOSITORY_ISSUES_LIST_FILTER", 35, "REPOSITORY_ISSUES_LIST_FILTER");
    public static final MobileAppElement ISSUES_SEARCH = new MobileAppElement("ISSUES_SEARCH", 36, "ISSUES_SEARCH");
    public static final MobileAppElement ISSUE_COMPOSER = new MobileAppElement("ISSUE_COMPOSER", 37, "ISSUE_COMPOSER");
    public static final MobileAppElement ISSUE_COMPOSER_PROPERTY_BAR = new MobileAppElement("ISSUE_COMPOSER_PROPERTY_BAR", 38, "ISSUE_COMPOSER_PROPERTY_BAR");
    public static final MobileAppElement PULL_REQUESTS_LIST_ITEM = new MobileAppElement("PULL_REQUESTS_LIST_ITEM", 39, "PULL_REQUESTS_LIST_ITEM");
    public static final MobileAppElement VIEWER_PULL_REQUESTS_LIST_FILTER = new MobileAppElement("VIEWER_PULL_REQUESTS_LIST_FILTER", 40, "VIEWER_PULL_REQUESTS_LIST_FILTER");
    public static final MobileAppElement REPOSITORY_PULL_REQUESTS_LIST_FILTER = new MobileAppElement("REPOSITORY_PULL_REQUESTS_LIST_FILTER", 41, "REPOSITORY_PULL_REQUESTS_LIST_FILTER");
    public static final MobileAppElement SHORTCUTS_LIST_ITEM = new MobileAppElement("SHORTCUTS_LIST_ITEM", 42, "SHORTCUTS_LIST_ITEM");
    public static final MobileAppElement SHORTCUT_SUGGESTIONS_LIST_ITEM = new MobileAppElement("SHORTCUT_SUGGESTIONS_LIST_ITEM", 43, "SHORTCUT_SUGGESTIONS_LIST_ITEM");
    public static final MobileAppElement SHOW_MORE_ROLLUP = new MobileAppElement("SHOW_MORE_ROLLUP", 44, "SHOW_MORE_ROLLUP");
    public static final MobileAppElement STAR_REPOSITORY = new MobileAppElement("STAR_REPOSITORY", 45, "STAR_REPOSITORY");
    public static final MobileAppElement PROFILE_BOTTOM_NAVIGATION = new MobileAppElement("PROFILE_BOTTOM_NAVIGATION", 46, "PROFILE_BOTTOM_NAVIGATION");
    public static final MobileAppElement PULL_REQUESTS_SEARCH = new MobileAppElement("PULL_REQUESTS_SEARCH", 47, "PULL_REQUESTS_SEARCH");
    public static final MobileAppElement TRIAGE_EXPAND = new MobileAppElement("TRIAGE_EXPAND", 48, "TRIAGE_EXPAND");
    public static final MobileAppElement TRIAGE_COMMENT = new MobileAppElement("TRIAGE_COMMENT", 49, "TRIAGE_COMMENT");
    public static final MobileAppElement TRIAGE_COMMENT_UP = new MobileAppElement("TRIAGE_COMMENT_UP", 50, "TRIAGE_COMMENT_UP");
    public static final MobileAppElement TRIAGE_COMMENT_DOWN = new MobileAppElement("TRIAGE_COMMENT_DOWN", 51, "TRIAGE_COMMENT_DOWN");
    public static final MobileAppElement TRIAGE_COMMENT_EDIT = new MobileAppElement("TRIAGE_COMMENT_EDIT", 52, "TRIAGE_COMMENT_EDIT");
    public static final MobileAppElement TRIAGE_REVIEW_REQUEST_EDIT = new MobileAppElement("TRIAGE_REVIEW_REQUEST_EDIT", 53, "TRIAGE_REVIEW_REQUEST_EDIT");
    public static final MobileAppElement TRIAGE_ASSIGNEE_EDIT = new MobileAppElement("TRIAGE_ASSIGNEE_EDIT", 54, "TRIAGE_ASSIGNEE_EDIT");
    public static final MobileAppElement TRIAGE_ISSUE_TYPE_EDIT = new MobileAppElement("TRIAGE_ISSUE_TYPE_EDIT", 55, "TRIAGE_ISSUE_TYPE_EDIT");
    public static final MobileAppElement TRIAGE_LABEL_EDIT = new MobileAppElement("TRIAGE_LABEL_EDIT", 56, "TRIAGE_LABEL_EDIT");
    public static final MobileAppElement TRIAGE_LINKED_ITEM_EDIT = new MobileAppElement("TRIAGE_LINKED_ITEM_EDIT", 57, "TRIAGE_LINKED_ITEM_EDIT");
    public static final MobileAppElement TRIAGE_PROJECT_EDIT = new MobileAppElement("TRIAGE_PROJECT_EDIT", 58, "TRIAGE_PROJECT_EDIT");
    public static final MobileAppElement TRIAGE_PROJECT_NEXT_EDIT = new MobileAppElement("TRIAGE_PROJECT_NEXT_EDIT", 59, "TRIAGE_PROJECT_NEXT_EDIT");
    public static final MobileAppElement TRIAGE_PROJECT_NEXT_PICKER_OWNER = new MobileAppElement("TRIAGE_PROJECT_NEXT_PICKER_OWNER", 60, "TRIAGE_PROJECT_NEXT_PICKER_OWNER");
    public static final MobileAppElement TRIAGE_PROJECT_NEXT_PICKER_RECENT = new MobileAppElement("TRIAGE_PROJECT_NEXT_PICKER_RECENT", 61, "TRIAGE_PROJECT_NEXT_PICKER_RECENT");
    public static final MobileAppElement TRIAGE_MILESTONE_EDIT = new MobileAppElement("TRIAGE_MILESTONE_EDIT", 62, "TRIAGE_MILESTONE_EDIT");
    public static final MobileAppElement TRIAGE_CLOSE = new MobileAppElement("TRIAGE_CLOSE", 63, "TRIAGE_CLOSE");
    public static final MobileAppElement TRIAGE_LOCK = new MobileAppElement("TRIAGE_LOCK", 64, "TRIAGE_LOCK");
    public static final MobileAppElement TRIAGE_UNSUBSCRIBE = new MobileAppElement("TRIAGE_UNSUBSCRIBE", 65, "TRIAGE_UNSUBSCRIBE");
    public static final MobileAppElement ONBOARDING_BANNER = new MobileAppElement("ONBOARDING_BANNER", 66, "ONBOARDING_BANNER");
    public static final MobileAppElement NOTIFICATIONS_ONBOARDING_BANNER = new MobileAppElement("NOTIFICATIONS_ONBOARDING_BANNER", 67, "NOTIFICATIONS_ONBOARDING_BANNER");
    public static final MobileAppElement REPOSITORY_LATEST_RELEASE = new MobileAppElement("REPOSITORY_LATEST_RELEASE", 68, "REPOSITORY_LATEST_RELEASE");
    public static final MobileAppElement RELEASES_LIST_LATEST_RELEASE = new MobileAppElement("RELEASES_LIST_LATEST_RELEASE", 69, "RELEASES_LIST_LATEST_RELEASE");
    public static final MobileAppElement RELEASE_DOWNLOAD_ASSET = new MobileAppElement("RELEASE_DOWNLOAD_ASSET", 70, "RELEASE_DOWNLOAD_ASSET");
    public static final MobileAppElement RELEASE_LINKED_DISCUSSION = new MobileAppElement("RELEASE_LINKED_DISCUSSION", 71, "RELEASE_LINKED_DISCUSSION");
    public static final MobileAppElement VIEWER_PULL_TO_REFRESH = new MobileAppElement("VIEWER_PULL_TO_REFRESH", 72, "VIEWER_PULL_TO_REFRESH");
    public static final MobileAppElement PROJECTS_LIST_ITEM = new MobileAppElement("PROJECTS_LIST_ITEM", 73, "PROJECTS_LIST_ITEM");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_CLOSE = new MobileAppElement("PROJECTS_QUICK_ACTION_CLOSE", 74, "PROJECTS_QUICK_ACTION_CLOSE");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_DELETE = new MobileAppElement("PROJECTS_QUICK_ACTION_DELETE", 75, "PROJECTS_QUICK_ACTION_DELETE");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_EDIT_FIELD = new MobileAppElement("PROJECTS_QUICK_ACTION_EDIT_FIELD", 76, "PROJECTS_QUICK_ACTION_EDIT_FIELD");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_EDIT_TITLE = new MobileAppElement("PROJECTS_QUICK_ACTION_EDIT_TITLE", 77, "PROJECTS_QUICK_ACTION_EDIT_TITLE");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_OPEN_DETAILS = new MobileAppElement("PROJECTS_QUICK_ACTION_OPEN_DETAILS", 78, "PROJECTS_QUICK_ACTION_OPEN_DETAILS");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_OTHER_PROJECTS = new MobileAppElement("PROJECTS_QUICK_ACTION_OTHER_PROJECTS", 79, "PROJECTS_QUICK_ACTION_OTHER_PROJECTS");
    public static final MobileAppElement PROJECTS_QUICK_ACTION_REOPEN = new MobileAppElement("PROJECTS_QUICK_ACTION_REOPEN", 80, "PROJECTS_QUICK_ACTION_REOPEN");
    public static final MobileAppElement PROJECTS_TABLE_VIEW_LIST_ITEM = new MobileAppElement("PROJECTS_TABLE_VIEW_LIST_ITEM", 81, "PROJECTS_TABLE_VIEW_LIST_ITEM");
    public static final MobileAppElement PROJECT_VIEW = new MobileAppElement("PROJECT_VIEW", 82, "PROJECT_VIEW");
    public static final MobileAppElement PROJECT_VIEW_TIMEOUT_CTA = new MobileAppElement("PROJECT_VIEW_TIMEOUT_CTA", 83, "PROJECT_VIEW_TIMEOUT_CTA");
    public static final MobileAppElement HOME_REPOSITORY_LIST_FILTER = new MobileAppElement("HOME_REPOSITORY_LIST_FILTER", 84, "HOME_REPOSITORY_LIST_FILTER");
    public static final MobileAppElement PROFILE_REPOSITORY_LIST_FILTER = new MobileAppElement("PROFILE_REPOSITORY_LIST_FILTER", 85, "PROFILE_REPOSITORY_LIST_FILTER");
    public static final MobileAppElement SETTINGS_DISABLE_ANALYTICS = new MobileAppElement("SETTINGS_DISABLE_ANALYTICS", 86, "SETTINGS_DISABLE_ANALYTICS");
    public static final MobileAppElement SETTINGS_ENABLE_APP_LOCK = new MobileAppElement("SETTINGS_ENABLE_APP_LOCK", 87, "SETTINGS_ENABLE_APP_LOCK");
    public static final MobileAppElement ACCOUNT_SWITCHER_ADD = new MobileAppElement("ACCOUNT_SWITCHER_ADD", 88, "ACCOUNT_SWITCHER_ADD");
    public static final MobileAppElement ACCOUNT_SWITCHER_ITEM = new MobileAppElement("ACCOUNT_SWITCHER_ITEM", 89, "ACCOUNT_SWITCHER_ITEM");
    public static final MobileAppElement ACCOUNT_SWITCHER_REMOVE = new MobileAppElement("ACCOUNT_SWITCHER_REMOVE", 90, "ACCOUNT_SWITCHER_REMOVE");
    public static final MobileAppElement PROFILE_HEADER_NAME = new MobileAppElement("PROFILE_HEADER_NAME", 91, "PROFILE_HEADER_NAME");
    public static final MobileAppElement SETTINGS_ACCOUNTS = new MobileAppElement("SETTINGS_ACCOUNTS", 92, "SETTINGS_ACCOUNTS");
    public static final MobileAppElement VIEWING_AS_TOAST = new MobileAppElement("VIEWING_AS_TOAST", 93, "VIEWING_AS_TOAST");
    public static final MobileAppElement DEEP_LINK_ERROR_ACCOUNT_SWITCHER = new MobileAppElement("DEEP_LINK_ERROR_ACCOUNT_SWITCHER", 94, "DEEP_LINK_ERROR_ACCOUNT_SWITCHER");
    public static final MobileAppElement REPOSITORY_EDIT_README = new MobileAppElement("REPOSITORY_EDIT_README", 95, "REPOSITORY_EDIT_README");
    public static final MobileAppElement CODE_SEARCH_LIST_ITEM = new MobileAppElement("CODE_SEARCH_LIST_ITEM", 96, "CODE_SEARCH_LIST_ITEM");
    public static final MobileAppElement GLOBAL_SEARCH_SHORTCUT = new MobileAppElement("GLOBAL_SEARCH_SHORTCUT", 97, "GLOBAL_SEARCH_SHORTCUT");
    public static final MobileAppElement HOME_ISSUES_LIST_NEW_ISSUE = new MobileAppElement("HOME_ISSUES_LIST_NEW_ISSUE", 98, "HOME_ISSUES_LIST_NEW_ISSUE");
    public static final MobileAppElement COPILOT_CHAT_BUTTON = new MobileAppElement("COPILOT_CHAT_BUTTON", 99, "COPILOT_CHAT_BUTTON");
    public static final MobileAppElement COPILOT_CHAT_CONVERSATION = new MobileAppElement("COPILOT_CHAT_CONVERSATION", 100, "COPILOT_CHAT_CONVERSATION");
    public static final MobileAppElement COPILOT_CHAT_MESSAGE_COPY = new MobileAppElement("COPILOT_CHAT_MESSAGE_COPY", 101, "COPILOT_CHAT_MESSAGE_COPY");
    public static final MobileAppElement COPILOT_CHAT_SUGGESTION = new MobileAppElement("COPILOT_CHAT_SUGGESTION", 102, "COPILOT_CHAT_SUGGESTION");
    public static final MobileAppElement COPILOT_AGREEMENT = new MobileAppElement("COPILOT_AGREEMENT", 103, "COPILOT_AGREEMENT");
    public static final MobileAppElement COPILOT_ALL_CONVERSATIONS = new MobileAppElement("COPILOT_ALL_CONVERSATIONS", 104, "COPILOT_ALL_CONVERSATIONS");
    public static final MobileAppElement COPILOT_BUY = new MobileAppElement("COPILOT_BUY", 105, "COPILOT_BUY");
    public static final MobileAppElement COPILOT_DELETE_CONVERSATION = new MobileAppElement("COPILOT_DELETE_CONVERSATION", 106, "COPILOT_DELETE_CONVERSATION");
    public static final MobileAppElement COPILOT_DISMISS_PAYWALL = new MobileAppElement("COPILOT_DISMISS_PAYWALL", 107, "COPILOT_DISMISS_PAYWALL");
    public static final MobileAppElement COPILOT_LEARN_MORE = new MobileAppElement("COPILOT_LEARN_MORE", 108, "COPILOT_LEARN_MORE");
    public static final MobileAppElement COPILOT_MANAGE_SUBSCRIPTION = new MobileAppElement("COPILOT_MANAGE_SUBSCRIPTION", 109, "COPILOT_MANAGE_SUBSCRIPTION");
    public static final MobileAppElement COPILOT_NEW_CONVERSATION = new MobileAppElement("COPILOT_NEW_CONVERSATION", 110, "COPILOT_NEW_CONVERSATION");
    public static final MobileAppElement COPILOT_POLICY_DISABLED_LINK = new MobileAppElement("COPILOT_POLICY_DISABLED_LINK", 111, "COPILOT_POLICY_DISABLED_LINK");
    public static final MobileAppElement COPILOT_PRIVACY_POLICY = new MobileAppElement("COPILOT_PRIVACY_POLICY", 112, "COPILOT_PRIVACY_POLICY");
    public static final MobileAppElement COPILOT_RECENT_CONVERSATION = new MobileAppElement("COPILOT_RECENT_CONVERSATION", 113, "COPILOT_RECENT_CONVERSATION");
    public static final MobileAppElement COPILOT_RESTORE_PURCHASE = new MobileAppElement("COPILOT_RESTORE_PURCHASE", 114, "COPILOT_RESTORE_PURCHASE");
    public static final MobileAppElement COPILOT_SCOPE_LINK = new MobileAppElement("COPILOT_SCOPE_LINK", 115, "COPILOT_SCOPE_LINK");
    public static final MobileAppElement COPILOT_SETTINGS_ENABLE = new MobileAppElement("COPILOT_SETTINGS_ENABLE", 116, "COPILOT_SETTINGS_ENABLE");
    public static final MobileAppElement COPILOT_SETTINGS_HIDE_BOA = new MobileAppElement("COPILOT_SETTINGS_HIDE_BOA", 117, "COPILOT_SETTINGS_HIDE_BOA");
    public static final MobileAppElement COPILOT_UPSELL_DISMISS = new MobileAppElement("COPILOT_UPSELL_DISMISS", 118, "COPILOT_UPSELL_DISMISS");
    public static final MobileAppElement COPILOT_UPSELL_LEARN_MORE = new MobileAppElement("COPILOT_UPSELL_LEARN_MORE", 119, "COPILOT_UPSELL_LEARN_MORE");
    public static final MobileAppElement FINISH_REVIEW_BOA = new MobileAppElement("FINISH_REVIEW_BOA", 120, "FINISH_REVIEW_BOA");
    public static final MobileAppElement PULL_REQUEST_FILES_CHANGED = new MobileAppElement("PULL_REQUEST_FILES_CHANGED", 121, "PULL_REQUEST_FILES_CHANGED");
    public static final MobileAppElement PULL_REQUEST_REVIEW_BANNER = new MobileAppElement("PULL_REQUEST_REVIEW_BANNER", 122, "PULL_REQUEST_REVIEW_BANNER");
    public static final MobileAppElement PULL_REQUEST_REVIEW_CTA = new MobileAppElement("PULL_REQUEST_REVIEW_CTA", 123, "PULL_REQUEST_REVIEW_CTA");
    public static final MobileAppElement SUBMIT_REVIEW = new MobileAppElement("SUBMIT_REVIEW", 124, "SUBMIT_REVIEW");
    public static final MobileAppElement FOCUS_CTA_DISMISSED = new MobileAppElement("FOCUS_CTA_DISMISSED", 125, "FOCUS_CTA_DISMISSED");
    public static final MobileAppElement FOCUS_CTA_ENABLED = new MobileAppElement("FOCUS_CTA_ENABLED", 126, "FOCUS_CTA_ENABLED");
    public static final MobileAppElement FOCUS_CTA_VIEWED = new MobileAppElement("FOCUS_CTA_VIEWED", 127, "FOCUS_CTA_VIEWED");
    public static final MobileAppElement PIN_SHORTCUT = new MobileAppElement("PIN_SHORTCUT", 128, "PIN_SHORTCUT");
    public static final MobileAppElement PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW = new MobileAppElement("PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW", 129, "PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW");
    public static final MobileAppElement PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY = new MobileAppElement("PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY", 130, "PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY");
    public static final MobileAppElement COMPARE_BRANCHES = new MobileAppElement("COMPARE_BRANCHES", 131, "COMPARE_BRANCHES");
    public static final MobileAppElement COMPARE_BRANCHES_ACTIVE_PULL_REQUEST = new MobileAppElement("COMPARE_BRANCHES_ACTIVE_PULL_REQUEST", 132, "COMPARE_BRANCHES_ACTIVE_PULL_REQUEST");
    public static final MobileAppElement COMPARE_BRANCHES_COMMITS = new MobileAppElement("COMPARE_BRANCHES_COMMITS", 133, "COMPARE_BRANCHES_COMMITS");
    public static final MobileAppElement COMPARE_BRANCHES_CREATE_PULL_REQUEST = new MobileAppElement("COMPARE_BRANCHES_CREATE_PULL_REQUEST", 134, "COMPARE_BRANCHES_CREATE_PULL_REQUEST");
    public static final MobileAppElement COMPARE_BRANCHES_FILES_CHANGED = new MobileAppElement("COMPARE_BRANCHES_FILES_CHANGED", 135, "COMPARE_BRANCHES_FILES_CHANGED");
    public static final MobileAppElement PULL_REQUEST_COMPOSER_SUBMIT = new MobileAppElement("PULL_REQUEST_COMPOSER_SUBMIT", 136, "PULL_REQUEST_COMPOSER_SUBMIT");
    public static final MobileAppElement PULL_REQUEST_LEGACY_CREATION_SUBMIT = new MobileAppElement("PULL_REQUEST_LEGACY_CREATION_SUBMIT", 137, "PULL_REQUEST_LEGACY_CREATION_SUBMIT");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_CONTINUE_BANNER = new MobileAppElement("NOTIFICATION_ONBOARDING_CONTINUE_BANNER", 138, "NOTIFICATION_ONBOARDING_CONTINUE_BANNER");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER = new MobileAppElement("NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER", 139, "NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_NUX_BANNER = new MobileAppElement("NOTIFICATION_ONBOARDING_NUX_BANNER", 140, "NOTIFICATION_ONBOARDING_NUX_BANNER");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_PROGRESS = new MobileAppElement("NOTIFICATION_ONBOARDING_PROGRESS", 141, "NOTIFICATION_ONBOARDING_PROGRESS");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_PROGRESS_REVIEW = new MobileAppElement("NOTIFICATION_ONBOARDING_PROGRESS_REVIEW", 142, "NOTIFICATION_ONBOARDING_PROGRESS_REVIEW");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_RECAPTURE = new MobileAppElement("NOTIFICATION_ONBOARDING_RECAPTURE", 143, "NOTIFICATION_ONBOARDING_RECAPTURE");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_REVIEW_BANNER = new MobileAppElement("NOTIFICATION_ONBOARDING_REVIEW_BANNER", 144, "NOTIFICATION_ONBOARDING_REVIEW_BANNER");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS = new MobileAppElement("NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS", 145, "NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS");
    public static final MobileAppElement SUB_ISSUE_ADD_EXISTING_ISSUE = new MobileAppElement("SUB_ISSUE_ADD_EXISTING_ISSUE", 146, "SUB_ISSUE_ADD_EXISTING_ISSUE");
    public static final MobileAppElement SUB_ISSUE_ADD_NEW_ISSUE = new MobileAppElement("SUB_ISSUE_ADD_NEW_ISSUE", 147, "SUB_ISSUE_ADD_NEW_ISSUE");
    public static final MobileAppElement SUB_ISSUE_EDIT_PARENT_ISSUE = new MobileAppElement("SUB_ISSUE_EDIT_PARENT_ISSUE", 148, "SUB_ISSUE_EDIT_PARENT_ISSUE");
    public static final MobileAppElement SUB_ISSUE_EDIT_SUB_ISSUE = new MobileAppElement("SUB_ISSUE_EDIT_SUB_ISSUE", 149, "SUB_ISSUE_EDIT_SUB_ISSUE");
    public static final MobileAppElement SUB_ISSUE_ISSUE = new MobileAppElement("SUB_ISSUE_ISSUE", 150, "SUB_ISSUE_ISSUE");
    public static final MobileAppElement SUB_ISSUE_NESTED_ISSUES_TOGGLE = new MobileAppElement("SUB_ISSUE_NESTED_ISSUES_TOGGLE", 151, "SUB_ISSUE_NESTED_ISSUES_TOGGLE");
    public static final MobileAppElement SUB_ISSUE_PARENT_ISSUE = new MobileAppElement("SUB_ISSUE_PARENT_ISSUE", 152, "SUB_ISSUE_PARENT_ISSUE");
    public static final MobileAppElement SUB_ISSUE_SECTION = new MobileAppElement("SUB_ISSUE_SECTION", 153, "SUB_ISSUE_SECTION");
    public static final MobileAppElement NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER = new MobileAppElement("NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER", 154, "NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER");
    public static final MobileAppElement MODEL_PICKER = new MobileAppElement("MODEL_PICKER", ModuleDescriptor.MODULE_VERSION, "MODEL_PICKER");
    public static final MobileAppElement MODEL_PICKER_ITEM = new MobileAppElement("MODEL_PICKER_ITEM", 156, "MODEL_PICKER_ITEM");
    public static final MobileAppElement CODING_AGENT_ASSIGNED = new MobileAppElement("CODING_AGENT_ASSIGNED", 157, "CODING_AGENT_ASSIGNED");
    public static final MobileAppElement CODING_AGENT_UNASSIGNED = new MobileAppElement("CODING_AGENT_UNASSIGNED", 158, "CODING_AGENT_UNASSIGNED");
    public static final MobileAppElement CODING_AGENT_WORK_SESSION = new MobileAppElement("CODING_AGENT_WORK_SESSION", 159, "CODING_AGENT_WORK_SESSION");
    public static final MobileAppElement COPILOT_CODE_REVIEW_BANNER = new MobileAppElement("COPILOT_CODE_REVIEW_BANNER", 160, "COPILOT_CODE_REVIEW_BANNER");
    public static final MobileAppElement COPILOT_SEND_MESSAGE = new MobileAppElement("COPILOT_SEND_MESSAGE", 161, "COPILOT_SEND_MESSAGE");
    public static final MobileAppElement CODING_AGENT_BANNER = new MobileAppElement("CODING_AGENT_BANNER", 162, "CODING_AGENT_BANNER");
    public static final MobileAppElement COPILOT_EXPLAIN_ERROR = new MobileAppElement("COPILOT_EXPLAIN_ERROR", 163, "COPILOT_EXPLAIN_ERROR");
    public static final MobileAppElement HOME_AGENT_PULL_REQUESTS = new MobileAppElement("HOME_AGENT_PULL_REQUESTS", 164, "HOME_AGENT_PULL_REQUESTS");
    public static final MobileAppElement PULL_REQUEST_LIST_ITEM_AGENT = new MobileAppElement("PULL_REQUEST_LIST_ITEM_AGENT", 165, "PULL_REQUEST_LIST_ITEM_AGENT");
    public static final MobileAppElement PULL_REQUEST_REVIEW_REQUESTED_FILTER = new MobileAppElement("PULL_REQUEST_REVIEW_REQUESTED_FILTER", 166, "PULL_REQUEST_REVIEW_REQUESTED_FILTER");
    public static final MobileAppElement COPILOT_CODE_REVIEW_SUGGESTED_CTA = new MobileAppElement("COPILOT_CODE_REVIEW_SUGGESTED_CTA", 167, "COPILOT_CODE_REVIEW_SUGGESTED_CTA");
    public static final MobileAppElement AGENT_TASKS = new MobileAppElement("AGENT_TASKS", 168, "AGENT_TASKS");
    public static final MobileAppElement CREATE_AGENT_TASK = new MobileAppElement("CREATE_AGENT_TASK", 169, "CREATE_AGENT_TASK");
    public static final MobileAppElement CREATE_AGENT_TASK_CONFIGURATION = new MobileAppElement("CREATE_AGENT_TASK_CONFIGURATION", 170, "CREATE_AGENT_TASK_CONFIGURATION");
    public static final MobileAppElement DRAFT_FILTER_ONBOARDING = new MobileAppElement("DRAFT_FILTER_ONBOARDING", 171, "DRAFT_FILTER_ONBOARDING");
    public static final MobileAppElement COPILOT_CODE_REVIEW_AGENT_ASSIGNED = new MobileAppElement("COPILOT_CODE_REVIEW_AGENT_ASSIGNED", 172, "COPILOT_CODE_REVIEW_AGENT_ASSIGNED");
    public static final MobileAppElement COPILOT_CODE_REVIEW_AGENT_UNASSIGNED = new MobileAppElement("COPILOT_CODE_REVIEW_AGENT_UNASSIGNED", 173, "COPILOT_CODE_REVIEW_AGENT_UNASSIGNED");
    public static final MobileAppElement DELETE_FILE_BUTTON_TAPPED = new MobileAppElement("DELETE_FILE_BUTTON_TAPPED", 174, "DELETE_FILE_BUTTON_TAPPED");
    public static final MobileAppElement DELETE_FILE_CANCELLED = new MobileAppElement("DELETE_FILE_CANCELLED", 175, "DELETE_FILE_CANCELLED");
    public static final MobileAppElement DELETE_FILE_COMMITTED_TO_EXISTING_BRANCH = new MobileAppElement("DELETE_FILE_COMMITTED_TO_EXISTING_BRANCH", 176, "DELETE_FILE_COMMITTED_TO_EXISTING_BRANCH");
    public static final MobileAppElement DELETE_FILE_COMMITTED_TO_NEW_BRANCH = new MobileAppElement("DELETE_FILE_COMMITTED_TO_NEW_BRANCH", 177, "DELETE_FILE_COMMITTED_TO_NEW_BRANCH");
    public static final MobileAppElement THIRD_PARTY_CODING_AGENT_ASSIGNED = new MobileAppElement("THIRD_PARTY_CODING_AGENT_ASSIGNED", 178, "THIRD_PARTY_CODING_AGENT_ASSIGNED");
    public static final MobileAppElement THIRD_PARTY_CODING_AGENT_UNASSIGNED = new MobileAppElement("THIRD_PARTY_CODING_AGENT_UNASSIGNED", 179, "THIRD_PARTY_CODING_AGENT_UNASSIGNED");
    public static final MobileAppElement THIRD_PARTY_CODING_AGENT_WORK_SESSION = new MobileAppElement("THIRD_PARTY_CODING_AGENT_WORK_SESSION", 180, "THIRD_PARTY_CODING_AGENT_WORK_SESSION");
    public static final MobileAppElement ASSIGN_AGENT_INSTRUCTIONS_PILL = new MobileAppElement("ASSIGN_AGENT_INSTRUCTIONS_PILL", 181, "ASSIGN_AGENT_INSTRUCTIONS_PILL");
    public static final MobileAppElement ASSIGN_AGENT_MENU = new MobileAppElement("ASSIGN_AGENT_MENU", 182, "ASSIGN_AGENT_MENU");
    public static final MobileAppElement ASSIGN_AGENT_SUBMIT = new MobileAppElement("ASSIGN_AGENT_SUBMIT", 183, "ASSIGN_AGENT_SUBMIT");
    public static final MobileAppElement ASSIGN_AGENT_TOOLTIP_DISMISS = new MobileAppElement("ASSIGN_AGENT_TOOLTIP_DISMISS", 184, "ASSIGN_AGENT_TOOLTIP_DISMISS");
    public static final MobileAppElement ASSIGN_AGENT_CREATE_ISSUE = new MobileAppElement("ASSIGN_AGENT_CREATE_ISSUE", 185, "ASSIGN_AGENT_CREATE_ISSUE");
    public static final MobileAppElement ASSIGN_AGENT_INSTRUCTIONS_TOOLTIP_DISMISS = new MobileAppElement("ASSIGN_AGENT_INSTRUCTIONS_TOOLTIP_DISMISS", 186, "ASSIGN_AGENT_INSTRUCTIONS_TOOLTIP_DISMISS");
    public static final MobileAppElement AGENT_TASKS_FILTER = new MobileAppElement("AGENT_TASKS_FILTER", 187, "AGENT_TASKS_FILTER");
    public static final MobileAppElement AGENT_TASKS_SEARCH = new MobileAppElement("AGENT_TASKS_SEARCH", 188, "AGENT_TASKS_SEARCH");
    public static final MobileAppElement COPILOT_CHAT_LIST_SEARCH = new MobileAppElement("COPILOT_CHAT_LIST_SEARCH", 189, "COPILOT_CHAT_LIST_SEARCH");
    public static final MobileAppElement COPILOT_HOME_AGENT_SESSIONS_COLLAPSE = new MobileAppElement("COPILOT_HOME_AGENT_SESSIONS_COLLAPSE", 190, "COPILOT_HOME_AGENT_SESSIONS_COLLAPSE");
    public static final MobileAppElement COPILOT_HOME_AGENT_SESSIONS_EXPAND = new MobileAppElement("COPILOT_HOME_AGENT_SESSIONS_EXPAND", 191, "COPILOT_HOME_AGENT_SESSIONS_EXPAND");
    public static final MobileAppElement COPILOT_HOME_CHAT_SESSIONS_COLLAPSE = new MobileAppElement("COPILOT_HOME_CHAT_SESSIONS_COLLAPSE", 192, "COPILOT_HOME_CHAT_SESSIONS_COLLAPSE");
    public static final MobileAppElement COPILOT_HOME_CHAT_SESSIONS_EXPAND = new MobileAppElement("COPILOT_HOME_CHAT_SESSIONS_EXPAND", 193, "COPILOT_HOME_CHAT_SESSIONS_EXPAND");
    public static final MobileAppElement COPILOT_HOME_CREATE_MENU_FAB = new MobileAppElement("COPILOT_HOME_CREATE_MENU_FAB", 194, "COPILOT_HOME_CREATE_MENU_FAB");
    public static final MobileAppElement COPILOT_TAB = new MobileAppElement("COPILOT_TAB", 195, "COPILOT_TAB");
    public static final MobileAppElement HOME_PROFILE = new MobileAppElement("HOME_PROFILE", 196, "HOME_PROFILE");
    public static final MobileAppElement AGENT_LOGS = new MobileAppElement("AGENT_LOGS", 197, "AGENT_LOGS");
    public static final MobileAppElement AGENT_LOG_CREATE_PR = new MobileAppElement("AGENT_LOG_CREATE_PR", 198, "AGENT_LOG_CREATE_PR");
    public static final MobileAppElement AGENT_LOG_FALLBACK_RENDERING = new MobileAppElement("AGENT_LOG_FALLBACK_RENDERING", 199, "AGENT_LOG_FALLBACK_RENDERING");
    public static final MobileAppElement AGENT_LOG_FILE_DIFF_CARD = new MobileAppElement("AGENT_LOG_FILE_DIFF_CARD", 200, "AGENT_LOG_FILE_DIFF_CARD");
    public static final MobileAppElement AGENT_LOG_TOOLCALL_DETAIL = new MobileAppElement("AGENT_LOG_TOOLCALL_DETAIL", 201, "AGENT_LOG_TOOLCALL_DETAIL");
    public static final MobileAppElement AGENT_LOG_VIEW_PR = new MobileAppElement("AGENT_LOG_VIEW_PR", 202, "AGENT_LOG_VIEW_PR");
    public static final MobileAppElement COPILOT_HOME_UPSELL = new MobileAppElement("COPILOT_HOME_UPSELL", 203, "COPILOT_HOME_UPSELL");
    public static final MobileAppElement CREATE_AGENT_TASK_FROM_EMPTY_STATE = new MobileAppElement("CREATE_AGENT_TASK_FROM_EMPTY_STATE", 204, "CREATE_AGENT_TASK_FROM_EMPTY_STATE");
    public static final MobileAppElement NEW_CONVERSATION_FROM_EMPTY_STATE = new MobileAppElement("NEW_CONVERSATION_FROM_EMPTY_STATE", 205, "NEW_CONVERSATION_FROM_EMPTY_STATE");
    public static final MobileAppElement AGENT_LOG_PERMISSION_REQUEST = new MobileAppElement("AGENT_LOG_PERMISSION_REQUEST", 206, "AGENT_LOG_PERMISSION_REQUEST");
    public static final MobileAppElement AGENT_LOG_PLAN_APPROVAL = new MobileAppElement("AGENT_LOG_PLAN_APPROVAL", 207, "AGENT_LOG_PLAN_APPROVAL");
    public static final MobileAppElement AGENT_LOG_STEER_INPUT = new MobileAppElement("AGENT_LOG_STEER_INPUT", 208, "AGENT_LOG_STEER_INPUT");
    public static final MobileAppElement AGENT_LOG_STOP = new MobileAppElement("AGENT_LOG_STOP", 209, "AGENT_LOG_STOP");
    public static final MobileAppElement AGENT_LOG_USER_ASK = new MobileAppElement("AGENT_LOG_USER_ASK", 210, "AGENT_LOG_USER_ASK");
    public static final MobileAppElement CREATE_REPO_BACK = new MobileAppElement("CREATE_REPO_BACK", 211, "CREATE_REPO_BACK");
    public static final MobileAppElement CREATE_REPO_DISMISS = new MobileAppElement("CREATE_REPO_DISMISS", 212, "CREATE_REPO_DISMISS");
    public static final MobileAppElement CREATE_REPO_FLOW_OPEN = new MobileAppElement("CREATE_REPO_FLOW_OPEN", 213, "CREATE_REPO_FLOW_OPEN");
    public static final MobileAppElement CREATE_REPO_GITIGNORE_PICKER = new MobileAppElement("CREATE_REPO_GITIGNORE_PICKER", 214, "CREATE_REPO_GITIGNORE_PICKER");
    public static final MobileAppElement CREATE_REPO_GITIGNORE_SELECT = new MobileAppElement("CREATE_REPO_GITIGNORE_SELECT", 215, "CREATE_REPO_GITIGNORE_SELECT");
    public static final MobileAppElement CREATE_REPO_LICENSE_PICKER = new MobileAppElement("CREATE_REPO_LICENSE_PICKER", 216, "CREATE_REPO_LICENSE_PICKER");
    public static final MobileAppElement CREATE_REPO_LICENSE_SELECT = new MobileAppElement("CREATE_REPO_LICENSE_SELECT", 217, "CREATE_REPO_LICENSE_SELECT");
    public static final MobileAppElement CREATE_REPO_NEXT = new MobileAppElement("CREATE_REPO_NEXT", 218, "CREATE_REPO_NEXT");
    public static final MobileAppElement CREATE_REPO_README_TOGGLE = new MobileAppElement("CREATE_REPO_README_TOGGLE", 219, "CREATE_REPO_README_TOGGLE");
    public static final MobileAppElement CREATE_REPO_SUBMIT = new MobileAppElement("CREATE_REPO_SUBMIT", 220, "CREATE_REPO_SUBMIT");
    public static final MobileAppElement CREATE_REPO_TEMPLATE_PICKER = new MobileAppElement("CREATE_REPO_TEMPLATE_PICKER", 221, "CREATE_REPO_TEMPLATE_PICKER");
    public static final MobileAppElement CREATE_REPO_TEMPLATE_SELECT = new MobileAppElement("CREATE_REPO_TEMPLATE_SELECT", 222, "CREATE_REPO_TEMPLATE_SELECT");
    public static final MobileAppElement CREATE_REPO_VISIBILITY_TOGGLE = new MobileAppElement("CREATE_REPO_VISIBILITY_TOGGLE", 223, "CREATE_REPO_VISIBILITY_TOGGLE");
    public static final MobileAppElement UNKNOWN__ = new MobileAppElement("UNKNOWN__", 224, "UNKNOWN__");

    private static final /* synthetic */ MobileAppElement[] $values() {
        return new MobileAppElement[]{REPOSITORY_DISCUSSIONS_LIST_FILTER, VIEWER_DISCUSSIONS_LIST_FILTER, EXPLORE_BOTTOM_NAVIGATION, EXPLORE_TRENDING_REPOSITORY, EXPLORE_FOR_YOU_REPOSITORY, EXPLORE_FEATURED_REPOSITORY, EXPLORE_STAR_TRENDING_REPOSITORY, EXPLORE_STAR_FOR_YOU_REPOSITORY, EXPLORE_STAR_FEATURED_REPOSITORY, EXPLORE_TRENDING_LIST_FILTER, FOLLOW, HOME_BOTTOM_NAVIGATION, HOME_ISSUES, HOME_FAVORITE_REPOSITORY_ITEM, HOME_PULL_REQUESTS, HOME_RECENT_ACTIVITY_ITEM, HOME_REPOSITORIES, HOME_STARRED, HOME_SHORTCUTS, HOME_ORGANIZATIONS, HOME_CREATE_ISSUE, HOME_RELEASE_NOTES, HOME_DISCUSSIONS, HOME_PROJECTS, HOME_IN_APP_UPDATE, NOTIFICATION_LIST, NOTIFICATION_LIST_ITEM, NOTIFICATION_LIST_ITEM_UNDO, NOTIFICATION_LIST_ITEM_FOCUSED, NOTIFICATION_LIST_FILTER, NOTIFICATION_FILTER, NOTIFICATION_BOTTOM_NAVIGATION, NOTIFICATION_PUSH, ISSUES_LIST_ITEM, VIEWER_ISSUES_LIST_FILTER, REPOSITORY_ISSUES_LIST_FILTER, ISSUES_SEARCH, ISSUE_COMPOSER, ISSUE_COMPOSER_PROPERTY_BAR, PULL_REQUESTS_LIST_ITEM, VIEWER_PULL_REQUESTS_LIST_FILTER, REPOSITORY_PULL_REQUESTS_LIST_FILTER, SHORTCUTS_LIST_ITEM, SHORTCUT_SUGGESTIONS_LIST_ITEM, SHOW_MORE_ROLLUP, STAR_REPOSITORY, PROFILE_BOTTOM_NAVIGATION, PULL_REQUESTS_SEARCH, TRIAGE_EXPAND, TRIAGE_COMMENT, TRIAGE_COMMENT_UP, TRIAGE_COMMENT_DOWN, TRIAGE_COMMENT_EDIT, TRIAGE_REVIEW_REQUEST_EDIT, TRIAGE_ASSIGNEE_EDIT, TRIAGE_ISSUE_TYPE_EDIT, TRIAGE_LABEL_EDIT, TRIAGE_LINKED_ITEM_EDIT, TRIAGE_PROJECT_EDIT, TRIAGE_PROJECT_NEXT_EDIT, TRIAGE_PROJECT_NEXT_PICKER_OWNER, TRIAGE_PROJECT_NEXT_PICKER_RECENT, TRIAGE_MILESTONE_EDIT, TRIAGE_CLOSE, TRIAGE_LOCK, TRIAGE_UNSUBSCRIBE, ONBOARDING_BANNER, NOTIFICATIONS_ONBOARDING_BANNER, REPOSITORY_LATEST_RELEASE, RELEASES_LIST_LATEST_RELEASE, RELEASE_DOWNLOAD_ASSET, RELEASE_LINKED_DISCUSSION, VIEWER_PULL_TO_REFRESH, PROJECTS_LIST_ITEM, PROJECTS_QUICK_ACTION_CLOSE, PROJECTS_QUICK_ACTION_DELETE, PROJECTS_QUICK_ACTION_EDIT_FIELD, PROJECTS_QUICK_ACTION_EDIT_TITLE, PROJECTS_QUICK_ACTION_OPEN_DETAILS, PROJECTS_QUICK_ACTION_OTHER_PROJECTS, PROJECTS_QUICK_ACTION_REOPEN, PROJECTS_TABLE_VIEW_LIST_ITEM, PROJECT_VIEW, PROJECT_VIEW_TIMEOUT_CTA, HOME_REPOSITORY_LIST_FILTER, PROFILE_REPOSITORY_LIST_FILTER, SETTINGS_DISABLE_ANALYTICS, SETTINGS_ENABLE_APP_LOCK, ACCOUNT_SWITCHER_ADD, ACCOUNT_SWITCHER_ITEM, ACCOUNT_SWITCHER_REMOVE, PROFILE_HEADER_NAME, SETTINGS_ACCOUNTS, VIEWING_AS_TOAST, DEEP_LINK_ERROR_ACCOUNT_SWITCHER, REPOSITORY_EDIT_README, CODE_SEARCH_LIST_ITEM, GLOBAL_SEARCH_SHORTCUT, HOME_ISSUES_LIST_NEW_ISSUE, COPILOT_CHAT_BUTTON, COPILOT_CHAT_CONVERSATION, COPILOT_CHAT_MESSAGE_COPY, COPILOT_CHAT_SUGGESTION, COPILOT_AGREEMENT, COPILOT_ALL_CONVERSATIONS, COPILOT_BUY, COPILOT_DELETE_CONVERSATION, COPILOT_DISMISS_PAYWALL, COPILOT_LEARN_MORE, COPILOT_MANAGE_SUBSCRIPTION, COPILOT_NEW_CONVERSATION, COPILOT_POLICY_DISABLED_LINK, COPILOT_PRIVACY_POLICY, COPILOT_RECENT_CONVERSATION, COPILOT_RESTORE_PURCHASE, COPILOT_SCOPE_LINK, COPILOT_SETTINGS_ENABLE, COPILOT_SETTINGS_HIDE_BOA, COPILOT_UPSELL_DISMISS, COPILOT_UPSELL_LEARN_MORE, FINISH_REVIEW_BOA, PULL_REQUEST_FILES_CHANGED, PULL_REQUEST_REVIEW_BANNER, PULL_REQUEST_REVIEW_CTA, SUBMIT_REVIEW, FOCUS_CTA_DISMISSED, FOCUS_CTA_ENABLED, FOCUS_CTA_VIEWED, PIN_SHORTCUT, PUSH_NOTIFICATIONS_PERMISSION_DIALOG_ALLOW, PUSH_NOTIFICATIONS_PERMISSION_DIALOG_DENY, COMPARE_BRANCHES, COMPARE_BRANCHES_ACTIVE_PULL_REQUEST, COMPARE_BRANCHES_COMMITS, COMPARE_BRANCHES_CREATE_PULL_REQUEST, COMPARE_BRANCHES_FILES_CHANGED, PULL_REQUEST_COMPOSER_SUBMIT, PULL_REQUEST_LEGACY_CREATION_SUBMIT, NOTIFICATION_ONBOARDING_CONTINUE_BANNER, NOTIFICATION_ONBOARDING_MISSING_OUT_BANNER, NOTIFICATION_ONBOARDING_NUX_BANNER, NOTIFICATION_ONBOARDING_PROGRESS, NOTIFICATION_ONBOARDING_PROGRESS_REVIEW, NOTIFICATION_ONBOARDING_RECAPTURE, NOTIFICATION_ONBOARDING_REVIEW_BANNER, NOTIFICATION_ONBOARDING_REVIEW_CHANGE_SETTINGS, SUB_ISSUE_ADD_EXISTING_ISSUE, SUB_ISSUE_ADD_NEW_ISSUE, SUB_ISSUE_EDIT_PARENT_ISSUE, SUB_ISSUE_EDIT_SUB_ISSUE, SUB_ISSUE_ISSUE, SUB_ISSUE_NESTED_ISSUES_TOGGLE, SUB_ISSUE_PARENT_ISSUE, SUB_ISSUE_SECTION, NOTIFICATION_ONBOARDING_EXPIRED_TWO_FACTOR_BANNER, MODEL_PICKER, MODEL_PICKER_ITEM, CODING_AGENT_ASSIGNED, CODING_AGENT_UNASSIGNED, CODING_AGENT_WORK_SESSION, COPILOT_CODE_REVIEW_BANNER, COPILOT_SEND_MESSAGE, CODING_AGENT_BANNER, COPILOT_EXPLAIN_ERROR, HOME_AGENT_PULL_REQUESTS, PULL_REQUEST_LIST_ITEM_AGENT, PULL_REQUEST_REVIEW_REQUESTED_FILTER, COPILOT_CODE_REVIEW_SUGGESTED_CTA, AGENT_TASKS, CREATE_AGENT_TASK, CREATE_AGENT_TASK_CONFIGURATION, DRAFT_FILTER_ONBOARDING, COPILOT_CODE_REVIEW_AGENT_ASSIGNED, COPILOT_CODE_REVIEW_AGENT_UNASSIGNED, DELETE_FILE_BUTTON_TAPPED, DELETE_FILE_CANCELLED, DELETE_FILE_COMMITTED_TO_EXISTING_BRANCH, DELETE_FILE_COMMITTED_TO_NEW_BRANCH, THIRD_PARTY_CODING_AGENT_ASSIGNED, THIRD_PARTY_CODING_AGENT_UNASSIGNED, THIRD_PARTY_CODING_AGENT_WORK_SESSION, ASSIGN_AGENT_INSTRUCTIONS_PILL, ASSIGN_AGENT_MENU, ASSIGN_AGENT_SUBMIT, ASSIGN_AGENT_TOOLTIP_DISMISS, ASSIGN_AGENT_CREATE_ISSUE, ASSIGN_AGENT_INSTRUCTIONS_TOOLTIP_DISMISS, AGENT_TASKS_FILTER, AGENT_TASKS_SEARCH, COPILOT_CHAT_LIST_SEARCH, COPILOT_HOME_AGENT_SESSIONS_COLLAPSE, COPILOT_HOME_AGENT_SESSIONS_EXPAND, COPILOT_HOME_CHAT_SESSIONS_COLLAPSE, COPILOT_HOME_CHAT_SESSIONS_EXPAND, COPILOT_HOME_CREATE_MENU_FAB, COPILOT_TAB, HOME_PROFILE, AGENT_LOGS, AGENT_LOG_CREATE_PR, AGENT_LOG_FALLBACK_RENDERING, AGENT_LOG_FILE_DIFF_CARD, AGENT_LOG_TOOLCALL_DETAIL, AGENT_LOG_VIEW_PR, COPILOT_HOME_UPSELL, CREATE_AGENT_TASK_FROM_EMPTY_STATE, NEW_CONVERSATION_FROM_EMPTY_STATE, AGENT_LOG_PERMISSION_REQUEST, AGENT_LOG_PLAN_APPROVAL, AGENT_LOG_STEER_INPUT, AGENT_LOG_STOP, AGENT_LOG_USER_ASK, CREATE_REPO_BACK, CREATE_REPO_DISMISS, CREATE_REPO_FLOW_OPEN, CREATE_REPO_GITIGNORE_PICKER, CREATE_REPO_GITIGNORE_SELECT, CREATE_REPO_LICENSE_PICKER, CREATE_REPO_LICENSE_SELECT, CREATE_REPO_NEXT, CREATE_REPO_README_TOGGLE, CREATE_REPO_SUBMIT, CREATE_REPO_TEMPLATE_PICKER, CREATE_REPO_TEMPLATE_SELECT, CREATE_REPO_VISIBILITY_TOGGLE, UNKNOWN__};
    }

    static {
        MobileAppElement[] $values = $values();
        $VALUES = $values;
        $ENTRIES = l0.t($values);
        Companion = new j();
    }

    private MobileAppElement(String str, int i, String str2) {
        this.rawValue = str2;
    }

    public static a getEntries() {
        return $ENTRIES;
    }

    public static MobileAppElement valueOf(String str) {
        return (MobileAppElement) Enum.valueOf(MobileAppElement.class, str);
    }

    public static MobileAppElement[] values() {
        return (MobileAppElement[]) $VALUES.clone();
    }

    public final String getRawValue() {
        return this.rawValue;
    }
}
