package com.google.android.gms.measurement.internal;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class c0 {
    public static final b0 A;
    public static final b0 A0;
    public static final b0 B;
    public static final b0 B0;
    public static final b0 C;
    public static final b0 C0;
    public static final b0 D;
    public static final b0 D0;
    public static final b0 E;
    public static final b0 E0;
    public static final b0 F;
    public static final b0 F0;
    public static final b0 G;
    public static final b0 G0;
    public static final b0 H;
    public static final b0 H0;
    public static final b0 I;
    public static final b0 I0;
    public static final b0 J;
    public static final b0 J0;
    public static final b0 K;
    public static final b0 K0;
    public static final b0 L;
    public static final b0 L0;
    public static final b0 M;
    public static final b0 M0;
    public static final b0 N;
    public static final b0 N0;
    public static final b0 O;
    public static final b0 O0;
    public static final b0 P;
    public static final b0 P0;
    public static final b0 Q;
    public static final b0 Q0;
    public static final b0 R;
    public static final b0 R0;
    public static final b0 S;
    public static final b0 S0;
    public static final b0 T;
    public static final b0 T0;
    public static final b0 U;
    public static final b0 U0;
    public static final b0 V;
    public static final b0 V0;
    public static final b0 W;
    public static final b0 W0;
    public static final b0 X;
    public static final b0 X0;
    public static final b0 Y;
    public static final b0 Y0;
    public static final b0 Z;
    public static final b0 Z0;
    public static final List a = Collections.synchronizedList(new ArrayList());
    public static final b0 a0;
    public static final b0 a1;
    public static final b0 b;
    public static final b0 b0;
    public static final b0 b1;
    public static final b0 c;
    public static final b0 c0;
    public static final b0 c1;
    public static final b0 d;
    public static final b0 d0;
    public static final b0 d1;
    public static final b0 e;
    public static final b0 e0;
    public static final b0 e1;
    public static final b0 f;
    public static final b0 f0;
    public static final b0 f1;
    public static final b0 g;
    public static final b0 g0;
    public static final b0 g1;
    public static final b0 h;
    public static final b0 h0;
    public static final b0 h1;
    public static final b0 i;
    public static final b0 i0;
    public static final b0 i1;
    public static final b0 j;
    public static final b0 j0;
    public static final b0 j1;
    public static final b0 k;
    public static final b0 k0;
    public static final b0 k1;
    public static final b0 l;
    public static final b0 l0;
    public static final b0 m;
    public static final b0 m0;
    public static final b0 n;
    public static final b0 n0;
    public static final b0 o;
    public static final b0 o0;
    public static final b0 p;
    public static final b0 p0;
    public static final b0 q;
    public static final b0 q0;
    public static final b0 r;
    public static final b0 r0;
    public static final b0 s;
    public static final b0 s0;
    public static final b0 t;
    public static final b0 t0;
    public static final b0 u;
    public static final b0 u0;
    public static final b0 v;
    public static final b0 v0;
    public static final b0 w;
    public static final b0 w0;
    public static final b0 x;
    public static final b0 x0;
    public static final b0 y;
    public static final b0 y0;
    public static final b0 z;
    public static final b0 z0;

    static {
        Collections.synchronizedSet(new HashSet());
        b = a("measurement.ad_id_cache_time", 10000L, e50.z0.v, false);
        c = a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, z70.m3.s, false);
        d = a("measurement.monitoring.sample_period_millis", 86400000L, n51.e.s, false);
        e = a("measurement.config.cache_time", 86400000L, z70.y1.t, false);
        f = a("measurement.config.url_scheme", "https", e50.e.t, false);
        g = a("measurement.config.url_authority", "app-measurement.com", rb0.b.t, false);
        h = a("measurement.upload.max_bundles", 100, z70.m2.u, false);
        i = a("measurement.upload.max_batch_size", 65536, e50.k.v, false);
        j = a("measurement.upload.max_bundle_size", 65536, u31.f.u, false);
        k = a("measurement.upload.max_events_per_bundle", 1000, z70.a3.v, false);
        l = a("measurement.upload.max_events_per_day", 100000, e50.y.v, false);
        m = a("measurement.upload.max_error_events_per_day", 1000, e50.e.s, false);
        n = a("measurement.upload.max_public_events_per_day", 50000, e50.k.t, false);
        o = a("measurement.upload.max_conversions_per_day", 10000, e50.y.s, false);
        p = a("measurement.upload.max_realtime_events_per_day", 10, e50.z0.s, false);
        q = a("measurement.store.max_stored_events_per_app", 100000, i50.c.s, false);
        r = a("measurement.upload.url", "https://app-measurement.com/a", i80.d.s, false);
        s = a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s/d", k50.c.s, false);
        t = a("measurement.sgtm.service_upload_apps_list", "", k60.f.s, false);
        u = a("measurement.sgtm.upload.backoff_http_codes", "404,429,503,504", la0.d.s, false);
        v = a("measurement.sgtm.upload.retry_interval", 600000L, m90.c.s, false);
        w = a("measurement.sgtm.upload.retry_max_wait", 21600000L, rb0.b.s, false);
        x = a("measurement.sgtm.batch.retry_interval", 1800000L, u31.f.s, false);
        y = a("measurement.sgtm.batch.retry_max_wait", 21600000L, w50.c.s, false);
        z = a("measurement.sgtm.batch.retry_max_count", 10, w50.m.s, false);
        A = a("measurement.sgtm.upload.max_queued_batches", 5000, w80.t.s, false);
        B = a("measurement.sgtm.upload.batches_retrieval_limit", 5, w80.a0Shadow.s, false);
        C = a("measurement.sgtm.upload.min_delay_after_startup", 5000L, w80.n3.s, false);
        D = a("measurement.sgtm.upload.min_delay_after_broadcast", 1000L, w80.w3.s, false);
        E = a("measurement.sgtm.upload.min_delay_after_background", 600000L, y60.b.t, false);
        F = a("measurement.sgtm.batch.long_queuing_threshold", 14400000L, z70.w.t, false);
        G = a("measurement.upload.backoff_period", 43200000L, z70.m2.t, false);
        a("measurement.upload.window_interval", 3600000L, z70.a3.t, false);
        H = a("measurement.upload.interval", 3600000L, z70.j3.t, false);
        I = a("measurement.upload.realtime_upload_interval", 10000L, z70.m3.t, false);
        J = a("measurement.upload.debug_upload_interval", 1000L, z70.x3.t, false);
        K = a("measurement.upload.minimum_delay", 500L, c21.j.u, false);
        L = a("measurement.alarm_manager.minimum_interval", 60000L, c30.d.t, false);
        M = a("measurement.upload.stale_data_deletion_interval", 86400000L, c30.o0.t, false);
        N = a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, c30.s0.t, false);
        O = a("measurement.upload.initial_upload_delay_time", 15000L, d9.e.t, false);
        P = a("measurement.upload.retry_time", 1800000L, e50.k.u, false);
        Q = a("measurement.upload.retry_count", 6, e50.y.t, false);
        R = a("measurement.upload.max_queue_time", 518400000L, e50.z0.t, false);
        S = a("measurement.upload.google_signal_max_queue_time", 300000L, i50.c.t, false);
        T = a("measurement.lifetimevalue.max_currency_tracked", 4, i80.d.t, false);
        U = a("measurement.audience.filter_result_max_count", 200, k50.c.t, false);
        V = a("measurement.upload.max_public_user_properties", 100, null, false);
        W = a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        X = a("measurement.upload.max_public_event_params", 100, null, false);
        Y = a("measurement.service_client.idle_disconnect_millis", 5000L, k60.f.t, false);
        Z = a("measurement.service_client.reconnect_millis", 1000L, la0.d.t, false);
        Boolean bool = Boolean.FALSE;
        a0 = a("measurement.test.boolean_flag", bool, m90.c.t, false);
        b0 = a("measurement.test.string_flag", "---", n51.e.t, false);
        c0 = a("measurement.test.long_flag", -1L, u31.f.t, false);
        a("measurement.test.cached_long_flag", -1L, w50.c.t, true);
        d0 = a("measurement.test.int_flag", -2, w50.m.t, false);
        e0 = a("measurement.test.double_flag", Double.valueOf(-3.0d), w80.t.t, false);
        f0 = a("measurement.experiment.max_ids", 50, w80.a0Shadow.t, false);
        g0 = a("measurement.upload.max_item_scoped_custom_parameters", 27, w80.n3.t, false);
        h0 = a("measurement.upload.max_event_parameter_value_length", 500, w80.w3.t, true);
        i0 = a("measurement.max_bundles_per_iteration", 100, y60.b.u, false);
        j0 = a("measurement.sdk.attribution.cache.ttl", 604800000L, z70.w.u, false);
        k0 = a("measurement.redaction.app_instance_id.ttl", 7200000L, z70.y1.u, false);
        l0 = a("measurement.rb.attribution.client.min_ad_services_version", 7, z70.a3.u, false);
        m0 = a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, z70.j3.u, false);
        n0 = a("measurement.rb.attribution.uri_scheme", "https", z70.m3.u, false);
        o0 = a("measurement.rb.attribution.uri_authority", "google-analytics.com", z70.x3.u, false);
        p0 = a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", c21.j.v, false);
        q0 = a("measurement.session.engagement_interval", 3600000L, c30.d.u, false);
        r0 = a("measurement.rb.attribution.app_allowlist", "", c30.o0.u, false);
        s0 = a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", c30.s0.u, false);
        t0 = a("measurement.rb.attribution.event_params", "value|currency", d9.e.u, false);
        u0 = a("measurement.rb.attribution.query_parameters_to_remove", "", e50.e.u, false);
        v0 = a("measurement.rb.attribution.max_queue_time", 864000000L, e50.y.u, false);
        w0 = a("measurement.rb.attribution.max_retry_delay_seconds", 16, e50.z0.u, false);
        x0 = a("measurement.rb.attribution.client.min_time_after_boot_seconds", 90, i50.c.u, false);
        a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, i80.d.u, false);
        y0 = a("measurement.rb.max_trigger_registrations_per_day", 1000, k50.c.u, false);
        Boolean bool2 = Boolean.TRUE;
        z0 = a("measurement.config.bundle_for_all_apps_on_backgrounded", bool2, k60.f.u, false);
        A0 = a("measurement.config.notify_trigger_uris_on_backgrounded", bool2, la0.d.u, false);
        B0 = a("measurement.rb.attribution.notify_app_delay_millis", 3000, m90.c.u, false);
        C0 = a("measurement.quality.checksum", bool, null, false);
        D0 = a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, n51.e.u, false);
        E0 = a("measurement.audience.refresh_event_count_filters_timestamp", bool, rb0.b.u, false);
        F0 = a("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, w50.c.u, true);
        G0 = a("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, w50.m.u, false);
        H0 = a("measurement.integration.disable_firebase_instance_id", bool, w80.t.u, false);
        I0 = a("measurement.collection.service.update_with_analytics_fix", bool, w80.a0Shadow.u, false);
        J0 = a("measurement.service.storage_consent_support_version", 203600, w80.n3.u, false);
        K0 = a("measurement.service.store_null_safelist", bool2, w80.w3.u, false);
        L0 = a("measurement.service.store_safelist", bool2, y60.b.v, false);
        M0 = a("measurement.session_stitching_token_enabled", bool, z70.w.v, false);
        N0 = a("measurement.sgtm.client.upload_on_backgrounded.dev", bool, z70.y1.v, true);
        O0 = a("measurement.gmscore_client_telemetry", bool, i80.d.v, false);
        P0 = a("measurement.rb.attribution.service", bool2, z70.m2.v, true);
        Q0 = a("measurement.rb.attribution.client2", bool2, z70.j3.v, true);
        R0 = a("measurement.rb.attribution.uuid_generation", bool2, z70.m3.v, false);
        S0 = a("measurement.rb.attribution.enable_trigger_redaction", bool2, z70.x3.v, false);
        a("measurement.rb.attribution.followup1.service", bool, c21.j.w, false);
        T0 = a("measurement.rb.attribution.retry_disposition", bool, c30.d.v, false);
        U0 = a("measurement.client.sessions.enable_fix_background_engagement", bool, k60.f.v, false);
        V0 = a("measurement.set_default_event_parameters_propagate_clear.service.dev", bool2, c30.o0.v, false);
        W0 = a("measurement.set_default_event_parameters_propagate_clear.client.dev", bool2, c30.s0.v, false);
        X0 = a("measurement.service.ad_impression.convert_value_to_double", bool2, d9.e.v, false);
        a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", bool2, e50.e.v, false);
        a("measurement.remove_conflicting_first_party_apis.dev", bool, e50.k.w, false);
        Y0 = a("measurement.rb.attribution.service.trigger_uris_high_priority", bool2, z70.x3.s, false);
        Z0 = a("measurement.tcf.consent_fix", bool2, c21.j.t, false);
        a1 = a("measurement.experiment.enable_phenotype_experiment_reporting", bool2, c30.d.s, false);
        b1 = a("measurement.set_default_event_parameters.fix_service_request_ordering", bool, z70.y1.s, false);
        c1 = a("measurement.set_default_event_parameters.fix_app_update_logging", bool2, z70.w.s, false);
        d1 = a("measurement.service.fix_stop_bundling_bug", bool2, z70.j3.s, false);
        e1 = a("measurement.fix_params_logcat_spam", bool2, z70.a3.s, false);
        f1 = a("measurement.gbraid_campaign.stop_lgclid", bool, i50.c.v, false);
        g1 = a("measurement.gbraid_compaign.compaign_params_triggering_info_update", "gclid,gbraid,gad_campaignid", c30.o0.s, false);
        h1 = a("measurement.edpb.service", bool, z70.m2.s, false);
        i1 = a("measurement.edpb.events_cached_in_no_data_mode", "_f,_v,_cmp", c30.s0.s, false);
        j1 = a("measurement.add_first_launch_logging_timestamp.service", bool, k50.c.v, false);
        k1 = a("measurement.overlapping_bundles_fix", bool, d9.e.s, false);
    }

    public static b0 a(String str, Object obj, x xVar, boolean z2) {
        b0 b0Var = new b0(str, obj, xVar);
        if (z2) {
            a.add(b0Var);
        }
        return b0Var;
    }
}
