package d30;

import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import aa.x0;
import hc0.ap;
import hc0.bb;
import hc0.cw;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.hb;
import hc0.jn;
import hc0.ra;
import hc0.s9;
import hc0.t3;
import hc0.ta;
import hc0.x9;
import hc0.xa;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class d {
    public static final List a;

    static {
        fb.Companion.getClass();
        x xVar = fb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        s mVar = new m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = d0.n("FileLine");
        List list = p50.a.a;
        List r = l.r(new s[]{mVar, no.a.c(list, "selections", "FileLine", n, list)});
        hb.Companion.getClass();
        x xVar2 = hb.a;
        k.g(xVar2, "type");
        m mVar2 = new m("contentHTML", xVar2, (String) null, rVar, rVar, rVar);
        x9.Companion.getClass();
        q0 q0Var = x9.a;
        List r2 = l.r(new m[]{mVar2, new m("fileLines", l0.a(q0Var), "markDownFileLines", rVar, rVar, r)});
        ew.Companion.getClass();
        x xVar3 = ew.a;
        k.g(xVar3, "type");
        List r3 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("MarkdownFileType", d0.n("MarkdownFileType"), r2), new n("ImageFileType", d0.n("ImageFileType"), d0.n(new m("url", xVar3, (String) null, rVar, rVar, rVar))), new n("PdfFileType", d0.n("PdfFileType"), d0.n(new m("url", xVar3, (String) null, rVar, rVar, rVar))), new n("TextFileType", d0.n("TextFileType"), d0.n(new m("fileLines", l0.a(q0Var), "textFieldFileLines", rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("FileLine", d0.n("FileLine"), list)}))))});
        m mVar3 = new m("extension", xVar, (String) null, rVar, rVar, rVar);
        m mVar4 = new m("path", xVar, (String) null, rVar, rVar, rVar);
        s9.Companion.getClass();
        x0 x0Var = s9.a;
        k.g(x0Var, "type");
        List r4 = l.r(new m[]{mVar3, mVar4, new m("fileType", x0Var, (String) null, rVar, rVar, r3)});
        cw.Companion.getClass();
        q0 q0Var2 = cw.a;
        k.g(q0Var2, "type");
        t3.Companion.getClass();
        m mVar5 = new m("file", q0Var2, (String) null, rVar, no.a.s(t3.e, new u0(new t("path"))), r4);
        bb.Companion.getClass();
        x xVar4 = bb.a;
        List r5 = l.r(new m[]{mVar5, new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        s mVar6 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r6 = l.r(new String[]{"Achievement", "AchievementTier", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list2 = ka0.a.a;
        List r7 = l.r(new s[]{mVar6, no.a.c(list2, "selections", "Node", r6, list2), new n("Commit", d0.n("Commit"), r5)});
        m mVar7 = new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        ta.Companion.getClass();
        List r8 = l.r(new m[]{mVar7, new m("oid", l0.b(ta.a), (String) null, rVar, rVar, rVar)});
        m mVar8 = new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar5 = xa.a;
        m mVar10 = new m("viewerCanCommitToBranch", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        ra.Companion.getClass();
        j0 j0Var = ra.a;
        k.g(j0Var, "type");
        List r9 = l.r(new m[]{mVar8, mVar9, mVar10, new m("target", j0Var, (String) null, rVar, rVar, r8), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r11 = l.r(new m[]{new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        m mVar11 = new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        db.Companion.getClass();
        x xVar6 = db.a;
        k.g(xVar6, "type");
        m mVar12 = new m("databaseId", xVar6, (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        m mVar13 = new m("object", j0Var, "gitObject", rVar, no.a.s(ap.F, new u0(new t("ref"))), r7);
        m mVar14 = new m("viewerCanPush", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        jn.Companion.getClass();
        q0 q0Var3 = jn.b;
        k.g(q0Var3, "type");
        m mVar15 = new m("ref", q0Var3, (String) null, rVar, no.a.s(ap.O, new u0(new t("ref"))), r9);
        dq.Companion.getClass();
        a = l.r(new m[]{mVar11, mVar12, mVar13, mVar14, mVar15, new m("owner", l0.b(dq.a), (String) null, rVar, rVar, r11), new m("isInOrganization", l0.b(xVar5), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
