package nz;

import aa.a0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import aa.x0;
import java.util.List;
import k71.k;
import m10.a00;
import m10.a4;
import m10.ah;
import m10.b00;
import m10.b4;
import m10.bc0;
import m10.bh;
import m10.cc0;
import m10.ch;
import m10.dh;
import m10.eh;
import m10.fh;
import m10.fr;
import m10.gh;
import m10.gr;
import m10.h30;
import m10.h4;
import m10.i30;
import m10.iq;
import m10.jq;
import m10.k40;
import m10.l40;
import m10.lr;
import m10.mr;
import m10.nd;
import m10.oq;
import m10.pq;
import m10.qf0;
import m10.qq;
import m10.ra;
import m10.rf0;
import m10.rq;
import m10.sa;
import m10.t3;
import m10.tg0;
import m10.tq;
import m10.uq;
import m10.vg;
import m10.vq;
import m10.wg;
import m10.wi;
import m10.wq;
import m10.xa0;
import m10.xi;
import m10.xq;
import m10.ya0;
import m10.yd;
import m10.yi;
import m10.yq;
import m10.zd;
import m10.zg;
import rx.j;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        wg.Companion.getClass();
        r b = l0.b(vg.a());
        x61.rShadow rVar = x61.rShadow.r;
        m mVar = new m("hasNextPage", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        x a2 = dh.a();
        k.g(a2, "type");
        List o = d0Shadow.o(mVar, new m("endCursor", a2, (String) null, rVar, rVar, rVar));
        s mVar2 = new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o2 = d0Shadow.o("Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User");
        List a3 = fq.b.a();
        s c = no.a.c(a3, "selections", "Actor", o2, a3);
        s mVar3 = new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        ah.Companion.getClass();
        List o3 = d0Shadow.o(mVar2, c, mVar3, new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        s mVar4 = new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o4 = d0Shadow.o("Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile");
        List a4 = wx.a.a();
        s c2 = no.a.c(a4, "selections", "Node", o4, a4);
        ya0.Companion.getClass();
        a0 a5 = xa0.a();
        k.g(a5, "type");
        List o5 = d0Shadow.o(mVar4, c2, new m("viewerSubscription", a5, (String) null, rVar, rVar, rVar));
        List o6 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        m mVar5 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        List o7 = d0Shadow.o(mVar5, new m("owner", l0.b(k40.a()), (String) null, rVar, rVar, o6), new m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        m mVar6 = new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        x a6 = dh.a();
        k.g(a6, "type");
        List o8 = d0Shadow.o(mVar6, new m("name", a6, "userName", rVar, rVar, rVar), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        List o9 = d0Shadow.o(new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        gr.Companion.getClass();
        List o11 = d0Shadow.o(new m("organization", l0.b(fr.a()), (String) null, rVar, rVar, o9), new m("slug", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        List o12 = d0Shadow.o(new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        s mVar7 = new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o13 = d0Shadow.o("Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile");
        List a7 = wx.a.a();
        List o14 = d0Shadow.o(mVar7, no.a.c(a7, "selections", "Node", o13, a7), new n("Subscribable", d0Shadow.o("Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team"), o5), new n("Repository", d0Shadow.n("Repository"), o7), new n("User", d0Shadow.n("User"), o8), new n("Team", d0Shadow.n("Team"), o11), new n("Organization", d0Shadow.n("Organization"), o12));
        m mVar8 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("abbreviatedOid", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        List o15 = d0Shadow.o(mVar8, mVar9, new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar));
        List o16 = d0Shadow.o(new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        m mVar10 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar11 = new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        a0 a0Var = t3.s;
        k.g(a0Var, "type");
        m mVar12 = new m("conclusion", a0Var, (String) null, rVar, rVar, rVar);
        b4.Companion.getClass();
        List o17 = d0Shadow.o(mVar10, mVar11, mVar12, new m("status", l0.b(a4.a()), (String) null, rVar, rVar, rVar));
        List o18 = d0Shadow.o(new m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        List o19 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        m mVar13 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        m mVar15 = new m("runNumber", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        tg0.Companion.getClass();
        m mVar16 = new m("workflow", l0.b(tg0.e), (String) null, rVar, rVar, o18);
        h4.Companion.getClass();
        List o21 = d0Shadow.o(mVar13, mVar14, mVar15, mVar16, new m("checkSuite", l0.b(h4.f), (String) null, rVar, rVar, o19));
        List o22 = d0Shadow.o(new m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(k40.a()), (String) null, rVar, rVar, d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(bc0.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        m mVar17 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        m mVar19 = new m("number", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        wi.Companion.getClass();
        m mVar20 = new m("state", l0.b(wi.s), "issueState", rVar, rVar, rVar);
        i30.Companion.getClass();
        m mVar21 = new m("repository", l0.b(h30.a()), (String) null, rVar, rVar, o22);
        yi.Companion.getClass();
        a0 a8 = xi.a();
        k.g(a8, "type");
        List o23 = d0Shadow.o(mVar17, mVar18, mVar19, mVar20, mVar21, new m("stateReason", a8, (String) null, rVar, rVar, rVar), new m("titleHTML", l0.b(dh.a()), "titleHTMLString", rVar, rVar, rVar));
        List o24 = d0Shadow.o(new m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(k40.a()), (String) null, rVar, rVar, d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(bc0.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        m mVar22 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("isDraft", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("number", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        b00.Companion.getClass();
        m mVar26 = new m("state", l0.b(a00.a()), "pullRequestState", rVar, rVar, rVar);
        m mVar27 = new m("repository", l0.b(h30.a()), (String) null, rVar, rVar, o24);
        m mVar28 = new m("isInMergeQueue", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        gh.Companion.getClass();
        List o25 = d0Shadow.o(mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, new m("titleHTML", l0.b(fh.a()), (String) null, rVar, rVar, rVar));
        List o26 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("tagName", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar), new m("repository", l0.b(h30.a()), (String) null, rVar, rVar, d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(k40.a()), (String) null, rVar, rVar, d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(bc0.a()), (String) null, rVar, rVar, rVar))), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar))));
        List o27 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(bc0.a()), (String) null, rVar, rVar, rVar));
        List o28 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(bc0.a()), (String) null, rVar, rVar, rVar));
        List o29 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar));
        List o31 = d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        List o32 = d0Shadow.o(new m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(k40.a()), (String) null, rVar, rVar, d0Shadow.o(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(bc0.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        m mVar29 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        m mVar31 = new m("number", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        zd.Companion.getClass();
        a0 a9 = yd.a();
        k.g(a9, "type");
        m mVar32 = new m("stateReason", a9, "discussionStateReason", rVar, rVar, rVar);
        nd.Companion.getClass();
        q0 q0Var = nd.c;
        k.g(q0Var, "type");
        List o33 = d0Shadow.o(mVar29, mVar30, mVar31, mVar32, new m("answer", q0Var, (String) null, rVar, rVar, o31), new m("repository", l0.b(h30.a()), (String) null, rVar, rVar, o32));
        m mVar33 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        x a11 = bc0.a();
        k.g(a11, "type");
        List o34 = d0Shadow.o(mVar33, new m("notificationsPermalink", a11, (String) null, rVar, rVar, rVar));
        m mVar34 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        x a12 = bc0.a();
        k.g(a12, "type");
        List o35 = d0Shadow.o(mVar34, new m("notificationsPermalink", a12, (String) null, rVar, rVar, rVar));
        List n = d0Shadow.n(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        List n2 = d0Shadow.n(new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        s mVar35 = new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o36 = d0Shadow.o("Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile");
        List a13 = wx.a.a();
        List o37 = d0Shadow.o(mVar35, no.a.c(a13, "selections", "Node", o36, a13), new n("Commit", d0Shadow.n("Commit"), o15), new n("Gist", d0Shadow.n("Gist"), o16), new n("CheckSuite", d0Shadow.n("CheckSuite"), o17), new n("WorkflowRun", d0Shadow.n("WorkflowRun"), o21), new n("Issue", d0Shadow.n("Issue"), o23), new n("PullRequest", d0Shadow.n("PullRequest"), o25), new n("Release", d0Shadow.n("Release"), o26), new n("RepositoryInvitation", d0Shadow.n("RepositoryInvitation"), o27), new n("RepositoryVulnerabilityAlert", d0Shadow.n("RepositoryVulnerabilityAlert"), o28), new n("RepositoryAdvisory", d0Shadow.n("RepositoryAdvisory"), o29), new n("Discussion", d0Shadow.n("Discussion"), o33), new n("RepositoryDependabotAlertsThread", d0Shadow.n("RepositoryDependabotAlertsThread"), o34), new n("SecurityAdvisory", d0Shadow.n("SecurityAdvisory"), o35), new n("MemberFeatureRequestNotification", d0Shadow.n("MemberFeatureRequestNotification"), n), new n("ProjectV2", d0Shadow.n("ProjectV2"), n2));
        m mVar36 = new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        m mVar37 = new m("threadType", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        m mVar38 = new m("title", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        m mVar39 = new m("isUnread", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        m mVar40 = new m("unreadItemsCount", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        m mVar41 = new m("lastUpdatedAt", l0.b(ra.a()), (String) null, rVar, rVar, rVar);
        uq.Companion.getClass();
        m mVar42 = new m("subscriptionStatus", l0.b(tq.a()), (String) null, rVar, rVar, rVar);
        rf0.Companion.getClass();
        q0 q0Var2 = rf0.g0;
        k.g(q0Var2, "type");
        m mVar43 = new m("summaryItemAuthor", q0Var2, (String) null, rVar, rVar, o3);
        x a14 = dh.a();
        k.g(a14, "type");
        m mVar44 = new m("summaryItemBody", a14, (String) null, rVar, rVar, rVar);
        m mVar45 = new m("isArchived", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        m mVar46 = new m("isSaved", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        m mVar47 = new m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        wq.Companion.getClass();
        x0 a15 = vq.a();
        k.g(a15, "type");
        m mVar48 = new m("optionalList", a15, (String) null, rVar, rVar, o14);
        jq.Companion.getClass();
        a0 a16 = iq.a();
        k.g(a16, "type");
        m mVar49 = new m("reason", a16, (String) null, rVar, rVar, rVar);
        yq.Companion.getClass();
        x0 a17 = xq.a();
        k.g(a17, "type");
        List o38 = d0Shadow.o(mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, mVar48, mVar49, new m("optionalSubject", a17, (String) null, rVar, rVar, o37), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        mr.Companion.getClass();
        m mVar50 = new m("pageInfo", l0.b(lr.a()), (String) null, rVar, rVar, o);
        pq.Companion.getClass();
        List o39 = d0Shadow.o(mVar50, new m("nodes", l0.a(oq.a()), (String) null, rVar, rVar, o38));
        s mVar51 = new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("User");
        List a18 = j.a();
        s c3 = no.a.c(a18, "selections", "User", n3, a18);
        rq.Companion.getClass();
        r b2 = l0.b(qq.a());
        qf0.a();
        aa.k kVar = new aa.k(rf0.u, new u0(new t("after")));
        qf0.b();
        aa.k kVar2 = new aa.k(rf0.v, new u0(new t("filterBy")));
        qf0.c();
        aa.k kVar3 = new aa.k(rf0.w, new u0(new t("first")));
        qf0.d();
        a = d0Shadow.o(new m("viewer", l0.b(q0Var2), (String) null, rVar, rVar, d0Shadow.o(mVar51, c3, new m("notificationThreads", b2, (String) null, rVar, d0Shadow.o(kVar, kVar2, kVar3, new aa.k(rf0.x, new u0(new t("query")))), o39), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
    }
}
