package j91;

import c21.h0;

/* loaded from: /home/user/work/p/classes5.dex */
public abstract class a {
    public static final h0 a = new h0("MARKDOWN_FILE");
    public static final h0 b = new h0("UNORDERED_LIST");
    public static final h0 c = new h0("ORDERED_LIST");
    public static final h0 d = new h0("LIST_ITEM");
    public static final h0 e = new h0("BLOCK_QUOTE");
    public static final h0 f = new h0("CODE_FENCE");
    public static final h0 g = new h0("CODE_BLOCK");
    public static final h0 h = new h0("CODE_SPAN");
    public static final h0 i = new h0("HTML_BLOCK");
    public static final h0 j = new h0(1, "PARAGRAPH", true);
    public static final h0 k = new h0("EMPH");
    public static final h0 l = new h0("STRONG");
    public static final h0 m = new h0("LINK_DEFINITION");
    public static final h0 n = new h0(1, "LINK_LABEL", true);
    public static final h0 o = new h0(1, "LINK_DESTINATION", true);
    public static final h0 p = new h0(1, "LINK_TITLE", true);
    public static final h0 q = new h0(1, "LINK_TEXT", true);
    public static final h0 r = new h0("INLINE_LINK");
    public static final h0 s = new h0("FULL_REFERENCE_LINK");
    public static final h0 t = new h0("SHORT_REFERENCE_LINK");
    public static final h0 u = new h0("IMAGE");
    public static final h0 v = new h0("AUTOLINK");
    public static final h0 w = new h0("SETEXT_1");
    public static final h0 x = new h0("SETEXT_2");
    public static final h0 y = new h0("ATX_1");
    public static final h0 z = new h0("ATX_2");
    public static final h0 A = new h0("ATX_3");
    public static final h0 B = new h0("ATX_4");
    public static final h0 C = new h0("ATX_5");
    public static final h0 D = new h0("ATX_6");
    public static final h0 E = new h0(1, "TEXT", true);
    public static final h0 F = new h0(1, "CODE_LINE", true);
    public static final h0 G = new h0(1, "BLOCK_QUOTE", true);
    public static final h0 H = new h0(1, "HTML_BLOCK_CONTENT", true);
    public static final h0 I = new h0(1, "'", true);
    public static final h0 J = new h0(1, "\"", true);
    public static final h0 K = new h0(1, "(", true);
    public static final h0 L = new h0(1, ")", true);
    public static final h0 M = new h0(1, "[", true);
    public static final h0 N = new h0(1, "]", true);
    public static final h0 O = new h0(1, "<", true);
    public static final h0 P = new h0(1, ">", true);
    public static final h0 Q = new h0(1, ":", true);
    public static final h0 R = new h0(1, "!", true);
    public static final h0 S = new h0(1, "BR", true);
    public static final h0 T = new h0(1, "EOL", true);
    public static final h0 U = new h0(1, "LINK_ID", true);
    public static final h0 V = new h0(1, "ATX_HEADER", true);
    public static final h0 W = new h0(1, "ATX_CONTENT", true);
    public static final h0 X = new h0(1, "SETEXT_1", true);
    public static final h0 Y = new h0(1, "SETEXT_2", true);
    public static final h0 Z = new h0(1, "SETEXT_CONTENT", true);
    public static final h0 a0 = new h0(1, "EMPH", true);
    public static final h0 b0 = new h0(1, "BACKTICK", true);
    public static final h0 c0 = new h0(1, "ESCAPED_BACKTICKS", true);
    public static final h0 d0 = new h0(1, "LIST_BULLET", true);
    public static final h0 e0 = new h0(1, "URL", true);
    public static final h0 f0 = new h0(1, "HORIZONTAL_RULE", true);
    public static final h0 g0 = new h0(1, "LIST_NUMBER", true);
    public static final h0 h0 = new h0(1, "FENCE_LANG", true);
    public static final h0 i0 = new h0(1, "CODE_FENCE_START", true);
    public static final h0 j0 = new h0(1, "CODE_FENCE_CONTENT", true);
    public static final h0 k0 = new h0(1, "CODE_FENCE_END", true);
    public static final h0 l0 = new h0(1, "LINK_TITLE", true);
    public static final h0 m0 = new h0(1, "AUTOLINK", true);
    public static final h0 n0 = new h0(1, "EMAIL_AUTOLINK", true);
    public static final h0 o0 = new h0(1, "HTML_TAG", true);
    public static final h0 p0 = new h0(1, "BAD_CHARACTER", true);
    public static final b q0 = new b(1, "WHITE_SPACE", true);
}
