package qx0;

import aa.a0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import gw0.j;
import java.util.List;
import k71.k;
import pz0.am;
import pz0.bf;
import pz0.bm;
import pz0.d3;
import pz0.df;
import pz0.e3;
import pz0.e40;
import pz0.f40;
import pz0.fl;
import pz0.g50;
import pz0.gl;
import pz0.gu;
import pz0.h50;
import pz0.hm;
import pz0.ia;
import pz0.ix;
import pz0.ja;
import pz0.jx;
import pz0.k3;
import pz0.ll;
import pz0.ml;
import pz0.my;
import pz0.n7;
import pz0.nl;
import pz0.ny;
import pz0.o7;
import pz0.od;
import pz0.ol;
import pz0.pd;
import pz0.ql;
import pz0.rl;
import pz0.sd;
import pz0.sl;
import pz0.td;
import pz0.tl;
import pz0.ua;
import pz0.ud;
import pz0.ul;
import pz0.v80;
import pz0.va;
import pz0.vd;
import pz0.vl;
import pz0.w80;
import pz0.wd;
import pz0.xd;
import pz0.y2;
import pz0.y90;
import pz0.yd;
import pz0.zd;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class a {
    public static final List a;

    static {
        pd.Companion.getClass();
        r b = l0.b(od.a());
        x61.rShadow rVar = x61.rShadow.r;
        m mVar = new m("hasNextPage", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        x a2 = wd.a();
        k.g(a2, "type");
        List o = d0Shadow.o(new m[]{mVar, new m("endCursor", a2, (String) null, rVar, rVar, rVar)});
        s mVar2 = new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o2 = d0Shadow.o(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.b.a;
        s c = no.a.c(list, "selections", "Actor", o2, list);
        s mVar3 = new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        List o3 = d0Shadow.o(new s[]{mVar2, c, mVar3, new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        s mVar4 = new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o4 = d0Shadow.o(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueType", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List a3 = lw0.a.a();
        s c2 = no.a.c(a3, "selections", "Node", o4, a3);
        f40.Companion.getClass();
        a0 a4 = e40.a();
        k.g(a4, "type");
        List o5 = d0Shadow.o(new s[]{mVar4, c2, new m("viewerSubscription", a4, (String) null, rVar, rVar, rVar)});
        List o6 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        ny.Companion.getClass();
        List o7 = d0Shadow.o(new m[]{mVar5, new m("owner", l0.b(my.a()), (String) null, rVar, rVar, o6), new m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        m mVar6 = new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        x a5 = wd.a();
        k.g(a5, "type");
        List o8 = d0Shadow.o(new m[]{mVar6, new m("name", a5, "userName", rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        List o9 = d0Shadow.o(new m[]{new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        bm.Companion.getClass();
        List o10 = d0Shadow.o(new m[]{new m("organization", l0.b(am.a()), (String) null, rVar, rVar, o9), new m("slug", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        List o12 = d0Shadow.o(new m[]{new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        s mVar7 = new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o13 = d0Shadow.o(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueType", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List a6 = lw0.a.a();
        List o14 = d0Shadow.o(new s[]{mVar7, no.a.c(a6, "selections", "Node", o13, a6), new n("Subscribable", d0Shadow.o(new String[]{"Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team", "TeamDiscussion"}), o5), new n("Repository", d0Shadow.n("Repository"), o7), new n("User", d0Shadow.n("User"), o8), new n("Team", d0Shadow.n("Team"), o10), new n("Organization", d0Shadow.n("Organization"), o12)});
        m mVar8 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("abbreviatedOid", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        List o15 = d0Shadow.o(new m[]{mVar8, mVar9, new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar)});
        List o16 = d0Shadow.o(new m[]{new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        List o17 = d0Shadow.o(new m[]{new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        m mVar10 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar11 = new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        y2.Companion.getClass();
        a0 a0Var = y2.s;
        k.g(a0Var, "type");
        m mVar12 = new m("conclusion", a0Var, (String) null, rVar, rVar, rVar);
        e3.Companion.getClass();
        List o18 = d0Shadow.o(new m[]{mVar10, mVar11, mVar12, new m("status", l0.b(d3.a()), (String) null, rVar, rVar, rVar)});
        List o19 = d0Shadow.o(new m[]{new m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        List o20 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        m mVar13 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        m mVar15 = new m("runNumber", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        y90.Companion.getClass();
        m mVar16 = new m("workflow", l0.b(y90.e), (String) null, rVar, rVar, o19);
        k3.Companion.getClass();
        List o22 = d0Shadow.o(new m[]{mVar13, mVar14, mVar15, mVar16, new m("checkSuite", l0.b(k3.f), (String) null, rVar, rVar, o20)});
        List o23 = d0Shadow.o(new m[]{new m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(my.a()), (String) null, rVar, rVar, d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(g50.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        m mVar17 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        m mVar19 = new m("number", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        bf.Companion.getClass();
        m mVar20 = new m("state", l0.b(bf.s), "issueState", rVar, rVar, rVar);
        jx.Companion.getClass();
        m mVar21 = new m("repository", l0.b(ix.a()), (String) null, rVar, rVar, o23);
        df.Companion.getClass();
        a0 a0Var2 = df.s;
        k.g(a0Var2, "type");
        List o24 = d0Shadow.o(new m[]{mVar17, mVar18, mVar19, mVar20, mVar21, new m("stateReason", a0Var2, (String) null, rVar, rVar, rVar), new m("titleHTML", l0.b(wd.a()), "titleHTMLString", rVar, rVar, rVar)});
        List o25 = d0Shadow.o(new m[]{new m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(my.a()), (String) null, rVar, rVar, d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(g50.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        m mVar22 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("isDraft", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("number", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        gu.Companion.getClass();
        m mVar26 = new m("state", l0.b(gu.s), "pullRequestState", rVar, rVar, rVar);
        m mVar27 = new m("repository", l0.b(ix.a()), (String) null, rVar, rVar, o25);
        m mVar28 = new m("isInMergeQueue", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        zd.Companion.getClass();
        List o26 = d0Shadow.o(new m[]{mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, new m("titleHTML", l0.b(yd.a()), (String) null, rVar, rVar, rVar)});
        List o27 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("tagName", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar), new m("repository", l0.b(ix.a()), (String) null, rVar, rVar, d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(my.a()), (String) null, rVar, rVar, d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(g50.a()), (String) null, rVar, rVar, rVar)})), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)}))});
        List o28 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(g50.a()), (String) null, rVar, rVar, rVar)});
        List o29 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(g50.a()), (String) null, rVar, rVar, rVar)});
        List o30 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar)});
        List o32 = d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        List o33 = d0Shadow.o(new m[]{new m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(my.a()), (String) null, rVar, rVar, d0Shadow.o(new m[]{new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(g50.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        m mVar29 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        m mVar31 = new m("number", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        va.Companion.getClass();
        a0 a7 = ua.a();
        k.g(a7, "type");
        m mVar32 = new m("stateReason", a7, "discussionStateReason", rVar, rVar, rVar);
        ja.Companion.getClass();
        q0 a8 = ia.a();
        k.g(a8, "type");
        List o34 = d0Shadow.o(new m[]{mVar29, mVar30, mVar31, mVar32, new m("answer", a8, (String) null, rVar, rVar, o32), new m("repository", l0.b(ix.a()), (String) null, rVar, rVar, o33)});
        m mVar33 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        x a9 = g50.a();
        k.g(a9, "type");
        List o35 = d0Shadow.o(new m[]{mVar33, new m("notificationsPermalink", a9, (String) null, rVar, rVar, rVar)});
        m mVar34 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        x a10 = g50.a();
        k.g(a10, "type");
        List o36 = d0Shadow.o(new m[]{mVar34, new m("notificationsPermalink", a10, (String) null, rVar, rVar, rVar)});
        List n = d0Shadow.n(new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar));
        List n2 = d0Shadow.n(new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar));
        s mVar35 = new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o37 = d0Shadow.o(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueType", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List a12 = lw0.a.a();
        List o38 = d0Shadow.o(new s[]{mVar35, no.a.c(a12, "selections", "Node", o37, a12), new n("Commit", d0Shadow.n("Commit"), o15), new n("Gist", d0Shadow.n("Gist"), o16), new n("TeamDiscussion", d0Shadow.n("TeamDiscussion"), o17), new n("CheckSuite", d0Shadow.n("CheckSuite"), o18), new n("WorkflowRun", d0Shadow.n("WorkflowRun"), o22), new n("Issue", d0Shadow.n("Issue"), o24), new n("PullRequest", d0Shadow.n("PullRequest"), o26), new n("Release", d0Shadow.n("Release"), o27), new n("RepositoryInvitation", d0Shadow.n("RepositoryInvitation"), o28), new n("RepositoryVulnerabilityAlert", d0Shadow.n("RepositoryVulnerabilityAlert"), o29), new n("RepositoryAdvisory", d0Shadow.n("RepositoryAdvisory"), o30), new n("Discussion", d0Shadow.n("Discussion"), o34), new n("RepositoryDependabotAlertsThread", d0Shadow.n("RepositoryDependabotAlertsThread"), o35), new n("SecurityAdvisory", d0Shadow.n("SecurityAdvisory"), o36), new n("MemberFeatureRequestNotification", d0Shadow.n("MemberFeatureRequestNotification"), n), new n("ProjectV2", d0Shadow.n("ProjectV2"), n2)});
        m mVar36 = new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        m mVar37 = new m("threadType", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        m mVar38 = new m("title", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        m mVar39 = new m("isUnread", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        m mVar40 = new m("unreadItemsCount", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        m mVar41 = new m("lastUpdatedAt", l0.b(n7.a()), (String) null, rVar, rVar, rVar);
        rl.Companion.getClass();
        m mVar42 = new m("subscriptionStatus", l0.b(ql.a()), (String) null, rVar, rVar, rVar);
        w80.Companion.getClass();
        q0 a13 = v80.a();
        k.g(a13, "type");
        m mVar43 = new m("summaryItemAuthor", a13, (String) null, rVar, rVar, o3);
        x a14 = wd.a();
        k.g(a14, "type");
        m mVar44 = new m("summaryItemBody", a14, (String) null, rVar, rVar, rVar);
        m mVar45 = new m("isArchived", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        m mVar46 = new m("isSaved", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        m mVar47 = new m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        tl.Companion.getClass();
        m mVar48 = new m("list", l0.b(sl.a()), (String) null, rVar, rVar, o14);
        gl.Companion.getClass();
        a0 a15 = fl.a();
        k.g(a15, "type");
        m mVar49 = new m("reason", a15, (String) null, rVar, rVar, rVar);
        vl.Companion.getClass();
        List o39 = d0Shadow.o(new m[]{mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, mVar48, mVar49, new m("subject", l0.b(ul.a()), (String) null, rVar, rVar, o38), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        hm.Companion.getClass();
        m mVar50 = new m("pageInfo", l0.b(hm.a), (String) null, rVar, rVar, o);
        ml.Companion.getClass();
        List o40 = d0Shadow.o(new m[]{mVar50, new m("nodes", l0.a(ll.a()), (String) null, rVar, rVar, o39)});
        s mVar51 = new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("User");
        List a16 = j.a();
        s c3 = no.a.c(a16, "selections", "User", n3, a16);
        ol.Companion.getClass();
        r b2 = l0.b(nl.a());
        v80.b();
        aa.k kVar = new aa.k(w80.u, new u0(new t("after")));
        v80.c();
        aa.k kVar2 = new aa.k(w80.v, new u0(new t("filterBy")));
        v80.d();
        aa.k kVar3 = new aa.k(w80.w, new u0(new t("first")));
        v80.e();
        a = d0Shadow.o(new m[]{new m("viewer", l0.b(v80.a()), (String) null, rVar, rVar, d0Shadow.o(new s[]{mVar51, c3, new m("notificationThreads", b2, (String) null, rVar, d0Shadow.o(new aa.k[]{kVar, kVar2, kVar3, new aa.k(w80.xShadow, new u0(new t("query")))}), o40), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
    }
}
