package gv;

import java.time.ZonedDateTime;
import m10.b00;
import m10.jz;
import m10.wm;

/* loaded from: /home/user/work/p/classes3.dex */
public final class g6 implements aa.h0 {
    public jz A;
    public boolean B;
    public y5 C;
    public w4 D;
    public String E;
    public c5 F;
    public String G;
    public k5 H;
    public z5 I;
    public f5 J;
    public e5 K;
    public c6 L;
    public int M;
    public a5 N;
    public d6 O;
    public boolean P;
    public boolean Q;
    public boolean R;
    public boolean S;
    public boolean T;
    public ar.c U;
    public pv.c V;
    public pu.a W;
    public gq.i X;
    public lt.j Y;
    public rt.e Z;
    public String a;
    public mx.a a0;
    public String b;
    public f8 b0;
    public String c;
    public b c0;
    public String d;
    public d5 e;
    public x4 f;
    public String g;
    public String h;
    public ZonedDateTime i;
    public boolean j;
    public boolean k;
    public boolean l;
    public boolean m;
    public v4 n;
    public Boolean o;
    public String p;
    public int q;
    public b00 r;
    public int s;
    public int t;
    public int u;
    public wm v;
    public j5 w;
    public g5 x;
    public h5 y;
    public i5 z;

    public g6(String str, String str2, String str3, String str4, d5 d5Var, x4 x4Var, String str5, String str6, ZonedDateTime zonedDateTime, boolean z, boolean z2, boolean z3, boolean z4, v4 v4Var, Boolean bool, String str7, int i, b00 b00Var, int i2, int i3, int i4, wm wmVar, j5 j5Var, g5 g5Var, h5 h5Var, i5 i5Var, jz jzVar, boolean z5, y5 y5Var, w4 w4Var, String str8, c5 c5Var, String str9, k5 k5Var, z5 z5Var, f5 f5Var, e5 e5Var, c6 c6Var, int i5, a5 a5Var, d6 d6Var, boolean z6, boolean z7, boolean z8, boolean z9, boolean z11, ar.c cVar, pv.c cVar2, pu.a aVar, gq.i iVar, lt.j jVar, rt.e eVar, mx.a aVar2, f8 f8Var, b bVar) {
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = str4;
        this.e = d5Var;
        this.f = x4Var;
        this.g = str5;
        this.h = str6;
        this.i = zonedDateTime;
        this.j = z;
        this.k = z2;
        this.l = z3;
        this.m = z4;
        this.n = v4Var;
        this.o = bool;
        this.p = str7;
        this.q = i;
        this.r = b00Var;
        this.s = i2;
        this.t = i3;
        this.u = i4;
        this.v = wmVar;
        this.w = j5Var;
        this.x = g5Var;
        this.y = h5Var;
        this.z = i5Var;
        this.A = jzVar;
        this.B = z5;
        this.C = y5Var;
        this.D = w4Var;
        this.E = str8;
        this.F = c5Var;
        this.G = str9;
        this.H = k5Var;
        this.I = z5Var;
        this.J = f5Var;
        this.K = e5Var;
        this.L = c6Var;
        this.M = i5;
        this.N = a5Var;
        this.O = d6Var;
        this.P = z6;
        this.Q = z7;
        this.R = z8;
        this.S = z9;
        this.T = z11;
        this.U = cVar;
        this.V = cVar2;
        this.W = aVar;
        this.X = iVar;
        this.Y = jVar;
        this.Z = eVar;
        this.a0 = aVar2;
        this.b0 = f8Var;
        this.c0 = bVar;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof g6)) {
            return false;
        }
        g6 g6Var = (g6) obj;
        return k71.k.b(this.a, g6Var.a) && k71.k.b(this.b, g6Var.b) && k71.k.b(this.c, g6Var.c) && k71.k.b(this.d, g6Var.d) && k71.k.b(this.e, g6Var.e) && k71.k.b(this.f, g6Var.f) && k71.k.b(this.g, g6Var.g) && k71.k.b(this.h, g6Var.h) && k71.k.b(this.i, g6Var.i) && this.j == g6Var.j && this.k == g6Var.k && this.l == g6Var.l && this.m == g6Var.m && k71.k.b(this.n, g6Var.n) && k71.k.b(this.o, g6Var.o) && k71.k.b(this.p, g6Var.p) && this.q == g6Var.q && this.r == g6Var.r && this.s == g6Var.s && this.t == g6Var.t && this.u == g6Var.u && this.v == g6Var.v && k71.k.b(this.w, g6Var.w) && k71.k.b(this.x, g6Var.x) && k71.k.b(this.y, g6Var.y) && k71.k.b(this.z, g6Var.z) && this.A == g6Var.A && this.B == g6Var.B && k71.k.b(this.C, g6Var.C) && k71.k.b(this.D, g6Var.D) && k71.k.b(this.E, g6Var.E) && k71.k.b(this.F, g6Var.F) && k71.k.b(this.G, g6Var.G) && k71.k.b(this.H, g6Var.H) && k71.k.b(this.I, g6Var.I) && k71.k.b(this.J, g6Var.J) && k71.k.b(this.K, g6Var.K) && k71.k.b(this.L, g6Var.L) && this.M == g6Var.M && k71.k.b(this.N, g6Var.N) && k71.k.b(this.O, g6Var.O) && this.P == g6Var.P && this.Q == g6Var.Q && this.R == g6Var.R && this.S == g6Var.S && this.T == g6Var.T && k71.k.b(this.U, g6Var.U) && k71.k.b(this.V, g6Var.V) && k71.k.b(this.W, g6Var.W) && k71.k.b(this.X, g6Var.X) && k71.k.b(this.Y, g6Var.Y) && k71.k.b(this.Z, g6Var.Z) && k71.k.b(this.a0, g6Var.a0) && k71.k.b(this.b0, g6Var.b0) && k71.k.b(this.c0, g6Var.c0);
    }

    public final int hashCode() {
        int i = com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(this.a.hashCode() * 31, this.b, 31), this.c, 31), this.d, 31);
        d5 d5Var = this.e;
        int hashCode = (i + (d5Var == null ? 0 : d5Var.hashCode())) * 31;
        x4 x4Var = this.f;
        int e = x.i.e(x.i.e(x.i.e(x.i.e(com.github.rudroid.m0.a(this.i, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i((hashCode + (x4Var == null ? 0 : x4Var.hashCode())) * 31, this.g, 31), this.h, 31), 31), 31, this.j), 31, this.k), 31, this.l), 31, this.m);
        v4 v4Var = this.n;
        int hashCode2 = (e + (v4Var == null ? 0 : v4Var.hashCode())) * 31;
        Boolean bool = this.o;
        int hashCode3 = (this.v.hashCode() + a0.s0.b(this.u, a0.s0.b(this.t, a0.s0.b(this.s, (this.r.hashCode() + a0.s0.b(this.q, com.github.rudroid.copilot.h1.i((hashCode2 + (bool == null ? 0 : bool.hashCode())) * 31, this.p, 31), 31)) * 31, 31), 31), 31)) * 31;
        j5 j5Var = this.w;
        int hashCode4 = (hashCode3 + (j5Var == null ? 0 : j5Var.hashCode())) * 31;
        g5 g5Var = this.x;
        int hashCode5 = (hashCode4 + (g5Var == null ? 0 : g5Var.hashCode())) * 31;
        h5 h5Var = this.y;
        int hashCode6 = (hashCode5 + (h5Var == null ? 0 : h5Var.hashCode())) * 31;
        i5 i5Var = this.z;
        int hashCode7 = (hashCode6 + (i5Var == null ? 0 : i5Var.hashCode())) * 31;
        jz jzVar = this.A;
        int hashCode8 = (this.C.hashCode() + x.i.e((hashCode7 + (jzVar == null ? 0 : jzVar.hashCode())) * 31, 31, this.B)) * 31;
        w4 w4Var = this.D;
        int i2 = com.github.rudroid.copilot.h1.i((hashCode8 + (w4Var == null ? 0 : w4Var.hashCode())) * 31, this.E, 31);
        c5 c5Var = this.F;
        int i3 = com.github.rudroid.copilot.h1.i((i2 + (c5Var == null ? 0 : c5Var.hashCode())) * 31, this.G, 31);
        k5 k5Var = this.H;
        int hashCode9 = (i3 + (k5Var == null ? 0 : k5Var.hashCode())) * 31;
        z5 z5Var = this.I;
        int hashCode10 = (hashCode9 + (z5Var == null ? 0 : z5Var.hashCode())) * 31;
        f5 f5Var = this.J;
        int hashCode11 = (hashCode10 + (f5Var == null ? 0 : f5Var.hashCode())) * 31;
        e5 e5Var = this.K;
        int hashCode12 = (this.N.hashCode() + a0.s0.b(this.M, (this.L.hashCode() + ((hashCode11 + (e5Var == null ? 0 : e5Var.hashCode())) * 31)) * 31, 31)) * 31;
        d6 d6Var = this.O;
        return this.c0.hashCode() + ((this.b0.hashCode() + ((this.a0.hashCode() + ((this.Z.hashCode() + ((this.Y.hashCode() + ((this.X.hashCode() + ((this.W.hashCode() + ((this.V.hashCode() + ((this.U.hashCode() + x.i.e(x.i.e(x.i.e(x.i.e(x.i.e((hashCode12 + (d6Var != null ? d6Var.hashCode() : 0)) * 31, 31, this.P), 31, this.Q), 31, this.R), 31, this.S), 31, this.T)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder o = a0.s0.o("RepositoryNodeFragmentPullRequest(__typename=", this.a, ", url=", this.b, ", id=");
        f1.e.x(o, this.c, ", headRefOid=", this.d, ", headRepository=");
        o.append(this.e);
        o.append(", baseRepository=");
        o.append(this.f);
        o.append(", title=");
        f1.e.x(o, this.g, ", titleHTML=", this.h, ", createdAt=");
        com.github.rudroid.m0.v(", viewerCanDeleteHeadRef=", ", viewerDidAuthor=", o, this.i, this.j);
        com.github.rudroid.m0.A(o, this.k, ", viewerCanChangeBaseBranch=", this.l, ", locked=");
        o.append(this.m);
        o.append(", author=");
        o.append(this.n);
        o.append(", isReadByViewer=");
        o.append(this.o);
        o.append(", bodyHtml=");
        o.append(this.p);
        o.append(", number=");
        o.append(this.q);
        o.append(", pullRequestState=");
        o.append(this.r);
        o.append(", changedFiles=");
        a0.s0.z(o, this.s, ", additions=", this.t, ", deletions=");
        o.append(this.u);
        o.append(", mergeStateStatus=");
        o.append(this.v);
        o.append(", mergedBy=");
        o.append(this.w);
        o.append(", mergeCommit=");
        o.append(this.x);
        o.append(", mergeQueue=");
        o.append(this.y);
        o.append(", mergeQueueEntry=");
        o.append(this.z);
        o.append(", reviewDecision=");
        o.append(this.A);
        o.append(", isDraft=");
        o.append(this.B);
        o.append(", requiredStatusChecks=");
        o.append(this.C);
        o.append(", baseRef=");
        o.append(this.D);
        o.append(", baseRefName=");
        o.append(this.E);
        o.append(", headRef=");
        o.append(this.F);
        o.append(", headRefName=");
        o.append(this.G);
        o.append(", milestone=");
        o.append(this.H);
        o.append(", reviewRequests=");
        o.append(this.I);
        o.append(", latestReviews=");
        o.append(this.J);
        o.append(", latestOpinionatedReviews=");
        o.append(this.K);
        o.append(", suggestedReviewerActors=");
        o.append(this.L);
        o.append(", actionRequiredWorkflowRunCount=");
        o.append(this.M);
        o.append(", commits=");
        o.append(this.N);
        o.append(", viewerLatestReview=");
        o.append(this.O);
        o.append(", viewerCanReopen=");
        o.append(this.P);
        o.append(", viewerCanMergeAsAdmin=");
        com.github.rudroid.m0.A(o, this.Q, ", viewerCanAssign=", this.R, ", viewerCanLabel=");
        com.github.rudroid.m0.A(o, this.S, ", viewerCanUpdateBranch=", this.T, ", commentFragment=");
        o.append(this.U);
        o.append(", reactionFragment=");
        o.append(this.V);
        o.append(", orgBlockableFragment=");
        o.append(this.W);
        o.append(", assigneeFragment=");
        o.append(this.X);
        o.append(", labelsFragment=");
        o.append(this.Y);
        o.append(", linkedIssues=");
        o.append(this.Z);
        o.append(", updatableFields=");
        o.append(this.a0);
        o.append(", viewerLatestReviewRequestFragment=");
        o.append(this.b0);
        o.append(", autoMergeRequestFragment=");
        o.append(this.c0);
        o.append(")");
        return o.toString();
    }
}
