package gn0;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class rh {
    public static final rh A;
    public static final rh A0;
    public static final rh B;
    public static final rh B0;
    public static final rh C;
    public static final rh C0;
    public static final qh Companion;
    public static final rh D;
    public static final rh D0;
    public static final rh E;
    public static final rh E0;
    public static final rh F;
    public static final rh F0;
    public static final rh G;
    public static final rh G0;
    public static final rh H;
    public static final rh H0;
    public static final rh I;
    public static final rh I0;
    public static final rh J;
    public static final rh J0;
    public static final rh K;
    public static final rh K0;
    public static final rh L;
    public static final rh L0;
    public static final rh M;
    public static final rh M0;
    public static final rh N;
    public static final rh N0;
    public static final rh O;
    public static final rh O0;
    public static final rh P;
    public static final /* synthetic */ rh[] P0;
    public static final rh Q;
    public static final /* synthetic */ d71.b Q0;
    public static final rh R;
    public static final rh S;
    public static final rh T;
    public static final rh U;
    public static final rh V;
    public static final rh W;
    public static final rh X;
    public static final rh Y;
    public static final rh Z;
    public static final rh a0;
    public static final rh b0;
    public static final rh c0;
    public static final rh d0;
    public static final rh e0;
    public static final rh f0;
    public static final rh g0;
    public static final rh h0;
    public static final rh i0;
    public static final rh j0;
    public static final rh k0;
    public static final rh l0;
    public static final rh m0;
    public static final rh n0;
    public static final rh o0;
    public static final rh p0;
    public static final rh q0;
    public static final rh r0;
    public static final rh s;
    public static final rh s0;
    public static final rh t;
    public static final rh t0;
    public static final rh u;
    public static final rh u0;
    public static final rh v;
    public static final rh v0;
    public static final rh w;
    public static final rh w0;
    public static final rh x;
    public static final rh x0;
    public static final rh y;
    public static final rh y0;
    public static final rh z;
    public static final rh z0;
    public String r;

    static {
        rh rhVar = new rh("CHECK_SUITE", 0, "CHECK_SUITE");
        s = rhVar;
        rh rhVar2 = new rh("CODE", 1, "CODE");
        t = rhVar2;
        rh rhVar3 = new rh("COMMIT", 2, "COMMIT");
        u = rhVar3;
        rh rhVar4 = new rh("COMMITS", 3, "COMMITS");
        v = rhVar4;
        rh rhVar5 = new rh("DEEP_LINK", 4, "DEEP_LINK");
        w = rhVar5;
        rh rhVar6 = new rh("DEPLOYMENT_REVIEW", 5, "DEPLOYMENT_REVIEW");
        x = rhVar6;
        rh rhVar7 = new rh("DISCUSSION", 6, "DISCUSSION");
        y = rhVar7;
        rh rhVar8 = new rh("DISCUSSIONS", 7, "DISCUSSIONS");
        z = rhVar8;
        rh rhVar9 = new rh("DRAFT_ISSUE", 8, "DRAFT_ISSUE");
        A = rhVar9;
        rh rhVar10 = new rh("FILTER_ASSIGNEE", 9, "FILTER_ASSIGNEE");
        B = rhVar10;
        rh rhVar11 = new rh("FILTER_AUTHOR", 10, "FILTER_AUTHOR");
        C = rhVar11;
        rh rhVar12 = new rh("FILTER_DISCUSSION_CATEGORY", 11, "FILTER_DISCUSSION_CATEGORY");
        D = rhVar12;
        rh rhVar13 = new rh("FILTER_DISCUSSION_IS_UNANSWERED", 12, "FILTER_DISCUSSION_IS_UNANSWERED");
        E = rhVar13;
        rh rhVar14 = new rh("FILTER_DISCUSSION_TOP", 13, "FILTER_DISCUSSION_TOP");
        F = rhVar14;
        rh rhVar15 = new rh("FILTER_DISCUSSION_VIEWER", 14, "FILTER_DISCUSSION_VIEWER");
        G = rhVar15;
        rh rhVar16 = new rh("FILTER_ISSUE_STATUS", 15, "FILTER_ISSUE_STATUS");
        H = rhVar16;
        rh rhVar17 = new rh("FILTER_ISSUE_VIEWER", 16, "FILTER_ISSUE_VIEWER");
        I = rhVar17;
        rh rhVar18 = new rh("FILTER_LABEL", 17, "FILTER_LABEL");
        J = rhVar18;
        rh rhVar19 = new rh("FILTER_LANGUAGE", 18, "FILTER_LANGUAGE");
        K = rhVar19;
        rh rhVar20 = new rh("FILTER_MILESTONE", 19, "FILTER_MILESTONE");
        L = rhVar20;
        rh rhVar21 = new rh("FILTER_NOTIFICATION_FILTER", 20, "FILTER_NOTIFICATION_FILTER");
        M = rhVar21;
        rh rhVar22 = new rh("FILTER_NOTIFICATION_IS_UNREAD", 21, "FILTER_NOTIFICATION_IS_UNREAD");
        N = rhVar22;
        rh rhVar23 = new rh("FILTER_NOTIFICATION_STATUS", 22, "FILTER_NOTIFICATION_STATUS");
        O = rhVar23;
        rh rhVar24 = new rh("FILTER_ORGANIZATION", 23, "FILTER_ORGANIZATION");
        P = rhVar24;
        rh rhVar25 = new rh("FILTER_PROJECT", 24, "FILTER_PROJECT");
        Q = rhVar25;
        rh rhVar26 = new rh("FILTER_PULL_REQUEST_REVIEW_STATUS", 25, "FILTER_PULL_REQUEST_REVIEW_STATUS");
        R = rhVar26;
        rh rhVar27 = new rh("FILTER_PULL_REQUEST_STATUS", 26, "FILTER_PULL_REQUEST_STATUS");
        S = rhVar27;
        rh rhVar28 = new rh("FILTER_PULL_REQUEST_VIEWER", 27, "FILTER_PULL_REQUEST_VIEWER");
        T = rhVar28;
        rh rhVar29 = new rh("FILTER_REPOSITORY", 28, "FILTER_REPOSITORY");
        U = rhVar29;
        rh rhVar30 = new rh("FILTER_REPOSITORY_TYPE", 29, "FILTER_REPOSITORY_TYPE");
        V = rhVar30;
        rh rhVar31 = new rh("FILTER_REPOSITORY_VISIBILITY", 30, "FILTER_REPOSITORY_VISIBILITY");
        W = rhVar31;
        rh rhVar32 = new rh("FILTER_SORT", 31, "FILTER_SORT");
        X = rhVar32;
        rh rhVar33 = new rh("FILTER_TRENDING_DATE_RANGE", 32, "FILTER_TRENDING_DATE_RANGE");
        Y = rhVar33;
        rh rhVar34 = new rh("FILTER_TRENDING_LANGUAGE", 33, "FILTER_TRENDING_LANGUAGE");
        Z = rhVar34;
        rh rhVar35 = new rh("FILTER_TRENDING_SPOKEN_LANGUAGE", 34, "FILTER_TRENDING_SPOKEN_LANGUAGE");
        a0 = rhVar35;
        rh rhVar36 = new rh("GIST", 35, "GIST");
        b0 = rhVar36;
        rh rhVar37 = new rh("GLOBAL_SEARCH", 36, "GLOBAL_SEARCH");
        c0 = rhVar37;
        rh rhVar38 = new rh("HOME", 37, "HOME");
        d0 = rhVar38;
        rh rhVar39 = new rh("ISSUE", 38, "ISSUE");
        e0 = rhVar39;
        rh rhVar40 = new rh("ISSUES", 39, "ISSUES");
        f0 = rhVar40;
        rh rhVar41 = new rh("JUMP_TO", 40, "JUMP_TO");
        g0 = rhVar41;
        rh rhVar42 = new rh("NAVIGATION_BAR", 41, "NAVIGATION_BAR");
        h0 = rhVar42;
        rh rhVar43 = new rh("NOTIFICATIONS", 42, "NOTIFICATIONS");
        i0 = rhVar43;
        rh rhVar44 = new rh("ORGANIZATION", 43, "ORGANIZATION");
        j0 = rhVar44;
        rh rhVar45 = new rh("ORGANIZATIONS", 44, "ORGANIZATIONS");
        k0 = rhVar45;
        rh rhVar46 = new rh("PROJECT", 45, "PROJECT");
        l0 = rhVar46;
        rh rhVar47 = new rh("PROJECTS", 46, "PROJECTS");
        m0 = rhVar47;
        rh rhVar48 = new rh("PULL_REQUEST", 47, "PULL_REQUEST");
        n0 = rhVar48;
        rh rhVar49 = new rh("PULL_REQUESTS", 48, "PULL_REQUESTS");
        o0 = rhVar49;
        rh rhVar50 = new rh("PUSH_NOTIFICATIONS", 49, "PUSH_NOTIFICATIONS");
        p0 = rhVar50;
        rh rhVar51 = new rh("PUSH_NOTIFICATION_ACTION", 50, "PUSH_NOTIFICATION_ACTION");
        q0 = rhVar51;
        rh rhVar52 = new rh("PUSH_NOTIFICATION_ASSIGN", 51, "PUSH_NOTIFICATION_ASSIGN");
        r0 = rhVar52;
        rh rhVar53 = new rh("PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", 52, "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL");
        s0 = rhVar53;
        rh rhVar54 = new rh("PUSH_NOTIFICATION_MENTION", 53, "PUSH_NOTIFICATION_MENTION");
        t0 = rhVar54;
        rh rhVar55 = new rh("PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", 54, "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST");
        u0 = rhVar55;
        rh rhVar56 = new rh("PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", 55, "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW");
        v0 = rhVar56;
        rh rhVar57 = new rh("PUSH_NOTIFICATION_RELEASE", 56, "PUSH_NOTIFICATION_RELEASE");
        w0 = rhVar57;
        rh rhVar58 = new rh("PUSH_NOTIFICATION_REVIEW_REQUEST", 57, "PUSH_NOTIFICATION_REVIEW_REQUEST");
        x0 = rhVar58;
        rh rhVar59 = new rh("RELEASE", 58, "RELEASE");
        y0 = rhVar59;
        rh rhVar60 = new rh("RELEASES", 59, "RELEASES");
        z0 = rhVar60;
        rh rhVar61 = new rh("REPOSITORIES", 60, "REPOSITORIES");
        A0 = rhVar61;
        rh rhVar62 = new rh("REPOSITORY", 61, "REPOSITORY");
        B0 = rhVar62;
        rh rhVar63 = new rh("REPOSITORY_ADVISORY", 62, "REPOSITORY_ADVISORY");
        C0 = rhVar63;
        rh rhVar64 = new rh("REPOSITORY_DEPENDABOT_THREAD_ALERT", 63, "REPOSITORY_DEPENDABOT_THREAD_ALERT");
        D0 = rhVar64;
        rh rhVar65 = new rh("REPOSITORY_VULNERABILITY_ALERT", 64, "REPOSITORY_VULNERABILITY_ALERT");
        E0 = rhVar65;
        rh rhVar66 = new rh("SECURITY_ADVISORY", 65, "SECURITY_ADVISORY");
        F0 = rhVar66;
        rh rhVar67 = new rh("SETTINGS", 66, "SETTINGS");
        G0 = rhVar67;
        rh rhVar68 = new rh("SHORTCUT", 67, "SHORTCUT");
        H0 = rhVar68;
        rh rhVar69 = new rh("SWIPE_ACTIONS", 68, "SWIPE_ACTIONS");
        I0 = rhVar69;
        rh rhVar70 = new rh("TEAM_DISCUSSION", 69, "TEAM_DISCUSSION");
        J0 = rhVar70;
        rh rhVar71 = new rh("TOAST", 70, "TOAST");
        K0 = rhVar71;
        rh rhVar72 = new rh("USER", 71, "USER");
        L0 = rhVar72;
        rh rhVar73 = new rh("USERS", 72, "USERS");
        M0 = rhVar73;
        rh rhVar74 = new rh("WORKFLOW_RUN", 73, "WORKFLOW_RUN");
        N0 = rhVar74;
        rh rhVar75 = new rh("UNKNOWN__", 74, "UNKNOWN__");
        O0 = rhVar75;
        rh[] rhVarArr = {rhVar, rhVar2, rhVar3, rhVar4, rhVar5, rhVar6, rhVar7, rhVar8, rhVar9, rhVar10, rhVar11, rhVar12, rhVar13, rhVar14, rhVar15, rhVar16, rhVar17, rhVar18, rhVar19, rhVar20, rhVar21, rhVar22, rhVar23, rhVar24, rhVar25, rhVar26, rhVar27, rhVar28, rhVar29, rhVar30, rhVar31, rhVar32, rhVar33, rhVar34, rhVar35, rhVar36, rhVar37, rhVar38, rhVar39, rhVar40, rhVar41, rhVar42, rhVar43, rhVar44, rhVar45, rhVar46, rhVar47, rhVar48, rhVar49, rhVar50, rhVar51, rhVar52, rhVar53, rhVar54, rhVar55, rhVar56, rhVar57, rhVar58, rhVar59, rhVar60, rhVar61, rhVar62, rhVar63, rhVar64, rhVar65, rhVar66, rhVar67, rhVar68, rhVar69, rhVar70, rhVar71, rhVar72, rhVar73, rhVar74, rhVar75};
        P0 = rhVarArr;
        Q0 = v8.l0.t(rhVarArr);
        Companion = new qh();
        sy.d0.o(new String[]{"CHECK_SUITE", "CODE", "COMMIT", "COMMITS", "DEEP_LINK", "DEPLOYMENT_REVIEW", "DISCUSSION", "DISCUSSIONS", "DRAFT_ISSUE", "FILTER_ASSIGNEE", "FILTER_AUTHOR", "FILTER_DISCUSSION_CATEGORY", "FILTER_DISCUSSION_IS_UNANSWERED", "FILTER_DISCUSSION_TOP", "FILTER_DISCUSSION_VIEWER", "FILTER_ISSUE_STATUS", "FILTER_ISSUE_VIEWER", "FILTER_LABEL", "FILTER_LANGUAGE", "FILTER_MILESTONE", "FILTER_NOTIFICATION_FILTER", "FILTER_NOTIFICATION_IS_UNREAD", "FILTER_NOTIFICATION_STATUS", "FILTER_ORGANIZATION", "FILTER_PROJECT", "FILTER_PULL_REQUEST_REVIEW_STATUS", "FILTER_PULL_REQUEST_STATUS", "FILTER_PULL_REQUEST_VIEWER", "FILTER_REPOSITORY", "FILTER_REPOSITORY_TYPE", "FILTER_REPOSITORY_VISIBILITY", "FILTER_SORT", "FILTER_TRENDING_DATE_RANGE", "FILTER_TRENDING_LANGUAGE", "FILTER_TRENDING_SPOKEN_LANGUAGE", "GIST", "GLOBAL_SEARCH", "HOME", "ISSUE", "ISSUES", "JUMP_TO", "NAVIGATION_BAR", "NOTIFICATIONS", "ORGANIZATION", "ORGANIZATIONS", "PROJECT", "PROJECTS", "PULL_REQUEST", "PULL_REQUESTS", "PUSH_NOTIFICATIONS", "PUSH_NOTIFICATION_ACTION", "PUSH_NOTIFICATION_ASSIGN", "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", "PUSH_NOTIFICATION_MENTION", "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", "PUSH_NOTIFICATION_RELEASE", "PUSH_NOTIFICATION_REVIEW_REQUEST", "RELEASE", "RELEASES", "REPOSITORIES", "REPOSITORY", "REPOSITORY_ADVISORY", "REPOSITORY_DEPENDABOT_THREAD_ALERT", "REPOSITORY_VULNERABILITY_ALERT", "SECURITY_ADVISORY", "SETTINGS", "SHORTCUT", "SWIPE_ACTIONS", "TEAM_DISCUSSION", "TOAST", "USER", "USERS", "WORKFLOW_RUN"});
    }

    public rh(String str, int i, String str2) {
        this.r = str2;
    }

    public static rh valueOf(String str) {
        return (rh) Enum.valueOf(rh.class, str);
    }

    public static rh[] values() {
        return (rh[]) P0.clone();
    }
}
