package gn0;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class yg {
    public static final xg Companion;
    public static final yg s;
    public static final /* synthetic */ yg[] t;
    public static final /* synthetic */ d71.b u;
    public String r;

    static {
        yg ygVar = new yg("ACCOUNT_SWITCHER_ADD", 0, "ACCOUNT_SWITCHER_ADD");
        yg ygVar2 = new yg("ACCOUNT_SWITCHER_ITEM", 1, "ACCOUNT_SWITCHER_ITEM");
        yg ygVar3 = new yg("ACCOUNT_SWITCHER_REMOVE", 2, "ACCOUNT_SWITCHER_REMOVE");
        yg ygVar4 = new yg("CODE_SEARCH_LIST_ITEM", 3, "CODE_SEARCH_LIST_ITEM");
        yg ygVar5 = new yg("DEEP_LINK_ERROR_ACCOUNT_SWITCHER", 4, "DEEP_LINK_ERROR_ACCOUNT_SWITCHER");
        yg ygVar6 = new yg("EXPLORE_BOTTOM_NAVIGATION", 5, "EXPLORE_BOTTOM_NAVIGATION");
        yg ygVar7 = new yg("EXPLORE_FEATURED_REPOSITORY", 6, "EXPLORE_FEATURED_REPOSITORY");
        yg ygVar8 = new yg("EXPLORE_FOR_YOU_REPOSITORY", 7, "EXPLORE_FOR_YOU_REPOSITORY");
        yg ygVar9 = new yg("EXPLORE_STAR_FEATURED_REPOSITORY", 8, "EXPLORE_STAR_FEATURED_REPOSITORY");
        yg ygVar10 = new yg("EXPLORE_STAR_FOR_YOU_REPOSITORY", 9, "EXPLORE_STAR_FOR_YOU_REPOSITORY");
        yg ygVar11 = new yg("EXPLORE_STAR_TRENDING_REPOSITORY", 10, "EXPLORE_STAR_TRENDING_REPOSITORY");
        yg ygVar12 = new yg("EXPLORE_TRENDING_LIST_FILTER", 11, "EXPLORE_TRENDING_LIST_FILTER");
        yg ygVar13 = new yg("EXPLORE_TRENDING_REPOSITORY", 12, "EXPLORE_TRENDING_REPOSITORY");
        yg ygVar14 = new yg("FOLLOW", 13, "FOLLOW");
        yg ygVar15 = new yg("GLOBAL_SEARCH_SHORTCUT", 14, "GLOBAL_SEARCH_SHORTCUT");
        yg ygVar16 = new yg("HOME_BOTTOM_NAVIGATION", 15, "HOME_BOTTOM_NAVIGATION");
        yg ygVar17 = new yg("HOME_CREATE_ISSUE", 16, "HOME_CREATE_ISSUE");
        yg ygVar18 = new yg("HOME_DISCUSSIONS", 17, "HOME_DISCUSSIONS");
        yg ygVar19 = new yg("HOME_FAVORITE_REPOSITORY_ITEM", 18, "HOME_FAVORITE_REPOSITORY_ITEM");
        yg ygVar20 = new yg("HOME_IN_APP_UPDATE", 19, "HOME_IN_APP_UPDATE");
        yg ygVar21 = new yg("HOME_ISSUES", 20, "HOME_ISSUES");
        yg ygVar22 = new yg("HOME_ISSUES_LIST_NEW_ISSUE", 21, "HOME_ISSUES_LIST_NEW_ISSUE");
        yg ygVar23 = new yg("HOME_ORGANIZATIONS", 22, "HOME_ORGANIZATIONS");
        yg ygVar24 = new yg("HOME_PROJECTS", 23, "HOME_PROJECTS");
        yg ygVar25 = new yg("HOME_PULL_REQUESTS", 24, "HOME_PULL_REQUESTS");
        yg ygVar26 = new yg("HOME_RECENT_ACTIVITY_ITEM", 25, "HOME_RECENT_ACTIVITY_ITEM");
        yg ygVar27 = new yg("HOME_RELEASE_NOTES", 26, "HOME_RELEASE_NOTES");
        yg ygVar28 = new yg("HOME_REPOSITORIES", 27, "HOME_REPOSITORIES");
        yg ygVar29 = new yg("HOME_REPOSITORY_LIST_FILTER", 28, "HOME_REPOSITORY_LIST_FILTER");
        yg ygVar30 = new yg("HOME_SHORTCUTS", 29, "HOME_SHORTCUTS");
        yg ygVar31 = new yg("HOME_STARRED", 30, "HOME_STARRED");
        yg ygVar32 = new yg("ISSUES_LIST_ITEM", 31, "ISSUES_LIST_ITEM");
        yg ygVar33 = new yg("ISSUES_SEARCH", 32, "ISSUES_SEARCH");
        yg ygVar34 = new yg("ISSUE_COMPOSER", 33, "ISSUE_COMPOSER");
        yg ygVar35 = new yg("ISSUE_COMPOSER_PROPERTY_BAR", 34, "ISSUE_COMPOSER_PROPERTY_BAR");
        yg ygVar36 = new yg("NOTIFICATIONS_ONBOARDING_BANNER", 35, "NOTIFICATIONS_ONBOARDING_BANNER");
        yg ygVar37 = new yg("NOTIFICATION_BOTTOM_NAVIGATION", 36, "NOTIFICATION_BOTTOM_NAVIGATION");
        yg ygVar38 = new yg("NOTIFICATION_FILTER", 37, "NOTIFICATION_FILTER");
        yg ygVar39 = new yg("NOTIFICATION_LIST_FILTER", 38, "NOTIFICATION_LIST_FILTER");
        yg ygVar40 = new yg("NOTIFICATION_LIST_ITEM", 39, "NOTIFICATION_LIST_ITEM");
        yg ygVar41 = new yg("NOTIFICATION_LIST_ITEM_UNDO", 40, "NOTIFICATION_LIST_ITEM_UNDO");
        yg ygVar42 = new yg("NOTIFICATION_PUSH", 41, "NOTIFICATION_PUSH");
        yg ygVar43 = new yg("ONBOARDING_BANNER", 42, "ONBOARDING_BANNER");
        yg ygVar44 = new yg("PROFILE_BOTTOM_NAVIGATION", 43, "PROFILE_BOTTOM_NAVIGATION");
        yg ygVar45 = new yg("PROFILE_HEADER_NAME", 44, "PROFILE_HEADER_NAME");
        yg ygVar46 = new yg("PROFILE_REPOSITORY_LIST_FILTER", 45, "PROFILE_REPOSITORY_LIST_FILTER");
        yg ygVar47 = new yg("PROJECTS_LIST_ITEM", 46, "PROJECTS_LIST_ITEM");
        yg ygVar48 = new yg("PROJECTS_QUICK_ACTION_CLOSE", 47, "PROJECTS_QUICK_ACTION_CLOSE");
        yg ygVar49 = new yg("PROJECTS_QUICK_ACTION_DELETE", 48, "PROJECTS_QUICK_ACTION_DELETE");
        yg ygVar50 = new yg("PROJECTS_QUICK_ACTION_EDIT_FIELD", 49, "PROJECTS_QUICK_ACTION_EDIT_FIELD");
        yg ygVar51 = new yg("PROJECTS_QUICK_ACTION_EDIT_TITLE", 50, "PROJECTS_QUICK_ACTION_EDIT_TITLE");
        yg ygVar52 = new yg("PROJECTS_QUICK_ACTION_OPEN_DETAILS", 51, "PROJECTS_QUICK_ACTION_OPEN_DETAILS");
        yg ygVar53 = new yg("PROJECTS_QUICK_ACTION_OTHER_PROJECTS", 52, "PROJECTS_QUICK_ACTION_OTHER_PROJECTS");
        yg ygVar54 = new yg("PROJECTS_QUICK_ACTION_REOPEN", 53, "PROJECTS_QUICK_ACTION_REOPEN");
        yg ygVar55 = new yg("PROJECTS_TABLE_VIEW_LIST_ITEM", 54, "PROJECTS_TABLE_VIEW_LIST_ITEM");
        yg ygVar56 = new yg("PROJECT_VIEW", 55, "PROJECT_VIEW");
        yg ygVar57 = new yg("PROJECT_VIEW_TIMEOUT_CTA", 56, "PROJECT_VIEW_TIMEOUT_CTA");
        yg ygVar58 = new yg("PULL_REQUESTS_LIST_ITEM", 57, "PULL_REQUESTS_LIST_ITEM");
        yg ygVar59 = new yg("PULL_REQUESTS_SEARCH", 58, "PULL_REQUESTS_SEARCH");
        yg ygVar60 = new yg("RELEASES_LIST_LATEST_RELEASE", 59, "RELEASES_LIST_LATEST_RELEASE");
        yg ygVar61 = new yg("RELEASE_DOWNLOAD_ASSET", 60, "RELEASE_DOWNLOAD_ASSET");
        yg ygVar62 = new yg("RELEASE_LINKED_DISCUSSION", 61, "RELEASE_LINKED_DISCUSSION");
        yg ygVar63 = new yg("REPOSITORY_DISCUSSIONS_LIST_FILTER", 62, "REPOSITORY_DISCUSSIONS_LIST_FILTER");
        yg ygVar64 = new yg("REPOSITORY_EDIT_README", 63, "REPOSITORY_EDIT_README");
        yg ygVar65 = new yg("REPOSITORY_ISSUES_LIST_FILTER", 64, "REPOSITORY_ISSUES_LIST_FILTER");
        yg ygVar66 = new yg("REPOSITORY_LATEST_RELEASE", 65, "REPOSITORY_LATEST_RELEASE");
        yg ygVar67 = new yg("REPOSITORY_PULL_REQUESTS_LIST_FILTER", 66, "REPOSITORY_PULL_REQUESTS_LIST_FILTER");
        yg ygVar68 = new yg("SETTINGS_ACCOUNTS", 67, "SETTINGS_ACCOUNTS");
        yg ygVar69 = new yg("SETTINGS_DISABLE_ANALYTICS", 68, "SETTINGS_DISABLE_ANALYTICS");
        yg ygVar70 = new yg("SHORTCUTS_LIST_ITEM", 69, "SHORTCUTS_LIST_ITEM");
        yg ygVar71 = new yg("SHORTCUT_SUGGESTIONS_LIST_ITEM", 70, "SHORTCUT_SUGGESTIONS_LIST_ITEM");
        yg ygVar72 = new yg("SHOW_MORE_ROLLUP", 71, "SHOW_MORE_ROLLUP");
        yg ygVar73 = new yg("STAR_REPOSITORY", 72, "STAR_REPOSITORY");
        yg ygVar74 = new yg("TRIAGE_ASSIGNEE_EDIT", 73, "TRIAGE_ASSIGNEE_EDIT");
        yg ygVar75 = new yg("TRIAGE_CLOSE", 74, "TRIAGE_CLOSE");
        yg ygVar76 = new yg("TRIAGE_COMMENT", 75, "TRIAGE_COMMENT");
        yg ygVar77 = new yg("TRIAGE_COMMENT_DOWN", 76, "TRIAGE_COMMENT_DOWN");
        yg ygVar78 = new yg("TRIAGE_COMMENT_EDIT", 77, "TRIAGE_COMMENT_EDIT");
        yg ygVar79 = new yg("TRIAGE_COMMENT_UP", 78, "TRIAGE_COMMENT_UP");
        yg ygVar80 = new yg("TRIAGE_EXPAND", 79, "TRIAGE_EXPAND");
        yg ygVar81 = new yg("TRIAGE_LABEL_EDIT", 80, "TRIAGE_LABEL_EDIT");
        yg ygVar82 = new yg("TRIAGE_LINKED_ITEM_EDIT", 81, "TRIAGE_LINKED_ITEM_EDIT");
        yg ygVar83 = new yg("TRIAGE_LOCK", 82, "TRIAGE_LOCK");
        yg ygVar84 = new yg("TRIAGE_MILESTONE_EDIT", 83, "TRIAGE_MILESTONE_EDIT");
        yg ygVar85 = new yg("TRIAGE_PROJECT_EDIT", 84, "TRIAGE_PROJECT_EDIT");
        yg ygVar86 = new yg("TRIAGE_PROJECT_NEXT_EDIT", 85, "TRIAGE_PROJECT_NEXT_EDIT");
        yg ygVar87 = new yg("TRIAGE_PROJECT_NEXT_PICKER_OWNER", 86, "TRIAGE_PROJECT_NEXT_PICKER_OWNER");
        yg ygVar88 = new yg("TRIAGE_PROJECT_NEXT_PICKER_RECENT", 87, "TRIAGE_PROJECT_NEXT_PICKER_RECENT");
        yg ygVar89 = new yg("TRIAGE_REVIEW_REQUEST_EDIT", 88, "TRIAGE_REVIEW_REQUEST_EDIT");
        yg ygVar90 = new yg("TRIAGE_UNSUBSCRIBE", 89, "TRIAGE_UNSUBSCRIBE");
        yg ygVar91 = new yg("VIEWER_DISCUSSIONS_LIST_FILTER", 90, "VIEWER_DISCUSSIONS_LIST_FILTER");
        yg ygVar92 = new yg("VIEWER_ISSUES_LIST_FILTER", 91, "VIEWER_ISSUES_LIST_FILTER");
        yg ygVar93 = new yg("VIEWER_PULL_REQUESTS_LIST_FILTER", 92, "VIEWER_PULL_REQUESTS_LIST_FILTER");
        yg ygVar94 = new yg("VIEWER_PULL_TO_REFRESH", 93, "VIEWER_PULL_TO_REFRESH");
        yg ygVar95 = new yg("VIEWING_AS_TOAST", 94, "VIEWING_AS_TOAST");
        yg ygVar96 = new yg("UNKNOWN__", 95, "UNKNOWN__");
        s = ygVar96;
        yg[] ygVarArr = {ygVar, ygVar2, ygVar3, ygVar4, ygVar5, ygVar6, ygVar7, ygVar8, ygVar9, ygVar10, ygVar11, ygVar12, ygVar13, ygVar14, ygVar15, ygVar16, ygVar17, ygVar18, ygVar19, ygVar20, ygVar21, ygVar22, ygVar23, ygVar24, ygVar25, ygVar26, ygVar27, ygVar28, ygVar29, ygVar30, ygVar31, ygVar32, ygVar33, ygVar34, ygVar35, ygVar36, ygVar37, ygVar38, ygVar39, ygVar40, ygVar41, ygVar42, ygVar43, ygVar44, ygVar45, ygVar46, ygVar47, ygVar48, ygVar49, ygVar50, ygVar51, ygVar52, ygVar53, ygVar54, ygVar55, ygVar56, ygVar57, ygVar58, ygVar59, ygVar60, ygVar61, ygVar62, ygVar63, ygVar64, ygVar65, ygVar66, ygVar67, ygVar68, ygVar69, ygVar70, ygVar71, ygVar72, ygVar73, ygVar74, ygVar75, ygVar76, ygVar77, ygVar78, ygVar79, ygVar80, ygVar81, ygVar82, ygVar83, ygVar84, ygVar85, ygVar86, ygVar87, ygVar88, ygVar89, ygVar90, ygVar91, ygVar92, ygVar93, ygVar94, ygVar95, ygVar96};
        t = ygVarArr;
        u = v8.l0.t(ygVarArr);
        Companion = new xg();
        sy.d0.o(new String[]{"ACCOUNT_SWITCHER_ADD", "ACCOUNT_SWITCHER_ITEM", "ACCOUNT_SWITCHER_REMOVE", "CODE_SEARCH_LIST_ITEM", "DEEP_LINK_ERROR_ACCOUNT_SWITCHER", "EXPLORE_BOTTOM_NAVIGATION", "EXPLORE_FEATURED_REPOSITORY", "EXPLORE_FOR_YOU_REPOSITORY", "EXPLORE_STAR_FEATURED_REPOSITORY", "EXPLORE_STAR_FOR_YOU_REPOSITORY", "EXPLORE_STAR_TRENDING_REPOSITORY", "EXPLORE_TRENDING_LIST_FILTER", "EXPLORE_TRENDING_REPOSITORY", "FOLLOW", "GLOBAL_SEARCH_SHORTCUT", "HOME_BOTTOM_NAVIGATION", "HOME_CREATE_ISSUE", "HOME_DISCUSSIONS", "HOME_FAVORITE_REPOSITORY_ITEM", "HOME_IN_APP_UPDATE", "HOME_ISSUES", "HOME_ISSUES_LIST_NEW_ISSUE", "HOME_ORGANIZATIONS", "HOME_PROJECTS", "HOME_PULL_REQUESTS", "HOME_RECENT_ACTIVITY_ITEM", "HOME_RELEASE_NOTES", "HOME_REPOSITORIES", "HOME_REPOSITORY_LIST_FILTER", "HOME_SHORTCUTS", "HOME_STARRED", "ISSUES_LIST_ITEM", "ISSUES_SEARCH", "ISSUE_COMPOSER", "ISSUE_COMPOSER_PROPERTY_BAR", "NOTIFICATIONS_ONBOARDING_BANNER", "NOTIFICATION_BOTTOM_NAVIGATION", "NOTIFICATION_FILTER", "NOTIFICATION_LIST_FILTER", "NOTIFICATION_LIST_ITEM", "NOTIFICATION_LIST_ITEM_UNDO", "NOTIFICATION_PUSH", "ONBOARDING_BANNER", "PROFILE_BOTTOM_NAVIGATION", "PROFILE_HEADER_NAME", "PROFILE_REPOSITORY_LIST_FILTER", "PROJECTS_LIST_ITEM", "PROJECTS_QUICK_ACTION_CLOSE", "PROJECTS_QUICK_ACTION_DELETE", "PROJECTS_QUICK_ACTION_EDIT_FIELD", "PROJECTS_QUICK_ACTION_EDIT_TITLE", "PROJECTS_QUICK_ACTION_OPEN_DETAILS", "PROJECTS_QUICK_ACTION_OTHER_PROJECTS", "PROJECTS_QUICK_ACTION_REOPEN", "PROJECTS_TABLE_VIEW_LIST_ITEM", "PROJECT_VIEW", "PROJECT_VIEW_TIMEOUT_CTA", "PULL_REQUESTS_LIST_ITEM", "PULL_REQUESTS_SEARCH", "RELEASES_LIST_LATEST_RELEASE", "RELEASE_DOWNLOAD_ASSET", "RELEASE_LINKED_DISCUSSION", "REPOSITORY_DISCUSSIONS_LIST_FILTER", "REPOSITORY_EDIT_README", "REPOSITORY_ISSUES_LIST_FILTER", "REPOSITORY_LATEST_RELEASE", "REPOSITORY_PULL_REQUESTS_LIST_FILTER", "SETTINGS_ACCOUNTS", "SETTINGS_DISABLE_ANALYTICS", "SHORTCUTS_LIST_ITEM", "SHORTCUT_SUGGESTIONS_LIST_ITEM", "SHOW_MORE_ROLLUP", "STAR_REPOSITORY", "TRIAGE_ASSIGNEE_EDIT", "TRIAGE_CLOSE", "TRIAGE_COMMENT", "TRIAGE_COMMENT_DOWN", "TRIAGE_COMMENT_EDIT", "TRIAGE_COMMENT_UP", "TRIAGE_EXPAND", "TRIAGE_LABEL_EDIT", "TRIAGE_LINKED_ITEM_EDIT", "TRIAGE_LOCK", "TRIAGE_MILESTONE_EDIT", "TRIAGE_PROJECT_EDIT", "TRIAGE_PROJECT_NEXT_EDIT", "TRIAGE_PROJECT_NEXT_PICKER_OWNER", "TRIAGE_PROJECT_NEXT_PICKER_RECENT", "TRIAGE_REVIEW_REQUEST_EDIT", "TRIAGE_UNSUBSCRIBE", "VIEWER_DISCUSSIONS_LIST_FILTER", "VIEWER_ISSUES_LIST_FILTER", "VIEWER_PULL_REQUESTS_LIST_FILTER", "VIEWER_PULL_TO_REFRESH", "VIEWING_AS_TOAST"});
    }

    public yg(String str, int i, String str2) {
        this.r = str2;
    }

    public static yg valueOf(String str) {
        return (yg) Enum.valueOf(yg.class, str);
    }

    public static yg[] values() {
        return (yg[]) t.clone();
    }
}
