package fc0;

import hc0.ap;
import hc0.bb;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.kz;
import hc0.lk;
import hc0.m00;
import hc0.n7;
import hc0.p7;
import hc0.pm;
import hc0.q00;
import hc0.xk;
import hc0.yg;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class n0 {
    public static final List a;

    static {
        fb.Companion.getClass();
        aa.x xVar = fb.a;
        aa.r b = v8.l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = f30.a.a;
        List r2 = x61.l.r(new aa.s[]{mVar, no.a.c(list, "selections", "Actor", r, list)});
        dq.Companion.getClass();
        aa.m mVar2 = new aa.m("owner", v8.l0.b(dq.a), (String) null, rVar, rVar, r2);
        aa.m mVar3 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        bb.Companion.getClass();
        aa.x xVar2 = bb.a;
        List r3 = x61.l.r(new aa.m[]{mVar2, mVar3, new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r4 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = sy.d0.n("DeploymentRequest");
        List list2 = z40.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar4, no.a.c(list2, "selections", "DeploymentRequest", n, list2)});
        n7.Companion.getClass();
        List n2 = sy.d0.n(new aa.m("nodes", v8.l0.a(n7.c), (String) null, rVar, rVar, r6));
        aa.m mVar5 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        aa.x xVar3 = ew.a;
        aa.m mVar6 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        db.Companion.getClass();
        aa.m mVar7 = new aa.m("runNumber", v8.l0.b(db.a), (String) null, rVar, rVar, rVar);
        m00.Companion.getClass();
        aa.m mVar8 = new aa.m("workflow", v8.l0.b(m00.c), (String) null, rVar, rVar, r5);
        p7.Companion.getClass();
        aa.r b2 = v8.l0.b(p7.a);
        q00.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, mVar8, new aa.m("pendingDeploymentRequests", b2, (String) null, rVar, no.a.s(q00.a, new aa.u0(new aa.t("numberOfDeploymentRequests"))), n2), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0.n("CheckRun");
        List list3 = z30.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar9, no.a.c(list3, "selections", "CheckRun", n3, list3), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        hc0.l2.Companion.getClass();
        List n4 = sy.d0.n(new aa.m("nodes", v8.l0.a(hc0.l2.f), (String) null, rVar, rVar, r8));
        aa.s mVar10 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n5 = sy.d0.n("PullRequest");
        List list4 = a80.b.a;
        List r9 = x61.l.r(new aa.s[]{mVar10, no.a.c(list4, "selections", "PullRequest", n5, list4), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        lk.Companion.getClass();
        List n6 = sy.d0.n(new aa.m("nodes", v8.l0.a(lk.J), (String) null, rVar, rVar, r9));
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar12 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        hc0.p2.Companion.getClass();
        aa.m mVar13 = new aa.m("status", v8.l0.b(hc0.p2.s), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        aa.m mVar14 = new aa.m("repository", v8.l0.b(ap.k0), (String) null, rVar, rVar, r3);
        kz.Companion.getClass();
        aa.q0 q0Var = kz.O;
        k71.k.g(q0Var, "type");
        aa.m mVar15 = new aa.m("creator", q0Var, (String) null, rVar, rVar, r4);
        aa.q0 q0Var2 = q00.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar16 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r7);
        hc0.n2.Companion.getClass();
        aa.q0 q0Var3 = hc0.n2.a;
        k71.k.g(q0Var3, "type");
        hc0.v2.Companion.getClass();
        aa.m mVar17 = new aa.m("checkRuns", q0Var3, (String) null, rVar, no.a.s(hc0.v2.c, new aa.u0(new aa.t("numberOfCheckRuns"))), n4);
        xk.Companion.getClass();
        aa.q0 q0Var4 = xk.a;
        k71.k.g(q0Var4, "type");
        List r10 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("CheckSuite", sy.d0.n("CheckSuite"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("matchingPullRequests", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(hc0.v2.d, new aa.u0(new aa.t("cursor"))), new aa.k(hc0.v2.e, new aa.u0(new aa.t("numberOfPullRequests")))}), n6)})), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        yg.Companion.getClass();
        aa.j0 j0Var = yg.a;
        k71.k.g(j0Var, "type");
        pm.Companion.getClass();
        a = sy.d0.n(new aa.m("node", j0Var, (String) null, rVar, no.a.s(pm.f, new aa.u0(new aa.t("nodeId"))), r10));
    }
}
