package fc0;

import hc0.bb;
import hc0.br;
import hc0.db;
import hc0.ew;
import hc0.fb;
import hc0.ji;
import hc0.lk;
import hc0.m00;
import hc0.mu;
import hc0.ou;
import hc0.pm;
import hc0.q00;
import hc0.qu;
import hc0.rk;
import hc0.su;
import hc0.uu;
import hc0.vk;
import hc0.xa;
import hc0.yg;
import hc0.zq;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class u {
    public static final List a;

    static {
        bb.Companion.getClass();
        aa.x xVar = bb.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        aa.x xVar2 = fb.a;
        aa.m mVar2 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        uu.Companion.getClass();
        aa.a0 a0Var = uu.s;
        List r = x61.l.r(new aa.m[]{mVar, mVar2, new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar), new aa.m("description", xVar2, (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        db.Companion.getClass();
        aa.x xVar3 = db.a;
        aa.m mVar3 = new aa.m("totalCount", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        zq.Companion.getClass();
        List r2 = x61.l.r(new aa.m[]{mVar3, new aa.m("nodes", v8.l0.a(zq.a), (String) null, rVar, rVar, r)});
        xa.Companion.getClass();
        aa.x xVar4 = xa.a;
        List r3 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        aa.m mVar4 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar6 = new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        aa.x xVar5 = ew.a;
        k71.k.g(xVar5, "type");
        aa.m mVar7 = new aa.m("avatarUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.m mVar8 = new aa.m("description", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("targetUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.r b2 = v8.l0.b(xVar4);
        su.Companion.getClass();
        List r4 = x61.l.r(new aa.m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(su.a, new aa.u0(new aa.t("id"))), rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m00.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{new aa.m("workflow", v8.l0.b(m00.c), (String) null, rVar, rVar, r5), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("logoUrl", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        q00.Companion.getClass();
        aa.q0 q0Var = q00.b;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("workflowRun", q0Var, (String) null, rVar, rVar, r6);
        hc0.l0.Companion.getClass();
        aa.q0 q0Var2 = hc0.l0.a;
        k71.k.g(q0Var2, "type");
        List r8 = x61.l.r(new aa.m[]{mVar10, new aa.m("app", q0Var2, (String) null, rVar, rVar, r7), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        hc0.j2.Companion.getClass();
        aa.a0 a0Var2 = hc0.j2.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar12 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar14 = new aa.m("summary", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar15 = new aa.m("permalink", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("duration", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        hc0.v2.Companion.getClass();
        aa.m mVar17 = new aa.m("checkSuite", v8.l0.b(hc0.v2.f), (String) null, rVar, rVar, r8);
        aa.r b3 = v8.l0.b(xVar4);
        hc0.l2.Companion.getClass();
        List r9 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", sy.d0Shadow.n("StatusContext"), r4), new aa.n("CheckRun", sy.d0Shadow.n("CheckRun"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(hc0.l2.a, new aa.u0(new aa.t("id"))), rVar)}))});
        ji.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", v8.l0.b(ji.a), (String) null, rVar, rVar, r3);
        ou.Companion.getClass();
        List r10 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", v8.l0.a(ou.a), (String) null, rVar, rVar, r9)});
        aa.m mVar19 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        qu.Companion.getClass();
        aa.r b4 = v8.l0.b(qu.a);
        mu.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar19, new aa.m("contexts", b4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(mu.a, new aa.u0(new aa.t("after"))), new aa.k(mu.b, new aa.u0(25))}), r10), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        hc0.h6.Companion.getClass();
        aa.x xVar6 = hc0.h6.a;
        k71.k.g(xVar6, "type");
        aa.m mVar20 = new aa.m("pushedDate", xVar6, (String) null, rVar, rVar, rVar);
        aa.q0 q0Var3 = mu.c;
        k71.k.g(q0Var3, "type");
        List r13 = x61.l.r(new aa.m[]{mVar20, new aa.m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r12), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        hc0.t3.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{new aa.m("commit", v8.l0.b(hc0.t3.j), (String) null, rVar, rVar, r13), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        rk.Companion.getClass();
        List n = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(rk.a), (String) null, rVar, rVar, r14));
        br.Companion.getClass();
        aa.r b5 = v8.l0.b(br.a);
        lk.Companion.getClass();
        aa.m mVar21 = new aa.m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(lk.u, new aa.u0(25)), r2);
        vk.Companion.getClass();
        List r15 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequest", sy.d0Shadow.n("PullRequest"), x61.l.r(new aa.m[]{mVar21, new aa.m("commits", v8.l0.b(vk.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(lk.i, new aa.u0((Object) null)), new aa.k(lk.k, new aa.u0(1))}), n)})), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yg.Companion.getClass();
        aa.j0 j0Var = yg.a;
        k71.k.g(j0Var, "type");
        pm.Companion.getClass();
        a = sy.d0Shadow.n(new aa.m("node", j0Var, (String) null, rVar, no.a.s(pm.f, new aa.u0(new aa.t("id"))), r15));
    }
}
