package fc0;

import hc0.ap;
import hc0.bb;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.hb;
import hc0.ji;
import hc0.jn;
import hc0.kz;
import hc0.na;
import hc0.o8;
import hc0.pm;
import hc0.qz;
import hc0.ra;
import hc0.ta;
import hc0.va;
import hc0.vn;
import hc0.w8;
import hc0.xa;
import hc0.xn;
import hc0.y8;
import hc0.zn;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class z2 {
    public static final List a;

    static {
        fb.Companion.getClass();
        aa.x xVar = fb.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        bb.Companion.getClass();
        aa.x xVar2 = bb.a;
        aa.s mVar2 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = f30.b.a;
        List r2 = x61.l.r(new aa.s[]{mVar, mVar2, no.a.c(list, "selections", "Actor", r, list)});
        xa.Companion.getClass();
        aa.x xVar3 = xa.a;
        List n = sy.d0Shadow.n(new aa.m("isValid", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar3 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ta.Companion.getClass();
        aa.x xVar4 = ta.a;
        aa.m mVar4 = new aa.m("oid", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("abbreviatedOid", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        va.Companion.getClass();
        aa.j0 j0Var = va.a;
        k71.k.g(j0Var, "type");
        aa.m mVar6 = new aa.m("signature", j0Var, (String) null, rVar, rVar, n);
        aa.m mVar7 = new aa.m("message", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        aa.x xVar5 = hb.a;
        aa.m mVar8 = new aa.m("messageBodyHTML", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        hc0.h6.Companion.getClass();
        aa.x xVar6 = hc0.h6.a;
        List r3 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("Commit", sy.d0Shadow.n("Commit"), x61.l.r(new aa.m[]{mVar3, mVar4, mVar5, mVar6, mVar7, mVar8, new aa.m("authoredDate", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar)}))});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r4 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = f30.a.a;
        List r5 = x61.l.r(new aa.s[]{mVar9, no.a.c(list2, "selections", "Actor", r4, list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        kz.Companion.getClass();
        aa.q0 q0Var = kz.O;
        k71.k.g(q0Var, "type");
        List n2 = sy.d0Shadow.n(new aa.m("user", q0Var, (String) null, rVar, rVar, r5));
        aa.m mVar10 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ra.Companion.getClass();
        aa.j0 j0Var2 = ra.a;
        aa.m mVar11 = new aa.m("target", v8.l0.b(j0Var2), (String) null, rVar, rVar, r3);
        aa.m mVar12 = new aa.m("message", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        aa.x xVar7 = ew.a;
        aa.m mVar14 = new aa.m("commitUrl", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar);
        na.Companion.getClass();
        aa.q0 q0Var2 = na.a;
        k71.k.g(q0Var2, "type");
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("target", j0Var2, (String) null, rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("Tag", sy.d0Shadow.n("Tag"), x61.l.r(new aa.m[]{mVar10, mVar11, mVar12, mVar13, mVar14, new aa.m("tagger", q0Var2, (String) null, rVar, rVar, n2)}))})), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("oid", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("abbreviatedOid", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r8 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar, (String) null, rVar, rVar, rVar)});
        aa.m mVar15 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        db.Companion.getClass();
        aa.x xVar8 = db.a;
        List r10 = x61.l.r(new aa.m[]{mVar15, mVar16, new aa.m("size", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar), new aa.m("url", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar), new aa.m("contentType", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        ji.Companion.getClass();
        aa.m mVar17 = new aa.m("pageInfo", v8.l0.b(ji.a), (String) null, rVar, rVar, r9);
        xn.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar17, new aa.m("nodes", v8.l0.a(xn.a), (String) null, rVar, rVar, r10)});
        List r13 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2)});
        aa.s mVar18 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar19 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hc0.l.Companion.getClass();
        aa.j0 j0Var3 = hc0.l.a;
        k71.k.g(j0Var3, "type");
        aa.s mVar20 = new aa.m("author", j0Var3, (String) null, rVar, rVar, r13);
        aa.s mVar21 = new aa.m("createdAt", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("lastEditedAt", xVar6, (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("body", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReviewComment"});
        List list3 = z60.a.a;
        List r15 = x61.l.r(new aa.s[]{mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, no.a.c(list3, "selections", "Minimizable", r14, list3)});
        aa.m mVar24 = new aa.m("totalCount", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar);
        w8.Companion.getClass();
        List r16 = x61.l.r(new aa.m[]{mVar24, new aa.m("nodes", v8.l0.a(w8.c), (String) null, rVar, rVar, r15)});
        aa.m mVar25 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar26 = new aa.m("number", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar);
        y8.Companion.getClass();
        aa.r b2 = v8.l0.b(y8.a);
        o8.Companion.getClass();
        List r17 = x61.l.r(new aa.m[]{mVar25, mVar26, new aa.m("comments", b2, (String) null, rVar, no.a.s(o8.h, new aa.u0(3)), r16), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r18 = x61.l.r(new aa.m[]{new aa.m("totalCount", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar), new aa.m("nodes", v8.l0.a(q0Var), (String) null, rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        aa.s mVar27 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar29 = new aa.m("url", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar30 = new aa.m("name", xVar, (String) null, rVar, rVar, rVar);
        aa.s mVar31 = new aa.m("tagName", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        hc0.t3.Companion.getClass();
        aa.q0 q0Var3 = hc0.t3.j;
        k71.k.g(q0Var3, "type");
        aa.s mVar32 = new aa.m("tagCommit", q0Var3, (String) null, rVar, rVar, r7);
        aa.s mVar33 = new aa.m("author", q0Var, (String) null, rVar, rVar, r8);
        List r19 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list4 = j80.a.a;
        aa.s c = no.a.c(list4, "selections", "Reactable", r19, list4);
        aa.s mVar34 = new aa.m("descriptionHTML", xVar5, (String) null, rVar, rVar, rVar);
        aa.s mVar35 = new aa.m("isPrerelease", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar36 = new aa.m("isDraft", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar37 = new aa.m("isLatest", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar38 = new aa.m("createdAt", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar39 = new aa.m("publishedAt", xVar6, (String) null, rVar, rVar, rVar);
        zn.Companion.getClass();
        aa.r b3 = v8.l0.b(zn.a);
        vn.Companion.getClass();
        aa.s mVar40 = new aa.m("releaseAssets", b3, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(vn.c, new aa.u0(new aa.t("after"))), new aa.k(vn.d, new aa.u0(new aa.t("number")))}), r12);
        aa.q0 q0Var4 = o8.l;
        k71.k.g(q0Var4, "type");
        aa.s mVar41 = new aa.m("discussion", q0Var4, (String) null, rVar, rVar, r17);
        qz.Companion.getClass();
        aa.q0 q0Var5 = qz.a;
        k71.k.g(q0Var5, "type");
        List r20 = x61.l.r(new aa.s[]{mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, c, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, new aa.m("mentions", q0Var5, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(vn.a, new aa.u0((Object) null)), new aa.k(vn.b, new aa.u0(5))}), r18)});
        aa.m mVar42 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        aa.m mVar43 = new aa.m("owner", v8.l0.b(dq.a), (String) null, rVar, rVar, r2);
        jn.Companion.getClass();
        aa.q0 q0Var6 = jn.b;
        k71.k.g(q0Var6, "type");
        ap.Companion.getClass();
        aa.m mVar44 = new aa.m("ref", q0Var6, (String) null, rVar, no.a.s(ap.O, new aa.u0(new aa.t("tagName"))), r6);
        aa.q0 q0Var7 = vn.e;
        k71.k.g(q0Var7, "type");
        List r22 = x61.l.r(new aa.m[]{mVar42, mVar43, mVar44, new aa.m("release", q0Var7, (String) null, rVar, no.a.s(ap.U, new aa.u0(new aa.t("tagName"))), r20), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.q0 q0Var8 = ap.k0;
        k71.k.g(q0Var8, "type");
        pm.Companion.getClass();
        a = sy.d0Shadow.n(new aa.m("repository", q0Var8, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(pm.i, new aa.u0(new aa.t("repositoryName"))), new aa.k(pm.j, new aa.u0(new aa.t("repositoryOwner")))}), r22));
    }
}
