package bp0;

import aa.j0;
import aa.q0;
import aa.u0;
import aa.x0;
import java.util.List;
import pz0.cc;
import pz0.d50;
import pz0.h50;
import pz0.hc;
import pz0.jd;
import pz0.jx;
import pz0.ld;
import pz0.mv;
import pz0.ny;
import pz0.pd;
import pz0.s4;
import pz0.td;
import pz0.vd;
import pz0.xd;
import pz0.zd;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class y {
    public static final List a;

    static {
        xd.Companion.getClass();
        aa.x xVar = xd.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = sy.d0Shadow.n("FileLine");
        List list = nr0.a.a;
        List r = x61.l.r(new aa.s[]{mVar, no.a.c(list, "selections", "FileLine", n, list)});
        zd.Companion.getClass();
        aa.x xVar2 = zd.a;
        k71.k.g(xVar2, "type");
        aa.m mVar2 = new aa.m("contentHTML", xVar2, (String) null, rVar, rVar, rVar);
        hc.Companion.getClass();
        q0 q0Var = hc.a;
        List r2 = x61.l.r(new aa.m[]{mVar2, new aa.m("fileLines", l0.a(q0Var), "markDownFileLines", rVar, rVar, r)});
        h50.Companion.getClass();
        aa.x xVar3 = h50.a;
        k71.k.g(xVar3, "type");
        List r3 = x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("MarkdownFileType", sy.d0Shadow.n("MarkdownFileType"), r2), new aa.n("ImageFileType", sy.d0Shadow.n("ImageFileType"), sy.d0Shadow.n(new aa.m("url", xVar3, (String) null, rVar, rVar, rVar))), new aa.n("PdfFileType", sy.d0Shadow.n("PdfFileType"), sy.d0Shadow.n(new aa.m("url", xVar3, (String) null, rVar, rVar, rVar))), new aa.n("TextFileType", sy.d0Shadow.n("TextFileType"), sy.d0Shadow.n(new aa.m("fileLines", l0.a(q0Var), "textFieldFileLines", rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("FileLine", sy.d0Shadow.n("FileLine"), list)}))))});
        aa.m mVar3 = new aa.m("extension", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar4 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        cc.Companion.getClass();
        x0 x0Var = cc.a;
        k71.k.g(x0Var, "type");
        List r4 = x61.l.r(new aa.m[]{mVar3, mVar4, new aa.m("fileType", x0Var, (String) null, rVar, rVar, r3)});
        d50.Companion.getClass();
        q0 q0Var2 = d50.a;
        k71.k.g(q0Var2, "type");
        s4.Companion.getClass();
        aa.m mVar5 = new aa.m("file", q0Var2, (String) null, rVar, no.a.s(s4.e, new u0(new aa.t("path"))), r4);
        td.Companion.getClass();
        aa.x xVar4 = td.a;
        List r5 = x61.l.r(new aa.m[]{mVar5, new aa.m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r6 = x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueType", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list2 = lw0.a.a;
        List r7 = x61.l.r(new aa.s[]{mVar6, no.a.c(list2, "selections", "Node", r6, list2), new aa.n("Commit", sy.d0Shadow.n("Commit"), r5)});
        aa.m mVar7 = new aa.m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        ld.Companion.getClass();
        List r8 = x61.l.r(new aa.m[]{mVar7, new aa.m("oid", l0.b(ld.a), (String) null, rVar, rVar, rVar)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        aa.x xVar5 = pd.a;
        aa.m mVar10 = new aa.m("viewerCanCommitToBranch", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        jd.Companion.getClass();
        j0 j0Var = jd.a;
        k71.k.g(j0Var, "type");
        List r9 = x61.l.r(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("target", j0Var, (String) null, rVar, rVar, r8), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r10 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.m mVar11 = new aa.m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        aa.x xVar6 = vd.a;
        k71.k.g(xVar6, "type");
        aa.m mVar12 = new aa.m("databaseId", xVar6, (String) null, rVar, rVar, rVar);
        jx.Companion.getClass();
        aa.m mVar13 = new aa.m("object", j0Var, "gitObject", rVar, no.a.s(jx.J, new u0(new aa.t("ref"))), r7);
        aa.m mVar14 = new aa.m("viewerCanPush", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        mv.Companion.getClass();
        q0 q0Var3 = mv.e;
        k71.k.g(q0Var3, "type");
        aa.m mVar15 = new aa.m("ref", q0Var3, (String) null, rVar, no.a.s(jx.W, new u0(new aa.t("ref"))), r9);
        ny.Companion.getClass();
        a = x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, new aa.m("owner", l0.b(ny.e), (String) null, rVar, rVar, r10), new aa.m("isInOrganization", l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
