package ng0;

import aa.m;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import gn0.dd;
import gn0.fd;
import gn0.hc;
import gn0.jj;
import gn0.lb;
import gn0.pb;
import gn0.rb;
import gn0.tb;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class c {
    public static final List a;

    static {
        lb.Companion.getClass();
        x xVar = lb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("hasPreviousPage", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar2 = tb.a;
        k.g(xVar2, "type");
        List r = l.r(new m[]{mVar, new m("startCursor", xVar2, (String) null, rVar, rVar, rVar), new m("hasNextPage", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        s mVar2 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list = cl0.a.a;
        s c = no.a.c(list, "selections", "Node", r2, list);
        List n = d0.n("IssueComment");
        List list2 = pg0.a.a;
        s c2 = no.a.c(list2, "selections", "IssueComment", n, list2);
        List n2 = d0.n("RenamedTitleEvent");
        List list3 = jj0.a.a;
        s c3 = no.a.c(list3, "selections", "RenamedTitleEvent", n2, list3);
        List n3 = d0.n("AssignedEvent");
        List list4 = be0.a.a;
        s c4 = no.a.c(list4, "selections", "AssignedEvent", n3, list4);
        List n4 = d0.n("UnassignedEvent");
        List list5 = lk0.a.a;
        s c5 = no.a.c(list5, "selections", "UnassignedEvent", n4, list5);
        List n5 = d0.n("ClosedEvent");
        List list6 = re0.a.a;
        s c6 = no.a.c(list6, "selections", "ClosedEvent", n5, list6);
        List n6 = d0.n("ReopenedEvent");
        List list7 = lj0.a.a;
        s c7 = no.a.c(list7, "selections", "ReopenedEvent", n6, list7);
        List n7 = d0.n("LabeledEvent");
        List list8 = vg0.a.a;
        s c8 = no.a.c(list8, "selections", "LabeledEvent", n7, list8);
        List n8 = d0.n("UnlabeledEvent");
        List list9 = nk0.a.a;
        s c9 = no.a.c(list9, "selections", "UnlabeledEvent", n8, list9);
        List n9 = d0.n("LockedEvent");
        List list10 = dh0.a.a;
        s c10 = no.a.c(list10, "selections", "LockedEvent", n9, list10);
        List n10 = d0.n("UnlockedEvent");
        List list11 = pk0.a.a;
        s c12 = no.a.c(list11, "selections", "UnlockedEvent", n10, list11);
        List n12 = d0.n("MilestonedEvent");
        List list12 = ph0.a.a;
        s c13 = no.a.c(list12, "selections", "MilestonedEvent", n12, list12);
        List n13 = d0.n("DemilestonedEvent");
        List list13 = jf0.a.a;
        s c14 = no.a.c(list13, "selections", "DemilestonedEvent", n13, list13);
        List n14 = d0.n("CrossReferencedEvent");
        List list14 = ff0.a.a;
        s c15 = no.a.c(list14, "selections", "CrossReferencedEvent", n14, list14);
        List n15 = d0.n("ReferencedEvent");
        List list15 = fj0.a.a;
        s c16 = no.a.c(list15, "selections", "ReferencedEvent", n15, list15);
        List n16 = d0.n("AddedToProjectEvent");
        List list16 = xd0.a.a;
        s c17 = no.a.c(list16, "selections", "AddedToProjectEvent", n16, list16);
        List n17 = d0.n("MovedColumnsInProjectEvent");
        List list17 = vh0.a.a;
        s c18 = no.a.c(list17, "selections", "MovedColumnsInProjectEvent", n17, list17);
        List n18 = d0.n("RemovedFromProjectEvent");
        List list18 = hj0.a.a;
        s c19 = no.a.c(list18, "selections", "RemovedFromProjectEvent", n18, list18);
        List n19 = d0.n("PinnedEvent");
        List list19 = ii0.a.a;
        s c20 = no.a.c(list19, "selections", "PinnedEvent", n19, list19);
        List n20 = d0.n("UnpinnedEvent");
        List list20 = rk0.a.a;
        s c22 = no.a.c(list20, "selections", "UnpinnedEvent", n20, list20);
        List n22 = d0.n("CommentDeletedEvent");
        List list21 = ve0.a.a;
        s c23 = no.a.c(list21, "selections", "CommentDeletedEvent", n22, list21);
        List n23 = d0.n("TransferredEvent");
        List list22 = jk0.a.a;
        s c24 = no.a.c(list22, "selections", "TransferredEvent", n23, list22);
        List n24 = d0.n("MarkedAsDuplicateEvent");
        List list23 = fh0.a.a;
        s c25 = no.a.c(list23, "selections", "MarkedAsDuplicateEvent", n24, list23);
        List n25 = d0.n("UserBlockedEvent");
        List list24 = al0.a.a;
        s c26 = no.a.c(list24, "selections", "UserBlockedEvent", n25, list24);
        List n26 = d0.n("ConvertedToDiscussionEvent");
        List list25 = df0.a.a;
        s c27 = no.a.c(list25, "selections", "ConvertedToDiscussionEvent", n26, list25);
        List n27 = d0.n("ConnectedEvent");
        List list26 = ze0.a.a;
        s c28 = no.a.c(list26, "selections", "ConnectedEvent", n27, list26);
        List n28 = d0.n("DisconnectedEvent");
        List list27 = tf0.a.a;
        List r3 = l.r(new s[]{mVar2, c, c2, c3, c4, c5, c6, c7, c8, c9, c10, c12, c13, c14, c15, c16, c17, c18, c19, c20, c22, c23, c24, c25, c26, c27, c28, no.a.c(list27, "selections", "DisconnectedEvent", n28, list27)});
        m mVar3 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        m mVar4 = new m("beforeFocusCount", l0.b(rb.a), (String) null, rVar, rVar, rVar);
        jj.Companion.getClass();
        m mVar5 = new m("pageInfo", l0.b(jj.a), (String) null, rVar, rVar, r);
        dd.Companion.getClass();
        List r4 = l.r(new m[]{mVar3, mVar4, mVar5, new m("nodes", l0.a(dd.a), (String) null, rVar, rVar, r3)});
        m mVar6 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        pb.Companion.getClass();
        m mVar7 = new m("id", l0.b(pb.a), (String) null, rVar, rVar, rVar);
        fd.Companion.getClass();
        r b2 = l0.b(fd.a);
        hc.Companion.getClass();
        a = l.r(new m[]{mVar6, mVar7, new m("timelineItems", b2, (String) null, rVar, l.r(new aa.k[]{new aa.k(hc.q, new u0(new t("after"))), new aa.k(hc.r, new u0(new t("before"))), new aa.k(hc.s, new u0(new t("desiredAfterCount"))), new aa.k(hc.t, new u0(new t("focusId"))), new aa.k(hc.u, new u0(l.r(new String[]{"ISSUE_COMMENT", "RENAMED_TITLE_EVENT", "ASSIGNED_EVENT", "UNASSIGNED_EVENT", "CLOSED_EVENT", "REOPENED_EVENT", "LABELED_EVENT", "UNLABELED_EVENT", "LOCKED_EVENT", "UNLOCKED_EVENT", "MILESTONED_EVENT", "DEMILESTONED_EVENT", "CROSS_REFERENCED_EVENT", "REFERENCED_EVENT", "ADDED_TO_PROJECT_EVENT", "MOVED_COLUMNS_IN_PROJECT_EVENT", "REMOVED_FROM_PROJECT_EVENT", "PINNED_EVENT", "UNPINNED_EVENT", "COMMENT_DELETED_EVENT", "TRANSFERRED_EVENT", "MARKED_AS_DUPLICATE_EVENT", "USER_BLOCKED_EVENT", "CONVERTED_TO_DISCUSSION_EVENT", "CONNECTED_EVENT", "DISCONNECTED_EVENT"}))), new aa.k(hc.v, new u0(new t("desiredBeforeCount")))}), r4)});
    }
}
