package fa0;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import hc0.ap;
import hc0.bb;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.fc;
import hc0.fm;
import hc0.h6;
import hc0.hn;
import hc0.jc;
import hc0.kz;
import hc0.lc;
import hc0.rb;
import hc0.xa;
import hc0.zb;
import java.util.List;
import k71.k;
import sy.d0Shadow;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class c {
    public static final List a;

    static {
        fb.Companion.getClass();
        x xVar = fb.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        s mVar = new m("__typename", b, (String) null, rVar, rVar, rVar);
        s mVar2 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = f30.b.a;
        s c = no.a.c(list, "selections", "Actor", r, list);
        bb.Companion.getClass();
        x xVar2 = bb.a;
        List r2 = l.r(new s[]{mVar, mVar2, c, new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        db.Companion.getClass();
        x xVar3 = db.a;
        List n = d0Shadow.n(new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r3 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)});
        m mVar3 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar4 = new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        j0 j0Var = dq.a;
        List r4 = l.r(new m[]{mVar3, mVar4, new m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        x xVar4 = ew.a;
        m mVar6 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar7 = new m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        fm.Companion.getClass();
        m mVar10 = new m("state", l0.b(fm.s), "pullRequestState", rVar, rVar, rVar);
        zb.Companion.getClass();
        q0 q0Var = zb.a;
        m mVar11 = new m("comments", l0.b(q0Var), "pullComments", rVar, rVar, n);
        xa.Companion.getClass();
        x xVar5 = xa.a;
        k.g(xVar5, "type");
        m mVar12 = new m("isReadByViewer", xVar5, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("isDraft", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        x xVar6 = h6.a;
        m mVar14 = new m("createdAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        q0 q0Var2 = ap.k0;
        List r5 = l.r(new m[]{mVar5, mVar6, mVar7, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, new m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4)});
        List n2 = d0Shadow.n(new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r6 = l.r(new m[]{new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("owner", l0.b(j0Var), (String) null, rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)})), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar15 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        jc.Companion.getClass();
        m mVar19 = new m("state", l0.b(jc.s), "issueState", rVar, rVar, rVar);
        m mVar20 = new m("comments", l0.b(q0Var), "issueComments", rVar, rVar, n2);
        m mVar21 = new m("isReadByViewer", xVar5, (String) null, rVar, rVar, rVar);
        m mVar22 = new m("createdAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r6);
        lc.Companion.getClass();
        a0 a0Var = lc.s;
        k.g(a0Var, "type");
        List r7 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("PullRequest", d0Shadow.n("PullRequest"), r5), new n("Issue", d0Shadow.n("Issue"), l.r(new m[]{mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, new m("stateReason", a0Var, (String) null, rVar, rVar, rVar)}))});
        rb.Companion.getClass();
        m mVar24 = new m("interaction", l0.b(rb.s), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("occurredAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        kz.Companion.getClass();
        q0 q0Var3 = kz.O;
        k.g(q0Var3, "type");
        m mVar26 = new m("commenter", q0Var3, (String) null, rVar, rVar, r2);
        fc.Companion.getClass();
        List r8 = l.r(new m[]{mVar24, mVar25, mVar26, new m("interactable", l0.b(fc.a), (String) null, rVar, rVar, r7)});
        hn.Companion.getClass();
        a = l.r(new m[]{new m("recentInteractions", no.a.d(hn.a), (String) null, rVar, no.a.s(kz.w, new u0(10)), r8), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
