package pj0;

import a81.t;
import aa.a0;
import aa.j0;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import gn0.dl;
import gn0.hc;
import gn0.kg;
import gn0.lb;
import gn0.mx;
import gn0.nk;
import gn0.pb;
import gn0.pk;
import gn0.r6;
import gn0.rb;
import gn0.rk;
import gn0.tb;
import gn0.tk;
import gn0.vb;
import gn0.xc;
import gn0.zc;
import java.util.List;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class h {
    public static final List a;

    static {
        tb.Companion.getClass();
        x xVar = tb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        s mVar2 = new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.b.a;
        List r2 = x61.l.r(new s[]{mVar, mVar2, no.a.c(list, "selections", "Actor", r, list)});
        s mVar3 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = d0.n("Milestone");
        List list2 = nh0.a.a;
        s c = no.a.c(list2, "selections", "Milestone", n, list2);
        pb.Companion.getClass();
        x xVar2 = pb.a;
        List r3 = x61.l.r(new s[]{mVar3, c, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r4 = x61.l.r(new aa.m[]{new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar4 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        dl.Companion.getClass();
        List r5 = x61.l.r(new aa.m[]{mVar4, mVar5, new aa.m("state", l0.b(dl.s), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        tk.Companion.getClass();
        q0 q0Var = tk.a;
        k71.k.g(q0Var, "type");
        aa.m mVar6 = new aa.m("column", q0Var, (String) null, rVar, rVar, r4);
        nk.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{mVar6, new aa.m("project", l0.b(nk.a), (String) null, rVar, rVar, r5), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        pk.Companion.getClass();
        List n2 = d0.n(new aa.m("nodes", l0.a(pk.a), (String) null, rVar, rVar, r6));
        s mVar7 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        x xVar3 = mx.a;
        s mVar8 = new aa.m("url", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        s mVar9 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar10 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar11 = new aa.m("titleHTML", l0.b(xVar), "titleHTMLString", rVar, rVar, rVar);
        r6.Companion.getClass();
        s mVar12 = new aa.m("createdAt", l0.b(r6.a), (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar4 = lb.a;
        s mVar13 = new aa.m("viewerDidAuthor", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        s mVar14 = new aa.m("locked", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        gn0.l.Companion.getClass();
        j0 j0Var = gn0.l.a;
        k71.k.g(j0Var, "type");
        s mVar15 = new aa.m("author", j0Var, (String) null, rVar, rVar, r2);
        s mVar16 = new aa.m("isReadByViewer", xVar4, (String) null, rVar, rVar, rVar);
        vb.Companion.getClass();
        r b2 = l0.b(vb.a);
        hc.Companion.getClass();
        t tVar = hc.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        aa.k kVar2 = new aa.k(hc.c, new u0(bool));
        aa.k kVar3 = new aa.k(hc.d, new u0(bool));
        t tVar2 = hc.e;
        Boolean bool2 = Boolean.FALSE;
        s mVar17 = new aa.m("bodyHTML", b2, "bodyHtml", rVar, x61.l.r(new aa.k[]{kVar, kVar2, kVar3, new aa.k(tVar2, new u0(bool2)), new aa.k(hc.f, new u0(bool2)), new aa.k(hc.g, new u0(bool))}), rVar);
        s mVar18 = new aa.m("bodyUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        x xVar5 = rb.a;
        s mVar19 = new aa.m("number", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list3 = te0.a.a;
        s c2 = no.a.c(list3, "selections", "Comment", r7, list3);
        List r8 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list4 = bj0.a.a;
        s c3 = no.a.c(list4, "selections", "Reactable", r8, list4);
        List r9 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list5 = zh0.a.a;
        s c4 = no.a.c(list5, "selections", "OrgBlockable", r9, list5);
        List r10 = x61.l.r(new String[]{"Issue", "PullRequest"});
        List list6 = zd0.b.a;
        s c5 = no.a.c(list6, "selections", "Assignable", r10, list6);
        xc.Companion.getClass();
        s mVar20 = new aa.m("state", l0.b(xc.s), "issueState", rVar, rVar, rVar);
        List r12 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list7 = tg0.a.a;
        s c6 = no.a.c(list7, "selections", "Labelable", r12, list7);
        kg.Companion.getClass();
        q0 q0Var2 = kg.a;
        k71.k.g(q0Var2, "type");
        s mVar21 = new aa.m("milestone", q0Var2, (String) null, rVar, rVar, r3);
        rk.Companion.getClass();
        s mVar22 = new aa.m("projectCards", l0.b(rk.a), (String) null, rVar, no.a.s(hc.n, new u0(25)), n2);
        List n3 = d0.n("Issue");
        List list8 = zg0.b.a;
        s c7 = no.a.c(list8, "selections", "Issue", n3, list8);
        List r13 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list9 = tk0.a.a;
        s c8 = no.a.c(list9, "selections", "Updatable", r13, list9);
        r b3 = l0.b(xVar5);
        t tVar3 = hc.o;
        s mVar23 = new aa.m("taskListItemCount", b3, "completeTaskListItemCount", rVar, no.a.s(tVar3, new u0(d0.n("COMPLETE"))), rVar);
        s mVar24 = new aa.m("taskListItemCount", l0.b(xVar5), "incompleteTaskListItemCount", rVar, no.a.s(tVar3, new u0(d0.n("INCOMPLETE"))), rVar);
        s mVar25 = new aa.m("viewerCanReopen", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        zc.Companion.getClass();
        a0 a0Var = zc.s;
        k71.k.g(a0Var, "type");
        a = x61.l.r(new s[]{mVar7, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, c2, c3, c4, c5, mVar20, c6, mVar21, mVar22, c7, c8, mVar23, mVar24, mVar25, new aa.m("stateReason", a0Var, (String) null, rVar, rVar, rVar), new aa.m("viewerCanAssign", l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("viewerCanLabel", l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("isPinned", xVar4, (String) null, rVar, rVar, rVar)});
    }
}
