package y10;

import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import hc0.ap;
import hc0.bb;
import hc0.db;
import hc0.ew;
import hc0.fb;
import hc0.h;
import hc0.ip;
import hc0.lk;
import hc0.mv;
import hc0.o8;
import hc0.tb;
import java.util.List;
import k71.k;
import sy.d0Shadow;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        ew.Companion.getClass();
        x xVar = ew.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        m mVar = new m("url", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar2 = fb.a;
        m mVar2 = new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        bb.Companion.getClass();
        x xVar3 = bb.a;
        List r = l.r(new m[]{mVar, mVar2, new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ap.Companion.getClass();
        q0 q0Var = ap.k0;
        m mVar3 = new m("nodes", l0.a(q0Var), (String) null, rVar, rVar, r);
        db.Companion.getClass();
        x xVar4 = db.a;
        List r2 = l.r(new m[]{mVar3, new m("totalCount", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        ip.Companion.getClass();
        r b2 = l0.b(ip.a);
        h.Companion.getClass();
        List n = d0Shadow.n(new m("repositories", b2, (String) null, rVar, no.a.s(h.a, new u0(3)), r2));
        List r3 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r4 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r5 = l.r(new m[]{new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar4 = new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar);
        o8.Companion.getClass();
        q0 q0Var2 = o8.l;
        k.g(q0Var2, "type");
        List r6 = l.r(new m[]{mVar4, new m("discussion", q0Var2, (String) null, rVar, rVar, r5), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r7 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r8 = l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = l.r(new m[]{new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("repository", l0.b(q0Var), (String) null, rVar, rVar, r8);
        tb.Companion.getClass();
        List r11 = l.r(new m[]{mVar5, mVar6, new m("issue", l0.b(tb.x), (String) null, rVar, rVar, r9), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r12 = l.r(new m[]{new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r13 = l.r(new m[]{new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar7 = new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar);
        lk.Companion.getClass();
        q0 q0Var3 = lk.J;
        List r14 = l.r(new m[]{mVar7, new m("pullRequest", l0.b(q0Var3), (String) null, rVar, rVar, r13), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r15 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("pullRequest", l0.b(q0Var3), (String) null, rVar, rVar, l.r(new m[]{new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        m mVar8 = new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)}));
        k.g(xVar2, "type");
        List r16 = l.r(new m[]{mVar8, new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r17 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r18 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r19 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("repository", l0.b(q0Var), (String) null, rVar, rVar, l.r(new m[]{new m("nameWithOwner", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r21 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar9 = new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar);
        mv.Companion.getClass();
        List r22 = l.r(new m[]{mVar9, new m("team", l0.b(mv.a), (String) null, rVar, rVar, r21), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List r23 = l.r(new m[]{new m("url", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        s mVar10 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r24 = l.r(new String[]{"Achievement", "AchievementTier", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list = ka0.a.a;
        a = l.r(new s[]{mVar10, no.a.c(list, "selections", "Node", r24, list), new n("AchievementRepositoryList", d0Shadow.n("AchievementRepositoryList"), n), new n("CommitComment", d0Shadow.n("CommitComment"), r3), new n("Discussion", d0Shadow.n("Discussion"), r4), new n("DiscussionComment", d0Shadow.n("DiscussionComment"), r6), new n("Issue", d0Shadow.n("Issue"), r7), new n("IssueComment", d0Shadow.n("IssueComment"), r11), new n("PullRequest", d0Shadow.n("PullRequest"), r12), new n("PullRequestReview", d0Shadow.n("PullRequestReview"), r14), new n("PullRequestReviewComment", d0Shadow.n("PullRequestReviewComment"), r15), new n("Release", d0Shadow.n("Release"), r16), new n("Repository", d0Shadow.n("Repository"), r17), new n("RepositoryAdvisory", d0Shadow.n("RepositoryAdvisory"), r18), new n("RepositoryAdvisoryComment", d0Shadow.n("RepositoryAdvisoryComment"), r19), new n("TeamDiscussion", d0Shadow.n("TeamDiscussion"), r22), new n("TeamDiscussionComment", d0Shadow.n("TeamDiscussionComment"), r23)});
    }
}
