package dk0;

import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.x;
import aa.x0;
import f1.e;
import gn0.c9;
import gn0.eq;
import gn0.hd;
import gn0.hr;
import gn0.jt;
import gn0.ju;
import gn0.kg;
import gn0.lb;
import gn0.lu;
import gn0.mx;
import gn0.nk;
import gn0.pb;
import gn0.pt;
import gn0.pu;
import gn0.tb;
import java.util.List;
import k71.k;
import sy.d0Shadow;
import v8.l0;
import vd0.b;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class a {
    public static final List a;

    static {
        pb.Companion.getClass();
        x xVar = pb.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar2 = tb.a;
        List r = l.r(new m[]{mVar, new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar2 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar3 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hr.Companion.getClass();
        List r2 = l.r(new m[]{mVar2, mVar3, new m("owner", l0.b(hr.a), (String) null, rVar, rVar, r), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar4 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("Label");
        List list = rg0.a.a;
        List r3 = l.r(new s[]{mVar4, no.a.c(list, "selections", "Label", n, list), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar3 = lb.a;
        m mVar7 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hd.Companion.getClass();
        q0 q0Var = hd.a;
        k.g(q0Var, "type");
        List r4 = l.r(new m[]{mVar5, mVar6, mVar7, mVar8, new m("label", q0Var, (String) null, rVar, rVar, r3)});
        List n2 = d0Shadow.n(new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar));
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar10 = new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        s mVar11 = new m("url", l0.b(mx.a), (String) null, rVar, rVar, rVar);
        List r5 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = b.a;
        List r6 = l.r(new s[]{mVar9, mVar10, mVar11, no.a.c(list2, "selections", "Actor", r5, list2)});
        k.g(xVar2, "type");
        List r7 = l.r(new m[]{new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        k.g(xVar2, "type");
        m mVar12 = new m("name", xVar2, (String) null, rVar, rVar, rVar);
        k.g(xVar2, "type");
        List r8 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("Node", l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"}), n2), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), r6), new n("User", d0Shadow.n("User"), r7), new n("Organization", d0Shadow.n("Organization"), l.r(new m[]{mVar12, new m("descriptionHTML", xVar2, (String) null, rVar, rVar, rVar), new m("viewerIsFollowing", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)}))});
        m mVar13 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar15 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        lu.Companion.getClass();
        x0 x0Var = lu.a;
        k.g(x0Var, "type");
        List r9 = l.r(new m[]{mVar13, mVar14, mVar15, mVar16, new m("loginRef", x0Var, (String) null, rVar, rVar, r8)});
        s mVar17 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("Milestone");
        List list3 = nh0.a.a;
        List r10 = l.r(new s[]{mVar17, no.a.c(list3, "selections", "Milestone", n3, list3), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar18 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar19 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar21 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        kg.Companion.getClass();
        q0 q0Var2 = kg.a;
        k.g(q0Var2, "type");
        List r12 = l.r(new m[]{mVar18, mVar19, mVar20, mVar21, new m("milestone", q0Var2, (String) null, rVar, rVar, r10)});
        s mVar22 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n4 = d0Shadow.n("Repository");
        List list4 = pj0.l.a;
        List r13 = l.r(new s[]{mVar22, no.a.c(list4, "selections", "Repository", n4, list4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar23 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar26 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        q0 q0Var3 = eq.m0;
        k.g(q0Var3, "type");
        List r14 = l.r(new m[]{mVar23, mVar24, mVar25, mVar26, new m("repository", q0Var3, (String) null, rVar, rVar, r13)});
        s mVar27 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n5 = d0Shadow.n("DiscussionCategory");
        List list5 = xf0.a.a;
        List r15 = l.r(new s[]{mVar27, no.a.c(list5, "selections", "DiscussionCategory", n5, list5), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar28 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar29 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar31 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        c9.Companion.getClass();
        q0 q0Var4 = c9.a;
        k.g(q0Var4, "type");
        List r16 = l.r(new m[]{mVar28, mVar29, mVar30, mVar31, new m("discussionCategory", q0Var4, (String) null, rVar, rVar, r15)});
        s mVar32 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n6 = d0Shadow.n("Project");
        List list6 = mi0.a.a;
        List r17 = l.r(new s[]{mVar32, no.a.c(list6, "selections", "Project", n6, list6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar33 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar34 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar35 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar36 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        nk.Companion.getClass();
        q0 q0Var5 = nk.a;
        k.g(q0Var5, "type");
        List r18 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("SearchShortcutQueryLabelTerm", d0Shadow.n("SearchShortcutQueryLabelTerm"), r4), new n("SearchShortcutQueryLoginRefTerm", d0Shadow.n("SearchShortcutQueryLoginRefTerm"), r9), new n("SearchShortcutQueryMilestoneTerm", d0Shadow.n("SearchShortcutQueryMilestoneTerm"), r12), new n("SearchShortcutQueryRepoTerm", d0Shadow.n("SearchShortcutQueryRepoTerm"), r14), new n("SearchShortcutQueryCategoryTerm", d0Shadow.n("SearchShortcutQueryCategoryTerm"), r16), new n("SearchShortcutQueryProjectTerm", d0Shadow.n("SearchShortcutQueryProjectTerm"), l.r(new m[]{mVar33, mVar34, mVar35, mVar36, new m("project", q0Var5, (String) null, rVar, rVar, r17)})), new n("SearchShortcutQueryTerm", d0Shadow.n("SearchShortcutQueryTerm"), l.r(new m[]{new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new n("SearchShortcutQueryText", d0Shadow.n("SearchShortcutQueryText"), d0Shadow.n(new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar)))});
        jt.Companion.getClass();
        m mVar37 = new m("color", l0.b(jt.s), (String) null, rVar, rVar, rVar);
        pt.Companion.getClass();
        m mVar38 = new m("icon", l0.b(pt.s), (String) null, rVar, rVar, rVar);
        m mVar39 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar40 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar41 = new m("query", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        k.g(q0Var3, "type");
        m mVar42 = new m("scopingRepository", q0Var3, (String) null, rVar, rVar, r2);
        pu.Companion.getClass();
        m mVar43 = new m("searchType", l0.b(pu.s), (String) null, rVar, rVar, rVar);
        ju.Companion.getClass();
        a = l.r(new m[]{mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, new m("queryTerms", e.e(ju.a), (String) null, rVar, rVar, r18), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
