package z70;

import hc0.ff;
import hc0.fm;
import hc0.nl;
import java.time.ZonedDateTime;
import java.util.ArrayList;

/* loaded from: /home/user/work/p/classes3.dex */
public final class l5 implements aa.h0 {
    public final b4 A;
    public final String B;
    public final i4 C;
    public final String D;
    public final o4 E;
    public final a5 F;
    public final e5 G;
    public final l4 H;
    public final k4 I;
    public final ArrayList J;
    public final int K;
    public final g4 L;
    public final i5 M;
    public final boolean N;
    public final boolean O;
    public final boolean P;
    public final boolean Q;
    public final c40.c R;
    public final i80.c S;
    public final g70.a T;
    public final i30.i U;
    public final c60.j V;
    public final i60.e W;
    public final aa0.a X;
    public final l7 Y;
    public final b Z;
    public final String a;
    public final String b;
    public final String c;
    public final String d;
    public final j4 e;
    public final c4 f;
    public final String g;
    public final String h;
    public final ZonedDateTime i;
    public final boolean j;
    public final boolean k;
    public final boolean l;
    public final a4 m;
    public final Boolean n;
    public final String o;
    public final int p;
    public final fm q;
    public final int r;
    public final int s;
    public final int t;
    public final ff u;
    public final n4 v;
    public final m4 w;
    public final nl x;
    public final boolean y;
    public final d5 z;

    public l5(String str, String str2, String str3, String str4, j4 j4Var, c4 c4Var, String str5, String str6, ZonedDateTime zonedDateTime, boolean z, boolean z2, boolean z3, a4 a4Var, Boolean bool, String str7, int i, fm fmVar, int i2, int i3, int i4, ff ffVar, n4 n4Var, m4 m4Var, nl nlVar, boolean z4, d5 d5Var, b4 b4Var, String str8, i4 i4Var, String str9, o4 o4Var, a5 a5Var, e5 e5Var, l4 l4Var, k4 k4Var, ArrayList arrayList, int i5, g4 g4Var, i5 i5Var, boolean z5, boolean z6, boolean z7, boolean z8, c40.c cVar, i80.c cVar2, g70.a aVar, i30.i iVar, c60.j jVar, i60.e eVar, aa0.a aVar2, l7 l7Var, b bVar) {
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = str4;
        this.e = j4Var;
        this.f = c4Var;
        this.g = str5;
        this.h = str6;
        this.i = zonedDateTime;
        this.j = z;
        this.k = z2;
        this.l = z3;
        this.m = a4Var;
        this.n = bool;
        this.o = str7;
        this.p = i;
        this.q = fmVar;
        this.r = i2;
        this.s = i3;
        this.t = i4;
        this.u = ffVar;
        this.v = n4Var;
        this.w = m4Var;
        this.x = nlVar;
        this.y = z4;
        this.z = d5Var;
        this.A = b4Var;
        this.B = str8;
        this.C = i4Var;
        this.D = str9;
        this.E = o4Var;
        this.F = a5Var;
        this.G = e5Var;
        this.H = l4Var;
        this.I = k4Var;
        this.J = arrayList;
        this.K = i5;
        this.L = g4Var;
        this.M = i5Var;
        this.N = z5;
        this.O = z6;
        this.P = z7;
        this.Q = z8;
        this.R = cVar;
        this.S = cVar2;
        this.T = aVar;
        this.U = iVar;
        this.V = jVar;
        this.W = eVar;
        this.X = aVar2;
        this.Y = l7Var;
        this.Z = bVar;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof l5)) {
            return false;
        }
        l5 l5Var = (l5) obj;
        return this.a.equals(l5Var.a) && this.b.equals(l5Var.b) && this.c.equals(l5Var.c) && this.d.equals(l5Var.d) && k71.k.b(this.e, l5Var.e) && k71.k.b(this.f, l5Var.f) && this.g.equals(l5Var.g) && this.h.equals(l5Var.h) && this.i.equals(l5Var.i) && this.j == l5Var.j && this.k == l5Var.k && this.l == l5Var.l && k71.k.b(this.m, l5Var.m) && k71.k.b(this.n, l5Var.n) && this.o.equals(l5Var.o) && this.p == l5Var.p && this.q == l5Var.q && this.r == l5Var.r && this.s == l5Var.s && this.t == l5Var.t && this.u == l5Var.u && k71.k.b(this.v, l5Var.v) && k71.k.b(this.w, l5Var.w) && this.x == l5Var.x && this.y == l5Var.y && this.z.equals(l5Var.z) && k71.k.b(this.A, l5Var.A) && this.B.equals(l5Var.B) && k71.k.b(this.C, l5Var.C) && this.D.equals(l5Var.D) && k71.k.b(this.E, l5Var.E) && this.F.equals(l5Var.F) && k71.k.b(this.G, l5Var.G) && k71.k.b(this.H, l5Var.H) && k71.k.b(this.I, l5Var.I) && this.J.equals(l5Var.J) && this.K == l5Var.K && this.L.equals(l5Var.L) && k71.k.b(this.M, l5Var.M) && this.N == l5Var.N && this.O == l5Var.O && this.P == l5Var.P && this.Q == l5Var.Q && this.R.equals(l5Var.R) && this.S.equals(l5Var.S) && this.T.equals(l5Var.T) && this.U.equals(l5Var.U) && this.V.equals(l5Var.V) && this.W.equals(l5Var.W) && this.X.equals(l5Var.X) && this.Y.equals(l5Var.Y) && this.Z.equals(l5Var.Z);
    }

    public final int hashCode() {
        int i = com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(this.a.hashCode() * 31, this.b, 31), this.c, 31), this.d, 31);
        j4 j4Var = this.e;
        int hashCode = (i + (j4Var == null ? 0 : j4Var.hashCode())) * 31;
        c4 c4Var = this.f;
        int e = x.i.e(x.i.e(x.i.e(com.github.rudroid.m0.a(this.i, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i((hashCode + (c4Var == null ? 0 : c4Var.hashCode())) * 31, this.g, 31), this.h, 31), 31), 31, this.j), 31, this.k), 31, this.l);
        a4 a4Var = this.m;
        int hashCode2 = (e + (a4Var == null ? 0 : a4Var.hashCode())) * 31;
        Boolean bool = this.n;
        int hashCode3 = (this.u.hashCode() + a0.s0.b(this.t, a0.s0.b(this.s, a0.s0.b(this.r, (this.q.hashCode() + a0.s0.b(this.p, com.github.rudroid.copilot.h1.i((hashCode2 + (bool == null ? 0 : bool.hashCode())) * 31, this.o, 31), 31)) * 31, 31), 31), 31)) * 31;
        n4 n4Var = this.v;
        int hashCode4 = (hashCode3 + (n4Var == null ? 0 : n4Var.hashCode())) * 31;
        m4 m4Var = this.w;
        int hashCode5 = (hashCode4 + (m4Var == null ? 0 : m4Var.hashCode())) * 31;
        nl nlVar = this.x;
        int hashCode6 = (this.z.hashCode() + x.i.e((hashCode5 + (nlVar == null ? 0 : nlVar.hashCode())) * 31, 31, this.y)) * 31;
        b4 b4Var = this.A;
        int i2 = com.github.rudroid.copilot.h1.i((hashCode6 + (b4Var == null ? 0 : b4Var.hashCode())) * 31, this.B, 31);
        i4 i4Var = this.C;
        int i3 = com.github.rudroid.copilot.h1.i((i2 + (i4Var == null ? 0 : i4Var.hashCode())) * 31, this.D, 31);
        o4 o4Var = this.E;
        int hashCode7 = (this.F.hashCode() + ((i3 + (o4Var == null ? 0 : o4Var.hashCode())) * 31)) * 31;
        e5 e5Var = this.G;
        int hashCode8 = (hashCode7 + (e5Var == null ? 0 : e5Var.hashCode())) * 31;
        l4 l4Var = this.H;
        int hashCode9 = (hashCode8 + (l4Var == null ? 0 : l4Var.hashCode())) * 31;
        k4 k4Var = this.I;
        int hashCode10 = (this.L.hashCode() + a0.s0.b(this.K, no.a.b(this.J, (hashCode9 + (k4Var == null ? 0 : k4Var.hashCode())) * 31, 31), 31)) * 31;
        i5 i5Var = this.M;
        return this.Z.hashCode() + ((this.Y.hashCode() + ((this.X.hashCode() + ((this.W.hashCode() + ((this.V.hashCode() + ((this.U.hashCode() + ((this.T.hashCode() + ((this.S.hashCode() + ((this.R.hashCode() + x.i.e(x.i.e(x.i.e(x.i.e((hashCode10 + (i5Var != null ? i5Var.hashCode() : 0)) * 31, 31, this.N), 31, this.O), 31, this.P), 31, this.Q)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder o = a0.s0.o("RepositoryNodeFragmentPullRequest(__typename=", this.a, ", url=", this.b, ", id=");
        f1.e.x(o, this.c, ", headRefOid=", this.d, ", headRepository=");
        o.append(this.e);
        o.append(", baseRepository=");
        o.append(this.f);
        o.append(", title=");
        f1.e.x(o, this.g, ", titleHTML=", this.h, ", createdAt=");
        com.github.rudroid.m0.v(", viewerCanDeleteHeadRef=", ", viewerDidAuthor=", o, this.i, this.j);
        com.github.rudroid.m0.A(o, this.k, ", locked=", this.l, ", author=");
        o.append(this.m);
        o.append(", isReadByViewer=");
        o.append(this.n);
        o.append(", bodyHtml=");
        a0.s0.w(this.p, this.o, ", number=", ", pullRequestState=", o);
        o.append(this.q);
        o.append(", changedFiles=");
        o.append(this.r);
        o.append(", additions=");
        a0.s0.z(o, this.s, ", deletions=", this.t, ", mergeStateStatus=");
        o.append(this.u);
        o.append(", mergedBy=");
        o.append(this.v);
        o.append(", mergeCommit=");
        o.append(this.w);
        o.append(", reviewDecision=");
        o.append(this.x);
        o.append(", isDraft=");
        o.append(this.y);
        o.append(", requiredStatusChecks=");
        o.append(this.z);
        o.append(", baseRef=");
        o.append(this.A);
        o.append(", baseRefName=");
        o.append(this.B);
        o.append(", headRef=");
        o.append(this.C);
        o.append(", headRefName=");
        o.append(this.D);
        o.append(", milestone=");
        o.append(this.E);
        o.append(", projectCards=");
        o.append(this.F);
        o.append(", reviewRequests=");
        o.append(this.G);
        o.append(", latestReviews=");
        o.append(this.H);
        o.append(", latestOpinionatedReviews=");
        o.append(this.I);
        o.append(", suggestedReviewers=");
        o.append(this.J);
        o.append(", actionRequiredWorkflowRunCount=");
        o.append(this.K);
        o.append(", commits=");
        o.append(this.L);
        o.append(", viewerLatestReview=");
        o.append(this.M);
        o.append(", viewerCanReopen=");
        o.append(this.N);
        o.append(", viewerCanMergeAsAdmin=");
        com.github.rudroid.m0.A(o, this.O, ", viewerCanAssign=", this.P, ", viewerCanLabel=");
        o.append(this.Q);
        o.append(", commentFragment=");
        o.append(this.R);
        o.append(", reactionFragment=");
        o.append(this.S);
        o.append(", orgBlockableFragment=");
        o.append(this.T);
        o.append(", assigneeFragment=");
        o.append(this.U);
        o.append(", labelsFragment=");
        o.append(this.V);
        o.append(", linkedIssues=");
        o.append(this.W);
        o.append(", updatableFields=");
        o.append(this.X);
        o.append(", viewerLatestReviewRequestFragment=");
        o.append(this.Y);
        o.append(", autoMergeRequestFragment=");
        o.append(this.Z);
        o.append(")");
        return o.toString();
    }
}
