package jh;

import a0.s0;
import com.github.rudroid.copilot.h1;
import d2.t;
import f1.e;
import x.i;

/* loaded from: /home/user/work/p/classes3.dex */
public final class d {
    public long A;
    public long A0;
    public long B;
    public long B0;
    public long C;
    public long C0;
    public long D;
    public long D0;
    public long E;
    public long E0;
    public long F;
    public long F0;
    public long G;
    public long G0;
    public long H;
    public long H0;
    public long I;
    public long I0;
    public long J;
    public long J0;
    public long K;
    public long K0;
    public long L;
    public long L0;
    public long M;
    public long M0;
    public long N;
    public long N0;
    public long O;
    public long O0;
    public long P;
    public long P0;
    public long Q;
    public long Q0;
    public long R;
    public long R0;
    public long S;
    public long S0;
    public long T;
    public long T0;
    public long U;
    public long U0;
    public long V;
    public long V0;
    public long W;
    public long W0;
    public long X;
    public long X0;
    public long Y;
    public long Y0;
    public long Z;
    public long Z0;
    public long a;
    public long a0;
    public long a1;
    public long b;
    public long b0;
    public long b1;
    public long c;
    public long c0;
    public long c1;
    public long d;
    public long d0;
    public long d1;
    public long e;
    public long e0;
    public long e1;
    public long f;
    public long f0;
    public long f1;
    public long g;
    public long g0;
    public long g1;
    public long h;
    public long h0;
    public long h1;
    public long i;
    public long i0;
    public long i1;
    public long j;
    public long j0;
    public long j1;
    public long k;
    public long k0;
    public long k1;
    public long l;
    public long l0;
    public long l1;
    public long m;
    public long m0;
    public long m1;
    public long n;
    public long n0;
    public long n1;
    public long o;
    public long o0;
    public long o1;
    public long p;
    public long p0;
    public long p1;
    public long q;
    public long q0;
    public long q1;
    public long r;
    public long r0;
    public long r1;
    public long s;
    public long s0;
    public long s1;
    public long t;
    public long t0;
    public long u;
    public long u0;
    public long v;
    public long v0;
    public long w;
    public long w0;
    public long x;
    public long x0;
    public long y;
    public long y0;
    public long z;
    public long z0;

    public d(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48, long j49, long j51, long j52, long j53, long j54, long j55, long j56, long j57, long j58, long j59, long j61, long j62, long j63, long j64, long j65, long j66, long j67, long j68, long j69, long j71, long j72, long j73, long j74, long j75, long j76, long j77, long j78, long j79, long j81, long j82, long j83, long j84, long j85, long j86, long j87, long j88, long j89, long j91, long j92, long j93, long j94, long j95, long j96, long j97, long j98, long j99, long j100, long j101, long j102, long j103, long j104, long j105, long j106, long j107, long j108, long j109, long j110, long j111, long j112, long j113, long j114, long j115, long j116, long j117, long j118, long j119, long j120, long j121, long j122, long j123, long j124, long j125, long j126, long j127, long j128, long j129, long j130, long j131, long j132) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j11;
        this.k = j12;
        this.l = j13;
        this.m = j14;
        this.n = j15;
        this.o = j16;
        this.p = j17;
        this.q = j18;
        this.r = j19;
        this.s = j21;
        this.t = j22;
        this.u = j23;
        this.v = j24;
        this.w = j25;
        this.x = j26;
        this.y = j27;
        this.z = j28;
        this.A = j29;
        this.B = j31;
        this.C = j32;
        this.D = j33;
        this.E = j34;
        this.F = j35;
        this.G = j36;
        this.H = j37;
        this.I = j38;
        this.J = j39;
        this.K = j41;
        this.L = j42;
        this.M = j43;
        this.N = j44;
        this.O = j45;
        this.P = j46;
        this.Q = j47;
        this.R = j48;
        this.S = j49;
        this.T = j51;
        this.U = j52;
        this.V = j53;
        this.W = j54;
        this.X = j55;
        this.Y = j56;
        this.Z = j57;
        this.a0 = j58;
        this.b0 = j59;
        this.c0 = j61;
        this.d0 = j62;
        this.e0 = j63;
        this.f0 = j64;
        this.g0 = j65;
        this.h0 = j66;
        this.i0 = j67;
        this.j0 = j68;
        this.k0 = j69;
        this.l0 = j71;
        this.m0 = j72;
        this.n0 = j73;
        this.o0 = j74;
        this.p0 = j75;
        this.q0 = j76;
        this.r0 = j77;
        this.s0 = j78;
        this.t0 = j79;
        this.u0 = j81;
        this.v0 = j82;
        this.w0 = j83;
        this.x0 = j84;
        this.y0 = j85;
        this.z0 = j86;
        this.A0 = j87;
        this.B0 = j88;
        this.C0 = j89;
        this.D0 = j91;
        this.E0 = j92;
        this.F0 = j93;
        this.G0 = j94;
        this.H0 = j95;
        this.I0 = j96;
        this.J0 = j97;
        this.K0 = j98;
        this.L0 = j99;
        this.M0 = j100;
        this.N0 = j101;
        this.O0 = j102;
        this.P0 = j103;
        this.Q0 = j104;
        this.R0 = j105;
        this.S0 = j106;
        this.T0 = j107;
        this.U0 = j108;
        this.V0 = j109;
        this.W0 = j110;
        this.X0 = j111;
        this.Y0 = j112;
        this.Z0 = j113;
        this.a1 = j114;
        this.b1 = j115;
        this.c1 = j116;
        this.d1 = j117;
        this.e1 = j118;
        this.f1 = j119;
        this.g1 = j120;
        this.h1 = j121;
        this.i1 = j122;
        this.j1 = j123;
        this.k1 = j124;
        this.l1 = j125;
        this.m1 = j126;
        this.n1 = j127;
        this.o1 = j128;
        this.p1 = j129;
        this.q1 = j130;
        this.r1 = j131;
        this.s1 = j132;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof d)) {
            return false;
        }
        d dVar = (d) obj;
        return t.c(this.a, dVar.a) && t.c(this.b, dVar.b) && t.c(this.c, dVar.c) && t.c(this.d, dVar.d) && t.c(this.e, dVar.e) && t.c(this.f, dVar.f) && t.c(this.g, dVar.g) && t.c(this.h, dVar.h) && t.c(this.i, dVar.i) && t.c(this.j, dVar.j) && t.c(this.k, dVar.k) && t.c(this.l, dVar.l) && t.c(this.m, dVar.m) && t.c(this.n, dVar.n) && t.c(this.o, dVar.o) && t.c(this.p, dVar.p) && t.c(this.q, dVar.q) && t.c(this.r, dVar.r) && t.c(this.s, dVar.s) && t.c(this.t, dVar.t) && t.c(this.u, dVar.u) && t.c(this.v, dVar.v) && t.c(this.w, dVar.w) && t.c(this.x, dVar.x) && t.c(this.y, dVar.y) && t.c(this.z, dVar.z) && t.c(this.A, dVar.A) && t.c(this.B, dVar.B) && t.c(this.C, dVar.C) && t.c(this.D, dVar.D) && t.c(this.E, dVar.E) && t.c(this.F, dVar.F) && t.c(this.G, dVar.G) && t.c(this.H, dVar.H) && t.c(this.I, dVar.I) && t.c(this.J, dVar.J) && t.c(this.K, dVar.K) && t.c(this.L, dVar.L) && t.c(this.M, dVar.M) && t.c(this.N, dVar.N) && t.c(this.O, dVar.O) && t.c(this.P, dVar.P) && t.c(this.Q, dVar.Q) && t.c(this.R, dVar.R) && t.c(this.S, dVar.S) && t.c(this.T, dVar.T) && t.c(this.U, dVar.U) && t.c(this.V, dVar.V) && t.c(this.W, dVar.W) && t.c(this.X, dVar.X) && t.c(this.Y, dVar.Y) && t.c(this.Z, dVar.Z) && t.c(this.a0, dVar.a0) && t.c(this.b0, dVar.b0) && t.c(this.c0, dVar.c0) && t.c(this.d0, dVar.d0) && t.c(this.e0, dVar.e0) && t.c(this.f0, dVar.f0) && t.c(this.g0, dVar.g0) && t.c(this.h0, dVar.h0) && t.c(this.i0, dVar.i0) && t.c(this.j0, dVar.j0) && t.c(this.k0, dVar.k0) && t.c(this.l0, dVar.l0) && t.c(this.m0, dVar.m0) && t.c(this.n0, dVar.n0) && t.c(this.o0, dVar.o0) && t.c(this.p0, dVar.p0) && t.c(this.q0, dVar.q0) && t.c(this.r0, dVar.r0) && t.c(this.s0, dVar.s0) && t.c(this.t0, dVar.t0) && t.c(this.u0, dVar.u0) && t.c(this.v0, dVar.v0) && t.c(this.w0, dVar.w0) && t.c(this.x0, dVar.x0) && t.c(this.y0, dVar.y0) && t.c(this.z0, dVar.z0) && t.c(this.A0, dVar.A0) && t.c(this.B0, dVar.B0) && t.c(this.C0, dVar.C0) && t.c(this.D0, dVar.D0) && t.c(this.E0, dVar.E0) && t.c(this.F0, dVar.F0) && t.c(this.G0, dVar.G0) && t.c(this.H0, dVar.H0) && t.c(this.I0, dVar.I0) && t.c(this.J0, dVar.J0) && t.c(this.K0, dVar.K0) && t.c(this.L0, dVar.L0) && t.c(this.M0, dVar.M0) && t.c(this.N0, dVar.N0) && t.c(this.O0, dVar.O0) && t.c(this.P0, dVar.P0) && t.c(this.Q0, dVar.Q0) && t.c(this.R0, dVar.R0) && t.c(this.S0, dVar.S0) && t.c(this.T0, dVar.T0) && t.c(this.U0, dVar.U0) && t.c(this.V0, dVar.V0) && t.c(this.W0, dVar.W0) && t.c(this.X0, dVar.X0) && t.c(this.Y0, dVar.Y0) && t.c(this.Z0, dVar.Z0) && t.c(this.a1, dVar.a1) && t.c(this.b1, dVar.b1) && t.c(this.c1, dVar.c1) && t.c(this.d1, dVar.d1) && t.c(this.e1, dVar.e1) && t.c(this.f1, dVar.f1) && t.c(this.g1, dVar.g1) && t.c(this.h1, dVar.h1) && t.c(this.i1, dVar.i1) && t.c(this.j1, dVar.j1) && t.c(this.k1, dVar.k1) && t.c(this.l1, dVar.l1) && t.c(this.m1, dVar.m1) && t.c(this.n1, dVar.n1) && t.c(this.o1, dVar.o1) && t.c(this.p1, dVar.p1) && t.c(this.q1, dVar.q1) && t.c(this.r1, dVar.r1) && t.c(this.s1, dVar.s1);
    }

    public final int hashCode() {
        int i = t.l;
        return Long.hashCode(this.s1) + i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(Long.hashCode(this.a) * 31, 31, this.b), 31, this.c), 31, this.d), 31, this.e), 31, this.f), 31, this.g), 31, this.h), 31, this.i), 31, this.j), 31, this.k), 31, this.l), 31, this.m), 31, this.n), 31, this.o), 31, this.p), 31, this.q), 31, this.r), 31, this.s), 31, this.t), 31, this.u), 31, this.v), 31, this.w), 31, this.x), 31, this.y), 31, this.z), 31, this.A), 31, this.B), 31, this.C), 31, this.D), 31, this.E), 31, this.F), 31, this.G), 31, this.H), 31, this.I), 31, this.J), 31, this.K), 31, this.L), 31, this.M), 31, this.N), 31, this.O), 31, this.P), 31, this.Q), 31, this.R), 31, this.S), 31, this.T), 31, this.U), 31, this.V), 31, this.W), 31, this.X), 31, this.Y), 31, this.Z), 31, this.a0), 31, this.b0), 31, this.c0), 31, this.d0), 31, this.e0), 31, this.f0), 31, this.g0), 31, this.h0), 31, this.i0), 31, this.j0), 31, this.k0), 31, this.l0), 31, this.m0), 31, this.n0), 31, this.o0), 31, this.p0), 31, this.q0), 31, this.r0), 31, this.s0), 31, this.t0), 31, this.u0), 31, this.v0), 31, this.w0), 31, this.x0), 31, this.y0), 31, this.z0), 31, this.A0), 31, this.B0), 31, this.C0), 31, this.D0), 31, this.E0), 31, this.F0), 31, this.G0), 31, this.H0), 31, this.I0), 31, this.J0), 31, this.K0), 31, this.L0), 31, this.M0), 31, this.N0), 31, this.O0), 31, this.P0), 31, this.Q0), 31, this.R0), 31, this.S0), 31, this.T0), 31, this.U0), 31, this.V0), 31, this.W0), 31, this.X0), 31, this.Y0), 31, this.Z0), 31, this.a1), 31, this.b1), 31, this.c1), 31, this.d1), 31, this.e1), 31, this.f1), 31, this.g1), 31, this.h1), 31, this.i1), 31, this.j1), 31, this.k1), 31, this.l1), 31, this.m1), 31, this.n1), 31, this.o1), 31, this.p1), 31, this.q1), 31, this.r1);
    }

    public final String toString() {
        String i = t.i(this.a);
        String i2 = t.i(this.b);
        String i3 = t.i(this.c);
        String i4 = t.i(this.d);
        String i5 = t.i(this.e);
        String i6 = t.i(this.f);
        String i7 = t.i(this.g);
        String i8 = t.i(this.h);
        String i9 = t.i(this.i);
        String i11 = t.i(this.j);
        String i12 = t.i(this.k);
        String i13 = t.i(this.l);
        String i14 = t.i(this.m);
        String i15 = t.i(this.n);
        String i16 = t.i(this.o);
        String i17 = t.i(this.p);
        String i18 = t.i(this.q);
        String i19 = t.i(this.r);
        String i21 = t.i(this.s);
        String i22 = t.i(this.t);
        String i23 = t.i(this.u);
        String i24 = t.i(this.v);
        String i25 = t.i(this.w);
        String i26 = t.i(this.x);
        String i27 = t.i(this.y);
        String i28 = t.i(this.z);
        String i29 = t.i(this.A);
        String i31 = t.i(this.B);
        String i32 = t.i(this.C);
        String i33 = t.i(this.D);
        String i34 = t.i(this.E);
        String i35 = t.i(this.F);
        String i36 = t.i(this.G);
        String i37 = t.i(this.H);
        String i38 = t.i(this.I);
        String i39 = t.i(this.J);
        String i41 = t.i(this.K);
        String i42 = t.i(this.L);
        String i43 = t.i(this.M);
        String i44 = t.i(this.N);
        String i45 = t.i(this.O);
        String i46 = t.i(this.P);
        String i47 = t.i(this.Q);
        String i48 = t.i(this.R);
        String i49 = t.i(this.S);
        String i51 = t.i(this.T);
        String i52 = t.i(this.U);
        String i53 = t.i(this.V);
        String i54 = t.i(this.W);
        String i55 = t.i(this.X);
        String i56 = t.i(this.Y);
        String i57 = t.i(this.Z);
        String i58 = t.i(this.a0);
        String i59 = t.i(this.b0);
        String i61 = t.i(this.c0);
        String i62 = t.i(this.d0);
        String i63 = t.i(this.e0);
        String i64 = t.i(this.f0);
        String i65 = t.i(this.g0);
        String i66 = t.i(this.h0);
        String i67 = t.i(this.i0);
        String i68 = t.i(this.j0);
        String i69 = t.i(this.k0);
        String i71 = t.i(this.l0);
        String i72 = t.i(this.m0);
        String i73 = t.i(this.n0);
        String i74 = t.i(this.o0);
        String i75 = t.i(this.p0);
        String i76 = t.i(this.q0);
        String i77 = t.i(this.r0);
        String i78 = t.i(this.s0);
        String i79 = t.i(this.t0);
        String i81 = t.i(this.u0);
        String i82 = t.i(this.v0);
        String i83 = t.i(this.w0);
        String i84 = t.i(this.x0);
        String i85 = t.i(this.y0);
        String i86 = t.i(this.z0);
        String i87 = t.i(this.A0);
        String i88 = t.i(this.B0);
        String i89 = t.i(this.C0);
        String i91 = t.i(this.D0);
        String i92 = t.i(this.E0);
        String i93 = t.i(this.F0);
        String i94 = t.i(this.G0);
        String i95 = t.i(this.H0);
        String i96 = t.i(this.I0);
        String i97 = t.i(this.J0);
        String i98 = t.i(this.K0);
        String i99 = t.i(this.L0);
        String i100 = t.i(this.M0);
        String i101 = t.i(this.N0);
        String i102 = t.i(this.O0);
        String i103 = t.i(this.P0);
        String i104 = t.i(this.Q0);
        String i105 = t.i(this.R0);
        String i106 = t.i(this.S0);
        String i107 = t.i(this.T0);
        String i108 = t.i(this.U0);
        String i109 = t.i(this.V0);
        String i110 = t.i(this.W0);
        String i111 = t.i(this.X0);
        String i112 = t.i(this.Y0);
        String i113 = t.i(this.Z0);
        String i114 = t.i(this.a1);
        String i115 = t.i(this.b1);
        String i116 = t.i(this.c1);
        String i117 = t.i(this.d1);
        String i118 = t.i(this.e1);
        String i119 = t.i(this.f1);
        String i120 = t.i(this.g1);
        String i121 = t.i(this.h1);
        String i122 = t.i(this.i1);
        String i123 = t.i(this.j1);
        String i124 = t.i(this.k1);
        String i125 = t.i(this.l1);
        String i126 = t.i(this.m1);
        String i127 = t.i(this.n1);
        String i128 = t.i(this.o1);
        String i129 = t.i(this.p1);
        String i130 = t.i(this.q1);
        String i131 = t.i(this.r1);
        String i132 = t.i(this.s1);
        StringBuilder o = s0.o("GitHubFunctionalColors(backgroundPrimary=", i, ", backgroundSecondary=", i2, ", backgroundElevatedPrimary=");
        e.x(o, i3, ", backgroundElevatedSecondary=", i4, ", backgroundElevatedSecondaryInverse=");
        e.x(o, i5, ", backgroundTertiary=", i6, ", backgroundElevatedTertiary=");
        e.x(o, i7, ", backgroundInset=", i8, ", backgroundBlue=");
        e.x(o, i9, ", backgroundInverted=", i11, ", codeViewLineNumbersBackground=");
        e.x(o, i12, ", codeViewLineNumbersBorder=", i13, ", codeViewBackground=");
        e.x(o, i14, ", menuButtonOtherBackground=", i15, ", headerBackground=");
        e.x(o, i16, ", border=", i17, ", borderBlue=");
        e.x(o, i18, ", filterBarItemBackgroundInactive=", i19, ", textPrimary=");
        e.x(o, i21, ", textSecondary=", i22, ", textError=");
        e.x(o, i23, ", textTertiary=", i24, ", textTertiaryElevated=");
        e.x(o, i25, ", textPlaceholder=", i26, ", textInverted=");
        e.x(o, i27, ", iconPrimary=", i28, ", iconSecondary=");
        e.x(o, i29, ", iconSecondaryForBackgroundElevatedSecondary=", i31, ", destructiveButtonDisabled=");
        e.x(o, i32, ", destructiveButtonEnabled=", i33, ", ripple=");
        e.x(o, i34, ", link=", i35, ", linkHighContrast=");
        e.x(o, i36, ", disabledLink=", i37, ", barOfActionStroke=");
        e.x(o, i38, ", barOfActionBackground=", i39, ", actionsAvatarBackground=");
        e.x(o, i41, ", outlinedTextFieldBackground=", i42, ", branchSelector=");
        e.x(o, i43, ", shadow=", i44, ", snackbarTextColor=");
        e.x(o, i45, ", snackbarActionTextColor=", i46, ", snackbarBackgroundColor=");
        e.x(o, i47, ", preferenceTrack=", i48, ", lineBackgroundGreen=");
        e.x(o, i49, ", lineBackgroundRed=", i51, ", lineBackgroundBlue=");
        e.x(o, i52, ", lineNumberBackgroundGreen=", i53, ", lineNumberBackgroundRed=");
        e.x(o, i54, ", lineNumberBackgroundBlue=", i55, ", lineNumberForegroundGreen=");
        e.x(o, i56, ", lineNumberForegroundRed=", i57, ", lineNumberForegroundBlue=");
        e.x(o, i58, ", insetProjectMetadataBackground=", i59, ", disabledButtonText=");
        e.x(o, i61, ", userMessageBackground=", i62, ", copilotAvatarBackground=");
        e.x(o, i63, ", backgroundListItemSelected=", i64, ", progressIndicatorTrack=");
        e.x(o, i65, ", gradientHeaderBackgroundStart=", i66, ", repoBannerBackground=");
        e.x(o, i67, ", metadataLabelDefaultBackground=", i68, ", filterBarCellBackgroundInactive=");
        e.x(o, i69, ", filterBarCellBorderInactive=", i71, ", filterBarCellTextInactive=");
        e.x(o, i72, ", filterBarCellIconInactive=", i73, ", filterBarCellBackgroundActive=");
        e.x(o, i74, ", filterBarCellBorderActive=", i75, ", filterBarCellTextActive=");
        e.x(o, i76, ", filterBarCellIconActive=", i77, ", redBadge=");
        e.x(o, i78, ", redBadgeBackground=", i79, ", redBadgeStroke=");
        e.x(o, i81, ", yellowBadge=", i82, ", yellowBadgeBackground=");
        e.x(o, i83, ", yellowBadgeStroke=", i84, ", purpleBadge=");
        e.x(o, i85, ", purpleBadgeBackground=", i86, ", purpleBadgeStroke=");
        e.x(o, i87, ", blueBadge=", i88, ", blueBadgeBackground=");
        e.x(o, i89, ", blueBadgeStroke=", i91, ", grayBadge=");
        e.x(o, i92, ", grayBadgeBackground=", i93, ", grayBadgeStroke=");
        e.x(o, i94, ", greenBadge=", i95, ", greenBadgeBackground=");
        e.x(o, i96, ", greenBadgeStroke=", i97, ", defaultButtonGradientStart=");
        e.x(o, i98, ", defaultButtonGradientEnd=", i99, ", buttonActiveBackground=");
        e.x(o, i100, ", buttonBackground=", i101, ", primaryButtonGreen=");
        e.x(o, i102, ", primaryButtonBackgroundGray=", i103, ", primaryButtonForegroundGray=");
        e.x(o, i104, ", backgroundTertiaryStroke=", i105, ", navIconColor=");
        e.x(o, i106, ", navIconIndicatorColor=", i107, ", agentMentionText=");
        e.x(o, i108, ", agentMentionBackground=", i109, ", open=");
        e.x(o, i110, ", closedIssue=", i111, ", closedIssueNotReason=");
        e.x(o, i112, ", closedIssueDuplicate=", i113, ", closedPullRequest=");
        e.x(o, i114, ", merged=", i115, ", draft=");
        e.x(o, i116, ", shortcutForegroundColorGray=", i117, ", shortcutForegroundColorBlue=");
        e.x(o, i118, ", shortcutForegroundColorGreen=", i119, ", shortcutForegroundColorOrange=");
        e.x(o, i120, ", shortcutForegroundColorRed=", i121, ", shortcutForegroundColorPink=");
        e.x(o, i122, ", shortcutForegroundColorPurple=", i123, ", shortcutBackgroundColorGray=");
        e.x(o, i124, ", shortcutBackgroundColorBlue=", i125, ", shortcutBackgroundColorGreen=");
        e.x(o, i126, ", shortcutBackgroundColorOrange=", i127, ", shortcutBackgroundColorRed=");
        e.x(o, i128, ", shortcutBackgroundColorPink=", i129, ", shortcutBackgroundColorPurple=");
        e.x(o, i130, ", checkboxCheckedBackground=", i131, ", checkboxUncheckedBackground=");
        return h1.p(o, i132, ")");
    }
}
