package hv;

import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import aa.x0;
import java.util.List;
import m10.ah;
import m10.ay;
import m10.cc0;
import m10.ch;
import m10.dz;
import m10.eh;
import m10.gf;
import m10.hz;
import m10.i30;
import m10.l40;
import m10.mr;
import m10.na0;
import m10.qf;
import m10.sc;
import m10.sg;
import m10.sr;
import m10.uc;
import m10.ur;
import m10.ux;
import m10.wg;
import m10.wr;
import m10.yb0;
import m10.yx;
import m10.zy;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class f {
    public static final List a;

    static {
        eh.Companion.getClass();
        x xVar = eh.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        ah.Companion.getClass();
        x xVar2 = ah.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = d0.n("Repository");
        List list = ew.j.a;
        aa.s c = no.a.c(list, "selections", "Repository", n, list);
        List n2 = d0.n("Repository");
        List list2 = ew.b.a;
        List r3 = x61.l.r(new aa.s[]{mVar2, c, no.a.c(list2, "selections", "Repository", n2, list2), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar3 = new aa.m("endCursor", xVar, (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar3 = wg.a;
        List r4 = x61.l.r(new aa.m[]{mVar3, new aa.m("hasNextPage", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        cc0.Companion.getClass();
        x xVar4 = cc0.a;
        k71.k.g(xVar4, "type");
        List r5 = x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("ImageFileType", d0.n("ImageFileType"), d0.n(new aa.m("url", xVar4, (String) null, rVar, rVar, rVar)))});
        aa.m mVar4 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        gf.Companion.getClass();
        x0 x0Var = gf.a;
        k71.k.g(x0Var, "type");
        List r6 = x61.l.r(new aa.m[]{mVar4, new aa.m("fileType", x0Var, (String) null, rVar, rVar, r5)});
        List n3 = d0.n(new aa.m("gitUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar));
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"ImageFileType", "MarkdownFileType", "PdfFileType", "TextFileType"});
        List list3 = d.a;
        List r8 = x61.l.r(new aa.s[]{mVar5, no.a.c(list3, "selections", "File", r7, list3)});
        aa.m mVar6 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("isGenerated", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        na0.Companion.getClass();
        q0 q0Var = na0.a;
        k71.k.g(q0Var, "type");
        aa.m mVar8 = new aa.m("submodule", q0Var, (String) null, rVar, rVar, n3);
        ch.Companion.getClass();
        x xVar5 = ch.a;
        k71.k.g(xVar5, "type");
        List r9 = x61.l.r(new aa.m[]{mVar6, mVar7, mVar8, new aa.m("lineCount", xVar5, (String) null, rVar, rVar, rVar), new aa.m("fileType", x0Var, (String) null, rVar, rVar, r8)});
        aa.s mVar9 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n4 = d0.n("DiffLine");
        List list4 = fs.a.a;
        List r11 = x61.l.r(new aa.s[]{mVar9, no.a.c(list4, "selections", "DiffLine", n4, list4)});
        aa.m mVar10 = new aa.m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar11 = new aa.m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        yb0.Companion.getClass();
        q0 q0Var2 = yb0.a;
        k71.k.g(q0Var2, "type");
        aa.m mVar12 = new aa.m("oldTreeEntry", q0Var2, (String) null, rVar, rVar, r6);
        aa.m mVar13 = new aa.m("newTreeEntry", q0Var2, (String) null, rVar, rVar, r9);
        uc.Companion.getClass();
        aa.m mVar14 = new aa.m("diffLines", l0.a(uc.a), (String) null, rVar, rVar, r11);
        aa.m mVar15 = new aa.m("isBinary", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("isLargeDiff", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.m mVar17 = new aa.m("isSubmodule", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        wr.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("status", l0.b(wr.s), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        mr.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", l0.b(mr.a), (String) null, rVar, rVar, r4);
        sr.Companion.getClass();
        List r13 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", l0.a(sr.b), (String) null, rVar, rVar, r12)});
        sg.Companion.getClass();
        x xVar6 = sg.a;
        k71.k.g(xVar6, "type");
        aa.m mVar19 = new aa.m("baseCommitOid", xVar6, (String) null, rVar, rVar, rVar);
        aa.m mVar20 = new aa.m("headCommitOid", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        ur.Companion.getClass();
        aa.r b2 = l0.b(ur.a);
        sc.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{mVar19, mVar20, new aa.m("patches", b2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(sc.b, new u0(new aa.t("after"))), new aa.k(sc.c, new u0(50))}), r13)});
        List n5 = d0.n(new aa.m("totalCount", l0.b(xVar5), (String) null, rVar, rVar, rVar));
        aa.m mVar21 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        dz.Companion.getClass();
        aa.r b3 = l0.b(dz.a);
        zy.Companion.getClass();
        List n6 = d0.n(new aa.m("nodes", l0.a(zy.d), (String) null, rVar, rVar, x61.l.r(new aa.m[]{mVar21, new aa.m("comments", b3, (String) null, rVar, no.a.s(zy.a, new u0(1)), n5), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)})));
        qf.Companion.getClass();
        List r15 = x61.l.r(new aa.m[]{new aa.m("viewerViewedState", l0.b(qf.s), (String) null, rVar, rVar, rVar), new aa.m("path", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yx.Companion.getClass();
        List n7 = d0.n(new aa.m("nodes", l0.a(yx.a), (String) null, rVar, rVar, r15));
        aa.s mVar22 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("headRefOid", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("viewerCanEditFiles", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("baseRefName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("headRefName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("additions", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.s mVar29 = new aa.m("deletions", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        q0 q0Var3 = i30.w0;
        k71.k.g(q0Var3, "type");
        aa.s mVar30 = new aa.m("headRepository", q0Var3, (String) null, rVar, rVar, r);
        l40.Companion.getClass();
        j0 j0Var = l40.e;
        k71.k.g(j0Var, "type");
        aa.s mVar31 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar32 = new aa.m("repository", l0.b(q0Var3), (String) null, rVar, rVar, r3);
        q0 q0Var4 = sc.d;
        k71.k.g(q0Var4, "type");
        ux.Companion.getClass();
        aa.s mVar33 = new aa.m("diff", q0Var4, (String) null, rVar, no.a.s(ux.m, new u0(Boolean.TRUE)), r14);
        List n8 = d0.n("PullRequest");
        List list5 = e.a;
        aa.s c2 = no.a.c(list5, "selections", "PullRequest", n8, list5);
        hz.Companion.getClass();
        q0 q0Var5 = hz.a;
        k71.k.g(q0Var5, "type");
        aa.s mVar34 = new aa.m("reviews", q0Var5, "pendingReviews", rVar, x61.l.r(new aa.k[]{new aa.k(ux.F, new u0(1)), new aa.k(ux.G, new u0(d0.n("PENDING")))}), n6);
        ay.Companion.getClass();
        q0 q0Var6 = ay.a;
        k71.k.g(q0Var6, "type");
        a = x61.l.r(new aa.s[]{mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, c2, mVar34, new aa.m("files", q0Var6, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ux.n, new u0(new aa.t("after"))), new aa.k(ux.o, new u0(50))}), n7)});
    }
}
