package hv;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.b00;
import m10.cc0;
import m10.ch;
import m10.da0;
import m10.dy;
import m10.eh;
import m10.gh;
import m10.hy;
import m10.i30;
import m10.ia;
import m10.jz;
import m10.ki;
import m10.l40;
import m10.om;
import m10.p90;
import m10.sa;
import m10.sm;
import m10.ux;
import m10.wg;
import m10.x1;
import m10.y5;
import m10.ya0;
import m10.z1;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class i {
    public static final List a;

    static {
        eh.Companion.getClass();
        x xVar = eh.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        ah.Companion.getClass();
        x xVar2 = ah.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r3 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar2 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        ya0.Companion.getClass();
        a0 a0Var = ya0.s;
        k71.k.g(a0Var, "type");
        aa.m mVar4 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        ia.Companion.getClass();
        aa.m mVar5 = new aa.m("viewerSubscriptionTypes", l0.a(l0.b(ia.s)), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        j0 j0Var = l40.e;
        List r4 = x61.l.r(new aa.m[]{mVar2, mVar3, mVar4, mVar5, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r5 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar6, no.a.c(list, "selections", "Actor", r5, list)});
        ch.Companion.getClass();
        x xVar3 = ch.a;
        aa.m mVar7 = new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        x1.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar7, new aa.m("nodes", l0.a(x1.a), (String) null, rVar, rVar, r6)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        da0.Companion.getClass();
        List r8 = x61.l.r(new aa.m[]{mVar8, new aa.m("state", l0.b(da0.s), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar9 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        p90.Companion.getClass();
        q0 q0Var = p90.c;
        k71.k.g(q0Var, "type");
        List r9 = x61.l.r(new aa.m[]{mVar9, new aa.m("statusCheckRollup", q0Var, (String) null, rVar, rVar, r8), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar10 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        y5.Companion.getClass();
        List r11 = x61.l.r(new aa.m[]{mVar10, new aa.m("commit", l0.b(y5.j), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        dy.Companion.getClass();
        List n = d0.n(new aa.m("nodes", l0.a(dy.a), (String) null, rVar, rVar, r11));
        List n2 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r12 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("position", l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = d0.n("MergeQueue");
        List list2 = cu.c.a;
        List r13 = x61.l.r(new aa.s[]{mVar11, no.a.c(list2, "selections", "MergeQueue", n3, list2), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar12 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar4 = wg.a;
        aa.s mVar14 = new aa.m("isDraft", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar15 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        gh.Companion.getClass();
        aa.s mVar16 = new aa.m("titleHTML", l0.b(gh.a), "titleHTMLString", rVar, rVar, rVar);
        aa.s mVar17 = new aa.m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        aa.s mVar18 = new aa.m("createdAt", l0.b(sa.a), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        q0 q0Var2 = i30.w0;
        k71.k.g(q0Var2, "type");
        aa.s mVar19 = new aa.m("headRepository", q0Var2, (String) null, rVar, rVar, r);
        aa.s mVar20 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar21 = new aa.m("isReadByViewer", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list3 = mt.a.a;
        aa.s c = no.a.c(list3, "selections", "Labelable", r14, list3);
        b00.Companion.getClass();
        aa.s mVar23 = new aa.m("state", l0.b(b00.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4);
        cc0.Companion.getClass();
        aa.s mVar25 = new aa.m("url", l0.b(cc0.a), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        jz.Companion.getClass();
        a0 a0Var2 = jz.s;
        k71.k.g(a0Var2, "type");
        aa.s mVar27 = new aa.m("reviewDecision", a0Var2, (String) null, rVar, rVar, rVar);
        z1.Companion.getClass();
        aa.r b2 = l0.b(z1.a);
        ux.Companion.getClass();
        aa.s mVar28 = new aa.m("assignedActors", b2, (String) null, rVar, no.a.s(ux.a, new u0(25)), r7);
        hy.Companion.getClass();
        aa.s mVar29 = new aa.m("commits", l0.b(hy.a), (String) null, rVar, no.a.s(ux.l, new u0(1)), n);
        ki.Companion.getClass();
        q0 q0Var3 = ki.a;
        k71.k.g(q0Var3, "type");
        aa.s mVar30 = new aa.m("closingIssuesReferences", q0Var3, (String) null, rVar, rVar, n2);
        aa.s mVar31 = new aa.m("isInMergeQueue", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        sm.Companion.getClass();
        q0 q0Var4 = sm.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar32 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, r12);
        om.Companion.getClass();
        q0 q0Var5 = om.d;
        k71.k.g(q0Var5, "type");
        aa.s mVar33 = new aa.m("mergeQueue", q0Var5, (String) null, rVar, rVar, r13);
        List n4 = d0.n("PullRequest");
        List list4 = s.a;
        a = x61.l.r(new aa.s[]{mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, c, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, no.a.c(list4, "selections", "PullRequest", n4, list4)});
    }

    public static List a() {
        return a;
    }
}
