package hv;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import m10.a00;
import m10.ab0;
import m10.ah;
import m10.b00;
import m10.bb0;
import m10.bc0;
import m10.bh;
import m10.bh0;
import m10.cb0;
import m10.cc0;
import m10.ch;
import m10.ch0;
import m10.cn;
import m10.da0;
import m10.dh;
import m10.dy;
import m10.eh;
import m10.fh;
import m10.g1;
import m10.gh;
import m10.h1;
import m10.h30;
import m10.h4;
import m10.hy;
import m10.hz;
import m10.i30;
import m10.iz;
import m10.j10;
import m10.jz;
import m10.k50;
import m10.l50;
import m10.m50;
import m10.n10;
import m10.n50;
import m10.o90;
import m10.om;
import m10.p90;
import m10.q90;
import m10.r90;
import m10.ra;
import m10.rz;
import m10.s90;
import m10.sa;
import m10.sg;
import m10.sm;
import m10.t3;
import m10.t90;
import m10.tg0;
import m10.tx;
import m10.u3;
import m10.ux;
import m10.v3;
import m10.vg;
import m10.w50;
import m10.w90;
import m10.wg;
import m10.wm;
import m10.x5;
import m10.x50;
import m10.x90;
import m10.y5;
import m10.y50;
import m10.z50;
import m10.za0;
import m10.zg;
import m10.zy;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class p {
    public static final List a;

    static {
        ah.Companion.getClass();
        aa.r b = l0.b(zg.a());
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        List o = d0Shadow.o(mVar, new aa.m("nameWithOwner", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        List o2 = d0Shadow.o(new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("nameWithOwner", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar2 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar3 = new aa.m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o3 = d0Shadow.o("Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User");
        List a2 = fq.b.a();
        List o4 = d0Shadow.o(mVar2, mVar3, no.a.c(a2, "selections", "Actor", o3, a2));
        aa.s mVar4 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o5 = d0Shadow.o("Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile");
        List a3 = wx.a.a();
        List o6 = d0Shadow.o(mVar4, no.a.c(a3, "selections", "Node", o5, a3), new aa.m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar5 = new aa.m("abbreviatedOid", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        List o7 = d0Shadow.o(mVar5, new aa.m("committedDate", l0.b(ra.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar6 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("MergeQueue");
        List list = cu.c.a;
        List o8 = d0Shadow.o(mVar6, no.a.c(list, "selections", "MergeQueue", n, list), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar7 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List n2 = d0Shadow.n("MergeQueueEntry");
        List list2 = cu.b.a;
        List o9 = d0Shadow.o(mVar7, no.a.c(list2, "selections", "MergeQueueEntry", n2, list2), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar8 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("context", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        da0.Companion.getClass();
        a0 a0Var = da0.s;
        aa.m mVar10 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        x a4 = dh.a();
        k71.k.g(a4, "type");
        List o11 = d0Shadow.o(mVar8, mVar9, mVar10, new aa.m("description", a4, (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        ch.Companion.getClass();
        aa.m mVar11 = new aa.m("totalCount", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        l50.Companion.getClass();
        List o12 = d0Shadow.o(mVar11, new aa.m("nodes", l0.a(k50.a()), (String) null, rVar, rVar, o11));
        x a5 = bh.a();
        k71.k.g(a5, "type");
        aa.m mVar12 = new aa.m("recommendedApprovingReviewCount", a5, (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        List o13 = d0Shadow.o(mVar12, new aa.m("requiresCodeOwnerReviews", l0.b(vg.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerAllowedToDismissReviews", l0.b(vg.a()), (String) null, rVar, rVar, rVar));
        n10.Companion.getClass();
        q0 q0Var = n10.a;
        k71.k.g(q0Var, "type");
        List o14 = d0Shadow.o(new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, o13), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        List n3 = d0Shadow.n(new aa.m("viewerCanPush", l0.b(vg.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar13 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        List o15 = d0Shadow.o(mVar13, new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, n3), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar14 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List n4 = d0Shadow.n("Milestone");
        List list3 = gu.a.a;
        List o16 = d0Shadow.o(mVar14, no.a.c(list3, "selections", "Milestone", n4, list3), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar15 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List n5 = d0Shadow.n("ReviewRequest");
        List a6 = lw.a.a();
        List o17 = d0Shadow.o(mVar15, no.a.c(a6, "selections", "ReviewRequest", n5, a6), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        x50.Companion.getClass();
        List n6 = d0Shadow.n(new aa.m("nodes", l0.a(w50.a()), (String) null, rVar, rVar, o17));
        aa.s mVar16 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List n7 = d0Shadow.n("PullRequestReview");
        List list4 = mv.b.a;
        List o18 = d0Shadow.o(mVar16, no.a.c(list4, "selections", "PullRequestReview", n7, list4), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar));
        zy.Companion.getClass();
        q0 q0Var2 = zy.d;
        List n8 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, o18));
        List n9 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, d0Shadow.o(new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar), no.a.c(list4, "selections", "PullRequestReview", d0Shadow.n("PullRequestReview"), list4), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar))));
        aa.s mVar17 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar18 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar19 = new aa.m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o19 = d0Shadow.o("Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User");
        List a7 = fq.b.a();
        List o21 = d0Shadow.o(mVar17, mVar18, mVar19, no.a.c(a7, "selections", "Actor", o19, a7));
        aa.s mVar20 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("login", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("displayName", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("isCopilot", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        aa.s mVar25 = new aa.m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        List o22 = d0Shadow.o("Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User");
        List a8 = fq.b.a();
        List o23 = d0Shadow.o(mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, no.a.c(a8, "selections", "Actor", o22, a8));
        aa.s mVar26 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o24 = d0Shadow.o("Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile");
        List a9 = wx.a.a();
        List o25 = d0Shadow.o(mVar26, no.a.c(a9, "selections", "Node", o24, a9), new aa.m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar), new aa.n("User", d0Shadow.n("User"), o21), new aa.n("Bot", d0Shadow.n("Bot"), o23));
        aa.m mVar27 = new aa.m("isAuthor", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar28 = new aa.m("isCommenter", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        m10.l.Companion.getClass();
        List o26 = d0Shadow.o(mVar27, mVar28, new aa.m("reviewer", l0.b(m10.k.a()), (String) null, rVar, rVar, o25));
        ab0.Companion.getClass();
        List n11 = d0Shadow.n(new aa.m("nodes", l0.a(za0.a()), (String) null, rVar, rVar, o26));
        aa.m mVar29 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar30 = new aa.m("context", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar31 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        x a11 = bc0.a();
        k71.k.g(a11, "type");
        aa.m mVar32 = new aa.m("avatarUrl", a11, (String) null, rVar, rVar, rVar);
        x a12 = dh.a();
        k71.k.g(a12, "type");
        aa.m mVar33 = new aa.m("description", a12, (String) null, rVar, rVar, rVar);
        x a13 = bc0.a();
        k71.k.g(a13, "type");
        aa.m mVar34 = new aa.m("targetUrl", a13, (String) null, rVar, rVar, rVar);
        aa.r b2 = l0.b(vg.a());
        x90.Companion.getClass();
        w90.a();
        List o27 = d0Shadow.o(mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(x90.b, new u0(new aa.t("numberNullableBug"))), rVar));
        List o28 = d0Shadow.o(new aa.m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        tg0.Companion.getClass();
        List o29 = d0Shadow.o(new aa.m("workflow", l0.b(tg0.e), (String) null, rVar, rVar, o28), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        List o31 = d0Shadow.o(new aa.m("logoUrl", l0.b(bc0.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        ch0.Companion.getClass();
        q0 a14 = bh0.a();
        k71.k.g(a14, "type");
        aa.m mVar35 = new aa.m("workflowRun", a14, (String) null, rVar, rVar, o29);
        h1.Companion.getClass();
        q0 a15 = g1.a();
        k71.k.g(a15, "type");
        List o32 = d0Shadow.o(mVar35, new aa.m("app", a15, (String) null, rVar, rVar, o31), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar36 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        a0 a0Var2 = t3.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar37 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar38 = new aa.m("name", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar39 = new aa.m("duration", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        x a16 = dh.a();
        k71.k.g(a16, "type");
        aa.m mVar40 = new aa.m("summary", a16, (String) null, rVar, rVar, rVar);
        aa.m mVar41 = new aa.m("permalink", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        h4.Companion.getClass();
        aa.m mVar42 = new aa.m("checkSuite", l0.b(h4.f), (String) null, rVar, rVar, o32);
        aa.r b3 = l0.b(vg.a());
        v3.Companion.getClass();
        u3.a();
        List o33 = d0Shadow.o(new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", d0Shadow.n("StatusContext"), o27), new aa.n("CheckRun", d0Shadow.n("CheckRun"), d0Shadow.o(mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(v3.b, new u0(new aa.t("numberNullableBug"))), rVar))));
        aa.m mVar43 = new aa.m("totalCount", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        r90.Companion.getClass();
        List o34 = d0Shadow.o(mVar43, new aa.m("nodes", l0.a(q90.a()), (String) null, rVar, rVar, o33));
        aa.m mVar44 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar45 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        t90.Companion.getClass();
        aa.r b4 = l0.b(s90.a());
        p90.Companion.getClass();
        o90.b();
        List o35 = d0Shadow.o(mVar44, mVar45, new aa.m("contexts", b4, (String) null, rVar, no.a.s(p90.b, new u0(100)), o34), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar46 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar47 = new aa.m("committedDate", l0.b(ra.a()), (String) null, rVar, rVar, rVar);
        q0 a17 = o90.a();
        k71.k.g(a17, "type");
        List o36 = d0Shadow.o(mVar46, mVar47, new aa.m("statusCheckRollup", a17, (String) null, rVar, rVar, o35), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar48 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        y5.Companion.getClass();
        List o37 = d0Shadow.o(mVar48, new aa.m("commit", l0.b(x5.a()), (String) null, rVar, rVar, o36), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar49 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar50 = new aa.m("totalCount", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        dy.Companion.getClass();
        List o38 = d0Shadow.o(mVar49, mVar50, new aa.m("nodes", l0.a(dy.a), (String) null, rVar, rVar, o37));
        rz.Companion.getClass();
        aa.m mVar51 = new aa.m("state", l0.b(rz.s), (String) null, rVar, rVar, rVar);
        x a18 = ra.a();
        k71.k.g(a18, "type");
        List o39 = d0Shadow.o(mVar51, new aa.m("submittedAt", a18, (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar52 = new aa.m("__typename", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar53 = new aa.m("url", l0.b(bc0.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar54 = new aa.m("id", l0.b(zg.a()), (String) null, rVar, rVar, rVar);
        sg.Companion.getClass();
        aa.s mVar55 = new aa.m("headRefOid", l0.b(sg.a), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        q0 a19 = h30.a();
        k71.k.g(a19, "type");
        aa.s mVar56 = new aa.m("headRepository", a19, (String) null, rVar, rVar, o);
        q0 a21 = h30.a();
        k71.k.g(a21, "type");
        aa.s mVar57 = new aa.m("baseRepository", a21, (String) null, rVar, rVar, o2);
        aa.s mVar58 = new aa.m("title", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        gh.Companion.getClass();
        aa.s mVar59 = new aa.m("titleHTML", l0.b(fh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar60 = new aa.m("createdAt", l0.b(ra.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar61 = new aa.m("viewerCanDeleteHeadRef", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar62 = new aa.m("viewerDidAuthor", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar63 = new aa.m("viewerCanChangeBaseBranch", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar64 = new aa.m("locked", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        j0 a22 = m10.k.a();
        k71.k.g(a22, "type");
        aa.s mVar65 = new aa.m("author", a22, (String) null, rVar, rVar, o4);
        x a23 = vg.a();
        k71.k.g(a23, "type");
        aa.s mVar66 = new aa.m("isReadByViewer", a23, (String) null, rVar, rVar, rVar);
        aa.r b5 = l0.b(fh.a());
        ux.Companion.getClass();
        tx.b();
        a81.t tVar = ux.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        tx.c();
        aa.k kVar2 = new aa.k(ux.c, new u0(bool));
        tx.d();
        aa.k kVar3 = new aa.k(ux.d, new u0(bool));
        tx.e();
        a81.t tVar2 = ux.e;
        Boolean bool2 = Boolean.FALSE;
        aa.k kVar4 = new aa.k(tVar2, new u0(bool2));
        tx.f();
        aa.k kVar5 = new aa.k(ux.f, new u0(bool2));
        tx.g();
        aa.s mVar67 = new aa.m("bodyHTML", b5, "bodyHtml", rVar, d0Shadow.o(kVar, kVar2, kVar3, kVar4, kVar5, new aa.k(ux.g, new u0(bool))), rVar);
        aa.s mVar68 = new aa.m("number", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        List o41 = d0Shadow.o("CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment");
        List list5 = br.a.a;
        aa.s c = no.a.c(list5, "selections", "Comment", o41, list5);
        List o42 = d0Shadow.o("CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment");
        List list6 = qv.a.a;
        aa.s c2 = no.a.c(list6, "selections", "Reactable", o42, list6);
        List o43 = d0Shadow.o("CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment");
        List list7 = qu.a.a;
        aa.s c3 = no.a.c(list7, "selections", "OrgBlockable", o43, list7);
        List o44 = d0Shadow.o("Issue", "PullRequest");
        List list8 = hq.b.a;
        aa.s c4 = no.a.c(list8, "selections", "Assignable", o44, list8);
        b00.Companion.getClass();
        aa.s mVar69 = new aa.m("state", l0.b(a00.a()), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar70 = new aa.m("changedFiles", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar71 = new aa.m("additions", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar72 = new aa.m("deletions", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        wm.Companion.getClass();
        aa.s mVar73 = new aa.m("mergeStateStatus", l0.b(wm.s), (String) null, rVar, rVar, rVar);
        j0 a24 = m10.k.a();
        k71.k.g(a24, "type");
        aa.s mVar74 = new aa.m("mergedBy", a24, (String) null, rVar, rVar, o6);
        q0 a25 = x5.a();
        k71.k.g(a25, "type");
        aa.s mVar75 = new aa.m("mergeCommit", a25, (String) null, rVar, rVar, o7);
        om.Companion.getClass();
        q0 q0Var3 = om.d;
        k71.k.g(q0Var3, "type");
        aa.s mVar76 = new aa.m("mergeQueue", q0Var3, (String) null, rVar, rVar, o8);
        sm.Companion.getClass();
        q0 q0Var4 = sm.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar77 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, o9);
        jz.Companion.getClass();
        a0 a26 = iz.a();
        k71.k.g(a26, "type");
        aa.s mVar78 = new aa.m("reviewDecision", a26, (String) null, rVar, rVar, rVar);
        aa.s mVar79 = new aa.m("isDraft", l0.b(vg.a()), (String) null, rVar, rVar, rVar);
        n50.Companion.getClass();
        aa.r b6 = l0.b(m50.a());
        tx.l();
        aa.s mVar80 = new aa.m("requiredStatusChecks", b6, (String) null, rVar, no.a.s(ux.C, new u0(25)), o12);
        j10.Companion.getClass();
        q0 q0Var5 = j10.e;
        k71.k.g(q0Var5, "type");
        aa.s mVar81 = new aa.m("baseRef", q0Var5, (String) null, rVar, rVar, o14);
        aa.s mVar82 = new aa.m("baseRefName", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var5, "type");
        aa.s mVar83 = new aa.m("headRef", q0Var5, (String) null, rVar, rVar, o15);
        aa.s mVar84 = new aa.m("headRefName", l0.b(dh.a()), (String) null, rVar, rVar, rVar);
        List o45 = d0Shadow.o("Discussion", "Issue", "PullRequest");
        List list9 = mt.a.a;
        aa.s c5 = no.a.c(list9, "selections", "Labelable", o45, list9);
        cn.Companion.getClass();
        q0 q0Var6 = cn.a;
        k71.k.g(q0Var6, "type");
        aa.s mVar85 = new aa.m("milestone", q0Var6, (String) null, rVar, rVar, o16);
        z50.Companion.getClass();
        q0 a27 = y50.a();
        k71.k.g(a27, "type");
        tx.m();
        aa.s mVar86 = new aa.m("reviewRequests", a27, (String) null, rVar, no.a.s(ux.D, new u0(25)), n6);
        hz.Companion.getClass();
        q0 q0Var7 = hz.a;
        k71.k.g(q0Var7, "type");
        tx.k();
        aa.s mVar87 = new aa.m("latestReviews", q0Var7, (String) null, rVar, no.a.s(ux.s, new u0(25)), n8);
        k71.k.g(q0Var7, "type");
        tx.i();
        aa.k kVar6 = new aa.k(ux.q, new u0(25));
        tx.j();
        aa.s mVar88 = new aa.m("latestOpinionatedReviews", q0Var7, (String) null, rVar, d0Shadow.o(kVar6, new aa.k(ux.r, new u0(bool))), n9);
        cb0.Companion.getClass();
        aa.r b7 = l0.b(bb0.a());
        tx.n();
        aa.s mVar89 = new aa.m("suggestedReviewerActors", b7, (String) null, rVar, no.a.s(ux.H, new u0(10)), n11);
        aa.s mVar90 = new aa.m("actionRequiredWorkflowRunCount", l0.b(bh.a()), (String) null, rVar, rVar, rVar);
        hy.Companion.getClass();
        aa.r b8 = l0.b(hy.a);
        tx.h();
        aa.s mVar91 = new aa.m("commits", b8, (String) null, rVar, no.a.s(ux.l, new u0(1)), o38);
        List n12 = d0Shadow.n("PullRequest");
        List a28 = st.a.a();
        aa.s c6 = no.a.c(a28, "selections", "PullRequest", n12, a28);
        List o46 = d0Shadow.o("CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment");
        List list10 = nx.a.a;
        aa.s c7 = no.a.c(list10, "selections", "Updatable", o46, list10);
        List n13 = d0Shadow.n("PullRequest");
        List a29 = r.a();
        aa.s c8 = no.a.c(a29, "selections", "PullRequest", n13, a29);
        k71.k.g(q0Var2, "type");
        aa.s mVar92 = new aa.m("viewerLatestReview", q0Var2, (String) null, rVar, rVar, o39);
        List n14 = d0Shadow.n("PullRequest");
        List list11 = a.a;
        a = d0Shadow.o(mVar52, mVar53, mVar54, mVar55, mVar56, mVar57, mVar58, mVar59, mVar60, mVar61, mVar62, mVar63, mVar64, mVar65, mVar66, mVar67, mVar68, c, c2, c3, c4, mVar69, mVar70, mVar71, mVar72, mVar73, mVar74, mVar75, mVar76, mVar77, mVar78, mVar79, mVar80, mVar81, mVar82, mVar83, mVar84, c5, mVar85, mVar86, mVar87, mVar88, mVar89, mVar90, mVar91, c6, c7, c8, mVar92, no.a.c(list11, "selections", "PullRequest", n14, list11), new aa.m("viewerCanReopen", l0.b(vg.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanMergeAsAdmin", l0.b(vg.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanAssign", l0.b(vg.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanLabel", l0.b(vg.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanUpdateBranch", l0.b(vg.a()), (String) null, rVar, rVar, rVar));
    }
}
