package hv;

import aa.q0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.eh;
import m10.fz;
import m10.rf0;
import m10.t5;
import m10.tz;
import m10.wg;
import m10.zy;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class q {
    public static final List a;

    static {
        ah.Companion.getClass();
        x xVar = ah.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        x xVar2 = eh.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r3 = x61.l.r(new String[]{"FileComment", "IndeterminateComment", "LineComment", "MultilineComment"});
        List list = b.a;
        List r4 = x61.l.r(new aa.s[]{mVar2, no.a.c(list, "selections", "CommentPosition", r3, list)});
        aa.s mVar3 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar4 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar3 = wg.a;
        aa.s mVar5 = new aa.m("isResolved", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        rf0.Companion.getClass();
        q0 q0Var = rf0.g0;
        k71.k.g(q0Var, "type");
        aa.s mVar6 = new aa.m("resolvedBy", q0Var, (String) null, rVar, rVar, r2);
        aa.s mVar7 = new aa.m("viewerCanResolve", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar8 = new aa.m("viewerCanUnresolve", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        t5.Companion.getClass();
        aa.s mVar9 = new aa.m("positioning", l0.b(t5.a), (String) null, rVar, rVar, r4);
        List n = d0.n("PullRequestReviewThread");
        List list2 = ov.a.a;
        List r5 = x61.l.r(new aa.s[]{mVar3, mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, no.a.c(list2, "selections", "PullRequestReviewThread", n, list2)});
        aa.s mVar10 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar11 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        x xVar4 = ch.a;
        k71.k.g(xVar4, "type");
        aa.s mVar12 = new aa.m("position", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("startLine", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("line", xVar4, (String) null, rVar, rVar, rVar);
        zy.Companion.getClass();
        q0 q0Var2 = zy.d;
        k71.k.g(q0Var2, "type");
        aa.s mVar15 = new aa.m("pullRequestReview", q0Var2, (String) null, rVar, rVar, r);
        tz.Companion.getClass();
        q0 q0Var3 = tz.e;
        k71.k.g(q0Var3, "type");
        aa.s mVar16 = new aa.m("thread", q0Var3, (String) null, rVar, rVar, r5);
        aa.s mVar17 = new aa.m("path", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        fz.Companion.getClass();
        aa.s mVar18 = new aa.m("state", l0.b(fz.s), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        aa.s mVar19 = new aa.m("url", l0.b(cc0.a), (String) null, rVar, rVar, rVar);
        List r6 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list3 = br.a.a;
        aa.s c = no.a.c(list3, "selections", "Comment", r6, list3);
        List r7 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list4 = qv.a.a;
        aa.s c2 = no.a.c(list4, "selections", "Reactable", r7, list4);
        List r8 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list5 = nx.b.a;
        aa.s c3 = no.a.c(list5, "selections", "Updatable", r8, list5);
        List r9 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list6 = qu.a.a;
        aa.s c4 = no.a.c(list6, "selections", "OrgBlockable", r9, list6);
        List r11 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"});
        List list7 = ku.a.a;
        a = x61.l.r(new aa.s[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, c, c2, c3, c4, no.a.c(list7, "selections", "Minimizable", r11, list7)});
    }
}
