package ih;

import y41.t1;

/* loaded from: /home/user/work/p/classes3.dex */
public final class a {
    public static final float A;
    public static final float B;
    public static final float C;
    public static final float D;
    public static final float E;
    public static final float F;
    public static final float G;
    public static final float I;
    public static final float K;
    public static final float L;
    public static final float M;
    public static final float N;
    public static final float O;
    public static final float b;
    public static final float c;
    public static final float e;
    public static final float f;
    public static final float g;
    public static final float h;
    public static final float i;
    public static final float k;
    public static final float l;
    public static final float m;
    public static final float n;
    public static final float o;
    public static final float p;
    public static final float q;
    public static final float r;
    public static final float s;
    public static final float t;
    public static final float u;
    public static final float v;
    public static final float w;
    public static final float x;
    public static final float a = 6;
    public static final float d = (float) 0.2d;
    public static final float j = 2;
    public static final float y = 36;
    public static final float z = 40;
    public static final long H = t1.C(16);
    public static final float J = 372;
    public static final float P = 56;
    public static final int Q = Integer.MAX_VALUE;

    static {
        float f2 = 12;
        b = f2;
        float f3 = 1;
        c = f3;
        float f4 = 0;
        e = f4;
        f = f3;
        float f5 = 24;
        g = f5;
        float f6 = 8;
        h = f6;
        i = f4;
        float f7 = 4;
        k = f7;
        l = f6;
        m = f2;
        float f8 = 16;
        n = f8;
        float f9 = 20;
        o = f9;
        p = f5;
        float f11 = 32;
        q = f11;
        float f12 = 96;
        r = f12;
        float f13 = 72;
        s = f13;
        float f14 = 64;
        t = f14;
        u = f8;
        v = f9;
        w = f5;
        x = f11;
        float f15 = 44;
        A = f15;
        float f16 = 48;
        B = f16;
        C = f14;
        D = f7;
        E = f7;
        F = f15;
        G = f12;
        I = f13;
        K = f16;
        L = f2;
        M = f8;
        N = f5;
        O = f11;
    }
}
