package f50;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.x;
import hc0.ap;
import hc0.bb;
import hc0.c9;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.fq;
import hc0.h6;
import hc0.p3;
import hc0.q8;
import hc0.w8;
import hc0.xa;
import hc0.y8;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class e {
    public static final List a;

    static {
        bb.Companion.getClass();
        x xVar = bb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar2 = fb.a;
        List r = l.r(new m[]{mVar, new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar2 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar3 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        m mVar4 = new m("owner", l0.b(dq.a), (String) null, rVar, rVar, r);
        fq.Companion.getClass();
        a0 a0Var = fq.s;
        k.g(a0Var, "type");
        m mVar5 = new m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar3 = xa.a;
        List r2 = l.r(new m[]{mVar2, mVar3, mVar4, mVar5, new m("isOrganizationDiscussionRepository", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r3 = l.r(new m[]{new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar6 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar7 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        w8.Companion.getClass();
        q0 q0Var = w8.c;
        k.g(q0Var, "type");
        s mVar8 = new m("replyTo", q0Var, (String) null, rVar, rVar, r3);
        List n = d0.n("DiscussionComment");
        List list = j50.b.a;
        List r4 = l.r(new s[]{mVar6, mVar7, mVar8, no.a.c(list, "selections", "DiscussionComment", n, list)});
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("DiscussionCategory");
        List list2 = h50.a.a;
        List r5 = l.r(new s[]{mVar9, no.a.c(list2, "selections", "DiscussionCategory", n2, list2), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List n3 = d0.n(new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar));
        s mVar10 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r6 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list3 = f30.a.a;
        List r7 = l.r(new s[]{mVar10, no.a.c(list3, "selections", "Actor", r6, list3), new n("Node", l.r(new String[]{"Achievement", "AchievementTier", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"}), n3)});
        db.Companion.getClass();
        x xVar4 = db.a;
        List n4 = d0.n(new m("totalCount", l0.b(xVar4), (String) null, rVar, rVar, rVar));
        s mVar11 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n5 = d0.n("DiscussionPoll");
        List list4 = l50.b.a;
        List r8 = l.r(new s[]{mVar11, no.a.c(list4, "selections", "DiscussionPoll", n5, list4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        s mVar12 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar13 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar14 = new m("title", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        x xVar5 = h6.a;
        s mVar15 = new m("updatedAt", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        s mVar16 = new m("createdAt", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        s mVar17 = new m("lastEditedAt", xVar5, (String) null, rVar, rVar, rVar);
        s mVar18 = new m("number", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        s mVar19 = new m("viewerDidAuthor", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        s mVar20 = new m("viewerCanUpdate", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        s mVar21 = new m("viewerCanUpvote", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        p3.Companion.getClass();
        s mVar22 = new m("authorAssociation", l0.b(p3.s), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        s mVar23 = new m("url", l0.b(ew.a), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        s mVar24 = new m("repository", l0.b(ap.k0), (String) null, rVar, rVar, r2);
        s mVar25 = new m("answerChosenAt", xVar5, (String) null, rVar, rVar, rVar);
        s mVar26 = new m("answer", q0Var, (String) null, rVar, rVar, r4);
        q8.Companion.getClass();
        s mVar27 = new m("category", l0.b(q8.a), (String) null, rVar, rVar, r5);
        hc0.l.Companion.getClass();
        j0 j0Var = hc0.l.a;
        k.g(j0Var, "type");
        s mVar28 = new m("author", j0Var, (String) null, rVar, rVar, r7);
        y8.Companion.getClass();
        s mVar29 = new m("comments", l0.b(y8.a), (String) null, rVar, rVar, n4);
        c9.Companion.getClass();
        q0 q0Var2 = c9.b;
        k.g(q0Var2, "type");
        s mVar30 = new m("poll", q0Var2, (String) null, rVar, rVar, r8);
        List r9 = l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list5 = d60.a.a;
        s c = no.a.c(list5, "selections", "Labelable", r9, list5);
        List r11 = l.r(new String[]{"Discussion", "DiscussionComment"});
        List list6 = g.a;
        s c2 = no.a.c(list6, "selections", "Votable", r11, list6);
        List n6 = d0.n("Discussion");
        List list7 = b.a;
        a = l.r(new s[]{mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, c, c2, no.a.c(list7, "selections", "Discussion", n6, list7)});
    }
}
