package vu0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.aw;
import pz0.c90;
import pz0.cg;
import pz0.gw;
import pz0.h50;
import pz0.jx;
import pz0.ki;
import pz0.mv;
import pz0.ny;
import pz0.o7;
import pz0.ov;
import pz0.pd;
import pz0.py;
import pz0.rx;
import pz0.ry;
import pz0.td;
import pz0.vd;
import pz0.ve;
import pz0.vy;
import pz0.xd;
import pz0.xs;
import pz0.xy;
import pz0.z40;
import pz0.zd;
import pz0.zn;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class i {
    public static final List a;

    static {
        xd.Companion.getClass();
        x xVar = xd.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("Ref");
        List list = h.a;
        aa.s c = no.a.c(list, "selections", "Ref", n, list);
        td.Companion.getClass();
        x xVar2 = td.a;
        List r = x61.l.r(new aa.s[]{mVar, c, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Ref", d0Shadow.n("Ref"), list), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        vd.Companion.getClass();
        x xVar3 = vd.a;
        List n2 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar3 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar4 = new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r3 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = dp0.b.a;
        List r4 = x61.l.r(new aa.s[]{mVar2, mVar3, mVar4, no.a.c(list2, "selections", "Actor", r3, list2)});
        List n3 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List n4 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        zd.Companion.getClass();
        x xVar4 = zd.a;
        k71.k.g(xVar4, "type");
        List r5 = x61.l.r(new aa.m[]{new aa.m("contentHTML", xVar4, (String) null, rVar, rVar, rVar), new aa.m("path", xVar, (String) null, rVar, rVar, rVar)});
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        z40.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{new aa.m("topic", l0.b(z40.d), (String) null, rVar, rVar, r6), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        vy.Companion.getClass();
        List n5 = d0Shadow.n(new aa.m("nodes", l0.a(vy.a), (String) null, rVar, rVar, r7));
        List n6 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n7 = d0Shadow.n("License");
        List list3 = hs0.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar5, no.a.c(list3, "selections", "License", n7, list3), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar6 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        ny.Companion.getClass();
        j0 j0Var = ny.e;
        List r10 = x61.l.r(new aa.m[]{mVar6, mVar7, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List n8 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("name", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar10 = new aa.m("tagName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        x xVar5 = o7.a;
        k71.k.g(xVar5, "type");
        List r12 = x61.l.r(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("publishedAt", xVar5, (String) null, rVar, rVar, rVar), new aa.m("createdAt", l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n9 = d0Shadow.n("MergeQueue");
        List list4 = ts0.c.a;
        List r13 = x61.l.r(new aa.s[]{mVar11, no.a.c(list4, "selections", "MergeQueue", n9, list4), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List n10 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar12 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        x xVar6 = h50.a;
        List r14 = x61.l.r(new aa.m[]{mVar12, new aa.m("url", l0.b(xVar6), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        jx.Companion.getClass();
        q0 q0Var = jx.t0;
        List n12 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var), (String) null, rVar, rVar, r14));
        aa.s mVar13 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar15 = new aa.m("databaseId", xVar3, (String) null, rVar, rVar, rVar);
        List n13 = d0Shadow.n("Repository");
        List list5 = b.a;
        aa.s c2 = no.a.c(list5, "selections", "Repository", n13, list5);
        aa.s mVar16 = new aa.m("contributorsCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        mv.Companion.getClass();
        q0 q0Var2 = mv.e;
        k71.k.g(q0Var2, "type");
        aa.s mVar17 = new aa.m("defaultBranchRef", q0Var2, (String) null, d0Shadow.n(new aa.l("defaultBranch", false)), rVar, r);
        aa.s mVar18 = new aa.m("ref", q0Var2, "branchInfo", no.a.t("defaultBranch", true), no.a.s(jx.W, new u0(new aa.t("qualifiedName"))), r2);
        aa.s mVar19 = new aa.m("forkCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        x xVar7 = pd.a;
        aa.s mVar20 = new aa.m("hasIssuesEnabled", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("showActions", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("homepageUrl", xVar6, (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("isPrivate", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("isArchived", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("isTemplate", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("isFork", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("forkingAllowed", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("isEmpty", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar29 = new aa.m("isInOrganization", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        ve.Companion.getClass();
        aa.s mVar30 = new aa.m("issues", l0.b(ve.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(jx.t, new u0(0)), new aa.k(jx.u, new u0(d0Shadow.n("OPEN")))}), n2);
        aa.s mVar31 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar32 = new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r4);
        xs.Companion.getClass();
        aa.s mVar33 = new aa.m("pullRequests", l0.b(xs.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(jx.T, new u0(0)), new aa.k(jx.U, new u0(d0Shadow.n("OPEN")))}), n3);
        ov.Companion.getClass();
        q0 q0Var3 = ov.a;
        k71.k.g(q0Var3, "type");
        aa.s mVar34 = new aa.m("refs", q0Var3, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(jx.Y, new u0(0)), new aa.k(jx.b0, new u0("refs/heads/"))}), n4);
        ry.Companion.getClass();
        q0 q0Var4 = ry.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar35 = new aa.m("readme", q0Var4, (String) null, rVar, no.a.s(jx.V, new u0(new aa.t("branch"))), r5);
        xy.Companion.getClass();
        aa.s mVar36 = new aa.m("repositoryTopics", l0.b(xy.a), (String) null, rVar, no.a.s(jx.g0, new u0(6)), n5);
        aa.s mVar37 = new aa.m("url", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar38 = new aa.m("shortDescriptionHTML", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar39 = new aa.m("descriptionHTML", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar, "type");
        aa.s mVar40 = new aa.m("description", xVar, (String) null, rVar, rVar, rVar);
        aa.s mVar41 = new aa.m("viewerCanAdminister", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar42 = new aa.m("viewerCanPush", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar43 = new aa.m("viewerCanSubscribe", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        py.Companion.getClass();
        a0 a0Var = py.s;
        k71.k.g(a0Var, "type");
        aa.s mVar44 = new aa.m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar);
        c90.Companion.getClass();
        aa.s mVar45 = new aa.m("watchers", l0.b(c90.a), (String) null, rVar, no.a.s(jx.p0, new u0(0)), n6);
        cg.Companion.getClass();
        q0 q0Var5 = cg.a;
        k71.k.g(q0Var5, "type");
        aa.s mVar46 = new aa.m("licenseInfo", q0Var5, (String) null, rVar, rVar, r8);
        aa.s mVar47 = new aa.m("isDiscussionsEnabled", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar48 = new aa.m("discussionsCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        aa.s mVar49 = new aa.m("parent", q0Var, (String) null, rVar, rVar, r10);
        gw.Companion.getClass();
        aa.s mVar50 = new aa.m("releases", l0.b(gw.a), (String) null, rVar, no.a.s(jx.e0, new u0(0)), n8);
        List r15 = x61.l.r(new String[]{"Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team", "TeamDiscussion"});
        List list6 = ov0.a.a;
        aa.s c3 = no.a.c(list6, "selections", "Subscribable", r15, list6);
        aw.Companion.getClass();
        q0 q0Var6 = aw.e;
        k71.k.g(q0Var6, "type");
        aa.s mVar51 = new aa.m("latestRelease", q0Var6, (String) null, rVar, rVar, r12);
        List n14 = d0Shadow.n("Repository");
        List list7 = gw0.f.a;
        aa.s c4 = no.a.c(list7, "selections", "Repository", n14, list7);
        aa.s mVar52 = new aa.m("isViewersFavorite", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar53 = new aa.m("viewerHasBlockedContributors", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar54 = new aa.m("viewerBlockedByOwner", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        ki.Companion.getClass();
        q0 q0Var7 = ki.c;
        k71.k.g(q0Var7, "type");
        aa.s mVar55 = new aa.m("mergeQueue", q0Var7, (String) null, rVar, no.a.s(jx.D, new u0(new aa.t("branch"))), r13);
        List n15 = d0Shadow.n("Repository");
        List list8 = u.a;
        aa.s c5 = no.a.c(list8, "selections", "Repository", n15, list8);
        zn.Companion.getClass();
        aa.s mVar56 = new aa.m("projectsV2", l0.b(zn.a), (String) null, rVar, no.a.s(jx.P, new u0(0)), n10);
        List n16 = d0Shadow.n("Repository");
        List list9 = o.a;
        aa.s c6 = no.a.c(list9, "selections", "Repository", n16, list9);
        rx.Companion.getClass();
        a = x61.l.r(new aa.s[]{mVar13, mVar14, mVar15, c2, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, mVar48, mVar49, mVar50, c3, mVar51, c4, mVar52, mVar53, mVar54, mVar55, c5, mVar56, c6, new aa.m("forks", l0.b(rx.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(jx.n, new u0(d0Shadow.n("OWNER"))), new aa.k(jx.p, new u0(1))}), n12)});
    }
}
