package vu0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.bf;
import pz0.df;
import pz0.h50;
import pz0.le;
import pz0.mf;
import pz0.o7;
import pz0.pd;
import pz0.td;
import pz0.vd;
import pz0.xd;
import pz0.yi;
import pz0.zd;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class l {
    public static final List a;

    static {
        xd.Companion.getClass();
        x xVar = xd.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        aa.s mVar2 = new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.b.a;
        List r2 = x61.l.r(new aa.s[]{mVar, mVar2, no.a.c(list, "selections", "Actor", r, list)});
        aa.s mVar3 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("Milestone");
        List list2 = xs0.a.a;
        aa.s c = no.a.c(list2, "selections", "Milestone", n, list2);
        td.Companion.getClass();
        x xVar2 = td.a;
        List r3 = x61.l.r(new aa.s[]{mVar3, c, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n2 = d0Shadow.n("IssueType");
        List list3 = zr0.a.a;
        List r4 = x61.l.r(new aa.s[]{mVar4, no.a.c(list3, "selections", "IssueType", n2, list3), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        x xVar3 = h50.a;
        aa.s mVar6 = new aa.m("url", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar7 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar8 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar9 = new aa.m("titleHTML", l0.b(xVar), "titleHTMLString", rVar, rVar, rVar);
        o7.Companion.getClass();
        aa.s mVar10 = new aa.m("createdAt", l0.b(o7.a), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        x xVar4 = pd.a;
        aa.s mVar11 = new aa.m("viewerDidAuthor", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar12 = new aa.m("locked", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        pz0.l.Companion.getClass();
        j0 j0Var = pz0.l.a;
        k71.k.g(j0Var, "type");
        aa.s mVar13 = new aa.m("author", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar14 = new aa.m("isReadByViewer", xVar4, (String) null, rVar, rVar, rVar);
        zd.Companion.getClass();
        aa.r b2 = l0.b(zd.a);
        le.Companion.getClass();
        a81.t tVar = le.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        aa.k kVar2 = new aa.k(le.c, new u0(bool));
        aa.k kVar3 = new aa.k(le.d, new u0(bool));
        a81.t tVar2 = le.e;
        Boolean bool2 = Boolean.FALSE;
        aa.s mVar15 = new aa.m("bodyHTML", b2, "bodyHtml", rVar, x61.l.r(new aa.k[]{kVar, kVar2, kVar3, new aa.k(tVar2, new u0(bool2)), new aa.k(le.f, new u0(bool2)), new aa.k(le.g, new u0(bool))}), rVar);
        aa.s mVar16 = new aa.m("bodyUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        x xVar5 = vd.a;
        aa.s mVar17 = new aa.m("number", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        List r5 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list4 = zp0.a.a;
        aa.s c2 = no.a.c(list4, "selections", "Comment", r5, list4);
        List r6 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list5 = hu0.a.a;
        aa.s c3 = no.a.c(list5, "selections", "Reactable", r6, list5);
        List r7 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list6 = ht0.a.a;
        aa.s c4 = no.a.c(list6, "selections", "OrgBlockable", r7, list6);
        List r8 = x61.l.r(new String[]{"Issue", "PullRequest"});
        List list7 = fp0.b.a;
        aa.s c5 = no.a.c(list7, "selections", "Assignable", r8, list7);
        bf.Companion.getClass();
        aa.s mVar18 = new aa.m("state", l0.b(bf.s), "issueState", rVar, rVar, rVar);
        List r9 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list8 = ds0.a.a;
        aa.s c6 = no.a.c(list8, "selections", "Labelable", r9, list8);
        yi.Companion.getClass();
        q0 q0Var = yi.a;
        k71.k.g(q0Var, "type");
        aa.s mVar19 = new aa.m("milestone", q0Var, (String) null, rVar, rVar, r3);
        List n3 = d0Shadow.n("Issue");
        List list9 = js0.b.a;
        aa.s c7 = no.a.c(list9, "selections", "Issue", n3, list9);
        List r10 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list10 = cw0.a.a;
        aa.s c8 = no.a.c(list10, "selections", "Updatable", r10, list10);
        aa.r b3 = l0.b(xVar5);
        a81.t tVar3 = le.r;
        aa.s mVar20 = new aa.m("taskListItemCount", b3, "completeTaskListItemCount", rVar, no.a.s(tVar3, new u0(d0Shadow.n("COMPLETE"))), rVar);
        aa.s mVar21 = new aa.m("taskListItemCount", l0.b(xVar5), "incompleteTaskListItemCount", rVar, no.a.s(tVar3, new u0(d0Shadow.n("INCOMPLETE"))), rVar);
        aa.s mVar22 = new aa.m("viewerCanReopen", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        df.Companion.getClass();
        a0 a0Var = df.s;
        k71.k.g(a0Var, "type");
        aa.s mVar23 = new aa.m("stateReason", a0Var, (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("viewerCanAssign", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("viewerCanLabel", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("isPinned", xVar4, (String) null, rVar, rVar, rVar);
        mf.Companion.getClass();
        q0 q0Var2 = mf.a;
        k71.k.g(q0Var2, "type");
        aa.s mVar27 = new aa.m("issueType", q0Var2, (String) null, rVar, rVar, r4);
        List n4 = d0Shadow.n("Issue");
        List list11 = e.a;
        a = x61.l.r(new aa.s[]{mVar5, mVar6, mVar7, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, c2, c3, c4, c5, mVar18, c6, mVar19, c7, c8, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, no.a.c(list11, "selections", "Issue", n4, list11)});
    }
}
