package wo;

import aa.a0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.b4;
import m10.cc0;
import m10.ch;
import m10.eh;
import m10.h1;
import m10.h4;
import m10.i30;
import m10.j10;
import m10.l40;
import m10.ly;
import m10.mr;
import m10.n00;
import m10.n40;
import m10.r1;
import m10.t3;
import m10.ux;
import m10.v3;
import m10.wg;
import m10.x3;
import m10.y5;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class b {
    public static final List a;

    static {
        ch.Companion.getClass();
        x xVar = ch.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        List n = d0.n(new m("totalCount", b, (String) null, rVar, rVar, rVar));
        eh.Companion.getClass();
        x xVar2 = eh.a;
        s mVar = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.a.a;
        List r2 = l.r(new s[]{mVar, no.a.c(list, "selections", "Actor", r, list)});
        ah.Companion.getClass();
        x xVar3 = ah.a;
        m mVar2 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar3 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        m mVar4 = new m("owner", l0.b(l40.e), (String) null, rVar, rVar, r2);
        n40.Companion.getClass();
        a0 a0Var = n40.s;
        k71.k.g(a0Var, "type");
        List r3 = l.r(new m[]{mVar2, mVar3, mVar4, new m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r4 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)});
        m10.l.Companion.getClass();
        List r5 = l.r(new m[]{new m("pusher", l0.b(m10.l.a), (String) null, rVar, rVar, r4), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r7 = l.r(new m[]{new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("title", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ux.Companion.getClass();
        List n2 = d0.n(new m("nodes", l0.a(ux.T), (String) null, rVar, rVar, r7));
        m mVar5 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("abbreviatedOid", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ly.Companion.getClass();
        q0 q0Var = ly.a;
        k71.k.g(q0Var, "type");
        y5.Companion.getClass();
        List r8 = l.r(new m[]{mVar5, mVar6, new m("associatedPullRequests", q0Var, (String) null, rVar, no.a.s(y5.a, new u0(1)), n2), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar7 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        x xVar4 = cc0.a;
        List r9 = l.r(new m[]{mVar7, mVar8, new m("logoUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        wg.Companion.getClass();
        x xVar5 = wg.a;
        List r11 = l.r(new m[]{new m("hasNextPage", l0.b(xVar5), (String) null, rVar, rVar, rVar), new m("hasPreviousPage", l0.b(xVar5), (String) null, rVar, rVar, rVar), new m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0.n("CheckRun");
        List list2 = f.a;
        List r12 = l.r(new s[]{mVar9, no.a.c(list2, "selections", "CheckRun", n3, list2), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        m mVar10 = new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar);
        mr.Companion.getClass();
        m mVar11 = new m("pageInfo", l0.b(mr.a), (String) null, rVar, rVar, r11);
        v3.Companion.getClass();
        q0 q0Var2 = v3.f;
        List r13 = l.r(new m[]{mVar10, mVar11, new m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, r12)});
        List r14 = l.r(new m[]{new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("CheckRun", d0.n("CheckRun"), list2), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)}))});
        List n4 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n5 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n6 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n7 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        m mVar12 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        b4.Companion.getClass();
        m mVar13 = new m("status", l0.b(b4.s), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        a0 a0Var2 = t3.s;
        k71.k.g(a0Var2, "type");
        m mVar14 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        m mVar15 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("duration", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("event", xVar2, (String) null, rVar, rVar, rVar);
        r1.Companion.getClass();
        q0 q0Var3 = r1.a;
        k71.k.g(q0Var3, "type");
        m mVar18 = new m("artifacts", q0Var3, (String) null, rVar, rVar, n);
        i30.Companion.getClass();
        m mVar19 = new m("repository", l0.b(i30.w0), (String) null, rVar, rVar, r3);
        n00.Companion.getClass();
        q0 q0Var4 = n00.a;
        k71.k.g(q0Var4, "type");
        m mVar20 = new m("push", q0Var4, (String) null, rVar, rVar, r5);
        j10.Companion.getClass();
        q0 q0Var5 = j10.e;
        k71.k.g(q0Var5, "type");
        m mVar21 = new m("branch", q0Var5, (String) null, rVar, rVar, r6);
        m mVar22 = new m("commit", l0.b(y5.j), (String) null, rVar, rVar, r8);
        m mVar23 = new m("rerunnable", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        h1.Companion.getClass();
        q0 q0Var6 = h1.a;
        k71.k.g(q0Var6, "type");
        m mVar24 = new m("app", q0Var6, (String) null, rVar, rVar, r9);
        x3.Companion.getClass();
        q0 q0Var7 = x3.a;
        k71.k.g(q0Var7, "type");
        h4.Companion.getClass();
        aa.k kVar = new aa.k(h4.a, new u0(new t("afterCheckRuns")));
        a81.t tVar = h4.c;
        m mVar25 = new m("checkRuns", q0Var7, "checkRuns", rVar, l.r(new aa.k[]{kVar, new aa.k(tVar, new u0(new t("first")))}), r13);
        a81.t tVar2 = h4.b;
        a = l.r(new m[]{mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, new m("checkRuns", q0Var7, "failedCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", l.r(new String[]{"CANCELLED", "FAILURE", "TIMED_OUT", "ACTION_REQUIRED", "STALE", "STARTUP_FAILURE"})))), new aa.k(tVar, new u0(5))}), r14), new m("checkRuns", q0Var7, "runningCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("statuses", l.r(new String[]{"IN_PROGRESS", "PENDING", "QUEUED", "REQUESTED", "WAITING"})))), new aa.k(tVar, new u0(1))}), n4), new m("checkRuns", q0Var7, "skippedCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", d0.n("SKIPPED")))), new aa.k(tVar, new u0(1))}), n5), new m("checkRuns", q0Var7, "neutralCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", d0.n("NEUTRAL")))), new aa.k(tVar, new u0(1))}), n6), new m("checkRuns", q0Var7, "successfulCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", d0.n("SUCCESS")))), new aa.k(tVar, new u0(1))}), n7), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
