package xe0;

import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import aa.x0;
import gn0.bb;
import gn0.cw;
import gn0.d4;
import gn0.db;
import gn0.eq;
import gn0.ga;
import gn0.h4;
import gn0.hb;
import gn0.hn;
import gn0.hr;
import gn0.ix;
import gn0.lb;
import gn0.lj;
import gn0.ll;
import gn0.mx;
import gn0.n8;
import gn0.nj;
import gn0.p8;
import gn0.pb;
import gn0.pj;
import gn0.qv;
import gn0.r6;
import gn0.rb;
import gn0.s00;
import gn0.tb;
import gn0.vb;
import gn0.yv;
import gn0.zl;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class a {
    public static final List a;

    static {
        pb.Companion.getClass();
        x xVar = pb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar2 = tb.a;
        List r = l.r(new m[]{mVar, new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar2 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        hr.Companion.getClass();
        j0 j0Var = hr.a;
        List r2 = l.r(new m[]{mVar2, new m("owner", l0.b(j0Var), (String) null, rVar, rVar, r), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r3 = l.r(new m[]{new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar3 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        x xVar3 = mx.a;
        m mVar4 = new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar5 = new m("name", xVar2, (String) null, rVar, rVar, rVar);
        s00.Companion.getClass();
        q0 q0Var = s00.P;
        k.g(q0Var, "type");
        List r4 = l.r(new m[]{mVar3, mVar4, mVar5, new m("user", q0Var, (String) null, rVar, rVar, r3)});
        List r5 = l.r(new m[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("user", q0Var, (String) null, rVar, rVar, l.r(new m[]{new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        List r6 = l.r(new m[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("user", q0Var, (String) null, rVar, rVar, l.r(new m[]{new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        bb.Companion.getClass();
        q0 q0Var2 = bb.a;
        List n = d0.n(new m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, r6));
        List r7 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("ImageFileType", d0.n("ImageFileType"), d0.n(new m("url", xVar3, (String) null, rVar, rVar, rVar)))});
        m mVar6 = new m("path", xVar2, (String) null, rVar, rVar, rVar);
        ga.Companion.getClass();
        x0 x0Var = ga.a;
        k.g(x0Var, "type");
        List r8 = l.r(new m[]{mVar6, new m("fileType", x0Var, (String) null, rVar, rVar, r7)});
        List n2 = d0.n(new m("gitUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r9 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("ImageFileType", d0.n("ImageFileType"), d0.n(new m("url", xVar3, (String) null, rVar, rVar, rVar)))});
        m mVar7 = new m("path", xVar2, (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar4 = lb.a;
        m mVar8 = new m("isGenerated", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        cw.Companion.getClass();
        q0 q0Var3 = cw.a;
        k.g(q0Var3, "type");
        List r10 = l.r(new m[]{mVar7, mVar8, new m("submodule", q0Var3, (String) null, rVar, rVar, n2), new m("fileType", x0Var, (String) null, rVar, rVar, r9)});
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0.n("DiffLine");
        List list = rf0.a.a;
        List r12 = l.r(new s[]{mVar9, no.a.c(list, "selections", "DiffLine", n3, list)});
        rb.Companion.getClass();
        x xVar5 = rb.a;
        m mVar10 = new m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar11 = new m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        ix.Companion.getClass();
        q0 q0Var4 = ix.a;
        k.g(q0Var4, "type");
        m mVar12 = new m("oldTreeEntry", q0Var4, (String) null, rVar, rVar, r8);
        m mVar13 = new m("newTreeEntry", q0Var4, (String) null, rVar, rVar, r10);
        p8.Companion.getClass();
        m mVar14 = new m("diffLines", l0.a(p8.a), (String) null, rVar, rVar, r12);
        m mVar15 = new m("isBinary", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("isLargeDiff", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("isSubmodule", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        pj.Companion.getClass();
        List r13 = l.r(new m[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new m("status", l0.b(pj.s), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        lj.Companion.getClass();
        List n4 = d0.n(new m("nodes", l0.a(lj.b), (String) null, rVar, rVar, r13));
        m mVar18 = new m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar19 = new m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("filesChanged", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        nj.Companion.getClass();
        r b2 = l0.b(nj.a);
        n8.Companion.getClass();
        List r14 = l.r(new m[]{mVar18, mVar19, mVar20, new m("patches", b2, (String) null, rVar, no.a.s(n8.c, new u0(50)), n4)});
        m mVar21 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        yv.Companion.getClass();
        List r15 = l.r(new m[]{mVar21, new m("state", l0.b(yv.s), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r16 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("owner", l0.b(j0Var), (String) null, rVar, rVar, l.r(new m[]{new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar22 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        hn.Companion.getClass();
        m mVar23 = new m("state", l0.b(hn.s), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("headRefName", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("number", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar26 = new m("title", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        q0 q0Var5 = eq.m0;
        List r17 = l.r(new m[]{mVar22, mVar23, mVar24, mVar25, mVar26, new m("repository", l0.b(q0Var5), (String) null, rVar, rVar, r16), new m("isInMergeQueue", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ll.Companion.getClass();
        List n5 = d0.n(new m("nodes", l0.a(ll.K), (String) null, rVar, rVar, r17));
        List r18 = l.r(new m[]{new m("abbreviatedOid", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        d4.Companion.getClass();
        List n6 = d0.n(new m("nodes", l0.a(d4.j), (String) null, rVar, rVar, r18));
        r6.Companion.getClass();
        m mVar27 = new m("committedDate", l0.b(r6.a), (String) null, rVar, rVar, rVar);
        vb.Companion.getClass();
        x xVar6 = vb.a;
        m mVar28 = new m("messageBodyHTML", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar29 = new m("messageHeadlineHTML", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("abbreviatedOid", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        m mVar31 = new m("oid", l0.b(hb.a), (String) null, rVar, rVar, rVar);
        m mVar32 = new m("committedViaWeb", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar33 = new m("authoredByCommitter", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar34 = new m("url", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar35 = new m("repository", l0.b(q0Var5), (String) null, rVar, rVar, r2);
        m mVar36 = new m("committer", q0Var2, (String) null, rVar, rVar, r4);
        m mVar37 = new m("author", q0Var2, (String) null, rVar, rVar, r5);
        db.Companion.getClass();
        m mVar38 = new m("authors", l0.b(db.a), (String) null, rVar, no.a.s(d4.b, new u0(15)), n);
        q0 q0Var6 = n8.d;
        k.g(q0Var6, "type");
        m mVar39 = new m("diff", q0Var6, (String) null, rVar, rVar, r14);
        qv.Companion.getClass();
        q0 q0Var7 = qv.c;
        k.g(q0Var7, "type");
        m mVar40 = new m("statusCheckRollup", q0Var7, (String) null, rVar, rVar, r15);
        zl.Companion.getClass();
        q0 q0Var8 = zl.a;
        k.g(q0Var8, "type");
        m mVar41 = new m("associatedPullRequests", q0Var8, (String) null, rVar, no.a.s(d4.a, new u0(5)), n5);
        h4.Companion.getClass();
        a = l.r(new m[]{mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, new m("parents", l0.b(h4.a), (String) null, rVar, no.a.s(d4.i, new u0(5)), n6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
