package wn0;

import aa.a0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.a3;
import pz0.c3;
import pz0.e3;
import pz0.g1;
import pz0.h50;
import pz0.hm;
import pz0.hs;
import pz0.jx;
import pz0.k3;
import pz0.mv;
import pz0.ny;
import pz0.pd;
import pz0.py;
import pz0.qu;
import pz0.s4;
import pz0.td;
import pz0.vd;
import pz0.w0;
import pz0.xd;
import pz0.xs;
import pz0.y2;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class b {
    public static final List a;

    static {
        vd.Companion.getClass();
        x xVar = vd.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        List n = d0.n(new m("totalCount", b, (String) null, rVar, rVar, rVar));
        xd.Companion.getClass();
        x xVar2 = xd.a;
        s mVar = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.a.a;
        List r2 = l.r(new s[]{mVar, no.a.c(list, "selections", "Actor", r, list)});
        td.Companion.getClass();
        x xVar3 = td.a;
        m mVar2 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar3 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ny.Companion.getClass();
        m mVar4 = new m("owner", l0.b(ny.e), (String) null, rVar, rVar, r2);
        py.Companion.getClass();
        a0 a0Var = py.s;
        k71.k.g(a0Var, "type");
        List r3 = l.r(new m[]{mVar2, mVar3, mVar4, new m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r4 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)});
        pz0.l.Companion.getClass();
        List r5 = l.r(new m[]{new m("pusher", l0.b(pz0.l.a), (String) null, rVar, rVar, r4), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r7 = l.r(new m[]{new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("title", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        hs.Companion.getClass();
        List n2 = d0.n(new m("nodes", l0.a(hs.N), (String) null, rVar, rVar, r7));
        m mVar5 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("abbreviatedOid", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        xs.Companion.getClass();
        q0 q0Var = xs.a;
        k71.k.g(q0Var, "type");
        s4.Companion.getClass();
        List r8 = l.r(new m[]{mVar5, mVar6, new m("associatedPullRequests", q0Var, (String) null, rVar, no.a.s(s4.a, new u0(1)), n2), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar7 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        x xVar4 = h50.a;
        List r9 = l.r(new m[]{mVar7, mVar8, new m("logoUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        pd.Companion.getClass();
        x xVar5 = pd.a;
        List r10 = l.r(new m[]{new m("hasNextPage", l0.b(xVar5), (String) null, rVar, rVar, rVar), new m("hasPreviousPage", l0.b(xVar5), (String) null, rVar, rVar, rVar), new m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0.n("CheckRun");
        List list2 = f.a;
        List r12 = l.r(new s[]{mVar9, no.a.c(list2, "selections", "CheckRun", n3, list2), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        m mVar10 = new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar);
        hm.Companion.getClass();
        m mVar11 = new m("pageInfo", l0.b(hm.a), (String) null, rVar, rVar, r10);
        a3.Companion.getClass();
        q0 q0Var2 = a3.f;
        List r13 = l.r(new m[]{mVar10, mVar11, new m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, r12)});
        List r14 = l.r(new m[]{new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("CheckRun", d0.n("CheckRun"), list2), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)}))});
        List n4 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n5 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n6 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n7 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        m mVar12 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        e3.Companion.getClass();
        m mVar13 = new m("status", l0.b(e3.s), (String) null, rVar, rVar, rVar);
        y2.Companion.getClass();
        a0 a0Var2 = y2.s;
        k71.k.g(a0Var2, "type");
        m mVar14 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        m mVar15 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("duration", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("event", xVar2, (String) null, rVar, rVar, rVar);
        g1.Companion.getClass();
        q0 q0Var3 = g1.a;
        k71.k.g(q0Var3, "type");
        m mVar18 = new m("artifacts", q0Var3, (String) null, rVar, rVar, n);
        jx.Companion.getClass();
        m mVar19 = new m("repository", l0.b(jx.t0), (String) null, rVar, rVar, r3);
        qu.Companion.getClass();
        q0 q0Var4 = qu.a;
        k71.k.g(q0Var4, "type");
        m mVar20 = new m("push", q0Var4, (String) null, rVar, rVar, r5);
        mv.Companion.getClass();
        q0 q0Var5 = mv.e;
        k71.k.g(q0Var5, "type");
        m mVar21 = new m("branch", q0Var5, (String) null, rVar, rVar, r6);
        m mVar22 = new m("commit", l0.b(s4.j), (String) null, rVar, rVar, r8);
        m mVar23 = new m("rerunnable", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        w0.Companion.getClass();
        q0 q0Var6 = w0.a;
        k71.k.g(q0Var6, "type");
        m mVar24 = new m("app", q0Var6, (String) null, rVar, rVar, r9);
        c3.Companion.getClass();
        q0 q0Var7 = c3.a;
        k71.k.g(q0Var7, "type");
        k3.Companion.getClass();
        aa.k kVar = new aa.k(k3.a, new u0(new t("afterCheckRuns")));
        a81.t tVar = k3.c;
        m mVar25 = new m("checkRuns", q0Var7, "checkRuns", rVar, l.r(new aa.k[]{kVar, new aa.k(tVar, new u0(new t("first")))}), r13);
        a81.t tVar2 = k3.b;
        a = l.r(new m[]{mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, new m("checkRuns", q0Var7, "failedCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", l.r(new String[]{"CANCELLED", "FAILURE", "TIMED_OUT", "ACTION_REQUIRED", "STALE", "STARTUP_FAILURE"})))), new aa.k(tVar, new u0(5))}), r14), new m("checkRuns", q0Var7, "runningCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("statuses", l.r(new String[]{"IN_PROGRESS", "PENDING", "QUEUED", "REQUESTED", "WAITING"})))), new aa.k(tVar, new u0(1))}), n4), new m("checkRuns", q0Var7, "skippedCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", d0.n("SKIPPED")))), new aa.k(tVar, new u0(1))}), n5), new m("checkRuns", q0Var7, "neutralCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", d0.n("NEUTRAL")))), new aa.k(tVar, new u0(1))}), n6), new m("checkRuns", q0Var7, "successfulCheckRuns", rVar, l.r(new aa.k[]{new aa.k(tVar2, new u0(no.a.u("conclusions", d0.n("SUCCESS")))), new aa.k(tVar, new u0(1))}), n7), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
