package m10;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes3.dex */
public final class bp {
    public static final bp A;
    public static final bp A0;
    public static final bp B;
    public static final bp B0;
    public static final bp C;
    public static final bp C0;
    public static final ap Companion;
    public static final bp D;
    public static final bp D0;
    public static final bp E;
    public static final bp E0;
    public static final bp F;
    public static final bp F0;
    public static final bp G;
    public static final /* synthetic */ bp[] G0;
    public static final bp H;
    public static final /* synthetic */ d71.b H0;
    public static final bp I;
    public static final bp J;
    public static final bp K;
    public static final bp L;
    public static final bp M;
    public static final bp N;
    public static final bp O;
    public static final bp P;
    public static final bp Q;
    public static final bp R;
    public static final bp S;
    public static final bp T;
    public static final bp U;
    public static final bp V;
    public static final bp W;
    public static final bp X;
    public static final bp Y;
    public static final bp Z;
    public static final bp a0;
    public static final bp b0;
    public static final bp c0;
    public static final bp d0;
    public static final bp e0;
    public static final bp f0;
    public static final bp g0;
    public static final bp h0;
    public static final bp i0;
    public static final bp j0;
    public static final bp k0;
    public static final bp l0;
    public static final bp m0;
    public static final bp n0;
    public static final bp o0;
    public static final bp p0;
    public static final bp q0;
    public static final bp r0;
    public static final bp s;
    public static final bp s0;
    public static final bp t;
    public static final bp t0;
    public static final bp u;
    public static final bp u0;
    public static final bp v;
    public static final bp v0;
    public static final bp w;
    public static final bp w0;
    public static final bp x;
    public static final bp x0;
    public static final bp y;
    public static final bp y0;
    public static final bp z;
    public static final bp z0;
    public String r;

    static {
        bp bpVar = new bp("AGENT_INSTRUCTIONS_EMPTY", 0, "AGENT_INSTRUCTIONS_EMPTY");
        s = bpVar;
        bp bpVar2 = new bp("AGENT_INSTRUCTIONS_INCLUDED", 1, "AGENT_INSTRUCTIONS_INCLUDED");
        t = bpVar2;
        bp bpVar3 = new bp("AGENT_LOGS", 2, "AGENT_LOGS");
        u = bpVar3;
        bp bpVar4 = new bp("AGENT_PULL_REQUESTS", 3, "AGENT_PULL_REQUESTS");
        v = bpVar4;
        bp bpVar5 = new bp("AGENT_TASKS_HOME", 4, "AGENT_TASKS_HOME");
        w = bpVar5;
        bp bpVar6 = new bp("AGENT_TASKS_REPOSITORY", 5, "AGENT_TASKS_REPOSITORY");
        x = bpVar6;
        bp bpVar7 = new bp("AGENT_TASK_ACTIVE", 6, "AGENT_TASK_ACTIVE");
        y = bpVar7;
        bp bpVar8 = new bp("AGENT_TASK_COMPLETED", 7, "AGENT_TASK_COMPLETED");
        z = bpVar8;
        bp bpVar9 = new bp("ASSIGNED", 8, "ASSIGNED");
        A = bpVar9;
        bp bpVar10 = new bp("AWESOME", 9, "AWESOME");
        B = bpVar10;
        bp bpVar11 = new bp("CLOSED", 10, "CLOSED");
        C = bpVar11;
        bp bpVar12 = new bp("COMMIT_DETAILS", 11, "COMMIT_DETAILS");
        D = bpVar12;
        bp bpVar13 = new bp("COMPLETE", 12, "COMPLETE");
        E = bpVar13;
        bp bpVar14 = new bp("CONTINUE_REVIEW", 13, "CONTINUE_REVIEW");
        F = bpVar14;
        bp bpVar15 = new bp("COPILOT_CHAT", 14, "COPILOT_CHAT");
        G = bpVar15;
        bp bpVar16 = new bp("COPILOT_CHAT_ASSISTANT_MESSAGE", 15, "COPILOT_CHAT_ASSISTANT_MESSAGE");
        H = bpVar16;
        bp bpVar17 = new bp("COPILOT_CHAT_INPUT_FIELD", 16, "COPILOT_CHAT_INPUT_FIELD");
        I = bpVar17;
        bp bpVar18 = new bp("COPILOT_HOME", 17, "COPILOT_HOME");
        J = bpVar18;
        bp bpVar19 = new bp("COPILOT_THREADS", 18, "COPILOT_THREADS");
        K = bpVar19;
        bp bpVar20 = new bp("COPILOT_UPSELL_BANNER_FLOW", 19, "COPILOT_UPSELL_BANNER_FLOW");
        L = bpVar20;
        bp bpVar21 = new bp("CREATED", 20, "CREATED");
        M = bpVar21;
        bp bpVar22 = new bp("CREATE_REPO_CONFIGURATION", 21, "CREATE_REPO_CONFIGURATION");
        N = bpVar22;
        bp bpVar23 = new bp("CREATE_REPO_GENERAL", 22, "CREATE_REPO_GENERAL");
        O = bpVar23;
        bp bpVar24 = new bp("DISMISSED", 23, "DISMISSED");
        P = bpVar24;
        bp bpVar25 = new bp("DISPLAYED", 24, "DISPLAYED");
        Q = bpVar25;
        bp bpVar26 = new bp("DONE", 25, "DONE");
        R = bpVar26;
        bp bpVar27 = new bp("EXTERNAL", 26, "EXTERNAL");
        S = bpVar27;
        bp bpVar28 = new bp("FEED", 27, "FEED");
        T = bpVar28;
        bp bpVar29 = new bp("FOCUSED", 28, "FOCUSED");
        U = bpVar29;
        bp bpVar30 = new bp("HOME", 29, "HOME");
        V = bpVar30;
        bp bpVar31 = new bp("ISSUE_CELL", 30, "ISSUE_CELL");
        W = bpVar31;
        bp bpVar32 = new bp("ISSUE_DETAILS", 31, "ISSUE_DETAILS");
        X = bpVar32;
        bp bpVar33 = new bp("MENTIONED", 32, "MENTIONED");
        Y = bpVar33;
        bp bpVar34 = new bp("NEW_ISSUE", 33, "NEW_ISSUE");
        Z = bpVar34;
        bp bpVar35 = new bp("NOTIFICATIONS_ONBOARDING_FLOW", 34, "NOTIFICATIONS_ONBOARDING_FLOW");
        a0 = bpVar35;
        bp bpVar36 = new bp("NOT_FOCUSED", 35, "NOT_FOCUSED");
        b0 = bpVar36;
        bp bpVar37 = new bp("OPEN", 36, "OPEN");
        c0 = bpVar37;
        bp bpVar38 = new bp("OPENED", 37, "OPENED");
        d0 = bpVar38;
        bp bpVar39 = new bp("PAGE_FIVE", 38, "PAGE_FIVE");
        e0 = bpVar39;
        bp bpVar40 = new bp("PAGE_FOUR", 39, "PAGE_FOUR");
        f0 = bpVar40;
        bp bpVar41 = new bp("PAGE_ONE", 40, "PAGE_ONE");
        g0 = bpVar41;
        bp bpVar42 = new bp("PAGE_SEVEN", 41, "PAGE_SEVEN");
        h0 = bpVar42;
        bp bpVar43 = new bp("PAGE_SIX", 42, "PAGE_SIX");
        i0 = bpVar43;
        bp bpVar44 = new bp("PAGE_THREE", 43, "PAGE_THREE");
        j0 = bpVar44;
        bp bpVar45 = new bp("PAGE_TWO", 44, "PAGE_TWO");
        k0 = bpVar45;
        bp bpVar46 = new bp("PROFILE_REPOSITORIES", 45, "PROFILE_REPOSITORIES");
        l0 = bpVar46;
        bp bpVar47 = new bp("PULL_REQUEST_DETAILS", 46, "PULL_REQUEST_DETAILS");
        m0 = bpVar47;
        bp bpVar48 = new bp("PULL_REQUEST_FILES", 47, "PULL_REQUEST_FILES");
        n0 = bpVar48;
        bp bpVar49 = new bp("PULL_REQUEST_FILES_CHANGED", 48, "PULL_REQUEST_FILES_CHANGED");
        o0 = bpVar49;
        bp bpVar50 = new bp("PULL_REQUEST_FILES_CHANGED_SINGLE_FILE", 49, "PULL_REQUEST_FILES_CHANGED_SINGLE_FILE");
        p0 = bpVar50;
        bp bpVar51 = new bp("READ", 50, "READ");
        q0 = bpVar51;
        bp bpVar52 = new bp("REPOSITORY", 51, "REPOSITORY");
        r0 = bpVar52;
        bp bpVar53 = new bp("REPOSITORY_FILE_VIEWER", 52, "REPOSITORY_FILE_VIEWER");
        s0 = bpVar53;
        bp bpVar54 = new bp("REVIEW_REQUESTED", 53, "REVIEW_REQUESTED");
        t0 = bpVar54;
        bp bpVar55 = new bp("SAVE", 54, "SAVE");
        u0 = bpVar55;
        bp bpVar56 = new bp("SUBSCRIBE", 55, "SUBSCRIBE");
        v0 = bpVar56;
        bp bpVar57 = new bp("TRENDING", 56, "TRENDING");
        w0 = bpVar57;
        bp bpVar58 = new bp("UNDONE", 57, "UNDONE");
        x0 = bpVar58;
        bp bpVar59 = new bp("UNREAD", 58, "UNREAD");
        y0 = bpVar59;
        bp bpVar60 = new bp("UNSAVE", 59, "UNSAVE");
        z0 = bpVar60;
        bp bpVar61 = new bp("UNSUBSCRIBE", 60, "UNSUBSCRIBE");
        A0 = bpVar61;
        bp bpVar62 = new bp("WORKFLOW_RUNS", 61, "WORKFLOW_RUNS");
        B0 = bpVar62;
        bp bpVar63 = new bp("WORKFLOW_RUN_STEPS", 62, "WORKFLOW_RUN_STEPS");
        C0 = bpVar63;
        bp bpVar64 = new bp("WORKFLOW_RUN_STEP_LOG", 63, "WORKFLOW_RUN_STEP_LOG");
        D0 = bpVar64;
        bp bpVar65 = new bp("WORKFLOW_SUMMARY", 64, "WORKFLOW_SUMMARY");
        E0 = bpVar65;
        bp bpVar66 = new bp("UNKNOWN__", 65, "UNKNOWN__");
        F0 = bpVar66;
        bp[] bpVarArr = {bpVar, bpVar2, bpVar3, bpVar4, bpVar5, bpVar6, bpVar7, bpVar8, bpVar9, bpVar10, bpVar11, bpVar12, bpVar13, bpVar14, bpVar15, bpVar16, bpVar17, bpVar18, bpVar19, bpVar20, bpVar21, bpVar22, bpVar23, bpVar24, bpVar25, bpVar26, bpVar27, bpVar28, bpVar29, bpVar30, bpVar31, bpVar32, bpVar33, bpVar34, bpVar35, bpVar36, bpVar37, bpVar38, bpVar39, bpVar40, bpVar41, bpVar42, bpVar43, bpVar44, bpVar45, bpVar46, bpVar47, bpVar48, bpVar49, bpVar50, bpVar51, bpVar52, bpVar53, bpVar54, bpVar55, bpVar56, bpVar57, bpVar58, bpVar59, bpVar60, bpVar61, bpVar62, bpVar63, bpVar64, bpVar65, bpVar66};
        G0 = bpVarArr;
        H0 = v8.l0.t(bpVarArr);
        Companion = new ap();
        sy.d0.o("AGENT_INSTRUCTIONS_EMPTY", "AGENT_INSTRUCTIONS_INCLUDED", "AGENT_LOGS", "AGENT_PULL_REQUESTS", "AGENT_TASKS_HOME", "AGENT_TASKS_REPOSITORY", "AGENT_TASK_ACTIVE", "AGENT_TASK_COMPLETED", "ASSIGNED", "AWESOME", "CLOSED", "COMMIT_DETAILS", "COMPLETE", "CONTINUE_REVIEW", "COPILOT_CHAT", "COPILOT_CHAT_ASSISTANT_MESSAGE", "COPILOT_CHAT_INPUT_FIELD", "COPILOT_HOME", "COPILOT_THREADS", "COPILOT_UPSELL_BANNER_FLOW", "CREATED", "CREATE_REPO_CONFIGURATION", "CREATE_REPO_GENERAL", "DISMISSED", "DISPLAYED", "DONE", "EXTERNAL", "FEED", "FOCUSED", "HOME", "ISSUE_CELL", "ISSUE_DETAILS", "MENTIONED", "NEW_ISSUE", "NOTIFICATIONS_ONBOARDING_FLOW", "NOT_FOCUSED", "OPEN", "OPENED", "PAGE_FIVE", "PAGE_FOUR", "PAGE_ONE", "PAGE_SEVEN", "PAGE_SIX", "PAGE_THREE", "PAGE_TWO", "PROFILE_REPOSITORIES", "PULL_REQUEST_DETAILS", "PULL_REQUEST_FILES", "PULL_REQUEST_FILES_CHANGED", "PULL_REQUEST_FILES_CHANGED_SINGLE_FILE", "READ", "REPOSITORY", "REPOSITORY_FILE_VIEWER", "REVIEW_REQUESTED", "SAVE", "SUBSCRIBE", "TRENDING", "UNDONE", "UNREAD", "UNSAVE", "UNSUBSCRIBE", "WORKFLOW_RUNS", "WORKFLOW_RUN_STEPS", "WORKFLOW_RUN_STEP_LOG", "WORKFLOW_SUMMARY");
    }

    public bp(String str, int i, String str2) {
        this.r = str2;
    }

    public static bp valueOf(String str) {
        return (bp) Enum.valueOf(bp.class, str);
    }

    public static bp[] values() {
        return (bp[]) G0.clone();
    }
}
