package m10;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes3.dex */
public final class op {
    public static final op A;
    public static final op A0;
    public static final op B;
    public static final op B0;
    public static final op C;
    public static final op C0;
    public static final np Companion;
    public static final op D;
    public static final op D0;
    public static final op E;
    public static final op E0;
    public static final op F;
    public static final op F0;
    public static final op G;
    public static final op G0;
    public static final op H;
    public static final op H0;
    public static final op I;
    public static final op I0;
    public static final op J;
    public static final op J0;
    public static final op K;
    public static final op K0;
    public static final op L;
    public static final op L0;
    public static final op M;
    public static final op M0;
    public static final op N;
    public static final op N0;
    public static final op O;
    public static final op O0;
    public static final op P;
    public static final op P0;
    public static final op Q;
    public static final op Q0;
    public static final op R;
    public static final op R0;
    public static final op S;
    public static final op S0;
    public static final op T;
    public static final op T0;
    public static final op U;
    public static final op U0;
    public static final op V;
    public static final op V0;
    public static final op W;
    public static final op W0;
    public static final op X;
    public static final op X0;
    public static final op Y;
    public static final op Y0;
    public static final op Z;
    public static final op Z0;
    public static final op a0;
    public static final op a1;
    public static final op b0;
    public static final op b1;
    public static final op c0;
    public static final op c1;
    public static final op d0;
    public static final op d1;
    public static final op e0;
    public static final op e1;
    public static final op f0;
    public static final op f1;
    public static final op g0;
    public static final op g1;
    public static final op h0;
    public static final op h1;
    public static final op i0;
    public static final op i1;
    public static final op j0;
    public static final op j1;
    public static final op k0;
    public static final op k1;
    public static final op l0;
    public static final op l1;
    public static final op m0;
    public static final op m1;
    public static final op n0;
    public static final op n1;
    public static final op o0;
    public static final op o1;
    public static final op p0;
    public static final op p1;
    public static final op q0;
    public static final op q1;
    public static final op r0;
    public static final op r1;
    public static final op s;
    public static final op s0;
    public static final op s1;
    public static final op t;
    public static final op t0;
    public static final /* synthetic */ op[] t1;
    public static final op u;
    public static final op u0;
    public static final /* synthetic */ d71.b u1;
    public static final op v;
    public static final op v0;
    public static final op w;
    public static final op w0;
    public static final op x;
    public static final op x0;
    public static final op y;
    public static final op y0;
    public static final op z;
    public static final op z0;
    public String r;

    static {
        op opVar = new op("AGENT_ASSIGNMENT", 0, "AGENT_ASSIGNMENT");
        s = opVar;
        op opVar2 = new op("AGENT_TASK", 1, "AGENT_TASK");
        t = opVar2;
        op opVar3 = new op("AGENT_TASK_CCA", 2, "AGENT_TASK_CCA");
        u = opVar3;
        op opVar4 = new op("AGENT_TASK_CLI", 3, "AGENT_TASK_CLI");
        v = opVar4;
        op opVar5 = new op("AGENT_TASK_CLI_REPOLESS", 4, "AGENT_TASK_CLI_REPOLESS");
        w = opVar5;
        op opVar6 = new op("AGENT_TASK_VSCODE", 5, "AGENT_TASK_VSCODE");
        x = opVar6;
        op opVar7 = new op("BRANCHES", 6, "BRANCHES");
        y = opVar7;
        op opVar8 = new op("CHECK_SUITE", 7, "CHECK_SUITE");
        z = opVar8;
        op opVar9 = new op("CODE", 8, "CODE");
        A = opVar9;
        op opVar10 = new op("COMMIT", 9, "COMMIT");
        B = opVar10;
        op opVar11 = new op("COMMITS", 10, "COMMITS");
        C = opVar11;
        op opVar12 = new op("COPILOT_PAYWALL", 11, "COPILOT_PAYWALL");
        D = opVar12;
        op opVar13 = new op("COPILOT_SETTINGS", 12, "COPILOT_SETTINGS");
        E = opVar13;
        op opVar14 = new op("COPILOT_UPSELL", 13, "COPILOT_UPSELL");
        F = opVar14;
        op opVar15 = new op("CUSTOM_AGENT", 14, "CUSTOM_AGENT");
        G = opVar15;
        op opVar16 = new op("DEEP_LINK", 15, "DEEP_LINK");
        H = opVar16;
        op opVar17 = new op("DEPLOYMENT_REVIEW", 16, "DEPLOYMENT_REVIEW");
        I = opVar17;
        op opVar18 = new op("DIFF", 17, "DIFF");
        J = opVar18;
        op opVar19 = new op("DISCUSSION", 18, "DISCUSSION");
        K = opVar19;
        op opVar20 = new op("DISCUSSIONS", 19, "DISCUSSIONS");
        L = opVar20;
        op opVar21 = new op("DRAFT_ISSUE", 20, "DRAFT_ISSUE");
        M = opVar21;
        op opVar22 = new op("EMPTY_STATE", 21, "EMPTY_STATE");
        N = opVar22;
        op opVar23 = new op("EMPTY_STATE_CTA", 22, "EMPTY_STATE_CTA");
        O = opVar23;
        op opVar24 = new op("FEED", 23, "FEED");
        P = opVar24;
        op opVar25 = new op("FILE", 24, "FILE");
        Q = opVar25;
        op opVar26 = new op("FILTER", 25, "FILTER");
        R = opVar26;
        op opVar27 = new op("FILTER_AGENT_TASKS_SORT", 26, "FILTER_AGENT_TASKS_SORT");
        S = opVar27;
        op opVar28 = new op("FILTER_AGENT_TASK_STATE", 27, "FILTER_AGENT_TASK_STATE");
        T = opVar28;
        op opVar29 = new op("FILTER_ASSIGNEE", 28, "FILTER_ASSIGNEE");
        U = opVar29;
        op opVar30 = new op("FILTER_AUTHOR", 29, "FILTER_AUTHOR");
        V = opVar30;
        op opVar31 = new op("FILTER_DISCUSSION_CATEGORY", 30, "FILTER_DISCUSSION_CATEGORY");
        W = opVar31;
        op opVar32 = new op("FILTER_DISCUSSION_IS_UNANSWERED", 31, "FILTER_DISCUSSION_IS_UNANSWERED");
        X = opVar32;
        op opVar33 = new op("FILTER_DISCUSSION_TOP", 32, "FILTER_DISCUSSION_TOP");
        Y = opVar33;
        op opVar34 = new op("FILTER_DISCUSSION_VIEWER", 33, "FILTER_DISCUSSION_VIEWER");
        Z = opVar34;
        op opVar35 = new op("FILTER_DRAFT", 34, "FILTER_DRAFT");
        a0 = opVar35;
        op opVar36 = new op("FILTER_ISSUE_STATUS", 35, "FILTER_ISSUE_STATUS");
        b0 = opVar36;
        op opVar37 = new op("FILTER_ISSUE_TYPE", 36, "FILTER_ISSUE_TYPE");
        c0 = opVar37;
        op opVar38 = new op("FILTER_ISSUE_VIEWER", 37, "FILTER_ISSUE_VIEWER");
        d0 = opVar38;
        op opVar39 = new op("FILTER_LABEL", 38, "FILTER_LABEL");
        e0 = opVar39;
        op opVar40 = new op("FILTER_LANGUAGE", 39, "FILTER_LANGUAGE");
        f0 = opVar40;
        op opVar41 = new op("FILTER_MILESTONE", 40, "FILTER_MILESTONE");
        g0 = opVar41;
        op opVar42 = new op("FILTER_NOTIFICATION_FILTER", 41, "FILTER_NOTIFICATION_FILTER");
        h0 = opVar42;
        op opVar43 = new op("FILTER_NOTIFICATION_FOCUSED", 42, "FILTER_NOTIFICATION_FOCUSED");
        i0 = opVar43;
        op opVar44 = new op("FILTER_NOTIFICATION_IS_UNREAD", 43, "FILTER_NOTIFICATION_IS_UNREAD");
        j0 = opVar44;
        op opVar45 = new op("FILTER_NOTIFICATION_STATUS", 44, "FILTER_NOTIFICATION_STATUS");
        k0 = opVar45;
        op opVar46 = new op("FILTER_ORGANIZATION", 45, "FILTER_ORGANIZATION");
        l0 = opVar46;
        op opVar47 = new op("FILTER_PROJECT", 46, "FILTER_PROJECT");
        m0 = opVar47;
        op opVar48 = new op("FILTER_PULL_REQUEST_REVIEW_STATUS", 47, "FILTER_PULL_REQUEST_REVIEW_STATUS");
        n0 = opVar48;
        op opVar49 = new op("FILTER_PULL_REQUEST_STATUS", 48, "FILTER_PULL_REQUEST_STATUS");
        o0 = opVar49;
        op opVar50 = new op("FILTER_PULL_REQUEST_VIEWER", 49, "FILTER_PULL_REQUEST_VIEWER");
        p0 = opVar50;
        op opVar51 = new op("FILTER_REPOSITORY", 50, "FILTER_REPOSITORY");
        q0 = opVar51;
        op opVar52 = new op("FILTER_REPOSITORY_TYPE", 51, "FILTER_REPOSITORY_TYPE");
        r0 = opVar52;
        op opVar53 = new op("FILTER_REPOSITORY_VISIBILITY", 52, "FILTER_REPOSITORY_VISIBILITY");
        s0 = opVar53;
        op opVar54 = new op("FILTER_SORT", 53, "FILTER_SORT");
        t0 = opVar54;
        op opVar55 = new op("FILTER_TRENDING_DATE_RANGE", 54, "FILTER_TRENDING_DATE_RANGE");
        u0 = opVar55;
        op opVar56 = new op("FILTER_TRENDING_LANGUAGE", 55, "FILTER_TRENDING_LANGUAGE");
        v0 = opVar56;
        op opVar57 = new op("FILTER_TRENDING_SPOKEN_LANGUAGE", 56, "FILTER_TRENDING_SPOKEN_LANGUAGE");
        w0 = opVar57;
        op opVar58 = new op("FILTER_VIEWER_REVIEW_REQUESTED", 57, "FILTER_VIEWER_REVIEW_REQUESTED");
        x0 = opVar58;
        op opVar59 = new op("GIST", 58, "GIST");
        y0 = opVar59;
        op opVar60 = new op("GLOBAL_SEARCH", 59, "GLOBAL_SEARCH");
        z0 = opVar60;
        op opVar61 = new op("HOME", 60, "HOME");
        A0 = opVar61;
        op opVar62 = new op("ISSUE", 61, "ISSUE");
        B0 = opVar62;
        op opVar63 = new op("ISSUES", 62, "ISSUES");
        C0 = opVar63;
        op opVar64 = new op("JUMP_TO", 63, "JUMP_TO");
        D0 = opVar64;
        op opVar65 = new op("NAVIGATION_BAR", 64, "NAVIGATION_BAR");
        E0 = opVar65;
        op opVar66 = new op("NOTIFICATIONS", 65, "NOTIFICATIONS");
        F0 = opVar66;
        op opVar67 = new op("ORGANIZATION", 66, "ORGANIZATION");
        G0 = opVar67;
        op opVar68 = new op("ORGANIZATIONS", 67, "ORGANIZATIONS");
        H0 = opVar68;
        op opVar69 = new op("PROJECT", 68, "PROJECT");
        I0 = opVar69;
        op opVar70 = new op("PROJECTS", 69, "PROJECTS");
        J0 = opVar70;
        op opVar71 = new op("PULL_REQUEST", 70, "PULL_REQUEST");
        K0 = opVar71;
        op opVar72 = new op("PULL_REQUESTS", 71, "PULL_REQUESTS");
        L0 = opVar72;
        op opVar73 = new op("PUSH_NOTIFICATIONS", 72, "PUSH_NOTIFICATIONS");
        M0 = opVar73;
        op opVar74 = new op("PUSH_NOTIFICATION_ACTION", 73, "PUSH_NOTIFICATION_ACTION");
        N0 = opVar74;
        op opVar75 = new op("PUSH_NOTIFICATION_ASSIGN", 74, "PUSH_NOTIFICATION_ASSIGN");
        O0 = opVar75;
        op opVar76 = new op("PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", 75, "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL");
        P0 = opVar76;
        op opVar77 = new op("PUSH_NOTIFICATION_DISABLE_LIVE_UPDATES", 76, "PUSH_NOTIFICATION_DISABLE_LIVE_UPDATES");
        Q0 = opVar77;
        op opVar78 = new op("PUSH_NOTIFICATION_LIVE_UPDATE_AGENTS", 77, "PUSH_NOTIFICATION_LIVE_UPDATE_AGENTS");
        R0 = opVar78;
        op opVar79 = new op("PUSH_NOTIFICATION_MENTION", 78, "PUSH_NOTIFICATION_MENTION");
        S0 = opVar79;
        op opVar80 = new op("PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", 79, "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST");
        T0 = opVar80;
        op opVar81 = new op("PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", 80, "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW");
        U0 = opVar81;
        op opVar82 = new op("PUSH_NOTIFICATION_RELEASE", 81, "PUSH_NOTIFICATION_RELEASE");
        V0 = opVar82;
        op opVar83 = new op("PUSH_NOTIFICATION_REVIEW_REQUEST", 82, "PUSH_NOTIFICATION_REVIEW_REQUEST");
        W0 = opVar83;
        op opVar84 = new op("RELEASE", 83, "RELEASE");
        X0 = opVar84;
        op opVar85 = new op("RELEASES", 84, "RELEASES");
        Y0 = opVar85;
        op opVar86 = new op("REPOSITORIES", 85, "REPOSITORIES");
        Z0 = opVar86;
        op opVar87 = new op("REPOSITORY", 86, "REPOSITORY");
        a1 = opVar87;
        op opVar88 = new op("REPOSITORY_ADVISORY", 87, "REPOSITORY_ADVISORY");
        b1 = opVar88;
        op opVar89 = new op("REPOSITORY_CREATION", 88, "REPOSITORY_CREATION");
        c1 = opVar89;
        op opVar90 = new op("REPOSITORY_DEPENDABOT_THREAD_ALERT", 89, "REPOSITORY_DEPENDABOT_THREAD_ALERT");
        d1 = opVar90;
        op opVar91 = new op("REPOSITORY_VULNERABILITY_ALERT", 90, "REPOSITORY_VULNERABILITY_ALERT");
        e1 = opVar91;
        op opVar92 = new op("SEARCH", 91, "SEARCH");
        f1 = opVar92;
        op opVar93 = new op("SECURITY_ADVISORY", 92, "SECURITY_ADVISORY");
        g1 = opVar93;
        op opVar94 = new op("SEND_AGENT_TASK", 93, "SEND_AGENT_TASK");
        h1 = opVar94;
        op opVar95 = new op("SETTINGS", 94, "SETTINGS");
        i1 = opVar95;
        op opVar96 = new op("SHORTCUT", 95, "SHORTCUT");
        j1 = opVar96;
        op opVar97 = new op("SUBMIT_REVIEW_SHEET", 96, "SUBMIT_REVIEW_SHEET");
        k1 = opVar97;
        op opVar98 = new op("SUB_ISSUE", 97, "SUB_ISSUE");
        l1 = opVar98;
        op opVar99 = new op("SWIPE_ACTIONS", 98, "SWIPE_ACTIONS");
        m1 = opVar99;
        op opVar100 = new op("TEAM_DISCUSSION", 99, "TEAM_DISCUSSION");
        n1 = opVar100;
        op opVar101 = new op("TOAST", 100, "TOAST");
        o1 = opVar101;
        op opVar102 = new op("USER", 101, "USER");
        p1 = opVar102;
        op opVar103 = new op("USERS", 102, "USERS");
        q1 = opVar103;
        op opVar104 = new op("WORKFLOW_RUN", 103, "WORKFLOW_RUN");
        r1 = opVar104;
        op opVar105 = new op("UNKNOWN__", 104, "UNKNOWN__");
        s1 = opVar105;
        op[] opVarArr = {opVar, opVar2, opVar3, opVar4, opVar5, opVar6, opVar7, opVar8, opVar9, opVar10, opVar11, opVar12, opVar13, opVar14, opVar15, opVar16, opVar17, opVar18, opVar19, opVar20, opVar21, opVar22, opVar23, opVar24, opVar25, opVar26, opVar27, opVar28, opVar29, opVar30, opVar31, opVar32, opVar33, opVar34, opVar35, opVar36, opVar37, opVar38, opVar39, opVar40, opVar41, opVar42, opVar43, opVar44, opVar45, opVar46, opVar47, opVar48, opVar49, opVar50, opVar51, opVar52, opVar53, opVar54, opVar55, opVar56, opVar57, opVar58, opVar59, opVar60, opVar61, opVar62, opVar63, opVar64, opVar65, opVar66, opVar67, opVar68, opVar69, opVar70, opVar71, opVar72, opVar73, opVar74, opVar75, opVar76, opVar77, opVar78, opVar79, opVar80, opVar81, opVar82, opVar83, opVar84, opVar85, opVar86, opVar87, opVar88, opVar89, opVar90, opVar91, opVar92, opVar93, opVar94, opVar95, opVar96, opVar97, opVar98, opVar99, opVar100, opVar101, opVar102, opVar103, opVar104, opVar105};
        t1 = opVarArr;
        u1 = v8.l0.t(opVarArr);
        Companion = new np();
        sy.d0Shadow.o("AGENT_ASSIGNMENT", "AGENT_TASK", "AGENT_TASK_CCA", "AGENT_TASK_CLI", "AGENT_TASK_CLI_REPOLESS", "AGENT_TASK_VSCODE", "BRANCHES", "CHECK_SUITE", "CODE", "COMMIT", "COMMITS", "COPILOT_PAYWALL", "COPILOT_SETTINGS", "COPILOT_UPSELL", "CUSTOM_AGENT", "DEEP_LINK", "DEPLOYMENT_REVIEW", "DIFF", "DISCUSSION", "DISCUSSIONS", "DRAFT_ISSUE", "EMPTY_STATE", "EMPTY_STATE_CTA", "FEED", "FILE", "FILTER", "FILTER_AGENT_TASKS_SORT", "FILTER_AGENT_TASK_STATE", "FILTER_ASSIGNEE", "FILTER_AUTHOR", "FILTER_DISCUSSION_CATEGORY", "FILTER_DISCUSSION_IS_UNANSWERED", "FILTER_DISCUSSION_TOP", "FILTER_DISCUSSION_VIEWER", "FILTER_DRAFT", "FILTER_ISSUE_STATUS", "FILTER_ISSUE_TYPE", "FILTER_ISSUE_VIEWER", "FILTER_LABEL", "FILTER_LANGUAGE", "FILTER_MILESTONE", "FILTER_NOTIFICATION_FILTER", "FILTER_NOTIFICATION_FOCUSED", "FILTER_NOTIFICATION_IS_UNREAD", "FILTER_NOTIFICATION_STATUS", "FILTER_ORGANIZATION", "FILTER_PROJECT", "FILTER_PULL_REQUEST_REVIEW_STATUS", "FILTER_PULL_REQUEST_STATUS", "FILTER_PULL_REQUEST_VIEWER", "FILTER_REPOSITORY", "FILTER_REPOSITORY_TYPE", "FILTER_REPOSITORY_VISIBILITY", "FILTER_SORT", "FILTER_TRENDING_DATE_RANGE", "FILTER_TRENDING_LANGUAGE", "FILTER_TRENDING_SPOKEN_LANGUAGE", "FILTER_VIEWER_REVIEW_REQUESTED", "GIST", "GLOBAL_SEARCH", "HOME", "ISSUE", "ISSUES", "JUMP_TO", "NAVIGATION_BAR", "NOTIFICATIONS", "ORGANIZATION", "ORGANIZATIONS", "PROJECT", "PROJECTS", "PULL_REQUEST", "PULL_REQUESTS", "PUSH_NOTIFICATIONS", "PUSH_NOTIFICATION_ACTION", "PUSH_NOTIFICATION_ASSIGN", "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", "PUSH_NOTIFICATION_DISABLE_LIVE_UPDATES", "PUSH_NOTIFICATION_LIVE_UPDATE_AGENTS", "PUSH_NOTIFICATION_MENTION", "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", "PUSH_NOTIFICATION_RELEASE", "PUSH_NOTIFICATION_REVIEW_REQUEST", "RELEASE", "RELEASES", "REPOSITORIES", "REPOSITORY", "REPOSITORY_ADVISORY", "REPOSITORY_CREATION", "REPOSITORY_DEPENDABOT_THREAD_ALERT", "REPOSITORY_VULNERABILITY_ALERT", "SEARCH", "SECURITY_ADVISORY", "SEND_AGENT_TASK", "SETTINGS", "SHORTCUT", "SUBMIT_REVIEW_SHEET", "SUB_ISSUE", "SWIPE_ACTIONS", "TEAM_DISCUSSION", "TOAST", "USER", "USERS", "WORKFLOW_RUN");
    }

    public op(String str, int i, String str2) {
        this.r = str2;
    }

    public static op valueOf(String str) {
        return (op) Enum.valueOf(op.class, str);
    }

    public static op[] values() {
        return (op[]) t1.clone();
    }
}
