package m10;

import java.util.List;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class rf0 {
    public static final aa.q0 g0;
    public static final qf0 Companion = new qf0();
    public static final a81.t a = new a81.t(1, "after", false);
    public static final a81.t b = new a81.t(1, "first", false);
    public static final a81.t c = new a81.t(1, "after", false);
    public static final a81.t d = new a81.t(1, "first", false);
    public static final a81.t e = new a81.t(1, "orderBy", false);
    public static final a81.t f = new a81.t(1, "query", false);
    public static final a81.t g = new a81.t(1, "first", false);
    public static final a81.t h = new a81.t(1, "flags", false);
    public static final a81.t i = new a81.t(1, "after", false);
    public static final a81.t j = new a81.t(1, "first", false);
    public static final a81.t k = new a81.t(1, "after", false);
    public static final a81.t l = new a81.t(1, "first", false);
    public static final a81.t m = new a81.t(1, "after", false);
    public static final a81.t n = new a81.t(1, "first", false);
    public static final a81.t o = new a81.t(1, "after", false);
    public static final a81.t p = new a81.t(1, "before", false);
    public static final a81.t q = new a81.t(1, "first", false);
    public static final a81.t r = new a81.t(1, "first", false);
    public static final a81.t s = new a81.t(1, "first", false);
    public static final a81.t t = new a81.t(1, "statuses", false);
    public static final a81.t u = new a81.t(1, "after", false);
    public static final a81.t v = new a81.t(1, "filterBy", false);
    public static final a81.t w = new a81.t(1, "first", false);
    public static final a81.t x = new a81.t(1, "query", false);
    public static final a81.t y = new a81.t(1, "after", false);
    public static final a81.t z = new a81.t(1, "first", false);
    public static final a81.t A = new a81.t(1, "first", false);
    public static final a81.t B = new a81.t(1, "limit", false);
    public static final a81.t C = new a81.t(1, "after", false);
    public static final a81.t D = new a81.t(1, "first", false);
    public static final a81.t E = new a81.t(1, "after", false);
    public static final a81.t F = new a81.t(1, "first", false);
    public static final a81.t G = new a81.t(1, "language", false);
    public static final a81.t H = new a81.t(1, "orderBy", false);
    public static final a81.t I = new a81.t(1, "ownerAffiliations", false);
    public static final a81.t J = new a81.t(1, "query", false);
    public static final a81.t K = new a81.t(1, "type", false);
    public static final a81.t L = new a81.t(1, "after", false);
    public static final a81.t M = new a81.t(1, "first", false);
    public static final a81.t N = new a81.t(1, "name", false);
    public static final a81.t O = new a81.t(1, "owner", false);
    public static final a81.t P = new a81.t(1, "after", false);
    public static final a81.t Q = new a81.t(1, "first", false);
    public static final a81.t R = new a81.t(1, "first", false);
    public static final a81.t S = new a81.t(1, "after", false);
    public static final a81.t T = new a81.t(1, "first", false);
    public static final a81.t U = new a81.t(1, "orderBy", false);
    public static final a81.t V = new a81.t(1, "query", false);
    public static final a81.t W = new a81.t(1, "after", false);
    public static final a81.t X = new a81.t(1, "first", false);
    public static final a81.t Y = new a81.t(1, "orderBy", false);
    public static final a81.t Z = new a81.t(1, "type", false);
    public static final a81.t a0 = new a81.t(1, "sessionId", false);
    public static final a81.t b0 = new a81.t(1, "taskId", false);
    public static final a81.t c0 = new a81.t(1, "after", false);
    public static final a81.t d0 = new a81.t(1, "filterBy", false);
    public static final a81.t e0 = new a81.t(1, "first", false);
    public static final a81.t f0 = new a81.t(1, "orderBy", false);

    static {
        new a81.t(1, "after", false);
        new a81.t(1, "currentRepositoryId", false);
        new a81.t(1, "first", false);
        new a81.t(1, "includeForks", false);
        new a81.t(1, "owner", false);
        new a81.t(1, "query", false);
        List n2 = sy.d0.n("id");
        l.Companion.getClass();
        aa.j0 j0Var = l.a;
        b1.Companion.getClass();
        aa.j0 j0Var2 = b1.a;
        zp.Companion.getClass();
        aa.j0 j0Var3 = zp.a;
        kr.Companion.getClass();
        aa.j0 j0Var4 = kr.a;
        us.Companion.getClass();
        aa.j0 j0Var5 = us.a;
        ys.Companion.getClass();
        aa.j0 j0Var6 = ys.a;
        ow.Companion.getClass();
        aa.j0 j0Var7 = ow.g;
        sw.Companion.getClass();
        aa.j0 j0Var8 = sw.a;
        y30.Companion.getClass();
        aa.j0 j0Var9 = y30.a;
        a40.Companion.getClass();
        aa.j0 j0Var10 = a40.a;
        l40.Companion.getClass();
        aa.j0 j0Var11 = l40.e;
        t80.Companion.getClass();
        aa.j0 j0Var12 = t80.c;
        qc0.Companion.getClass();
        g0 = new aa.q0("User", n2, x61.l.r(new aa.j0[]{j0Var, j0Var2, j0Var3, j0Var4, j0Var5, j0Var6, j0Var7, j0Var8, j0Var9, j0Var10, j0Var11, j0Var12, qc0.a}));
    }
}
