package xk0;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import gn0.eq;
import gn0.fc;
import gn0.hn;
import gn0.hr;
import gn0.ko;
import gn0.lb;
import gn0.mx;
import gn0.nc;
import gn0.pb;
import gn0.r6;
import gn0.rb;
import gn0.s00;
import gn0.tb;
import gn0.tc;
import gn0.xc;
import gn0.zc;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class c {
    public static final List a;

    static {
        tb.Companion.getClass();
        x xVar = tb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        s mVar = new m("__typename", b, (String) null, rVar, rVar, rVar);
        s mVar2 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.b.a;
        s c = no.a.c(list, "selections", "Actor", r, list);
        pb.Companion.getClass();
        x xVar2 = pb.a;
        List r2 = l.r(new s[]{mVar, mVar2, c, new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        rb.Companion.getClass();
        x xVar3 = rb.a;
        List n = d0.n(new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r3 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)});
        m mVar3 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar4 = new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        hr.Companion.getClass();
        j0 j0Var = hr.a;
        List r4 = l.r(new m[]{mVar3, mVar4, new m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        x xVar4 = mx.a;
        m mVar6 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar7 = new m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        hn.Companion.getClass();
        m mVar10 = new m("state", l0.b(hn.s), "pullRequestState", rVar, rVar, rVar);
        nc.Companion.getClass();
        q0 q0Var = nc.a;
        m mVar11 = new m("comments", l0.b(q0Var), "pullComments", rVar, rVar, n);
        lb.Companion.getClass();
        x xVar5 = lb.a;
        k.g(xVar5, "type");
        m mVar12 = new m("isReadByViewer", xVar5, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("isDraft", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        r6.Companion.getClass();
        x xVar6 = r6.a;
        m mVar14 = new m("createdAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        q0 q0Var2 = eq.m0;
        List r5 = l.r(new m[]{mVar5, mVar6, mVar7, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, new m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4), new m("isInMergeQueue", l0.b(xVar5), (String) null, rVar, rVar, rVar)});
        List n2 = d0.n(new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r6 = l.r(new m[]{new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("owner", l0.b(j0Var), (String) null, rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)})), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar15 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        xc.Companion.getClass();
        m mVar19 = new m("state", l0.b(xc.s), "issueState", rVar, rVar, rVar);
        m mVar20 = new m("comments", l0.b(q0Var), "issueComments", rVar, rVar, n2);
        m mVar21 = new m("isReadByViewer", xVar5, (String) null, rVar, rVar, rVar);
        m mVar22 = new m("createdAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r6);
        zc.Companion.getClass();
        a0 a0Var = zc.s;
        k.g(a0Var, "type");
        List r7 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("PullRequest", d0.n("PullRequest"), r5), new n("Issue", d0.n("Issue"), l.r(new m[]{mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, new m("stateReason", a0Var, (String) null, rVar, rVar, rVar)}))});
        fc.Companion.getClass();
        m mVar24 = new m("interaction", l0.b(fc.s), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("occurredAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s00.Companion.getClass();
        q0 q0Var3 = s00.P;
        k.g(q0Var3, "type");
        m mVar26 = new m("commenter", q0Var3, (String) null, rVar, rVar, r2);
        tc.Companion.getClass();
        List r8 = l.r(new m[]{mVar24, mVar25, mVar26, new m("interactable", l0.b(tc.a), (String) null, rVar, rVar, r7)});
        ko.Companion.getClass();
        a = l.r(new m[]{new m("recentInteractions", no.a.d(ko.a), (String) null, rVar, no.a.s(s00.w, new u0(10)), r8), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
