package xk0;

import aa.m;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import gn0.av;
import gn0.cv;
import gn0.ev;
import gn0.fj;
import gn0.fl;
import gn0.jk;
import gn0.lb;
import gn0.lr;
import gn0.mq;
import gn0.mv;
import gn0.mx;
import gn0.pb;
import gn0.q10;
import gn0.rb;
import gn0.s00;
import gn0.tb;
import gn0.va;
import gn0.vb;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class i {
    public static final List a;

    static {
        rb.Companion.getClass();
        x xVar = rb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        List n = d0.n(new m("totalCount", b, (String) null, rVar, rVar, rVar));
        tb.Companion.getClass();
        x xVar2 = tb.a;
        s mVar = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("ProfileItemShowcase");
        List list = ki0.a.a;
        List r = l.r(new s[]{mVar, no.a.c(list, "selections", "ProfileItemShowcase", n2, list)});
        List n3 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n4 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n5 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        s mVar2 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n6 = d0.n("UserStatus");
        List list2 = d.a;
        s c = no.a.c(list2, "selections", "UserStatus", n6, list2);
        pb.Companion.getClass();
        x xVar3 = pb.a;
        List r2 = l.r(new s[]{mVar2, c, new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        s mVar3 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n7 = d0.n("RepositoryReadme");
        List list3 = pj0.j.a;
        List r3 = l.r(new s[]{mVar3, no.a.c(list3, "selections", "RepositoryReadme", n7, list3)});
        List n8 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        m mVar4 = new m("displayName", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ev.Companion.getClass();
        m mVar5 = new m("provider", l0.b(ev.s), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        x xVar4 = mx.a;
        List r4 = l.r(new m[]{mVar4, mVar5, new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        av.Companion.getClass();
        List n9 = d0.n(new m("nodes", l0.a(av.a), (String) null, rVar, rVar, r4));
        List r5 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("slug", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("badgeImageUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        gn0.b.Companion.getClass();
        m mVar6 = new m("achievable", l0.b(gn0.b.a), (String) null, rVar, rVar, r5);
        gn0.j.Companion.getClass();
        q0 q0Var = gn0.j.b;
        k.g(q0Var, "type");
        gn0.d.Companion.getClass();
        List n10 = d0.n(new m("nodes", l0.a(gn0.d.c), (String) null, rVar, rVar, l.r(new m[]{mVar6, new m("tier", q0Var, (String) null, rVar, no.a.s(gn0.d.b, new u0(1)), r6), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})));
        s mVar7 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar8 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        s mVar9 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        List r7 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list4 = vd0.b.a;
        s c2 = no.a.c(list4, "selections", "Actor", r7, list4);
        vb.Companion.getClass();
        x xVar5 = vb.a;
        s mVar10 = new m("bioHTML", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        s mVar11 = new m("companyHTML", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        s mVar12 = new m("email", l0.b(xVar2), "userEmail", rVar, rVar, rVar);
        List n12 = d0.n("User");
        List list5 = td0.g.a;
        s c3 = no.a.c(list5, "selections", "User", n12, list5);
        va.Companion.getClass();
        s mVar13 = new m("following", l0.b(va.a), (String) null, rVar, rVar, n);
        lb.Companion.getClass();
        x xVar6 = lb.a;
        s mVar14 = new m("isDeveloperProgramMember", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar15 = new m("isEmployee", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar16 = new m("isFollowingViewer", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar17 = new m("isViewer", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar18 = new m("isBountyHunter", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        jk.Companion.getClass();
        s mVar19 = new m("itemShowcase", l0.b(jk.b), (String) null, rVar, rVar, r);
        s mVar20 = new m("location", xVar2, (String) null, rVar, rVar, rVar);
        s mVar21 = new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar22 = new m("name", xVar2, (String) null, rVar, rVar, rVar);
        fj.Companion.getClass();
        s mVar23 = new m("organizations", l0.b(fj.a), (String) null, rVar, rVar, n3);
        s mVar24 = new m("pronouns", xVar2, (String) null, rVar, rVar, rVar);
        mq.Companion.getClass();
        r b2 = l0.b(mq.a);
        s00.Companion.getClass();
        s mVar25 = new m("repositories", b2, (String) null, rVar, no.a.s(s00.B, new u0(d0.n("OWNER"))), n4);
        mv.Companion.getClass();
        s mVar26 = new m("starredRepositories", l0.b(mv.a), (String) null, rVar, rVar, n5);
        q10.Companion.getClass();
        q0 q0Var2 = q10.a;
        k.g(q0Var2, "type");
        s mVar27 = new m("status", q0Var2, (String) null, rVar, rVar, r2);
        s mVar28 = new m("showProfileReadme", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        lr.Companion.getClass();
        q0 q0Var3 = lr.a;
        k.g(q0Var3, "type");
        s mVar29 = new m("profileReadme", q0Var3, (String) null, rVar, rVar, r3);
        s mVar30 = new m("viewerCanFollow", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar31 = new m("viewerIsFollowing", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar32 = new m("websiteUrl", xVar4, (String) null, rVar, rVar, rVar);
        s mVar33 = new m("viewerCanBlock", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar34 = new m("viewerCanUnblock", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar35 = new m("privateProfile", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        fl.Companion.getClass();
        s mVar36 = new m("projectsV2", l0.b(fl.a), (String) null, rVar, no.a.s(s00.v, new u0(0)), n8);
        cv.Companion.getClass();
        s mVar37 = new m("socialAccounts", l0.b(cv.a), (String) null, rVar, no.a.s(s00.G, new u0(4)), n9);
        gn0.f.Companion.getClass();
        a = l.r(new s[]{mVar7, mVar8, mVar9, c2, mVar10, mVar11, mVar12, c3, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, new m("achievements", l0.b(gn0.f.a), (String) null, rVar, no.a.s(s00.b, new u0(10)), n10)});
    }
}
