package pa0;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import hc0.bb;
import hc0.br;
import hc0.db;
import hc0.ew;
import hc0.fb;
import hc0.h6;
import hc0.j2;
import hc0.l2;
import hc0.lk;
import hc0.m00;
import hc0.mu;
import hc0.ou;
import hc0.pm;
import hc0.q00;
import hc0.qu;
import hc0.rk;
import hc0.su;
import hc0.t3;
import hc0.uu;
import hc0.v2;
import hc0.vk;
import hc0.xa;
import hc0.yg;
import hc0.zq;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class d {
    public static final List a;

    static {
        bb.Companion.getClass();
        x xVar = bb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar2 = fb.a;
        m mVar2 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        uu.Companion.getClass();
        a0 a0Var = uu.s;
        List r = l.r(new m[]{mVar, mVar2, new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar), new m("description", xVar2, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        db.Companion.getClass();
        x xVar3 = db.a;
        m mVar3 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        zq.Companion.getClass();
        List r2 = l.r(new m[]{mVar3, new m("nodes", l0.a(zq.a), (String) null, rVar, rVar, r)});
        m mVar4 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar5 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        x xVar4 = ew.a;
        k.g(xVar4, "type");
        m mVar7 = new m("avatarUrl", xVar4, (String) null, rVar, rVar, rVar);
        m mVar8 = new m("description", xVar2, (String) null, rVar, rVar, rVar);
        m mVar9 = new m("targetUrl", xVar4, (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar5 = xa.a;
        r b2 = l0.b(xVar5);
        su.Companion.getClass();
        List r3 = l.r(new m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new m("isRequired", b2, (String) null, rVar, no.a.s(su.b, new u0(new t("prNumber"))), rVar)});
        List r4 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m00.Companion.getClass();
        List r5 = l.r(new m[]{new m("workflow", l0.b(m00.c), (String) null, rVar, rVar, r4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("logoUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        q00.Companion.getClass();
        q0 q0Var = q00.b;
        k.g(q0Var, "type");
        m mVar10 = new m("workflowRun", q0Var, (String) null, rVar, rVar, r5);
        hc0.l0.Companion.getClass();
        q0 q0Var2 = hc0.l0.a;
        k.g(q0Var2, "type");
        List r7 = l.r(new m[]{mVar10, new m("app", q0Var2, (String) null, rVar, rVar, r6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar11 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        j2.Companion.getClass();
        a0 a0Var2 = j2.s;
        k.g(a0Var2, "type");
        m mVar12 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("duration", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar15 = new m("summary", xVar2, (String) null, rVar, rVar, rVar);
        m mVar16 = new m("permalink", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        v2.Companion.getClass();
        m mVar17 = new m("checkSuite", l0.b(v2.f), (String) null, rVar, rVar, r7);
        r b3 = l0.b(xVar5);
        l2.Companion.getClass();
        List r8 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("StatusContext", d0.n("StatusContext"), r3), new n("CheckRun", d0.n("CheckRun"), l.r(new m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new m("isRequired", b3, (String) null, rVar, no.a.s(l2.b, new u0(new t("prNumber"))), rVar)}))});
        m mVar18 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ou.Companion.getClass();
        List r9 = l.r(new m[]{mVar18, new m("nodes", l0.a(ou.a), (String) null, rVar, rVar, r8)});
        m mVar19 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        qu.Companion.getClass();
        r b4 = l0.b(qu.a);
        mu.Companion.getClass();
        List r11 = l.r(new m[]{mVar19, mVar20, new m("contexts", b4, (String) null, rVar, no.a.s(mu.b, new u0(100)), r9), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar21 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        m mVar22 = new m("committedDate", l0.b(h6.a), (String) null, rVar, rVar, rVar);
        q0 q0Var3 = mu.c;
        k.g(q0Var3, "type");
        List r12 = l.r(new m[]{mVar21, mVar22, new m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r11), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar23 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        List r13 = l.r(new m[]{mVar23, new m("commit", l0.b(t3.j), (String) null, rVar, rVar, r12), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar24 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        rk.Companion.getClass();
        List r14 = l.r(new m[]{mVar24, mVar25, new m("nodes", l0.a(rk.a), (String) null, rVar, rVar, r13)});
        m mVar26 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        br.Companion.getClass();
        r b5 = l0.b(br.a);
        lk.Companion.getClass();
        m mVar27 = new m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(lk.u, new u0(25)), r2);
        m mVar28 = new m("actionRequiredWorkflowRunCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        vk.Companion.getClass();
        List r15 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("PullRequest", d0.n("PullRequest"), l.r(new m[]{mVar26, mVar27, mVar28, new m("commits", l0.b(vk.a), (String) null, rVar, no.a.s(lk.k, new u0(1)), r14)})), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yg.Companion.getClass();
        j0 j0Var = yg.a;
        k.g(j0Var, "type");
        pm.Companion.getClass();
        a = d0.n(new m("node", j0Var, (String) null, rVar, no.a.s(pm.f, new u0(new t("id"))), r15));
    }
}
