package kh;

import com.github.rudroid.copilot.h1;
import d2.t;
import x.i;

/* loaded from: /home/user/work/p/classes3.dex */
public final class e {
    public long A;
    public long A0;
    public long B;
    public long B0;
    public long C;
    public long C0;
    public long D;
    public long D0;
    public long E;
    public long E0;
    public long F;
    public long F0;
    public long G;
    public long H;
    public long I;
    public long J;
    public long K;
    public long L;
    public long M;
    public long N;
    public long O;
    public long P;
    public long Q;
    public long R;
    public long S;
    public long T;
    public long U;
    public long V;
    public long W;
    public long X;
    public long Y;
    public long Z;
    public boolean a;
    public long a0;
    public long b;
    public long b0;
    public long c;
    public long c0;
    public long d;
    public long d0;
    public long e;
    public long e0;
    public long f;
    public long f0;
    public long g;
    public long g0;
    public long h;
    public long h0;
    public long i;
    public long i0;
    public long j;
    public long j0;
    public long k;
    public long k0;
    public long l;
    public long l0;
    public long m;
    public long m0;
    public long n;
    public long n0;
    public long o;
    public long o0;
    public long p;
    public long p0;
    public long q;
    public long q0;
    public long r;
    public long r0;
    public long s;
    public long s0;
    public long t;
    public long t0;
    public long u;
    public long u0;
    public long v;
    public long v0;
    public long w;
    public long w0;
    public long x;
    public long x0;
    public long y;
    public long y0;
    public long z;
    public long z0;

    public e(boolean z, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48, long j49, long j51, long j52, long j53, long j54, long j55, long j56, long j57, long j58, long j59, long j61, long j62, long j63, long j64, long j65, long j66, long j67, long j68, long j69, long j71, long j72, long j73, long j74, long j75, long j76, long j77, long j78, long j79, long j81, long j82, long j83, long j84, long j85, long j86, long j87, long j88, long j89, long j91, long j92) {
        this.a = z;
        this.b = j;
        this.c = j2;
        this.d = j3;
        this.e = j4;
        this.f = j5;
        this.g = j6;
        this.h = j7;
        this.i = j8;
        this.j = j9;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j21;
        this.u = j22;
        this.v = j23;
        this.w = j24;
        this.x = j25;
        this.y = j26;
        this.z = j27;
        this.A = j28;
        this.B = j29;
        this.C = j31;
        this.D = j32;
        this.E = j33;
        this.F = j34;
        this.G = j35;
        this.H = j36;
        this.I = j37;
        this.J = j38;
        this.K = j39;
        this.L = j41;
        this.M = j42;
        this.N = j43;
        this.O = j44;
        this.P = j45;
        this.Q = j46;
        this.R = j47;
        this.S = j48;
        this.T = j49;
        this.U = j51;
        this.V = j52;
        this.W = j53;
        this.X = j54;
        this.Y = j55;
        this.Z = j56;
        this.a0 = j57;
        this.b0 = j58;
        this.c0 = j59;
        this.d0 = j61;
        this.e0 = j62;
        this.f0 = j63;
        this.g0 = j64;
        this.h0 = j65;
        this.i0 = j66;
        this.j0 = j67;
        this.k0 = j68;
        this.l0 = j69;
        this.m0 = j71;
        this.n0 = j72;
        this.o0 = j73;
        this.p0 = j74;
        this.q0 = j75;
        this.r0 = j76;
        this.s0 = j77;
        this.t0 = j78;
        this.u0 = j79;
        this.v0 = j81;
        this.w0 = j82;
        this.x0 = j83;
        this.y0 = j84;
        this.z0 = j85;
        this.A0 = j86;
        this.B0 = j87;
        this.C0 = j88;
        this.D0 = j89;
        this.E0 = j91;
        this.F0 = j92;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof e)) {
            return false;
        }
        e eVar = (e) obj;
        return this.a == eVar.a && t.c(this.b, eVar.b) && t.c(this.c, eVar.c) && t.c(this.d, eVar.d) && t.c(this.e, eVar.e) && t.c(this.f, eVar.f) && t.c(this.g, eVar.g) && t.c(this.h, eVar.h) && t.c(this.i, eVar.i) && t.c(this.j, eVar.j) && t.c(this.k, eVar.k) && t.c(this.l, eVar.l) && t.c(this.m, eVar.m) && t.c(this.n, eVar.n) && t.c(this.o, eVar.o) && t.c(this.p, eVar.p) && t.c(this.q, eVar.q) && t.c(this.r, eVar.r) && t.c(this.s, eVar.s) && t.c(this.t, eVar.t) && t.c(this.u, eVar.u) && t.c(this.v, eVar.v) && t.c(this.w, eVar.w) && t.c(this.x, eVar.x) && t.c(this.y, eVar.y) && t.c(this.z, eVar.z) && t.c(this.A, eVar.A) && t.c(this.B, eVar.B) && t.c(this.C, eVar.C) && t.c(this.D, eVar.D) && t.c(this.E, eVar.E) && t.c(this.F, eVar.F) && t.c(this.G, eVar.G) && t.c(this.H, eVar.H) && t.c(this.I, eVar.I) && t.c(this.J, eVar.J) && t.c(this.K, eVar.K) && t.c(this.L, eVar.L) && t.c(this.M, eVar.M) && t.c(this.N, eVar.N) && t.c(this.O, eVar.O) && t.c(this.P, eVar.P) && t.c(this.Q, eVar.Q) && t.c(this.R, eVar.R) && t.c(this.S, eVar.S) && t.c(this.T, eVar.T) && t.c(this.U, eVar.U) && t.c(this.V, eVar.V) && t.c(this.W, eVar.W) && t.c(this.X, eVar.X) && t.c(this.Y, eVar.Y) && t.c(this.Z, eVar.Z) && t.c(this.a0, eVar.a0) && t.c(this.b0, eVar.b0) && t.c(this.c0, eVar.c0) && t.c(this.d0, eVar.d0) && t.c(this.e0, eVar.e0) && t.c(this.f0, eVar.f0) && t.c(this.g0, eVar.g0) && t.c(this.h0, eVar.h0) && t.c(this.i0, eVar.i0) && t.c(this.j0, eVar.j0) && t.c(this.k0, eVar.k0) && t.c(this.l0, eVar.l0) && t.c(this.m0, eVar.m0) && t.c(this.n0, eVar.n0) && t.c(this.o0, eVar.o0) && t.c(this.p0, eVar.p0) && t.c(this.q0, eVar.q0) && t.c(this.r0, eVar.r0) && t.c(this.s0, eVar.s0) && t.c(this.t0, eVar.t0) && t.c(this.u0, eVar.u0) && t.c(this.v0, eVar.v0) && t.c(this.w0, eVar.w0) && t.c(this.x0, eVar.x0) && t.c(this.y0, eVar.y0) && t.c(this.z0, eVar.z0) && t.c(this.A0, eVar.A0) && t.c(this.B0, eVar.B0) && t.c(this.C0, eVar.C0) && t.c(this.D0, eVar.D0) && t.c(this.E0, eVar.E0) && t.c(this.F0, eVar.F0);
    }

    public final int hashCode() {
        int hashCode = Boolean.hashCode(this.a) * 31;
        int i = t.l;
        return Long.hashCode(this.F0) + i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(i.c(hashCode, 31, this.b), 31, this.c), 31, this.d), 31, this.e), 31, this.f), 31, this.g), 31, this.h), 31, this.i), 31, this.j), 31, this.k), 31, this.l), 31, this.m), 31, this.n), 31, this.o), 31, this.p), 31, this.q), 31, this.r), 31, this.s), 31, this.t), 31, this.u), 31, this.v), 31, this.w), 31, this.x), 31, this.y), 31, this.z), 31, this.A), 31, this.B), 31, this.C), 31, this.D), 31, this.E), 31, this.F), 31, this.G), 31, this.H), 31, this.I), 31, this.J), 31, this.K), 31, this.L), 31, this.M), 31, this.N), 31, this.O), 31, this.P), 31, this.Q), 31, this.R), 31, this.S), 31, this.T), 31, this.U), 31, this.V), 31, this.W), 31, this.X), 31, this.Y), 31, this.Z), 31, this.a0), 31, this.b0), 31, this.c0), 31, this.d0), 31, this.e0), 31, this.f0), 31, this.g0), 31, this.h0), 31, this.i0), 31, this.j0), 31, this.k0), 31, this.l0), 31, this.m0), 31, this.n0), 31, this.o0), 31, this.p0), 31, this.q0), 31, this.r0), 31, this.s0), 31, this.t0), 31, this.u0), 31, this.v0), 31, this.w0), 31, this.x0), 31, this.y0), 31, this.z0), 31, this.A0), 31, this.B0), 31, this.C0), 31, this.D0), 31, this.E0);
    }

    public final String toString() {
        String i = t.i(this.b);
        String i2 = t.i(this.c);
        String i3 = t.i(this.d);
        String i4 = t.i(this.e);
        String i5 = t.i(this.f);
        String i6 = t.i(this.g);
        String i7 = t.i(this.h);
        String i8 = t.i(this.i);
        String i9 = t.i(this.j);
        String i11 = t.i(this.k);
        String i12 = t.i(this.l);
        String i13 = t.i(this.m);
        String i14 = t.i(this.n);
        String i15 = t.i(this.o);
        String i16 = t.i(this.p);
        String i17 = t.i(this.q);
        String i18 = t.i(this.r);
        String i19 = t.i(this.s);
        String i21 = t.i(this.t);
        String i22 = t.i(this.u);
        String i23 = t.i(this.v);
        String i24 = t.i(this.w);
        String i25 = t.i(this.x);
        String i26 = t.i(this.y);
        String i27 = t.i(this.z);
        String i28 = t.i(this.A);
        String i29 = t.i(this.B);
        String i31 = t.i(this.C);
        String i32 = t.i(this.D);
        String i33 = t.i(this.E);
        String i34 = t.i(this.F);
        String i35 = t.i(this.G);
        String i36 = t.i(this.H);
        String i37 = t.i(this.I);
        String i38 = t.i(this.J);
        String i39 = t.i(this.K);
        String i41 = t.i(this.L);
        String i42 = t.i(this.M);
        String i43 = t.i(this.N);
        String i44 = t.i(this.O);
        String i45 = t.i(this.P);
        String i46 = t.i(this.Q);
        String i47 = t.i(this.R);
        String i48 = t.i(this.S);
        String i49 = t.i(this.T);
        String i51 = t.i(this.U);
        String i52 = t.i(this.V);
        String i53 = t.i(this.W);
        String i54 = t.i(this.X);
        String i55 = t.i(this.Y);
        String i56 = t.i(this.Z);
        String i57 = t.i(this.a0);
        String i58 = t.i(this.b0);
        String i59 = t.i(this.c0);
        String i61 = t.i(this.d0);
        String i62 = t.i(this.e0);
        String i63 = t.i(this.f0);
        String i64 = t.i(this.g0);
        String i65 = t.i(this.h0);
        String i66 = t.i(this.i0);
        String i67 = t.i(this.j0);
        String i68 = t.i(this.k0);
        String i69 = t.i(this.l0);
        String i71 = t.i(this.m0);
        String i72 = t.i(this.n0);
        String i73 = t.i(this.o0);
        String i74 = t.i(this.p0);
        String i75 = t.i(this.q0);
        String i76 = t.i(this.r0);
        String i77 = t.i(this.s0);
        String i78 = t.i(this.t0);
        String i79 = t.i(this.u0);
        String i81 = t.i(this.v0);
        String i82 = t.i(this.w0);
        String i83 = t.i(this.x0);
        String i84 = t.i(this.y0);
        String i85 = t.i(this.z0);
        String i86 = t.i(this.A0);
        String i87 = t.i(this.B0);
        String i88 = t.i(this.C0);
        String i89 = t.i(this.D0);
        String i91 = t.i(this.E0);
        String i92 = t.i(this.F0);
        StringBuilder t = h1.t("PrimerPalette(isLight=", ", Red400=", i, ", Red500=", this.a);
        f1.e.x(t, i2, ", Red600=", i3, ", Gray000=");
        f1.e.x(t, i4, ", Gray050=", i5, ", Gray100=");
        f1.e.x(t, i6, ", Gray150=", i7, ", Gray200=");
        f1.e.x(t, i8, ", Gray250=", i9, ", Gray300=");
        f1.e.x(t, i11, ", Gray350=", i12, ", Gray400=");
        f1.e.x(t, i13, ", Gray500=", i14, ", Gray550=");
        f1.e.x(t, i15, ", Gray600=", i16, ", Gray650=");
        f1.e.x(t, i17, ", Gray700=", i18, ", Gray800=");
        f1.e.x(t, i19, ", Gray850=", i21, ", Gray900=");
        f1.e.x(t, i22, ", Gray1000=", i23, ", Green300=");
        f1.e.x(t, i24, ", Green400=", i25, ", Green500=");
        f1.e.x(t, i26, ", Green600=", i27, ", Green700=");
        f1.e.x(t, i28, ", Green900=", i29, ", Blue000=");
        f1.e.x(t, i31, ", Blue100=", i32, ", Blue200=");
        f1.e.x(t, i33, ", Blue300=", i34, ", Blue400=");
        f1.e.x(t, i35, ", Blue500=", i36, ", Blue600=");
        f1.e.x(t, i37, ", Blue700=", i38, ", Blue800=");
        f1.e.x(t, i39, ", Blue900=", i41, ", AccentMuted=");
        f1.e.x(t, i42, ", Purple000=", i43, ", Purple050=");
        f1.e.x(t, i44, ", Purple100=", i45, ", Purple200=");
        f1.e.x(t, i46, ", Purple400=", i47, ", Purple500=");
        f1.e.x(t, i48, ", Purple600=", i49, ", Orange400=");
        f1.e.x(t, i51, ", Orange500=", i52, ", Orange600=");
        f1.e.x(t, i53, ", Pink500=", i54, ", Pink600=");
        f1.e.x(t, i55, ", Yellow100=", i56, ", Yellow500=");
        f1.e.x(t, i57, ", Yellow600=", i58, ", Yellow700=");
        f1.e.x(t, i59, ", Yellow800=", i61, ", BadgeBlueBackground=");
        f1.e.x(t, i62, ", BadgeBlueLabel=", i63, ", BadgeBlueStroke=");
        f1.e.x(t, i64, ", BadgeDisabledBlue=", i65, ", BadgeDisabledGray=");
        f1.e.x(t, i66, ", BadgeGrayBackground=", i67, ", BadgeGrayLabel=");
        f1.e.x(t, i68, ", BadgeGrayStroke=", i69, ", BadgeGreenBackground=");
        f1.e.x(t, i71, ", BadgeGreenLabel=", i72, ", BadgeGreenStroke=");
        f1.e.x(t, i73, ", BadgeOrangeBackground=", i74, ", BadgeOrangeLabel=");
        f1.e.x(t, i75, ", BadgeOrangeStroke=", i76, ", BadgePurpleBackground=");
        f1.e.x(t, i77, ", BadgePurpleLabel=", i78, ", BadgePurpleStroke=");
        f1.e.x(t, i79, ", BadgeRedBackground=", i81, ", BadgeRedLabel=");
        f1.e.x(t, i82, ", BadgeRedStroke=", i83, ", BadgeYellowBackground=");
        f1.e.x(t, i84, ", BadgeYellowLabel=", i85, ", BadgeYellowStroke=");
        f1.e.x(t, i86, ", BadgePinkBackground=", i87, ", BadgePinkLabel=");
        f1.e.x(t, i88, ", BadgePinkStroke=", i89, ", Border=");
        return i.k(t, i91, ", BorderOpaque=", i92, ")");
    }
}
