package ri0;

import gn0.gg;
import gn0.hn;
import gn0.pm;
import java.time.ZonedDateTime;
import java.util.ArrayList;

/* loaded from: /home/user/work/p/classes4.dex */
public final class y5 implements aa.h0 {
    public final pm A;
    public final boolean B;
    public final q5 C;
    public final m4 D;
    public final String E;
    public final t4 F;
    public final String G;
    public final b5 H;
    public final n5 I;
    public final r5 J;
    public final w4 K;
    public final v4 L;
    public final ArrayList M;
    public final int N;
    public final r4 O;
    public final v5 P;
    public final boolean Q;
    public final boolean R;
    public final boolean S;
    public final boolean T;
    public final boolean U;
    public final se0.c V;
    public final aj0.c W;
    public final yh0.a X;
    public final yd0.i Y;
    public final sg0.j Z;
    public final String a;
    public final yg0.e a0;
    public final String b;
    public final sk0.a b0;
    public final String c;
    public final a8 c0;
    public final String d;
    public final b d0;
    public final u4 e;
    public final n4 f;
    public final String g;
    public final String h;
    public final ZonedDateTime i;
    public final boolean j;
    public final boolean k;
    public final boolean l;
    public final boolean m;
    public final l4 n;
    public final Boolean o;
    public final String p;
    public final int q;
    public final hn r;
    public final int s;
    public final int t;
    public final int u;
    public final gg v;
    public final a5 w;
    public final x4 x;
    public final y4 y;
    public final z4 z;

    public y5(String str, String str2, String str3, String str4, u4 u4Var, n4 n4Var, String str5, String str6, ZonedDateTime zonedDateTime, boolean z, boolean z2, boolean z3, boolean z4, l4 l4Var, Boolean bool, String str7, int i, hn hnVar, int i2, int i3, int i4, gg ggVar, a5 a5Var, x4 x4Var, y4 y4Var, z4 z4Var, pm pmVar, boolean z5, q5 q5Var, m4 m4Var, String str8, t4 t4Var, String str9, b5 b5Var, n5 n5Var, r5 r5Var, w4 w4Var, v4 v4Var, ArrayList arrayList, int i5, r4 r4Var, v5 v5Var, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, se0.c cVar, aj0.c cVar2, yh0.a aVar, yd0.i iVar, sg0.j jVar, yg0.e eVar, sk0.a aVar2, a8 a8Var, b bVar) {
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = str4;
        this.e = u4Var;
        this.f = n4Var;
        this.g = str5;
        this.h = str6;
        this.i = zonedDateTime;
        this.j = z;
        this.k = z2;
        this.l = z3;
        this.m = z4;
        this.n = l4Var;
        this.o = bool;
        this.p = str7;
        this.q = i;
        this.r = hnVar;
        this.s = i2;
        this.t = i3;
        this.u = i4;
        this.v = ggVar;
        this.w = a5Var;
        this.x = x4Var;
        this.y = y4Var;
        this.z = z4Var;
        this.A = pmVar;
        this.B = z5;
        this.C = q5Var;
        this.D = m4Var;
        this.E = str8;
        this.F = t4Var;
        this.G = str9;
        this.H = b5Var;
        this.I = n5Var;
        this.J = r5Var;
        this.K = w4Var;
        this.L = v4Var;
        this.M = arrayList;
        this.N = i5;
        this.O = r4Var;
        this.P = v5Var;
        this.Q = z6;
        this.R = z7;
        this.S = z8;
        this.T = z9;
        this.U = z10;
        this.V = cVar;
        this.W = cVar2;
        this.X = aVar;
        this.Y = iVar;
        this.Z = jVar;
        this.a0 = eVar;
        this.b0 = aVar2;
        this.c0 = a8Var;
        this.d0 = bVar;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof y5)) {
            return false;
        }
        y5 y5Var = (y5) obj;
        return this.a.equals(y5Var.a) && this.b.equals(y5Var.b) && this.c.equals(y5Var.c) && this.d.equals(y5Var.d) && k71.k.b(this.e, y5Var.e) && k71.k.b(this.f, y5Var.f) && this.g.equals(y5Var.g) && this.h.equals(y5Var.h) && this.i.equals(y5Var.i) && this.j == y5Var.j && this.k == y5Var.k && this.l == y5Var.l && this.m == y5Var.m && k71.k.b(this.n, y5Var.n) && k71.k.b(this.o, y5Var.o) && this.p.equals(y5Var.p) && this.q == y5Var.q && this.r == y5Var.r && this.s == y5Var.s && this.t == y5Var.t && this.u == y5Var.u && this.v == y5Var.v && k71.k.b(this.w, y5Var.w) && k71.k.b(this.x, y5Var.x) && k71.k.b(this.y, y5Var.y) && k71.k.b(this.z, y5Var.z) && this.A == y5Var.A && this.B == y5Var.B && this.C.equals(y5Var.C) && k71.k.b(this.D, y5Var.D) && this.E.equals(y5Var.E) && k71.k.b(this.F, y5Var.F) && this.G.equals(y5Var.G) && k71.k.b(this.H, y5Var.H) && this.I.equals(y5Var.I) && k71.k.b(this.J, y5Var.J) && k71.k.b(this.K, y5Var.K) && k71.k.b(this.L, y5Var.L) && this.M.equals(y5Var.M) && this.N == y5Var.N && this.O.equals(y5Var.O) && k71.k.b(this.P, y5Var.P) && this.Q == y5Var.Q && this.R == y5Var.R && this.S == y5Var.S && this.T == y5Var.T && this.U == y5Var.U && this.V.equals(y5Var.V) && this.W.equals(y5Var.W) && this.X.equals(y5Var.X) && this.Y.equals(y5Var.Y) && this.Z.equals(y5Var.Z) && this.a0.equals(y5Var.a0) && this.b0.equals(y5Var.b0) && this.c0.equals(y5Var.c0) && this.d0.equals(y5Var.d0);
    }

    public final int hashCode() {
        int i = com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(this.a.hashCode() * 31, this.b, 31), this.c, 31), this.d, 31);
        u4 u4Var = this.e;
        int hashCode = (i + (u4Var == null ? 0 : u4Var.hashCode())) * 31;
        n4 n4Var = this.f;
        int e = x.i.e(x.i.e(x.i.e(x.i.e(com.github.rudroid.m0.a(this.i, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i((hashCode + (n4Var == null ? 0 : n4Var.hashCode())) * 31, this.g, 31), this.h, 31), 31), 31, this.j), 31, this.k), 31, this.l), 31, this.m);
        l4 l4Var = this.n;
        int hashCode2 = (e + (l4Var == null ? 0 : l4Var.hashCode())) * 31;
        Boolean bool = this.o;
        int hashCode3 = (this.v.hashCode() + a0.s0.b(this.u, a0.s0.b(this.t, a0.s0.b(this.s, (this.r.hashCode() + a0.s0.b(this.q, com.github.rudroid.copilot.h1.i((hashCode2 + (bool == null ? 0 : bool.hashCode())) * 31, this.p, 31), 31)) * 31, 31), 31), 31)) * 31;
        a5 a5Var = this.w;
        int hashCode4 = (hashCode3 + (a5Var == null ? 0 : a5Var.hashCode())) * 31;
        x4 x4Var = this.x;
        int hashCode5 = (hashCode4 + (x4Var == null ? 0 : x4Var.hashCode())) * 31;
        y4 y4Var = this.y;
        int hashCode6 = (hashCode5 + (y4Var == null ? 0 : y4Var.hashCode())) * 31;
        z4 z4Var = this.z;
        int hashCode7 = (hashCode6 + (z4Var == null ? 0 : z4Var.hashCode())) * 31;
        pm pmVar = this.A;
        int hashCode8 = (this.C.hashCode() + x.i.e((hashCode7 + (pmVar == null ? 0 : pmVar.hashCode())) * 31, 31, this.B)) * 31;
        m4 m4Var = this.D;
        int i2 = com.github.rudroid.copilot.h1.i((hashCode8 + (m4Var == null ? 0 : m4Var.hashCode())) * 31, this.E, 31);
        t4 t4Var = this.F;
        int i3 = com.github.rudroid.copilot.h1.i((i2 + (t4Var == null ? 0 : t4Var.hashCode())) * 31, this.G, 31);
        b5 b5Var = this.H;
        int hashCode9 = (this.I.hashCode() + ((i3 + (b5Var == null ? 0 : b5Var.hashCode())) * 31)) * 31;
        r5 r5Var = this.J;
        int hashCode10 = (hashCode9 + (r5Var == null ? 0 : r5Var.hashCode())) * 31;
        w4 w4Var = this.K;
        int hashCode11 = (hashCode10 + (w4Var == null ? 0 : w4Var.hashCode())) * 31;
        v4 v4Var = this.L;
        int hashCode12 = (this.O.hashCode() + a0.s0.b(this.N, no.a.b(this.M, (hashCode11 + (v4Var == null ? 0 : v4Var.hashCode())) * 31, 31), 31)) * 31;
        v5 v5Var = this.P;
        return this.d0.hashCode() + ((this.c0.hashCode() + ((this.b0.hashCode() + ((this.a0.hashCode() + ((this.Z.hashCode() + ((this.Y.hashCode() + ((this.X.hashCode() + ((this.W.hashCode() + ((this.V.hashCode() + x.i.e(x.i.e(x.i.e(x.i.e(x.i.e((hashCode12 + (v5Var != null ? v5Var.hashCode() : 0)) * 31, 31, this.Q), 31, this.R), 31, this.S), 31, this.T), 31, this.U)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder o = a0.s0.o("RepositoryNodeFragmentPullRequest(__typename=", this.a, ", url=", this.b, ", id=");
        f1.e.x(o, this.c, ", headRefOid=", this.d, ", headRepository=");
        o.append(this.e);
        o.append(", baseRepository=");
        o.append(this.f);
        o.append(", title=");
        f1.e.x(o, this.g, ", titleHTML=", this.h, ", createdAt=");
        com.github.rudroid.m0.v(", viewerCanDeleteHeadRef=", ", viewerDidAuthor=", o, this.i, this.j);
        com.github.rudroid.m0.A(o, this.k, ", viewerCanChangeBaseBranch=", this.l, ", locked=");
        o.append(this.m);
        o.append(", author=");
        o.append(this.n);
        o.append(", isReadByViewer=");
        o.append(this.o);
        o.append(", bodyHtml=");
        o.append(this.p);
        o.append(", number=");
        o.append(this.q);
        o.append(", pullRequestState=");
        o.append(this.r);
        o.append(", changedFiles=");
        a0.s0.z(o, this.s, ", additions=", this.t, ", deletions=");
        o.append(this.u);
        o.append(", mergeStateStatus=");
        o.append(this.v);
        o.append(", mergedBy=");
        o.append(this.w);
        o.append(", mergeCommit=");
        o.append(this.x);
        o.append(", mergeQueue=");
        o.append(this.y);
        o.append(", mergeQueueEntry=");
        o.append(this.z);
        o.append(", reviewDecision=");
        o.append(this.A);
        o.append(", isDraft=");
        o.append(this.B);
        o.append(", requiredStatusChecks=");
        o.append(this.C);
        o.append(", baseRef=");
        o.append(this.D);
        o.append(", baseRefName=");
        o.append(this.E);
        o.append(", headRef=");
        o.append(this.F);
        o.append(", headRefName=");
        o.append(this.G);
        o.append(", milestone=");
        o.append(this.H);
        o.append(", projectCards=");
        o.append(this.I);
        o.append(", reviewRequests=");
        o.append(this.J);
        o.append(", latestReviews=");
        o.append(this.K);
        o.append(", latestOpinionatedReviews=");
        o.append(this.L);
        o.append(", suggestedReviewers=");
        o.append(this.M);
        o.append(", actionRequiredWorkflowRunCount=");
        o.append(this.N);
        o.append(", commits=");
        o.append(this.O);
        o.append(", viewerLatestReview=");
        o.append(this.P);
        o.append(", viewerCanReopen=");
        com.github.rudroid.m0.A(o, this.Q, ", viewerCanMergeAsAdmin=", this.R, ", viewerCanAssign=");
        com.github.rudroid.m0.A(o, this.S, ", viewerCanLabel=", this.T, ", viewerCanUpdateBranch=");
        o.append(this.U);
        o.append(", commentFragment=");
        o.append(this.V);
        o.append(", reactionFragment=");
        o.append(this.W);
        o.append(", orgBlockableFragment=");
        o.append(this.X);
        o.append(", assigneeFragment=");
        o.append(this.Y);
        o.append(", labelsFragment=");
        o.append(this.Z);
        o.append(", linkedIssues=");
        o.append(this.a0);
        o.append(", updatableFields=");
        o.append(this.b0);
        o.append(", viewerLatestReviewRequestFragment=");
        o.append(this.c0);
        o.append(", autoMergeRequestFragment=");
        o.append(this.d0);
        o.append(")");
        return o.toString();
    }
}
