pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url = uri('https://chaquo.com/maven') }
        gradlePluginPortal()
    }
    plugins {
        id 'com.android.application' version '8.0.2'
        id 'com.chaquo.python' version '14.0.2'
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'pythonTemplate'
