package cm0;

import aa.a0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import gn0.dj;
import gn0.dq;
import gn0.eq;
import gn0.gr;
import gn0.hn;
import gn0.hr;
import gn0.i9;
import gn0.ii;
import gn0.jj;
import gn0.kb;
import gn0.kw;
import gn0.l2;
import gn0.lb;
import gn0.lx;
import gn0.mx;
import gn0.ob;
import gn0.oi;
import gn0.pb;
import gn0.q6;
import gn0.qb;
import gn0.qi;
import gn0.r00;
import gn0.r2;
import gn0.r6;
import gn0.rb;
import gn0.s00;
import gn0.sb;
import gn0.tb;
import gn0.ti;
import gn0.u10;
import gn0.u9;
import gn0.vb;
import gn0.vi;
import gn0.x2;
import gn0.xc;
import gn0.xi;
import gn0.zc;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;
import xk0.j;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class a {
    public static final List a;

    static {
        lb.Companion.getClass();
        r b = l0.b(lb.a);
        x61.r rVar = x61.r.r;
        m mVar = new m("hasNextPage", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar = tb.a;
        k.g(xVar, "type");
        List r = l.r(new m[]{mVar, new m("endCursor", xVar, (String) null, rVar, rVar, rVar)});
        s mVar2 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r2 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.b.a;
        s c = no.a.c(list, "selections", "Actor", r2, list);
        s mVar3 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        pb.Companion.getClass();
        x xVar2 = pb.a;
        List r3 = l.r(new s[]{mVar2, c, mVar3, new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar4 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r4 = l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list2 = cl0.a.a;
        s c2 = no.a.c(list2, "selections", "Node", r4, list2);
        kw.Companion.getClass();
        a0 a0Var = kw.s;
        k.g(a0Var, "type");
        List r5 = l.r(new s[]{mVar4, c2, new m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar)});
        List o = d0.o(new m[]{new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        hr.Companion.getClass();
        List o2 = d0.o(new m[]{mVar5, new m("owner", l0.b(gr.a()), (String) null, rVar, rVar, o), new m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        m mVar6 = new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        x a2 = sb.a();
        k.g(a2, "type");
        List o3 = d0.o(new m[]{mVar6, new m("name", a2, "userName", rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        List o4 = d0.o(new m[]{new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        dj.Companion.getClass();
        List o5 = d0.o(new s[]{new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new n("Subscribable", d0.o(new String[]{"Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team", "TeamDiscussion"}), r5), new n("Repository", d0.n("Repository"), o2), new n("User", d0.n("User"), o3), new n("Team", d0.n("Team"), d0.o(new m[]{new m("organization", l0.b(dj.m), (String) null, rVar, rVar, o4), new m("slug", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)})), new n("Organization", d0.n("Organization"), d0.o(new m[]{new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)}))});
        m mVar7 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("abbreviatedOid", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        List o6 = d0.o(new m[]{mVar7, mVar8, new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar)});
        List o7 = d0.o(new m[]{new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        List o8 = d0.o(new m[]{new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        m mVar9 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar10 = new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        l2.Companion.getClass();
        a0 a0Var2 = l2.s;
        k.g(a0Var2, "type");
        m mVar11 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        r2.Companion.getClass();
        List o9 = d0.o(new m[]{mVar9, mVar10, mVar11, new m("status", l0.b(r2.s), (String) null, rVar, rVar, rVar)});
        List o10 = d0.o(new m[]{new m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        List o12 = d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        m mVar12 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar13 = new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        m mVar14 = new m("runNumber", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        u10.Companion.getClass();
        m mVar15 = new m("workflow", l0.b(u10.c), (String) null, rVar, rVar, o10);
        x2.Companion.getClass();
        List o13 = d0.o(new m[]{mVar12, mVar13, mVar14, mVar15, new m("checkSuite", l0.b(x2.f), (String) null, rVar, rVar, o12)});
        List o14 = d0.o(new m[]{new m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(gr.a()), (String) null, rVar, rVar, d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(lx.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        m mVar16 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("number", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        xc.Companion.getClass();
        m mVar19 = new m("state", l0.b(xc.s), "issueState", rVar, rVar, rVar);
        eq.Companion.getClass();
        m mVar20 = new m("repository", l0.b(dq.a()), (String) null, rVar, rVar, o14);
        zc.Companion.getClass();
        a0 a0Var3 = zc.s;
        k.g(a0Var3, "type");
        List o15 = d0.o(new m[]{mVar16, mVar17, mVar18, mVar19, mVar20, new m("stateReason", a0Var3, (String) null, rVar, rVar, rVar), new m("titleHTML", l0.b(sb.a()), "titleHTMLString", rVar, rVar, rVar)});
        List o16 = d0.o(new m[]{new m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(gr.a()), (String) null, rVar, rVar, d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(lx.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        m mVar21 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar22 = new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("isDraft", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("number", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        hn.Companion.getClass();
        m mVar25 = new m("state", l0.b(hn.s), "pullRequestState", rVar, rVar, rVar);
        m mVar26 = new m("repository", l0.b(dq.a()), (String) null, rVar, rVar, o16);
        m mVar27 = new m("isInMergeQueue", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        vb.Companion.getClass();
        List o17 = d0.o(new m[]{mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, new m("titleHTML", l0.b(vb.a), (String) null, rVar, rVar, rVar)});
        List o18 = d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("tagName", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar), new m("repository", l0.b(dq.a()), (String) null, rVar, rVar, d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(gr.a()), (String) null, rVar, rVar, d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(lx.a()), (String) null, rVar, rVar, rVar)})), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)}))});
        List o19 = d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(lx.a()), (String) null, rVar, rVar, rVar)});
        List o20 = d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(lx.a()), (String) null, rVar, rVar, rVar)});
        List o22 = d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar)});
        List o23 = d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        List o24 = d0.o(new m[]{new m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(gr.a()), (String) null, rVar, rVar, d0.o(new m[]{new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(lx.a()), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        m mVar28 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar29 = new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("number", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        u9.Companion.getClass();
        a0 a0Var4 = u9.s;
        k.g(a0Var4, "type");
        m mVar31 = new m("stateReason", a0Var4, "discussionStateReason", rVar, rVar, rVar);
        i9.Companion.getClass();
        q0 q0Var = i9.c;
        k.g(q0Var, "type");
        List o25 = d0.o(new m[]{mVar28, mVar29, mVar30, mVar31, new m("answer", q0Var, (String) null, rVar, rVar, o23), new m("repository", l0.b(dq.a()), (String) null, rVar, rVar, o24)});
        m mVar32 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        x a3 = lx.a();
        k.g(a3, "type");
        List o26 = d0.o(new m[]{mVar32, new m("notificationsPermalink", a3, (String) null, rVar, rVar, rVar)});
        m mVar33 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        x a4 = lx.a();
        k.g(a4, "type");
        List o27 = d0.o(new s[]{new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new n("Commit", d0.n("Commit"), o6), new n("Gist", d0.n("Gist"), o7), new n("TeamDiscussion", d0.n("TeamDiscussion"), o8), new n("CheckSuite", d0.n("CheckSuite"), o9), new n("WorkflowRun", d0.n("WorkflowRun"), o13), new n("Issue", d0.n("Issue"), o15), new n("PullRequest", d0.n("PullRequest"), o17), new n("Release", d0.n("Release"), o18), new n("RepositoryInvitation", d0.n("RepositoryInvitation"), o19), new n("RepositoryVulnerabilityAlert", d0.n("RepositoryVulnerabilityAlert"), o20), new n("RepositoryAdvisory", d0.n("RepositoryAdvisory"), o22), new n("Discussion", d0.n("Discussion"), o25), new n("RepositoryDependabotAlertsThread", d0.n("RepositoryDependabotAlertsThread"), o26), new n("SecurityAdvisory", d0.n("SecurityAdvisory"), d0.o(new m[]{mVar33, new m("notificationsPermalink", a4, (String) null, rVar, rVar, rVar)})), new n("MemberFeatureRequestNotification", d0.n("MemberFeatureRequestNotification"), d0.n(new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)))});
        m mVar34 = new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        m mVar35 = new m("threadType", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        m mVar36 = new m("title", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        m mVar37 = new m("isUnread", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        m mVar38 = new m("unreadItemsCount", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        r6.Companion.getClass();
        m mVar39 = new m("lastUpdatedAt", l0.b(q6.a()), (String) null, rVar, rVar, rVar);
        ti.Companion.getClass();
        m mVar40 = new m("subscriptionStatus", l0.b(ti.s), (String) null, rVar, rVar, rVar);
        s00.Companion.getClass();
        q0 q0Var2 = s00.P;
        k.g(q0Var2, "type");
        m mVar41 = new m("summaryItemAuthor", q0Var2, (String) null, rVar, rVar, r3);
        x a5 = sb.a();
        k.g(a5, "type");
        m mVar42 = new m("summaryItemBody", a5, (String) null, rVar, rVar, rVar);
        m mVar43 = new m("isArchived", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        m mVar44 = new m("isSaved", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        m mVar45 = new m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        vi.Companion.getClass();
        m mVar46 = new m("list", l0.b(vi.a), (String) null, rVar, rVar, o5);
        ii.Companion.getClass();
        a0 a0Var5 = ii.s;
        k.g(a0Var5, "type");
        m mVar47 = new m("reason", a0Var5, (String) null, rVar, rVar, rVar);
        xi.Companion.getClass();
        List o28 = d0.o(new m[]{mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, new m("subject", l0.b(xi.a), (String) null, rVar, rVar, o27), new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        jj.Companion.getClass();
        m mVar48 = new m("pageInfo", l0.b(jj.a), (String) null, rVar, rVar, r);
        oi.Companion.getClass();
        List o29 = d0.o(new m[]{mVar48, new m("nodes", l0.a(oi.a), (String) null, rVar, rVar, o28)});
        s mVar49 = new m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List n = d0.n("User");
        List a6 = j.a();
        s c3 = no.a.c(a6, "selections", "User", n, a6);
        qi.Companion.getClass();
        r b2 = l0.b(qi.a);
        r00 r00Var = s00.Companion;
        aa.k kVar = new aa.k(s00.p, new u0(new t("after")));
        r00 r00Var2 = s00.Companion;
        aa.k kVar2 = new aa.k(s00.q, new u0(new t("filterBy")));
        r00 r00Var3 = s00.Companion;
        aa.k kVar3 = new aa.k(s00.r, new u0(new t("first")));
        r00 r00Var4 = s00.Companion;
        a = d0.n(new m("viewer", l0.b(q0Var2), (String) null, rVar, rVar, d0.o(new s[]{mVar49, c3, new m("notificationThreads", b2, (String) null, rVar, d0.o(new aa.k[]{kVar, kVar2, kVar3, new aa.k(s00.s, new u0(new t("query")))}), o29), new m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)})));
    }
}
