package dy;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.ch0;
import m10.da0;
import m10.dy;
import m10.eh;
import m10.h1;
import m10.h4;
import m10.hy;
import m10.l50;
import m10.n50;
import m10.p00;
import m10.p90;
import m10.r90;
import m10.sa;
import m10.t3;
import m10.t90;
import m10.tg0;
import m10.ux;
import m10.v3;
import m10.wg;
import m10.x90;
import m10.y5;
import m10.zp;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class h {
    public static final List a;

    static {
        ah.Companion.getClass();
        x xVar = ah.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        x xVar2 = eh.a;
        m mVar2 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        da0.Companion.getClass();
        a0 a0Var = da0.s;
        List r = x61.l.r(new m[]{mVar, mVar2, new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar), new m("description", xVar2, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ch.Companion.getClass();
        x xVar3 = ch.a;
        m mVar3 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        l50.Companion.getClass();
        List r2 = x61.l.r(new m[]{mVar3, new m("nodes", l0.a(l50.a), (String) null, rVar, rVar, r)});
        m mVar4 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar5 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        x xVar4 = cc0.a;
        k71.k.g(xVar4, "type");
        m mVar7 = new m("avatarUrl", xVar4, (String) null, rVar, rVar, rVar);
        m mVar8 = new m("description", xVar2, (String) null, rVar, rVar, rVar);
        m mVar9 = new m("targetUrl", xVar4, (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar5 = wg.a;
        r b2 = l0.b(xVar5);
        x90.Companion.getClass();
        List r3 = x61.l.r(new m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new m("isRequired", b2, (String) null, rVar, no.a.s(x90.b, new u0(new t("prNumber"))), rVar)});
        List r4 = x61.l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        tg0.Companion.getClass();
        List r5 = x61.l.r(new m[]{new m("workflow", l0.b(tg0.e), (String) null, rVar, rVar, r4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = x61.l.r(new m[]{new m("logoUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ch0.Companion.getClass();
        q0 q0Var = ch0.b;
        k71.k.g(q0Var, "type");
        m mVar10 = new m("workflowRun", q0Var, (String) null, rVar, rVar, r5);
        h1.Companion.getClass();
        q0 q0Var2 = h1.a;
        k71.k.g(q0Var2, "type");
        List r7 = x61.l.r(new m[]{mVar10, new m("app", q0Var2, (String) null, rVar, rVar, r6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar11 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        a0 a0Var2 = t3.s;
        k71.k.g(a0Var2, "type");
        m mVar12 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("duration", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar15 = new m("summary", xVar2, (String) null, rVar, rVar, rVar);
        m mVar16 = new m("permalink", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        h4.Companion.getClass();
        m mVar17 = new m("checkSuite", l0.b(h4.f), (String) null, rVar, rVar, r7);
        r b3 = l0.b(xVar5);
        v3.Companion.getClass();
        List r8 = x61.l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("StatusContext", d0.n("StatusContext"), r3), new n("CheckRun", d0.n("CheckRun"), x61.l.r(new m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new m("isRequired", b3, (String) null, rVar, no.a.s(v3.b, new u0(new t("prNumber"))), rVar)}))});
        m mVar18 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        r90.Companion.getClass();
        List r9 = x61.l.r(new m[]{mVar18, new m("nodes", l0.a(r90.a), (String) null, rVar, rVar, r8)});
        m mVar19 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        t90.Companion.getClass();
        r b4 = l0.b(t90.a);
        p90.Companion.getClass();
        List r11 = x61.l.r(new m[]{mVar19, mVar20, new m("contexts", b4, (String) null, rVar, no.a.s(p90.b, new u0(100)), r9), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar21 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        m mVar22 = new m("committedDate", l0.b(sa.a), (String) null, rVar, rVar, rVar);
        q0 q0Var3 = p90.c;
        k71.k.g(q0Var3, "type");
        List r12 = x61.l.r(new m[]{mVar21, mVar22, new m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r11), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar23 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        y5.Companion.getClass();
        List r13 = x61.l.r(new m[]{mVar23, new m("commit", l0.b(y5.j), (String) null, rVar, rVar, r12), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar24 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        dy.Companion.getClass();
        List r14 = x61.l.r(new m[]{mVar24, mVar25, new m("nodes", l0.a(dy.a), (String) null, rVar, rVar, r13)});
        m mVar26 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        n50.Companion.getClass();
        r b5 = l0.b(n50.a);
        ux.Companion.getClass();
        m mVar27 = new m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(ux.C, new u0(25)), r2);
        m mVar28 = new m("actionRequiredWorkflowRunCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        hy.Companion.getClass();
        List r15 = x61.l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("PullRequest", d0.n("PullRequest"), x61.l.r(new m[]{mVar26, mVar27, mVar28, new m("commits", l0.b(hy.a), (String) null, rVar, no.a.s(ux.l, new u0(1)), r14)})), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        zp.Companion.getClass();
        j0 j0Var = zp.a;
        k71.k.g(j0Var, "type");
        p00.Companion.getClass();
        a = x61.l.r(new m[]{new m("node", j0Var, (String) null, rVar, no.a.s(p00.i, new u0(new t("id"))), r15), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
