package td0;

import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import aa.x0;
import gn0.d4;
import gn0.eq;
import gn0.fb;
import gn0.ga;
import gn0.hb;
import gn0.hr;
import gn0.ix;
import gn0.la;
import gn0.lb;
import gn0.mo;
import gn0.mx;
import gn0.pb;
import gn0.rb;
import gn0.tb;
import gn0.vb;
import java.util.List;
import k71.k;
import sy.d0Shadow;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class e {
    public static final List a;

    static {
        tb.Companion.getClass();
        x xVar = tb.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        s mVar = new m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("FileLine");
        List list = fg0.a.a;
        List r = l.r(new s[]{mVar, no.a.c(list, "selections", "FileLine", n, list)});
        vb.Companion.getClass();
        x xVar2 = vb.a;
        k.g(xVar2, "type");
        m mVar2 = new m("contentHTML", xVar2, (String) null, rVar, rVar, rVar);
        la.Companion.getClass();
        q0 q0Var = la.a;
        List r2 = l.r(new m[]{mVar2, new m("fileLines", l0.a(q0Var), "markDownFileLines", rVar, rVar, r)});
        mx.Companion.getClass();
        x xVar3 = mx.a;
        k.g(xVar3, "type");
        List r3 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("MarkdownFileType", d0Shadow.n("MarkdownFileType"), r2), new n("ImageFileType", d0Shadow.n("ImageFileType"), d0Shadow.n(new m("url", xVar3, (String) null, rVar, rVar, rVar))), new n("PdfFileType", d0Shadow.n("PdfFileType"), d0Shadow.n(new m("url", xVar3, (String) null, rVar, rVar, rVar))), new n("TextFileType", d0Shadow.n("TextFileType"), d0Shadow.n(new m("fileLines", l0.a(q0Var), "textFieldFileLines", rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("FileLine", d0Shadow.n("FileLine"), list)}))))});
        m mVar3 = new m("extension", xVar, (String) null, rVar, rVar, rVar);
        m mVar4 = new m("path", xVar, (String) null, rVar, rVar, rVar);
        ga.Companion.getClass();
        x0 x0Var = ga.a;
        k.g(x0Var, "type");
        List r4 = l.r(new m[]{mVar3, mVar4, new m("fileType", x0Var, (String) null, rVar, rVar, r3)});
        ix.Companion.getClass();
        q0 q0Var2 = ix.a;
        k.g(q0Var2, "type");
        d4.Companion.getClass();
        m mVar5 = new m("file", q0Var2, (String) null, rVar, no.a.s(d4.e, new u0(new t("path"))), r4);
        pb.Companion.getClass();
        x xVar4 = pb.a;
        List r5 = l.r(new m[]{mVar5, new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        s mVar6 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r6 = l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list2 = cl0.a.a;
        List r7 = l.r(new s[]{mVar6, no.a.c(list2, "selections", "Node", r6, list2), new n("Commit", d0Shadow.n("Commit"), r5)});
        m mVar7 = new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        List r8 = l.r(new m[]{mVar7, new m("oid", l0.b(hb.a), (String) null, rVar, rVar, rVar)});
        m mVar8 = new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar5 = lb.a;
        m mVar10 = new m("viewerCanCommitToBranch", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        j0 j0Var = fb.a;
        k.g(j0Var, "type");
        List r9 = l.r(new m[]{mVar8, mVar9, mVar10, new m("target", j0Var, (String) null, rVar, rVar, r8), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r10 = l.r(new m[]{new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        m mVar11 = new m("id", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        x xVar6 = rb.a;
        k.g(xVar6, "type");
        m mVar12 = new m("databaseId", xVar6, (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        m mVar13 = new m("object", j0Var, "gitObject", rVar, no.a.s(eq.G, new u0(new t("ref"))), r7);
        m mVar14 = new m("viewerCanPush", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        mo.Companion.getClass();
        q0 q0Var3 = mo.b;
        k.g(q0Var3, "type");
        m mVar15 = new m("ref", q0Var3, (String) null, rVar, no.a.s(eq.P, new u0(new t("ref"))), r9);
        hr.Companion.getClass();
        a = l.r(new m[]{mVar11, mVar12, mVar13, mVar14, mVar15, new m("owner", l0.b(hr.a), (String) null, rVar, rVar, r10), new m("isInOrganization", l0.b(xVar5), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
