package tw;

import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.x;
import aa.x0;
import ew.q;
import f1.e;
import fq.b;
import java.util.List;
import k71.k;
import m10.ah;
import m10.cc0;
import m10.cn;
import m10.eh;
import m10.hd;
import m10.i30;
import m10.l40;
import m10.s60;
import m10.s70;
import m10.sj;
import m10.u70;
import m10.wg;
import m10.y60;
import m10.y70;
import sy.d0Shadow;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        ah.Companion.getClass();
        x xVar = ah.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        x xVar2 = eh.a;
        List r = l.r(new m[]{mVar, new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar2 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar3 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        List r2 = l.r(new m[]{mVar2, mVar3, new m("owner", l0.b(l40.e), (String) null, rVar, rVar, r), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar4 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("Label");
        List list = kt.a.a;
        List r3 = l.r(new s[]{mVar4, no.a.c(list, "selections", "Label", n, list), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar3 = wg.a;
        m mVar7 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        sj.Companion.getClass();
        q0 q0Var = sj.a;
        k.g(q0Var, "type");
        List r4 = l.r(new m[]{mVar5, mVar6, mVar7, mVar8, new m("label", q0Var, (String) null, rVar, rVar, r3)});
        List n2 = d0Shadow.n(new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar));
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar10 = new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        s mVar11 = new m("url", l0.b(cc0.a), (String) null, rVar, rVar, rVar);
        List r5 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = b.a;
        List r6 = l.r(new s[]{mVar9, mVar10, mVar11, no.a.c(list2, "selections", "Actor", r5, list2)});
        k.g(xVar2, "type");
        List r7 = l.r(new m[]{new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        k.g(xVar2, "type");
        m mVar12 = new m("name", xVar2, (String) null, rVar, rVar, rVar);
        k.g(xVar2, "type");
        List r8 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("Node", l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"}), n2), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), r6), new n("User", d0Shadow.n("User"), r7), new n("Organization", d0Shadow.n("Organization"), l.r(new m[]{mVar12, new m("descriptionHTML", xVar2, (String) null, rVar, rVar, rVar), new m("viewerIsFollowing", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)}))});
        m mVar13 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar15 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        u70.Companion.getClass();
        x0 x0Var = u70.a;
        k.g(x0Var, "type");
        List r9 = l.r(new m[]{mVar13, mVar14, mVar15, mVar16, new m("loginRef", x0Var, (String) null, rVar, rVar, r8)});
        s mVar17 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("Milestone");
        List list3 = gu.a.a;
        List r11 = l.r(new s[]{mVar17, no.a.c(list3, "selections", "Milestone", n3, list3), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar18 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar19 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar21 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        cn.Companion.getClass();
        q0 q0Var2 = cn.a;
        k.g(q0Var2, "type");
        List r12 = l.r(new m[]{mVar18, mVar19, mVar20, mVar21, new m("milestone", q0Var2, (String) null, rVar, rVar, r11)});
        s mVar22 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n4 = d0Shadow.n("Repository");
        List list4 = q.a;
        List r13 = l.r(new s[]{mVar22, no.a.c(list4, "selections", "Repository", n4, list4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar23 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar26 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        q0 q0Var3 = i30.w0;
        k.g(q0Var3, "type");
        List r14 = l.r(new m[]{mVar23, mVar24, mVar25, mVar26, new m("repository", q0Var3, (String) null, rVar, rVar, r13)});
        s mVar27 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n5 = d0Shadow.n("DiscussionCategory");
        List list5 = ls.a.a;
        List r15 = l.r(new s[]{mVar27, no.a.c(list5, "selections", "DiscussionCategory", n5, list5), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar28 = new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar29 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar31 = new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hd.Companion.getClass();
        q0 q0Var4 = hd.a;
        k.g(q0Var4, "type");
        List r16 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("SearchShortcutQueryLabelTerm", d0Shadow.n("SearchShortcutQueryLabelTerm"), r4), new n("SearchShortcutQueryLoginRefTerm", d0Shadow.n("SearchShortcutQueryLoginRefTerm"), r9), new n("SearchShortcutQueryMilestoneTerm", d0Shadow.n("SearchShortcutQueryMilestoneTerm"), r12), new n("SearchShortcutQueryRepoTerm", d0Shadow.n("SearchShortcutQueryRepoTerm"), r14), new n("SearchShortcutQueryCategoryTerm", d0Shadow.n("SearchShortcutQueryCategoryTerm"), l.r(new m[]{mVar28, mVar29, mVar30, mVar31, new m("discussionCategory", q0Var4, (String) null, rVar, rVar, r15)})), new n("SearchShortcutQueryTerm", d0Shadow.n("SearchShortcutQueryTerm"), l.r(new m[]{new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("negative", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("value", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new n("SearchShortcutQueryText", d0Shadow.n("SearchShortcutQueryText"), d0Shadow.n(new m("term", l0.b(xVar2), (String) null, rVar, rVar, rVar)))});
        s60.Companion.getClass();
        m mVar32 = new m("color", l0.b(s60.s), (String) null, rVar, rVar, rVar);
        y60.Companion.getClass();
        m mVar33 = new m("icon", l0.b(y60.s), (String) null, rVar, rVar, rVar);
        m mVar34 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar35 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar36 = new m("query", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        k.g(q0Var3, "type");
        m mVar37 = new m("scopingRepository", q0Var3, (String) null, rVar, rVar, r2);
        y70.Companion.getClass();
        m mVar38 = new m("searchType", l0.b(y70.s), (String) null, rVar, rVar, rVar);
        s70.Companion.getClass();
        a = l.r(new m[]{mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, new m("queryTerms", e.e(s70.a), (String) null, rVar, rVar, r16), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
