package h40;

import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import aa.x0;
import hc0.ap;
import hc0.b8;
import hc0.bb;
import hc0.cw;
import hc0.d8;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.fm;
import hc0.h6;
import hc0.hb;
import hc0.kz;
import hc0.li;
import hc0.lk;
import hc0.mu;
import hc0.na;
import hc0.ni;
import hc0.pa;
import hc0.pi;
import hc0.s9;
import hc0.t3;
import hc0.ta;
import hc0.uu;
import hc0.x3;
import hc0.xa;
import hc0.xk;
import hc0.yu;
import java.util.List;
import k71.k;
import sy.d0Shadow;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        bb.Companion.getClass();
        x xVar = bb.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar2 = fb.a;
        List r = l.r(new m[]{mVar, new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar2 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        j0 j0Var = dq.a;
        List r2 = l.r(new m[]{mVar2, new m("owner", l0.b(j0Var), (String) null, rVar, rVar, r), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r3 = l.r(new m[]{new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar3 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        x xVar3 = ew.a;
        m mVar4 = new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar5 = new m("name", xVar2, (String) null, rVar, rVar, rVar);
        kz.Companion.getClass();
        q0 q0Var = kz.O;
        k.g(q0Var, "type");
        List r4 = l.r(new m[]{mVar3, mVar4, mVar5, new m("user", q0Var, (String) null, rVar, rVar, r3)});
        List r5 = l.r(new m[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("user", q0Var, (String) null, rVar, rVar, l.r(new m[]{new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        List r6 = l.r(new m[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", xVar2, (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("user", q0Var, (String) null, rVar, rVar, l.r(new m[]{new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        na.Companion.getClass();
        q0 q0Var2 = na.a;
        List n = d0Shadow.n(new m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, r6));
        List r7 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("ImageFileType", d0Shadow.n("ImageFileType"), d0Shadow.n(new m("url", xVar3, (String) null, rVar, rVar, rVar)))});
        m mVar6 = new m("path", xVar2, (String) null, rVar, rVar, rVar);
        s9.Companion.getClass();
        x0 x0Var = s9.a;
        k.g(x0Var, "type");
        List r8 = l.r(new m[]{mVar6, new m("fileType", x0Var, (String) null, rVar, rVar, r7)});
        List n2 = d0Shadow.n(new m("gitUrl", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r9 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("ImageFileType", d0Shadow.n("ImageFileType"), d0Shadow.n(new m("url", xVar3, (String) null, rVar, rVar, rVar)))});
        m mVar7 = new m("path", xVar2, (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar4 = xa.a;
        m mVar8 = new m("isGenerated", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        yu.Companion.getClass();
        q0 q0Var3 = yu.a;
        k.g(q0Var3, "type");
        List r11 = l.r(new m[]{mVar7, mVar8, new m("submodule", q0Var3, (String) null, rVar, rVar, n2), new m("fileType", x0Var, (String) null, rVar, rVar, r9)});
        s mVar9 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("DiffLine");
        List list = b50.a.a;
        List r12 = l.r(new s[]{mVar9, no.a.c(list, "selections", "DiffLine", n3, list)});
        db.Companion.getClass();
        x xVar5 = db.a;
        m mVar10 = new m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar11 = new m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        cw.Companion.getClass();
        q0 q0Var4 = cw.a;
        k.g(q0Var4, "type");
        m mVar12 = new m("oldTreeEntry", q0Var4, (String) null, rVar, rVar, r8);
        m mVar13 = new m("newTreeEntry", q0Var4, (String) null, rVar, rVar, r11);
        d8.Companion.getClass();
        m mVar14 = new m("diffLines", l0.a(d8.a), (String) null, rVar, rVar, r12);
        m mVar15 = new m("isBinary", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("isLargeDiff", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("isSubmodule", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        pi.Companion.getClass();
        List r13 = l.r(new m[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new m("status", l0.b(pi.s), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        li.Companion.getClass();
        List n4 = d0Shadow.n(new m("nodes", l0.a(li.b), (String) null, rVar, rVar, r13));
        m mVar18 = new m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar19 = new m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("filesChanged", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        ni.Companion.getClass();
        r b2 = l0.b(ni.a);
        b8.Companion.getClass();
        List r14 = l.r(new m[]{mVar18, mVar19, mVar20, new m("patches", b2, (String) null, rVar, no.a.s(b8.c, new u0(50)), n4)});
        m mVar21 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        uu.Companion.getClass();
        List r15 = l.r(new m[]{mVar21, new m("state", l0.b(uu.s), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r16 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("owner", l0.b(j0Var), (String) null, rVar, rVar, l.r(new m[]{new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar)})), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar22 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        fm.Companion.getClass();
        m mVar23 = new m("state", l0.b(fm.s), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("headRefName", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("number", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        m mVar26 = new m("title", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        q0 q0Var5 = ap.k0;
        List r17 = l.r(new m[]{mVar22, mVar23, mVar24, mVar25, mVar26, new m("repository", l0.b(q0Var5), (String) null, rVar, rVar, r16), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        lk.Companion.getClass();
        List n5 = d0Shadow.n(new m("nodes", l0.a(lk.J), (String) null, rVar, rVar, r17));
        List r18 = l.r(new m[]{new m("abbreviatedOid", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        t3.Companion.getClass();
        List n6 = d0Shadow.n(new m("nodes", l0.a(t3.j), (String) null, rVar, rVar, r18));
        h6.Companion.getClass();
        m mVar27 = new m("committedDate", l0.b(h6.a), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        x xVar6 = hb.a;
        m mVar28 = new m("messageBodyHTML", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar29 = new m("messageHeadlineHTML", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar30 = new m("abbreviatedOid", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ta.Companion.getClass();
        m mVar31 = new m("oid", l0.b(ta.a), (String) null, rVar, rVar, rVar);
        m mVar32 = new m("committedViaWeb", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar33 = new m("authoredByCommitter", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar34 = new m("url", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar35 = new m("repository", l0.b(q0Var5), (String) null, rVar, rVar, r2);
        m mVar36 = new m("committer", q0Var2, (String) null, rVar, rVar, r4);
        m mVar37 = new m("author", q0Var2, (String) null, rVar, rVar, r5);
        pa.Companion.getClass();
        m mVar38 = new m("authors", l0.b(pa.a), (String) null, rVar, no.a.s(t3.b, new u0(15)), n);
        q0 q0Var6 = b8.d;
        k.g(q0Var6, "type");
        m mVar39 = new m("diff", q0Var6, (String) null, rVar, rVar, r14);
        mu.Companion.getClass();
        q0 q0Var7 = mu.c;
        k.g(q0Var7, "type");
        m mVar40 = new m("statusCheckRollup", q0Var7, (String) null, rVar, rVar, r15);
        xk.Companion.getClass();
        q0 q0Var8 = xk.a;
        k.g(q0Var8, "type");
        m mVar41 = new m("associatedPullRequests", q0Var8, (String) null, rVar, no.a.s(t3.a, new u0(5)), n5);
        x3.Companion.getClass();
        a = l.r(new m[]{mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, new m("parents", l0.b(x3.a), (String) null, rVar, no.a.s(t3.i, new u0(5)), n6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
