package cp;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.ch0;
import m10.d4;
import m10.da0;
import m10.eh;
import m10.f4;
import m10.h1;
import m10.h4;
import m10.i30;
import m10.j10;
import m10.l40;
import m10.mr;
import m10.n40;
import m10.p00;
import m10.sa;
import m10.tg0;
import m10.v3;
import m10.wg;
import m10.zp;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        ah.Companion.getClass();
        x xVar = ah.a;
        r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        x xVar2 = eh.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar2 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.a.a;
        List r3 = x61.l.r(new s[]{mVar2, no.a.c(list, "selections", "Actor", r2, list)});
        aa.m mVar3 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar4 = new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        aa.m mVar5 = new aa.m("owner", l0.b(l40.e), (String) null, rVar, rVar, r3);
        n40.Companion.getClass();
        a0 a0Var = n40.s;
        k71.k.g(a0Var, "type");
        List r4 = x61.l.r(new aa.m[]{mVar3, mVar4, mVar5, new aa.m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar6 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        x xVar3 = ch.a;
        aa.m mVar7 = new aa.m("runNumber", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        tg0.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{mVar6, mVar7, new aa.m("workflow", l0.b(tg0.e), (String) null, rVar, rVar, r5), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar8, new aa.m("logoUrl", l0.b(cc0.a), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar9 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        j10.Companion.getClass();
        q0 q0Var = j10.e;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("branch", q0Var, (String) null, rVar, rVar, r);
        wg.Companion.getClass();
        x xVar4 = wg.a;
        aa.m mVar11 = new aa.m("rerunnable", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        aa.m mVar12 = new aa.m("repository", l0.b(i30.w0), (String) null, rVar, rVar, r4);
        ch0.Companion.getClass();
        q0 q0Var2 = ch0.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar13 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r6);
        h1.Companion.getClass();
        q0 q0Var3 = h1.a;
        k71.k.g(q0Var3, "type");
        List r8 = x61.l.r(new aa.m[]{mVar9, mVar10, mVar11, mVar12, mVar13, new aa.m("app", q0Var3, (String) null, rVar, rVar, r7), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar), new aa.m("hasPreviousPage", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        s mVar14 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("CheckStep");
        List list2 = wo.a.a;
        List r11 = x61.l.r(new s[]{mVar14, no.a.c(list2, "selections", "CheckStep", n, list2)});
        aa.m mVar15 = new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        mr.Companion.getClass();
        aa.m mVar16 = new aa.m("pageInfo", l0.b(mr.a), (String) null, rVar, rVar, r9);
        d4.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar15, mVar16, new aa.m("nodes", l0.a(d4.a), (String) null, rVar, rVar, r11)});
        s mVar17 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0Shadow.n("CheckRun");
        List list3 = wo.f.a;
        s c = no.a.c(list3, "selections", "CheckRun", n2, list3);
        h4.Companion.getClass();
        s mVar18 = new aa.m("checkSuite", l0.b(h4.f), (String) null, rVar, rVar, r8);
        f4.Companion.getClass();
        q0 q0Var4 = f4.a;
        k71.k.g(q0Var4, "type");
        v3.Companion.getClass();
        List r13 = x61.l.r(new s[]{mVar17, c, mVar18, new aa.m("steps", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(v3.c, new u0(new t("afterSteps"))), new aa.k(v3.d, new u0(new t("first")))}), r12)});
        aa.m mVar19 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar20 = new aa.m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar21 = new aa.m("description", xVar2, (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        aa.m mVar22 = new aa.m("createdAt", l0.b(sa.a), (String) null, rVar, rVar, rVar);
        da0.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{mVar19, mVar20, mVar21, mVar22, new aa.m("state", l0.b(da0.s), (String) null, rVar, rVar, rVar)});
        s mVar23 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s nVar = new aa.n("CheckRun", d0Shadow.n("CheckRun"), r13);
        List n3 = d0Shadow.n("StatusContext");
        List list4 = wo.e.a;
        List r15 = x61.l.r(new s[]{mVar23, nVar, no.a.c(list4, "selections", "StatusContext", n3, list4), new aa.n("RequiredStatusCheck", d0Shadow.n("RequiredStatusCheck"), r14), new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        zp.Companion.getClass();
        j0 j0Var = zp.a;
        k71.k.g(j0Var, "type");
        p00.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(p00.i, new u0(new t("id"))), r15), new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
