package h10;

import java.util.List;
import m10.ah;
import m10.bz;
import m10.cc0;
import m10.dz;
import m10.eh;
import m10.fz;
import m10.i30;
import m10.nz;
import m10.p00;
import m10.pz;
import m10.rf0;
import m10.rz;
import m10.sa;
import m10.sg;
import m10.tz;
import m10.uc;
import m10.ux;
import m10.wg;
import m10.xz;
import m10.zp;
import m10.zy;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class l3 {
    public static final List a;

    static {
        ah.Companion.getClass();
        aa.x xVar = ah.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        sg.Companion.getClass();
        aa.m mVar2 = new aa.m("headRefOid", v8.l0.b(sg.a), (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        aa.x xVar2 = eh.a;
        List r = x61.l.r(new aa.m[]{mVar, mVar2, new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar3 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.a.a;
        List r3 = x61.l.r(new aa.s[]{mVar3, no.a.c(list, "selections", "Actor", r2, list)});
        aa.s mVar4 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = sy.d0Shadow.n("Repository");
        List list2 = ew.j.a;
        aa.s c = no.a.c(list2, "selections", "Repository", n, list2);
        List n2 = sy.d0Shadow.n("Repository");
        List list3 = ew.b.a;
        List r4 = x61.l.r(new aa.s[]{mVar4, c, no.a.c(list3, "selections", "Repository", n2, list3), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("login", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar5 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0Shadow.n("DiffLine");
        List list4 = fs.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar5, no.a.c(list4, "selections", "DiffLine", n3, list4)});
        aa.s mVar6 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list5 = br.a.a;
        aa.s c2 = no.a.c(list5, "selections", "Comment", r7, list5);
        List r8 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list6 = qv.a.a;
        aa.s c3 = no.a.c(list6, "selections", "Reactable", r8, list6);
        List r9 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list7 = nx.b.a;
        aa.s c4 = no.a.c(list7, "selections", "Updatable", r9, list7);
        List r11 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list8 = qu.a.a;
        aa.s c5 = no.a.c(list8, "selections", "OrgBlockable", r11, list8);
        List r12 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"});
        List list9 = ku.a.a;
        aa.s c6 = no.a.c(list9, "selections", "Minimizable", r12, list9);
        cc0.Companion.getClass();
        aa.x xVar3 = cc0.a;
        aa.s mVar7 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        fz.Companion.getClass();
        aa.a0 a0Var = fz.s;
        List r13 = x61.l.r(new aa.s[]{mVar6, c2, c3, c4, c5, c6, mVar7, new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        bz.Companion.getClass();
        List n4 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(bz.a), (String) null, rVar, rVar, r13));
        aa.s mVar8 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar9 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar10 = new aa.m("path", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        xz.Companion.getClass();
        aa.a0 a0Var2 = xz.s;
        aa.s mVar11 = new aa.m("subjectType", v8.l0.b(a0Var2), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        aa.x xVar4 = wg.a;
        aa.s mVar12 = new aa.m("isResolved", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("viewerCanResolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("viewerCanUnresolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        rf0.Companion.getClass();
        aa.q0 q0Var = rf0.g0;
        k71.k.g(q0Var, "type");
        aa.s mVar15 = new aa.m("resolvedBy", q0Var, (String) null, rVar, rVar, r5);
        aa.s mVar16 = new aa.m("viewerCanReply", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        uc.Companion.getClass();
        aa.q0 q0Var2 = uc.a;
        aa.p a2 = v8.l0.a(q0Var2);
        tz.Companion.getClass();
        a81.t tVar = tz.c;
        Boolean bool = Boolean.TRUE;
        aa.s mVar17 = new aa.m("diffLines", a2, (String) null, rVar, no.a.s(tVar, new aa.u0(bool)), r6);
        List n5 = sy.d0Shadow.n("PullRequestReviewThread");
        List list10 = ov.a.a;
        aa.s c7 = no.a.c(list10, "selections", "PullRequestReviewThread", n5, list10);
        dz.Companion.getClass();
        List r14 = x61.l.r(new aa.s[]{mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, c7, new aa.m("comments", v8.l0.b(dz.a), (String) null, rVar, no.a.s(tz.a, new aa.u0(50)), n4)});
        List r15 = x61.l.r(new aa.m[]{new aa.m("login", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r16 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), no.a.c(list4, "selections", "DiffLine", sy.d0Shadow.n("DiffLine"), list4)});
        aa.s mVar18 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar19 = new aa.m("isResolved", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        List r17 = x61.l.r(new aa.s[]{mVar18, mVar19, new aa.m("resolvedBy", q0Var, (String) null, rVar, rVar, r15), new aa.m("viewerCanResolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("viewerCanUnresolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("viewerCanReply", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("diffLines", v8.l0.a(q0Var2), (String) null, rVar, no.a.s(tVar, new aa.u0(bool)), r16), no.a.c(list10, "selections", "PullRequestReviewThread", sy.d0Shadow.n("PullRequestReviewThread"), list10), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar20 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("path", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("subjectType", v8.l0.b(a0Var2), (String) null, rVar, rVar, rVar);
        aa.q0 q0Var3 = tz.e;
        k71.k.g(q0Var3, "type");
        List r18 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequestReviewThread", sy.d0Shadow.n("PullRequestReviewThread"), r14), new aa.n("PullRequestReviewComment", sy.d0Shadow.n("PullRequestReviewComment"), x61.l.r(new aa.s[]{mVar20, mVar21, mVar22, mVar23, new aa.m("thread", q0Var3, (String) null, rVar, rVar, r17), no.a.c(list5, "selections", "Comment", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"}), list5), no.a.c(list6, "selections", "Reactable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment"}), list6), no.a.c(list7, "selections", "Updatable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"}), list7), no.a.c(list8, "selections", "OrgBlockable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"}), list8), no.a.c(list9, "selections", "Minimizable", x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"}), list9), new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar)}))});
        nz.Companion.getClass();
        List n6 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(nz.a), (String) null, rVar, rVar, r18));
        aa.s mVar24 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        rz.Companion.getClass();
        aa.s mVar26 = new aa.m("state", v8.l0.b(rz.s), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("authorCanPushToRepository", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        aa.x xVar5 = sa.a;
        k71.k.g(xVar5, "type");
        aa.s mVar29 = new aa.m("submittedAt", xVar5, (String) null, rVar, rVar, rVar);
        aa.s c8 = no.a.c(list5, "selections", "Comment", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"}), list5);
        aa.s c9 = no.a.c(list6, "selections", "Reactable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment"}), list6);
        aa.s c11 = no.a.c(list7, "selections", "Updatable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"}), list7);
        aa.s c12 = no.a.c(list8, "selections", "OrgBlockable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"}), list8);
        ux.Companion.getClass();
        aa.s mVar30 = new aa.m("pullRequest", v8.l0.b(ux.T), (String) null, rVar, rVar, r);
        m10.l.Companion.getClass();
        aa.j0 j0Var = m10.l.a;
        k71.k.g(j0Var, "type");
        aa.s mVar31 = new aa.m("author", j0Var, (String) null, rVar, rVar, r3);
        i30.Companion.getClass();
        aa.s mVar32 = new aa.m("repository", v8.l0.b(i30.w0), (String) null, rVar, rVar, r4);
        pz.Companion.getClass();
        aa.q0 q0Var4 = pz.a;
        k71.k.g(q0Var4, "type");
        zy.Companion.getClass();
        List r19 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequestReview", sy.d0Shadow.n("PullRequestReview"), x61.l.r(new aa.s[]{mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, c8, c9, c11, c12, mVar30, mVar31, mVar32, new aa.m("threadsAndReplies", q0Var4, (String) null, rVar, no.a.s(zy.c, new aa.u0(50)), n6)})), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        zp.Companion.getClass();
        aa.j0 j0Var2 = zp.a;
        k71.k.g(j0Var2, "type");
        p00.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var2, (String) null, rVar, no.a.s(p00.i, new aa.u0(new aa.t("id"))), r19), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
