package h10;

import java.util.List;
import m10.ah;
import m10.b20;
import m10.cc0;
import m10.ch;
import m10.eh;
import m10.fd;
import m10.gh;
import m10.i30;
import m10.j10;
import m10.l40;
import m10.mg;
import m10.mr;
import m10.nd;
import m10.p00;
import m10.pd;
import m10.qg;
import m10.rf0;
import m10.sa;
import m10.sg;
import m10.ug;
import m10.wg;
import m10.x10;
import m10.xf0;
import m10.z10;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class r3 {
    public static final List a;

    static {
        eh.Companion.getClass();
        aa.x xVar = eh.a;
        aa.r b = v8.l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        ah.Companion.getClass();
        aa.x xVar2 = ah.a;
        aa.s mVar2 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.b.a;
        List r2 = x61.l.r(new aa.s[]{mVar, mVar2, no.a.c(list, "selections", "Actor", r, list)});
        wg.Companion.getClass();
        aa.x xVar3 = wg.a;
        List n = sy.d0.n(new aa.m("isValid", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar3 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        sg.Companion.getClass();
        aa.x xVar4 = sg.a;
        aa.m mVar4 = new aa.m("oid", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("abbreviatedOid", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        ug.Companion.getClass();
        aa.j0 j0Var = ug.a;
        k71.k.g(j0Var, "type");
        aa.m mVar6 = new aa.m("signature", j0Var, (String) null, rVar, rVar, n);
        aa.m mVar7 = new aa.m("message", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        gh.Companion.getClass();
        aa.x xVar5 = gh.a;
        aa.m mVar8 = new aa.m("messageBodyHTML", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        aa.x xVar6 = sa.a;
        List r3 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("Commit", sy.d0.n("Commit"), x61.l.r(new aa.m[]{mVar3, mVar4, mVar5, mVar6, mVar7, mVar8, new aa.m("authoredDate", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar)}))});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r4 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = fq.a.a;
        List r5 = x61.l.r(new aa.s[]{mVar9, no.a.c(list2, "selections", "Actor", r4, list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        rf0.Companion.getClass();
        aa.q0 q0Var = rf0.g0;
        k71.k.g(q0Var, "type");
        List n2 = sy.d0.n(new aa.m("user", q0Var, (String) null, rVar, rVar, r5));
        aa.m mVar10 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        qg.Companion.getClass();
        aa.j0 j0Var2 = qg.a;
        aa.m mVar11 = new aa.m("target", v8.l0.b(j0Var2), (String) null, rVar, rVar, r3);
        aa.m mVar12 = new aa.m("message", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        aa.x xVar7 = cc0.a;
        aa.m mVar14 = new aa.m("commitUrl", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar);
        mg.Companion.getClass();
        aa.q0 q0Var2 = mg.a;
        k71.k.g(q0Var2, "type");
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("target", j0Var2, (String) null, rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("Tag", sy.d0.n("Tag"), x61.l.r(new aa.m[]{mVar10, mVar11, mVar12, mVar13, mVar14, new aa.m("tagger", q0Var2, (String) null, rVar, rVar, n2)}))})), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("oid", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("abbreviatedOid", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r8 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar, (String) null, rVar, rVar, rVar)});
        aa.m mVar15 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        aa.x xVar8 = ch.a;
        List r11 = x61.l.r(new aa.m[]{mVar15, mVar16, new aa.m("size", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar), new aa.m("url", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar), new aa.m("contentType", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        mr.Companion.getClass();
        aa.m mVar17 = new aa.m("pageInfo", v8.l0.b(mr.a), (String) null, rVar, rVar, r9);
        z10.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar17, new aa.m("nodes", v8.l0.a(z10.a), (String) null, rVar, rVar, r11)});
        List r13 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2)});
        aa.s mVar18 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar19 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m10.l.Companion.getClass();
        aa.j0 j0Var3 = m10.l.a;
        k71.k.g(j0Var3, "type");
        aa.s mVar20 = new aa.m("author", j0Var3, (String) null, rVar, rVar, r13);
        aa.s mVar21 = new aa.m("createdAt", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("lastEditedAt", xVar6, (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("body", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"});
        List list3 = ku.a.a;
        List r15 = x61.l.r(new aa.s[]{mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, no.a.c(list3, "selections", "Minimizable", r14, list3)});
        aa.m mVar24 = new aa.m("totalCount", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar);
        nd.Companion.getClass();
        List r16 = x61.l.r(new aa.m[]{mVar24, new aa.m("nodes", v8.l0.a(nd.c), (String) null, rVar, rVar, r15)});
        aa.m mVar25 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar26 = new aa.m("number", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        aa.r b2 = v8.l0.b(pd.a);
        fd.Companion.getClass();
        List r17 = x61.l.r(new aa.m[]{mVar25, mVar26, new aa.m("comments", b2, (String) null, rVar, no.a.s(fd.h, new aa.u0(3)), r16), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r18 = x61.l.r(new aa.m[]{new aa.m("totalCount", v8.l0.b(xVar8), (String) null, rVar, rVar, rVar), new aa.m("nodes", v8.l0.a(q0Var), (String) null, rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list2), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)}))});
        aa.s mVar27 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar29 = new aa.m("url", v8.l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar30 = new aa.m("name", xVar, (String) null, rVar, rVar, rVar);
        aa.s mVar31 = new aa.m("tagName", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        m10.y5.Companion.getClass();
        aa.q0 q0Var3 = m10.y5.j;
        k71.k.g(q0Var3, "type");
        aa.s mVar32 = new aa.m("tagCommit", q0Var3, (String) null, rVar, rVar, r7);
        aa.s mVar33 = new aa.m("author", q0Var, (String) null, rVar, rVar, r8);
        List r19 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list4 = qv.a.a;
        aa.s c = no.a.c(list4, "selections", "Reactable", r19, list4);
        aa.s mVar34 = new aa.m("descriptionHTML", xVar5, (String) null, rVar, rVar, rVar);
        aa.s mVar35 = new aa.m("isPrerelease", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar36 = new aa.m("isDraft", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar37 = new aa.m("isLatest", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar38 = new aa.m("createdAt", v8.l0.b(xVar6), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar6, "type");
        aa.s mVar39 = new aa.m("publishedAt", xVar6, (String) null, rVar, rVar, rVar);
        b20.Companion.getClass();
        aa.r b3 = v8.l0.b(b20.a);
        x10.Companion.getClass();
        aa.s mVar40 = new aa.m("releaseAssets", b3, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(x10.c, new aa.u0(new aa.t("after"))), new aa.k(x10.d, new aa.u0(new aa.t("number")))}), r12);
        aa.q0 q0Var4 = fd.l;
        k71.k.g(q0Var4, "type");
        aa.s mVar41 = new aa.m("discussion", q0Var4, (String) null, rVar, rVar, r17);
        xf0.Companion.getClass();
        aa.q0 q0Var5 = xf0.a;
        k71.k.g(q0Var5, "type");
        List r21 = x61.l.r(new aa.s[]{mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, c, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, new aa.m("mentions", q0Var5, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(x10.a, new aa.u0((Object) null)), new aa.k(x10.b, new aa.u0(5))}), r18)});
        aa.m mVar42 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        aa.m mVar43 = new aa.m("owner", v8.l0.b(l40.e), (String) null, rVar, rVar, r2);
        j10.Companion.getClass();
        aa.q0 q0Var6 = j10.e;
        k71.k.g(q0Var6, "type");
        i30.Companion.getClass();
        aa.m mVar44 = new aa.m("ref", q0Var6, (String) null, rVar, no.a.s(i30.T, new aa.u0(new aa.t("tagName"))), r6);
        aa.q0 q0Var7 = x10.e;
        k71.k.g(q0Var7, "type");
        List r22 = x61.l.r(new aa.m[]{mVar42, mVar43, mVar44, new aa.m("release", q0Var7, (String) null, rVar, no.a.s(i30.Z, new aa.u0(new aa.t("tagName"))), r21), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.q0 q0Var8 = i30.w0;
        k71.k.g(q0Var8, "type");
        p00.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("repository", q0Var8, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(p00.l, new aa.u0(new aa.t("repositoryName"))), new aa.k(p00.m, new aa.u0(new aa.t("repositoryOwner")))}), r22), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
