package h10;

import java.util.List;
import m10.ah;
import m10.cc;
import m10.cc0;
import m10.ch;
import m10.ch0;
import m10.ec;
import m10.eh;
import m10.i30;
import m10.l40;
import m10.ly;
import m10.p00;
import m10.rf0;
import m10.tg0;
import m10.ux;
import m10.zp;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class u0 {
    public static final List a;

    static {
        eh.Companion.getClass();
        aa.x xVar = eh.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.a.a;
        List r2 = x61.l.r(new aa.s[]{mVar, no.a.c(list, "selections", "Actor", r, list)});
        l40.Companion.getClass();
        aa.m mVar2 = new aa.m("owner", v8.l0.b(l40.e), (String) null, rVar, rVar, r2);
        aa.m mVar3 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        ah.Companion.getClass();
        aa.x xVar2 = ah.a;
        List r3 = x61.l.r(new aa.m[]{mVar2, mVar3, new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r4 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = sy.d0Shadow.n("DeploymentRequest");
        List list2 = ds.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar4, no.a.c(list2, "selections", "DeploymentRequest", n, list2)});
        cc.Companion.getClass();
        List n2 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(cc.c), (String) null, rVar, rVar, r6));
        aa.m mVar5 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        aa.x xVar3 = cc0.a;
        aa.m mVar6 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        aa.m mVar7 = new aa.m("runNumber", v8.l0.b(ch.a), (String) null, rVar, rVar, rVar);
        tg0.Companion.getClass();
        aa.m mVar8 = new aa.m("workflow", v8.l0.b(tg0.e), (String) null, rVar, rVar, r5);
        ec.Companion.getClass();
        aa.r b2 = v8.l0.b(ec.a);
        ch0.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, mVar8, new aa.m("pendingDeploymentRequests", b2, (String) null, rVar, no.a.s(ch0.a, new aa.u0(new aa.t("numberOfDeploymentRequests"))), n2), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0Shadow.n("CheckRun");
        List list3 = xq.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar9, no.a.c(list3, "selections", "CheckRun", n3, list3), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m10.v3.Companion.getClass();
        List n4 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(m10.v3.f), (String) null, rVar, rVar, r8));
        aa.s mVar10 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n5 = sy.d0Shadow.n("PullRequest");
        List list4 = hv.c.a;
        List r9 = x61.l.r(new aa.s[]{mVar10, no.a.c(list4, "selections", "PullRequest", n5, list4), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ux.Companion.getClass();
        List n6 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(ux.T), (String) null, rVar, rVar, r9));
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar12 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m10.b4.Companion.getClass();
        aa.m mVar13 = new aa.m("status", v8.l0.b(m10.b4.s), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        aa.m mVar14 = new aa.m("repository", v8.l0.b(i30.w0), (String) null, rVar, rVar, r3);
        rf0.Companion.getClass();
        aa.q0 q0Var = rf0.g0;
        k71.k.g(q0Var, "type");
        aa.m mVar15 = new aa.m("creator", q0Var, (String) null, rVar, rVar, r4);
        aa.q0 q0Var2 = ch0.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar16 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r7);
        m10.x3.Companion.getClass();
        aa.q0 q0Var3 = m10.x3.a;
        k71.k.g(q0Var3, "type");
        m10.h4.Companion.getClass();
        aa.m mVar17 = new aa.m("checkRuns", q0Var3, (String) null, rVar, no.a.s(m10.h4.c, new aa.u0(new aa.t("numberOfCheckRuns"))), n4);
        ly.Companion.getClass();
        aa.q0 q0Var4 = ly.a;
        k71.k.g(q0Var4, "type");
        List r11 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("CheckSuite", sy.d0Shadow.n("CheckSuite"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("matchingPullRequests", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(m10.h4.d, new aa.u0(new aa.t("cursor"))), new aa.k(m10.h4.e, new aa.u0(new aa.t("numberOfPullRequests")))}), n6)})), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        zp.Companion.getClass();
        aa.j0 j0Var = zp.a;
        k71.k.g(j0Var, "type");
        p00.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(p00.i, new aa.u0(new aa.t("nodeId"))), r11), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
