package h10;

import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.ch0;
import m10.da0;
import m10.dy;
import m10.eh;
import m10.hy;
import m10.l50;
import m10.mr;
import m10.n50;
import m10.p00;
import m10.p90;
import m10.r90;
import m10.sa;
import m10.t90;
import m10.tg0;
import m10.ux;
import m10.wg;
import m10.x90;
import m10.zp;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class w {
    public static final List a;

    static {
        ah.Companion.getClass();
        aa.x xVar = ah.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        eh.Companion.getClass();
        aa.x xVar2 = eh.a;
        aa.m mVar2 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        da0.Companion.getClass();
        aa.a0 a0Var = da0.s;
        List r = x61.l.r(new aa.m[]{mVar, mVar2, new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar), new aa.m("description", xVar2, (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ch.Companion.getClass();
        aa.x xVar3 = ch.a;
        aa.m mVar3 = new aa.m("totalCount", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        l50.Companion.getClass();
        List r2 = x61.l.r(new aa.m[]{mVar3, new aa.m("nodes", v8.l0.a(l50.a), (String) null, rVar, rVar, r)});
        wg.Companion.getClass();
        aa.x xVar4 = wg.a;
        List r3 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        aa.m mVar4 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar6 = new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        aa.x xVar5 = cc0.a;
        k71.k.g(xVar5, "type");
        aa.m mVar7 = new aa.m("avatarUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.m mVar8 = new aa.m("description", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("targetUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.r b2 = v8.l0.b(xVar4);
        x90.Companion.getClass();
        List r4 = x61.l.r(new aa.m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(x90.a, new aa.u0(new aa.t("id"))), rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        tg0.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{new aa.m("workflow", v8.l0.b(tg0.e), (String) null, rVar, rVar, r5), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("logoUrl", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ch0.Companion.getClass();
        aa.q0 q0Var = ch0.b;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("workflowRun", q0Var, (String) null, rVar, rVar, r6);
        m10.h1.Companion.getClass();
        aa.q0 q0Var2 = m10.h1.a;
        k71.k.g(q0Var2, "type");
        List r8 = x61.l.r(new aa.m[]{mVar10, new aa.m("app", q0Var2, (String) null, rVar, rVar, r7), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        m10.t3.Companion.getClass();
        aa.a0 a0Var2 = m10.t3.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar12 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar14 = new aa.m("summary", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar15 = new aa.m("permalink", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("duration", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m10.h4.Companion.getClass();
        aa.m mVar17 = new aa.m("checkSuite", v8.l0.b(m10.h4.f), (String) null, rVar, rVar, r8);
        aa.r b3 = v8.l0.b(xVar4);
        m10.v3.Companion.getClass();
        List r9 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", sy.d0Shadow.n("StatusContext"), r4), new aa.n("CheckRun", sy.d0Shadow.n("CheckRun"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(m10.v3.a, new aa.u0(new aa.t("id"))), rVar)}))});
        mr.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", v8.l0.b(mr.a), (String) null, rVar, rVar, r3);
        r90.Companion.getClass();
        List r11 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", v8.l0.a(r90.a), (String) null, rVar, rVar, r9)});
        aa.m mVar19 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        t90.Companion.getClass();
        aa.r b4 = v8.l0.b(t90.a);
        p90.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar19, new aa.m("contexts", b4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(p90.a, new aa.u0(new aa.t("after"))), new aa.k(p90.b, new aa.u0(25))}), r11), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        sa.Companion.getClass();
        aa.x xVar6 = sa.a;
        k71.k.g(xVar6, "type");
        aa.m mVar20 = new aa.m("pushedDate", xVar6, (String) null, rVar, rVar, rVar);
        aa.q0 q0Var3 = p90.c;
        k71.k.g(q0Var3, "type");
        List r13 = x61.l.r(new aa.m[]{mVar20, new aa.m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r12), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m10.y5.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{new aa.m("commit", v8.l0.b(m10.y5.j), (String) null, rVar, rVar, r13), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        dy.Companion.getClass();
        List n = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(dy.a), (String) null, rVar, rVar, r14));
        n50.Companion.getClass();
        aa.r b5 = v8.l0.b(n50.a);
        ux.Companion.getClass();
        aa.m mVar21 = new aa.m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(ux.C, new aa.u0(25)), r2);
        hy.Companion.getClass();
        List r15 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequest", sy.d0Shadow.n("PullRequest"), x61.l.r(new aa.m[]{mVar21, new aa.m("commits", v8.l0.b(hy.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ux.j, new aa.u0((Object) null)), new aa.k(ux.l, new aa.u0(1))}), n)})), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        zp.Companion.getClass();
        aa.j0 j0Var = zp.a;
        k71.k.g(j0Var, "type");
        p00.Companion.getClass();
        a = x61.l.r(new aa.m[]{new aa.m("node", j0Var, (String) null, rVar, no.a.s(p00.i, new aa.u0(new aa.t("id"))), r15), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
    }
}
