package rx;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import java.util.List;
import k71.k;
import m10.ah;
import m10.b00;
import m10.cc0;
import m10.ch;
import m10.ci;
import m10.eh;
import m10.h10;
import m10.i30;
import m10.l40;
import m10.rf0;
import m10.sa;
import m10.si;
import m10.uh;
import m10.wg;
import m10.wi;
import m10.yi;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class c {
    public static final List a;

    static {
        eh.Companion.getClass();
        x xVar = eh.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        s mVar = new m("__typename", b, (String) null, rVar, rVar, rVar);
        s mVar2 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.b.a;
        s c = no.a.c(list, "selections", "Actor", r, list);
        ah.Companion.getClass();
        x xVar2 = ah.a;
        List r2 = l.r(new s[]{mVar, mVar2, c, new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ch.Companion.getClass();
        x xVar3 = ch.a;
        List n = d0.n(new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r3 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)});
        m mVar3 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar4 = new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        j0 j0Var = l40.e;
        List r4 = l.r(new m[]{mVar3, mVar4, new m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        x xVar4 = cc0.a;
        m mVar6 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar7 = new m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar9 = new m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        b00.Companion.getClass();
        m mVar10 = new m("state", l0.b(b00.s), "pullRequestState", rVar, rVar, rVar);
        ci.Companion.getClass();
        q0 q0Var = ci.a;
        m mVar11 = new m("comments", l0.b(q0Var), "pullComments", rVar, rVar, n);
        wg.Companion.getClass();
        x xVar5 = wg.a;
        k.g(xVar5, "type");
        m mVar12 = new m("isReadByViewer", xVar5, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("isDraft", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        x xVar6 = sa.a;
        m mVar14 = new m("createdAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        q0 q0Var2 = i30.w0;
        List r5 = l.r(new m[]{mVar5, mVar6, mVar7, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, new m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4), new m("isInMergeQueue", l0.b(xVar5), (String) null, rVar, rVar, rVar)});
        List n2 = d0.n(new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r6 = l.r(new m[]{new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("owner", l0.b(j0Var), (String) null, rVar, rVar, l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("Actor", l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)})), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar15 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar16 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        wi.Companion.getClass();
        m mVar19 = new m("state", l0.b(wi.s), "issueState", rVar, rVar, rVar);
        m mVar20 = new m("comments", l0.b(q0Var), "issueComments", rVar, rVar, n2);
        m mVar21 = new m("isReadByViewer", xVar5, (String) null, rVar, rVar, rVar);
        m mVar22 = new m("createdAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r6);
        yi.Companion.getClass();
        a0 a0Var = yi.s;
        k.g(a0Var, "type");
        List r7 = l.r(new s[]{new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new n("PullRequest", d0.n("PullRequest"), r5), new n("Issue", d0.n("Issue"), l.r(new m[]{mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, new m("stateReason", a0Var, (String) null, rVar, rVar, rVar)}))});
        uh.Companion.getClass();
        m mVar24 = new m("interaction", l0.b(uh.s), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("occurredAt", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        rf0.Companion.getClass();
        q0 q0Var3 = rf0.g0;
        k.g(q0Var3, "type");
        m mVar26 = new m("commenter", q0Var3, (String) null, rVar, rVar, r2);
        si.Companion.getClass();
        List r8 = l.r(new m[]{mVar24, mVar25, mVar26, new m("interactable", l0.b(si.a), (String) null, rVar, rVar, r7)});
        h10.Companion.getClass();
        a = l.r(new m[]{new m("recentInteractions", no.a.d(h10.a), (String) null, rVar, no.a.s(rf0.B, new u0(10)), r8), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
