package rx;

import aa.m;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import dq.o0;
import ew.o;
import java.util.List;
import k71.k;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.ct;
import m10.eg;
import m10.eh;
import m10.f90;
import m10.gh;
import m10.ir;
import m10.l80;
import m10.n80;
import m10.p40;
import m10.p80;
import m10.pg0;
import m10.q30;
import m10.rf0;
import m10.ss;
import m10.wg;
import m10.z80;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class i {
    public static final List a;

    static {
        ch.Companion.getClass();
        x xVar = ch.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        List n = d0.n(new m("totalCount", b, (String) null, rVar, rVar, rVar));
        eh.Companion.getClass();
        x xVar2 = eh.a;
        s mVar = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("ProfileItemShowcase");
        List list = dv.a.a;
        List r = l.r(new s[]{mVar, no.a.c(list, "selections", "ProfileItemShowcase", n2, list)});
        List n3 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n4 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n5 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        List n6 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        s mVar2 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n7 = d0.n("UserStatus");
        List list2 = d.a;
        s c = no.a.c(list2, "selections", "UserStatus", n7, list2);
        ah.Companion.getClass();
        x xVar3 = ah.a;
        List r2 = l.r(new s[]{mVar2, c, new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        s mVar3 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n8 = d0.n("RepositoryReadme");
        List list3 = o.a;
        List r3 = l.r(new s[]{mVar3, no.a.c(list3, "selections", "RepositoryReadme", n8, list3)});
        List n9 = d0.n(new m("totalCount", l0.b(xVar), (String) null, rVar, rVar, rVar));
        m mVar4 = new m("displayName", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        p80.Companion.getClass();
        m mVar5 = new m("provider", l0.b(p80.s), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        x xVar4 = cc0.a;
        List r4 = l.r(new m[]{mVar4, mVar5, new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        l80.Companion.getClass();
        List n11 = d0.n(new m("nodes", l0.a(l80.a), (String) null, rVar, rVar, r4));
        List r5 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("slug", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("badgeImageUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m10.b.Companion.getClass();
        m mVar6 = new m("achievable", l0.b(m10.b.a), (String) null, rVar, rVar, r5);
        m10.j.Companion.getClass();
        q0 q0Var = m10.j.b;
        k.g(q0Var, "type");
        m10.d.Companion.getClass();
        List n12 = d0.n(new m("nodes", l0.a(m10.d.c), (String) null, rVar, rVar, l.r(new m[]{mVar6, new m("tier", q0Var, (String) null, rVar, no.a.s(m10.d.b, new u0(1)), r6), new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)})));
        s mVar7 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar8 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        s mVar9 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        List r7 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list4 = fq.b.a;
        s c2 = no.a.c(list4, "selections", "Actor", r7, list4);
        gh.Companion.getClass();
        x xVar5 = gh.a;
        s mVar10 = new m("bioHTML", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        s mVar11 = new m("companyHTML", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        s mVar12 = new m("email", l0.b(xVar2), "userEmail", rVar, rVar, rVar);
        List n13 = d0.n("User");
        List list5 = o0.a;
        s c3 = no.a.c(list5, "selections", "User", n13, list5);
        eg.Companion.getClass();
        s mVar13 = new m("following", l0.b(eg.a), (String) null, rVar, rVar, n);
        wg.Companion.getClass();
        x xVar6 = wg.a;
        s mVar14 = new m("isDeveloperProgramMember", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar15 = new m("isEmployee", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar16 = new m("isFollowingViewer", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar17 = new m("isViewer", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar18 = new m("isBountyHunter", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        ss.Companion.getClass();
        s mVar19 = new m("itemShowcase", l0.b(ss.b), (String) null, rVar, rVar, r);
        s mVar20 = new m("location", xVar2, (String) null, rVar, rVar, rVar);
        s mVar21 = new m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s mVar22 = new m("name", xVar2, (String) null, rVar, rVar, rVar);
        ir.Companion.getClass();
        s mVar23 = new m("organizations", l0.b(ir.a), (String) null, rVar, rVar, n3);
        s mVar24 = new m("pronouns", xVar2, (String) null, rVar, rVar, rVar);
        q30.Companion.getClass();
        r b2 = l0.b(q30.a);
        rf0.Companion.getClass();
        s mVar25 = new m("repositories", b2, (String) null, rVar, no.a.s(rf0.I, new u0(d0.n("OWNER"))), n4);
        f90.Companion.getClass();
        s mVar26 = new m("starredRepositories", l0.b(f90.a), (String) null, rVar, rVar, n5);
        z80.Companion.getClass();
        s mVar27 = new m("sponsorshipsAsSponsor", l0.b(z80.a), (String) null, rVar, rVar, n6);
        pg0.Companion.getClass();
        q0 q0Var2 = pg0.a;
        k.g(q0Var2, "type");
        s mVar28 = new m("status", q0Var2, (String) null, rVar, rVar, r2);
        s mVar29 = new m("showProfileReadme", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        p40.Companion.getClass();
        q0 q0Var3 = p40.a;
        k.g(q0Var3, "type");
        s mVar30 = new m("profileReadme", q0Var3, (String) null, rVar, rVar, r3);
        s mVar31 = new m("viewerCanFollow", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar32 = new m("viewerIsFollowing", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar33 = new m("websiteUrl", xVar4, (String) null, rVar, rVar, rVar);
        s mVar34 = new m("viewerCanBlock", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar35 = new m("viewerCanUnblock", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        s mVar36 = new m("privateProfile", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        ct.Companion.getClass();
        s mVar37 = new m("projectsV2", l0.b(ct.a), (String) null, rVar, no.a.s(rf0.A, new u0(0)), n9);
        n80.Companion.getClass();
        s mVar38 = new m("socialAccounts", l0.b(n80.a), (String) null, rVar, no.a.s(rf0.R, new u0(4)), n11);
        m10.f.Companion.getClass();
        a = l.r(new s[]{mVar7, mVar8, mVar9, c2, mVar10, mVar11, mVar12, c3, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, new m("achievements", l0.b(m10.f.a), (String) null, rVar, no.a.s(rf0.b, new u0(10)), n12)});
    }
}
