package ew;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.ck;
import m10.ct;
import m10.d20;
import m10.eh;
import m10.gh;
import m10.i30;
import m10.j10;
import m10.ki;
import m10.l10;
import m10.l40;
import m10.ly;
import m10.n40;
import m10.om;
import m10.p40;
import m10.q30;
import m10.sa;
import m10.t40;
import m10.ub0;
import m10.v40;
import m10.wg;
import m10.x10;
import m10.xf0;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class i {
    public static final List a;

    static {
        eh.Companion.getClass();
        x xVar = eh.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = d0.n("Ref");
        List list = h.a;
        aa.s c = no.a.c(list, "selections", "Ref", n, list);
        ah.Companion.getClass();
        x xVar2 = ah.a;
        List r = x61.l.r(new aa.s[]{mVar, c, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Ref", d0.n("Ref"), list), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ch.Companion.getClass();
        x xVar3 = ch.a;
        List n2 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar3 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar4 = new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r3 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list2 = fq.b.a;
        List r4 = x61.l.r(new aa.s[]{mVar2, mVar3, mVar4, no.a.c(list2, "selections", "Actor", r3, list2)});
        List n3 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List n4 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        gh.Companion.getClass();
        x xVar4 = gh.a;
        k71.k.g(xVar4, "type");
        List r5 = x61.l.r(new aa.m[]{new aa.m("contentHTML", xVar4, (String) null, rVar, rVar, rVar), new aa.m("path", xVar, (String) null, rVar, rVar, rVar)});
        List r6 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        ub0.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{new aa.m("topic", l0.b(ub0.d), (String) null, rVar, rVar, r6), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        t40.Companion.getClass();
        List n5 = d0.n(new aa.m("nodes", l0.a(t40.a), (String) null, rVar, rVar, r7));
        List n6 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n7 = d0.n("License");
        List list3 = qt.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar5, no.a.c(list3, "selections", "License", n7, list3), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar6 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        l40.Companion.getClass();
        j0 j0Var = l40.e;
        List r11 = x61.l.r(new aa.m[]{mVar6, mVar7, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List n8 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("name", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar10 = new aa.m("tagName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        sa.Companion.getClass();
        x xVar5 = sa.a;
        k71.k.g(xVar5, "type");
        List r12 = x61.l.r(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("publishedAt", xVar5, (String) null, rVar, rVar, rVar), new aa.m("createdAt", l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n9 = d0.n("MergeQueue");
        List list4 = cu.c.a;
        List r13 = x61.l.r(new aa.s[]{mVar11, no.a.c(list4, "selections", "MergeQueue", n9, list4), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List n11 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.m mVar12 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        x xVar6 = cc0.a;
        List r14 = x61.l.r(new aa.m[]{mVar12, new aa.m("url", l0.b(xVar6), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        i30.Companion.getClass();
        q0 q0Var = i30.w0;
        List n12 = d0.n(new aa.m("nodes", l0.a(q0Var), (String) null, rVar, rVar, r14));
        aa.s mVar13 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar15 = new aa.m("databaseId", xVar3, (String) null, rVar, rVar, rVar);
        List n13 = d0.n("Repository");
        List list5 = b.a;
        aa.s c2 = no.a.c(list5, "selections", "Repository", n13, list5);
        aa.s mVar16 = new aa.m("contributorsCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        j10.Companion.getClass();
        q0 q0Var2 = j10.e;
        k71.k.g(q0Var2, "type");
        aa.s mVar17 = new aa.m("defaultBranchRef", q0Var2, (String) null, d0.n(new aa.l("defaultBranch", false)), rVar, r);
        aa.s mVar18 = new aa.m("ref", q0Var2, "branchInfo", no.a.t("defaultBranch", true), no.a.s(i30.T, new u0(new aa.t("qualifiedName"))), r2);
        aa.s mVar19 = new aa.m("forkCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar7 = wg.a;
        aa.s mVar20 = new aa.m("hasIssuesEnabled", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("showActions", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("homepageUrl", xVar6, (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("isPrivate", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("isArchived", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("isTemplate", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("isFork", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("forkingAllowed", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("isEmpty", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar29 = new aa.m("isInOrganization", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        ki.Companion.getClass();
        aa.s mVar30 = new aa.m("issues", l0.b(ki.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(i30.q, new u0(0)), new aa.k(i30.r, new u0(d0.n("OPEN")))}), n2);
        aa.s mVar31 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar32 = new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r4);
        ly.Companion.getClass();
        aa.s mVar33 = new aa.m("pullRequests", l0.b(ly.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(i30.Q, new u0(0)), new aa.k(i30.R, new u0(d0.n("OPEN")))}), n3);
        l10.Companion.getClass();
        q0 q0Var3 = l10.a;
        k71.k.g(q0Var3, "type");
        aa.s mVar34 = new aa.m("refs", q0Var3, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(i30.V, new u0(0)), new aa.k(i30.Y, new u0("refs/heads/"))}), n4);
        p40.Companion.getClass();
        q0 q0Var4 = p40.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar35 = new aa.m("readme", q0Var4, (String) null, rVar, no.a.s(i30.S, new u0(new aa.t("branch"))), r5);
        v40.Companion.getClass();
        aa.s mVar36 = new aa.m("repositoryTopics", l0.b(v40.a), (String) null, rVar, no.a.s(i30.d0, new u0(6)), n5);
        aa.s mVar37 = new aa.m("url", l0.b(xVar6), (String) null, rVar, rVar, rVar);
        aa.s mVar38 = new aa.m("shortDescriptionHTML", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar39 = new aa.m("descriptionHTML", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar, "type");
        aa.s mVar40 = new aa.m("description", xVar, (String) null, rVar, rVar, rVar);
        aa.s mVar41 = new aa.m("viewerCanAdminister", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar42 = new aa.m("viewerCanPush", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar43 = new aa.m("viewerCanSubscribe", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        n40.Companion.getClass();
        a0 a0Var = n40.s;
        k71.k.g(a0Var, "type");
        aa.s mVar44 = new aa.m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar);
        xf0.Companion.getClass();
        aa.s mVar45 = new aa.m("watchers", l0.b(xf0.a), (String) null, rVar, no.a.s(i30.s0, new u0(0)), n6);
        ck.Companion.getClass();
        q0 q0Var5 = ck.a;
        k71.k.g(q0Var5, "type");
        aa.s mVar46 = new aa.m("licenseInfo", q0Var5, (String) null, rVar, rVar, r8);
        aa.s mVar47 = new aa.m("isDiscussionsEnabled", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar48 = new aa.m("discussionsCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        aa.s mVar49 = new aa.m("parent", q0Var, (String) null, rVar, rVar, r11);
        d20.Companion.getClass();
        aa.s mVar50 = new aa.m("releases", l0.b(d20.a), (String) null, rVar, no.a.s(i30.b0, new u0(0)), n8);
        List r15 = x61.l.r(new String[]{"Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team"});
        List list6 = zw.a.a;
        aa.s c3 = no.a.c(list6, "selections", "Subscribable", r15, list6);
        x10.Companion.getClass();
        q0 q0Var6 = x10.e;
        k71.k.g(q0Var6, "type");
        aa.s mVar51 = new aa.m("latestRelease", q0Var6, (String) null, rVar, rVar, r12);
        List n14 = d0.n("Repository");
        List list7 = rx.f.a;
        aa.s c4 = no.a.c(list7, "selections", "Repository", n14, list7);
        aa.s mVar52 = new aa.m("isViewersFavorite", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar53 = new aa.m("viewerHasBlockedContributors", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        aa.s mVar54 = new aa.m("viewerBlockedByOwner", l0.b(xVar7), (String) null, rVar, rVar, rVar);
        om.Companion.getClass();
        q0 q0Var7 = om.d;
        k71.k.g(q0Var7, "type");
        aa.s mVar55 = new aa.m("mergeQueue", q0Var7, (String) null, rVar, no.a.s(i30.A, new u0(new aa.t("branch"))), r13);
        List n15 = d0.n("Repository");
        List list8 = v.a;
        aa.s c5 = no.a.c(list8, "selections", "Repository", n15, list8);
        ct.Companion.getClass();
        aa.s mVar56 = new aa.m("projectsV2", l0.b(ct.a), (String) null, rVar, no.a.s(i30.M, new u0(0)), n11);
        List n16 = d0.n("Repository");
        List list9 = p.a;
        aa.s c6 = no.a.c(list9, "selections", "Repository", n16, list9);
        q30.Companion.getClass();
        aa.s mVar57 = new aa.m("forks", l0.b(q30.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(i30.k, new u0(d0.n("OWNER"))), new aa.k(i30.m, new u0(1))}), n12);
        k71.k.g(xVar7, "type");
        a = x61.l.r(new aa.s[]{mVar13, mVar14, mVar15, c2, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, mVar48, mVar49, mVar50, c3, mVar51, c4, mVar52, mVar53, mVar54, mVar55, c5, mVar56, c6, mVar57, new aa.m("isCopilotAgentEnabled", xVar7, (String) null, rVar, rVar, rVar)});
    }
}
