package ew;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.cn;
import m10.eh;
import m10.gh;
import m10.gj;
import m10.sa;
import m10.wg;
import m10.wh;
import m10.wi;
import m10.x1;
import m10.yi;
import m10.z1;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class l {
    public static final List a;

    static {
        eh.Companion.getClass();
        x xVar = eh.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        aa.s mVar2 = new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = fq.b.a;
        List r2 = x61.l.r(new aa.s[]{mVar, mVar2, no.a.c(list, "selections", "Actor", r, list)});
        aa.s mVar3 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = d0.n("Milestone");
        List list2 = gu.a.a;
        aa.s c = no.a.c(list2, "selections", "Milestone", n, list2);
        ah.Companion.getClass();
        x xVar2 = ah.a;
        List r3 = x61.l.r(new aa.s[]{mVar3, c, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("IssueType");
        List list3 = ht.a.a;
        List r4 = x61.l.r(new aa.s[]{mVar4, no.a.c(list3, "selections", "IssueType", n2, list3), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = d0.n("Issue");
        List list4 = dt.a.a;
        List r5 = x61.l.r(new aa.s[]{mVar5, no.a.c(list4, "selections", "Issue", n3, list4), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar6 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        x xVar3 = wg.a;
        List r6 = x61.l.r(new aa.m[]{mVar6, new aa.m("isCopilot", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.s mVar7 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list5 = wx.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar7, no.a.c(list5, "selections", "Node", r7, list5), new aa.n("Bot", d0.n("Bot"), r6)});
        x1.Companion.getClass();
        List n4 = d0.n(new aa.m("nodes", l0.a(x1.a), (String) null, rVar, rVar, r8));
        aa.s mVar8 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        cc0.Companion.getClass();
        x xVar4 = cc0.a;
        aa.s mVar9 = new aa.m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar10 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar11 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar12 = new aa.m("titleHTML", l0.b(xVar), "titleHTMLString", rVar, rVar, rVar);
        sa.Companion.getClass();
        aa.s mVar13 = new aa.m("createdAt", l0.b(sa.a), (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("viewerDidAuthor", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar15 = new aa.m("locked", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m10.l.Companion.getClass();
        j0 j0Var = m10.l.a;
        k71.k.g(j0Var, "type");
        aa.s mVar16 = new aa.m("author", j0Var, (String) null, rVar, rVar, r2);
        k71.k.g(xVar3, "type");
        aa.s mVar17 = new aa.m("isReadByViewer", xVar3, (String) null, rVar, rVar, rVar);
        gh.Companion.getClass();
        aa.r b2 = l0.b(gh.a);
        wh.Companion.getClass();
        a81.t tVar = wh.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        aa.k kVar2 = new aa.k(wh.c, new u0(bool));
        aa.k kVar3 = new aa.k(wh.d, new u0(bool));
        a81.t tVar2 = wh.e;
        Boolean bool2 = Boolean.FALSE;
        aa.s mVar18 = new aa.m("bodyHTML", b2, "bodyHtml", rVar, x61.l.r(new aa.k[]{kVar, kVar2, kVar3, new aa.k(tVar2, new u0(bool2)), new aa.k(wh.f, new u0(bool2)), new aa.k(wh.g, new u0(bool))}), rVar);
        aa.s mVar19 = new aa.m("bodyUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        x xVar5 = ch.a;
        aa.s mVar20 = new aa.m("number", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        List r9 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list6 = br.a.a;
        aa.s c2 = no.a.c(list6, "selections", "Comment", r9, list6);
        List r11 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list7 = qv.a.a;
        aa.s c3 = no.a.c(list7, "selections", "Reactable", r11, list7);
        List r12 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list8 = qu.a.a;
        aa.s c4 = no.a.c(list8, "selections", "OrgBlockable", r12, list8);
        List r13 = x61.l.r(new String[]{"Issue", "PullRequest"});
        List list9 = hq.b.a;
        aa.s c5 = no.a.c(list9, "selections", "Assignable", r13, list9);
        wi.Companion.getClass();
        aa.s mVar21 = new aa.m("state", l0.b(wi.s), "issueState", rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list10 = mt.a.a;
        aa.s c6 = no.a.c(list10, "selections", "Labelable", r14, list10);
        cn.Companion.getClass();
        q0 q0Var = cn.a;
        k71.k.g(q0Var, "type");
        aa.s mVar22 = new aa.m("milestone", q0Var, (String) null, rVar, rVar, r3);
        List n5 = d0.n("Issue");
        List list11 = st.b.a;
        aa.s c7 = no.a.c(list11, "selections", "Issue", n5, list11);
        List r15 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment"});
        List list12 = nx.a.a;
        aa.s c8 = no.a.c(list12, "selections", "Updatable", r15, list12);
        aa.r b3 = l0.b(xVar5);
        a81.t tVar3 = wh.s;
        aa.s mVar23 = new aa.m("taskListItemCount", b3, "completeTaskListItemCount", rVar, no.a.s(tVar3, new u0(d0.n("COMPLETE"))), rVar);
        aa.s mVar24 = new aa.m("taskListItemCount", l0.b(xVar5), "incompleteTaskListItemCount", rVar, no.a.s(tVar3, new u0(d0.n("INCOMPLETE"))), rVar);
        aa.s mVar25 = new aa.m("viewerCanReopen", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        yi.Companion.getClass();
        a0 a0Var = yi.s;
        k71.k.g(a0Var, "type");
        aa.s mVar26 = new aa.m("stateReason", a0Var, (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("viewerCanAssign", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("viewerCanLabel", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar3, "type");
        aa.s mVar29 = new aa.m("isPinned", xVar3, (String) null, rVar, rVar, rVar);
        gj.Companion.getClass();
        q0 q0Var2 = gj.a;
        k71.k.g(q0Var2, "type");
        aa.s mVar30 = new aa.m("issueType", q0Var2, (String) null, rVar, rVar, r4);
        List n6 = d0.n("Issue");
        List list13 = e.a;
        aa.s c9 = no.a.c(list13, "selections", "Issue", n6, list13);
        q0 q0Var3 = wh.B;
        k71.k.g(q0Var3, "type");
        aa.s mVar31 = new aa.m("duplicateOf", q0Var3, (String) null, rVar, rVar, r5);
        z1.Companion.getClass();
        a = x61.l.r(new aa.s[]{mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, c2, c3, c4, c5, mVar21, c6, mVar22, c7, c8, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, c9, mVar31, new aa.m("suggestedActors", l0.b(z1.a), (String) null, rVar, no.a.s(wh.r, new u0(10)), n4)});
    }
}
