package a80;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import hc0.ap;
import hc0.bb;
import hc0.db;
import hc0.dc;
import hc0.dq;
import hc0.ev;
import hc0.ew;
import hc0.fb;
import hc0.fm;
import hc0.h6;
import hc0.hb;
import hc0.kz;
import hc0.lk;
import hc0.mu;
import hc0.nl;
import hc0.qz;
import hc0.rk;
import hc0.t3;
import hc0.uu;
import hc0.vk;
import hc0.xa;
import hc0.z5;
import java.util.List;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class h {
    public static final List a;

    static {
        fb.Companion.getClass();
        x xVar = fb.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        bb.Companion.getClass();
        x xVar2 = bb.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r3 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar2 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        ev.Companion.getClass();
        a0 a0Var = ev.s;
        k71.k.g(a0Var, "type");
        aa.m mVar4 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        z5.Companion.getClass();
        aa.m mVar5 = new aa.m("viewerSubscriptionTypes", l0.a(l0.b(z5.s)), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        j0 j0Var = dq.a;
        List r4 = x61.l.r(new aa.m[]{mVar2, mVar3, mVar4, mVar5, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r5 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = f30.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar6, no.a.c(list, "selections", "Actor", r5, list), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        db.Companion.getClass();
        x xVar3 = db.a;
        aa.m mVar7 = new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        kz.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar7, new aa.m("nodes", l0.a(kz.O), (String) null, rVar, rVar, r6)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        uu.Companion.getClass();
        List r8 = x61.l.r(new aa.m[]{mVar8, new aa.m("state", l0.b(uu.s), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar9 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        mu.Companion.getClass();
        q0 q0Var = mu.c;
        k71.k.g(q0Var, "type");
        List r9 = x61.l.r(new aa.m[]{mVar9, new aa.m("statusCheckRollup", q0Var, (String) null, rVar, rVar, r8), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar10 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        List r11 = x61.l.r(new aa.m[]{mVar10, new aa.m("commit", l0.b(t3.j), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        rk.Companion.getClass();
        List n = d0.n(new aa.m("nodes", l0.a(rk.a), (String) null, rVar, rVar, r11));
        List n2 = d0.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        aa.s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar12 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar4 = xa.a;
        aa.s mVar13 = new aa.m("isDraft", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        aa.s mVar15 = new aa.m("titleHTML", l0.b(hb.a), "titleHTMLString", rVar, rVar, rVar);
        aa.s mVar16 = new aa.m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        aa.s mVar17 = new aa.m("createdAt", l0.b(h6.a), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        q0 q0Var2 = ap.k0;
        k71.k.g(q0Var2, "type");
        aa.s mVar18 = new aa.m("headRepository", q0Var2, (String) null, rVar, rVar, r);
        aa.s mVar19 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar20 = new aa.m("isReadByViewer", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        List r12 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list2 = d60.a.a;
        aa.s c = no.a.c(list2, "selections", "Labelable", r12, list2);
        fm.Companion.getClass();
        aa.s mVar22 = new aa.m("state", l0.b(fm.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4);
        ew.Companion.getClass();
        aa.s mVar24 = new aa.m("url", l0.b(ew.a), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        nl.Companion.getClass();
        a0 a0Var2 = nl.s;
        k71.k.g(a0Var2, "type");
        aa.s mVar26 = new aa.m("reviewDecision", a0Var2, (String) null, rVar, rVar, rVar);
        qz.Companion.getClass();
        aa.r b2 = l0.b(qz.a);
        lk.Companion.getClass();
        aa.s mVar27 = new aa.m("assignees", b2, (String) null, rVar, no.a.s(lk.a, new u0(25)), r7);
        vk.Companion.getClass();
        aa.s mVar28 = new aa.m("commits", l0.b(vk.a), (String) null, rVar, no.a.s(lk.k, new u0(1)), n);
        dc.Companion.getClass();
        q0 q0Var3 = dc.a;
        k71.k.g(q0Var3, "type");
        aa.s mVar29 = new aa.m("closingIssuesReferences", q0Var3, (String) null, rVar, rVar, n2);
        List n3 = d0.n("PullRequest");
        List list3 = r.a;
        a = x61.l.r(new aa.s[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, c, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, no.a.c(list3, "selections", "PullRequest", n3, list3)});
    }

    public static List a() {
        return a;
    }
}
