package a80;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.t;
import aa.u0;
import aa.x;
import hc0.ab;
import hc0.ap;
import hc0.ar;
import hc0.bb;
import hc0.br;
import hc0.cb;
import hc0.ck;
import hc0.db;
import hc0.dk;
import hc0.dl;
import hc0.dw;
import hc0.eb;
import hc0.ew;
import hc0.fb;
import hc0.ff;
import hc0.fm;
import hc0.fv;
import hc0.g6;
import hc0.gv;
import hc0.h6;
import hc0.hb;
import hc0.j2;
import hc0.jn;
import hc0.k0;
import hc0.k2;
import hc0.kf;
import hc0.kk;
import hc0.kr;
import hc0.kz;
import hc0.l2;
import hc0.lk;
import hc0.ll;
import hc0.lr;
import hc0.lu;
import hc0.m00;
import hc0.ml;
import hc0.mr;
import hc0.mu;
import hc0.nj;
import hc0.nl;
import hc0.nn;
import hc0.nr;
import hc0.nu;
import hc0.oj;
import hc0.ou;
import hc0.p00;
import hc0.pj;
import hc0.pu;
import hc0.q00;
import hc0.qj;
import hc0.qu;
import hc0.rj;
import hc0.rk;
import hc0.ru;
import hc0.s3;
import hc0.sj;
import hc0.su;
import hc0.t3;
import hc0.ta;
import hc0.tj;
import hc0.uu;
import hc0.v2;
import hc0.vk;
import hc0.vl;
import hc0.wa;
import hc0.xa;
import hc0.yq;
import hc0.zo;
import hc0.zq;
import java.util.List;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class o {
    public static final List a;

    static {
        bb.Companion.getClass();
        aa.r b = l0.b(ab.a());
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        List o = d0.o(mVar, new aa.m("nameWithOwner", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        List o2 = d0.o(new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("nameWithOwner", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar2 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar3 = new aa.m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List o3 = d0.o("Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User");
        List list = f30.b.a;
        List o4 = d0.o(mVar2, mVar3, no.a.c(list, "selections", "Actor", o3, list));
        aa.s mVar4 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List o5 = d0.o("Achievement", "AchievementTier", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile");
        List a2 = ka0.a.a();
        List o6 = d0.o(mVar4, no.a.c(a2, "selections", "Node", o5, a2), new aa.m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar5 = new aa.m("abbreviatedOid", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        List o7 = d0.o(mVar5, new aa.m("committedDate", l0.b(g6.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar6 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("context", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        uu.Companion.getClass();
        a0 a0Var = uu.s;
        aa.m mVar8 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        x a3 = eb.a();
        k71.k.g(a3, "type");
        List o8 = d0.o(mVar6, mVar7, mVar8, new aa.m("description", a3, (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        db.Companion.getClass();
        aa.m mVar9 = new aa.m("totalCount", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        zq.Companion.getClass();
        List o9 = d0.o(mVar9, new aa.m("nodes", l0.a(yq.a()), (String) null, rVar, rVar, o8));
        x a4 = cb.a();
        k71.k.g(a4, "type");
        aa.m mVar10 = new aa.m("recommendedApprovingReviewCount", a4, (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        List o11 = d0.o(mVar10, new aa.m("requiresCodeOwnerReviews", l0.b(wa.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerAllowedToDismissReviews", l0.b(wa.a()), (String) null, rVar, rVar, rVar));
        nn.Companion.getClass();
        q0 q0Var = nn.a;
        k71.k.g(q0Var, "type");
        List o12 = d0.o(new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, o11), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        List n = d0.n(new aa.m("viewerCanPush", l0.b(wa.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar11 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        List o13 = d0.o(mVar11, new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, n), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar12 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("Milestone");
        List list2 = v60.a.a;
        List o14 = d0.o(mVar12, no.a.c(list2, "selections", "Milestone", n2, list2), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar));
        List o15 = d0.o(new aa.m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar13 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar14 = new aa.m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        dk.Companion.getClass();
        List o16 = d0.o(mVar13, mVar14, new aa.m("state", l0.b(ck.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        tj.Companion.getClass();
        q0 a5 = sj.a();
        k71.k.g(a5, "type");
        aa.m mVar15 = new aa.m("column", a5, (String) null, rVar, rVar, o15);
        nj.Companion.getClass();
        List o17 = d0.o(mVar15, new aa.m("project", l0.b(nj.a), (String) null, rVar, rVar, o16), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        pj.Companion.getClass();
        List n3 = d0.n(new aa.m("nodes", l0.a(oj.a()), (String) null, rVar, rVar, o17));
        aa.s mVar16 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List n4 = d0.n("ReviewRequest");
        List a6 = d90.a.a();
        List o18 = d0.o(mVar16, no.a.c(a6, "selections", "ReviewRequest", n4, a6), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar));
        lr.Companion.getClass();
        List n5 = d0.n(new aa.m("nodes", l0.a(kr.a()), (String) null, rVar, rVar, o18));
        aa.s mVar17 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List n6 = d0.n("PullRequestReview");
        List list3 = f80.b.a;
        List o19 = d0.o(mVar17, no.a.c(list3, "selections", "PullRequestReview", n6, list3), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar));
        dl.Companion.getClass();
        q0 q0Var2 = dl.d;
        List n7 = d0.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, o19));
        List n8 = d0.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, d0.o(new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar), no.a.c(list3, "selections", "PullRequestReview", d0.n("PullRequestReview"), list3), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar))));
        List o21 = d0.o(new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.n("User", d0.n("User"), d0.o(new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar), no.a.c(list, "selections", "Actor", d0.o("Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"), list))), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar18 = new aa.m("isAuthor", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar19 = new aa.m("isCommenter", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        kz.Companion.getClass();
        List o22 = d0.o(mVar18, mVar19, new aa.m("reviewer", l0.b(kz.O), (String) null, rVar, rVar, o21));
        aa.m mVar20 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar21 = new aa.m("context", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar22 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        x a7 = dw.a();
        k71.k.g(a7, "type");
        aa.m mVar23 = new aa.m("avatarUrl", a7, (String) null, rVar, rVar, rVar);
        x a8 = eb.a();
        k71.k.g(a8, "type");
        aa.m mVar24 = new aa.m("description", a8, (String) null, rVar, rVar, rVar);
        x a9 = dw.a();
        k71.k.g(a9, "type");
        aa.m mVar25 = new aa.m("targetUrl", a9, (String) null, rVar, rVar, rVar);
        aa.r b2 = l0.b(wa.a());
        su.Companion.getClass();
        ru.a();
        List o23 = d0.o(mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(su.b, new u0(new t("numberNullableBug"))), rVar));
        List o24 = d0.o(new aa.m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        m00.Companion.getClass();
        List o25 = d0.o(new aa.m("workflow", l0.b(m00.c), (String) null, rVar, rVar, o24), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        List o26 = d0.o(new aa.m("logoUrl", l0.b(dw.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        q00.Companion.getClass();
        q0 a11 = p00.a();
        k71.k.g(a11, "type");
        aa.m mVar26 = new aa.m("workflowRun", a11, (String) null, rVar, rVar, o25);
        hc0.l0.Companion.getClass();
        q0 a12 = k0.a();
        k71.k.g(a12, "type");
        List o27 = d0.o(mVar26, new aa.m("app", a12, (String) null, rVar, rVar, o26), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar27 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        j2.Companion.getClass();
        a0 a0Var2 = j2.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar28 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar29 = new aa.m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar30 = new aa.m("duration", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        x a13 = eb.a();
        k71.k.g(a13, "type");
        aa.m mVar31 = new aa.m("summary", a13, (String) null, rVar, rVar, rVar);
        aa.m mVar32 = new aa.m("permalink", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        v2.Companion.getClass();
        aa.m mVar33 = new aa.m("checkSuite", l0.b(v2.f), (String) null, rVar, rVar, o27);
        aa.r b3 = l0.b(wa.a());
        l2.Companion.getClass();
        k2.a();
        List o28 = d0.o(new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", d0.n("StatusContext"), o23), new aa.n("CheckRun", d0.n("CheckRun"), d0.o(mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(l2.b, new u0(new t("numberNullableBug"))), rVar))));
        aa.m mVar34 = new aa.m("totalCount", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        ou.Companion.getClass();
        List o29 = d0.o(mVar34, new aa.m("nodes", l0.a(nu.a()), (String) null, rVar, rVar, o28));
        aa.m mVar35 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar36 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        qu.Companion.getClass();
        aa.r b4 = l0.b(pu.a());
        mu.Companion.getClass();
        lu.b();
        List o31 = d0.o(mVar35, mVar36, new aa.m("contexts", b4, (String) null, rVar, no.a.s(mu.b, new u0(100)), o29), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar37 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar38 = new aa.m("committedDate", l0.b(g6.a()), (String) null, rVar, rVar, rVar);
        q0 a14 = lu.a();
        k71.k.g(a14, "type");
        List o32 = d0.o(mVar37, mVar38, new aa.m("statusCheckRollup", a14, (String) null, rVar, rVar, o31), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar39 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        t3.Companion.getClass();
        List o33 = d0.o(mVar39, new aa.m("commit", l0.b(s3.a()), (String) null, rVar, rVar, o32), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar40 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar41 = new aa.m("totalCount", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        rk.Companion.getClass();
        List o34 = d0.o(mVar40, mVar41, new aa.m("nodes", l0.a(rk.a), (String) null, rVar, rVar, o33));
        vl.Companion.getClass();
        aa.m mVar42 = new aa.m("state", l0.b(vl.s), (String) null, rVar, rVar, rVar);
        x a15 = g6.a();
        k71.k.g(a15, "type");
        List o35 = d0.o(mVar42, new aa.m("submittedAt", a15, (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        aa.s mVar43 = new aa.m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar44 = new aa.m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar45 = new aa.m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        ta.Companion.getClass();
        aa.s mVar46 = new aa.m("headRefOid", l0.b(ta.a), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        q0 a16 = zo.a();
        k71.k.g(a16, "type");
        aa.s mVar47 = new aa.m("headRepository", a16, (String) null, rVar, rVar, o);
        q0 a17 = zo.a();
        k71.k.g(a17, "type");
        aa.s mVar48 = new aa.m("baseRepository", a17, (String) null, rVar, rVar, o2);
        aa.s mVar49 = new aa.m("title", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        x xVar = hb.a;
        aa.s mVar50 = new aa.m("titleHTML", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar51 = new aa.m("createdAt", l0.b(g6.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar52 = new aa.m("viewerCanDeleteHeadRef", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar53 = new aa.m("viewerDidAuthor", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar54 = new aa.m("locked", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        hc0.l.Companion.getClass();
        j0 a18 = hc0.k.a();
        k71.k.g(a18, "type");
        aa.s mVar55 = new aa.m("author", a18, (String) null, rVar, rVar, o4);
        x a19 = wa.a();
        k71.k.g(a19, "type");
        aa.s mVar56 = new aa.m("isReadByViewer", a19, (String) null, rVar, rVar, rVar);
        aa.r b5 = l0.b(xVar);
        lk.Companion.getClass();
        kk.a();
        a81.t tVar = lk.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        kk.b();
        aa.k kVar2 = new aa.k(lk.c, new u0(bool));
        kk.c();
        a81.t tVar2 = lk.d;
        Boolean bool2 = Boolean.FALSE;
        aa.k kVar3 = new aa.k(tVar2, new u0(bool2));
        kk.d();
        aa.k kVar4 = new aa.k(lk.e, new u0(bool2));
        kk.e();
        aa.s mVar57 = new aa.m("bodyHTML", b5, "bodyHtml", rVar, d0.o(kVar, kVar2, kVar3, kVar4, new aa.k(lk.f, new u0(bool))), rVar);
        aa.s mVar58 = new aa.m("number", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        List o36 = d0.o("CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment");
        List list4 = d40.a.a;
        aa.s c = no.a.c(list4, "selections", "Comment", o36, list4);
        List o37 = d0.o("CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment");
        List list5 = j80.a.a;
        aa.s c2 = no.a.c(list5, "selections", "Reactable", o37, list5);
        List o38 = d0.o("CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment");
        List list6 = h70.a.a;
        aa.s c3 = no.a.c(list6, "selections", "OrgBlockable", o38, list6);
        List o39 = d0.o("Issue", "PullRequest");
        List a21 = j30.b.a();
        aa.s c4 = no.a.c(a21, "selections", "Assignable", o39, a21);
        fm.Companion.getClass();
        aa.s mVar59 = new aa.m("state", l0.b(fm.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar60 = new aa.m("changedFiles", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar61 = new aa.m("additions", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar62 = new aa.m("deletions", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        ff.Companion.getClass();
        aa.s mVar63 = new aa.m("mergeStateStatus", l0.b(ff.s), (String) null, rVar, rVar, rVar);
        j0 a22 = hc0.k.a();
        k71.k.g(a22, "type");
        aa.s mVar64 = new aa.m("mergedBy", a22, (String) null, rVar, rVar, o6);
        q0 a23 = s3.a();
        k71.k.g(a23, "type");
        aa.s mVar65 = new aa.m("mergeCommit", a23, (String) null, rVar, rVar, o7);
        nl.Companion.getClass();
        a0 a24 = ml.a();
        k71.k.g(a24, "type");
        aa.s mVar66 = new aa.m("reviewDecision", a24, (String) null, rVar, rVar, rVar);
        aa.s mVar67 = new aa.m("isDraft", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        br.Companion.getClass();
        aa.r b6 = l0.b(ar.a());
        kk.k();
        aa.s mVar68 = new aa.m("requiredStatusChecks", b6, (String) null, rVar, no.a.s(lk.u, new u0(25)), o9);
        jn.Companion.getClass();
        q0 q0Var3 = jn.b;
        k71.k.g(q0Var3, "type");
        aa.s mVar69 = new aa.m("baseRef", q0Var3, (String) null, rVar, rVar, o12);
        aa.s mVar70 = new aa.m("baseRefName", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var3, "type");
        aa.s mVar71 = new aa.m("headRef", q0Var3, (String) null, rVar, rVar, o13);
        aa.s mVar72 = new aa.m("headRefName", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List o41 = d0.o("Discussion", "Issue", "PullRequest");
        List a25 = d60.a.a();
        aa.s c5 = no.a.c(a25, "selections", "Labelable", o41, a25);
        kf.Companion.getClass();
        q0 q0Var4 = kf.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar73 = new aa.m("milestone", q0Var4, (String) null, rVar, rVar, o14);
        rj.Companion.getClass();
        aa.r b7 = l0.b(qj.a());
        kk.j();
        aa.s mVar74 = new aa.m("projectCards", b7, (String) null, rVar, no.a.s(lk.t, new u0(25)), n3);
        nr.Companion.getClass();
        q0 a26 = mr.a();
        k71.k.g(a26, "type");
        kk.l();
        aa.s mVar75 = new aa.m("reviewRequests", a26, (String) null, rVar, no.a.s(lk.v, new u0(25)), n5);
        ll.Companion.getClass();
        q0 q0Var5 = ll.a;
        k71.k.g(q0Var5, "type");
        kk.i();
        aa.s mVar76 = new aa.m("latestReviews", q0Var5, (String) null, rVar, no.a.s(lk.q, new u0(25)), n7);
        k71.k.g(q0Var5, "type");
        kk.g();
        aa.k kVar5 = new aa.k(lk.o, new u0(25));
        kk.h();
        aa.s mVar77 = new aa.m("latestOpinionatedReviews", q0Var5, (String) null, rVar, d0.o(kVar5, new aa.k(lk.p, new u0(bool))), n8);
        gv.Companion.getClass();
        aa.s mVar78 = new aa.m("suggestedReviewers", l0.b(l0.a(fv.a())), (String) null, rVar, rVar, o22);
        aa.s mVar79 = new aa.m("actionRequiredWorkflowRunCount", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        vk.Companion.getClass();
        aa.r b8 = l0.b(vk.a);
        kk.f();
        aa.s mVar80 = new aa.m("commits", b8, (String) null, rVar, no.a.s(lk.k, new u0(1)), o34);
        List n9 = d0.n("PullRequest");
        List a27 = j60.a.a();
        aa.s c6 = no.a.c(a27, "selections", "PullRequest", n9, a27);
        List o42 = d0.o("CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment");
        List a28 = ba0.a.a();
        aa.s c7 = no.a.c(a28, "selections", "Updatable", o42, a28);
        List n11 = d0.n("PullRequest");
        List a29 = q.a();
        aa.s c8 = no.a.c(a29, "selections", "PullRequest", n11, a29);
        k71.k.g(q0Var2, "type");
        aa.s mVar81 = new aa.m("viewerLatestReview", q0Var2, (String) null, rVar, rVar, o35);
        List n12 = d0.n("PullRequest");
        List list7 = a.a;
        a = d0.o(mVar43, mVar44, mVar45, mVar46, mVar47, mVar48, mVar49, mVar50, mVar51, mVar52, mVar53, mVar54, mVar55, mVar56, mVar57, mVar58, c, c2, c3, c4, mVar59, mVar60, mVar61, mVar62, mVar63, mVar64, mVar65, mVar66, mVar67, mVar68, mVar69, mVar70, mVar71, mVar72, c5, mVar73, mVar74, mVar75, mVar76, mVar77, mVar78, mVar79, mVar80, c6, c7, c8, mVar81, no.a.c(list7, "selections", "PullRequest", n12, list7), new aa.m("viewerCanReopen", l0.b(wa.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanMergeAsAdmin", l0.b(wa.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanAssign", l0.b(wa.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanLabel", l0.b(wa.a()), (String) null, rVar, rVar, rVar));
    }
}
