package a80;

import aa.q0;
import aa.u0;
import aa.x;
import hc0.bb;
import hc0.d8;
import hc0.db;
import hc0.dl;
import hc0.ew;
import hc0.fb;
import hc0.jl;
import hc0.kz;
import hc0.xa;
import hc0.xl;
import java.util.List;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class p {
    public static final List a;

    static {
        bb.Companion.getClass();
        x xVar = bb.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar2 = fb.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("login", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("DiffLine");
        List list = b50.a.a;
        List r3 = x61.l.r(new aa.s[]{mVar2, no.a.c(list, "selections", "DiffLine", n, list)});
        aa.s mVar3 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar4 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        xa.Companion.getClass();
        x xVar3 = xa.a;
        aa.s mVar5 = new aa.m("isResolved", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        kz.Companion.getClass();
        q0 q0Var = kz.O;
        k71.k.g(q0Var, "type");
        aa.s mVar6 = new aa.m("resolvedBy", q0Var, (String) null, rVar, rVar, r2);
        aa.s mVar7 = new aa.m("viewerCanResolve", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar8 = new aa.m("viewerCanUnresolve", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        d8.Companion.getClass();
        aa.p a2 = l0.a(d8.a);
        xl.Companion.getClass();
        aa.s mVar9 = new aa.m("diffLines", a2, (String) null, rVar, no.a.s(xl.c, new u0(1)), r3);
        List n2 = d0Shadow.n("PullRequestReviewThread");
        List list2 = h80.a.a;
        List r4 = x61.l.r(new aa.s[]{mVar3, mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, no.a.c(list2, "selections", "PullRequestReviewThread", n2, list2)});
        aa.s mVar10 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar11 = new aa.m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        db.Companion.getClass();
        x xVar4 = db.a;
        k71.k.g(xVar4, "type");
        aa.s mVar12 = new aa.m("position", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("line", xVar4, (String) null, rVar, rVar, rVar);
        dl.Companion.getClass();
        q0 q0Var2 = dl.d;
        k71.k.g(q0Var2, "type");
        aa.s mVar14 = new aa.m("pullRequestReview", q0Var2, (String) null, rVar, rVar, r);
        q0 q0Var3 = xl.d;
        k71.k.g(q0Var3, "type");
        aa.s mVar15 = new aa.m("thread", q0Var3, (String) null, rVar, rVar, r4);
        aa.s mVar16 = new aa.m("path", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        jl.Companion.getClass();
        aa.s mVar17 = new aa.m("state", l0.b(jl.s), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        aa.s mVar18 = new aa.m("url", l0.b(ew.a), (String) null, rVar, rVar, rVar);
        List r5 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list3 = d40.a.a;
        aa.s c = no.a.c(list3, "selections", "Comment", r5, list3);
        List r6 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list4 = j80.a.a;
        aa.s c2 = no.a.c(list4, "selections", "Reactable", r6, list4);
        List r7 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list5 = ba0.b.a;
        aa.s c3 = no.a.c(list5, "selections", "Updatable", r7, list5);
        List r8 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list6 = h70.a.a;
        aa.s c4 = no.a.c(list6, "selections", "OrgBlockable", r8, list6);
        List r9 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReviewComment"});
        List list7 = z60.a.a;
        a = x61.l.r(new aa.s[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, c, c2, c3, c4, no.a.c(list7, "selections", "Minimizable", r9, list7)});
    }
}
