package hc0;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class rg {
    public static final rg A;
    public static final rg A0;
    public static final rg B;
    public static final rg B0;
    public static final rg C;
    public static final rg C0;
    public static final qg Companion;
    public static final rg D;
    public static final rg D0;
    public static final rg E;
    public static final rg E0;
    public static final rg F;
    public static final rg F0;
    public static final rg G;
    public static final /* synthetic */ rg[] G0;
    public static final rg H;
    public static final /* synthetic */ d71.b H0;
    public static final rg I;
    public static final rg J;
    public static final rg K;
    public static final rg L;
    public static final rg M;
    public static final rg N;
    public static final rg O;
    public static final rg P;
    public static final rg Q;
    public static final rg R;
    public static final rg S;
    public static final rg T;
    public static final rg U;
    public static final rg V;
    public static final rg W;
    public static final rg X;
    public static final rg Y;
    public static final rg Z;
    public static final rg a0;
    public static final rg b0;
    public static final rg c0;
    public static final rg d0;
    public static final rg e0;
    public static final rg f0;
    public static final rg g0;
    public static final rg h0;
    public static final rg i0;
    public static final rg j0;
    public static final rg k0;
    public static final rg l0;
    public static final rg m0;
    public static final rg n0;
    public static final rg o0;
    public static final rg p0;
    public static final rg q0;
    public static final rg r0;
    public static final rg s;
    public static final rg s0;
    public static final rg t;
    public static final rg t0;
    public static final rg u;
    public static final rg u0;
    public static final rg v;
    public static final rg v0;
    public static final rg w;
    public static final rg w0;
    public static final rg x;
    public static final rg x0;
    public static final rg y;
    public static final rg y0;
    public static final rg z;
    public static final rg z0;
    public final String r;

    static {
        rg rgVar = new rg("CHECK_SUITE", 0, "CHECK_SUITE");
        s = rgVar;
        rg rgVar2 = new rg("COMMIT", 1, "COMMIT");
        t = rgVar2;
        rg rgVar3 = new rg("COMMITS", 2, "COMMITS");
        u = rgVar3;
        rg rgVar4 = new rg("DEPLOYMENT_REVIEW", 3, "DEPLOYMENT_REVIEW");
        v = rgVar4;
        rg rgVar5 = new rg("DISCUSSION", 4, "DISCUSSION");
        w = rgVar5;
        rg rgVar6 = new rg("DISCUSSIONS", 5, "DISCUSSIONS");
        x = rgVar6;
        rg rgVar7 = new rg("DRAFT_ISSUE", 6, "DRAFT_ISSUE");
        y = rgVar7;
        rg rgVar8 = new rg("FILTER_ASSIGNEE", 7, "FILTER_ASSIGNEE");
        z = rgVar8;
        rg rgVar9 = new rg("FILTER_AUTHOR", 8, "FILTER_AUTHOR");
        A = rgVar9;
        rg rgVar10 = new rg("FILTER_DISCUSSION_CATEGORY", 9, "FILTER_DISCUSSION_CATEGORY");
        B = rgVar10;
        rg rgVar11 = new rg("FILTER_DISCUSSION_IS_UNANSWERED", 10, "FILTER_DISCUSSION_IS_UNANSWERED");
        C = rgVar11;
        rg rgVar12 = new rg("FILTER_DISCUSSION_TOP", 11, "FILTER_DISCUSSION_TOP");
        D = rgVar12;
        rg rgVar13 = new rg("FILTER_DISCUSSION_VIEWER", 12, "FILTER_DISCUSSION_VIEWER");
        E = rgVar13;
        rg rgVar14 = new rg("FILTER_ISSUE_STATUS", 13, "FILTER_ISSUE_STATUS");
        F = rgVar14;
        rg rgVar15 = new rg("FILTER_ISSUE_VIEWER", 14, "FILTER_ISSUE_VIEWER");
        G = rgVar15;
        rg rgVar16 = new rg("FILTER_LABEL", 15, "FILTER_LABEL");
        H = rgVar16;
        rg rgVar17 = new rg("FILTER_LANGUAGE", 16, "FILTER_LANGUAGE");
        I = rgVar17;
        rg rgVar18 = new rg("FILTER_MILESTONE", 17, "FILTER_MILESTONE");
        J = rgVar18;
        rg rgVar19 = new rg("FILTER_NOTIFICATION_FILTER", 18, "FILTER_NOTIFICATION_FILTER");
        K = rgVar19;
        rg rgVar20 = new rg("FILTER_NOTIFICATION_IS_UNREAD", 19, "FILTER_NOTIFICATION_IS_UNREAD");
        L = rgVar20;
        rg rgVar21 = new rg("FILTER_NOTIFICATION_STATUS", 20, "FILTER_NOTIFICATION_STATUS");
        M = rgVar21;
        rg rgVar22 = new rg("FILTER_ORGANIZATION", 21, "FILTER_ORGANIZATION");
        N = rgVar22;
        rg rgVar23 = new rg("FILTER_PROJECT", 22, "FILTER_PROJECT");
        O = rgVar23;
        rg rgVar24 = new rg("FILTER_PULL_REQUEST_REVIEW_STATUS", 23, "FILTER_PULL_REQUEST_REVIEW_STATUS");
        P = rgVar24;
        rg rgVar25 = new rg("FILTER_PULL_REQUEST_STATUS", 24, "FILTER_PULL_REQUEST_STATUS");
        Q = rgVar25;
        rg rgVar26 = new rg("FILTER_PULL_REQUEST_VIEWER", 25, "FILTER_PULL_REQUEST_VIEWER");
        R = rgVar26;
        rg rgVar27 = new rg("FILTER_REPOSITORY", 26, "FILTER_REPOSITORY");
        S = rgVar27;
        rg rgVar28 = new rg("FILTER_REPOSITORY_TYPE", 27, "FILTER_REPOSITORY_TYPE");
        T = rgVar28;
        rg rgVar29 = new rg("FILTER_REPOSITORY_VISIBILITY", 28, "FILTER_REPOSITORY_VISIBILITY");
        U = rgVar29;
        rg rgVar30 = new rg("FILTER_SORT", 29, "FILTER_SORT");
        V = rgVar30;
        rg rgVar31 = new rg("FILTER_TRENDING_DATE_RANGE", 30, "FILTER_TRENDING_DATE_RANGE");
        W = rgVar31;
        rg rgVar32 = new rg("FILTER_TRENDING_LANGUAGE", 31, "FILTER_TRENDING_LANGUAGE");
        X = rgVar32;
        rg rgVar33 = new rg("FILTER_TRENDING_SPOKEN_LANGUAGE", 32, "FILTER_TRENDING_SPOKEN_LANGUAGE");
        Y = rgVar33;
        rg rgVar34 = new rg("GIST", 33, "GIST");
        Z = rgVar34;
        rg rgVar35 = new rg("HOME", 34, "HOME");
        a0 = rgVar35;
        rg rgVar36 = new rg("ISSUE", 35, "ISSUE");
        b0 = rgVar36;
        rg rgVar37 = new rg("ISSUES", 36, "ISSUES");
        c0 = rgVar37;
        rg rgVar38 = new rg("NOTIFICATIONS", 37, "NOTIFICATIONS");
        d0 = rgVar38;
        rg rgVar39 = new rg("ORGANIZATION", 38, "ORGANIZATION");
        e0 = rgVar39;
        rg rgVar40 = new rg("PROJECT", 39, "PROJECT");
        f0 = rgVar40;
        rg rgVar41 = new rg("PROJECTS", 40, "PROJECTS");
        g0 = rgVar41;
        rg rgVar42 = new rg("PULL_REQUEST", 41, "PULL_REQUEST");
        h0 = rgVar42;
        rg rgVar43 = new rg("PULL_REQUESTS", 42, "PULL_REQUESTS");
        i0 = rgVar43;
        rg rgVar44 = new rg("PUSH_NOTIFICATIONS", 43, "PUSH_NOTIFICATIONS");
        j0 = rgVar44;
        rg rgVar45 = new rg("PUSH_NOTIFICATION_ACTION", 44, "PUSH_NOTIFICATION_ACTION");
        k0 = rgVar45;
        rg rgVar46 = new rg("PUSH_NOTIFICATION_ASSIGN", 45, "PUSH_NOTIFICATION_ASSIGN");
        l0 = rgVar46;
        rg rgVar47 = new rg("PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", 46, "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL");
        m0 = rgVar47;
        rg rgVar48 = new rg("PUSH_NOTIFICATION_MENTION", 47, "PUSH_NOTIFICATION_MENTION");
        n0 = rgVar48;
        rg rgVar49 = new rg("PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", 48, "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST");
        o0 = rgVar49;
        rg rgVar50 = new rg("PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", 49, "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW");
        p0 = rgVar50;
        rg rgVar51 = new rg("PUSH_NOTIFICATION_REVIEW_REQUEST", 50, "PUSH_NOTIFICATION_REVIEW_REQUEST");
        q0 = rgVar51;
        rg rgVar52 = new rg("RELEASE", 51, "RELEASE");
        r0 = rgVar52;
        rg rgVar53 = new rg("RELEASES", 52, "RELEASES");
        s0 = rgVar53;
        rg rgVar54 = new rg("REPOSITORIES", 53, "REPOSITORIES");
        t0 = rgVar54;
        rg rgVar55 = new rg("REPOSITORY", 54, "REPOSITORY");
        u0 = rgVar55;
        rg rgVar56 = new rg("REPOSITORY_ADVISORY", 55, "REPOSITORY_ADVISORY");
        v0 = rgVar56;
        rg rgVar57 = new rg("REPOSITORY_DEPENDABOT_THREAD_ALERT", 56, "REPOSITORY_DEPENDABOT_THREAD_ALERT");
        w0 = rgVar57;
        rg rgVar58 = new rg("REPOSITORY_VULNERABILITY_ALERT", 57, "REPOSITORY_VULNERABILITY_ALERT");
        x0 = rgVar58;
        rg rgVar59 = new rg("SECURITY_ADVISORY", 58, "SECURITY_ADVISORY");
        y0 = rgVar59;
        rg rgVar60 = new rg("SHORTCUT", 59, "SHORTCUT");
        z0 = rgVar60;
        rg rgVar61 = new rg("SWIPE_ACTIONS", 60, "SWIPE_ACTIONS");
        A0 = rgVar61;
        rg rgVar62 = new rg("TEAM_DISCUSSION", 61, "TEAM_DISCUSSION");
        B0 = rgVar62;
        rg rgVar63 = new rg("USER", 62, "USER");
        C0 = rgVar63;
        rg rgVar64 = new rg("USERS", 63, "USERS");
        D0 = rgVar64;
        rg rgVar65 = new rg("WORKFLOW_RUN", 64, "WORKFLOW_RUN");
        E0 = rgVar65;
        rg rgVar66 = new rg("UNKNOWN__", 65, "UNKNOWN__");
        F0 = rgVar66;
        rg[] rgVarArr = {rgVar, rgVar2, rgVar3, rgVar4, rgVar5, rgVar6, rgVar7, rgVar8, rgVar9, rgVar10, rgVar11, rgVar12, rgVar13, rgVar14, rgVar15, rgVar16, rgVar17, rgVar18, rgVar19, rgVar20, rgVar21, rgVar22, rgVar23, rgVar24, rgVar25, rgVar26, rgVar27, rgVar28, rgVar29, rgVar30, rgVar31, rgVar32, rgVar33, rgVar34, rgVar35, rgVar36, rgVar37, rgVar38, rgVar39, rgVar40, rgVar41, rgVar42, rgVar43, rgVar44, rgVar45, rgVar46, rgVar47, rgVar48, rgVar49, rgVar50, rgVar51, rgVar52, rgVar53, rgVar54, rgVar55, rgVar56, rgVar57, rgVar58, rgVar59, rgVar60, rgVar61, rgVar62, rgVar63, rgVar64, rgVar65, rgVar66};
        G0 = rgVarArr;
        H0 = v8.l0.t(rgVarArr);
        Companion = new qg();
        sy.d0.o(new String[]{"CHECK_SUITE", "COMMIT", "COMMITS", "DEPLOYMENT_REVIEW", "DISCUSSION", "DISCUSSIONS", "DRAFT_ISSUE", "FILTER_ASSIGNEE", "FILTER_AUTHOR", "FILTER_DISCUSSION_CATEGORY", "FILTER_DISCUSSION_IS_UNANSWERED", "FILTER_DISCUSSION_TOP", "FILTER_DISCUSSION_VIEWER", "FILTER_ISSUE_STATUS", "FILTER_ISSUE_VIEWER", "FILTER_LABEL", "FILTER_LANGUAGE", "FILTER_MILESTONE", "FILTER_NOTIFICATION_FILTER", "FILTER_NOTIFICATION_IS_UNREAD", "FILTER_NOTIFICATION_STATUS", "FILTER_ORGANIZATION", "FILTER_PROJECT", "FILTER_PULL_REQUEST_REVIEW_STATUS", "FILTER_PULL_REQUEST_STATUS", "FILTER_PULL_REQUEST_VIEWER", "FILTER_REPOSITORY", "FILTER_REPOSITORY_TYPE", "FILTER_REPOSITORY_VISIBILITY", "FILTER_SORT", "FILTER_TRENDING_DATE_RANGE", "FILTER_TRENDING_LANGUAGE", "FILTER_TRENDING_SPOKEN_LANGUAGE", "GIST", "HOME", "ISSUE", "ISSUES", "NOTIFICATIONS", "ORGANIZATION", "PROJECT", "PROJECTS", "PULL_REQUEST", "PULL_REQUESTS", "PUSH_NOTIFICATIONS", "PUSH_NOTIFICATION_ACTION", "PUSH_NOTIFICATION_ASSIGN", "PUSH_NOTIFICATION_DEPLOYMENT_APPROVAL", "PUSH_NOTIFICATION_MENTION", "PUSH_NOTIFICATION_MOBILE_AUTH_REQUEST", "PUSH_NOTIFICATION_PULL_REQUEST_REVIEW", "PUSH_NOTIFICATION_REVIEW_REQUEST", "RELEASE", "RELEASES", "REPOSITORIES", "REPOSITORY", "REPOSITORY_ADVISORY", "REPOSITORY_DEPENDABOT_THREAD_ALERT", "REPOSITORY_VULNERABILITY_ALERT", "SECURITY_ADVISORY", "SHORTCUT", "SWIPE_ACTIONS", "TEAM_DISCUSSION", "USER", "USERS", "WORKFLOW_RUN"});
    }

    public rg(String str, int i, String str2) {
        this.r = str2;
    }

    public static rg valueOf(String str) {
        return (rg) Enum.valueOf(rg.class, str);
    }

    public static rg[] values() {
        return (rg[]) G0.clone();
    }
}
