package hc0;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* loaded from: /home/user/work/p/classes4.dex */
public final class yf {
    public static final xf Companion;
    public static final yf s;
    public static final /* synthetic */ yf[] t;
    public static final /* synthetic */ d71.b u;
    public final String r;

    static {
        yf yfVar = new yf("EXPLORE_BOTTOM_NAVIGATION", 0, "EXPLORE_BOTTOM_NAVIGATION");
        yf yfVar2 = new yf("EXPLORE_FEATURED_REPOSITORY", 1, "EXPLORE_FEATURED_REPOSITORY");
        yf yfVar3 = new yf("EXPLORE_FOR_YOU_REPOSITORY", 2, "EXPLORE_FOR_YOU_REPOSITORY");
        yf yfVar4 = new yf("EXPLORE_STAR_FEATURED_REPOSITORY", 3, "EXPLORE_STAR_FEATURED_REPOSITORY");
        yf yfVar5 = new yf("EXPLORE_STAR_FOR_YOU_REPOSITORY", 4, "EXPLORE_STAR_FOR_YOU_REPOSITORY");
        yf yfVar6 = new yf("EXPLORE_STAR_TRENDING_REPOSITORY", 5, "EXPLORE_STAR_TRENDING_REPOSITORY");
        yf yfVar7 = new yf("EXPLORE_TRENDING_LIST_FILTER", 6, "EXPLORE_TRENDING_LIST_FILTER");
        yf yfVar8 = new yf("EXPLORE_TRENDING_REPOSITORY", 7, "EXPLORE_TRENDING_REPOSITORY");
        yf yfVar9 = new yf("FOLLOW", 8, "FOLLOW");
        yf yfVar10 = new yf("HOME_BOTTOM_NAVIGATION", 9, "HOME_BOTTOM_NAVIGATION");
        yf yfVar11 = new yf("HOME_CREATE_ISSUE", 10, "HOME_CREATE_ISSUE");
        yf yfVar12 = new yf("HOME_DISCUSSIONS", 11, "HOME_DISCUSSIONS");
        yf yfVar13 = new yf("HOME_FAVORITE_REPOSITORY_ITEM", 12, "HOME_FAVORITE_REPOSITORY_ITEM");
        yf yfVar14 = new yf("HOME_ISSUES", 13, "HOME_ISSUES");
        yf yfVar15 = new yf("HOME_ORGANIZATIONS", 14, "HOME_ORGANIZATIONS");
        yf yfVar16 = new yf("HOME_PROJECTS", 15, "HOME_PROJECTS");
        yf yfVar17 = new yf("HOME_PULL_REQUESTS", 16, "HOME_PULL_REQUESTS");
        yf yfVar18 = new yf("HOME_RECENT_ACTIVITY_ITEM", 17, "HOME_RECENT_ACTIVITY_ITEM");
        yf yfVar19 = new yf("HOME_RELEASE_NOTES", 18, "HOME_RELEASE_NOTES");
        yf yfVar20 = new yf("HOME_REPOSITORIES", 19, "HOME_REPOSITORIES");
        yf yfVar21 = new yf("HOME_REPOSITORY_LIST_FILTER", 20, "HOME_REPOSITORY_LIST_FILTER");
        yf yfVar22 = new yf("HOME_SHORTCUTS", 21, "HOME_SHORTCUTS");
        yf yfVar23 = new yf("HOME_STARRED", 22, "HOME_STARRED");
        yf yfVar24 = new yf("ISSUES_LIST_ITEM", 23, "ISSUES_LIST_ITEM");
        yf yfVar25 = new yf("ISSUES_SEARCH", 24, "ISSUES_SEARCH");
        yf yfVar26 = new yf("ISSUE_COMPOSER", 25, "ISSUE_COMPOSER");
        yf yfVar27 = new yf("NOTIFICATIONS_ONBOARDING_BANNER", 26, "NOTIFICATIONS_ONBOARDING_BANNER");
        yf yfVar28 = new yf("NOTIFICATION_BOTTOM_NAVIGATION", 27, "NOTIFICATION_BOTTOM_NAVIGATION");
        yf yfVar29 = new yf("NOTIFICATION_FILTER", 28, "NOTIFICATION_FILTER");
        yf yfVar30 = new yf("NOTIFICATION_LIST_FILTER", 29, "NOTIFICATION_LIST_FILTER");
        yf yfVar31 = new yf("NOTIFICATION_LIST_ITEM", 30, "NOTIFICATION_LIST_ITEM");
        yf yfVar32 = new yf("NOTIFICATION_LIST_ITEM_UNDO", 31, "NOTIFICATION_LIST_ITEM_UNDO");
        yf yfVar33 = new yf("NOTIFICATION_PUSH", 32, "NOTIFICATION_PUSH");
        yf yfVar34 = new yf("ONBOARDING_BANNER", 33, "ONBOARDING_BANNER");
        yf yfVar35 = new yf("PROFILE_BOTTOM_NAVIGATION", 34, "PROFILE_BOTTOM_NAVIGATION");
        yf yfVar36 = new yf("PROFILE_REPOSITORY_LIST_FILTER", 35, "PROFILE_REPOSITORY_LIST_FILTER");
        yf yfVar37 = new yf("PROJECTS_LIST_ITEM", 36, "PROJECTS_LIST_ITEM");
        yf yfVar38 = new yf("PROJECTS_QUICK_ACTION_CLOSE", 37, "PROJECTS_QUICK_ACTION_CLOSE");
        yf yfVar39 = new yf("PROJECTS_QUICK_ACTION_DELETE", 38, "PROJECTS_QUICK_ACTION_DELETE");
        yf yfVar40 = new yf("PROJECTS_QUICK_ACTION_EDIT_FIELD", 39, "PROJECTS_QUICK_ACTION_EDIT_FIELD");
        yf yfVar41 = new yf("PROJECTS_QUICK_ACTION_EDIT_TITLE", 40, "PROJECTS_QUICK_ACTION_EDIT_TITLE");
        yf yfVar42 = new yf("PROJECTS_QUICK_ACTION_OPEN_DETAILS", 41, "PROJECTS_QUICK_ACTION_OPEN_DETAILS");
        yf yfVar43 = new yf("PROJECTS_QUICK_ACTION_OTHER_PROJECTS", 42, "PROJECTS_QUICK_ACTION_OTHER_PROJECTS");
        yf yfVar44 = new yf("PROJECTS_QUICK_ACTION_REOPEN", 43, "PROJECTS_QUICK_ACTION_REOPEN");
        yf yfVar45 = new yf("PROJECTS_TABLE_VIEW_LIST_ITEM", 44, "PROJECTS_TABLE_VIEW_LIST_ITEM");
        yf yfVar46 = new yf("PROJECT_VIEW", 45, "PROJECT_VIEW");
        yf yfVar47 = new yf("PROJECT_VIEW_TIMEOUT_CTA", 46, "PROJECT_VIEW_TIMEOUT_CTA");
        yf yfVar48 = new yf("PULL_REQUESTS_LIST_ITEM", 47, "PULL_REQUESTS_LIST_ITEM");
        yf yfVar49 = new yf("PULL_REQUESTS_SEARCH", 48, "PULL_REQUESTS_SEARCH");
        yf yfVar50 = new yf("RELEASES_LIST_LATEST_RELEASE", 49, "RELEASES_LIST_LATEST_RELEASE");
        yf yfVar51 = new yf("RELEASE_DOWNLOAD_ASSET", 50, "RELEASE_DOWNLOAD_ASSET");
        yf yfVar52 = new yf("RELEASE_LINKED_DISCUSSION", 51, "RELEASE_LINKED_DISCUSSION");
        yf yfVar53 = new yf("REPOSITORY_DISCUSSIONS_LIST_FILTER", 52, "REPOSITORY_DISCUSSIONS_LIST_FILTER");
        yf yfVar54 = new yf("REPOSITORY_ISSUES_LIST_FILTER", 53, "REPOSITORY_ISSUES_LIST_FILTER");
        yf yfVar55 = new yf("REPOSITORY_LATEST_RELEASE", 54, "REPOSITORY_LATEST_RELEASE");
        yf yfVar56 = new yf("REPOSITORY_PULL_REQUESTS_LIST_FILTER", 55, "REPOSITORY_PULL_REQUESTS_LIST_FILTER");
        yf yfVar57 = new yf("SETTINGS_DISABLE_ANALYTICS", 56, "SETTINGS_DISABLE_ANALYTICS");
        yf yfVar58 = new yf("SHORTCUTS_LIST_ITEM", 57, "SHORTCUTS_LIST_ITEM");
        yf yfVar59 = new yf("SHORTCUT_SUGGESTIONS_LIST_ITEM", 58, "SHORTCUT_SUGGESTIONS_LIST_ITEM");
        yf yfVar60 = new yf("SHOW_MORE_ROLLUP", 59, "SHOW_MORE_ROLLUP");
        yf yfVar61 = new yf("STAR_REPOSITORY", 60, "STAR_REPOSITORY");
        yf yfVar62 = new yf("TRIAGE_ASSIGNEE_EDIT", 61, "TRIAGE_ASSIGNEE_EDIT");
        yf yfVar63 = new yf("TRIAGE_CLOSE", 62, "TRIAGE_CLOSE");
        yf yfVar64 = new yf("TRIAGE_COMMENT", 63, "TRIAGE_COMMENT");
        yf yfVar65 = new yf("TRIAGE_COMMENT_DOWN", 64, "TRIAGE_COMMENT_DOWN");
        yf yfVar66 = new yf("TRIAGE_COMMENT_EDIT", 65, "TRIAGE_COMMENT_EDIT");
        yf yfVar67 = new yf("TRIAGE_COMMENT_UP", 66, "TRIAGE_COMMENT_UP");
        yf yfVar68 = new yf("TRIAGE_EXPAND", 67, "TRIAGE_EXPAND");
        yf yfVar69 = new yf("TRIAGE_LABEL_EDIT", 68, "TRIAGE_LABEL_EDIT");
        yf yfVar70 = new yf("TRIAGE_LINKED_ITEM_EDIT", 69, "TRIAGE_LINKED_ITEM_EDIT");
        yf yfVar71 = new yf("TRIAGE_LOCK", 70, "TRIAGE_LOCK");
        yf yfVar72 = new yf("TRIAGE_MILESTONE_EDIT", 71, "TRIAGE_MILESTONE_EDIT");
        yf yfVar73 = new yf("TRIAGE_PROJECT_EDIT", 72, "TRIAGE_PROJECT_EDIT");
        yf yfVar74 = new yf("TRIAGE_PROJECT_NEXT_EDIT", 73, "TRIAGE_PROJECT_NEXT_EDIT");
        yf yfVar75 = new yf("TRIAGE_PROJECT_NEXT_PICKER_OWNER", 74, "TRIAGE_PROJECT_NEXT_PICKER_OWNER");
        yf yfVar76 = new yf("TRIAGE_PROJECT_NEXT_PICKER_RECENT", 75, "TRIAGE_PROJECT_NEXT_PICKER_RECENT");
        yf yfVar77 = new yf("TRIAGE_REVIEW_REQUEST_EDIT", 76, "TRIAGE_REVIEW_REQUEST_EDIT");
        yf yfVar78 = new yf("TRIAGE_UNSUBSCRIBE", 77, "TRIAGE_UNSUBSCRIBE");
        yf yfVar79 = new yf("VIEWER_DISCUSSIONS_LIST_FILTER", 78, "VIEWER_DISCUSSIONS_LIST_FILTER");
        yf yfVar80 = new yf("VIEWER_ISSUES_LIST_FILTER", 79, "VIEWER_ISSUES_LIST_FILTER");
        yf yfVar81 = new yf("VIEWER_PULL_REQUESTS_LIST_FILTER", 80, "VIEWER_PULL_REQUESTS_LIST_FILTER");
        yf yfVar82 = new yf("VIEWER_PULL_TO_REFRESH", 81, "VIEWER_PULL_TO_REFRESH");
        yf yfVar83 = new yf("UNKNOWN__", 82, "UNKNOWN__");
        s = yfVar83;
        yf[] yfVarArr = {yfVar, yfVar2, yfVar3, yfVar4, yfVar5, yfVar6, yfVar7, yfVar8, yfVar9, yfVar10, yfVar11, yfVar12, yfVar13, yfVar14, yfVar15, yfVar16, yfVar17, yfVar18, yfVar19, yfVar20, yfVar21, yfVar22, yfVar23, yfVar24, yfVar25, yfVar26, yfVar27, yfVar28, yfVar29, yfVar30, yfVar31, yfVar32, yfVar33, yfVar34, yfVar35, yfVar36, yfVar37, yfVar38, yfVar39, yfVar40, yfVar41, yfVar42, yfVar43, yfVar44, yfVar45, yfVar46, yfVar47, yfVar48, yfVar49, yfVar50, yfVar51, yfVar52, yfVar53, yfVar54, yfVar55, yfVar56, yfVar57, yfVar58, yfVar59, yfVar60, yfVar61, yfVar62, yfVar63, yfVar64, yfVar65, yfVar66, yfVar67, yfVar68, yfVar69, yfVar70, yfVar71, yfVar72, yfVar73, yfVar74, yfVar75, yfVar76, yfVar77, yfVar78, yfVar79, yfVar80, yfVar81, yfVar82, yfVar83};
        t = yfVarArr;
        u = v8.l0.t(yfVarArr);
        Companion = new xf();
        sy.d0.o(new String[]{"EXPLORE_BOTTOM_NAVIGATION", "EXPLORE_FEATURED_REPOSITORY", "EXPLORE_FOR_YOU_REPOSITORY", "EXPLORE_STAR_FEATURED_REPOSITORY", "EXPLORE_STAR_FOR_YOU_REPOSITORY", "EXPLORE_STAR_TRENDING_REPOSITORY", "EXPLORE_TRENDING_LIST_FILTER", "EXPLORE_TRENDING_REPOSITORY", "FOLLOW", "HOME_BOTTOM_NAVIGATION", "HOME_CREATE_ISSUE", "HOME_DISCUSSIONS", "HOME_FAVORITE_REPOSITORY_ITEM", "HOME_ISSUES", "HOME_ORGANIZATIONS", "HOME_PROJECTS", "HOME_PULL_REQUESTS", "HOME_RECENT_ACTIVITY_ITEM", "HOME_RELEASE_NOTES", "HOME_REPOSITORIES", "HOME_REPOSITORY_LIST_FILTER", "HOME_SHORTCUTS", "HOME_STARRED", "ISSUES_LIST_ITEM", "ISSUES_SEARCH", "ISSUE_COMPOSER", "NOTIFICATIONS_ONBOARDING_BANNER", "NOTIFICATION_BOTTOM_NAVIGATION", "NOTIFICATION_FILTER", "NOTIFICATION_LIST_FILTER", "NOTIFICATION_LIST_ITEM", "NOTIFICATION_LIST_ITEM_UNDO", "NOTIFICATION_PUSH", "ONBOARDING_BANNER", "PROFILE_BOTTOM_NAVIGATION", "PROFILE_REPOSITORY_LIST_FILTER", "PROJECTS_LIST_ITEM", "PROJECTS_QUICK_ACTION_CLOSE", "PROJECTS_QUICK_ACTION_DELETE", "PROJECTS_QUICK_ACTION_EDIT_FIELD", "PROJECTS_QUICK_ACTION_EDIT_TITLE", "PROJECTS_QUICK_ACTION_OPEN_DETAILS", "PROJECTS_QUICK_ACTION_OTHER_PROJECTS", "PROJECTS_QUICK_ACTION_REOPEN", "PROJECTS_TABLE_VIEW_LIST_ITEM", "PROJECT_VIEW", "PROJECT_VIEW_TIMEOUT_CTA", "PULL_REQUESTS_LIST_ITEM", "PULL_REQUESTS_SEARCH", "RELEASES_LIST_LATEST_RELEASE", "RELEASE_DOWNLOAD_ASSET", "RELEASE_LINKED_DISCUSSION", "REPOSITORY_DISCUSSIONS_LIST_FILTER", "REPOSITORY_ISSUES_LIST_FILTER", "REPOSITORY_LATEST_RELEASE", "REPOSITORY_PULL_REQUESTS_LIST_FILTER", "SETTINGS_DISABLE_ANALYTICS", "SHORTCUTS_LIST_ITEM", "SHORTCUT_SUGGESTIONS_LIST_ITEM", "SHOW_MORE_ROLLUP", "STAR_REPOSITORY", "TRIAGE_ASSIGNEE_EDIT", "TRIAGE_CLOSE", "TRIAGE_COMMENT", "TRIAGE_COMMENT_DOWN", "TRIAGE_COMMENT_EDIT", "TRIAGE_COMMENT_UP", "TRIAGE_EXPAND", "TRIAGE_LABEL_EDIT", "TRIAGE_LINKED_ITEM_EDIT", "TRIAGE_LOCK", "TRIAGE_MILESTONE_EDIT", "TRIAGE_PROJECT_EDIT", "TRIAGE_PROJECT_NEXT_EDIT", "TRIAGE_PROJECT_NEXT_PICKER_OWNER", "TRIAGE_PROJECT_NEXT_PICKER_RECENT", "TRIAGE_REVIEW_REQUEST_EDIT", "TRIAGE_UNSUBSCRIBE", "VIEWER_DISCUSSIONS_LIST_FILTER", "VIEWER_ISSUES_LIST_FILTER", "VIEWER_PULL_REQUESTS_LIST_FILTER", "VIEWER_PULL_TO_REFRESH"});
    }

    public yf(String str, int i, String str2) {
        this.r = str2;
    }

    public static yf valueOf(String str) {
        return (yf) Enum.valueOf(yf.class, str);
    }

    public static yf[] values() {
        return (yf[]) t.clone();
    }
}
