package fl0;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import gn0.d4;
import gn0.ds;
import gn0.fs;
import gn0.l2;
import gn0.lb;
import gn0.ll;
import gn0.mx;
import gn0.n0;
import gn0.n2;
import gn0.pb;
import gn0.qv;
import gn0.r6;
import gn0.rb;
import gn0.rn;
import gn0.sv;
import gn0.tb;
import gn0.tl;
import gn0.u10;
import gn0.uv;
import gn0.wv;
import gn0.x2;
import gn0.xl;
import gn0.y10;
import gn0.yh;
import gn0.yv;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class d {
    public static final List a;

    static {
        pb.Companion.getClass();
        x xVar = pb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar2 = tb.a;
        m mVar2 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        yv.Companion.getClass();
        a0 a0Var = yv.s;
        List r = l.r(new m[]{mVar, mVar2, new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar), new m("description", xVar2, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        rb.Companion.getClass();
        x xVar3 = rb.a;
        m mVar3 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ds.Companion.getClass();
        List r2 = l.r(new m[]{mVar3, new m("nodes", l0.a(ds.a), (String) null, rVar, rVar, r)});
        m mVar4 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar5 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar6 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        x xVar4 = mx.a;
        k.g(xVar4, "type");
        m mVar7 = new m("avatarUrl", xVar4, (String) null, rVar, rVar, rVar);
        m mVar8 = new m("description", xVar2, (String) null, rVar, rVar, rVar);
        m mVar9 = new m("targetUrl", xVar4, (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar5 = lb.a;
        r b2 = l0.b(xVar5);
        wv.Companion.getClass();
        List r3 = l.r(new m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new m("isRequired", b2, (String) null, rVar, no.a.s(wv.b, new u0(new t("prNumber"))), rVar)});
        List r4 = l.r(new m[]{new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        u10.Companion.getClass();
        List r5 = l.r(new m[]{new m("workflow", l0.b(u10.c), (String) null, rVar, rVar, r4), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("logoUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        y10.Companion.getClass();
        q0 q0Var = y10.b;
        k.g(q0Var, "type");
        m mVar10 = new m("workflowRun", q0Var, (String) null, rVar, rVar, r5);
        n0.Companion.getClass();
        q0 q0Var2 = n0.a;
        k.g(q0Var2, "type");
        List r7 = l.r(new m[]{mVar10, new m("app", q0Var2, (String) null, rVar, rVar, r6), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar11 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        l2.Companion.getClass();
        a0 a0Var2 = l2.s;
        k.g(a0Var2, "type");
        m mVar12 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        m mVar13 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar14 = new m("duration", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m mVar15 = new m("summary", xVar2, (String) null, rVar, rVar, rVar);
        m mVar16 = new m("permalink", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        x2.Companion.getClass();
        m mVar17 = new m("checkSuite", l0.b(x2.f), (String) null, rVar, rVar, r7);
        r b3 = l0.b(xVar5);
        n2.Companion.getClass();
        List r8 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("StatusContext", d0.n("StatusContext"), r3), new n("CheckRun", d0.n("CheckRun"), l.r(new m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new m("isRequired", b3, (String) null, rVar, no.a.s(n2.b, new u0(new t("prNumber"))), rVar)}))});
        m mVar18 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        sv.Companion.getClass();
        List r9 = l.r(new m[]{mVar18, new m("nodes", l0.a(sv.a), (String) null, rVar, rVar, r8)});
        m mVar19 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        uv.Companion.getClass();
        r b4 = l0.b(uv.a);
        qv.Companion.getClass();
        List r10 = l.r(new m[]{mVar19, mVar20, new m("contexts", b4, (String) null, rVar, no.a.s(qv.b, new u0(100)), r9), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar21 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        r6.Companion.getClass();
        m mVar22 = new m("committedDate", l0.b(r6.a), (String) null, rVar, rVar, rVar);
        q0 q0Var3 = qv.c;
        k.g(q0Var3, "type");
        List r12 = l.r(new m[]{mVar21, mVar22, new m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r10), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar23 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        d4.Companion.getClass();
        List r13 = l.r(new m[]{mVar23, new m("commit", l0.b(d4.j), (String) null, rVar, rVar, r12), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar24 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar25 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        tl.Companion.getClass();
        List r14 = l.r(new m[]{mVar24, mVar25, new m("nodes", l0.a(tl.a), (String) null, rVar, rVar, r13)});
        m mVar26 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        fs.Companion.getClass();
        r b5 = l0.b(fs.a);
        ll.Companion.getClass();
        m mVar27 = new m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(ll.v, new u0(25)), r2);
        m mVar28 = new m("actionRequiredWorkflowRunCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        xl.Companion.getClass();
        List r15 = l.r(new s[]{new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar), new n("PullRequest", d0.n("PullRequest"), l.r(new m[]{mVar26, mVar27, mVar28, new m("commits", l0.b(xl.a), (String) null, rVar, no.a.s(ll.l, new u0(1)), r14)})), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yh.Companion.getClass();
        j0 j0Var = yh.a;
        k.g(j0Var, "type");
        rn.Companion.getClass();
        a = d0.n(new m("node", j0Var, (String) null, rVar, no.a.s(rn.i, new u0(new t("id"))), r15));
    }
}
