package yz0;

import com.github.service.models.response.IssueOrPullRequestState;
import com.github.service.models.response.issueorpullrequest.CloseReason;
import com.github.service.models.response.issueorpullrequest.IssueType;
import com.github.service.models.response.type.PullRequestReviewDecision;
import com.github.service.models.response.type.SubscriptionState;
import java.util.ArrayList;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public final class i2 {
    public final Object A;
    public final boolean B;
    public final boolean C;
    public final String D;
    public final boolean E;
    public final boolean F;
    public final int G;
    public final int H;
    public final boolean I;
    public final boolean J;
    public final Object K;
    public final boolean L;
    public final boolean M;
    public final boolean N;
    public final String O;
    public final boolean P;
    public final String Q;
    public final String R;
    public final boolean S;
    public final boolean T;
    public final a2 U;
    public final z1 V;
    public final String W;
    public final c2 X;
    public final Object Y;
    public final Object Z;
    public final String a;
    public final boolean a0;
    public final String b;
    public final PullRequestReviewDecision b0;
    public final String c;
    public final h01.h c0;
    public final com.github.service.models.response.a d;
    public final h01.c d0;
    public final String e;
    public final int e0;
    public final boolean f;
    public final boolean f0;
    public final boolean g;
    public final boolean g0;
    public final String h;
    public final boolean h0;
    public final boolean i;
    public final String i0;
    public final SubscriptionState j;
    public final String j0;
    public final SubscriptionState k;
    public final boolean k0;
    public final String l;
    public final boolean l0;
    public final String m;
    public final boolean m0;
    public final int n;
    public final List n0;
    public final boolean o;
    public final CloseReason o0;
    public final IssueOrPullRequestState p;
    public final boolean p0;
    public final com.github.service.models.response.a q;
    public final IssueType q0;
    public final boolean r;
    public final boolean r0;
    public final s s;
    public final h01.j s0;
    public final ArrayList t;
    public final z01.p t0;
    public final boolean u;
    public final boolean u0;
    public final h01.q v;
    public final v2 w;
    public final Object x;
    public final Object y;
    public final Object z;

    public i2(String str, String str2, String str3, com.github.service.models.response.a aVar, String str4, boolean z, boolean z2, String str5, boolean z3, SubscriptionState subscriptionState, SubscriptionState subscriptionState2, String str6, String str7, int i, boolean z4, IssueOrPullRequestState issueOrPullRequestState, com.github.service.models.response.a aVar2, boolean z5, s sVar, ArrayList arrayList, boolean z6, h01.q qVar, v2 v2Var, List list, List list2, List list3, List list4, boolean z7, boolean z8, String str8, boolean z9, boolean z10, int i2, int i3, boolean z12, boolean z13, List list5, boolean z14, boolean z15, boolean z16, String str9, boolean z17, String str10, String str11, boolean z18, boolean z19, a2 a2Var, z1 z1Var, String str12, c2 c2Var, List list6, List list7, boolean z20, PullRequestReviewDecision pullRequestReviewDecision, h01.h hVar, h01.c cVar, int i4, boolean z22, boolean z23, boolean z24, String str13, String str14, boolean z25, boolean z26, boolean z27, List list8, CloseReason closeReason, boolean z28, IssueType issueType, boolean z29, h01.j jVar, z01.p pVar, boolean z30) {
        k71.k.g(str, "currentViewerLogin");
        k71.k.g(str2, "repoId");
        k71.k.g(str3, "repoName");
        k71.k.g(str4, "ownerId");
        k71.k.g(str5, "id");
        k71.k.g(str6, "title");
        k71.k.g(str7, "titleHTML");
        k71.k.g(issueOrPullRequestState, "state");
        k71.k.g(qVar, "timeline");
        k71.k.g(str8, "url");
        k71.k.g(pullRequestReviewDecision, "reviewDecision");
        k71.k.g(list8, "viewerMergeActions");
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = aVar;
        this.e = str4;
        this.f = z;
        this.g = z2;
        this.h = str5;
        this.i = z3;
        this.j = subscriptionState;
        this.k = subscriptionState2;
        this.l = str6;
        this.m = str7;
        this.n = i;
        this.o = z4;
        this.p = issueOrPullRequestState;
        this.q = aVar2;
        this.r = z5;
        this.s = sVar;
        this.t = arrayList;
        this.u = z6;
        this.v = qVar;
        this.w = v2Var;
        this.x = list;
        this.y = list2;
        this.z = list3;
        this.A = list4;
        this.B = z7;
        this.C = z8;
        this.D = str8;
        this.E = z9;
        this.F = z10;
        this.G = i2;
        this.H = i3;
        this.I = z12;
        this.J = z13;
        this.K = list5;
        this.L = z14;
        this.M = z15;
        this.N = z16;
        this.O = str9;
        this.P = z17;
        this.Q = str10;
        this.R = str11;
        this.S = z18;
        this.T = z19;
        this.U = a2Var;
        this.V = z1Var;
        this.W = str12;
        this.X = c2Var;
        this.Y = list6;
        this.Z = list7;
        this.a0 = z20;
        this.b0 = pullRequestReviewDecision;
        this.c0 = hVar;
        this.d0 = cVar;
        this.e0 = i4;
        this.f0 = z22;
        this.g0 = z23;
        this.h0 = z24;
        this.i0 = str13;
        this.j0 = str14;
        this.k0 = z25;
        this.l0 = z26;
        this.m0 = z27;
        this.n0 = list8;
        this.o0 = closeReason;
        this.p0 = z28;
        this.q0 = issueType;
        this.r0 = z29;
        this.s0 = jVar;
        this.t0 = pVar;
        this.u0 = z30;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof i2)) {
            return false;
        }
        i2 i2Var = (i2) obj;
        return k71.k.b(this.a, i2Var.a) && k71.k.b(this.b, i2Var.b) && k71.k.b(this.c, i2Var.c) && this.d.equals(i2Var.d) && k71.k.b(this.e, i2Var.e) && this.f == i2Var.f && this.g == i2Var.g && k71.k.b(this.h, i2Var.h) && this.i == i2Var.i && this.j == i2Var.j && this.k == i2Var.k && k71.k.b(this.l, i2Var.l) && k71.k.b(this.m, i2Var.m) && this.n == i2Var.n && this.o == i2Var.o && this.p == i2Var.p && this.q.equals(i2Var.q) && this.r == i2Var.r && this.s.equals(i2Var.s) && this.t.equals(i2Var.t) && this.u == i2Var.u && k71.k.b(this.v, i2Var.v) && k71.k.b(this.w, i2Var.w) && this.x.equals(i2Var.x) && this.y.equals(i2Var.y) && this.z.equals(i2Var.z) && this.A.equals(i2Var.A) && this.B == i2Var.B && this.C == i2Var.C && k71.k.b(this.D, i2Var.D) && this.E == i2Var.E && this.F == i2Var.F && this.G == i2Var.G && this.H == i2Var.H && this.I == i2Var.I && this.J == i2Var.J && this.K.equals(i2Var.K) && this.L == i2Var.L && this.M == i2Var.M && this.N == i2Var.N && k71.k.b(this.O, i2Var.O) && this.P == i2Var.P && k71.k.b(this.Q, i2Var.Q) && k71.k.b(this.R, i2Var.R) && this.S == i2Var.S && this.T == i2Var.T && k71.k.b(this.U, i2Var.U) && k71.k.b(this.V, i2Var.V) && k71.k.b(this.W, i2Var.W) && k71.k.b(this.X, i2Var.X) && this.Y.equals(i2Var.Y) && this.Z.equals(i2Var.Z) && this.a0 == i2Var.a0 && this.b0 == i2Var.b0 && k71.k.b(this.c0, i2Var.c0) && k71.k.b(this.d0, i2Var.d0) && this.e0 == i2Var.e0 && this.f0 == i2Var.f0 && this.g0 == i2Var.g0 && this.h0 == i2Var.h0 && k71.k.b(this.i0, i2Var.i0) && k71.k.b(this.j0, i2Var.j0) && this.k0 == i2Var.k0 && this.l0 == i2Var.l0 && this.m0 == i2Var.m0 && this.n0.equals(i2Var.n0) && this.o0 == i2Var.o0 && this.p0 == i2Var.p0 && k71.k.b(this.q0, i2Var.q0) && this.r0 == i2Var.r0 && k71.k.b(this.s0, i2Var.s0) && k71.k.b(this.t0, i2Var.t0) && this.u0 == i2Var.u0;
    }

    public final int hashCode() {
        int e = x.i.e(com.github.rudroid.copilot.h1.i(x.i.e(x.i.e(com.github.rudroid.copilot.h1.i(jo.f4.b(this.d, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(this.a.hashCode() * 31, this.b, 31), this.c, 31), 31), this.e, 31), 31, this.f), 31, this.g), this.h, 31), 31, this.i);
        SubscriptionState subscriptionState = this.j;
        int hashCode = (e + (subscriptionState == null ? 0 : subscriptionState.hashCode())) * 31;
        SubscriptionState subscriptionState2 = this.k;
        int hashCode2 = (this.v.hashCode() + x.i.e(no.a.b(this.t, (this.s.hashCode() + x.i.e(jo.f4.b(this.q, (this.p.hashCode() + x.i.e(a0.s0.b(this.n, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i((hashCode + (subscriptionState2 == null ? 0 : subscriptionState2.hashCode())) * 31, this.l, 31), this.m, 31), 31), 31, this.o)) * 31, 31), 31, this.r)) * 31, 31), 31, this.u)) * 31;
        v2 v2Var = this.w;
        int e2 = x.i.e(x.i.e(x.i.e(com.github.rudroid.copilot.h1.h(x.i.e(x.i.e(a0.s0.b(this.H, a0.s0.b(this.G, x.i.e(x.i.e(com.github.rudroid.copilot.h1.i(x.i.e(x.i.e(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h((hashCode2 + (v2Var == null ? 0 : v2Var.hashCode())) * 31, this.x, 31), this.y, 31), this.z, 31), this.A, 31), 31, this.B), 31, this.C), this.D, 31), 31, this.E), 31, this.F), 31), 31), 31, this.I), 31, this.J), this.K, 31), 31, this.L), 31, this.M), 31, this.N);
        String str = this.O;
        int e3 = x.i.e((e2 + (str == null ? 0 : str.hashCode())) * 31, 31, this.P);
        String str2 = this.Q;
        int hashCode3 = (e3 + (str2 == null ? 0 : str2.hashCode())) * 31;
        String str3 = this.R;
        int e4 = x.i.e(x.i.e((hashCode3 + (str3 == null ? 0 : str3.hashCode())) * 31, 31, this.S), 31, this.T);
        a2 a2Var = this.U;
        int hashCode4 = (e4 + (a2Var == null ? 0 : a2Var.hashCode())) * 31;
        z1 z1Var = this.V;
        int hashCode5 = (hashCode4 + (z1Var == null ? 0 : z1Var.hashCode())) * 31;
        String str4 = this.W;
        int hashCode6 = (hashCode5 + (str4 == null ? 0 : str4.hashCode())) * 31;
        c2 c2Var = this.X;
        int hashCode7 = (this.b0.hashCode() + x.i.e(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h((hashCode6 + (c2Var == null ? 0 : c2Var.hashCode())) * 31, this.Y, 31), this.Z, 31), 31, this.a0)) * 31;
        h01.h hVar = this.c0;
        int hashCode8 = (hashCode7 + (hVar == null ? 0 : hVar.hashCode())) * 31;
        h01.c cVar = this.d0;
        int e5 = x.i.e(x.i.e(x.i.e(a0.s0.b(this.e0, (hashCode8 + (cVar == null ? 0 : cVar.hashCode())) * 31, 31), 31, this.f0), 31, this.g0), 31, this.h0);
        String str5 = this.i0;
        int hashCode9 = (e5 + (str5 == null ? 0 : str5.hashCode())) * 31;
        String str6 = this.j0;
        int c = f1.e.c(this.n0, x.i.e(x.i.e(x.i.e((hashCode9 + (str6 == null ? 0 : str6.hashCode())) * 31, 31, this.k0), 31, this.l0), 31, this.m0), 961);
        CloseReason closeReason = this.o0;
        int e6 = x.i.e((c + (closeReason == null ? 0 : closeReason.hashCode())) * 31, 31, this.p0);
        IssueType issueType = this.q0;
        int e7 = x.i.e((e6 + (issueType == null ? 0 : issueType.hashCode())) * 31, 31, this.r0);
        h01.j jVar = this.s0;
        int hashCode10 = (e7 + (jVar == null ? 0 : jVar.hashCode())) * 31;
        z01.p pVar = this.t0;
        return Boolean.hashCode(this.u0) + ((hashCode10 + (pVar != null ? pVar.hashCode() : 0)) * 31);
    }

    public final String toString() {
        StringBuilder o = a0.s0.o("IssueOrPullRequest(currentViewerLogin=", this.a, ", repoId=", this.b, ", repoName=");
        o.append(this.c);
        o.append(", owner=");
        o.append(this.d);
        o.append(", ownerId=");
        com.github.rudroid.m0.x(o, this.e, ", ownerIsOrg=", this.f, ", canManage=");
        com.github.rudroid.m0.z(o, this.g, ", id=", this.h, ", isSubscribed=");
        o.append(this.i);
        o.append(", subscribeActionState=");
        o.append(this.j);
        o.append(", unsubscribeActionState=");
        o.append(this.k);
        o.append(", title=");
        o.append(this.l);
        o.append(", titleHTML=");
        a0.s0.w(this.n, this.m, ", number=", ", locked=", o);
        o.append(this.o);
        o.append(", state=");
        o.append(this.p);
        o.append(", author=");
        o.append(this.q);
        o.append(", isReadByViewer=");
        o.append(this.r);
        o.append(", comment=");
        o.append(this.s);
        o.append(", reactions=");
        o.append(this.t);
        o.append(", viewerCanReact=");
        o.append(this.u);
        o.append(", timeline=");
        o.append(this.v);
        o.append(", milestone=");
        o.append(this.w);
        o.append(", assignees=");
        o.append(this.x);
        o.append(", labels=");
        o.append(this.y);
        o.append(", projects=");
        o.append(this.z);
        o.append(", projectItems=");
        o.append(this.A);
        o.append(", viewerCanDeleteHeadRef=");
        o.append(this.B);
        o.append(", viewerIsAuthor=");
        com.github.rudroid.m0.z(o, this.C, ", url=", this.D, ", viewerCanUpdate=");
        com.github.rudroid.m0.A(o, this.E, ", viewerHasWritePermission=", this.F, ", completeTaskListItemCount=");
        a0.s0.z(o, this.G, ", incompleteTaskListItemCount=", this.H, ", viewerCanBlockFromOrg=");
        com.github.rudroid.m0.A(o, this.I, ", viewerCanUnblockFromOrg=", this.J, ", linkedIssueOrPullRequests=");
        o.append(this.K);
        o.append(", viewerCanReopen=");
        o.append(this.L);
        o.append(", viewerCanAssign=");
        com.github.rudroid.m0.A(o, this.M, ", viewerCanLabel=", this.N, ", defaultRepoBranch=");
        com.github.rudroid.m0.x(o, this.O, ", hasAssignableCodingAgents=", this.P, ", baseRepoNameAndOwner=");
        f1.e.x(o, this.Q, ", headRepoNameAndOwner=", this.R, ", canApproveWorkflow=");
        com.github.rudroid.m0.A(o, this.S, ", isDraft=", this.T, ", filesChangedOverview=");
        o.append(this.U);
        o.append(", commitsOverview=");
        o.append(this.V);
        o.append(", refId=");
        o.append(this.W);
        o.append(", refNames=");
        o.append(this.X);
        o.append(", reviewers=");
        o.append(this.Y);
        o.append(", suggestedReviewers=");
        o.append(this.Z);
        o.append(", isPullRequest=");
        o.append(this.a0);
        o.append(", reviewDecision=");
        o.append(this.b0);
        o.append(", mergeOverview=");
        o.append(this.c0);
        o.append(", checksOverview=");
        o.append(this.d0);
        o.append(", reviewerProgress=");
        com.github.rudroid.m0.w(o, this.e0, ", viewerCanDismissReviews=", this.f0, ", repoCanReviewRequestTeams=");
        com.github.rudroid.m0.A(o, this.g0, ", canMerge=", this.h0, ", lastCommitId=");
        f1.e.x(o, this.i0, ", headRefOid=", this.j0, ", allowUpdateBranch=");
        com.github.rudroid.m0.A(o, this.k0, ", viewerCanChangeBaseBranch=", this.l0, ", viewerCanUpdateBranch=");
        o.append(this.m0);
        o.append(", viewerMergeActions=");
        o.append(this.n0);
        o.append(", mergeRequirements=null, closeReason=");
        o.append(this.o0);
        o.append(", isPinned=");
        o.append(this.p0);
        o.append(", issueType=");
        o.append(this.q0);
        o.append(", areIssueTypesAvailable=");
        o.append(this.r0);
        o.append(", parentIssueData=");
        o.append(this.s0);
        o.append(", duplicateOf=");
        o.append(this.t0);
        o.append(", copilotSuggestedAsAssignee=");
        return jo.f4.s(o, this.u0, ")");
    }
}
