package yz0;

import com.github.service.models.response.IssueOrPullRequestState;
import com.github.service.models.response.issueorpullrequest.CloseReason;
import com.github.service.models.response.issueorpullrequest.IssueType;
import com.github.service.models.response.type.PullRequestReviewDecision;
import com.github.service.models.response.type.SubscriptionState;
import java.util.ArrayList;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public final class j2 {
    public final boolean A;
    public final boolean B;
    public final String C;
    public final boolean D;
    public final boolean E;
    public final int F;
    public final int G;
    public final boolean H;
    public final boolean I;
    public final Object J;
    public final boolean K;
    public final boolean L;
    public final boolean M;
    public final String N;
    public final boolean O;
    public final String P;
    public final String Q;
    public final boolean R;
    public final boolean S;
    public final a2 T;
    public final z1 U;
    public final String V;
    public final c2 W;
    public final Object X;
    public final Object Y;
    public final boolean Z;
    public final String a;
    public final PullRequestReviewDecision a0;
    public final String b;
    public final h01.h b0;
    public final String c;
    public final h01.c c0;
    public final com.github.service.models.response.a d;
    public final int d0;
    public final String e;
    public final boolean e0;
    public final boolean f;
    public final boolean f0;
    public final boolean g;
    public final boolean g0;
    public final String h;
    public final String h0;
    public final boolean i;
    public final String i0;
    public final SubscriptionState j;
    public final boolean j0;
    public final SubscriptionState k;
    public final boolean k0;
    public final String l;
    public final boolean l0;
    public final String m;
    public final CloseReason m0;
    public final int n;
    public final boolean n0;
    public final boolean o;
    public final IssueType o0;
    public final IssueOrPullRequestState p;
    public final boolean p0;
    public final com.github.service.models.response.a q;
    public final h01.j q0;
    public final boolean r;
    public final z01.p r0;
    public final s s;
    public final boolean s0;
    public final ArrayList t;
    public final boolean u;
    public final v2 v;
    public final Object w;
    public final Object x;
    public final Object y;
    public final Object z;

    public j2(String str, String str2, String str3, com.github.service.models.response.a aVar, String str4, boolean z, boolean z2, String str5, boolean z3, SubscriptionState subscriptionState, SubscriptionState subscriptionState2, String str6, String str7, int i, boolean z4, IssueOrPullRequestState issueOrPullRequestState, com.github.service.models.response.a aVar2, boolean z5, s sVar, ArrayList arrayList, boolean z6, v2 v2Var, List list, List list2, List list3, List list4, boolean z7, boolean z8, String str8, boolean z9, boolean z10, int i2, int i3, boolean z12, boolean z13, List list5, boolean z14, boolean z15, boolean z16, String str9, boolean z17, String str10, String str11, boolean z18, boolean z19, a2 a2Var, z1 z1Var, String str12, c2 c2Var, List list6, List list7, boolean z20, PullRequestReviewDecision pullRequestReviewDecision, h01.h hVar, h01.c cVar, int i4, boolean z22, boolean z23, boolean z24, String str13, String str14, boolean z25, boolean z26, boolean z27, CloseReason closeReason, boolean z28, IssueType issueType, boolean z29, h01.j jVar, z01.p pVar, boolean z30, int i5) {
        boolean z32 = (i5 & 256) != 0 ? false : z17;
        k71.k.g(str, "currentViewerLogin");
        k71.k.g(str2, "repoId");
        k71.k.g(str3, "repoName");
        k71.k.g(str4, "ownerId");
        k71.k.g(str5, "id");
        k71.k.g(str6, "title");
        k71.k.g(str7, "titleHTML");
        k71.k.g(issueOrPullRequestState, "state");
        k71.k.g(str8, "url");
        k71.k.g(pullRequestReviewDecision, "reviewDecision");
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = aVar;
        this.e = str4;
        this.f = z;
        this.g = z2;
        this.h = str5;
        this.i = z3;
        this.j = subscriptionState;
        this.k = subscriptionState2;
        this.l = str6;
        this.m = str7;
        this.n = i;
        this.o = z4;
        this.p = issueOrPullRequestState;
        this.q = aVar2;
        this.r = z5;
        this.s = sVar;
        this.t = arrayList;
        this.u = z6;
        this.v = v2Var;
        this.w = list;
        this.x = list2;
        this.y = list3;
        this.z = list4;
        this.A = z7;
        this.B = z8;
        this.C = str8;
        this.D = z9;
        this.E = z10;
        this.F = i2;
        this.G = i3;
        this.H = z12;
        this.I = z13;
        this.J = list5;
        this.K = z14;
        this.L = z15;
        this.M = z16;
        this.N = str9;
        this.O = z32;
        this.P = str10;
        this.Q = str11;
        this.R = z18;
        this.S = z19;
        this.T = a2Var;
        this.U = z1Var;
        this.V = str12;
        this.W = c2Var;
        this.X = list6;
        this.Y = list7;
        this.Z = z20;
        this.a0 = pullRequestReviewDecision;
        this.b0 = hVar;
        this.c0 = cVar;
        this.d0 = i4;
        this.e0 = z22;
        this.f0 = z23;
        this.g0 = z24;
        this.h0 = str13;
        this.i0 = str14;
        this.j0 = z25;
        this.k0 = z26;
        this.l0 = z27;
        this.m0 = closeReason;
        this.n0 = z28;
        this.o0 = issueType;
        this.p0 = z29;
        this.q0 = jVar;
        this.r0 = pVar;
        this.s0 = z30;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof j2)) {
            return false;
        }
        j2 j2Var = (j2) obj;
        return k71.k.b(this.a, j2Var.a) && k71.k.b(this.b, j2Var.b) && k71.k.b(this.c, j2Var.c) && this.d.equals(j2Var.d) && k71.k.b(this.e, j2Var.e) && this.f == j2Var.f && this.g == j2Var.g && k71.k.b(this.h, j2Var.h) && this.i == j2Var.i && this.j == j2Var.j && this.k == j2Var.k && k71.k.b(this.l, j2Var.l) && k71.k.b(this.m, j2Var.m) && this.n == j2Var.n && this.o == j2Var.o && this.p == j2Var.p && this.q.equals(j2Var.q) && this.r == j2Var.r && this.s.equals(j2Var.s) && this.t.equals(j2Var.t) && this.u == j2Var.u && k71.k.b(this.v, j2Var.v) && this.w.equals(j2Var.w) && this.x.equals(j2Var.x) && this.y.equals(j2Var.y) && this.z.equals(j2Var.z) && this.A == j2Var.A && this.B == j2Var.B && k71.k.b(this.C, j2Var.C) && this.D == j2Var.D && this.E == j2Var.E && this.F == j2Var.F && this.G == j2Var.G && this.H == j2Var.H && this.I == j2Var.I && this.J.equals(j2Var.J) && this.K == j2Var.K && this.L == j2Var.L && this.M == j2Var.M && k71.k.b(this.N, j2Var.N) && this.O == j2Var.O && k71.k.b(this.P, j2Var.P) && k71.k.b(this.Q, j2Var.Q) && this.R == j2Var.R && this.S == j2Var.S && k71.k.b(this.T, j2Var.T) && k71.k.b(this.U, j2Var.U) && k71.k.b(this.V, j2Var.V) && k71.k.b(this.W, j2Var.W) && this.X.equals(j2Var.X) && this.Y.equals(j2Var.Y) && this.Z == j2Var.Z && this.a0 == j2Var.a0 && k71.k.b(this.b0, j2Var.b0) && k71.k.b(this.c0, j2Var.c0) && this.d0 == j2Var.d0 && this.e0 == j2Var.e0 && this.f0 == j2Var.f0 && this.g0 == j2Var.g0 && k71.k.b(this.h0, j2Var.h0) && k71.k.b(this.i0, j2Var.i0) && this.j0 == j2Var.j0 && this.k0 == j2Var.k0 && this.l0 == j2Var.l0 && this.m0 == j2Var.m0 && this.n0 == j2Var.n0 && k71.k.b(this.o0, j2Var.o0) && this.p0 == j2Var.p0 && k71.k.b(this.q0, j2Var.q0) && k71.k.b(this.r0, j2Var.r0) && this.s0 == j2Var.s0;
    }

    public final int hashCode() {
        int e = x.i.e(com.github.rudroid.copilot.h1.i(x.i.e(x.i.e(com.github.rudroid.copilot.h1.i(jo.f4.b(this.d, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(this.a.hashCode() * 31, this.b, 31), this.c, 31), 31), this.e, 31), 31, this.f), 31, this.g), this.h, 31), 31, this.i);
        SubscriptionState subscriptionState = this.j;
        int hashCode = (e + (subscriptionState == null ? 0 : subscriptionState.hashCode())) * 31;
        SubscriptionState subscriptionState2 = this.k;
        int e2 = x.i.e(no.a.b(this.t, (this.s.hashCode() + x.i.e(jo.f4.b(this.q, (this.p.hashCode() + x.i.e(a0.s0.b(this.n, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i((hashCode + (subscriptionState2 == null ? 0 : subscriptionState2.hashCode())) * 31, this.l, 31), this.m, 31), 31), 31, this.o)) * 31, 31), 31, this.r)) * 31, 31), 31, this.u);
        v2 v2Var = this.v;
        int e3 = x.i.e(x.i.e(x.i.e(com.github.rudroid.copilot.h1.h(x.i.e(x.i.e(a0.s0.b(this.G, a0.s0.b(this.F, x.i.e(x.i.e(com.github.rudroid.copilot.h1.i(x.i.e(x.i.e(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h((e2 + (v2Var == null ? 0 : v2Var.hashCode())) * 31, this.w, 31), this.x, 31), this.y, 31), this.z, 31), 31, this.A), 31, this.B), this.C, 31), 31, this.D), 31, this.E), 31), 31), 31, this.H), 31, this.I), this.J, 31), 31, this.K), 31, this.L), 31, this.M);
        String str = this.N;
        int e4 = x.i.e((e3 + (str == null ? 0 : str.hashCode())) * 31, 31, this.O);
        String str2 = this.P;
        int hashCode2 = (e4 + (str2 == null ? 0 : str2.hashCode())) * 31;
        String str3 = this.Q;
        int e5 = x.i.e(x.i.e((hashCode2 + (str3 == null ? 0 : str3.hashCode())) * 31, 31, this.R), 31, this.S);
        a2 a2Var = this.T;
        int hashCode3 = (e5 + (a2Var == null ? 0 : a2Var.hashCode())) * 31;
        z1 z1Var = this.U;
        int hashCode4 = (hashCode3 + (z1Var == null ? 0 : z1Var.hashCode())) * 31;
        String str4 = this.V;
        int hashCode5 = (hashCode4 + (str4 == null ? 0 : str4.hashCode())) * 31;
        c2 c2Var = this.W;
        int hashCode6 = (this.a0.hashCode() + x.i.e(com.github.rudroid.copilot.h1.h(com.github.rudroid.copilot.h1.h((hashCode5 + (c2Var == null ? 0 : c2Var.hashCode())) * 31, this.X, 31), this.Y, 31), 31, this.Z)) * 31;
        h01.h hVar = this.b0;
        int hashCode7 = (hashCode6 + (hVar == null ? 0 : hVar.hashCode())) * 31;
        h01.c cVar = this.c0;
        int e6 = x.i.e(x.i.e(x.i.e(a0.s0.b(this.d0, (hashCode7 + (cVar == null ? 0 : cVar.hashCode())) * 31, 31), 31, this.e0), 31, this.f0), 31, this.g0);
        String str5 = this.h0;
        int hashCode8 = (e6 + (str5 == null ? 0 : str5.hashCode())) * 31;
        String str6 = this.i0;
        int e7 = x.i.e(x.i.e(a0.s0.b(0, x.i.e((hashCode8 + (str6 == null ? 0 : str6.hashCode())) * 31, 31, this.j0), 31), 31, this.k0), 31, this.l0);
        CloseReason closeReason = this.m0;
        int e8 = x.i.e((e7 + (closeReason == null ? 0 : closeReason.hashCode())) * 31, 31, this.n0);
        IssueType issueType = this.o0;
        int e9 = x.i.e((e8 + (issueType == null ? 0 : issueType.hashCode())) * 31, 31, this.p0);
        h01.j jVar = this.q0;
        int hashCode9 = (e9 + (jVar == null ? 0 : jVar.hashCode())) * 31;
        z01.p pVar = this.r0;
        return Boolean.hashCode(this.s0) + ((hashCode9 + (pVar != null ? pVar.hashCode() : 0)) * 31);
    }

    public final String toString() {
        StringBuilder o = a0.s0.o("IssueOrPullRequestWithoutTimeline(currentViewerLogin=", this.a, ", repoId=", this.b, ", repoName=");
        o.append(this.c);
        o.append(", owner=");
        o.append(this.d);
        o.append(", ownerId=");
        com.github.rudroid.m0.x(o, this.e, ", ownerIsOrg=", this.f, ", canManage=");
        com.github.rudroid.m0.z(o, this.g, ", id=", this.h, ", isSubscribed=");
        o.append(this.i);
        o.append(", subscribeActionState=");
        o.append(this.j);
        o.append(", unsubscribeActionState=");
        o.append(this.k);
        o.append(", title=");
        o.append(this.l);
        o.append(", titleHTML=");
        a0.s0.w(this.n, this.m, ", number=", ", locked=", o);
        o.append(this.o);
        o.append(", state=");
        o.append(this.p);
        o.append(", author=");
        o.append(this.q);
        o.append(", isReadByViewer=");
        o.append(this.r);
        o.append(", comment=");
        o.append(this.s);
        o.append(", reactions=");
        o.append(this.t);
        o.append(", viewerCanReact=");
        o.append(this.u);
        o.append(", milestone=");
        o.append(this.v);
        o.append(", assignees=");
        o.append(this.w);
        o.append(", labels=");
        o.append(this.x);
        o.append(", projects=");
        o.append(this.y);
        o.append(", projectsItems=");
        o.append(this.z);
        o.append(", viewerCanDeleteHeadRef=");
        com.github.rudroid.m0.A(o, this.A, ", viewerIsAuthor=", this.B, ", url=");
        com.github.rudroid.m0.x(o, this.C, ", viewerCanUpdate=", this.D, ", viewerHasWritePermission=");
        com.github.rudroid.m0.y(o, this.E, ", completeTaskListItemCount=", this.F, ", incompleteTaskListItemCount=");
        com.github.rudroid.m0.w(o, this.G, ", viewerCanBlockFromOrg=", this.H, ", viewerCanUnblockFromOrg=");
        o.append(this.I);
        o.append(", linkedIssueOrPullRequests=");
        o.append(this.J);
        o.append(", viewerCanReopen=");
        com.github.rudroid.m0.A(o, this.K, ", viewerCanAssign=", this.L, ", viewerCanLabel=");
        com.github.rudroid.m0.z(o, this.M, ", defaultRepoBranch=", this.N, ", hasAssignableCodingAgents=");
        com.github.rudroid.m0.z(o, this.O, ", baseRepoNameAndOwner=", this.P, ", headRepoNameAndOwner=");
        com.github.rudroid.m0.x(o, this.Q, ", canApproveWorkflow=", this.R, ", isDraft=");
        o.append(this.S);
        o.append(", filesChangedOverview=");
        o.append(this.T);
        o.append(", commitsOverview=");
        o.append(this.U);
        o.append(", refId=");
        o.append(this.V);
        o.append(", refNames=");
        o.append(this.W);
        o.append(", reviewers=");
        o.append(this.X);
        o.append(", suggestedReviewers=");
        o.append(this.Y);
        o.append(", isPullRequest=");
        o.append(this.Z);
        o.append(", reviewDecision=");
        o.append(this.a0);
        o.append(", mergeOverview=");
        o.append(this.b0);
        o.append(", checksOverview=");
        o.append(this.c0);
        o.append(", reviewerProgress=");
        o.append(this.d0);
        o.append(", viewerCanDismissReviews=");
        com.github.rudroid.m0.A(o, this.e0, ", repoCanReviewRequestTeams=", this.f0, ", canMerge=");
        com.github.rudroid.m0.z(o, this.g0, ", lastCommitId=", this.h0, ", headRefOid=");
        com.github.rudroid.m0.x(o, this.i0, ", allowUpdateBranch=", this.j0, ", pendingReviewComments=0, viewerCanChangeBaseBranch=");
        com.github.rudroid.m0.A(o, this.k0, ", viewerCanUpdateBranch=", this.l0, ", closeReason=");
        o.append(this.m0);
        o.append(", isPinned=");
        o.append(this.n0);
        o.append(", issueType=");
        o.append(this.o0);
        o.append(", areIssueTypesAvailable=");
        o.append(this.p0);
        o.append(", parentIssueData=");
        o.append(this.q0);
        o.append(", duplicateOf=");
        o.append(this.r0);
        o.append(", copilotSuggestedAsAssignee=");
        return jo.f4.s(o, this.s0, ")");
    }
}
