package en0;

import gn0.eq;
import gn0.hr;
import gn0.ll;
import gn0.mx;
import gn0.pb;
import gn0.rb;
import gn0.rn;
import gn0.s00;
import gn0.tb;
import gn0.u10;
import gn0.x7;
import gn0.y10;
import gn0.yh;
import gn0.z7;
import gn0.zl;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class o0 {
    public static final List a;

    static {
        tb.Companion.getClass();
        aa.x xVar = tb.a;
        aa.r b = v8.l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List r = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.a.a;
        List r2 = x61.l.r(new aa.s[]{mVar, no.a.c(list, "selections", "Actor", r, list)});
        hr.Companion.getClass();
        aa.m mVar2 = new aa.m("owner", v8.l0.b(hr.a), (String) null, rVar, rVar, r2);
        aa.m mVar3 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        pb.Companion.getClass();
        aa.x xVar2 = pb.a;
        List r3 = x61.l.r(new aa.m[]{mVar2, mVar3, new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r4 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("Actor", x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = sy.d0.n("DeploymentRequest");
        List list2 = pf0.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar4, no.a.c(list2, "selections", "DeploymentRequest", n, list2)});
        x7.Companion.getClass();
        List n2 = sy.d0.n(new aa.m("nodes", v8.l0.a(x7.c), (String) null, rVar, rVar, r6));
        aa.m mVar5 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        aa.x xVar3 = mx.a;
        aa.m mVar6 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        aa.m mVar7 = new aa.m("runNumber", v8.l0.b(rb.a), (String) null, rVar, rVar, rVar);
        u10.Companion.getClass();
        aa.m mVar8 = new aa.m("workflow", v8.l0.b(u10.c), (String) null, rVar, rVar, r5);
        z7.Companion.getClass();
        aa.r b2 = v8.l0.b(z7.a);
        y10.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, mVar8, new aa.m("pendingDeploymentRequests", b2, (String) null, rVar, no.a.s(y10.a, new aa.u0(new aa.t("numberOfDeploymentRequests"))), n2), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0.n("CheckRun");
        List list3 = pe0.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar9, no.a.c(list3, "selections", "CheckRun", n3, list3), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        gn0.n2.Companion.getClass();
        List n4 = sy.d0.n(new aa.m("nodes", v8.l0.a(gn0.n2.f), (String) null, rVar, rVar, r8));
        aa.s mVar10 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n5 = sy.d0.n("PullRequest");
        List list4 = si0.b.a;
        List r9 = x61.l.r(new aa.s[]{mVar10, no.a.c(list4, "selections", "PullRequest", n5, list4), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        ll.Companion.getClass();
        List n6 = sy.d0.n(new aa.m("nodes", v8.l0.a(ll.K), (String) null, rVar, rVar, r9));
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar12 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        gn0.r2.Companion.getClass();
        aa.m mVar13 = new aa.m("status", v8.l0.b(gn0.r2.s), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        aa.m mVar14 = new aa.m("repository", v8.l0.b(eq.m0), (String) null, rVar, rVar, r3);
        s00.Companion.getClass();
        aa.q0 q0Var = s00.P;
        k71.k.g(q0Var, "type");
        aa.m mVar15 = new aa.m("creator", q0Var, (String) null, rVar, rVar, r4);
        aa.q0 q0Var2 = y10.b;
        k71.k.g(q0Var2, "type");
        aa.m mVar16 = new aa.m("workflowRun", q0Var2, (String) null, rVar, rVar, r7);
        gn0.p2.Companion.getClass();
        aa.q0 q0Var3 = gn0.p2.a;
        k71.k.g(q0Var3, "type");
        gn0.x2.Companion.getClass();
        aa.m mVar17 = new aa.m("checkRuns", q0Var3, (String) null, rVar, no.a.s(gn0.x2.c, new aa.u0(new aa.t("numberOfCheckRuns"))), n4);
        zl.Companion.getClass();
        aa.q0 q0Var4 = zl.a;
        k71.k.g(q0Var4, "type");
        List r10 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("CheckSuite", sy.d0.n("CheckSuite"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("matchingPullRequests", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(gn0.x2.d, new aa.u0(new aa.t("cursor"))), new aa.k(gn0.x2.e, new aa.u0(new aa.t("numberOfPullRequests")))}), n6)})), new aa.m("id", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        yh.Companion.getClass();
        aa.j0 j0Var = yh.a;
        k71.k.g(j0Var, "type");
        rn.Companion.getClass();
        a = sy.d0.n(new aa.m("node", j0Var, (String) null, rVar, no.a.s(rn.i, new aa.u0(new aa.t("nodeId"))), r10));
    }
}
