package en0;

import gn0.ds;
import gn0.fs;
import gn0.jj;
import gn0.lb;
import gn0.ll;
import gn0.mx;
import gn0.pb;
import gn0.qv;
import gn0.rb;
import gn0.rn;
import gn0.sv;
import gn0.tb;
import gn0.tl;
import gn0.u10;
import gn0.uv;
import gn0.wv;
import gn0.xl;
import gn0.y10;
import gn0.yh;
import gn0.yv;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class u {
    public static final List a;

    static {
        pb.Companion.getClass();
        aa.x xVar = pb.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        aa.x xVar2 = tb.a;
        aa.m mVar2 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        yv.Companion.getClass();
        aa.a0 a0Var = yv.s;
        List r = x61.l.r(new aa.m[]{mVar, mVar2, new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar), new aa.m("description", xVar2, (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        rb.Companion.getClass();
        aa.x xVar3 = rb.a;
        aa.m mVar3 = new aa.m("totalCount", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ds.Companion.getClass();
        List r2 = x61.l.r(new aa.m[]{mVar3, new aa.m("nodes", v8.l0.a(ds.a), (String) null, rVar, rVar, r)});
        lb.Companion.getClass();
        aa.x xVar4 = lb.a;
        List r3 = x61.l.r(new aa.m[]{new aa.m("hasNextPage", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        aa.m mVar4 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar5 = new aa.m("context", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar6 = new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        aa.x xVar5 = mx.a;
        k71.k.g(xVar5, "type");
        aa.m mVar7 = new aa.m("avatarUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.m mVar8 = new aa.m("description", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("targetUrl", xVar5, (String) null, rVar, rVar, rVar);
        aa.r b2 = v8.l0.b(xVar4);
        wv.Companion.getClass();
        List r4 = x61.l.r(new aa.m[]{mVar4, mVar5, mVar6, mVar7, mVar8, mVar9, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(wv.a, new aa.u0(new aa.t("id"))), rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        u10.Companion.getClass();
        List r6 = x61.l.r(new aa.m[]{new aa.m("workflow", v8.l0.b(u10.c), (String) null, rVar, rVar, r5), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r7 = x61.l.r(new aa.m[]{new aa.m("logoUrl", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        y10.Companion.getClass();
        aa.q0 q0Var = y10.b;
        k71.k.g(q0Var, "type");
        aa.m mVar10 = new aa.m("workflowRun", q0Var, (String) null, rVar, rVar, r6);
        gn0.n0.Companion.getClass();
        aa.q0 q0Var2 = gn0.n0.a;
        k71.k.g(q0Var2, "type");
        List r8 = x61.l.r(new aa.m[]{mVar10, new aa.m("app", q0Var2, (String) null, rVar, rVar, r7), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        gn0.l2.Companion.getClass();
        aa.a0 a0Var2 = gn0.l2.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar12 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar13 = new aa.m("name", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar14 = new aa.m("summary", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar15 = new aa.m("permalink", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("duration", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        gn0.x2.Companion.getClass();
        aa.m mVar17 = new aa.m("checkSuite", v8.l0.b(gn0.x2.f), (String) null, rVar, rVar, r8);
        aa.r b3 = v8.l0.b(xVar4);
        gn0.n2.Companion.getClass();
        List r9 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", sy.d0Shadow.n("StatusContext"), r4), new aa.n("CheckRun", sy.d0Shadow.n("CheckRun"), x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(gn0.n2.a, new aa.u0(new aa.t("id"))), rVar)}))});
        jj.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", v8.l0.b(jj.a), (String) null, rVar, rVar, r3);
        sv.Companion.getClass();
        List r10 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", v8.l0.a(sv.a), (String) null, rVar, rVar, r9)});
        aa.m mVar19 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        uv.Companion.getClass();
        aa.r b4 = v8.l0.b(uv.a);
        qv.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar19, new aa.m("contexts", b4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(qv.a, new aa.u0(new aa.t("after"))), new aa.k(qv.b, new aa.u0(25))}), r10), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        gn0.r6.Companion.getClass();
        aa.x xVar6 = gn0.r6.a;
        k71.k.g(xVar6, "type");
        aa.m mVar20 = new aa.m("pushedDate", xVar6, (String) null, rVar, rVar, rVar);
        aa.q0 q0Var3 = qv.c;
        k71.k.g(q0Var3, "type");
        List r13 = x61.l.r(new aa.m[]{mVar20, new aa.m("statusCheckRollup", q0Var3, (String) null, rVar, rVar, r12), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        gn0.d4.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{new aa.m("commit", v8.l0.b(gn0.d4.j), (String) null, rVar, rVar, r13), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        tl.Companion.getClass();
        List n = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(tl.a), (String) null, rVar, rVar, r14));
        fs.Companion.getClass();
        aa.r b5 = v8.l0.b(fs.a);
        ll.Companion.getClass();
        aa.m mVar21 = new aa.m("requiredStatusChecks", b5, (String) null, rVar, no.a.s(ll.v, new aa.u0(25)), r2);
        xl.Companion.getClass();
        List r15 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequest", sy.d0Shadow.n("PullRequest"), x61.l.r(new aa.m[]{mVar21, new aa.m("commits", v8.l0.b(xl.a), (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ll.j, new aa.u0((Object) null)), new aa.k(ll.l, new aa.u0(1))}), n)})), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yh.Companion.getClass();
        aa.j0 j0Var = yh.a;
        k71.k.g(j0Var, "type");
        rn.Companion.getClass();
        a = sy.d0Shadow.n(new aa.m("node", j0Var, (String) null, rVar, no.a.s(rn.i, new aa.u0(new aa.t("id"))), r15));
    }
}
