package en0;

import gn0.bm;
import gn0.cg;
import gn0.eq;
import gn0.gg;
import gn0.hb;
import gn0.hn;
import gn0.jn;
import gn0.jr;
import gn0.lb;
import gn0.ll;
import gn0.ln;
import gn0.mo;
import gn0.pb;
import gn0.qo;
import gn0.tb;
import gn0.uz;
import gn0.wh;
import gn0.yf;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class v5 {
    public static final List a;

    static {
        pb.Companion.getClass();
        aa.x xVar = pb.a;
        aa.r b = v8.l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        aa.x xVar2 = lb.a;
        aa.m mVar2 = new aa.m("mergeCommitAllowed", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("squashMergeAllowed", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar4 = new aa.m("rebaseMergeAllowed", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        bm.Companion.getClass();
        aa.m mVar5 = new aa.m("viewerDefaultMergeMethod", v8.l0.b(bm.s), (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        aa.x xVar3 = tb.a;
        k71.k.g(xVar3, "type");
        aa.m mVar6 = new aa.m("viewerDefaultCommitEmail", xVar3, (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("viewerPossibleCommitEmails", v8.l0.a(v8.l0.b(xVar3)), (String) null, rVar, rVar, rVar);
        jr.Companion.getClass();
        aa.a0 a0Var = jr.s;
        k71.k.g(a0Var, "type");
        List r = x61.l.r(new aa.m[]{mVar, mVar2, mVar3, mVar4, mVar5, mVar6, mVar7, new aa.m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        List n = sy.d0.n(new aa.m("viewerCanPush", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar));
        aa.m mVar8 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        qo.Companion.getClass();
        aa.q0 q0Var = qo.a;
        k71.k.g(q0Var, "type");
        List r2 = x61.l.r(new aa.m[]{mVar8, new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, n), new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.s mVar9 = new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        List r3 = x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list = cl0.a.a;
        List r4 = x61.l.r(new aa.s[]{mVar9, no.a.c(list, "selections", "Node", r3, list), new aa.m("login", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.m mVar10 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.m mVar11 = new aa.m("abbreviatedOid", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        gn0.r6.Companion.getClass();
        List r5 = x61.l.r(new aa.m[]{mVar10, mVar11, new aa.m("committedDate", v8.l0.b(gn0.r6.a), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.s mVar12 = new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        List n2 = sy.d0.n("MergeQueueEntry");
        List list2 = jh0.b.a;
        List r6 = x61.l.r(new aa.s[]{mVar12, no.a.c(list2, "selections", "MergeQueueEntry", n2, list2), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar13 = new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0.n("MergeQueue");
        List list3 = jh0.c.a;
        List r7 = x61.l.r(new aa.s[]{mVar13, no.a.c(list3, "selections", "MergeQueue", n3, list3), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar14 = new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s c = no.a.c(list, "selections", "Node", x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"}), list);
        List n4 = sy.d0.n("PullRequestCommit");
        List list4 = vi0.a.a;
        List r8 = x61.l.r(new aa.s[]{mVar14, c, no.a.c(list4, "selections", "PullRequestCommit", n4, list4)});
        jn.Companion.getClass();
        List n5 = sy.d0.n(new aa.m("nodes", v8.l0.a(jn.a), (String) null, rVar, rVar, r8));
        aa.s mVar15 = new aa.m("__typename", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar16 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        aa.s mVar17 = new aa.m("headRefOid", v8.l0.b(hb.a), (String) null, rVar, rVar, rVar);
        hn.Companion.getClass();
        aa.s mVar18 = new aa.m("state", v8.l0.b(hn.s), (String) null, rVar, rVar, rVar);
        gg.Companion.getClass();
        aa.s mVar19 = new aa.m("mergeStateStatus", v8.l0.b(gg.s), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        aa.s mVar20 = new aa.m("repository", v8.l0.b(eq.m0), (String) null, rVar, rVar, r);
        mo.Companion.getClass();
        aa.q0 q0Var2 = mo.b;
        k71.k.g(q0Var2, "type");
        aa.s mVar21 = new aa.m("headRef", q0Var2, (String) null, rVar, rVar, r2);
        aa.s mVar22 = new aa.m("baseRefName", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        List n6 = sy.d0.n("PullRequest");
        List list5 = si0.a.a;
        aa.s c2 = no.a.c(list5, "selections", "PullRequest", n6, list5);
        aa.s mVar23 = new aa.m("viewerCanMergeAsAdmin", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        gn0.l.Companion.getClass();
        aa.j0 j0Var = gn0.l.a;
        k71.k.g(j0Var, "type");
        aa.s mVar24 = new aa.m("mergedBy", j0Var, (String) null, rVar, rVar, r4);
        gn0.d4.Companion.getClass();
        aa.q0 q0Var3 = gn0.d4.j;
        k71.k.g(q0Var3, "type");
        aa.s mVar25 = new aa.m("mergeCommit", q0Var3, (String) null, rVar, rVar, r5);
        cg.Companion.getClass();
        aa.q0 q0Var4 = cg.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar26 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, r6);
        yf.Companion.getClass();
        aa.q0 q0Var5 = yf.c;
        k71.k.g(q0Var5, "type");
        aa.s mVar27 = new aa.m("mergeQueue", q0Var5, (String) null, rVar, rVar, r7);
        aa.s mVar28 = new aa.m("viewerCanUpdate", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ln.Companion.getClass();
        aa.r b2 = v8.l0.b(ln.a);
        ll.Companion.getClass();
        List r9 = x61.l.r(new aa.s[]{mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, c2, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, new aa.m("timelineItems", b2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ll.F, new aa.u0(sy.d0.n("PULL_REQUEST_COMMIT"))), new aa.k(ll.G, new aa.u0(1))}), n5)});
        aa.q0 q0Var6 = ll.K;
        k71.k.g(q0Var6, "type");
        aa.m mVar29 = new aa.m("pullRequest", q0Var6, (String) null, rVar, rVar, r9);
        k71.k.g(xVar3, "type");
        List r10 = x61.l.r(new aa.m[]{mVar29, new aa.m("clientMutationId", xVar3, (String) null, rVar, rVar, rVar)});
        uz.Companion.getClass();
        aa.q0 q0Var7 = uz.a;
        k71.k.g(q0Var7, "type");
        wh.Companion.getClass();
        a = sy.d0.n(new aa.m("updatePullRequestBranch", q0Var7, (String) null, rVar, no.a.s(wh.U0, new aa.u0(x61.x.u(new w61.k("pullRequestId", new aa.t("id")), new w61.k("updateMethod", new aa.t("updateMethod"))))), r10));
    }
}
