package en0;

import gn0.dn;
import gn0.eq;
import gn0.fm;
import gn0.hb;
import gn0.hm;
import gn0.jm;
import gn0.lb;
import gn0.ll;
import gn0.lm;
import gn0.mx;
import gn0.p8;
import gn0.pb;
import gn0.rn;
import gn0.s00;
import gn0.tb;
import gn0.tm;
import gn0.vm;
import gn0.xm;
import gn0.yh;
import gn0.zm;
import java.util.List;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class y2 {
    public static final List a;

    static {
        pb.Companion.getClass();
        aa.x xVar = pb.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        aa.m mVar2 = new aa.m("headRefOid", v8.l0.b(hb.a), (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        aa.x xVar2 = tb.a;
        List r = x61.l.r(new aa.m[]{mVar, mVar2, new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar3 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.a.a;
        List r3 = x61.l.r(new aa.s[]{mVar3, no.a.c(list, "selections", "Actor", r2, list)});
        aa.s mVar4 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = sy.d0Shadow.n("Repository");
        List list2 = pj0.f.a;
        aa.s c = no.a.c(list2, "selections", "Repository", n, list2);
        List n2 = sy.d0Shadow.n("Repository");
        List list3 = pj0.a.a;
        List r4 = x61.l.r(new aa.s[]{mVar4, c, no.a.c(list3, "selections", "Repository", n2, list3), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new aa.m[]{new aa.m("login", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar5 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n3 = sy.d0Shadow.n("DiffLine");
        List list4 = rf0.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar5, no.a.c(list4, "selections", "DiffLine", n3, list4)});
        aa.s mVar6 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list5 = te0.a.a;
        aa.s c2 = no.a.c(list5, "selections", "Comment", r7, list5);
        List r8 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list6 = bj0.a.a;
        aa.s c3 = no.a.c(list6, "selections", "Reactable", r8, list6);
        List r9 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list7 = tk0.b.a;
        aa.s c4 = no.a.c(list7, "selections", "Updatable", r9, list7);
        List r10 = x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list8 = zh0.a.a;
        aa.s c5 = no.a.c(list8, "selections", "OrgBlockable", r10, list8);
        List r12 = x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"});
        List list9 = rh0.a.a;
        aa.s c6 = no.a.c(list9, "selections", "Minimizable", r12, list9);
        mx.Companion.getClass();
        aa.x xVar3 = mx.a;
        aa.s mVar7 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        lm.Companion.getClass();
        aa.a0 a0Var = lm.s;
        List r13 = x61.l.r(new aa.s[]{mVar6, c2, c3, c4, c5, c6, mVar7, new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        hm.Companion.getClass();
        List n4 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(hm.a), (String) null, rVar, rVar, r13));
        aa.s mVar8 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar9 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar10 = new aa.m("path", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        dn.Companion.getClass();
        aa.a0 a0Var2 = dn.s;
        aa.s mVar11 = new aa.m("subjectType", v8.l0.b(a0Var2), (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        aa.x xVar4 = lb.a;
        aa.s mVar12 = new aa.m("isResolved", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("viewerCanResolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar14 = new aa.m("viewerCanUnresolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        s00.Companion.getClass();
        aa.q0 q0Var = s00.P;
        k71.k.g(q0Var, "type");
        aa.s mVar15 = new aa.m("resolvedBy", q0Var, (String) null, rVar, rVar, r5);
        aa.s mVar16 = new aa.m("viewerCanReply", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        p8.Companion.getClass();
        aa.q0 q0Var2 = p8.a;
        aa.s mVar17 = new aa.m("diffLines", v8.l0.a(q0Var2), (String) null, rVar, rVar, r6);
        List n5 = sy.d0Shadow.n("PullRequestReviewThread");
        List list10 = zi0.a.a;
        aa.s c7 = no.a.c(list10, "selections", "PullRequestReviewThread", n5, list10);
        jm.Companion.getClass();
        aa.r b2 = v8.l0.b(jm.a);
        zm.Companion.getClass();
        List r14 = x61.l.r(new aa.s[]{mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, c7, new aa.m("comments", b2, (String) null, rVar, no.a.s(zm.a, new aa.u0(50)), n4)});
        List r15 = x61.l.r(new aa.m[]{new aa.m("login", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r16 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), no.a.c(list4, "selections", "DiffLine", sy.d0Shadow.n("DiffLine"), list4)});
        aa.s mVar18 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar19 = new aa.m("isResolved", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        List r17 = x61.l.r(new aa.s[]{mVar18, mVar19, new aa.m("resolvedBy", q0Var, (String) null, rVar, rVar, r15), new aa.m("viewerCanResolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("viewerCanUnresolve", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("viewerCanReply", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("diffLines", v8.l0.a(q0Var2), (String) null, rVar, rVar, r16), no.a.c(list10, "selections", "PullRequestReviewThread", sy.d0Shadow.n("PullRequestReviewThread"), list10), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar20 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("path", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("subjectType", v8.l0.b(a0Var2), (String) null, rVar, rVar, rVar);
        aa.q0 q0Var3 = zm.d;
        k71.k.g(q0Var3, "type");
        List r18 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequestReviewThread", sy.d0Shadow.n("PullRequestReviewThread"), r14), new aa.n("PullRequestReviewComment", sy.d0Shadow.n("PullRequestReviewComment"), x61.l.r(new aa.s[]{mVar20, mVar21, mVar22, mVar23, new aa.m("thread", q0Var3, (String) null, rVar, rVar, r17), no.a.c(list5, "selections", "Comment", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"}), list5), no.a.c(list6, "selections", "Reactable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"}), list6), no.a.c(list7, "selections", "Updatable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"}), list7), no.a.c(list8, "selections", "OrgBlockable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"}), list8), no.a.c(list9, "selections", "Minimizable", x61.l.r(new String[]{"CommitComment", "DiscussionComment", "GistComment", "IssueComment", "PullRequestReview", "PullRequestReviewComment"}), list9), new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("state", v8.l0.b(a0Var), (String) null, rVar, rVar, rVar)}))});
        tm.Companion.getClass();
        List n6 = sy.d0Shadow.n(new aa.m("nodes", v8.l0.a(tm.a), (String) null, rVar, rVar, r18));
        aa.s mVar24 = new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        xm.Companion.getClass();
        aa.s mVar26 = new aa.m("state", v8.l0.b(xm.s), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("url", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar28 = new aa.m("authorCanPushToRepository", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        gn0.r6.Companion.getClass();
        aa.x xVar5 = gn0.r6.a;
        k71.k.g(xVar5, "type");
        aa.s mVar29 = new aa.m("submittedAt", xVar5, (String) null, rVar, rVar, rVar);
        aa.s c8 = no.a.c(list5, "selections", "Comment", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"}), list5);
        aa.s c9 = no.a.c(list6, "selections", "Reactable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"}), list6);
        aa.s c10 = no.a.c(list7, "selections", "Updatable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"}), list7);
        aa.s c12 = no.a.c(list8, "selections", "OrgBlockable", x61.l.r(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"}), list8);
        ll.Companion.getClass();
        aa.s mVar30 = new aa.m("pullRequest", v8.l0.b(ll.K), (String) null, rVar, rVar, r);
        gn0.l.Companion.getClass();
        aa.j0 j0Var = gn0.l.a;
        k71.k.g(j0Var, "type");
        aa.s mVar31 = new aa.m("author", j0Var, (String) null, rVar, rVar, r3);
        eq.Companion.getClass();
        aa.s mVar32 = new aa.m("repository", v8.l0.b(eq.m0), (String) null, rVar, rVar, r4);
        vm.Companion.getClass();
        aa.q0 q0Var4 = vm.a;
        k71.k.g(q0Var4, "type");
        fm.Companion.getClass();
        List r19 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.n("PullRequestReview", sy.d0Shadow.n("PullRequestReview"), x61.l.r(new aa.s[]{mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, c8, c9, c10, c12, mVar30, mVar31, mVar32, new aa.m("threadsAndReplies", q0Var4, (String) null, rVar, no.a.s(fm.c, new aa.u0(50)), n6)})), new aa.m("id", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yh.Companion.getClass();
        aa.j0 j0Var2 = yh.a;
        k71.k.g(j0Var2, "type");
        rn.Companion.getClass();
        a = sy.d0Shadow.n(new aa.m("node", j0Var2, (String) null, rVar, no.a.s(rn.i, new aa.u0(new aa.t("id"))), r19));
    }
}
