package lt0;

import aa.m;
import aa.q0;
import aa.r;
import aa.s;
import aa.u0;
import aa.x;
import java.util.List;
import k71.k;
import pz0.bm;
import pz0.h50;
import pz0.jx;
import pz0.ln;
import pz0.na;
import pz0.pd;
import pz0.rx;
import pz0.ry;
import pz0.td;
import pz0.vd;
import pz0.xd;
import pz0.zn;
import sy.d0;
import v8.l0;
import vu0.n;
import x61.l;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class b {
    public static final List a;

    static {
        xd.Companion.getClass();
        x xVar = xd.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        s mVar = new m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = d0.n("ProfileItemShowcase");
        List list = ut0.a.a;
        List r = l.r(new s[]{mVar, no.a.c(list, "selections", "ProfileItemShowcase", n, list)});
        vd.Companion.getClass();
        x xVar2 = vd.a;
        List n2 = d0.n(new m("totalCount", l0.b(xVar2), (String) null, rVar, rVar, rVar));
        s mVar2 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = d0.n("RepositoryReadme");
        List list2 = n.a;
        List r2 = l.r(new s[]{mVar2, no.a.c(list2, "selections", "RepositoryReadme", n3, list2)});
        List n4 = d0.n(new m("totalCount", l0.b(xVar2), (String) null, rVar, rVar, rVar));
        List n5 = d0.n(new m("totalCount", l0.b(xVar2), (String) null, rVar, rVar, rVar));
        m mVar3 = new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        na.Companion.getClass();
        r b2 = l0.b(na.a);
        jx.Companion.getClass();
        m mVar4 = new m("discussions", b2, (String) null, rVar, no.a.s(jx.m, new u0(0)), n5);
        td.Companion.getClass();
        x xVar3 = td.a;
        List r3 = l.r(new m[]{mVar3, mVar4, new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        s mVar5 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar6 = new m("id", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        x xVar4 = h50.a;
        s mVar7 = new m("url", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        List r4 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list3 = dp0.b.a;
        s c = no.a.c(list3, "selections", "Actor", r4, list3);
        s mVar8 = new m("descriptionHTML", xVar, (String) null, rVar, rVar, rVar);
        s mVar9 = new m("email", xVar, "organizationEmail", rVar, rVar, rVar);
        pd.Companion.getClass();
        x xVar5 = pd.a;
        s mVar10 = new m("isVerified", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        ln.Companion.getClass();
        s mVar11 = new m("itemShowcase", l0.b(ln.b), "organizationItemShowcase", rVar, rVar, r);
        s mVar12 = new m("location", xVar, (String) null, rVar, rVar, rVar);
        s mVar13 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        s mVar14 = new m("name", xVar, (String) null, rVar, rVar, rVar);
        s mVar15 = new m("viewerIsFollowing", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        rx.Companion.getClass();
        r b3 = l0.b(rx.a);
        bm.Companion.getClass();
        s mVar16 = new m("repositories", b3, "organizationRepositories", rVar, no.a.s(bm.h, new u0(d0.n("OWNER"))), n2);
        ry.Companion.getClass();
        q0 q0Var = ry.a;
        k.g(q0Var, "type");
        s mVar17 = new m("readme", q0Var, (String) null, rVar, rVar, r2);
        s mVar18 = new m("websiteUrl", xVar4, (String) null, rVar, rVar, rVar);
        s mVar19 = new m("twitterUsername", xVar, (String) null, rVar, rVar, rVar);
        zn.Companion.getClass();
        s mVar20 = new m("projectsV2", l0.b(zn.a), (String) null, rVar, no.a.s(bm.a, new u0(0)), n4);
        q0 q0Var2 = jx.t0;
        k.g(q0Var2, "type");
        a = l.r(new s[]{mVar5, mVar6, mVar7, c, mVar8, mVar9, mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, new m("organizationDiscussionsRepository", q0Var2, (String) null, rVar, rVar, r3), new m("viewerIsFollowing", l0.b(xVar5), (String) null, rVar, rVar, rVar)});
    }
}
