package si0;

import aa.j0;
import aa.q0;
import aa.t;
import aa.u0;
import aa.x;
import aa.x0;
import gn0.cw;
import gn0.eq;
import gn0.fm;
import gn0.ga;
import gn0.hb;
import gn0.hr;
import gn0.ix;
import gn0.jj;
import gn0.jm;
import gn0.lb;
import gn0.lj;
import gn0.ll;
import gn0.mx;
import gn0.n8;
import gn0.na;
import gn0.nj;
import gn0.nm;
import gn0.p8;
import gn0.pb;
import gn0.pj;
import gn0.pl;
import gn0.rb;
import gn0.rl;
import gn0.tb;
import java.util.List;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class e {
    public static final List a;

    static {
        tb.Companion.getClass();
        x xVar = tb.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        pb.Companion.getClass();
        x xVar2 = pb.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("Repository");
        List list = pj0.f.a;
        aa.s c = no.a.c(list, "selections", "Repository", n, list);
        List n2 = d0Shadow.n("Repository");
        List list2 = pj0.a.a;
        List r3 = x61.l.r(new aa.s[]{mVar2, c, no.a.c(list2, "selections", "Repository", n2, list2), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar3 = new aa.m("endCursor", xVar, (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar3 = lb.a;
        List r4 = x61.l.r(new aa.m[]{mVar3, new aa.m("hasNextPage", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        mx.Companion.getClass();
        x xVar4 = mx.a;
        k71.k.g(xVar4, "type");
        List r5 = x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("ImageFileType", d0Shadow.n("ImageFileType"), d0Shadow.n(new aa.m("url", xVar4, (String) null, rVar, rVar, rVar)))});
        aa.m mVar4 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        ga.Companion.getClass();
        x0 x0Var = ga.a;
        k71.k.g(x0Var, "type");
        List r6 = x61.l.r(new aa.m[]{mVar4, new aa.m("fileType", x0Var, (String) null, rVar, rVar, r5)});
        List n3 = d0Shadow.n(new aa.m("gitUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar));
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"ImageFileType", "MarkdownFileType", "PdfFileType", "TextFileType"});
        List list3 = c.a;
        List r8 = x61.l.r(new aa.s[]{mVar5, no.a.c(list3, "selections", "File", r7, list3)});
        aa.m mVar6 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("isGenerated", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        cw.Companion.getClass();
        q0 q0Var = cw.a;
        k71.k.g(q0Var, "type");
        aa.m mVar8 = new aa.m("submodule", q0Var, (String) null, rVar, rVar, n3);
        rb.Companion.getClass();
        x xVar5 = rb.a;
        k71.k.g(xVar5, "type");
        List r9 = x61.l.r(new aa.m[]{mVar6, mVar7, mVar8, new aa.m("lineCount", xVar5, (String) null, rVar, rVar, rVar), new aa.m("fileType", x0Var, (String) null, rVar, rVar, r8)});
        aa.s mVar9 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n4 = d0Shadow.n("DiffLine");
        List list4 = rf0.a.a;
        List r10 = x61.l.r(new aa.s[]{mVar9, no.a.c(list4, "selections", "DiffLine", n4, list4)});
        aa.m mVar10 = new aa.m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar11 = new aa.m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        ix.Companion.getClass();
        q0 q0Var2 = ix.a;
        k71.k.g(q0Var2, "type");
        aa.m mVar12 = new aa.m("oldTreeEntry", q0Var2, (String) null, rVar, rVar, r6);
        aa.m mVar13 = new aa.m("newTreeEntry", q0Var2, (String) null, rVar, rVar, r9);
        p8.Companion.getClass();
        aa.m mVar14 = new aa.m("diffLines", l0.a(p8.a), (String) null, rVar, rVar, r10);
        aa.m mVar15 = new aa.m("isBinary", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("isLargeDiff", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.m mVar17 = new aa.m("isSubmodule", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        pj.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("status", l0.b(pj.s), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        jj.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", l0.b(jj.a), (String) null, rVar, rVar, r4);
        lj.Companion.getClass();
        List r13 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", l0.a(lj.b), (String) null, rVar, rVar, r12)});
        nj.Companion.getClass();
        aa.r b2 = l0.b(nj.a);
        n8.Companion.getClass();
        List n5 = d0Shadow.n(new aa.m("patches", b2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(n8.b, new u0(new t("after"))), new aa.k(n8.c, new u0(50))}), r13));
        List n6 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar5), (String) null, rVar, rVar, rVar));
        aa.m mVar19 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        jm.Companion.getClass();
        aa.r b3 = l0.b(jm.a);
        fm.Companion.getClass();
        List n7 = d0Shadow.n(new aa.m("nodes", l0.a(fm.d), (String) null, rVar, rVar, x61.l.r(new aa.m[]{mVar19, new aa.m("comments", b3, (String) null, rVar, no.a.s(fm.a, new u0(1)), n6), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)})));
        na.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{new aa.m("viewerViewedState", l0.b(na.s), (String) null, rVar, rVar, rVar), new aa.m("path", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        pl.Companion.getClass();
        List n8 = d0Shadow.n(new aa.m("nodes", l0.a(pl.a), (String) null, rVar, rVar, r14));
        aa.s mVar20 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        aa.s mVar22 = new aa.m("headRefOid", l0.b(hb.a), (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("viewerCanEditFiles", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("baseRefName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("headRefName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("additions", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("deletions", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        q0 q0Var3 = eq.m0;
        k71.k.g(q0Var3, "type");
        aa.s mVar28 = new aa.m("headRepository", q0Var3, (String) null, rVar, rVar, r);
        hr.Companion.getClass();
        j0 j0Var = hr.a;
        k71.k.g(j0Var, "type");
        aa.s mVar29 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar30 = new aa.m("repository", l0.b(q0Var3), (String) null, rVar, rVar, r3);
        q0 q0Var4 = n8.d;
        k71.k.g(q0Var4, "type");
        aa.s mVar31 = new aa.m("diff", q0Var4, (String) null, rVar, rVar, n5);
        List n9 = d0Shadow.n("PullRequest");
        List list5 = d.a;
        aa.s c2 = no.a.c(list5, "selections", "PullRequest", n9, list5);
        nm.Companion.getClass();
        q0 q0Var5 = nm.a;
        k71.k.g(q0Var5, "type");
        ll.Companion.getClass();
        aa.s mVar32 = new aa.m("reviews", q0Var5, "pendingReviews", rVar, x61.l.r(new aa.k[]{new aa.k(ll.y, new u0(1)), new aa.k(ll.z, new u0(d0Shadow.n("PENDING")))}), n7);
        rl.Companion.getClass();
        q0 q0Var6 = rl.a;
        k71.k.g(q0Var6, "type");
        a = x61.l.r(new aa.s[]{mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, c2, mVar32, new aa.m("files", q0Var6, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ll.m, new u0(new t("after"))), new aa.k(ll.n, new u0(50))}), n8)});
    }
}
