package si0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import gn0.cg;
import gn0.d4;
import gn0.eq;
import gn0.hn;
import gn0.hr;
import gn0.j6;
import gn0.kw;
import gn0.lb;
import gn0.ll;
import gn0.mx;
import gn0.pb;
import gn0.pm;
import gn0.qv;
import gn0.r6;
import gn0.rb;
import gn0.rc;
import gn0.s00;
import gn0.tb;
import gn0.tl;
import gn0.vb;
import gn0.xl;
import gn0.y00;
import gn0.yf;
import gn0.yv;
import java.util.List;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class h {
    public static final List a;

    static {
        tb.Companion.getClass();
        x xVar = tb.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        pb.Companion.getClass();
        x xVar2 = pb.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r3 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar2 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        kw.Companion.getClass();
        a0 a0Var = kw.s;
        k71.k.g(a0Var, "type");
        aa.m mVar4 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        j6.Companion.getClass();
        aa.m mVar5 = new aa.m("viewerSubscriptionTypes", l0.a(l0.b(j6.s)), (String) null, rVar, rVar, rVar);
        hr.Companion.getClass();
        j0 j0Var = hr.a;
        List r4 = x61.l.r(new aa.m[]{mVar2, mVar3, mVar4, mVar5, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r5 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar6, no.a.c(list, "selections", "Actor", r5, list), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        rb.Companion.getClass();
        x xVar3 = rb.a;
        aa.m mVar7 = new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        s00.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar7, new aa.m("nodes", l0.a(s00.P), (String) null, rVar, rVar, r6)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        yv.Companion.getClass();
        List r8 = x61.l.r(new aa.m[]{mVar8, new aa.m("state", l0.b(yv.s), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar9 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        qv.Companion.getClass();
        q0 q0Var = qv.c;
        k71.k.g(q0Var, "type");
        List r9 = x61.l.r(new aa.m[]{mVar9, new aa.m("statusCheckRollup", q0Var, (String) null, rVar, rVar, r8), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar10 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        d4.Companion.getClass();
        List r10 = x61.l.r(new aa.m[]{mVar10, new aa.m("commit", l0.b(d4.j), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        tl.Companion.getClass();
        List n = d0Shadow.n(new aa.m("nodes", l0.a(tl.a), (String) null, rVar, rVar, r10));
        List n2 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r12 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("position", l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("MergeQueue");
        List list2 = jh0.c.a;
        List r13 = x61.l.r(new aa.s[]{mVar11, no.a.c(list2, "selections", "MergeQueue", n3, list2), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar12 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        x xVar4 = lb.a;
        aa.s mVar14 = new aa.m("isDraft", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar15 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        vb.Companion.getClass();
        aa.s mVar16 = new aa.m("titleHTML", l0.b(vb.a), "titleHTMLString", rVar, rVar, rVar);
        aa.s mVar17 = new aa.m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        r6.Companion.getClass();
        aa.s mVar18 = new aa.m("createdAt", l0.b(r6.a), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        q0 q0Var2 = eq.m0;
        k71.k.g(q0Var2, "type");
        aa.s mVar19 = new aa.m("headRepository", q0Var2, (String) null, rVar, rVar, r);
        aa.s mVar20 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar21 = new aa.m("isReadByViewer", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list3 = tg0.a.a;
        aa.s c = no.a.c(list3, "selections", "Labelable", r14, list3);
        hn.Companion.getClass();
        aa.s mVar23 = new aa.m("state", l0.b(hn.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4);
        mx.Companion.getClass();
        aa.s mVar25 = new aa.m("url", l0.b(mx.a), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        pm.Companion.getClass();
        a0 a0Var2 = pm.s;
        k71.k.g(a0Var2, "type");
        aa.s mVar27 = new aa.m("reviewDecision", a0Var2, (String) null, rVar, rVar, rVar);
        y00.Companion.getClass();
        aa.r b2 = l0.b(y00.a);
        ll.Companion.getClass();
        aa.s mVar28 = new aa.m("assignees", b2, (String) null, rVar, no.a.s(ll.a, new u0(25)), r7);
        xl.Companion.getClass();
        aa.s mVar29 = new aa.m("commits", l0.b(xl.a), (String) null, rVar, no.a.s(ll.l, new u0(1)), n);
        rc.Companion.getClass();
        q0 q0Var3 = rc.a;
        k71.k.g(q0Var3, "type");
        aa.s mVar30 = new aa.m("closingIssuesReferences", q0Var3, (String) null, rVar, rVar, n2);
        aa.s mVar31 = new aa.m("isInMergeQueue", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        cg.Companion.getClass();
        q0 q0Var4 = cg.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar32 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, r12);
        yf.Companion.getClass();
        q0 q0Var5 = yf.c;
        k71.k.g(q0Var5, "type");
        aa.s mVar33 = new aa.m("mergeQueue", q0Var5, (String) null, rVar, rVar, r13);
        List n4 = d0Shadow.n("PullRequest");
        List list4 = r.a;
        a = x61.l.r(new aa.s[]{mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, c, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, no.a.c(list4, "selections", "PullRequest", n4, list4)});
    }

    public static List a() {
        return a;
    }
}
