package si0;

import aa.t;
import aa.u0;
import aa.x;
import gn0.jj;
import gn0.jn;
import gn0.lb;
import gn0.ll;
import gn0.ln;
import gn0.pb;
import gn0.rb;
import gn0.tb;
import java.util.List;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class m {
    public static final List a;

    static {
        lb.Companion.getClass();
        x xVar = lb.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("hasPreviousPage", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        x xVar2 = tb.a;
        k71.k.g(xVar2, "type");
        aa.m mVar2 = new aa.m("startCursor", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("hasNextPage", l0.b(xVar), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar2, "type");
        List r = x61.l.r(new aa.m[]{mVar, mVar2, mVar3, new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list = cl0.a.a;
        aa.s c = no.a.c(list, "selections", "Node", r2, list);
        List n = d0Shadow.n("IssueComment");
        List list2 = pg0.a.a;
        aa.s c2 = no.a.c(list2, "selections", "IssueComment", n, list2);
        List n2 = d0Shadow.n("RenamedTitleEvent");
        List list3 = jj0.a.a;
        aa.s c3 = no.a.c(list3, "selections", "RenamedTitleEvent", n2, list3);
        List n3 = d0Shadow.n("AssignedEvent");
        List list4 = be0.a.a;
        aa.s c4 = no.a.c(list4, "selections", "AssignedEvent", n3, list4);
        List n4 = d0Shadow.n("UnassignedEvent");
        List list5 = lk0.a.a;
        aa.s c5 = no.a.c(list5, "selections", "UnassignedEvent", n4, list5);
        List n5 = d0Shadow.n("ClosedEvent");
        List list6 = re0.a.a;
        aa.s c6 = no.a.c(list6, "selections", "ClosedEvent", n5, list6);
        List n6 = d0Shadow.n("ReopenedEvent");
        List list7 = lj0.a.a;
        aa.s c7 = no.a.c(list7, "selections", "ReopenedEvent", n6, list7);
        List n7 = d0Shadow.n("LabeledEvent");
        List list8 = vg0.a.a;
        aa.s c8 = no.a.c(list8, "selections", "LabeledEvent", n7, list8);
        List n8 = d0Shadow.n("UnlabeledEvent");
        List list9 = nk0.a.a;
        aa.s c9 = no.a.c(list9, "selections", "UnlabeledEvent", n8, list9);
        List n9 = d0Shadow.n("LockedEvent");
        List list10 = dh0.a.a;
        aa.s c10 = no.a.c(list10, "selections", "LockedEvent", n9, list10);
        List n10 = d0Shadow.n("UnlockedEvent");
        List list11 = pk0.a.a;
        aa.s c12 = no.a.c(list11, "selections", "UnlockedEvent", n10, list11);
        List n12 = d0Shadow.n("MilestonedEvent");
        List list12 = ph0.a.a;
        aa.s c13 = no.a.c(list12, "selections", "MilestonedEvent", n12, list12);
        List n13 = d0Shadow.n("DemilestonedEvent");
        List list13 = jf0.a.a;
        aa.s c14 = no.a.c(list13, "selections", "DemilestonedEvent", n13, list13);
        List n14 = d0Shadow.n("CrossReferencedEvent");
        List list14 = ff0.a.a;
        aa.s c15 = no.a.c(list14, "selections", "CrossReferencedEvent", n14, list14);
        List n15 = d0Shadow.n("ReferencedEvent");
        List list15 = fj0.a.a;
        aa.s c16 = no.a.c(list15, "selections", "ReferencedEvent", n15, list15);
        List n16 = d0Shadow.n("MergedEvent");
        List list16 = lh0.a.a;
        aa.s c17 = no.a.c(list16, "selections", "MergedEvent", n16, list16);
        List n17 = d0Shadow.n("PullRequestCommit");
        List list17 = vi0.a.a;
        aa.s c18 = no.a.c(list17, "selections", "PullRequestCommit", n17, list17);
        List n18 = d0Shadow.n("HeadRefDeletedEvent");
        List list18 = hg0.a.a;
        aa.s c19 = no.a.c(list18, "selections", "HeadRefDeletedEvent", n18, list18);
        List n19 = d0Shadow.n("HeadRefRestoredEvent");
        List list19 = lg0.a.a;
        aa.s c20 = no.a.c(list19, "selections", "HeadRefRestoredEvent", n19, list19);
        List n20 = d0Shadow.n("ReviewRequestedEvent");
        List list20 = zj0.a.a;
        aa.s c22 = no.a.c(list20, "selections", "ReviewRequestedEvent", n20, list20);
        List n22 = d0Shadow.n("ReviewRequestRemovedEvent");
        List list21 = xj0.a.a;
        aa.s c23 = no.a.c(list21, "selections", "ReviewRequestRemovedEvent", n22, list21);
        List n23 = d0Shadow.n("ReviewDismissedEvent");
        List list22 = tj0.a.a;
        aa.s c24 = no.a.c(list22, "selections", "ReviewDismissedEvent", n23, list22);
        List n24 = d0Shadow.n("PullRequestReview");
        List list23 = xi0.a.a;
        aa.s c25 = no.a.c(list23, "selections", "PullRequestReview", n24, list23);
        List n25 = d0Shadow.n("ReadyForReviewEvent");
        List list24 = dj0.a.a;
        aa.s c26 = no.a.c(list24, "selections", "ReadyForReviewEvent", n25, list24);
        List n26 = d0Shadow.n("ConvertToDraftEvent");
        List list25 = bf0.a.a;
        aa.s c27 = no.a.c(list25, "selections", "ConvertToDraftEvent", n26, list25);
        List n27 = d0Shadow.n("AddedToProjectEvent");
        List list26 = xd0.a.a;
        aa.s c28 = no.a.c(list26, "selections", "AddedToProjectEvent", n27, list26);
        List n28 = d0Shadow.n("MovedColumnsInProjectEvent");
        List list27 = vh0.a.a;
        aa.s c29 = no.a.c(list27, "selections", "MovedColumnsInProjectEvent", n28, list27);
        List n29 = d0Shadow.n("RemovedFromProjectEvent");
        List list28 = hj0.a.a;
        aa.s c30 = no.a.c(list28, "selections", "RemovedFromProjectEvent", n29, list28);
        List n30 = d0Shadow.n("DeployedEvent");
        List list29 = lf0.a.a;
        aa.s c32 = no.a.c(list29, "selections", "DeployedEvent", n30, list29);
        List n32 = d0Shadow.n("CommentDeletedEvent");
        List list30 = ve0.a.a;
        aa.s c33 = no.a.c(list30, "selections", "CommentDeletedEvent", n32, list30);
        List n33 = d0Shadow.n("HeadRefForcePushedEvent");
        List list31 = jg0.a.a;
        aa.s c34 = no.a.c(list31, "selections", "HeadRefForcePushedEvent", n33, list31);
        List n34 = d0Shadow.n("TransferredEvent");
        List list32 = jk0.a.a;
        aa.s c35 = no.a.c(list32, "selections", "TransferredEvent", n34, list32);
        List n35 = d0Shadow.n("BaseRefChangedEvent");
        List list33 = ne0.a.a;
        aa.s c36 = no.a.c(list33, "selections", "BaseRefChangedEvent", n35, list33);
        List n36 = d0Shadow.n("MarkedAsDuplicateEvent");
        List list34 = fh0.a.a;
        aa.s c37 = no.a.c(list34, "selections", "MarkedAsDuplicateEvent", n36, list34);
        List n37 = d0Shadow.n("DeploymentEnvironmentChangedEvent");
        List list35 = nf0.a.a;
        aa.s c38 = no.a.c(list35, "selections", "DeploymentEnvironmentChangedEvent", n37, list35);
        List n38 = d0Shadow.n("AutoMergeEnabledEvent");
        List list36 = fe0.a.a;
        aa.s c39 = no.a.c(list36, "selections", "AutoMergeEnabledEvent", n38, list36);
        List n39 = d0Shadow.n("AutoSquashEnabledEvent");
        List list37 = je0.a.a;
        aa.s c40 = no.a.c(list37, "selections", "AutoSquashEnabledEvent", n39, list37);
        List n40 = d0Shadow.n("AutoRebaseEnabledEvent");
        List list38 = he0.a.a;
        aa.s c42 = no.a.c(list38, "selections", "AutoRebaseEnabledEvent", n40, list38);
        List n42 = d0Shadow.n("AutoMergeDisabledEvent");
        List list39 = de0.a.a;
        aa.s c43 = no.a.c(list39, "selections", "AutoMergeDisabledEvent", n42, list39);
        List n43 = d0Shadow.n("UserBlockedEvent");
        List list40 = al0.a.a;
        aa.s c44 = no.a.c(list40, "selections", "UserBlockedEvent", n43, list40);
        List n44 = d0Shadow.n("AddedToMergeQueueEvent");
        List list41 = jh0.a.a;
        aa.s c45 = no.a.c(list41, "selections", "AddedToMergeQueueEvent", n44, list41);
        List n45 = d0Shadow.n("RemovedFromMergeQueueEvent");
        List list42 = jh0.d.a;
        aa.s c46 = no.a.c(list42, "selections", "RemovedFromMergeQueueEvent", n45, list42);
        List n46 = d0Shadow.n("ConnectedEvent");
        List list43 = ze0.a.a;
        aa.s c47 = no.a.c(list43, "selections", "ConnectedEvent", n46, list43);
        List n47 = d0Shadow.n("DisconnectedEvent");
        List list44 = tf0.a.a;
        aa.s c48 = no.a.c(list44, "selections", "DisconnectedEvent", n47, list44);
        List n48 = d0Shadow.n("AutomaticBaseChangeSucceededEvent");
        List list45 = le0.a.a;
        List r3 = x61.l.r(new aa.s[]{mVar4, c, c2, c3, c4, c5, c6, c7, c8, c9, c10, c12, c13, c14, c15, c16, c17, c18, c19, c20, c22, c23, c24, c25, c26, c27, c28, c29, c30, c32, c33, c34, c35, c36, c37, c38, c39, c40, c42, c43, c44, c45, c46, c47, c48, no.a.c(list45, "selections", "AutomaticBaseChangeSucceededEvent", n48, list45)});
        aa.m mVar5 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        rb.Companion.getClass();
        aa.m mVar6 = new aa.m("beforeFocusCount", l0.b(rb.a), (String) null, rVar, rVar, rVar);
        jj.Companion.getClass();
        aa.m mVar7 = new aa.m("pageInfo", l0.b(jj.a), (String) null, rVar, rVar, r);
        jn.Companion.getClass();
        List r4 = x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, new aa.m("nodes", l0.a(jn.a), (String) null, rVar, rVar, r3)});
        aa.m mVar8 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        pb.Companion.getClass();
        aa.m mVar9 = new aa.m("id", l0.b(pb.a), (String) null, rVar, rVar, rVar);
        ln.Companion.getClass();
        aa.r b2 = l0.b(ln.a);
        ll.Companion.getClass();
        a = x61.l.r(new aa.m[]{mVar8, mVar9, new aa.m("timelineItems", b2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(ll.B, new u0(new t("after"))), new aa.k(ll.C, new u0(new t("before"))), new aa.k(ll.D, new u0(new t("desiredAfterCount"))), new aa.k(ll.E, new u0(new t("focusId"))), new aa.k(ll.F, new u0(x61.l.r(new String[]{"ISSUE_COMMENT", "RENAMED_TITLE_EVENT", "ASSIGNED_EVENT", "UNASSIGNED_EVENT", "CLOSED_EVENT", "REOPENED_EVENT", "LABELED_EVENT", "UNLABELED_EVENT", "LOCKED_EVENT", "UNLOCKED_EVENT", "MILESTONED_EVENT", "DEMILESTONED_EVENT", "CROSS_REFERENCED_EVENT", "REFERENCED_EVENT", "MERGED_EVENT", "PULL_REQUEST_COMMIT", "HEAD_REF_DELETED_EVENT", "REVIEW_REQUESTED_EVENT", "REVIEW_REQUEST_REMOVED_EVENT", "REVIEW_DISMISSED_EVENT", "PULL_REQUEST_REVIEW", "READY_FOR_REVIEW_EVENT", "CONVERT_TO_DRAFT_EVENT", "ADDED_TO_PROJECT_EVENT", "MOVED_COLUMNS_IN_PROJECT_EVENT", "REMOVED_FROM_PROJECT_EVENT", "COMMENT_DELETED_EVENT", "DEPLOYED_EVENT", "HEAD_REF_FORCE_PUSHED_EVENT", "HEAD_REF_RESTORED_EVENT", "BASE_REF_CHANGED_EVENT", "MARKED_AS_DUPLICATE_EVENT", "DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT", "AUTO_MERGE_DISABLED_EVENT", "AUTO_MERGE_ENABLED_EVENT", "AUTO_REBASE_ENABLED_EVENT", "AUTO_SQUASH_ENABLED_EVENT", "USER_BLOCKED_EVENT", "ADDED_TO_MERGE_QUEUE_EVENT", "REMOVED_FROM_MERGE_QUEUE_EVENT", "CONNECTED_EVENT", "DISCONNECTED_EVENT", "AUTOMATIC_BASE_CHANGE_SUCCEEDED_EVENT"}))), new aa.k(ll.G, new u0(new t("desiredBeforeCount")))}), r4)});
    }
}
