package si0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.t;
import aa.u0;
import aa.x;
import gn0.c4;
import gn0.cg;
import gn0.cl;
import gn0.cs;
import gn0.d4;
import gn0.dl;
import gn0.dq;
import gn0.ds;
import gn0.eq;
import gn0.es;
import gn0.fm;
import gn0.fs;
import gn0.gg;
import gn0.hb;
import gn0.hn;
import gn0.kb;
import gn0.kg;
import gn0.kl;
import gn0.l2;
import gn0.lb;
import gn0.ll;
import gn0.lw;
import gn0.lx;
import gn0.m0;
import gn0.m2;
import gn0.mo;
import gn0.mw;
import gn0.mx;
import gn0.n0;
import gn0.n2;
import gn0.nk;
import gn0.nm;
import gn0.ob;
import gn0.ok;
import gn0.om;
import gn0.os;
import gn0.pb;
import gn0.pk;
import gn0.pm;
import gn0.ps;
import gn0.pv;
import gn0.q6;
import gn0.qb;
import gn0.qk;
import gn0.qo;
import gn0.qs;
import gn0.qv;
import gn0.r6;
import gn0.rb;
import gn0.rk;
import gn0.rs;
import gn0.rv;
import gn0.s00;
import gn0.sb;
import gn0.sk;
import gn0.sv;
import gn0.tb;
import gn0.tk;
import gn0.tl;
import gn0.tv;
import gn0.u10;
import gn0.uv;
import gn0.vb;
import gn0.vv;
import gn0.wv;
import gn0.x10;
import gn0.x2;
import gn0.xl;
import gn0.xm;
import gn0.y10;
import gn0.yf;
import gn0.yv;
import java.util.List;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class o {
    public static final List a;

    static {
        pb.Companion.getClass();
        aa.r b = l0.b(ob.a());
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        tb.Companion.getClass();
        List o = d0Shadow.o(new aa.m[]{mVar, new aa.m("nameWithOwner", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        List o2 = d0Shadow.o(new aa.m[]{new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("nameWithOwner", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar3 = new aa.m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List o3 = d0Shadow.o(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = vd0.b.a;
        List o4 = d0Shadow.o(new aa.s[]{mVar2, mVar3, no.a.c(list, "selections", "Actor", o3, list)});
        aa.s mVar4 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List o5 = d0Shadow.o(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List a2 = cl0.a.a();
        List o6 = d0Shadow.o(new aa.s[]{mVar4, no.a.c(a2, "selections", "Node", o5, a2), new aa.m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar5 = new aa.m("abbreviatedOid", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        r6.Companion.getClass();
        List o7 = d0Shadow.o(new aa.m[]{mVar5, new aa.m("committedDate", l0.b(q6.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("MergeQueue");
        List list2 = jh0.c.a;
        List o8 = d0Shadow.o(new aa.s[]{mVar6, no.a.c(list2, "selections", "MergeQueue", n, list2), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar7 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List n2 = d0Shadow.n("MergeQueueEntry");
        List list3 = jh0.b.a;
        List o9 = d0Shadow.o(new aa.s[]{mVar7, no.a.c(list3, "selections", "MergeQueueEntry", n2, list3), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar8 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("context", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        yv.Companion.getClass();
        a0 a0Var = yv.s;
        aa.m mVar10 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        x a3 = sb.a();
        k71.k.g(a3, "type");
        List o10 = d0Shadow.o(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("description", a3, (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        rb.Companion.getClass();
        aa.m mVar11 = new aa.m("totalCount", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        ds.Companion.getClass();
        List o12 = d0Shadow.o(new aa.m[]{mVar11, new aa.m("nodes", l0.a(cs.a()), (String) null, rVar, rVar, o10)});
        x a4 = qb.a();
        k71.k.g(a4, "type");
        aa.m mVar12 = new aa.m("recommendedApprovingReviewCount", a4, (String) null, rVar, rVar, rVar);
        lb.Companion.getClass();
        List o13 = d0Shadow.o(new aa.m[]{mVar12, new aa.m("requiresCodeOwnerReviews", l0.b(kb.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerAllowedToDismissReviews", l0.b(kb.a()), (String) null, rVar, rVar, rVar)});
        qo.Companion.getClass();
        q0 q0Var = qo.a;
        k71.k.g(q0Var, "type");
        List o14 = d0Shadow.o(new aa.m[]{new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, o13), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        List n3 = d0Shadow.n(new aa.m("viewerCanPush", l0.b(kb.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar13 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        List o15 = d0Shadow.o(new aa.m[]{mVar13, new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, n3), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar14 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List n4 = d0Shadow.n("Milestone");
        List list4 = nh0.a.a;
        List o16 = d0Shadow.o(new aa.s[]{mVar14, no.a.c(list4, "selections", "Milestone", n4, list4), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        List o17 = d0Shadow.o(new aa.m[]{new aa.m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar15 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        dl.Companion.getClass();
        List o18 = d0Shadow.o(new aa.m[]{mVar15, mVar16, new aa.m("state", l0.b(cl.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        tk.Companion.getClass();
        q0 a5 = sk.a();
        k71.k.g(a5, "type");
        aa.m mVar17 = new aa.m("column", a5, (String) null, rVar, rVar, o17);
        nk.Companion.getClass();
        List o19 = d0Shadow.o(new aa.m[]{mVar17, new aa.m("project", l0.b(nk.a), (String) null, rVar, rVar, o18), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        pk.Companion.getClass();
        List n5 = d0Shadow.n(new aa.m("nodes", l0.a(ok.a()), (String) null, rVar, rVar, o19));
        aa.s mVar18 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List n6 = d0Shadow.n("ReviewRequest");
        List a6 = vj0.a.a();
        List o20 = d0Shadow.o(new aa.s[]{mVar18, no.a.c(a6, "selections", "ReviewRequest", n6, a6), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        ps.Companion.getClass();
        List n7 = d0Shadow.n(new aa.m("nodes", l0.a(os.a()), (String) null, rVar, rVar, o20));
        aa.s mVar19 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List n8 = d0Shadow.n("PullRequestReview");
        List list5 = xi0.b.a;
        List o22 = d0Shadow.o(new aa.s[]{mVar19, no.a.c(list5, "selections", "PullRequestReview", n8, list5), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        fm.Companion.getClass();
        q0 q0Var2 = fm.d;
        List n9 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, o22));
        List n10 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar), no.a.c(list5, "selections", "PullRequestReview", d0Shadow.n("PullRequestReview"), list5), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)})));
        List o23 = d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.n("User", d0Shadow.n("User"), d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(sb.a()), (String) null, rVar, rVar, rVar), no.a.c(list, "selections", "Actor", d0Shadow.o(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)})), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar20 = new aa.m("isAuthor", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar21 = new aa.m("isCommenter", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        s00.Companion.getClass();
        List o24 = d0Shadow.o(new aa.m[]{mVar20, mVar21, new aa.m("reviewer", l0.b(s00.P), (String) null, rVar, rVar, o23)});
        aa.m mVar22 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar23 = new aa.m("context", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar24 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        mx.Companion.getClass();
        x a7 = lx.a();
        k71.k.g(a7, "type");
        aa.m mVar25 = new aa.m("avatarUrl", a7, (String) null, rVar, rVar, rVar);
        x a8 = sb.a();
        k71.k.g(a8, "type");
        aa.m mVar26 = new aa.m("description", a8, (String) null, rVar, rVar, rVar);
        x a9 = lx.a();
        k71.k.g(a9, "type");
        aa.m mVar27 = new aa.m("targetUrl", a9, (String) null, rVar, rVar, rVar);
        aa.r b2 = l0.b(kb.a());
        wv.Companion.getClass();
        vv.a();
        List o25 = d0Shadow.o(new aa.m[]{mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(wv.b, new u0(new t("numberNullableBug"))), rVar)});
        List o26 = d0Shadow.o(new aa.m[]{new aa.m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        u10.Companion.getClass();
        List o27 = d0Shadow.o(new aa.m[]{new aa.m("workflow", l0.b(u10.c), (String) null, rVar, rVar, o26), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        List o28 = d0Shadow.o(new aa.m[]{new aa.m("logoUrl", l0.b(lx.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        y10.Companion.getClass();
        q0 a10 = x10.a();
        k71.k.g(a10, "type");
        aa.m mVar28 = new aa.m("workflowRun", a10, (String) null, rVar, rVar, o27);
        n0.Companion.getClass();
        q0 a12 = m0.a();
        k71.k.g(a12, "type");
        List o29 = d0Shadow.o(new aa.m[]{mVar28, new aa.m("app", a12, (String) null, rVar, rVar, o28), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar29 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        l2.Companion.getClass();
        a0 a0Var2 = l2.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar30 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar31 = new aa.m("name", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar32 = new aa.m("duration", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        x a13 = sb.a();
        k71.k.g(a13, "type");
        aa.m mVar33 = new aa.m("summary", a13, (String) null, rVar, rVar, rVar);
        aa.m mVar34 = new aa.m("permalink", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        x2.Companion.getClass();
        aa.m mVar35 = new aa.m("checkSuite", l0.b(x2.f), (String) null, rVar, rVar, o29);
        aa.r b3 = l0.b(kb.a());
        n2.Companion.getClass();
        m2.a();
        List o30 = d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", d0Shadow.n("StatusContext"), o25), new aa.n("CheckRun", d0Shadow.n("CheckRun"), d0Shadow.o(new aa.m[]{mVar29, mVar30, mVar31, mVar32, mVar33, mVar34, mVar35, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(n2.b, new u0(new t("numberNullableBug"))), rVar)}))});
        aa.m mVar36 = new aa.m("totalCount", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        sv.Companion.getClass();
        List o32 = d0Shadow.o(new aa.m[]{mVar36, new aa.m("nodes", l0.a(rv.a()), (String) null, rVar, rVar, o30)});
        aa.m mVar37 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar38 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        uv.Companion.getClass();
        aa.r b4 = l0.b(tv.a());
        qv.Companion.getClass();
        pv.b();
        List o33 = d0Shadow.o(new aa.m[]{mVar37, mVar38, new aa.m("contexts", b4, (String) null, rVar, no.a.s(qv.b, new u0(100)), o32), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar39 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar40 = new aa.m("committedDate", l0.b(q6.a()), (String) null, rVar, rVar, rVar);
        q0 a14 = pv.a();
        k71.k.g(a14, "type");
        List o34 = d0Shadow.o(new aa.m[]{mVar39, mVar40, new aa.m("statusCheckRollup", a14, (String) null, rVar, rVar, o33), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar41 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        d4.Companion.getClass();
        List o35 = d0Shadow.o(new aa.m[]{mVar41, new aa.m("commit", l0.b(c4.a()), (String) null, rVar, rVar, o34), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar42 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar43 = new aa.m("totalCount", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        tl.Companion.getClass();
        List o36 = d0Shadow.o(new aa.m[]{mVar42, mVar43, new aa.m("nodes", l0.a(tl.a), (String) null, rVar, rVar, o35)});
        xm.Companion.getClass();
        aa.m mVar44 = new aa.m("state", l0.b(xm.s), (String) null, rVar, rVar, rVar);
        x a15 = q6.a();
        k71.k.g(a15, "type");
        List o37 = d0Shadow.o(new aa.m[]{mVar44, new aa.m("submittedAt", a15, (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar45 = new aa.m("__typename", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar46 = new aa.m("url", l0.b(lx.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar47 = new aa.m("id", l0.b(ob.a()), (String) null, rVar, rVar, rVar);
        hb.Companion.getClass();
        aa.s mVar48 = new aa.m("headRefOid", l0.b(hb.a), (String) null, rVar, rVar, rVar);
        eq.Companion.getClass();
        q0 a16 = dq.a();
        k71.k.g(a16, "type");
        aa.s mVar49 = new aa.m("headRepository", a16, (String) null, rVar, rVar, o);
        q0 a17 = dq.a();
        k71.k.g(a17, "type");
        aa.s mVar50 = new aa.m("baseRepository", a17, (String) null, rVar, rVar, o2);
        aa.s mVar51 = new aa.m("title", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        vb.Companion.getClass();
        x xVar = vb.a;
        aa.s mVar52 = new aa.m("titleHTML", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar53 = new aa.m("createdAt", l0.b(q6.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar54 = new aa.m("viewerCanDeleteHeadRef", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar55 = new aa.m("viewerDidAuthor", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar56 = new aa.m("viewerCanChangeBaseBranch", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar57 = new aa.m("locked", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        gn0.l.Companion.getClass();
        j0 a18 = gn0.k.a();
        k71.k.g(a18, "type");
        aa.s mVar58 = new aa.m("author", a18, (String) null, rVar, rVar, o4);
        x a19 = kb.a();
        k71.k.g(a19, "type");
        aa.s mVar59 = new aa.m("isReadByViewer", a19, (String) null, rVar, rVar, rVar);
        aa.r b5 = l0.b(xVar);
        ll.Companion.getClass();
        kl.a();
        a81.t tVar = ll.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        kl.b();
        aa.k kVar2 = new aa.k(ll.c, new u0(bool));
        kl.c();
        aa.k kVar3 = new aa.k(ll.d, new u0(bool));
        kl.d();
        a81.t tVar2 = ll.e;
        Boolean bool2 = Boolean.FALSE;
        aa.k kVar4 = new aa.k(tVar2, new u0(bool2));
        kl.e();
        aa.k kVar5 = new aa.k(ll.f, new u0(bool2));
        kl.f();
        aa.s mVar60 = new aa.m("bodyHTML", b5, "bodyHtml", rVar, d0Shadow.o(new aa.k[]{kVar, kVar2, kVar3, kVar4, kVar5, new aa.k(ll.g, new u0(bool))}), rVar);
        aa.s mVar61 = new aa.m("number", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        List o38 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list6 = te0.a.a;
        aa.s c = no.a.c(list6, "selections", "Comment", o38, list6);
        List o39 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list7 = bj0.a.a;
        aa.s c2 = no.a.c(list7, "selections", "Reactable", o39, list7);
        List o40 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list8 = zh0.a.a;
        aa.s c3 = no.a.c(list8, "selections", "OrgBlockable", o40, list8);
        List o42 = d0Shadow.o(new String[]{"Issue", "PullRequest"});
        List a20 = zd0.b.a();
        aa.s c4 = no.a.c(a20, "selections", "Assignable", o42, a20);
        hn.Companion.getClass();
        aa.s mVar62 = new aa.m("state", l0.b(hn.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar63 = new aa.m("changedFiles", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar64 = new aa.m("additions", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar65 = new aa.m("deletions", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        gg.Companion.getClass();
        aa.s mVar66 = new aa.m("mergeStateStatus", l0.b(gg.s), (String) null, rVar, rVar, rVar);
        j0 a22 = gn0.k.a();
        k71.k.g(a22, "type");
        aa.s mVar67 = new aa.m("mergedBy", a22, (String) null, rVar, rVar, o6);
        q0 a23 = c4.a();
        k71.k.g(a23, "type");
        aa.s mVar68 = new aa.m("mergeCommit", a23, (String) null, rVar, rVar, o7);
        yf.Companion.getClass();
        q0 q0Var3 = yf.c;
        k71.k.g(q0Var3, "type");
        aa.s mVar69 = new aa.m("mergeQueue", q0Var3, (String) null, rVar, rVar, o8);
        cg.Companion.getClass();
        q0 q0Var4 = cg.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar70 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, o9);
        pm.Companion.getClass();
        a0 a24 = om.a();
        k71.k.g(a24, "type");
        aa.s mVar71 = new aa.m("reviewDecision", a24, (String) null, rVar, rVar, rVar);
        aa.s mVar72 = new aa.m("isDraft", l0.b(kb.a()), (String) null, rVar, rVar, rVar);
        fs.Companion.getClass();
        aa.r b6 = l0.b(es.a());
        kl.l();
        aa.s mVar73 = new aa.m("requiredStatusChecks", b6, (String) null, rVar, no.a.s(ll.v, new u0(25)), o12);
        mo.Companion.getClass();
        q0 q0Var5 = mo.b;
        k71.k.g(q0Var5, "type");
        aa.s mVar74 = new aa.m("baseRef", q0Var5, (String) null, rVar, rVar, o14);
        aa.s mVar75 = new aa.m("baseRefName", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var5, "type");
        aa.s mVar76 = new aa.m("headRef", q0Var5, (String) null, rVar, rVar, o15);
        aa.s mVar77 = new aa.m("headRefName", l0.b(sb.a()), (String) null, rVar, rVar, rVar);
        List o43 = d0Shadow.o(new String[]{"Discussion", "Issue", "PullRequest"});
        List a25 = tg0.a.a();
        aa.s c5 = no.a.c(a25, "selections", "Labelable", o43, a25);
        kg.Companion.getClass();
        q0 q0Var6 = kg.a;
        k71.k.g(q0Var6, "type");
        aa.s mVar78 = new aa.m("milestone", q0Var6, (String) null, rVar, rVar, o16);
        rk.Companion.getClass();
        aa.r b7 = l0.b(qk.a());
        kl.k();
        aa.s mVar79 = new aa.m("projectCards", b7, (String) null, rVar, no.a.s(ll.u, new u0(25)), n5);
        rs.Companion.getClass();
        q0 a26 = qs.a();
        k71.k.g(a26, "type");
        kl.m();
        aa.s mVar80 = new aa.m("reviewRequests", a26, (String) null, rVar, no.a.s(ll.w, new u0(25)), n7);
        nm.Companion.getClass();
        q0 q0Var7 = nm.a;
        k71.k.g(q0Var7, "type");
        kl.j();
        aa.s mVar81 = new aa.m("latestReviews", q0Var7, (String) null, rVar, no.a.s(ll.r, new u0(25)), n9);
        k71.k.g(q0Var7, "type");
        kl.h();
        aa.k kVar6 = new aa.k(ll.p, new u0(25));
        kl.i();
        aa.s mVar82 = new aa.m("latestOpinionatedReviews", q0Var7, (String) null, rVar, d0Shadow.o(new aa.k[]{kVar6, new aa.k(ll.q, new u0(bool))}), n10);
        mw.Companion.getClass();
        aa.s mVar83 = new aa.m("suggestedReviewers", l0.b(l0.a(lw.a())), (String) null, rVar, rVar, o24);
        aa.s mVar84 = new aa.m("actionRequiredWorkflowRunCount", l0.b(qb.a()), (String) null, rVar, rVar, rVar);
        xl.Companion.getClass();
        aa.r b8 = l0.b(xl.a);
        kl.g();
        aa.s mVar85 = new aa.m("commits", b8, (String) null, rVar, no.a.s(ll.l, new u0(1)), o36);
        List n12 = d0Shadow.n("PullRequest");
        List a27 = zg0.a.a();
        aa.s c6 = no.a.c(a27, "selections", "PullRequest", n12, a27);
        List o44 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List a28 = tk0.a.a();
        aa.s c7 = no.a.c(a28, "selections", "Updatable", o44, a28);
        List n13 = d0Shadow.n("PullRequest");
        List a29 = q.a();
        aa.s c8 = no.a.c(a29, "selections", "PullRequest", n13, a29);
        k71.k.g(q0Var2, "type");
        aa.s mVar86 = new aa.m("viewerLatestReview", q0Var2, (String) null, rVar, rVar, o37);
        List n14 = d0Shadow.n("PullRequest");
        List list9 = a.a;
        a = d0Shadow.o(new aa.s[]{mVar45, mVar46, mVar47, mVar48, mVar49, mVar50, mVar51, mVar52, mVar53, mVar54, mVar55, mVar56, mVar57, mVar58, mVar59, mVar60, mVar61, c, c2, c3, c4, mVar62, mVar63, mVar64, mVar65, mVar66, mVar67, mVar68, mVar69, mVar70, mVar71, mVar72, mVar73, mVar74, mVar75, mVar76, mVar77, c5, mVar78, mVar79, mVar80, mVar81, mVar82, mVar83, mVar84, mVar85, c6, c7, c8, mVar86, no.a.c(list9, "selections", "PullRequest", n14, list9), new aa.m("viewerCanReopen", l0.b(kb.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanMergeAsAdmin", l0.b(kb.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanAssign", l0.b(kb.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanLabel", l0.b(kb.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanUpdateBranch", l0.b(kb.a()), (String) null, rVar, rVar, rVar)});
    }
}
