package dq;

import aa.q0;
import aa.u0;
import aa.x0;
import java.util.List;
import m10.ah;
import m10.cc0;
import m10.ch;
import m10.eh;
import m10.gf;
import m10.gh;
import m10.i30;
import m10.j10;
import m10.l40;
import m10.of;
import m10.qg;
import m10.sg;
import m10.wg;
import m10.y5;
import m10.yb0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class f0 {
    public static final List a;

    static {
        eh.Companion.getClass();
        aa.x xVar = eh.a;
        aa.r b = v8.l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.s mVar = new aa.m("__typename", b, (String) null, rVar, rVar, rVar);
        List n = sy.d0Shadow.n("FileLine");
        List list = vs.a.a;
        List r = x61.l.r(new aa.s[]{mVar, no.a.c(list, "selections", "FileLine", n, list)});
        gh.Companion.getClass();
        aa.x xVar2 = gh.a;
        k71.k.g(xVar2, "type");
        aa.m mVar2 = new aa.m("contentHTML", xVar2, (String) null, rVar, rVar, rVar);
        of.Companion.getClass();
        q0 q0Var = of.a;
        List r2 = x61.l.r(new aa.m[]{mVar2, new aa.m("fileLines", v8.l0.a(q0Var), "markDownFileLines", rVar, rVar, r)});
        cc0.Companion.getClass();
        aa.x xVar3 = cc0.a;
        k71.k.g(xVar3, "type");
        List r3 = x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("MarkdownFileType", sy.d0Shadow.n("MarkdownFileType"), r2), new aa.n("ImageFileType", sy.d0Shadow.n("ImageFileType"), sy.d0Shadow.n(new aa.m("url", xVar3, (String) null, rVar, rVar, rVar))), new aa.n("PdfFileType", sy.d0Shadow.n("PdfFileType"), sy.d0Shadow.n(new aa.m("url", xVar3, (String) null, rVar, rVar, rVar))), new aa.n("TextFileType", sy.d0Shadow.n("TextFileType"), sy.d0Shadow.n(new aa.m("fileLines", v8.l0.a(q0Var), "textFieldFileLines", rVar, rVar, x61.l.r(new aa.s[]{new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("FileLine", sy.d0Shadow.n("FileLine"), list)}))))});
        aa.m mVar3 = new aa.m("extension", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar4 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        gf.Companion.getClass();
        x0 x0Var = gf.a;
        k71.k.g(x0Var, "type");
        List r4 = x61.l.r(new aa.m[]{mVar3, mVar4, new aa.m("fileType", x0Var, (String) null, rVar, rVar, r3)});
        yb0.Companion.getClass();
        q0 q0Var2 = yb0.a;
        k71.k.g(q0Var2, "type");
        y5.Companion.getClass();
        aa.m mVar5 = new aa.m("file", q0Var2, (String) null, rVar, no.a.s(y5.e, new u0(new aa.t("path"))), r4);
        ah.Companion.getClass();
        aa.x xVar4 = ah.a;
        List r5 = x61.l.r(new aa.m[]{mVar5, new aa.m("id", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r6 = x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "AddedToProjectV2Event", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "BlockedByAddedEvent", "BlockedByRemovedEvent", "BlockingAddedEvent", "BlockingRemovedEvent", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedFromDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CopilotWorkFinishedEvent", "CopilotWorkFinishedFailureEvent", "CopilotWorkStartedEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueCommentPinnedEvent", "IssueCommentUnpinnedEvent", "IssueFieldAddedEvent", "IssueFieldChangedEvent", "IssueFieldDate", "IssueFieldDateValue", "IssueFieldNumber", "IssueFieldNumberValue", "IssueFieldRemovedEvent", "IssueFieldSingleSelect", "IssueFieldSingleSelectOption", "IssueFieldSingleSelectValue", "IssueFieldText", "IssueFieldTextValue", "IssueType", "IssueTypeAddedEvent", "IssueTypeChangedEvent", "IssueTypeRemovedEvent", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MarketplaceCategory", "MarketplaceListing", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OIDCProvider", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PinnedIssueComment", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2ItemStatusChangedEvent", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RemovedFromProjectV2Event", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryCustomProperty", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "SponsorsActivity", "SponsorsListing", "SponsorsListingFeaturedItem", "SponsorsTier", "Sponsorship", "SponsorshipNewsletter", "Status", "StatusCheck", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list2 = wx.a.a;
        List r7 = x61.l.r(new aa.s[]{mVar6, no.a.c(list2, "selections", "Node", r6, list2), new aa.n("Commit", sy.d0Shadow.n("Commit"), r5)});
        aa.m mVar7 = new aa.m("id", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        sg.Companion.getClass();
        List r8 = x61.l.r(new aa.m[]{mVar7, new aa.m("oid", v8.l0.b(sg.a), (String) null, rVar, rVar, rVar)});
        aa.m mVar8 = new aa.m("id", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("name", v8.l0.b(xVar), (String) null, rVar, rVar, rVar);
        wg.Companion.getClass();
        aa.x xVar5 = wg.a;
        aa.m mVar10 = new aa.m("viewerCanCommitToBranch", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        qg.Companion.getClass();
        aa.j0 j0Var = qg.a;
        k71.k.g(j0Var, "type");
        List r9 = x61.l.r(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("target", j0Var, (String) null, rVar, rVar, r8), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r11 = x61.l.r(new aa.m[]{new aa.m("id", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar), new aa.m("avatarUrl", v8.l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        aa.m mVar11 = new aa.m("id", v8.l0.b(xVar4), (String) null, rVar, rVar, rVar);
        ch.Companion.getClass();
        aa.x xVar6 = ch.a;
        k71.k.g(xVar6, "type");
        aa.m mVar12 = new aa.m("databaseId", xVar6, (String) null, rVar, rVar, rVar);
        i30.Companion.getClass();
        aa.m mVar13 = new aa.m("object", j0Var, "gitObject", rVar, no.a.s(i30.G, new u0(new aa.t("ref"))), r7);
        aa.m mVar14 = new aa.m("viewerCanPush", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar);
        j10.Companion.getClass();
        q0 q0Var3 = j10.e;
        k71.k.g(q0Var3, "type");
        aa.m mVar15 = new aa.m("ref", q0Var3, (String) null, rVar, no.a.s(i30.T, new u0(new aa.t("ref"))), r9);
        l40.Companion.getClass();
        a = x61.l.r(new aa.m[]{mVar11, mVar12, mVar13, mVar14, mVar15, new aa.m("owner", v8.l0.b(l40.e), (String) null, rVar, rVar, r11), new aa.m("isInOrganization", v8.l0.b(xVar5), (String) null, rVar, rVar, rVar), new aa.m("__typename", v8.l0.b(xVar), (String) null, rVar, rVar, rVar)});
    }
}
