package yt0;

import aa.j0;
import aa.q0;
import aa.t;
import aa.u0;
import aa.x;
import aa.x0;
import java.util.List;
import pz0.cc;
import pz0.d50;
import pz0.dt;
import pz0.h50;
import pz0.hm;
import pz0.hs;
import pz0.ht;
import pz0.jc;
import pz0.jx;
import pz0.ld;
import pz0.ls;
import pz0.mt;
import pz0.nm;
import pz0.ns;
import pz0.ny;
import pz0.o9;
import pz0.pd;
import pz0.pm;
import pz0.q9;
import pz0.rm;
import pz0.td;
import pz0.vd;
import pz0.x30;
import pz0.xd;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class e {
    public static final List a;

    static {
        xd.Companion.getClass();
        x xVar = xd.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        x xVar2 = td.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n = d0.n("Repository");
        List list = vu0.j.a;
        aa.s c = no.a.c(list, "selections", "Repository", n, list);
        List n2 = d0.n("Repository");
        List list2 = vu0.b.a;
        List r3 = x61.l.r(new aa.s[]{mVar2, c, no.a.c(list2, "selections", "Repository", n2, list2), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.m mVar3 = new aa.m("endCursor", xVar, (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        x xVar3 = pd.a;
        List r4 = x61.l.r(new aa.m[]{mVar3, new aa.m("hasNextPage", l0.b(xVar3), (String) null, rVar, rVar, rVar)});
        h50.Companion.getClass();
        x xVar4 = h50.a;
        k71.k.g(xVar4, "type");
        List r5 = x61.l.r(new aa.s[]{new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar), new aa.n("ImageFileType", d0.n("ImageFileType"), d0.n(new aa.m("url", xVar4, (String) null, rVar, rVar, rVar)))});
        aa.m mVar4 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        cc.Companion.getClass();
        x0 x0Var = cc.a;
        k71.k.g(x0Var, "type");
        List r6 = x61.l.r(new aa.m[]{mVar4, new aa.m("fileType", x0Var, (String) null, rVar, rVar, r5)});
        List n3 = d0.n(new aa.m("gitUrl", l0.b(xVar4), (String) null, rVar, rVar, rVar));
        aa.s mVar5 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r7 = x61.l.r(new String[]{"ImageFileType", "MarkdownFileType", "PdfFileType", "TextFileType"});
        List list3 = c.a;
        List r8 = x61.l.r(new aa.s[]{mVar5, no.a.c(list3, "selections", "File", r7, list3)});
        aa.m mVar6 = new aa.m("path", xVar, (String) null, rVar, rVar, rVar);
        aa.m mVar7 = new aa.m("isGenerated", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        x30.Companion.getClass();
        q0 q0Var = x30.a;
        k71.k.g(q0Var, "type");
        aa.m mVar8 = new aa.m("submodule", q0Var, (String) null, rVar, rVar, n3);
        vd.Companion.getClass();
        x xVar5 = vd.a;
        k71.k.g(xVar5, "type");
        List r9 = x61.l.r(new aa.m[]{mVar6, mVar7, mVar8, new aa.m("lineCount", xVar5, (String) null, rVar, rVar, rVar), new aa.m("fileType", x0Var, (String) null, rVar, rVar, r8)});
        aa.s mVar9 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n4 = d0.n("DiffLine");
        List list4 = xq0.a.a;
        List r10 = x61.l.r(new aa.s[]{mVar9, no.a.c(list4, "selections", "DiffLine", n4, list4)});
        aa.m mVar10 = new aa.m("linesAdded", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.m mVar11 = new aa.m("linesDeleted", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        d50.Companion.getClass();
        q0 q0Var2 = d50.a;
        k71.k.g(q0Var2, "type");
        aa.m mVar12 = new aa.m("oldTreeEntry", q0Var2, (String) null, rVar, rVar, r6);
        aa.m mVar13 = new aa.m("newTreeEntry", q0Var2, (String) null, rVar, rVar, r9);
        q9.Companion.getClass();
        aa.m mVar14 = new aa.m("diffLines", l0.a(q9.a), (String) null, rVar, rVar, r10);
        aa.m mVar15 = new aa.m("isBinary", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.m mVar16 = new aa.m("isLargeDiff", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.m mVar17 = new aa.m("isSubmodule", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        rm.Companion.getClass();
        List r12 = x61.l.r(new aa.m[]{mVar10, mVar11, mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, new aa.m("status", l0.b(rm.s), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        hm.Companion.getClass();
        aa.m mVar18 = new aa.m("pageInfo", l0.b(hm.a), (String) null, rVar, rVar, r4);
        nm.Companion.getClass();
        List r13 = x61.l.r(new aa.m[]{mVar18, new aa.m("nodes", l0.a(nm.b), (String) null, rVar, rVar, r12)});
        pm.Companion.getClass();
        aa.r b2 = l0.b(pm.a);
        o9.Companion.getClass();
        List n5 = d0.n(new aa.m("patches", b2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(o9.b, new u0(new t("after"))), new aa.k(o9.c, new u0(50))}), r13));
        List n6 = d0.n(new aa.m("totalCount", l0.b(xVar5), (String) null, rVar, rVar, rVar));
        aa.m mVar19 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ht.Companion.getClass();
        aa.r b3 = l0.b(ht.a);
        dt.Companion.getClass();
        List n7 = d0.n(new aa.m("nodes", l0.a(dt.d), (String) null, rVar, rVar, x61.l.r(new aa.m[]{mVar19, new aa.m("comments", b3, (String) null, rVar, no.a.s(dt.a, new u0(1)), n6), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)})));
        jc.Companion.getClass();
        List r14 = x61.l.r(new aa.m[]{new aa.m("viewerViewedState", l0.b(jc.s), (String) null, rVar, rVar, rVar), new aa.m("path", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        ls.Companion.getClass();
        List n8 = d0.n(new aa.m("nodes", l0.a(ls.a), (String) null, rVar, rVar, r14));
        aa.s mVar20 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar21 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        ld.Companion.getClass();
        aa.s mVar22 = new aa.m("headRefOid", l0.b(ld.a), (String) null, rVar, rVar, rVar);
        aa.s mVar23 = new aa.m("viewerCanEditFiles", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("baseRefName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar25 = new aa.m("headRefName", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("additions", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        aa.s mVar27 = new aa.m("deletions", l0.b(xVar5), (String) null, rVar, rVar, rVar);
        jx.Companion.getClass();
        q0 q0Var3 = jx.t0;
        k71.k.g(q0Var3, "type");
        aa.s mVar28 = new aa.m("headRepository", q0Var3, (String) null, rVar, rVar, r);
        ny.Companion.getClass();
        j0 j0Var = ny.e;
        k71.k.g(j0Var, "type");
        aa.s mVar29 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar30 = new aa.m("repository", l0.b(q0Var3), (String) null, rVar, rVar, r3);
        q0 q0Var4 = o9.d;
        k71.k.g(q0Var4, "type");
        aa.s mVar31 = new aa.m("diff", q0Var4, (String) null, rVar, rVar, n5);
        List n9 = d0.n("PullRequest");
        List list5 = d.a;
        aa.s c2 = no.a.c(list5, "selections", "PullRequest", n9, list5);
        mt.Companion.getClass();
        q0 q0Var5 = mt.a;
        k71.k.g(q0Var5, "type");
        hs.Companion.getClass();
        aa.s mVar32 = new aa.m("reviews", q0Var5, "pendingReviews", rVar, x61.l.r(new aa.k[]{new aa.k(hs.A, new u0(1)), new aa.k(hs.B, new u0(d0.n("PENDING")))}), n7);
        ns.Companion.getClass();
        q0 q0Var6 = ns.a;
        k71.k.g(q0Var6, "type");
        a = x61.l.r(new aa.s[]{mVar20, mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, c2, mVar32, new aa.m("files", q0Var6, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(hs.m, new u0(new t("after"))), new aa.k(hs.n, new u0(50))}), n8)});
    }
}
