package yt0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.c90;
import pz0.e7;
import pz0.f30;
import pz0.f40;
import pz0.gu;
import pz0.h50;
import pz0.hs;
import pz0.jx;
import pz0.ki;
import pz0.n30;
import pz0.ny;
import pz0.o7;
import pz0.oi;
import pz0.ot;
import pz0.pd;
import pz0.ps;
import pz0.s4;
import pz0.td;
import pz0.ts;
import pz0.vd;
import pz0.ve;
import pz0.w80;
import pz0.xd;
import pz0.zd;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class h {
    public static final List a;

    static {
        xd.Companion.getClass();
        x xVar = xd.a;
        aa.r b = l0.b(xVar);
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("name", b, (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        x xVar2 = td.a;
        List r = x61.l.r(new aa.m[]{mVar, new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r2 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        List r3 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar2 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("name", l0.b(xVar), (String) null, rVar, rVar, rVar);
        f40.Companion.getClass();
        a0 a0Var = f40.s;
        k71.k.g(a0Var, "type");
        aa.m mVar4 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        e7.Companion.getClass();
        aa.m mVar5 = new aa.m("viewerSubscriptionTypes", l0.a(l0.b(e7.s)), (String) null, rVar, rVar, rVar);
        ny.Companion.getClass();
        j0 j0Var = ny.e;
        List r4 = x61.l.r(new aa.m[]{mVar2, mVar3, mVar4, mVar5, new aa.m("owner", l0.b(j0Var), (String) null, rVar, rVar, r3), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r5 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.a.a;
        List r6 = x61.l.r(new aa.s[]{mVar6, no.a.c(list, "selections", "Actor", r5, list), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        vd.Companion.getClass();
        x xVar3 = vd.a;
        aa.m mVar7 = new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        w80.Companion.getClass();
        List r7 = x61.l.r(new aa.m[]{mVar7, new aa.m("nodes", l0.a(w80.W), (String) null, rVar, rVar, r6)});
        aa.m mVar8 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        n30.Companion.getClass();
        List r8 = x61.l.r(new aa.m[]{mVar8, new aa.m("state", l0.b(n30.s), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar9 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        f30.Companion.getClass();
        q0 q0Var = f30.c;
        k71.k.g(q0Var, "type");
        List r9 = x61.l.r(new aa.m[]{mVar9, new aa.m("statusCheckRollup", q0Var, (String) null, rVar, rVar, r8), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.m mVar10 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s4.Companion.getClass();
        List r10 = x61.l.r(new aa.m[]{mVar10, new aa.m("commit", l0.b(s4.j), (String) null, rVar, rVar, r9), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        ps.Companion.getClass();
        List n = d0Shadow.n(new aa.m("nodes", l0.a(ps.a), (String) null, rVar, rVar, r10));
        List n2 = d0Shadow.n(new aa.m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar));
        List r12 = x61.l.r(new aa.m[]{new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new aa.m("position", l0.b(xVar3), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        aa.s mVar11 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List n3 = d0Shadow.n("MergeQueue");
        List list2 = ts0.c.a;
        List r13 = x61.l.r(new aa.s[]{mVar11, no.a.c(list2, "selections", "MergeQueue", n3, list2), new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        aa.s mVar12 = new aa.m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        aa.s mVar13 = new aa.m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        x xVar4 = pd.a;
        aa.s mVar14 = new aa.m("isDraft", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        aa.s mVar15 = new aa.m("title", l0.b(xVar), (String) null, rVar, rVar, rVar);
        zd.Companion.getClass();
        aa.s mVar16 = new aa.m("titleHTML", l0.b(zd.a), "titleHTMLString", rVar, rVar, rVar);
        aa.s mVar17 = new aa.m("number", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        aa.s mVar18 = new aa.m("createdAt", l0.b(o7.a), (String) null, rVar, rVar, rVar);
        jx.Companion.getClass();
        q0 q0Var2 = jx.t0;
        k71.k.g(q0Var2, "type");
        aa.s mVar19 = new aa.m("headRepository", q0Var2, (String) null, rVar, rVar, r);
        aa.s mVar20 = new aa.m("headRepositoryOwner", j0Var, (String) null, rVar, rVar, r2);
        aa.s mVar21 = new aa.m("isReadByViewer", xVar4, (String) null, rVar, rVar, rVar);
        aa.s mVar22 = new aa.m("totalCommentsCount", xVar3, (String) null, rVar, rVar, rVar);
        List r14 = x61.l.r(new String[]{"Discussion", "Issue", "PullRequest"});
        List list3 = ds0.a.a;
        aa.s c = no.a.c(list3, "selections", "Labelable", r14, list3);
        gu.Companion.getClass();
        aa.s mVar23 = new aa.m("state", l0.b(gu.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar24 = new aa.m("repository", l0.b(q0Var2), (String) null, rVar, rVar, r4);
        h50.Companion.getClass();
        aa.s mVar25 = new aa.m("url", l0.b(h50.a), (String) null, rVar, rVar, rVar);
        aa.s mVar26 = new aa.m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar);
        ot.Companion.getClass();
        a0 a0Var2 = ot.s;
        k71.k.g(a0Var2, "type");
        aa.s mVar27 = new aa.m("reviewDecision", a0Var2, (String) null, rVar, rVar, rVar);
        c90.Companion.getClass();
        aa.r b2 = l0.b(c90.a);
        hs.Companion.getClass();
        aa.s mVar28 = new aa.m("assignees", b2, (String) null, rVar, no.a.s(hs.a, new u0(25)), r7);
        ts.Companion.getClass();
        aa.s mVar29 = new aa.m("commits", l0.b(ts.a), (String) null, rVar, no.a.s(hs.l, new u0(1)), n);
        ve.Companion.getClass();
        q0 q0Var3 = ve.a;
        k71.k.g(q0Var3, "type");
        aa.s mVar30 = new aa.m("closingIssuesReferences", q0Var3, (String) null, rVar, rVar, n2);
        aa.s mVar31 = new aa.m("isInMergeQueue", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        oi.Companion.getClass();
        q0 q0Var4 = oi.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar32 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, r12);
        ki.Companion.getClass();
        q0 q0Var5 = ki.c;
        k71.k.g(q0Var5, "type");
        aa.s mVar33 = new aa.m("mergeQueue", q0Var5, (String) null, rVar, rVar, r13);
        List n4 = d0Shadow.n("PullRequest");
        List list4 = r.a;
        a = x61.l.r(new aa.s[]{mVar12, mVar13, mVar14, mVar15, mVar16, mVar17, mVar18, mVar19, mVar20, mVar21, mVar22, c, mVar23, mVar24, mVar25, mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, mVar33, no.a.c(list4, "selections", "PullRequest", n4, list4)});
    }

    public static List a() {
        return a;
    }
}
