package yt0;

import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.hm;
import pz0.hs;
import pz0.ku;
import pz0.mu;
import pz0.pd;
import pz0.td;
import pz0.vd;
import pz0.xd;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class m {
    public static final List a;

    static {
        pd.Companion.getClass();
        x xVar = pd.a;
        aa.r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        aa.m mVar = new aa.m("hasPreviousPage", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        x xVar2 = xd.a;
        k71.k.g(xVar2, "type");
        aa.m mVar2 = new aa.m("startCursor", xVar2, (String) null, rVar, rVar, rVar);
        aa.m mVar3 = new aa.m("hasNextPage", l0.b(xVar), (String) null, rVar, rVar, rVar);
        k71.k.g(xVar2, "type");
        List r = x61.l.r(new aa.m[]{mVar, mVar2, mVar3, new aa.m("endCursor", xVar2, (String) null, rVar, rVar, rVar)});
        aa.s mVar4 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueType", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list = lw0.a.a;
        aa.s c = no.a.c(list, "selections", "Node", r2, list);
        List n = d0.n("IssueComment");
        List list2 = xr0.a.a;
        aa.s c2 = no.a.c(list2, "selections", "IssueComment", n, list2);
        List n2 = d0.n("RenamedTitleEvent");
        List list3 = nu0.a.a;
        aa.s c3 = no.a.c(list3, "selections", "RenamedTitleEvent", n2, list3);
        List n3 = d0.n("AssignedEvent");
        List list4 = hp0.a.a;
        aa.s c4 = no.a.c(list4, "selections", "AssignedEvent", n3, list4);
        List n4 = d0.n("UnassignedEvent");
        List list5 = uv0.a.a;
        aa.s c5 = no.a.c(list5, "selections", "UnassignedEvent", n4, list5);
        List n5 = d0.n("ClosedEvent");
        List list6 = xp0.a.a;
        aa.s c6 = no.a.c(list6, "selections", "ClosedEvent", n5, list6);
        List n6 = d0.n("ReopenedEvent");
        List list7 = pu0.a.a;
        aa.s c7 = no.a.c(list7, "selections", "ReopenedEvent", n6, list7);
        List n7 = d0.n("LabeledEvent");
        List list8 = fs0.a.a;
        aa.s c8 = no.a.c(list8, "selections", "LabeledEvent", n7, list8);
        List n8 = d0.n("UnlabeledEvent");
        List list9 = wv0.a.a;
        aa.s c9 = no.a.c(list9, "selections", "UnlabeledEvent", n8, list9);
        List n9 = d0.n("LockedEvent");
        List list10 = ns0.a.a;
        aa.s c10 = no.a.c(list10, "selections", "LockedEvent", n9, list10);
        List n10 = d0.n("UnlockedEvent");
        List list11 = yv0.a.a;
        aa.s c12 = no.a.c(list11, "selections", "UnlockedEvent", n10, list11);
        List n12 = d0.n("MilestonedEvent");
        List list12 = zs0.a.a;
        aa.s c13 = no.a.c(list12, "selections", "MilestonedEvent", n12, list12);
        List n13 = d0.n("DemilestonedEvent");
        List list13 = pq0.a.a;
        aa.s c14 = no.a.c(list13, "selections", "DemilestonedEvent", n13, list13);
        List n14 = d0.n("CrossReferencedEvent");
        List list14 = lq0.a.a;
        aa.s c15 = no.a.c(list14, "selections", "CrossReferencedEvent", n14, list14);
        List n15 = d0.n("ReferencedEvent");
        List list15 = lu0.a.a;
        aa.s c16 = no.a.c(list15, "selections", "ReferencedEvent", n15, list15);
        List n16 = d0.n("MergedEvent");
        List list16 = vs0.a.a;
        aa.s c17 = no.a.c(list16, "selections", "MergedEvent", n16, list16);
        List n17 = d0.n("PullRequestCommit");
        List list17 = bu0.a.a;
        aa.s c18 = no.a.c(list17, "selections", "PullRequestCommit", n17, list17);
        List n18 = d0.n("HeadRefDeletedEvent");
        List list18 = pr0.a.a;
        aa.s c19 = no.a.c(list18, "selections", "HeadRefDeletedEvent", n18, list18);
        List n19 = d0.n("HeadRefRestoredEvent");
        List list19 = tr0.a.a;
        aa.s c20 = no.a.c(list19, "selections", "HeadRefRestoredEvent", n19, list19);
        List n20 = d0.n("ReviewRequestedEvent");
        List list20 = gv0.a.a;
        aa.s c22 = no.a.c(list20, "selections", "ReviewRequestedEvent", n20, list20);
        List n22 = d0.n("ReviewRequestRemovedEvent");
        List list21 = ev0.a.a;
        aa.s c23 = no.a.c(list21, "selections", "ReviewRequestRemovedEvent", n22, list21);
        List n23 = d0.n("ReviewDismissedEvent");
        List list22 = av0.a.a;
        aa.s c24 = no.a.c(list22, "selections", "ReviewDismissedEvent", n23, list22);
        List n24 = d0.n("PullRequestReview");
        List list23 = du0.a.a;
        aa.s c25 = no.a.c(list23, "selections", "PullRequestReview", n24, list23);
        List n25 = d0.n("ReadyForReviewEvent");
        List list24 = ju0.a.a;
        aa.s c26 = no.a.c(list24, "selections", "ReadyForReviewEvent", n25, list24);
        List n26 = d0.n("ConvertToDraftEvent");
        List list25 = hq0.a.a;
        aa.s c27 = no.a.c(list25, "selections", "ConvertToDraftEvent", n26, list25);
        List n27 = d0.n("DeployedEvent");
        List list26 = rq0.a.a;
        aa.s c28 = no.a.c(list26, "selections", "DeployedEvent", n27, list26);
        List n28 = d0.n("CommentDeletedEvent");
        List list27 = bq0.a.a;
        aa.s c29 = no.a.c(list27, "selections", "CommentDeletedEvent", n28, list27);
        List n29 = d0.n("HeadRefForcePushedEvent");
        List list28 = rr0.a.a;
        aa.s c30 = no.a.c(list28, "selections", "HeadRefForcePushedEvent", n29, list28);
        List n30 = d0.n("TransferredEvent");
        List list29 = sv0.a.a;
        aa.s c32 = no.a.c(list29, "selections", "TransferredEvent", n30, list29);
        List n32 = d0.n("BaseRefChangedEvent");
        List list30 = tp0.a.a;
        aa.s c33 = no.a.c(list30, "selections", "BaseRefChangedEvent", n32, list30);
        List n33 = d0.n("MarkedAsDuplicateEvent");
        List list31 = ps0.a.a;
        aa.s c34 = no.a.c(list31, "selections", "MarkedAsDuplicateEvent", n33, list31);
        List n34 = d0.n("DeploymentEnvironmentChangedEvent");
        List list32 = tq0.a.a;
        aa.s c35 = no.a.c(list32, "selections", "DeploymentEnvironmentChangedEvent", n34, list32);
        List n35 = d0.n("AutoMergeEnabledEvent");
        List list33 = lp0.a.a;
        aa.s c36 = no.a.c(list33, "selections", "AutoMergeEnabledEvent", n35, list33);
        List n36 = d0.n("AutoSquashEnabledEvent");
        List list34 = pp0.a.a;
        aa.s c37 = no.a.c(list34, "selections", "AutoSquashEnabledEvent", n36, list34);
        List n37 = d0.n("AutoRebaseEnabledEvent");
        List list35 = np0.a.a;
        aa.s c38 = no.a.c(list35, "selections", "AutoRebaseEnabledEvent", n37, list35);
        List n38 = d0.n("AutoMergeDisabledEvent");
        List list36 = jp0.a.a;
        aa.s c39 = no.a.c(list36, "selections", "AutoMergeDisabledEvent", n38, list36);
        List n39 = d0.n("UserBlockedEvent");
        List list37 = jw0.a.a;
        aa.s c40 = no.a.c(list37, "selections", "UserBlockedEvent", n39, list37);
        List n40 = d0.n("AddedToMergeQueueEvent");
        List list38 = ts0.a.a;
        aa.s c42 = no.a.c(list38, "selections", "AddedToMergeQueueEvent", n40, list38);
        List n42 = d0.n("RemovedFromMergeQueueEvent");
        List list39 = ts0.d.a;
        aa.s c43 = no.a.c(list39, "selections", "RemovedFromMergeQueueEvent", n42, list39);
        List n43 = d0.n("ConnectedEvent");
        List list40 = fq0.a.a;
        aa.s c44 = no.a.c(list40, "selections", "ConnectedEvent", n43, list40);
        List n44 = d0.n("DisconnectedEvent");
        List list41 = zq0.a.a;
        aa.s c45 = no.a.c(list41, "selections", "DisconnectedEvent", n44, list41);
        List n45 = d0.n("AutomaticBaseChangeSucceededEvent");
        List list42 = rp0.a.a;
        List r3 = x61.l.r(new aa.s[]{mVar4, c, c2, c3, c4, c5, c6, c7, c8, c9, c10, c12, c13, c14, c15, c16, c17, c18, c19, c20, c22, c23, c24, c25, c26, c27, c28, c29, c30, c32, c33, c34, c35, c36, c37, c38, c39, c40, c42, c43, c44, c45, no.a.c(list42, "selections", "AutomaticBaseChangeSucceededEvent", n45, list42)});
        aa.m mVar5 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        vd.Companion.getClass();
        aa.m mVar6 = new aa.m("beforeFocusCount", l0.b(vd.a), (String) null, rVar, rVar, rVar);
        hm.Companion.getClass();
        aa.m mVar7 = new aa.m("pageInfo", l0.b(hm.a), (String) null, rVar, rVar, r);
        ku.Companion.getClass();
        List r4 = x61.l.r(new aa.m[]{mVar5, mVar6, mVar7, new aa.m("nodes", l0.a(ku.a), (String) null, rVar, rVar, r3)});
        aa.m mVar8 = new aa.m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        td.Companion.getClass();
        aa.m mVar9 = new aa.m("id", l0.b(td.a), (String) null, rVar, rVar, rVar);
        mu.Companion.getClass();
        aa.r b2 = l0.b(mu.a);
        hs.Companion.getClass();
        a = x61.l.r(new aa.m[]{mVar8, mVar9, new aa.m("timelineItems", b2, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(hs.E, new u0(new t("after"))), new aa.k(hs.F, new u0(new t("before"))), new aa.k(hs.G, new u0(new t("desiredAfterCount"))), new aa.k(hs.H, new u0(new t("focusId"))), new aa.k(hs.I, new u0(x61.l.r(new String[]{"ISSUE_COMMENT", "RENAMED_TITLE_EVENT", "ASSIGNED_EVENT", "UNASSIGNED_EVENT", "CLOSED_EVENT", "REOPENED_EVENT", "LABELED_EVENT", "UNLABELED_EVENT", "LOCKED_EVENT", "UNLOCKED_EVENT", "MILESTONED_EVENT", "DEMILESTONED_EVENT", "CROSS_REFERENCED_EVENT", "REFERENCED_EVENT", "MERGED_EVENT", "PULL_REQUEST_COMMIT", "HEAD_REF_DELETED_EVENT", "REVIEW_REQUESTED_EVENT", "REVIEW_REQUEST_REMOVED_EVENT", "REVIEW_DISMISSED_EVENT", "PULL_REQUEST_REVIEW", "READY_FOR_REVIEW_EVENT", "CONVERT_TO_DRAFT_EVENT", "COMMENT_DELETED_EVENT", "DEPLOYED_EVENT", "HEAD_REF_FORCE_PUSHED_EVENT", "HEAD_REF_RESTORED_EVENT", "BASE_REF_CHANGED_EVENT", "MARKED_AS_DUPLICATE_EVENT", "DEPLOYMENT_ENVIRONMENT_CHANGED_EVENT", "AUTO_MERGE_DISABLED_EVENT", "AUTO_MERGE_ENABLED_EVENT", "AUTO_REBASE_ENABLED_EVENT", "AUTO_SQUASH_ENABLED_EVENT", "USER_BLOCKED_EVENT", "ADDED_TO_MERGE_QUEUE_EVENT", "REMOVED_FROM_MERGE_QUEUE_EVENT", "CONNECTED_EVENT", "DISCONNECTED_EVENT", "AUTOMATIC_BASE_CHANGE_SUCCEEDED_EVENT"}))), new aa.k(hs.J, new u0(new t("desiredBeforeCount")))}), r4)});
    }
}
