package yt0;

import aa.a0;
import aa.j0;
import aa.q0;
import aa.t;
import aa.u0;
import aa.x;
import java.util.List;
import pz0.a00;
import pz0.a3;
import pz0.b00;
import pz0.dt;
import pz0.e30;
import pz0.f30;
import pz0.g30;
import pz0.g40;
import pz0.g50;
import pz0.ga0;
import pz0.gs;
import pz0.gu;
import pz0.h30;
import pz0.h40;
import pz0.h50;
import pz0.ha0;
import pz0.hs;
import pz0.i30;
import pz0.ix;
import pz0.j30;
import pz0.jx;
import pz0.k3;
import pz0.k30;
import pz0.ki;
import pz0.l30;
import pz0.ld;
import pz0.mt;
import pz0.mv;
import pz0.mz;
import pz0.n30;
import pz0.n7;
import pz0.nt;
import pz0.nz;
import pz0.o7;
import pz0.od;
import pz0.oi;
import pz0.ot;
import pz0.oz;
import pz0.pd;
import pz0.ps;
import pz0.pz;
import pz0.qv;
import pz0.r4;
import pz0.s4;
import pz0.sd;
import pz0.si;
import pz0.td;
import pz0.ts;
import pz0.ud;
import pz0.v0;
import pz0.v80;
import pz0.vd;
import pz0.w0;
import pz0.w80;
import pz0.wd;
import pz0.wt;
import pz0.xd;
import pz0.y2;
import pz0.y90;
import pz0.yd;
import pz0.yi;
import pz0.yz;
import pz0.z2;
import pz0.zd;
import pz0.zz;
import sy.d0Shadow;
import v8.l0;

/* loaded from: /home/user/work/p/classes4.dex */
public abstract class o {
    public static final List a;

    static {
        td.Companion.getClass();
        aa.r b = l0.b(sd.a());
        x61.rShadow rVar = x61.rShadow.r;
        aa.m mVar = new aa.m("id", b, (String) null, rVar, rVar, rVar);
        xd.Companion.getClass();
        List o = d0Shadow.o(new aa.m[]{mVar, new aa.m("nameWithOwner", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        List o2 = d0Shadow.o(new aa.m[]{new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("nameWithOwner", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar2 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar3 = new aa.m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o3 = d0Shadow.o(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = dp0.b.a;
        List o4 = d0Shadow.o(new aa.s[]{mVar2, mVar3, no.a.c(list, "selections", "Actor", o3, list)});
        aa.s mVar4 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o5 = d0Shadow.o(new String[]{"Achievement", "AchievementTier", "AddedToMergeQueueEvent", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DependencyGraphManifest", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseMemberInvitation", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "IssueType", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MemberFeatureRequestNotification", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergeQueue", "MergeQueueEntry", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessBlockedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgOauthAppAccessUnblockedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "ParentIssueAddedEvent", "ParentIssueRemovedEvent", "Patch", "PinnedDiscussion", "PinnedEnvironment", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2StatusUpdate", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Query", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromMergeQueueEvent", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryRuleset", "RepositoryRulesetBypassActor", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubIssueAddedEvent", "SubIssueRemovedEvent", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserNamespaceRepository", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List a2 = lw0.a.a();
        List o6 = d0Shadow.o(new aa.s[]{mVar4, no.a.c(a2, "selections", "Node", o5, a2), new aa.m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar5 = new aa.m("abbreviatedOid", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        o7.Companion.getClass();
        List o7 = d0Shadow.o(new aa.m[]{mVar5, new aa.m("committedDate", l0.b(n7.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar6 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List n = d0Shadow.n("MergeQueue");
        List list2 = ts0.c.a;
        List o8 = d0Shadow.o(new aa.s[]{mVar6, no.a.c(list2, "selections", "MergeQueue", n, list2), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar7 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List n2 = d0Shadow.n("MergeQueueEntry");
        List list3 = ts0.b.a;
        List o9 = d0Shadow.o(new aa.s[]{mVar7, no.a.c(list3, "selections", "MergeQueueEntry", n2, list3), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar8 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar9 = new aa.m("context", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        n30.Companion.getClass();
        a0 a0Var = n30.s;
        aa.m mVar10 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        x a3 = wd.a();
        k71.k.g(a3, "type");
        List o10 = d0Shadow.o(new aa.m[]{mVar8, mVar9, mVar10, new aa.m("description", a3, (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        vd.Companion.getClass();
        aa.m mVar11 = new aa.m("totalCount", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        nz.Companion.getClass();
        List o12 = d0Shadow.o(new aa.m[]{mVar11, new aa.m("nodes", l0.a(mz.a()), (String) null, rVar, rVar, o10)});
        x a4 = ud.a();
        k71.k.g(a4, "type");
        aa.m mVar12 = new aa.m("recommendedApprovingReviewCount", a4, (String) null, rVar, rVar, rVar);
        pd.Companion.getClass();
        List o13 = d0Shadow.o(new aa.m[]{mVar12, new aa.m("requiresCodeOwnerReviews", l0.b(od.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerAllowedToDismissReviews", l0.b(od.a()), (String) null, rVar, rVar, rVar)});
        qv.Companion.getClass();
        q0 q0Var = qv.a;
        k71.k.g(q0Var, "type");
        List o14 = d0Shadow.o(new aa.m[]{new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, o13), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        List n3 = d0Shadow.n(new aa.m("viewerCanPush", l0.b(od.a()), (String) null, rVar, rVar, rVar));
        aa.m mVar13 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var, "type");
        List o15 = d0Shadow.o(new aa.m[]{mVar13, new aa.m("refUpdateRule", q0Var, (String) null, rVar, rVar, n3), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar14 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List n4 = d0Shadow.n("Milestone");
        List list4 = xs0.a.a;
        List o16 = d0Shadow.o(new aa.s[]{mVar14, no.a.c(list4, "selections", "Milestone", n4, list4), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar15 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List n5 = d0Shadow.n("ReviewRequest");
        List a5 = cv0.a.a();
        List o17 = d0Shadow.o(new aa.s[]{mVar15, no.a.c(a5, "selections", "ReviewRequest", n5, a5), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        zz.Companion.getClass();
        List n6 = d0Shadow.n(new aa.m("nodes", l0.a(yz.a()), (String) null, rVar, rVar, o17));
        aa.s mVar16 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List n7 = d0Shadow.n("PullRequestReview");
        List list5 = du0.b.a;
        List o18 = d0Shadow.o(new aa.s[]{mVar16, no.a.c(list5, "selections", "PullRequestReview", n7, list5), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        dt.Companion.getClass();
        q0 q0Var2 = dt.d;
        List n8 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, o18));
        List n9 = d0Shadow.n(new aa.m("nodes", l0.a(q0Var2), (String) null, rVar, rVar, d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar), no.a.c(list5, "selections", "PullRequestReview", d0Shadow.n("PullRequestReview"), list5), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)})));
        List o19 = d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new aa.n("User", d0Shadow.n("User"), d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("login", l0.b(wd.a()), (String) null, rVar, rVar, rVar), no.a.c(list, "selections", "Actor", d0Shadow.o(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"}), list)})), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar17 = new aa.m("isAuthor", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar18 = new aa.m("isCommenter", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        w80.Companion.getClass();
        List o20 = d0Shadow.o(new aa.m[]{mVar17, mVar18, new aa.m("reviewer", l0.b(v80.a()), (String) null, rVar, rVar, o19)});
        aa.m mVar19 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar20 = new aa.m("context", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar21 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        h50.Companion.getClass();
        x a6 = g50.a();
        k71.k.g(a6, "type");
        aa.m mVar22 = new aa.m("avatarUrl", a6, (String) null, rVar, rVar, rVar);
        x a7 = wd.a();
        k71.k.g(a7, "type");
        aa.m mVar23 = new aa.m("description", a7, (String) null, rVar, rVar, rVar);
        x a8 = g50.a();
        k71.k.g(a8, "type");
        aa.m mVar24 = new aa.m("targetUrl", a8, (String) null, rVar, rVar, rVar);
        aa.r b2 = l0.b(od.a());
        l30.Companion.getClass();
        k30.a();
        List o22 = d0Shadow.o(new aa.m[]{mVar19, mVar20, mVar21, mVar22, mVar23, mVar24, new aa.m("isRequired", b2, (String) null, rVar, no.a.s(l30.b, new u0(new t("numberNullableBug"))), rVar)});
        List o23 = d0Shadow.o(new aa.m[]{new aa.m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        y90.Companion.getClass();
        List o24 = d0Shadow.o(new aa.m[]{new aa.m("workflow", l0.b(y90.e), (String) null, rVar, rVar, o23), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        List o25 = d0Shadow.o(new aa.m[]{new aa.m("logoUrl", l0.b(g50.a()), (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        ha0.Companion.getClass();
        q0 a9 = ga0.a();
        k71.k.g(a9, "type");
        aa.m mVar25 = new aa.m("workflowRun", a9, (String) null, rVar, rVar, o24);
        w0.Companion.getClass();
        q0 a10 = v0.a();
        k71.k.g(a10, "type");
        List o26 = d0Shadow.o(new aa.m[]{mVar25, new aa.m("app", a10, (String) null, rVar, rVar, o25), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar26 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        y2.Companion.getClass();
        a0 a0Var2 = y2.s;
        k71.k.g(a0Var2, "type");
        aa.m mVar27 = new aa.m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        aa.m mVar28 = new aa.m("name", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar29 = new aa.m("duration", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        x a12 = wd.a();
        k71.k.g(a12, "type");
        aa.m mVar30 = new aa.m("summary", a12, (String) null, rVar, rVar, rVar);
        aa.m mVar31 = new aa.m("permalink", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        k3.Companion.getClass();
        aa.m mVar32 = new aa.m("checkSuite", l0.b(k3.f), (String) null, rVar, rVar, o26);
        aa.r b3 = l0.b(od.a());
        a3.Companion.getClass();
        z2.a();
        List o27 = d0Shadow.o(new aa.s[]{new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar), new aa.n("StatusContext", d0Shadow.n("StatusContext"), o22), new aa.n("CheckRun", d0Shadow.n("CheckRun"), d0Shadow.o(new aa.m[]{mVar26, mVar27, mVar28, mVar29, mVar30, mVar31, mVar32, new aa.m("isRequired", b3, (String) null, rVar, no.a.s(a3.b, new u0(new t("numberNullableBug"))), rVar)}))});
        aa.m mVar33 = new aa.m("totalCount", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        h30.Companion.getClass();
        List o28 = d0Shadow.o(new aa.m[]{mVar33, new aa.m("nodes", l0.a(g30.a()), (String) null, rVar, rVar, o27)});
        aa.m mVar34 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar35 = new aa.m("state", l0.b(a0Var), (String) null, rVar, rVar, rVar);
        j30.Companion.getClass();
        aa.r b4 = l0.b(i30.a());
        f30.Companion.getClass();
        e30.b();
        List o29 = d0Shadow.o(new aa.m[]{mVar34, mVar35, new aa.m("contexts", b4, (String) null, rVar, no.a.s(f30.b, new u0(100)), o28), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar36 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar37 = new aa.m("committedDate", l0.b(n7.a()), (String) null, rVar, rVar, rVar);
        q0 a13 = e30.a();
        k71.k.g(a13, "type");
        List o30 = d0Shadow.o(new aa.m[]{mVar36, mVar37, new aa.m("statusCheckRollup", a13, (String) null, rVar, rVar, o29), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar38 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        s4.Companion.getClass();
        List o32 = d0Shadow.o(new aa.m[]{mVar38, new aa.m("commit", l0.b(r4.a()), (String) null, rVar, rVar, o30), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.m mVar39 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        aa.m mVar40 = new aa.m("totalCount", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        ps.Companion.getClass();
        List o33 = d0Shadow.o(new aa.m[]{mVar39, mVar40, new aa.m("nodes", l0.a(ps.a), (String) null, rVar, rVar, o32)});
        wt.Companion.getClass();
        aa.m mVar41 = new aa.m("state", l0.b(wt.s), (String) null, rVar, rVar, rVar);
        x a14 = n7.a();
        k71.k.g(a14, "type");
        List o34 = d0Shadow.o(new aa.m[]{mVar41, new aa.m("submittedAt", a14, (String) null, rVar, rVar, rVar), new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar), new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar)});
        aa.s mVar42 = new aa.m("__typename", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar43 = new aa.m("url", l0.b(g50.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar44 = new aa.m("id", l0.b(sd.a()), (String) null, rVar, rVar, rVar);
        ld.Companion.getClass();
        aa.s mVar45 = new aa.m("headRefOid", l0.b(ld.a), (String) null, rVar, rVar, rVar);
        jx.Companion.getClass();
        q0 a15 = ix.a();
        k71.k.g(a15, "type");
        aa.s mVar46 = new aa.m("headRepository", a15, (String) null, rVar, rVar, o);
        q0 a16 = ix.a();
        k71.k.g(a16, "type");
        aa.s mVar47 = new aa.m("baseRepository", a16, (String) null, rVar, rVar, o2);
        aa.s mVar48 = new aa.m("title", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        zd.Companion.getClass();
        aa.s mVar49 = new aa.m("titleHTML", l0.b(yd.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar50 = new aa.m("createdAt", l0.b(n7.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar51 = new aa.m("viewerCanDeleteHeadRef", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar52 = new aa.m("viewerDidAuthor", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar53 = new aa.m("viewerCanChangeBaseBranch", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar54 = new aa.m("locked", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        pz0.l.Companion.getClass();
        j0 a17 = pz0.k.a();
        k71.k.g(a17, "type");
        aa.s mVar55 = new aa.m("author", a17, (String) null, rVar, rVar, o4);
        x a18 = od.a();
        k71.k.g(a18, "type");
        aa.s mVar56 = new aa.m("isReadByViewer", a18, (String) null, rVar, rVar, rVar);
        aa.r b5 = l0.b(yd.a());
        hs.Companion.getClass();
        gs.b();
        a81.t tVar = hs.b;
        Boolean bool = Boolean.TRUE;
        aa.k kVar = new aa.k(tVar, new u0(bool));
        gs.c();
        aa.k kVar2 = new aa.k(hs.c, new u0(bool));
        gs.d();
        aa.k kVar3 = new aa.k(hs.d, new u0(bool));
        gs.e();
        a81.t tVar2 = hs.e;
        Boolean bool2 = Boolean.FALSE;
        aa.k kVar4 = new aa.k(tVar2, new u0(bool2));
        gs.f();
        aa.k kVar5 = new aa.k(hs.f, new u0(bool2));
        gs.g();
        aa.s mVar57 = new aa.m("bodyHTML", b5, "bodyHtml", rVar, d0Shadow.o(new aa.k[]{kVar, kVar2, kVar3, kVar4, kVar5, new aa.k(hs.g, new u0(bool))}), rVar);
        aa.s mVar58 = new aa.m("number", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        List o35 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list6 = zp0.a.a;
        aa.s c = no.a.c(list6, "selections", "Comment", o35, list6);
        List o36 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "Release", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List list7 = hu0.a.a;
        aa.s c2 = no.a.c(list7, "selections", "Reactable", o36, list7);
        List o37 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "Issue", "IssueComment", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisoryComment"});
        List list8 = ht0.a.a;
        aa.s c3 = no.a.c(list8, "selections", "OrgBlockable", o37, list8);
        List o38 = d0Shadow.o(new String[]{"Issue", "PullRequest"});
        List a19 = fp0.b.a();
        aa.s c4 = no.a.c(a19, "selections", "Assignable", o38, a19);
        gu.Companion.getClass();
        aa.s mVar59 = new aa.m("state", l0.b(gu.s), "pullRequestState", rVar, rVar, rVar);
        aa.s mVar60 = new aa.m("changedFiles", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar61 = new aa.m("additions", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        aa.s mVar62 = new aa.m("deletions", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        si.Companion.getClass();
        aa.s mVar63 = new aa.m("mergeStateStatus", l0.b(si.s), (String) null, rVar, rVar, rVar);
        j0 a20 = pz0.k.a();
        k71.k.g(a20, "type");
        aa.s mVar64 = new aa.m("mergedBy", a20, (String) null, rVar, rVar, o6);
        q0 a22 = r4.a();
        k71.k.g(a22, "type");
        aa.s mVar65 = new aa.m("mergeCommit", a22, (String) null, rVar, rVar, o7);
        ki.Companion.getClass();
        q0 q0Var3 = ki.c;
        k71.k.g(q0Var3, "type");
        aa.s mVar66 = new aa.m("mergeQueue", q0Var3, (String) null, rVar, rVar, o8);
        oi.Companion.getClass();
        q0 q0Var4 = oi.a;
        k71.k.g(q0Var4, "type");
        aa.s mVar67 = new aa.m("mergeQueueEntry", q0Var4, (String) null, rVar, rVar, o9);
        ot.Companion.getClass();
        a0 a23 = nt.a();
        k71.k.g(a23, "type");
        aa.s mVar68 = new aa.m("reviewDecision", a23, (String) null, rVar, rVar, rVar);
        aa.s mVar69 = new aa.m("isDraft", l0.b(od.a()), (String) null, rVar, rVar, rVar);
        pz.Companion.getClass();
        aa.r b6 = l0.b(oz.a());
        gs.l();
        aa.s mVar70 = new aa.m("requiredStatusChecks", b6, (String) null, rVar, no.a.s(hs.x, new u0(25)), o12);
        mv.Companion.getClass();
        q0 q0Var5 = mv.e;
        k71.k.g(q0Var5, "type");
        aa.s mVar71 = new aa.m("baseRef", q0Var5, (String) null, rVar, rVar, o14);
        aa.s mVar72 = new aa.m("baseRefName", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        k71.k.g(q0Var5, "type");
        aa.s mVar73 = new aa.m("headRef", q0Var5, (String) null, rVar, rVar, o15);
        aa.s mVar74 = new aa.m("headRefName", l0.b(wd.a()), (String) null, rVar, rVar, rVar);
        List o39 = d0Shadow.o(new String[]{"Discussion", "Issue", "PullRequest"});
        List a24 = ds0.a.a();
        aa.s c5 = no.a.c(a24, "selections", "Labelable", o39, a24);
        yi.Companion.getClass();
        q0 q0Var6 = yi.a;
        k71.k.g(q0Var6, "type");
        aa.s mVar75 = new aa.m("milestone", q0Var6, (String) null, rVar, rVar, o16);
        b00.Companion.getClass();
        q0 a25 = a00.a();
        k71.k.g(a25, "type");
        gs.m();
        aa.s mVar76 = new aa.m("reviewRequests", a25, (String) null, rVar, no.a.s(hs.y, new u0(25)), n6);
        mt.Companion.getClass();
        q0 q0Var7 = mt.a;
        k71.k.g(q0Var7, "type");
        gs.k();
        aa.s mVar77 = new aa.m("latestReviews", q0Var7, (String) null, rVar, no.a.s(hs.r, new u0(25)), n8);
        k71.k.g(q0Var7, "type");
        gs.i();
        aa.k kVar6 = new aa.k(hs.p, new u0(25));
        gs.j();
        aa.s mVar78 = new aa.m("latestOpinionatedReviews", q0Var7, (String) null, rVar, d0Shadow.o(new aa.k[]{kVar6, new aa.k(hs.q, new u0(bool))}), n9);
        h40.Companion.getClass();
        aa.s mVar79 = new aa.m("suggestedReviewers", l0.b(l0.a(g40.a())), (String) null, rVar, rVar, o20);
        aa.s mVar80 = new aa.m("actionRequiredWorkflowRunCount", l0.b(ud.a()), (String) null, rVar, rVar, rVar);
        ts.Companion.getClass();
        aa.r b7 = l0.b(ts.a);
        gs.h();
        aa.s mVar81 = new aa.m("commits", b7, (String) null, rVar, no.a.s(hs.l, new u0(1)), o33);
        List n10 = d0Shadow.n("PullRequest");
        List a26 = js0.a.a();
        aa.s c6 = no.a.c(a26, "selections", "PullRequest", n10, a26);
        List o40 = d0Shadow.o(new String[]{"CommitComment", "Discussion", "DiscussionComment", "GistComment", "Issue", "IssueComment", "Project", "ProjectNext", "ProjectV2", "PullRequest", "PullRequestReview", "PullRequestReviewComment", "RepositoryAdvisory", "RepositoryAdvisoryComment", "TeamDiscussion", "TeamDiscussionComment"});
        List a27 = cw0.a.a();
        aa.s c7 = no.a.c(a27, "selections", "Updatable", o40, a27);
        List n12 = d0Shadow.n("PullRequest");
        List a28 = q.a();
        aa.s c8 = no.a.c(a28, "selections", "PullRequest", n12, a28);
        k71.k.g(q0Var2, "type");
        aa.s mVar82 = new aa.m("viewerLatestReview", q0Var2, (String) null, rVar, rVar, o34);
        List n13 = d0Shadow.n("PullRequest");
        List list9 = a.a;
        a = d0Shadow.o(new aa.s[]{mVar42, mVar43, mVar44, mVar45, mVar46, mVar47, mVar48, mVar49, mVar50, mVar51, mVar52, mVar53, mVar54, mVar55, mVar56, mVar57, mVar58, c, c2, c3, c4, mVar59, mVar60, mVar61, mVar62, mVar63, mVar64, mVar65, mVar66, mVar67, mVar68, mVar69, mVar70, mVar71, mVar72, mVar73, mVar74, c5, mVar75, mVar76, mVar77, mVar78, mVar79, mVar80, mVar81, c6, c7, c8, mVar82, no.a.c(list9, "selections", "PullRequest", n13, list9), new aa.m("viewerCanReopen", l0.b(od.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanMergeAsAdmin", l0.b(od.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanAssign", l0.b(od.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanLabel", l0.b(od.a()), (String) null, rVar, rVar, rVar), new aa.m("viewerCanUpdateBranch", l0.b(od.a()), (String) null, rVar, rVar, rVar)});
    }
}
