package hb0;

import aa.a0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import fa0.j;
import hc0.ab;
import hc0.ap;
import hc0.bb;
import hc0.cb;
import hc0.cq;
import hc0.db;
import hc0.di;
import hc0.dq;
import hc0.dw;
import hc0.eb;
import hc0.ev;
import hc0.ew;
import hc0.fb;
import hc0.fm;
import hc0.g6;
import hc0.h6;
import hc0.hb;
import hc0.i9;
import hc0.ih;
import hc0.j2;
import hc0.jc;
import hc0.ji;
import hc0.jz;
import hc0.kz;
import hc0.lc;
import hc0.m00;
import hc0.oh;
import hc0.p2;
import hc0.qh;
import hc0.th;
import hc0.v2;
import hc0.vh;
import hc0.w8;
import hc0.wa;
import hc0.xa;
import hc0.xh;
import hc0.zo;
import java.util.List;
import k71.k;
import sy.d0;
import v8.l0;
import x61.l;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        xa.Companion.getClass();
        r b = l0.b(xa.a);
        x61.r rVar = x61.r.r;
        m mVar = new m("hasNextPage", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar = fb.a;
        k.g(xVar, "type");
        List r = l.r(new m[]{mVar, new m("endCursor", xVar, (String) null, rVar, rVar, rVar)});
        s mVar2 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r2 = l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = f30.b.a;
        s c = no.a.c(list, "selections", "Actor", r2, list);
        s mVar3 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        bb.Companion.getClass();
        x xVar2 = bb.a;
        List r3 = l.r(new s[]{mVar2, c, mVar3, new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar4 = new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar);
        List r4 = l.r(new String[]{"Achievement", "AchievementTier", "AddedToProjectEvent", "App", "AssignedEvent", "AutoMergeDisabledEvent", "AutoMergeEnabledEvent", "AutoRebaseEnabledEvent", "AutoSquashEnabledEvent", "AutomaticBaseChangeFailedEvent", "AutomaticBaseChangeSucceededEvent", "BaseRefChangedEvent", "BaseRefDeletedEvent", "BaseRefForcePushedEvent", "Blob", "Bot", "BranchProtectionRule", "BypassForcePushAllowance", "BypassPullRequestAllowance", "CWE", "CheckRun", "CheckSuite", "ClosedEvent", "CodeOfConduct", "CommentDeletedEvent", "Commit", "CommitComment", "CommitCommentThread", "Comparison", "ConnectedEvent", "ConvertToDraftEvent", "ConvertedNoteToIssueEvent", "ConvertedToDiscussionEvent", "CrossReferencedEvent", "DemilestonedEvent", "DeployKey", "DeployedEvent", "Deployment", "DeploymentEnvironmentChangedEvent", "DeploymentReview", "DeploymentStatus", "DisconnectedEvent", "Discussion", "DiscussionCategory", "DiscussionComment", "DiscussionPoll", "DiscussionPollOption", "DraftIssue", "Enterprise", "EnterpriseAdministratorInvitation", "EnterpriseIdentityProvider", "EnterpriseRepositoryInfo", "EnterpriseServerInstallation", "EnterpriseServerUserAccount", "EnterpriseServerUserAccountEmail", "EnterpriseServerUserAccountsUpload", "EnterpriseUserAccount", "Environment", "ExternalIdentity", "Gist", "GistComment", "HeadRefDeletedEvent", "HeadRefForcePushedEvent", "HeadRefRestoredEvent", "IpAllowListEntry", "Issue", "IssueComment", "Label", "LabeledEvent", "Language", "License", "LinkedBranch", "LockedEvent", "Mannequin", "MarkedAsDuplicateEvent", "MembersCanDeleteReposClearAuditEntry", "MembersCanDeleteReposDisableAuditEntry", "MembersCanDeleteReposEnableAuditEntry", "MentionedEvent", "MergedEvent", "MigrationSource", "Milestone", "MilestonedEvent", "MobilePushNotificationSchedule", "MovedColumnsInProjectEvent", "NotificationFilter", "NotificationThread", "OauthApplicationCreateAuditEntry", "OrgAddBillingManagerAuditEntry", "OrgAddMemberAuditEntry", "OrgBlockUserAuditEntry", "OrgConfigDisableCollaboratorsOnlyAuditEntry", "OrgConfigEnableCollaboratorsOnlyAuditEntry", "OrgCreateAuditEntry", "OrgDisableOauthAppRestrictionsAuditEntry", "OrgDisableSamlAuditEntry", "OrgDisableTwoFactorRequirementAuditEntry", "OrgEnableOauthAppRestrictionsAuditEntry", "OrgEnableSamlAuditEntry", "OrgEnableTwoFactorRequirementAuditEntry", "OrgInviteMemberAuditEntry", "OrgInviteToBusinessAuditEntry", "OrgOauthAppAccessApprovedAuditEntry", "OrgOauthAppAccessDeniedAuditEntry", "OrgOauthAppAccessRequestedAuditEntry", "OrgRemoveBillingManagerAuditEntry", "OrgRemoveMemberAuditEntry", "OrgRemoveOutsideCollaboratorAuditEntry", "OrgRestoreMemberAuditEntry", "OrgUnblockUserAuditEntry", "OrgUpdateDefaultRepositoryPermissionAuditEntry", "OrgUpdateMemberAuditEntry", "OrgUpdateMemberRepositoryCreationPermissionAuditEntry", "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry", "Organization", "OrganizationIdentityProvider", "OrganizationInvitation", "OrganizationMigration", "Package", "PackageFile", "PackageTag", "PackageVersion", "Patch", "PinnedDiscussion", "PinnedEvent", "PinnedIssue", "PrivateRepositoryForkingDisableAuditEntry", "PrivateRepositoryForkingEnableAuditEntry", "Project", "ProjectCard", "ProjectColumn", "ProjectNext", "ProjectNextField", "ProjectNextItem", "ProjectNextItemFieldValue", "ProjectNextIterationField", "ProjectNextSingleSelectField", "ProjectV2", "ProjectV2Field", "ProjectV2Item", "ProjectV2ItemFieldDateValue", "ProjectV2ItemFieldIterationValue", "ProjectV2ItemFieldNumberValue", "ProjectV2ItemFieldSingleSelectValue", "ProjectV2ItemFieldTextValue", "ProjectV2IterationField", "ProjectV2SingleSelectField", "ProjectV2View", "ProjectV2Workflow", "ProjectView", "PublicKey", "PullRequest", "PullRequestCommit", "PullRequestCommitCommentThread", "PullRequestReview", "PullRequestReviewComment", "PullRequestReviewThread", "PullRequestThread", "Push", "PushAllowance", "Reaction", "ReadyForReviewEvent", "Ref", "ReferencedEvent", "Release", "ReleaseAsset", "RemovedFromProjectEvent", "RenamedTitleEvent", "ReopenedEvent", "RepoAccessAuditEntry", "RepoAddMemberAuditEntry", "RepoAddTopicAuditEntry", "RepoArchivedAuditEntry", "RepoChangeMergeSettingAuditEntry", "RepoConfigDisableAnonymousGitAccessAuditEntry", "RepoConfigDisableCollaboratorsOnlyAuditEntry", "RepoConfigDisableContributorsOnlyAuditEntry", "RepoConfigDisableSockpuppetDisallowedAuditEntry", "RepoConfigEnableAnonymousGitAccessAuditEntry", "RepoConfigEnableCollaboratorsOnlyAuditEntry", "RepoConfigEnableContributorsOnlyAuditEntry", "RepoConfigEnableSockpuppetDisallowedAuditEntry", "RepoConfigLockAnonymousGitAccessAuditEntry", "RepoConfigUnlockAnonymousGitAccessAuditEntry", "RepoCreateAuditEntry", "RepoDestroyAuditEntry", "RepoRemoveMemberAuditEntry", "RepoRemoveTopicAuditEntry", "Repository", "RepositoryAdvisory", "RepositoryAdvisoryComment", "RepositoryDependabotAlertsThread", "RepositoryInvitation", "RepositoryMigration", "RepositoryRule", "RepositoryTopic", "RepositoryVisibilityChangeDisableAuditEntry", "RepositoryVisibilityChangeEnableAuditEntry", "RepositoryVulnerabilityAlert", "RequiredStatusCheck", "ReviewDismissalAllowance", "ReviewDismissedEvent", "ReviewRequest", "ReviewRequestRemovedEvent", "ReviewRequestedEvent", "SavedReply", "SearchShortcut", "SecurityAdvisory", "Status", "StatusCheckRollup", "StatusContext", "SubscribedEvent", "Tag", "Team", "TeamAddMemberAuditEntry", "TeamAddRepositoryAuditEntry", "TeamChangeParentTeamAuditEntry", "TeamDashboard", "TeamDiscussion", "TeamDiscussionComment", "TeamRemoveMemberAuditEntry", "TeamRemoveRepositoryAuditEntry", "TeamSearchShortcut", "Topic", "TransferredEvent", "Tree", "UnassignedEvent", "UnlabeledEvent", "UnlockedEvent", "UnmarkedAsDuplicateEvent", "UnpinnedEvent", "UnsubscribedEvent", "User", "UserBlockedEvent", "UserContentEdit", "UserDashboard", "UserList", "UserStatus", "VerifiableDomain", "Workflow", "WorkflowRun", "WorkflowRunFile"});
        List list2 = ka0.a.a;
        s c2 = no.a.c(list2, "selections", "Node", r4, list2);
        ev.Companion.getClass();
        a0 a0Var = ev.s;
        k.g(a0Var, "type");
        List r5 = l.r(new s[]{mVar4, c2, new m("viewerSubscription", a0Var, (String) null, rVar, rVar, rVar)});
        List r6 = l.r(new m[]{new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar5 = new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        List r7 = l.r(new m[]{mVar5, new m("owner", l0.b(dq.a), (String) null, rVar, rVar, r6), new m("name", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        m mVar6 = new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar);
        k.g(xVar, "type");
        List r8 = l.r(new m[]{mVar6, new m("name", xVar, "userName", rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = l.r(new m[]{new m("login", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        di.Companion.getClass();
        List o = d0.o(new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new n("Subscribable", d0.o("Commit", "Discussion", "Issue", "PullRequest", "Repository", "Team", "TeamDiscussion"), r5), new n("Repository", d0.n("Repository"), r7), new n("User", d0.n("User"), r8), new n("Team", d0.n("Team"), d0.o(new m("organization", l0.b(di.m), (String) null, rVar, rVar, r9), new m("slug", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("id", l0.b(xVar2), (String) null, rVar, rVar, rVar))), new n("Organization", d0.n("Organization"), d0.o(new m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar))));
        m mVar7 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar8 = new m("abbreviatedOid", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        List o2 = d0.o(mVar7, mVar8, new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar));
        List o3 = d0.o(new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar));
        List o4 = d0.o(new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar));
        m mVar9 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar10 = new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        j2.Companion.getClass();
        a0 a0Var2 = j2.s;
        k.g(a0Var2, "type");
        m mVar11 = new m("conclusion", a0Var2, (String) null, rVar, rVar, rVar);
        p2.Companion.getClass();
        List o5 = d0.o(mVar9, mVar10, mVar11, new m("status", l0.b(p2.s), (String) null, rVar, rVar, rVar));
        List o6 = d0.o(new m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        List o7 = d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        m mVar12 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar13 = new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        db.Companion.getClass();
        m mVar14 = new m("runNumber", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        m00.Companion.getClass();
        m mVar15 = new m("workflow", l0.b(m00.c), (String) null, rVar, rVar, o6);
        v2.Companion.getClass();
        List o8 = d0.o(mVar12, mVar13, mVar14, mVar15, new m("checkSuite", l0.b(v2.f), (String) null, rVar, rVar, o7));
        List o9 = d0.o(new m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(cq.a()), (String) null, rVar, rVar, d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(dw.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        m mVar16 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar17 = new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        m mVar18 = new m("number", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        jc.Companion.getClass();
        m mVar19 = new m("state", l0.b(jc.s), "issueState", rVar, rVar, rVar);
        ap.Companion.getClass();
        m mVar20 = new m("repository", l0.b(zo.a()), (String) null, rVar, rVar, o9);
        lc.Companion.getClass();
        a0 a0Var3 = lc.s;
        k.g(a0Var3, "type");
        List o11 = d0.o(mVar16, mVar17, mVar18, mVar19, mVar20, new m("stateReason", a0Var3, (String) null, rVar, rVar, rVar), new m("titleHTML", l0.b(eb.a()), "titleHTMLString", rVar, rVar, rVar));
        List o12 = d0.o(new m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(cq.a()), (String) null, rVar, rVar, d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(dw.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        m mVar21 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar22 = new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        m mVar23 = new m("isDraft", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        m mVar24 = new m("number", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        fm.Companion.getClass();
        m mVar25 = new m("state", l0.b(fm.s), "pullRequestState", rVar, rVar, rVar);
        m mVar26 = new m("repository", l0.b(zo.a()), (String) null, rVar, rVar, o12);
        hb.Companion.getClass();
        List o13 = d0.o(mVar21, mVar22, mVar23, mVar24, mVar25, mVar26, new m("titleHTML", l0.b(hb.a), (String) null, rVar, rVar, rVar));
        List o14 = d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("tagName", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar), new m("repository", l0.b(zo.a()), (String) null, rVar, rVar, d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(cq.a()), (String) null, rVar, rVar, d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(dw.a()), (String) null, rVar, rVar, rVar))), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar))));
        List o15 = d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(dw.a()), (String) null, rVar, rVar, rVar));
        List o16 = d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("permalink", l0.b(dw.a()), (String) null, rVar, rVar, rVar));
        List o17 = d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar));
        List o18 = d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        List o19 = d0.o(new m("name", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("owner", l0.b(cq.a()), (String) null, rVar, rVar, d0.o(new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("login", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new m("avatarUrl", l0.b(dw.a()), (String) null, rVar, rVar, rVar))), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        m mVar27 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar28 = new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        m mVar29 = new m("number", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        i9.Companion.getClass();
        a0 a0Var4 = i9.s;
        k.g(a0Var4, "type");
        m mVar30 = new m("stateReason", a0Var4, "discussionStateReason", rVar, rVar, rVar);
        w8.Companion.getClass();
        q0 q0Var = w8.c;
        k.g(q0Var, "type");
        List o21 = d0.o(mVar27, mVar28, mVar29, mVar30, new m("answer", q0Var, (String) null, rVar, rVar, o18), new m("repository", l0.b(zo.a()), (String) null, rVar, rVar, o19));
        m mVar31 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        x a2 = dw.a();
        k.g(a2, "type");
        List o22 = d0.o(mVar31, new m("notificationsPermalink", a2, (String) null, rVar, rVar, rVar));
        m mVar32 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        x a3 = dw.a();
        k.g(a3, "type");
        List o23 = d0.o(new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar), new n("Commit", d0.n("Commit"), o2), new n("Gist", d0.n("Gist"), o3), new n("TeamDiscussion", d0.n("TeamDiscussion"), o4), new n("CheckSuite", d0.n("CheckSuite"), o5), new n("WorkflowRun", d0.n("WorkflowRun"), o8), new n("Issue", d0.n("Issue"), o11), new n("PullRequest", d0.n("PullRequest"), o13), new n("Release", d0.n("Release"), o14), new n("RepositoryInvitation", d0.n("RepositoryInvitation"), o15), new n("RepositoryVulnerabilityAlert", d0.n("RepositoryVulnerabilityAlert"), o16), new n("RepositoryAdvisory", d0.n("RepositoryAdvisory"), o17), new n("Discussion", d0.n("Discussion"), o21), new n("RepositoryDependabotAlertsThread", d0.n("RepositoryDependabotAlertsThread"), o22), new n("SecurityAdvisory", d0.n("SecurityAdvisory"), d0.o(mVar32, new m("notificationsPermalink", a3, (String) null, rVar, rVar, rVar))));
        m mVar33 = new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar);
        m mVar34 = new m("threadType", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        m mVar35 = new m("title", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        m mVar36 = new m("isUnread", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        m mVar37 = new m("unreadItemsCount", l0.b(cb.a()), (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        m mVar38 = new m("lastUpdatedAt", l0.b(g6.a()), (String) null, rVar, rVar, rVar);
        th.Companion.getClass();
        m mVar39 = new m("subscriptionStatus", l0.b(th.s), (String) null, rVar, rVar, rVar);
        kz.Companion.getClass();
        q0 q0Var2 = kz.O;
        k.g(q0Var2, "type");
        m mVar40 = new m("summaryItemAuthor", q0Var2, (String) null, rVar, rVar, r3);
        x a4 = eb.a();
        k.g(a4, "type");
        m mVar41 = new m("summaryItemBody", a4, (String) null, rVar, rVar, rVar);
        m mVar42 = new m("isArchived", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        m mVar43 = new m("isSaved", l0.b(wa.a()), (String) null, rVar, rVar, rVar);
        m mVar44 = new m("url", l0.b(dw.a()), (String) null, rVar, rVar, rVar);
        vh.Companion.getClass();
        m mVar45 = new m("list", l0.b(vh.a), (String) null, rVar, rVar, o);
        ih.Companion.getClass();
        a0 a0Var5 = ih.s;
        k.g(a0Var5, "type");
        m mVar46 = new m("reason", a0Var5, (String) null, rVar, rVar, rVar);
        xh.Companion.getClass();
        List o24 = d0.o(mVar33, mVar34, mVar35, mVar36, mVar37, mVar38, mVar39, mVar40, mVar41, mVar42, mVar43, mVar44, mVar45, mVar46, new m("subject", l0.b(xh.a), (String) null, rVar, rVar, o23), new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar));
        ji.Companion.getClass();
        m mVar47 = new m("pageInfo", l0.b(ji.a), (String) null, rVar, rVar, r);
        oh.Companion.getClass();
        List o25 = d0.o(mVar47, new m("nodes", l0.a(oh.a), (String) null, rVar, rVar, o24));
        s mVar48 = new m("__typename", l0.b(eb.a()), (String) null, rVar, rVar, rVar);
        List n = d0.n("User");
        List a5 = j.a();
        s c3 = no.a.c(a5, "selections", "User", n, a5);
        qh.Companion.getClass();
        r b2 = l0.b(qh.a);
        jz jzVar = kz.Companion;
        aa.k kVar = new aa.k(kz.p, new u0(new t("after")));
        jz jzVar2 = kz.Companion;
        aa.k kVar2 = new aa.k(kz.q, new u0(new t("filterBy")));
        jz jzVar3 = kz.Companion;
        aa.k kVar3 = new aa.k(kz.r, new u0(new t("first")));
        jz jzVar4 = kz.Companion;
        a = d0.n(new m("viewer", l0.b(q0Var2), (String) null, rVar, rVar, d0.o(mVar48, c3, new m("notificationThreads", b2, (String) null, rVar, d0.o(kVar, kVar2, kVar3, new aa.k(kz.s, new u0(new t("query")))), o25), new m("id", l0.b(ab.a()), (String) null, rVar, rVar, rVar))));
    }
}
