package xt0;

import java.time.ZonedDateTime;
import java.util.ArrayList;
import pz0.gu;
import pz0.ot;
import pz0.si;

/* loaded from: /home/user/work/p/classes4.dex */
public final class u5 implements aa.h0 {
    public final ot A;
    public final boolean B;
    public final m5 C;
    public final m4 D;
    public final String E;
    public final s4 F;
    public final String G;
    public final a5 H;
    public final n5 I;
    public final v4 J;
    public final u4 K;
    public final ArrayList L;
    public final int M;
    public final q4 N;
    public final r5 O;
    public final boolean P;
    public final boolean Q;
    public final boolean R;
    public final boolean S;
    public final boolean T;
    public final yp0.c U;
    public final gu0.c V;
    public final gt0.a W;
    public final ep0.i X;
    public final cs0.j Y;
    public final is0.e Z;
    public final String a;
    public final bw0.a a0;
    public final String b;
    public final s7 b0;
    public final String c;
    public final b c0;
    public final String d;
    public final t4 e;
    public final n4 f;
    public final String g;
    public final String h;
    public final ZonedDateTime i;
    public final boolean j;
    public final boolean k;
    public final boolean l;
    public final boolean m;
    public final l4 n;
    public final Boolean o;
    public final String p;
    public final int q;
    public final gu r;
    public final int s;
    public final int t;
    public final int u;
    public final si v;
    public final z4 w;
    public final w4 x;
    public final x4 y;
    public final y4 z;

    public u5(String str, String str2, String str3, String str4, t4 t4Var, n4 n4Var, String str5, String str6, ZonedDateTime zonedDateTime, boolean z, boolean z2, boolean z3, boolean z4, l4 l4Var, Boolean bool, String str7, int i, gu guVar, int i2, int i3, int i4, si siVar, z4 z4Var, w4 w4Var, x4 x4Var, y4 y4Var, ot otVar, boolean z5, m5 m5Var, m4 m4Var, String str8, s4 s4Var, String str9, a5 a5Var, n5 n5Var, v4 v4Var, u4 u4Var, ArrayList arrayList, int i5, q4 q4Var, r5 r5Var, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, yp0.c cVar, gu0.c cVar2, gt0.a aVar, ep0.i iVar, cs0.j jVar, is0.e eVar, bw0.a aVar2, s7 s7Var, b bVar) {
        this.a = str;
        this.b = str2;
        this.c = str3;
        this.d = str4;
        this.e = t4Var;
        this.f = n4Var;
        this.g = str5;
        this.h = str6;
        this.i = zonedDateTime;
        this.j = z;
        this.k = z2;
        this.l = z3;
        this.m = z4;
        this.n = l4Var;
        this.o = bool;
        this.p = str7;
        this.q = i;
        this.r = guVar;
        this.s = i2;
        this.t = i3;
        this.u = i4;
        this.v = siVar;
        this.w = z4Var;
        this.x = w4Var;
        this.y = x4Var;
        this.z = y4Var;
        this.A = otVar;
        this.B = z5;
        this.C = m5Var;
        this.D = m4Var;
        this.E = str8;
        this.F = s4Var;
        this.G = str9;
        this.H = a5Var;
        this.I = n5Var;
        this.J = v4Var;
        this.K = u4Var;
        this.L = arrayList;
        this.M = i5;
        this.N = q4Var;
        this.O = r5Var;
        this.P = z6;
        this.Q = z7;
        this.R = z8;
        this.S = z9;
        this.T = z10;
        this.U = cVar;
        this.V = cVar2;
        this.W = aVar;
        this.X = iVar;
        this.Y = jVar;
        this.Z = eVar;
        this.a0 = aVar2;
        this.b0 = s7Var;
        this.c0 = bVar;
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof u5)) {
            return false;
        }
        u5 u5Var = (u5) obj;
        return this.a.equals(u5Var.a) && this.b.equals(u5Var.b) && this.c.equals(u5Var.c) && this.d.equals(u5Var.d) && k71.k.b(this.e, u5Var.e) && k71.k.b(this.f, u5Var.f) && this.g.equals(u5Var.g) && this.h.equals(u5Var.h) && this.i.equals(u5Var.i) && this.j == u5Var.j && this.k == u5Var.k && this.l == u5Var.l && this.m == u5Var.m && k71.k.b(this.n, u5Var.n) && k71.k.b(this.o, u5Var.o) && this.p.equals(u5Var.p) && this.q == u5Var.q && this.r == u5Var.r && this.s == u5Var.s && this.t == u5Var.t && this.u == u5Var.u && this.v == u5Var.v && k71.k.b(this.w, u5Var.w) && k71.k.b(this.x, u5Var.x) && k71.k.b(this.y, u5Var.y) && k71.k.b(this.z, u5Var.z) && this.A == u5Var.A && this.B == u5Var.B && this.C.equals(u5Var.C) && k71.k.b(this.D, u5Var.D) && this.E.equals(u5Var.E) && k71.k.b(this.F, u5Var.F) && this.G.equals(u5Var.G) && k71.k.b(this.H, u5Var.H) && k71.k.b(this.I, u5Var.I) && k71.k.b(this.J, u5Var.J) && k71.k.b(this.K, u5Var.K) && this.L.equals(u5Var.L) && this.M == u5Var.M && this.N.equals(u5Var.N) && k71.k.b(this.O, u5Var.O) && this.P == u5Var.P && this.Q == u5Var.Q && this.R == u5Var.R && this.S == u5Var.S && this.T == u5Var.T && this.U.equals(u5Var.U) && this.V.equals(u5Var.V) && this.W.equals(u5Var.W) && this.X.equals(u5Var.X) && this.Y.equals(u5Var.Y) && this.Z.equals(u5Var.Z) && this.a0.equals(u5Var.a0) && this.b0.equals(u5Var.b0) && this.c0.equals(u5Var.c0);
    }

    public final int hashCode() {
        int i = com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i(this.a.hashCode() * 31, this.b, 31), this.c, 31), this.d, 31);
        t4 t4Var = this.e;
        int hashCode = (i + (t4Var == null ? 0 : t4Var.hashCode())) * 31;
        n4 n4Var = this.f;
        int e = x.i.e(x.i.e(x.i.e(x.i.e(com.github.rudroid.m0.a(this.i, com.github.rudroid.copilot.h1.i(com.github.rudroid.copilot.h1.i((hashCode + (n4Var == null ? 0 : n4Var.hashCode())) * 31, this.g, 31), this.h, 31), 31), 31, this.j), 31, this.k), 31, this.l), 31, this.m);
        l4 l4Var = this.n;
        int hashCode2 = (e + (l4Var == null ? 0 : l4Var.hashCode())) * 31;
        Boolean bool = this.o;
        int hashCode3 = (this.v.hashCode() + a0.s0.b(this.u, a0.s0.b(this.t, a0.s0.b(this.s, (this.r.hashCode() + a0.s0.b(this.q, com.github.rudroid.copilot.h1.i((hashCode2 + (bool == null ? 0 : bool.hashCode())) * 31, this.p, 31), 31)) * 31, 31), 31), 31)) * 31;
        z4 z4Var = this.w;
        int hashCode4 = (hashCode3 + (z4Var == null ? 0 : z4Var.hashCode())) * 31;
        w4 w4Var = this.x;
        int hashCode5 = (hashCode4 + (w4Var == null ? 0 : w4Var.hashCode())) * 31;
        x4 x4Var = this.y;
        int hashCode6 = (hashCode5 + (x4Var == null ? 0 : x4Var.hashCode())) * 31;
        y4 y4Var = this.z;
        int hashCode7 = (hashCode6 + (y4Var == null ? 0 : y4Var.hashCode())) * 31;
        ot otVar = this.A;
        int hashCode8 = (this.C.hashCode() + x.i.e((hashCode7 + (otVar == null ? 0 : otVar.hashCode())) * 31, 31, this.B)) * 31;
        m4 m4Var = this.D;
        int i2 = com.github.rudroid.copilot.h1.i((hashCode8 + (m4Var == null ? 0 : m4Var.hashCode())) * 31, this.E, 31);
        s4 s4Var = this.F;
        int i3 = com.github.rudroid.copilot.h1.i((i2 + (s4Var == null ? 0 : s4Var.hashCode())) * 31, this.G, 31);
        a5 a5Var = this.H;
        int hashCode9 = (i3 + (a5Var == null ? 0 : a5Var.hashCode())) * 31;
        n5 n5Var = this.I;
        int hashCode10 = (hashCode9 + (n5Var == null ? 0 : n5Var.hashCode())) * 31;
        v4 v4Var = this.J;
        int hashCode11 = (hashCode10 + (v4Var == null ? 0 : v4Var.hashCode())) * 31;
        u4 u4Var = this.K;
        int hashCode12 = (this.N.hashCode() + a0.s0.b(this.M, no.a.b(this.L, (hashCode11 + (u4Var == null ? 0 : u4Var.hashCode())) * 31, 31), 31)) * 31;
        r5 r5Var = this.O;
        return this.c0.hashCode() + ((this.b0.hashCode() + ((this.a0.hashCode() + ((this.Z.hashCode() + ((this.Y.hashCode() + ((this.X.hashCode() + ((this.W.hashCode() + ((this.V.hashCode() + ((this.U.hashCode() + x.i.e(x.i.e(x.i.e(x.i.e(x.i.e((hashCode12 + (r5Var != null ? r5Var.hashCode() : 0)) * 31, 31, this.P), 31, this.Q), 31, this.R), 31, this.S), 31, this.T)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31)) * 31);
    }

    public final String toString() {
        StringBuilder o = a0.s0.o("RepositoryNodeFragmentPullRequest(__typename=", this.a, ", url=", this.b, ", id=");
        f1.e.x(o, this.c, ", headRefOid=", this.d, ", headRepository=");
        o.append(this.e);
        o.append(", baseRepository=");
        o.append(this.f);
        o.append(", title=");
        f1.e.x(o, this.g, ", titleHTML=", this.h, ", createdAt=");
        com.github.rudroid.m0.v(", viewerCanDeleteHeadRef=", ", viewerDidAuthor=", o, this.i, this.j);
        com.github.rudroid.m0.A(o, this.k, ", viewerCanChangeBaseBranch=", this.l, ", locked=");
        o.append(this.m);
        o.append(", author=");
        o.append(this.n);
        o.append(", isReadByViewer=");
        o.append(this.o);
        o.append(", bodyHtml=");
        o.append(this.p);
        o.append(", number=");
        o.append(this.q);
        o.append(", pullRequestState=");
        o.append(this.r);
        o.append(", changedFiles=");
        a0.s0.z(o, this.s, ", additions=", this.t, ", deletions=");
        o.append(this.u);
        o.append(", mergeStateStatus=");
        o.append(this.v);
        o.append(", mergedBy=");
        o.append(this.w);
        o.append(", mergeCommit=");
        o.append(this.x);
        o.append(", mergeQueue=");
        o.append(this.y);
        o.append(", mergeQueueEntry=");
        o.append(this.z);
        o.append(", reviewDecision=");
        o.append(this.A);
        o.append(", isDraft=");
        o.append(this.B);
        o.append(", requiredStatusChecks=");
        o.append(this.C);
        o.append(", baseRef=");
        o.append(this.D);
        o.append(", baseRefName=");
        o.append(this.E);
        o.append(", headRef=");
        o.append(this.F);
        o.append(", headRefName=");
        o.append(this.G);
        o.append(", milestone=");
        o.append(this.H);
        o.append(", reviewRequests=");
        o.append(this.I);
        o.append(", latestReviews=");
        o.append(this.J);
        o.append(", latestOpinionatedReviews=");
        o.append(this.K);
        o.append(", suggestedReviewers=");
        o.append(this.L);
        o.append(", actionRequiredWorkflowRunCount=");
        o.append(this.M);
        o.append(", commits=");
        o.append(this.N);
        o.append(", viewerLatestReview=");
        o.append(this.O);
        o.append(", viewerCanReopen=");
        o.append(this.P);
        o.append(", viewerCanMergeAsAdmin=");
        com.github.rudroid.m0.A(o, this.Q, ", viewerCanAssign=", this.R, ", viewerCanLabel=");
        com.github.rudroid.m0.A(o, this.S, ", viewerCanUpdateBranch=", this.T, ", commentFragment=");
        o.append(this.U);
        o.append(", reactionFragment=");
        o.append(this.V);
        o.append(", orgBlockableFragment=");
        o.append(this.W);
        o.append(", assigneeFragment=");
        o.append(this.X);
        o.append(", labelsFragment=");
        o.append(this.Y);
        o.append(", linkedIssues=");
        o.append(this.Z);
        o.append(", updatableFields=");
        o.append(this.a0);
        o.append(", viewerLatestReviewRequestFragment=");
        o.append(this.b0);
        o.append(", autoMergeRequestFragment=");
        o.append(this.c0);
        o.append(")");
        return o.toString();
    }
}
