package n20;

import aa.a0;
import aa.j0;
import aa.m;
import aa.n;
import aa.q0;
import aa.r;
import aa.s;
import aa.t;
import aa.u0;
import aa.x;
import hc0.ap;
import hc0.bb;
import hc0.db;
import hc0.dq;
import hc0.ew;
import hc0.fb;
import hc0.fq;
import hc0.h6;
import hc0.ji;
import hc0.jn;
import hc0.l2;
import hc0.m00;
import hc0.pm;
import hc0.q00;
import hc0.r2;
import hc0.t2;
import hc0.uu;
import hc0.v2;
import hc0.xa;
import hc0.yg;
import java.util.List;
import sy.d0;
import v8.l0;

/* loaded from: /home/user/work/p/classes3.dex */
public abstract class a {
    public static final List a;

    static {
        bb.Companion.getClass();
        x xVar = bb.a;
        r b = l0.b(xVar);
        x61.r rVar = x61.r.r;
        m mVar = new m("id", b, (String) null, rVar, rVar, rVar);
        fb.Companion.getClass();
        x xVar2 = fb.a;
        List r = x61.l.r(new m[]{mVar, new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        s mVar2 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List r2 = x61.l.r(new String[]{"Bot", "EnterpriseUserAccount", "Mannequin", "Organization", "User"});
        List list = f30.a.a;
        List r3 = x61.l.r(new s[]{mVar2, no.a.c(list, "selections", "Actor", r2, list)});
        m mVar3 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar4 = new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        dq.Companion.getClass();
        m mVar5 = new m("owner", l0.b(dq.a), (String) null, rVar, rVar, r3);
        fq.Companion.getClass();
        a0 a0Var = fq.s;
        k71.k.g(a0Var, "type");
        List r4 = x61.l.r(new m[]{mVar3, mVar4, mVar5, new m("viewerPermission", a0Var, (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r5 = x61.l.r(new m[]{new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar6 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        db.Companion.getClass();
        x xVar3 = db.a;
        m mVar7 = new m("runNumber", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        m00.Companion.getClass();
        List r6 = x61.l.r(new m[]{mVar6, mVar7, new m("workflow", l0.b(m00.c), (String) null, rVar, rVar, r5), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar8 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        ew.Companion.getClass();
        List r7 = x61.l.r(new m[]{mVar8, new m("logoUrl", l0.b(ew.a), (String) null, rVar, rVar, rVar), new m("name", l0.b(xVar2), (String) null, rVar, rVar, rVar), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        m mVar9 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        jn.Companion.getClass();
        q0 q0Var = jn.b;
        k71.k.g(q0Var, "type");
        m mVar10 = new m("branch", q0Var, (String) null, rVar, rVar, r);
        xa.Companion.getClass();
        x xVar4 = xa.a;
        m mVar11 = new m("rerunnable", l0.b(xVar4), (String) null, rVar, rVar, rVar);
        ap.Companion.getClass();
        m mVar12 = new m("repository", l0.b(ap.k0), (String) null, rVar, rVar, r4);
        q00.Companion.getClass();
        q0 q0Var2 = q00.b;
        k71.k.g(q0Var2, "type");
        m mVar13 = new m("workflowRun", q0Var2, (String) null, rVar, rVar, r6);
        hc0.l0.Companion.getClass();
        q0 q0Var3 = hc0.l0.a;
        k71.k.g(q0Var3, "type");
        List r8 = x61.l.r(new m[]{mVar9, mVar10, mVar11, mVar12, mVar13, new m("app", q0Var3, (String) null, rVar, rVar, r7), new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar)});
        List r9 = x61.l.r(new m[]{new m("hasNextPage", l0.b(xVar4), (String) null, rVar, rVar, rVar), new m("endCursor", xVar2, (String) null, rVar, rVar, rVar), new m("hasPreviousPage", l0.b(xVar4), (String) null, rVar, rVar, rVar)});
        s mVar14 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n = d0.n("CheckStep");
        List list2 = h20.a.a;
        List r11 = x61.l.r(new s[]{mVar14, no.a.c(list2, "selections", "CheckStep", n, list2)});
        m mVar15 = new m("totalCount", l0.b(xVar3), (String) null, rVar, rVar, rVar);
        ji.Companion.getClass();
        m mVar16 = new m("pageInfo", l0.b(ji.a), (String) null, rVar, rVar, r9);
        r2.Companion.getClass();
        List r12 = x61.l.r(new m[]{mVar15, mVar16, new m("nodes", l0.a(r2.a), (String) null, rVar, rVar, r11)});
        s mVar17 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        List n2 = d0.n("CheckRun");
        List list3 = h20.f.a;
        s c = no.a.c(list3, "selections", "CheckRun", n2, list3);
        v2.Companion.getClass();
        s mVar18 = new m("checkSuite", l0.b(v2.f), (String) null, rVar, rVar, r8);
        t2.Companion.getClass();
        q0 q0Var4 = t2.a;
        k71.k.g(q0Var4, "type");
        l2.Companion.getClass();
        List r13 = x61.l.r(new s[]{mVar17, c, mVar18, new m("steps", q0Var4, (String) null, rVar, x61.l.r(new aa.k[]{new aa.k(l2.c, new u0(new t("afterSteps"))), new aa.k(l2.d, new u0(new t("first")))}), r12)});
        m mVar19 = new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar);
        m mVar20 = new m("context", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        m mVar21 = new m("description", xVar2, (String) null, rVar, rVar, rVar);
        h6.Companion.getClass();
        m mVar22 = new m("createdAt", l0.b(h6.a), (String) null, rVar, rVar, rVar);
        uu.Companion.getClass();
        List r14 = x61.l.r(new m[]{mVar19, mVar20, mVar21, mVar22, new m("state", l0.b(uu.s), (String) null, rVar, rVar, rVar)});
        s mVar23 = new m("__typename", l0.b(xVar2), (String) null, rVar, rVar, rVar);
        s nVar = new n("CheckRun", d0.n("CheckRun"), r13);
        List n3 = d0.n("StatusContext");
        List list4 = h20.e.a;
        List r15 = x61.l.r(new s[]{mVar23, nVar, no.a.c(list4, "selections", "StatusContext", n3, list4), new n("RequiredStatusCheck", d0.n("RequiredStatusCheck"), r14), new m("id", l0.b(xVar), (String) null, rVar, rVar, rVar)});
        yg.Companion.getClass();
        j0 j0Var = yg.a;
        k71.k.g(j0Var, "type");
        pm.Companion.getClass();
        a = d0.n(new m("node", j0Var, (String) null, rVar, no.a.s(pm.f, new u0(new t("id"))), r15));
    }
}
